### ISSUE TITLE
Internal Database is Corrupted

### ISSUE THREAD

**Issue by andyl** [influxdata/influxdb#8216] opened 2017-03-28 04:47 UTC
Internal database is corrupted - see the forum dialog at https://community.influxdata.com/t/no-data-in--internal-db/340/6

### Bug report

System info: Influxdb 1.2.0, Ubuntu 16.04

Steps to reproduce:

1. look at the _internal database, can't view tag/field keys or values.
2. delete and recreate the database.  it works!
3. wait 10-30 minutes:  oh it is broken again!  :-(

For me it is not a big deal - I can built my own metric collection for Influx.  But it is probably important for InfluxData that this should work.

**Comment by jwilder** [comment] 2017-04-06 21:17
I'm not able to reproduce this.  Can you attach the logs from any instance where this is occurring?

**Comment by andyl** [comment] 2017-04-07 16:09
Sorry I've moved on to another project - no more time to diagnose this issue.  My workaround was to disable Influx metrics collection, delete the `_internal` database, and write a little script that polls Influx to collect metrics - works perfectly.  Hope this datapoint is useful - perhaps there is an intermittent bug or maybe I misapplied a retention rule - not sure.

**Comment by jwilder** [comment] 2017-04-07 18:50
Closing since not reproducible.  We can re-open if someone finds a way to re-produce this issue.

**Closed by jwilder** 2017-04-07 18:50 UTC
Labels: need more info
