### ISSUE TITLE
Dashboards with no title leave "Loading..." in the web browser title

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/influxdb#18998] opened 2020-07-20 21:41 UTC
![Screen Shot 2020-07-20 at 5 33 10 PM](https://user-images.githubusercontent.com/13948193/87989539-2f9b8e80-cab0-11ea-95b0-2ac85630c5fc.png)

**Comment by Asalem1** [comment] 2020-07-20 21:51
For clarity: I was unable to reproduce this on tools on Chrome (the browser that this appeared on)

**Comment by russorat** [comment] 2021-05-13 05:55
this is still an issue. 
![image](https://user-images.githubusercontent.com/4805997/118084184-1df3e200-b375-11eb-901a-111f58dc3de2.png)

**Comment by hoorayimhelping** [comment] 2021-05-21 21:09
possibly related to https://github.com/influxdata/ui/issues/1487

**Comment by ShmuelLotman** [comment] 2021-06-02 16:40
@russorat i was not able to reproduce this either, although i've checked only after the PR Bucky linked above was merged. Can you confirm this was resolved so we can close this ticket out?

**Comment by kristinarobinson** [comment] 2021-06-11 22:13
Fixed with PR.

**Closed by kristinarobinson** 2021-06-11 22:13 UTC
Labels: kind/bug, severity/sev-4, team/dumplings, team/ui, v2-prod-bug
