### ISSUE TITLE
runtime: out of memory: cannot allocate 4194304-byte block (137437052928 in use)

### ISSUE THREAD

**Issue by luogangyi** [influxdata/influxdb#6378] opened 2016-04-14 12:47 UTC
## CentOS 7.1 and Influxdb 0.11 cluster

runtime: out of memory: cannot allocate 4194304-byte block (137437052928 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x108ebaa)
        /usr/local/go/src/runtime/panic.go:491 +0xad
runtime.largeAlloc_m()
        /usr/local/go/src/runtime/malloc.c:390 +0xee
runtime.onM(0xc20840eb70)
        /usr/local/go/src/runtime/asm_amd64.s:257 +0x68
runtime.mstart()
        /usr/local/go/src/runtime/proc.c:818

goroutine 856640 [running]:
runtime.switchtoM()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc39652e750 sp=0xc39652e748
runtime.mallocgc(0x400000, 0x9e6480, 0x100000001, 0x1)
        /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc39652e800 sp=0xc39652e750
runtime.newarray(0x9e6480, 0x400000, 0xc5e8da5080)
        /usr/local/go/src/runtime/malloc.go:365 +0xc1 fp=0xc39652e838 sp=0xc39652e800
runtime.makeslice(0x9ceb60, 0x400000, 0x400000, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x15c fp=0xc39652e880 sp=0xc39652e838
github.com/influxdata/influxdb/tsdb/engine/tsm1.getBuf(0x400000, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/pools.go:17 +0x7e fp=0xc39652e8e0 sp=0xc39652e880
github.com/influxdata/influxdb/tsdb/engine/tsm1.(_WAL).writeToLog(0xc2999de000, 0x7f20a41ca3e8, 0xc28fe2b038, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/wal.go:263 +0x56 fp=0xc39652ea40 sp=0xc39652e8e0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(_WAL).WritePoints(0xc2999de000, 0xc3527cb530, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/wal.go:186 +0xa3 fp=0xc39652ea90 sp=0xc39652ea40
github.com/influxdata/influxdb/tsdb/engine/tsm1.(_Engine).WritePoints(0xc2305420b0, 0xc32d041740, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:355 +0x570 fp=0xc39652ec78 sp=0xc39652ea90
github.com/influxdata/influxdb/tsdb.(_Shard).WritePoints(0xc2b22b6c60, 0xc32d041740, 0x1, 0x1, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:286 +0x66d fp=0xc39652eea0 sp=0xc39652ec78
github.com/influxdata/influxdb/tsdb.(_Store).WriteToShard(0xc20810a0f0, 0x35, 0xc32d041740, 0x1, 0x1, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:644 +0x14e fp=0xc39652eee8 sp=0xc39652eea0
github.com/influxdata/influxdb/cluster.func·003(0x35, 0x1, 0xc32d041740, 0x1, 0x1)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:316 +0x103 fp=0xc39652efb8 sp=0xc39652eee8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc39652efc0 sp=0xc39652efb8
created by github.com/influxdata/influxdb/cluster.(_PointsWriter).writeToShard
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:352 +0x31a

goroutine 1 [chan receive, 4 minutes]:
main.(*Main).Run(0xc20803b700, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:94 +0x765
main.main()
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/main.go:45 +0xdc

goroutine 6 [syscall, 810 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 302237 [semacquire]:
sync.(_Mutex).Lock(0xc208113360)
        /usr/local/go/src/sync/mutex.go:66 +0xd3
sync.(_RWMutex).Lock(0xc208113360)
        /usr/local/go/src/sync/rwmutex.go:82 +0x33
github.com/influxdata/influxdb/tsdb.(_Shard).WritePoints(0xc2b22b6c60, 0xc32f587640, 0x1, 0x1, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:234 +0x1e6
github.com/influxdata/influxdb/tsdb.(_Store).WriteToShard(0xc20810a0f0, 0x35, 0xc32f587640, 0x1, 0x1, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:644 +0x14e
github.com/influxdata/influxdb/cluster.func·003(0x35, 0x1, 0xc32f587640, 0x1, 0x1)
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:316 +0x103
created by github.com/influxdata/influxdb/cluster.(*PointsWriter).writeToShard
        /tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:352 +0x31a

goroutine 8 [IO wait]:
net.(_pollDesc).Wait(0xc208010920, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc208010920, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).accept(0xc2080108c0, 0x0, 0x7f20bd67a0d0, 0xc361054448)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(_TCPListener).AcceptTCP(0xc20802d658, 0xc2cdc7ced8, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(_TCPListener).Accept(0xc20802d658, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdata/influxdb/tcp.(_Mux).Serve(0xc20805c780, 0x7f20bd684de8, 0xc20802d658, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdata/influxdb/tcp/mux.go:52 +0xc7
created by github.com/influxdata/influxdb/cmd/influxd/run.(*Server).Open
        /tmp/influxdb/src/github.com/influxdata/influxdb/cmd/influxd/run/server.go:389 +0x25e

goroutine 9 [IO wait, 2 minutes]:
net.(_pollDesc).Wait(0xc208010990, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc208010990, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).accept(0xc208010930, 0x0, 0x7f20bd67a0d0, 0xc3637a8ad0)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(_TCPListener).AcceptTCP(0xc20802d660, 0xc208118db8, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(_TCPListener).Accept(0xc20802d660, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(_Server).Serve(0xc208110000, 0x7f20bd684de8, 0xc20802d660, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f20bd684de8, 0xc20802d660, 0x7f20bd685f50, 0xc20805c9c0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1606 +0xa1
github.com/influxdata/influxdb/services/meta.(_Service).serve(0xc20805f360)
        /tmp/influxdb/src/github.com/influxdata/influxdb/services/meta/service.go:152 +0x7a
created by github.com/influxdata/influxdb/services/meta.(_Service).Open
        /tmp/influxdb/src/github.com/influxdata/influxdb/services/meta/service.go:127 +0xa82
## my confiuration

reporting-disabled = false
[meta]
  enabled = true
  dir = "/var/lib/influxdb/meta"
  bind-address = "172.16.216.5:8088"
  http-bind-address = "172.16.216.5:8091"
  https-enabled = false
  https-certificate = ""
  retention-autocreate = true
  election-timeout = "10s"
  heartbeat-timeout = "10s"
  leader-lease-timeout = "5s"
  commit-timeout = "5s"
  cluster-tracing = false
  raft-promotion-enabled = true
  logging-enabled = true
  pprof-enabled = false
  lease-duration = "1m0s"
[data]
  enabled = true
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  wal-logging-enabled = true
  data-logging-enabled = true
  cache-max-memory-size = 5242880000
  cache-snapshot-memory-size = 262144000
[hinted-handoff]
  enabled = true
  dir = "/var/lib/influxdb/hh"
  max-size = 10737418240
  max-age = "168h"
  retry-rate-limit = 0
  retry-interval = "1s"
  retry-max-interval = "1m"
  purge-interval = "1h"
[cluster]
[retention]
  enabled = true
  check-interval = "30m"
[shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"
[monitor]
[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
[http]
  enabled = true
  bind-address = "172.16.216.5:8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
[[graphite]]
  enabled = false
[collectd]
  enabled = false
[opentsdb]
  enabled = false
[[udp]]
  enabled = false
[continuous_queries]
  log-enabled = true
  enabled = true
# Is this a bug or I config too large memory?

**Comment by fangdejia** [comment] 2016-04-15 03:27
I have the same problem on 0.12

**Comment by toddboom** [comment] 2016-04-15 21:46
@luogangyi @fangdejia can you tell me more about the hardware configuration you're running on and what sort of data you're sending in?

**Comment by luogangyi** [comment] 2016-04-16 12:48
@toddboom I have 256GB Memory, CPU E2650 v3, SAS 900G*2 (Raid 1) .
And I am using influxdb as backend of OpenStack Gnocchi project.

**Comment by whitelynx** [comment] 2016-05-02 15:58
Possible duplicate of #6243?

**Comment by pbek** [comment] 2016-06-01 04:15
I'm adding myself to the list of people with `out of memory` problems on a Ubuntu 14.04.4 LTS VPS with 4GB RAM. InfluxDB 0.13.0 will constantly try to grab every byte of available memory when querying data for graphs in Grafana until the InfluxDB daemon dies...

**Comment by jwilder** [comment] 2016-11-17 07:03
Fixed by #7024

**Closed by jwilder** 2016-11-17 07:03 UTC
