### ISSUE TITLE
influx_tsm on conversion panic: invalid page type: 0: 0 

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6165] opened 2016-03-30 22:13 UTC
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
OS X 10.11, InfluxDB 0.11 final loaded via Homebrew. Previously running 0.9.4 and up on this box with the same data files.

__Steps to reproduce:__
```
sean@catalyst-sean:~$ /usr/local/bin/influx_tsm -nobackup ~/.influxdb/data/

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:                  /Users/sean/.influxdb/data
Databases specified:                all
Database backups enabled:           no (NOT RECOMMENDED)
Parallel mode enabled (GOMAXPROCS): no (8)

panic: invalid page type: 0: 0

goroutine 1 [running]:
panic(0x4c49a0, 0xc820011e30)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/boltdb/bolt.(*Cursor).search(0xc82004d3f0, 0xc82004d450, 0x6, 0x6, 0x3e6)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/cursor.go:256 +0x215
github.com/boltdb/bolt.(*Cursor).seek(0xc82004d3f0, 0xc82004d450, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/cursor.go:159 +0xda
github.com/boltdb/bolt.(*Bucket).Get(0xc820013000, 0xc82004d450, 0x6, 0x6, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/bucket.go:260 +0xf4
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.shardFormat.func1(0xc8200c6620, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:226 +0x14b
github.com/boltdb/bolt.(*DB).View(0xc820118380, 0xc82004d630, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/db.go:599 +0xb9
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.shardFormat(0xc820012f00, 0x31, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:236 +0x25b
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.(*Database).Shards(0xc82004d8f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:176 +0x543
main.collectShards(0xc82000bb90, 0x3, 0x3, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/main.go:245 +0x24b
main.main()
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/main.go:186 +0xdc7
```

happens on all attempts, and I haven't found any `influx_tsm` flags that change the output.

Here's a gist with the structure of my `/data` directory: https://gist.github.com/beckettsean/47011a68c5086aef8396707fc265ee55.

Happy to provide the files if desired.

**Comment by jwilder** [comment] 2016-03-30 22:15
@joelegasse @benbjohnson

**Comment by beckettsean** [comment] 2016-03-30 22:17
@joelegasse fixed by #6159?

**Comment by benbjohnson** [comment] 2016-03-30 23:33
It looks like there's a bad copy of the bolt file. It's trying to access an empty page. 

@beckettsean Are you able to isolate the error to a single database? If so can you send me the db files for that database?

**Comment by beckettsean** [comment] 2016-04-05 00:08
@benbjohnson I've only got three dbs in the system:

```
sean@catalyst-sean:~/.influxdb/data$ l
_internal/	mydb/		telegraf/
```

When I try to launch `influx_tsm` I get the same panic for all three databases:

```
sean@catalyst-sean:~$ influx_tsm -nobackup -dbs _internal ~/.influxdb/data/

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:                  /Users/sean/.influxdb/data
Databases specified:                [_internal]
Database backups enabled:           no (NOT RECOMMENDED)
Parallel mode enabled (GOMAXPROCS): no (8)

unexpected fault address 0xec7008
fatal error: fault
[signal 0xb code=0x1 addr=0xec7008 pc=0x3540e5]

goroutine 1 [running]:
runtime.throw(0x6872b8, 0x5)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc8201351c8 sp=0xc8201351b0
runtime.sigpanic()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc820135218 sp=0xc8201351c8
github.com/boltdb/bolt.(*Cursor).search(0xc8201353e0, 0xc820135440, 0x6, 0x6, 0x3e6)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/cursor.go:255 +0x55 fp=0xc8201352f0 sp=0xc820135218
github.com/boltdb/bolt.(*Cursor).seek(0xc8201353e0, 0xc820135440, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/cursor.go:159 +0xda fp=0xc820135350 sp=0xc8201352f0
github.com/boltdb/bolt.(*Bucket).Get(0xc82006ef40, 0xc820135440, 0x6, 0x6, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/bucket.go:260 +0xf4 fp=0xc820135408 sp=0xc820135350
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.shardFormat.func1(0xc8200e6620, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:226 +0x14b fp=0xc820135530 sp=0xc820135408
github.com/boltdb/bolt.(*DB).View(0xc82013c380, 0xc820135620, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/boltdb/bolt/db.go:599 +0xb9 fp=0xc820135598 sp=0xc820135530
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.shardFormat(0xc82006ee40, 0x31, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:236 +0x25b fp=0xc820135638 sp=0xc820135598
github.com/influxdata/influxdb/cmd/influx_tsm/tsdb.(*Database).Shards(0xc8201358e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/database.go:176 +0x543 fp=0xc820135838 sp=0xc820135638
main.collectShards(0xc820077b00, 0x3, 0x3, 0x0, 0x0, 0x0)
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/main.go:245 +0x24b fp=0xc820135a10 sp=0xc820135838
main.main()
	/private/tmp/influxdb20160323-69440-pugshi/influxdb-0.11.0/src/github.com/influxdata/influxdb/cmd/influx_tsm/main.go:186 +0xdc7 fp=0xc820135f40 sp=0xc820135a10
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc820135f90 sp=0xc820135f40
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820135f98 sp=0xc820135f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1



sean@catalyst-sean:~$ influx_tsm -nobackup -dbs mydb ~/.influxdb/data/

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:                  /Users/sean/.influxdb/data
Databases specified:                [mydb]
Database backups enabled:           no (NOT RECOMMENDED)
Parallel mode enabled (GOMAXPROCS): no (8)

unexpected fault address 0xec7008
fatal error: fault
[signal 0xb code=0x1 addr=0xec7008 pc=0x3540e5]

goroutine 1 [running]:
runtime.throw(0x6872b8, 0x5)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc8201351c8 sp=0xc8201351b0
runtime.sigpanic()
<snip>


sean@catalyst-sean:~$ influx_tsm -nobackup -dbs telegraf ~/.influxdb/data/

b1 and bz1 shard conversion.
-----------------------------------
Data directory is:                  /Users/sean/.influxdb/data
Databases specified:                [telegraf]
Database backups enabled:           no (NOT RECOMMENDED)
Parallel mode enabled (GOMAXPROCS): no (8)

unexpected fault address 0xec7008
fatal error: fault
[signal 0xb code=0x1 addr=0xec7008 pc=0x3540e5]

goroutine 1 [running]:
runtime.throw(0x6872b8, 0x5)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc8201351c8 sp=0xc8201351b0
runtime.sigpanic()
<snip>
```

**Comment by beckettsean** [comment] 2016-04-05 00:12
I've got a 204MB gzipped tarball of `~/.influxdb/` from my machine. I'll slack you the dropbox link.

**Comment by objectified** [comment] 2016-06-14 12:21
Was there any resolution for this? I'm running into the (seemingly) same issue.

**Comment by jwilder** [comment] 2016-10-17 16:59
Closing this since it appears to be a corrupted bolt file and we have no way to reproduce right now.

**Closed by jwilder** 2016-10-17 16:59 UTC
Labels: area/tooling, panic
