### ISSUE TITLE
InfluxDB 2.0.1 Docker image on quay.io doesn't have arm64 build, amd64 pulled instead

### ISSUE THREAD

**Issue by phantomski77** [influxdata/influxdb#20057] opened 2020-11-16 17:59 UTC
Hi,

testing the new version 2.0.0 and 2.0.1 as per the instructions, on arm64 architecture (Rapsberry Pi 4 8GB) via:
```
 sudo docker run --name influxdb -d -p 8086:8086 quay.io/influxdb/influxdb:v2.0.1
```
Image is correctly pulled from  quay.io/influxdb/influxdb:v2.0.1, but instead of arm64 version, amd64 is used. That leads to expected error during the container's initialisation phase:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
I have tried to use various different tags, but it seems the arm64 build is not (yet) available on quay.io. The official Docker Hub repository doesn't even have any 2.x.x versions available yet.

I appreciate it's probably still too early after the new release, but would you have a timeframe in mind?

Thanks a lot.

**Comment by nottmufasa** [comment] 2020-11-21 04:55
Duplicate of #17840

**Comment by qeggs** [comment] 2020-12-05 18:51
Given that the quay.io builds don't work for arm64 yet, is there any way to get influxdb 2.X running on my raspberry pi 4 at the moment? I'm just getting started with influxdb and I won't want to begin with 1.X if the 2.X version is available (or will be soon).

**Comment by danxmoran** [comment] 2020-12-22 18:18
@qeggs our 2.0.3 release restored our ARM64 builds, you could run the binaries directly or use them to build your own Docker image. We're working on our multi-arch Docker support for 2.0.4.

**Comment by danxmoran** [comment] 2021-01-11 18:53
@phantomski77 @qeggs I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machines and let me know how it goes?

**Comment by phantomski77** [comment] 2021-01-11 21:24
Brilliant, of course I’m still interested!
It pulled ok, it is running on rPi4 now and I could do initial setup no problem, happy days!
I’ll do more testing tomorrow, but this is great news.
Thanks @danxmoran. Much appreciated.

**Comment by bertdwe** [comment] 2021-01-30 15:15
> @phantomski77 @qeggs I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machines and let me know how it goes?

did also deploy uay.io/influxdb/influxdb:nightly on rPi4/arm64 and all looks good!

**Comment by boumanb** [comment] 2021-01-31 19:56
Is not working for me at the moment (older Raspberry Pi (2B)):
```bash
pi@raspberrypi:~ $ docker run -p 8086:8086 --name influxdbnew -d quay.io/influxdb/influxdb:nightly
Unable to find image 'quay.io/influxdb/influxdb:nightly' locally
nightly: Pulling from influxdb/influxdb
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
```

**Comment by danxmoran** [comment] 2021-01-31 23:21
@boumanb that's expected, we aren't currently supporting 32-bit architectures.

**Comment by danxmoran** [comment] 2021-02-08 18:14
`quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`

**Closed by danxmoran** 2021-02-08 18:14 UTC
Labels: arch/arm, area/2.x, area/docker

**Comment by RyuunosukeDS3** [comment] 2021-06-26 21:06
> `quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`

tested on my Raspberry pi 4 And it did not work

```
docker run -d --name=influxdb -p 8086:8086 -v /tpm/testdata/influx:/root/.influxdbv2 --net=influxdb-telegraf-net quay.io/influxdb/influxdb:v2.0.4
Unable to find image 'quay.io/influxdb/influxdb:v2.0.4' locally
v2.0.4: Pulling from influxdb/influxdb
docker: no matching manifest for unknown in the manifest list entries.
```

**Comment by phantomski77** [comment] 2021-06-28 09:21
> > `quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`
> 
> tested on my Raspberry pi 4 And it did not work
> 
> ```
> docker run -d --name=influxdb -p 8086:8086 -v /tpm/testdata/influx:/root/.influxdbv2 --net=influxdb-telegraf-net quay.io/influxdb/influxdb:v2.0.4
> Unable to find image 'quay.io/influxdb/influxdb:v2.0.4' locally
> v2.0.4: Pulling from influxdb/influxdb
> docker: no matching manifest for unknown in the manifest list entries.
> ```

The InfluxDB arm64v8 Docker images are now officially hosted again at the official Docker Hub, so `influxdb` or `influxdb:latest` or `influxdb:2.0.7` will all do instead of `quay.io/influxdb/influxdb:v2.0.4` (if you specifically require 2.0.4 it’s the same, all 2.0.x tags are available there).

**Comment by RyuunosukeDS3** [comment] 2021-10-02 20:22
> > > `quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`
> > 
> > 
> > tested on my Raspberry pi 4 And it did not work
> > ```
> > docker run -d --name=influxdb -p 8086:8086 -v /tpm/testdata/influx:/root/.influxdbv2 --net=influxdb-telegraf-net quay.io/influxdb/influxdb:v2.0.4
> > Unable to find image 'quay.io/influxdb/influxdb:v2.0.4' locally
> > v2.0.4: Pulling from influxdb/influxdb
> > docker: no matching manifest for unknown in the manifest list entries.
> > ```
> 
> The InfluxDB arm64v8 Docker images are now officially hosted again at the official Docker Hub, so `influxdb` or `influxdb:latest` or `influxdb:2.0.7` will all do instead of `quay.io/influxdb/influxdb:v2.0.4` (if you specifically require 2.0.4 it’s the same, all 2.0.x tags are available there).

Sorry for the late reply, I gave up for a while and now i decided to try again. Still not working tho...

sudo docker pull influxdb:latest
latest: Pulling from library/influxdb
no matching manifest for unknown in the manifest list entries

**Comment by phantomski77** [comment] 2021-10-03 19:17
> 
> Sorry for the late reply, I gave up for a while and now i decided to try again. Still not working tho...
> 
> ```
> sudo docker pull influxdb:latest
> latest: Pulling from library/influxdb
> no matching manifest for unknown in the manifest list entries
> ```

Can you please try to run `uname -a` and `lscpu` commands on your system where you run Docker and send the results here?

**Comment by RyuunosukeDS3** [comment] 2021-10-03 20:04
> > Sorry for the late reply, I gave up for a while and now i decided to try again. Still not working tho...
> > ```
> > sudo docker pull influxdb:latest
> > latest: Pulling from library/influxdb
> > no matching manifest for unknown in the manifest list entries
> > ```
> 
> Can you please try to run `uname -a` and `lscpu` commands on your system where you run Docker and send the results here?
uname -a
Linux raspberrypi 5.10.63-v8+ #1457 SMP PREEMPT Tue Sep 28 11:27:02 BST 2021 aarch64 GNU/Linux```
```
lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               fp asimd evtstrm crc32 cpuid
```

**Comment by phantomski77** [comment] 2021-10-03 20:52
Thanks, everything seems to be ok for `arm64` / `aarch64`. Sometimes people run 32bit kernel on 64bit Raspberry.

Could you also provide output of `docker info` ? (remove private data you don’t want public).

Also please double check if you don’t have older (or different arch) image pulled already:
- list by: `docker image ps | grep influxdb`
- remove by: `docker image rm influxdb:[tag]`
- pull latest using specific tag by: `docker pull influxdb:2.0.8`
- or even more specific `2.0.8 arm64v8` digest by:
```
docker pull sha256:34caf52f34fd2e2bc83f925d7d6e180aca6b3b41971ea2d813e8d216e0c42e0e
```

**Comment by RyuunosukeDS3** [comment] 2021-10-03 22:52
> Thanks, everything seems to be ok for `arm64` / `aarch64`. Sometimes people run 32bit kernel on 64bit Raspberry.
> 
> Could you also provide output of `docker info` ? (remove private data you don’t want public).
> 
> Also please double check if you don’t have older (or different arch) image pulled already:
> 
> * list by: `docker image ps | grep influxdb`
> * remove by: `docker image rm influxdb:[tag]`
> * pull latest using specific tag by: `docker pull influxdb:2.0.8`
> * or even more specific `2.0.8 arm64v8` digest by:
> 
> ```
> docker pull influxdb@sha256:34caf52f34fd2e2bc83f925d7d6e180aca6b3b41971ea2d813e8d216e0c42e0e
> ```

Here goes Docker info:

```
sudo docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 18
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.10.63-v8+
Operating System: Raspbian GNU/Linux 10 (buster)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 7.63GiB
Name: ~
ID: BOEY:NG7P:VIPC:J7DF:45ZR:QCSV:FSIK:PMUY:GETO:RJ3S:L7MI:LEQY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

```
sudo docker pull influxdb:2.0.8
2.0.8: Pulling from library/influxdb
no matching manifest for unknown in the manifest list entries
```

Running `docker pull influxdb@sha256:34caf52f34fd2e2bc83f925d7d6e180aca6b3b41971ea2d813e8d216e0c42e0e` does download the image. But it i run
`sudo docker run -p 8086:8086 -v ~/Documents/influxdb/data:/var/lib/influxdb2 shaoftheimage`
It stops with no logs...

**Comment by phantomski77** [comment] 2021-10-04 07:32
> sudo docker pull influxdb:2.0.8
> 2.0.8: Pulling from library/influxdb
> no matching manifest for unknown in the manifest list entries
> ```
> 
> Running `docker pull influxdb@sha256:34caf52f34fd2e2bc83f925d7d6e180aca6b3b41971ea2d813e8d216e0c42e0e` does download the image. But it i run `sudo docker run -p 8086:8086 -v ~/Documents/influxdb/data:/var/lib/influxdb2 shaoftheimage` It stops with no logs...

Thanks.

I’m clutching straws here a bit, but is there a reason why you’re running such an old Docker version?
Unless there’s a valid reason not to, I’d suggest upgrading that to the latest 20.10.8 as there have been quite a few arm related improvements since your 18.09.1.

From your logs I don’t see anything different from my config (apart from Docker version), yet for some reason it’s struggling even to detect your arch automatically for pull/run, which is relatively basic thing. Depending on how you’ve installed Docker in the first place, upgrading it might not be automatic and I’d suggest following the official uninstall/install (using Docker repository) steps from https://docs.docker.com/engine/install/debian/

**Comment by phantomski77** [comment] 2021-10-04 07:49
If you don’t feel like upgrading or have reasons not to (it’s quite quick and straightforward), as the last attempt try forcing the platform for `docker run` with `--platform=linux/arm64`

**Comment by RyuunosukeDS3** [comment] 2021-10-04 11:42
I don't have a reason, acutally. I think I simply forgot... Maybe upgrading it could fix? I will try and upgrade it.
