### ISSUE TITLE
port 8086 stops listening after sometime.

### ISSUE THREAD

**Issue by Tejeshna** [influxdata/influxdb#9700] opened 2018-04-10 06:35 UTC
I am running InfluxDB(1.4.3) on debian 9.4, influxdb is running inside a docker container. The issue is when i start the service it all works fine but, after sometime ( when container get's recreated ) the influxdb stops listening on the port 8086 . When i delete influxdb data files and recreate container  it all works again.It was all working fine when we were running with 1.3.x version.

root@influxdb-7cc9c7f4cf-bgqr6:/var/log/influxdb# ss -nltpu 
Netid  State      Recv-Q Send-Q                                                      Local Address:Port                                                                     Peer Address:Port              
tcp    LISTEN     0      128                                                             127.0.0.1:8088                                                                                *:*                   users:(("influxd",pid=1,fd=3))

root@influxdb-7cc9c7f4cf-bgqr6:/var/log/influxdb# influx
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.

Any help would be appreciated .

**Comment by dgnorton** [comment] 2018-04-10 12:39
@Tejeshna can you provide influxdb logs from when the container gets recreated?

**Comment by dgnorton** [comment] 2018-04-10 12:48
Possibly related to or duplicate of #9550?

**Comment by simplyviks** [comment] 2018-11-20 05:40
can some body please update on this? all of a sudden it(influxDb) went to this state and restart brings 8086 up after 15 mins and then again it goes down

**Comment by russorat** [comment] 2019-02-16 00:45
closing due to lack of information. if this is still happening, please open a new issue with the details requested.

**Closed by russorat** 2019-02-16 00:45 UTC
Labels: 1.x, area/HTTP, need more info
