### ISSUE TITLE
select count(*) from some_measurement renders any installation useless for hours

### ISSUE THREAD

**Issue by mkontula** [influxdata/influxdb#7518] opened 2016-10-25 19:11 UTC
**System info:** InfluxDB 1.0.2, Ubuntu 16.04 TLS, running in an Azure DS11_V2 (2cores, 14gb, SSD)

**Steps to reproduce:**
1. Insert roughly 100M data points with 1h intervals to my_measurement. 100k of unique series
2. select count(*) from my_measurement

**Expected behavior:** 
Receive a number of invidual data points within my_measurement in reasonable time. Such query should never be allowed to bring the system down.

**Actual behavior:** 
Box crashed OOM. kswapd takes all CPU time. Only way to recover is hard boot from azure console. 

```
Last login: Tue Oct 25 18:53:24 2016 from 91.157.20.84
adminuser@influxssdtest:~$ top
top - 19:04:44 up 13 min,  2 users,  load average: 10.07, 8.76, 4.89
Tasks: 147 total,   6 running, 141 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  7.8 sy,  0.0 ni, 30.4 id, 61.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 14359844 total,   151912 free, 14127508 used,    80424 buff/cache
KiB Swap:        0 total,        0 free,        0 used.      860 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   34 root      20   0       0      0      0 R  13.9  0.0   1:16.22 kswapd0
 1167 influxdb  20   0 14.086g 0.013t      0 S   0.9 97.2   2:21.91 influxd
 1182 root      20   0  208672  13088      0 S   0.6  0.1   0:03.92 python3
 1565 root      20   0   59112   1060    500 R   0.3  0.0   0:00.15 sshd
```

**Additional info:** 
OOTB installation from apt-get package. No config changes.

While the system was completely overloaded, no further queries for heap or other variables never got thru.

Should the system block this kind of queries if they're able to bring down the whole OS?

**Comment by jwilder** [comment] 2016-10-25 19:16
We need more information in order to diagnose what is going on.   Can you run the following while the system is in this state:
```
curl -o block.txt "http://localhost:8086/debug/pprof/block?debug=1" 
curl -o goroutine.txt "http://localhost:8086/debug/pprof/goroutine?debug=1" 
curl -o heap.txt "http://localhost:8086/debug/pprof/heap?debug=1" 
curl -o vars.txt "http://localhost:8086/debug/vars" 
iostat -xd 1 30 > iostat.txt
influx -execute "show shards" > shards.txt
influx -execute "show stats" > stats.txt
influx -execute "show diagnostics" > diagnostics.txt
```

**Comment by mkontula** [comment] 2016-10-26 06:02
I try to get the statistics, but it's kinda hard when the login attempts won't go thru. Here's what the azure monitoring looks like. It's reading the disk like crazy.

![image](https://cloud.githubusercontent.com/assets/1148526/19714930/8e32d64e-9b5a-11e6-8bc1-edfac48249ee.png)
![image](https://cloud.githubusercontent.com/assets/1148526/19714958/b0b3d6a0-9b5a-11e6-85aa-145af1627b09.png)
![image](https://cloud.githubusercontent.com/assets/1148526/19714963/c045c3da-9b5a-11e6-85c8-7d8f1bebf829.png)

**Comment by mkontula** [comment] 2016-10-26 07:55
The disk usage was caused by kswapd bughttps://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457. After the fix, the system stayed responsible-ish, but influxd eats all mem and the query doesn't return. We should have around 90M data points at the moment, but exact number seems to be impossible to figure. Of course one could avoid using such monster query, but I would think there should be some protection against performing a system killing query by accident like "Err: too many results. Limit your query by applying more filters". 
[heap.txt](https://github.com/influxdata/influxdb/files/552617/heap.txt)
[iostat.txt](https://github.com/influxdata/influxdb/files/552618/iostat.txt)
[out.txt](https://github.com/influxdata/influxdb/files/552619/out.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/552620/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/552622/stats.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/552621/vars.txt)
[block.txt](https://github.com/influxdata/influxdb/files/552625/block.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/552624/diagnostics.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/552623/goroutine.txt)

**Comment by phemmer** [comment] 2016-10-31 21:38
I was experiencing this issue as well. Reported in #7539. Upgrading to the nightly build gave a huge performance boost and reduction of the memory usage. It will likely help you as well.
However be aware of #7540 which is a regression I am experiencing with the nightly.

**Comment by jwilder** [comment] 2017-05-19 18:19
Closing this since this is for 1.0 which is fairly old now.  If this is still occurring with the latest release, please open a new issue.

**Closed by jwilder** 2017-05-19 18:19 UTC
Labels: need more info
