### ISSUE TITLE
Error writing WAL entry: bad file descriptor

### ISSUE THREAD

**Issue by ericremoreynolds** [influxdata/influxdb#5791] opened 2016-02-23 08:36 UTC
Hello,

I get this error back from the HTTP write API when writing a large number of points in one go (for example > 2000)

    write failed: engine: error writing WAL entry: write
    /root/.influxdb/wal/mydb/default/396/_00004.wal: bad file descriptor

It doesn't seem to happen with a smaller number of points (for example 20).

I am using running Influx on Red Hat Enterprise Linux 6.6.

Let me know what other details would be useful for me to provide.

Thanks!

Eric

**Comment by zstyblik** [comment] 2016-02-23 14:49
@ericremoreynolds please, provide InfluxDB version. Devs don't have much to go with. Thanks in advance.

**Comment by ericremoreynolds** [comment] 2016-02-23 15:15
Connected to http://localhost:8086 version 0.10.0
    InfluxDB shell 0.10.0

Actually I tried dropping `mydb`, and it hung so I had to kill the processes. On restarting `influxd` it gave errors because it could not read the wal files and failed to startup. In the end I deleted the folders with the same named `mydb` in the `.influxdb/data` and `/wal` folders, restarted `influxd`, dropped and recreated the database and from then on everything worked again. 

So I guess the WAL files were somehow locked or corrupted. Indeed the error was no longer appearing even when contributing these 2000 or so points.

If you wish to investigate further I can try to collect further evidence (if you tell me what to try/look for), but I am afraid I don't have a recipe to reproduce the issue.

**Comment by rossmcdonald** [comment] 2016-02-23 15:26
@ericremoreynolds Did you install InfluxDB through a package? Or did you compile it yourself?

**Comment by ericremoreynolds** [comment] 2016-02-23 15:46
Prebuilt `influxdb-0.10.0-1.x86_64.rpm`

**Comment by rossmcdonald** [comment] 2016-02-23 15:57
@ericremoreynolds Thanks. I've seen similar issues when using newer versions of Go, but nothing that would cause that error on Go 1.4.3 (which is what that binary was built with). It sounds like something got corrupted somehow, but it will be hard to diagnose without a reproducible test case or access to the original data.

Since the issue hasn't resurfaced I'm going to go ahead and close this issue. Please let us know if you see the error again, though, and we can continue to investigate.

**Closed by rossmcdonald** 2016-02-23 15:57 UTC

**Comment by ericremoreynolds** [comment] 2016-02-23 17:07
Yeah sure that's fine, if it happens again I will try to extract the logs as soon as possible to try and give you more info.

I was unsure whether to post it given that I couldn't reproduce it, but I figured it was best to say something rather than not.

Thanks! Have a nice rest of day.

Eric
