### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in influxdb/query.(*floatMergeIterator) v1.4.3

### ISSUE THREAD

**Issue by dyanneo** [influxdata/influxdb#16115] opened 2019-12-04 17:47 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. This query was running: SELECT sum("keyCount") as "totalKeyCount" FROM (SELECT last("counter") as "keyCount" FROM "api_key_count" WHERE ("environment" =~ /^prod$/ AND "application" =~ /^app1$/ AND "cluster" =~ /^(app1)$/ AND "container" = 'proxy') AND time >= 1575266400000ms and time <= 1575352740000ms GROUP BY "apiKey", "host", "cluster", *) GROUP BY "apiKey"

__Expected behavior:__
Expected query to return results normally.

__Actual behavior:__
Panic - see log snippet below

__Environment info:__

* System info: Run `uname -srm` and copy the output here
Linux 3.10.0-1062.4.1.el7.x86_64 x86_64
* InfluxDB version: Run `influxd version` and copy the output here
1.4.3
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
```
[coordinator]
log-queries-after = "10s"
max-concurrent-queries = 10
max-select-buckets = 86401
max-select-point = 10000000
max-select-series = 0
query-timeout = "30s"
write-timeout = "10s"

[data]
cache-max-memory-size = 2147483648
cache-snapshot-memory-size = 268435456
cache-snapshot-write-cold-duration = "10m0s"
compact-full-write-cold-duration = "1h0m0s"
default-shard-duration-policy = "1d"
dir = "/data/influxdb"
engine = "tsm1"
index-version = "tsi1"
max-concurrent-compactions = 8
max-points-per-block = 0
max-series-per-database = 3000000
query-log-enabled = false
trace-logging-enabled = false
wal-dir = "/wal/influxdb"
wal-logging-enabled = true
```

__Logs:__
Include snippet of errors in log.
Contents of /var/log/messages at time of panic:
```Dec 3 05:08:32 influxd: [I] 2019-12-03T11:08:32Z Snapshot for path /data/influxdb/metrics/autogen/21 written in 8.781969432s engine=tsm1
Dec 3 05:08:50 influxd: panic: runtime error: invalid memory address or nil pointer dereference
Dec 3 05:08:50 influxd: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e51a2]
Dec 3 05:08:50 influxd: goroutine 2163197679 [running]:
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatMergeIterator).Stats(0xc512c1ac00, 0x1, 0x2)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:153 +0x52
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatInterruptIterator).Stats(0xc4916bd1c0, 0x1681d0c00, 0xe820692a4e99a)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:836 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*bufFloatIterator).Stats(0xc4916bd1e0, 0x0, 0x1)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:58 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatReduceFloatIterator).Stats(0xc4950d7a20, 0x2, 0x2)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:1097 +0x2e
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/tsdb/engine/tsm1.(*floatFinalizerIterator).Stats(0xc4916bd200, 0x4, 0xc4357f27e0)
Dec 3 05:08:50 influxd: :1 +0x3c
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatInterruptIterator).Stats(0xc4916bd220, 0xc4fa063500, 0xc5681d0e88)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:836 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*bufFloatIterator).Stats(0xc4916bd240, 0xc4fa063548, 0xc5681d0ee8)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:58 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatReduceFloatIterator).Stats(0xc4950d7ce0, 0xc51861d6e0, 0xcb8900)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:1097 +0x2e
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatInterruptIterator).Stats(0xc4916bd260, 0xc5681d0da0, 0x4123c7)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:836 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*bufFloatIterator).Stats(0xc4916bd280, 0xc5681d0e88, 0xc42003fe88)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:58 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatReduceFloatIterator).Stats(0xc4950d7e40, 0x2, 0x2)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:1097 +0x2e
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatIntervalIterator).Stats(0xc63e08e120, 0x45ac20, 0xc5681d0e88)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:808 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*bufFloatIterator).Stats(0xc4916bd2a0, 0x2, 0x2)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:58 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatFillIterator).Stats(0xc42c4b8000, 0x44ca6b, 0xc58dd89e88)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:667 +0x2e
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*floatInterruptIterator).Stats(0xc4916bd2c0, 0x43dd1f, 0xc5681d0e28)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.gen.go:836 +0x33
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.Iterators.Stats(0xc4916bc920, 0x2, 0x2, 0x0, 0x0)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/iterator.go:41 +0x57
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.PointLimitMonitor.func1(0xc4f761dce0, 0x0, 0x0)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/monitor.go:14 +0x16b
Dec 3 05:08:50 influxd: github.com/influxdata/influxdb/query.(*QueryTask).monitor(0xc490abd6c0, 0xc5d0b53f50)
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/query_executor.go:503 +0x4c
Dec 3 05:08:50 influxd: created by github.com/influxdata/influxdb/query.(*QueryTask).Monitor
Dec 3 05:08:50 influxd: /go/src/github.com/influxdata/influxdb/query/query_executor.go:485 +0x49
Dec 3 05:08:51 systemd: influxdb.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 3 05:08:51 systemd: Unit influxdb.service entered failed state.
Dec 3 05:08:51 systemd: influxdb.service failed.
Dec 3 05:08:51 systemd: influxdb.service holdoff time over, scheduling restart.
Dec 3 05:08:51 systemd: Stopped InfluxDB is an open-source, distributed, time series database.
Dec 3 05:08:51 systemd: Started InfluxDB is an open-source, distributed, time series database.
```

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment] 2019-12-04 21:26
@dyanneo thank you for opening the issue. InfluxDB 1.4.3 is quite old. Could you to upgrade to the latest release (1.7.9) and see if the issue is still there?

**Comment by dyanneo** [comment] 2019-12-06 14:41
@russorat I appreciate the quick response. We are evaluating the latest release. We did attempt an upgrade to 1.7.8 recently, and were stopped by a malfunction in the upgrade script as well as a bug with handling regex (which I understand is addressed in 1.7.9). Our environment is quite large, so we'd really need the migration steps for existing dbs to be flawless. We have more investigating to do as our roadmap planning continues.
Thanks again.

**Comment by russorat** [comment] 2019-12-09 18:06
thanks. i'll leave this issue open for the community, but we won't be making any bugfixes to the 1.4.x line. If there is an issue with the upgrade script, let us know in a new issue and we will take a look. Otherwise, let us know when you upgrade if the issue is still there and we will take a look.

**Comment by russorat** [comment] 2021-09-13 17:08
I'm going to close this since we won't be making any changes to the 1.4 line.

**Closed by russorat** 2021-09-13 17:08 UTC
Labels: 1.x
