### ISSUE TITLE
RES memory keeps on increasing and influxd crashes...

### ISSUE THREAD

**Issue by ambatigan** [influxdata/influxdb#8087] opened 2017-03-02 16:46 UTC
Using the influxd-1.2.0... The RES memory on that process is being increased gradually and finally influxd crashes....after a couple of hours.... Tried the patch v1.2.1-rc5.. too..but no use....

My system is a 32 core, 32 G RAM and Sles12 os...

**Comment by jwilder** [comment] 2017-03-02 16:55
@ambatigan Can you attach the saved curl output to the issue?  e.g. `heap.txt`, `block.txt`, etc..

**Comment by ambatigan** [comment] 2017-03-03 04:35
Here is info that asked.. placed a gist here at https://gist.github.com/ambatigan/30b210c93d6b5faf73439da6dc8ee911

**Comment by jwilder** [comment] 2017-03-03 19:59
@ambatigan Can you run the same commands when RES is high and close to crashing?  The heap in these profiles in only 800MB.

Also, if it crashed was do you have a stack trace in the logs?

**Comment by ambatigan** [comment] 2017-03-04 07:29
pl check the stack trace of .. two of the previous crash instances... at https://gist.github.com/ambatigan/63ce8939f5be940c778ad46a5334d714

**Comment by ambatigan** [comment] 2017-03-04 08:15
the stack trace for another two similar instances...at https://gist.github.com/ambatigan/94abfb75736c51644bca18be212910ff

**Comment by prune998** [comment] 2017-03-06 02:33
I'm used to have Influxdb OOM crashes...
Upgraded to 1.2 last week, and seeing huge Heap Idle usage and high CPU, while my usage is pretty basic : 
- telegraf on the same host
- internal databe graphing
- IoT sensors information

<img width="913" alt="grafana_-_influxdb_internals" src="https://cloud.githubusercontent.com/assets/1110398/23594683/bf3d6790-01e9-11e7-8a0f-42af7a599cdc.png">

Here is the graph of the query : 
```SELECT mean("numSeries") FROM "database" WHERE $timeFilter GROUP BY time($interval), "database" fill(null)```

<img width="704" alt="grafana_-_influxdb_internals" src="https://cloud.githubusercontent.com/assets/1110398/23594724/1bc0ff2c-01ea-11e7-8e22-5af66b3984c6.png">

As you can see I don't have much traffic...

Why is the Idle heap that huge ? 
I'm running on Ec2 with low memory and it's close to crash...
I'll send crash log if it happen, but I would definitely like an explanation of why the Idle is so high, and what can be done to free this memory which is never used...
thanks

**Comment by ambatigan** [comment] 2017-03-06 15:21
Please find the perf files..when the RES reached 1g+

[block.txt](https://github.com/influxdata/influxdb/files/821569/block.txt)
[diagnostics.txt](https://github.com/influxdata/influxdb/files/821570/diagnostics.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/821571/heap.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/821576/goroutine.txt)
[iostat.txt](https://github.com/influxdata/influxdb/files/821578/iostat.txt)
[shards.txt](https://github.com/influxdata/influxdb/files/821579/shards.txt)
[stats.txt](https://github.com/influxdata/influxdb/files/821580/stats.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/821581/vars.txt)

**Comment by jwilder** [comment] 2017-03-06 23:50
@ambatigan The heap in these snapshots is about 1.7GB.  I don't see anything unusual in these captures currently.  An OOM would occur when the heap is closer to 32GB.  Would you be able to grab these snapshot when the process RSS is closer to 32GB?

In the logs you attached, can you attach the _full_ trace as well?  The snippet that is attached is not enough to determine what the cause might be.  It looks like there are two different types of crashes.  One is a `fatal error: runtime: cannot allocate memory` and another is `unexpected fault address`.

**Comment by ambatigan** [comment] 2017-03-07 07:51
Another instance has come.. the RES has grown to huge memory.. to 3g...and the entire system has become unresponsive... Seems like it happened after executing a query from the webapp... We had to kill the influxd process.... 
[block.txt](https://github.com/influxdata/influxdb/files/823687/block.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/823688/goroutine.txt)
[vars.txt](https://github.com/influxdata/influxdb/files/823689/vars.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/823690/heap.txt)

Seen an error in the log like - ERR: max-concurrent-queries limit exceeded(10, 10)
Warning: It is possible this error is due to not setting a database.
So..changed the value back to zero to disable the mx-concurrent-queries limit...

Also....got err : Error: max-select-point limit exceeed: (220566055/5000)
So changed its value back to zero...
Hmm... facing lot of pains...with influxd.. **Anybody using it in production?** Seems like influxd is not withstanding the exceptions from client end....rather than hanging itself down or needing itself to be killed.....

**Comment by KiNgMaR** [comment] 2017-03-07 07:54
Have you checked for *high-cardinality tags*? These should be avoided (use fields instead).

**Comment by ambatigan** [comment] 2017-03-07 07:56
pl give me some example configurations... thanks.

**Comment by jwilder** [comment] 2017-03-07 15:58
@ambatigan Can you describe how you are writing data and a little more about your env?

- Are you overwriting points with the same timestamp?
- Are you writing points into the past?
- Are you deleting series or ranges of time?

The profiles show some work related to de-duplicating points in TSM files at query time which hints that you may be writing data in a way that is very expensive to query back.

It also looks like you have change the default `data` dir to something on `/fnet/`.  Can you describe how this filesystem is mounted?  
* Is this a directly attached SSD volume?
* Is this using some kind of networked filesystem NFS, SAN, NAS?
* Is this a RAID'd filesystem?

The config options you set are limits and will return an error when you exceed that limit.

`max-concurrent-queries` is config option to limit how many concurrent queries can be run at any given time.  If you set it to 10, then only 10 concurrent queries can be run and new ones will be prevented and return an error until one of the prior 10 completes.

`max-select-point` is a config option to limit how many points can be returned from a query.  If you set it to 5000, then it will return an error if more than 5000 points need to be returned.  In your case, you need tried to return 220M.

Can you list the queries you are running?  Returning 220M values in a single query seems odd and might hint that the OOMs you see could be due to a bad query.

If the process ever crashes, can you please attach the _full_ stack trace from the logs.  Without that, we don't have much insight into what is causing it to crash.  From your prior comments, there are at least 2 different sources of a crashes that we need the traces from to investigate further.

If the `influxd` process is ever hung or unresponsive, please send it a `sigquit` signal which will cause it to crash with a stack trace and attach the _full_ trace to this issue.

**Comment by ambatigan** [comment] 2017-03-08 11:20
Here are the answers to your questions -

    Are you overwriting points with the same timestamp? No.
    Are you writing points into the past? At series level, I believe we are writing in ascending order by time. We can enable write trace to confirm.
    Are you deleting series or ranges of time? No.

    Is this a directly attached SSD volume? No. directly attached HDD.
    Is this using some kind of networked filesystem NFS, SAN, NAS? No.
    Is this a RAID'd filesystem? Yes.

Whenever we are trying to execute the below query from the console seeing the below output with error (the same query we are using in our app as well..)…

"SELECT sum(ms_000_099) as _100, sum(ms_100_199) as _200, sum(ms_200_299) as _300, sum(ms_300_399) as _400, sum(ms_400_499) as _500, sum(ms_500_599) as _600, sum(ms_600_699) as _700, sum(ms_700_799) as _800, sum(ms_800_899) as _900, sum(ms_900_999) as _1000, sum(ms_1000_inf) as _1100 FROM latency WHERE time >= 1488911081738000000 and time <= 1488954281738000000 AND flavor = 'onl_qa' GROUP BY time(900s)" 

The console output is -

1488910500000000000 8195017  114812 2479 1966 2087 1658 1534 1433 1636 1161  9915

1488911400000000000 23726028 333134 7888 7044 5234 4848 4644 4589 4369 811   3734

1488912300000000000 21404314 339087 6140 5390 5105 4247 4721 5112 1289 22    83

1488913200000000000 11906048 162136 2253 2298 2317 2356 2303 2946

1488914100000000000 1025845  16452  121  194  178  112  34   125

1488915000000000000

1488915900000000000

1488916800000000000

1488917700000000000

1488918600000000000

1488919500000000000

1488920400000000000

1488921300000000000

1488922200000000000

1488923100000000000

1488924000000000000

1488924900000000000

1488925800000000000

1488926700000000000

1488927600000000000

1488928500000000000

1488929400000000000

1488930300000000000

1488931200000000000

1488932100000000000

1488933000000000000

1488933900000000000

1488934800000000000

1488935700000000000

1488936600000000000

1488937500000000000

1488938400000000000

1488939300000000000

1488940200000000000

1488941100000000000

1488942000000000000

1488942900000000000

1488943800000000000

1488944700000000000

1488945600000000000

1488946500000000000

1488947400000000000

1488948300000000000

1488949200000000000

1488950100000000000

1488951000000000000

1488951900000000000

1488952800000000000

1488953700000000000

ERR: max-select-point limit exceeed: (69026355/5000)

 

We expect only ~50 records for our above query, but we are seeing the error which has ~60M records.
Is it something like, it is getting 60M+ records before the GroupBy happens?

Btw, tried to run sigquit (kill -3) on the influx pid, but core file is not being formed though core pattern is configured correctly.. Dont know why.. But tried 'gcore' on the influx pid when it was unresponsive but core file is of very huge size (roughly 22G), i cant share it with you...

**Comment by russorat** [comment] 2019-02-16 00:37
closing due to age. please try again with the latest version of influx and open a new issue if you are still have this problem.

**Closed by russorat** 2019-02-16 00:37 UTC
Labels: 1.x, need more info

**Comment by lobocobra** [comment] 2019-11-15 23:38
exactly the same issue here with version 1.7.9.
![image](https://user-images.githubusercontent.com/7016785/68982852-dc7a8900-0808-11ea-8b3c-dff005a7c0b9.png)

I use influx only for my home automation and it crashes on regular bases. I will try now the 2 settings mentionned above:
max-concurrent-queries10
max-select-point 5000

Influx runs on a Synology NAS VMM and was rock solid before I updated from 1.6.4 to 1.7.9. Since then it is just a matter of times till it crashes the VMM. 
=> Query average is at 12min!! according to the stats
![image](https://user-images.githubusercontent.com/7016785/68982975-472bc480-0809-11ea-8bbe-745dcaacce68.png)

I tried TSM and TSI and saw no difference.

**Comment by lobocobra** [comment] 2019-11-15 23:46
Changing the settings and a restart of InfluxDB shows this...
![image](https://user-images.githubusercontent.com/7016785/68983184-231cb300-080a-11ea-852c-149ae8d8e219.png)

So there seems to be a recursive request? A loop?

Avg Query duration went up to 69min but is going down rapidly.
![image](https://user-images.githubusercontent.com/7016785/68983246-637c3100-080a-11ea-8444-a0f7bc26e1f5.png)

Seems to work better, but this all does not look healthy... must be a bug in there.

**Comment by lobocobra** [comment] 2020-01-11 10:06
and it crashes again... I try now to downgrade to version 1.6.4
