### ISSUE TITLE
Add back in the vertical hover line to graphs

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14691] opened 2019-06-10 15:57 UTC
as a user
with admin
when i hover over a line graph
then i would like to see a vertical line corresponding to the time on each graph in view. 

also, a possible enhancement to this would be to be able to "lock" the line so that i could view related points on other graphs without having to keep my mouse there. See design-in-progress slack channel for an example.

**Comment by russorat** [comment] 2019-12-11 23:58
this would be so handy!

**Comment by philjb** [comment] 2020-07-29 18:20
dupe of https://github.com/influxdata/influxdb/issues/16612 I believe.

**Comment by kristinarobinson** [comment] 2020-10-07 19:51
Fixed.  Hover line implemented in one graph in edit mode and in dashboard mode.  Will work on implementing shared hover line in issue above.

**Closed by kristinarobinson** 2020-10-07 19:51 UTC
Labels: difficulty/medium, team/monitoring
