### ISSUE TITLE
influxql: incomplete expressions accepted at end of select statement

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#7003] opened 2016-07-12 14:38 UTC
Working from 11d141a, the following statements look like they shouldn't parse correctly, but they are accepted. It looks like `SELECT * FROM x` is parsed correctly and then a partial expression is parsed but ignored.

```
> SELECT*FROM x -620./-409./-420./-423./-409./
name: x
-------
time			n
1468333544857324965	1

> SELECT*FROM x y>
name: x
-------
time			n
1468333544857324965	1

> SELECT*FROM x c=~
name: x
-------
time			n
1468333544857324965	1

> SELECT * FROM x DISTINCT m/
name: x
-------
time			n
1468333544857324965	1
```

**Comment by jsternberg** [comment] 2016-07-13 21:14
I think this is a duplicate of #6543.

**Closed by jsternberg** 2016-07-13 21:14 UTC
