### ISSUE TITLE
[0.11.0] Recreate the same database without on error in the new query engine

### ISSUE THREAD

**Issue by li-ang** [influxdata/influxdb#5632] opened 2016-02-11 13:48 UTC
Reproduce steps：

Create the same database twice. 
eg.
```
curl -G 'http://127.0.0.1:8086/query' --data-urlencode "q=create database foo"
{"results":[{}]}
curl -G 'http://127.0.0.1:8086/query' --data-urlencode "q=create database foo"
{"results":[{}]}
curl -G 'http://127.0.0.1:8086/query' --data-urlencode "q=create database foo"
{"results":[{}]}
```

**Comment by jwilder** [comment] 2016-02-11 20:10
Duplicate of #5563

**Closed by jwilder** 2016-02-11 20:10 UTC
Labels: category/error handling, category/queries
