### ISSUE TITLE
2.0.0-alpha19: cannot use _measurement field for delete predicate

### ISSUE THREAD

**Issue by ravz** [influxdata/influxdb#15946] opened 2019-11-16 06:24 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by russorat** [comment] 2019-11-22 18:26
@ravz i just tried in the latest master and could not reproduce. do you mind trying again with alpha 20 or latest master?

**Comment by danxmoran** [comment] 2020-12-22 22:12
This is working as of v2.0.3, closing this

**Closed by danxmoran** 2020-12-22 22:12 UTC
Labels: area/2.x
