### ISSUE TITLE
InfluxDB 2.x OSS fails to pass the correct retention policy to the API

### ISSUE THREAD

**Issue by Pupix** [influxdata/influxdb#21644] opened 2021-06-09 14:30 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create bucket with a retention policy (30 Days for example)
2. Click "Settings" and choose Delete Data "Never"
3. Click "Save Changes"

__Expected behavior:__
The retention policy to be set to "Never".

__Actual behavior:__
The UI passes the old retention policy to the API call so nothing changes.

__Environment info:__

* System info: Microsoft Windows [Version 10.0.19042.985]
* InfluxDB version: InfluxDB 2.0.6 (git: 4db98b4c9a) build_date: 2021-04-29T16:48:12Z
Tried 2.0.7 too and it does the same thing.

**Comment by danxmoran** [comment] 2021-06-09 15:02
Duplicate of influxdata/ui#1607

Closing this one, please track the linked issue for progress updates

**Closed by danxmoran** 2021-06-09 15:02 UTC
