### ISSUE TITLE
Alert list is empty after creating new alert

### ISSUE THREAD

**Issue by jpillora** [influxdata/influxdb#18395] opened 2020-06-08 16:21 UTC
```
$ docker images | grep influx
quay.io/influxdb/influxdb        2.0.0-beta          71a7ac91d210        3 weeks ago         225MB
$ docker exec influxdata uname -srm
Linux 5.3.0-40-generic x86_64
$ docker exec influxdata influxd version
InfluxDB 2.0.0-beta.10 (git: d00706dea8) build_date: 2020-06-02T21:09:12Z
```

1. create alert (aka check)

2. visit alerts screen, click new alert, click around some more, ????

3. visit alerts screen again to find it empty

4. api confirms list is empty:

```
$ export INFLUX_TOKEN=<all access token>
$ curl https://host/api/v2/checks -H "Authorization: Token $INFLUX_TOKEN" | jq
{
  "checks": [],
  "links": {
    "self": "/api/v2/checks?descending=false&limit=20&offset=0"
  }
}
```

5. api confirms item still exists:

```
$ curl https://host/api/v2/checks/05d1298bca205000 -H "Authorization: Token $INFLUX_TOKEN" | jq
{
  "id": "05d1298bca205000",
  "name": "Oxygen check",
  "ownerID": "05c5cdf80ddf4000",
  "orgID": "05c5cdf8249f4000",
  "query": { .... },
  "statusMessageTemplate": "Check: ${ r._check_name } is: ${ r._level }",
  "every": "1m",
  "offset": "0s",
  "tags": [],
  "createdAt": "2020-06-09T01:59:49.544442132+10:00",
  "updatedAt": "2020-06-09T02:00:00.06656539+10:00",
  "thresholds": [ ... ],
  "type": "threshold",
  "labels": [],
  "links": {
    "self": "/api/v2/checks/05d1298bca205000",
    "labels": "/api/v2/checks/05d1298bca205000/labels",
    "members": "/api/v2/checks/05d1298bca205000/members",
    "owners": "/api/v2/checks/05d1298bca205000/owners",
    "query": "/api/v2/checks/05d1298bca205000/query"
  },
  "status": "active",
  "latestCompleted": "2020-06-08T16:14:00Z",
  "latestScheduled": "2020-06-09T02:14:00+10:00",
  "lastRunStatus": "success"
}
```

the only way i can find my checks now is to "explore" the _monitoring bucket to find active check_ids

shoud i be using nightly instead of beta?

**Comment by russorat** [comment] 2020-06-26 23:31
@jpillora sorry for the delay in seeing this. can you still repro with beta-13?

**Comment by jpillora** [comment] 2020-06-27 04:08
Assuming beta-13 is this docker image, then yes, I still can

```sh
$ docker ps | grep influx
8572e742ed4c        quay.io/influxdb/influxdb:2.0.0-beta   "/entrypoint.sh infl…"   2 minutes ago       Up 2 minutes                      0.0.0.0:56080->9999/tcp
                                                                                  influxdata
$ docker images | grep influx
quay.io/influxdb/influxdb        2.0.0-beta          e89ed0141303        33 hours ago        242MB
quay.io/influxdb/influxdb        <none>              71a7ac91d210        7 weeks ago         225MB

$ curl -s https://inf.jpillora.com/api/v2/checks/05d1298bca205000 -H "Authorization: Token $INFLUX_TOKEN" | jq '.name'
"Oxygen check"
$ curl -s https://inf.jpillora.com/api/v2/checks -H "Authorization: Token $INFLUX_TOKEN" | jq
{
  "checks": [],
  "links": {
    "self": "/api/v2/checks?descending=false&limit=20&offset=0"
  }
}
```

**Comment by russorat** [comment] 2020-07-06 17:07
@jpillora i believe you will need to specify the org name or org id in the API call to /checks. https://v2.docs.influxdata.com/v2.0/api/#operation/GetChecks

**Comment by jpillora** [comment] 2020-07-06 17:15
Thanks @russorat, I didn't notice that param. Unfortunately, same result
```
$ curl -s "https://inf.jpillora.com/api/v2/checks/05d1298bca205000" -H "Authorization: Token $INFLUX_TOKEN" | jq '.orgID'
"05c5cdf8249f4000"

$ curl -s "https://inf.jpillora.com/api/v2/checks?orgID=05c5cdf8249f4000" -H "Authorization: Token $INFLUX_TOKEN" | jq
{
  "checks": [],
  "links": {
    "self": "/api/v2/checks?descending=false&limit=20&offset=0&orgID=05c5cdf8249f4000"
  }
}
```

Two comments on this,

1. If it is required, the server should throw a 400
2. Is it possible for it not to be required, and keeping the `orgID` as a filter - so leaving it off will return all checks the token has visibility into

**Comment by russorat** [comment] 2020-07-06 19:33
@jpillora try as i might, i can't seem to reproduce this in my local OSS build. I am going to try the docker image in case it's specific to that.

**Comment by jpillora** [comment] 2020-07-06 19:39
A couple things that might be affecting this:
- This alert was created by a now deleted user - I didn't think this would
be an issue as it's all under the same organisation and I'm currently using
an admin (full access) token
- I upgraded the influxdb beta image about 2 weeks ago, so maybe it's stuck
in a bad state? I guess the bug lies in how it got into this state...

I can try to repro from scratch when I get time, though I'm currently
swamped

**Comment by russorat** [comment] 2021-05-20 22:20
i'm going to close this for now since it was opened against a pre-release version of influxdb. if you are still facing this problem, please open a new issue with the details.

**Closed by russorat** 2021-05-20 22:20 UTC
