### ISSUE TITLE
When clicking on documentation button in admin area, a 404 is displayed

### ISSUE THREAD

**Issue by jaapz** [influxdata/influxdb#7526] opened 2016-10-27 07:43 UTC
### Bug report

__System info:__ InfluxDB 1.0.2, running on docker

__Steps to reproduce:__

1. start influxdb
2. click on documentation

__Expected behavior:__ 
go to docs

__Actual behavior:__
see a 404

**Comment by jwilder** [comment] 2016-10-27 20:30
This is fixed by #6688 which is in 1.0.2, but looks like the docker image is not working correctly.

**Comment by jsternberg** [comment] 2016-10-27 20:54
The issue is that the documentation link gets automatically updated to the version. Since the version is 1.0.2, it updates the documentation link to that, but that doesn't exist. We need to truncate the patch version when making the docs link.

**Comment by jsternberg** [comment] 2016-10-27 20:54
Also, the reason why a build works from source is because the version likely isn't set. When the version isn't set, it defaults to using `latest` which works.

**Closed** 2016-10-28 00:44 UTC
Labels: area/packaging, kind/bug

**Comment by jaapz** [comment] 2016-10-28 08:05
Neat, thanks!
