### ISSUE TITLE
CPU and RAM throw recurrently out of memory

### ISSUE THREAD

**Issue by Raul-87Py** [influxdata/influxdb#16087] opened 2019-12-03 12:39 UTC
Hello,

We are using influxDB and Grafana for show metrics. We have a problem with a memory usage an cpu, we can see RAM an CPU usage go to the limit and OS kill influxDB process.

Enviroment:

server/machine_1 - InfluxDB shell version: 1.7.4 -- OS: Red had 2.6.32-754.17.1.x86_64
number of cpu: 12
RAM: 45GB

 * DBs:    175
 * Shards: 1114
 * Points Writen Ok : 820.234 /1m
 * Write request: 10266 /1m
number of cpu: 12
RAM: 45GB

server/machine_2 - InfluxDB shell version: 1.7.4 -- OS: Red had 2.6.32-754.17.1.x86_64
 * DBs:    181
 * Shards: 1349
 * Points Writen Ok : 826.189 /1m
 * Write request: 10451 /1m

Similar issues:

https://github.com/influxdata/influxdb/issues/14800#issue-485187554

Steps to reproduce:

With are having a  normal commited traffic, data volume, etc..

Actual behavior:

Serveer up the cpu and Ram usage and it go to the limit and OS kill influxDB process. This behavior is recurring.
We have more graphics with memory and cpu usage, logs... but all info have big size, we can push that's info if it's necessary.

**Comment by russorat** [comment] 2019-12-03 19:53
@Raul-87Py thanks for the issue! Does this happen on all machines or just specific ones? What are the queries you are running against the instance to cause this? I'm trying to get some repro steps for our engineering team to help troubleshoot the issue. Also, what is "normal traffic"? Any idea of the amount of data being loaded into the servers that are running out of memory?

finally, have you tried to reproduce with the latest 1.7.9?

**Comment by Raul-87Py** [comment] 2019-12-04 10:39
Thanks for your fast response.

We edited the information, there are all necessary data? 

We don't tryed the 1.7.9 version because the migration it's so sensitive, because there are poruction metrics.

**Comment by russorat** [comment] 2019-12-04 21:15
@Raul-87Py am I reading this correctly that you are ingesting around 820 points per minute on these machines but you have over 10000 write requests per minute? That seems strange.

Also, is there a specific query you can provide that causes the OOM?

**Comment by Raul-87Py** [comment] 2019-12-05 10:56
Yes, we have 820 thousen points per minute. (820000).

We didn't see any especific query that cause this problem, but we saw in logs that in the same moment at the problem was present in Influxdb, it's was doing data compaction (.tsm files).

**Comment by Raul-87Py** [comment] 2019-12-10 15:01
After looking for in hardware sizing guidelines, we can see a points for minute limit around 800 thousand a 14 thousand fields for second (Prometheus are sending 1 point for field), The hardware sizing guidelines ranges, we are in moderate-high (around 4 million series cardinality). Are 40 GB RAM suitable for this load?


We are thinking the issue could be related with the total number of Databases, shards or measurements. Does it make any sense? Are there any documentation or guidelines about max number of Databases, shards, measurements…?

**Comment by russorat** [comment] 2019-12-10 18:09
@Raul-87Py honestly, at that scale, it could be a ton of things. Without a deep insight into your schema and queries, I won't be able to do much. Here are our documented guidelines for schema design which is what impacts the memory the most: https://docs.influxdata.com/influxdb/latest/concepts/schema_and_data_layout/

I'm going to close this issue since it's more of a support request. I recommend you join the Slack community (https://influxdata.com/slack) or forum (https://community.influxdata.com) and continue the discussion in there.

If you do discover this issue is due to a bug in the software, please open a new issue and we will address.

Thanks!

**Closed by russorat** 2019-12-10 18:09 UTC
Labels: 1.x, need more info
