### ISSUE TITLE
Data Explorer: Clicking submit a query is taking too long

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#18296] opened 2020-05-29 18:06 UTC
This delay is happening in the data explorer whenever i click the submit button. Clicking the button should register instantly for the user.

![image (54)](https://user-images.githubusercontent.com/4805997/83290924-528a8000-a19c-11ea-92bf-fe825e1aaf61.png)

**Comment by desa** [comment] 2020-06-12 19:12
@Asalem1 does the PR you have solve this issue or just add a cancel button?

**Comment by Asalem1** [comment] 2020-06-16 12:22
Both. It address the issue that clicking submit should immediately set the button value to a loading state rather than waiting for the query to compile and execute. @russorat I just merged the changes onto master if you wanna see if the issue is resolved for you. If it is, feel free to mark it as closed, otherwise let me know and I'll see about speeding the event up some other way

**Comment by russorat** [comment] 2020-06-16 15:31
This is what i see in the data explorer in us-west this morning. There is still a noticeable delay when interacting with the button.

![Kapture 2020-06-16 at 8 29 46](https://user-images.githubusercontent.com/4805997/84794850-9c9c9f80-afab-11ea-98b2-dda47f7c2318.gif)

**Comment by Asalem1** [comment] 2020-06-18 17:08
Hmmm, would you mind sending me a link to a dashboard that's experiencing this? We're setting the state on click so I'm not sure where the delay is coming from. We've got a feature enhancement request coming up to half a second until the `cancel` text displays (so that it doesn't flash so abruptly). I'm wondering if that might help in the perception that the event didn't register?

**Closed** 2020-07-17 19:33 UTC
Labels: area/performance, kind/bug, severity/sev-3, team/monitoring
