### ISSUE TITLE
Fields with null values stop appear on select * queries

### ISSUE THREAD

**Issue by sbengo** [influxdata/influxdb#8113] opened 2017-03-09 13:23 UTC
__System info:__ RH 6.4
__InfluxDB version:__ 1.0.0

Hi,
I am collecting a lot of metrics whose values are almost always 0 (~98%). In order to save disk space, we are not sending those values to Influx if they are not different than 0. 
To create the field keys, we only send them once and we leave a single metric of fields collection sending data always (even if its 0). As an example:

| Metric | Send Configuration |
| ------- | ------ |
| X |If non zero
| Y |If non zero
| Z | Always

So with a simple select: `SELECT * FROM "myMeas" WHERE time()...` we got the following output:

| Time | X | Y | Z |
| ----- | -- | -- | -- |
| ----- |     |     | 0 |
| ----- |     |     | 0 |
| ----- |     |     | 0 |

We assume that if value is null, we will treat it as zero and we can use the statement fill(0).

Few days ago, we did the same query and we have seen that only the sending field is shown with the same query. Note that since the first send values it has passed the `shard group duration` time defined on our RP.

| Time | Z |
| ----- | -- |
| ----- | 0 |
| ----- | 0 |
| ----- | 0 |

So... it made me think about some questions:
- Why the behaviour have changed?
- It has relation with the case that InfluxDB has passed the shard group duration time and the new file (TSM1) has not those fields 'registered'?

Thanks for all,
Greetings!

**Comment by jsternberg** [comment] 2017-03-09 13:51
I think this has to do with your use of `*`. The `*` will expand to any fields it finds within the time range. If you don't have the `X` or `Y` points within the specified time range, it isn't included in the expansion. I think the expansion is based on shards so if you have a shard duration of 1 week and you do `now() - 3d` (anywhere within 1 week), it will only look at the last shard group.

**Comment by sbengo** [comment] 2017-03-09 14:58
Thanks for your answer @jstenberg.

I'am sorry to ask that, but: is the expected behaviour?

As the same way you are returning me the existing fields on a measurement with `SHOW FIELD KEYS` statement,  wouldn't be useful /possible to  return all field keys as columns and null values if query with the `*` ?

Thanks,
Greetings!

**Comment by jsternberg** [comment] 2017-03-09 14:59
I believe this is expected behavior if what I said is correct. You can still explicitly specify the fields and they'll show up. It's the wildcard expansion that won't work as you want it to.

**Comment by sbengo** [comment] 2017-03-09 16:05
Thanks again for your answer.

If I specify the field, there are some cases:

1. `SELECT X FROM "myMeas" WHERE time()...`
It returns empty, as it doesn't contain any value.

2. `SELECT X,Z FROM "myMeas" WHERE time()...`
It returns columns and empty for X field... but InfluxDB doesn't check if X is a `Field Key`:  if you execute the same query with `K` (it doesn't exist as field key) instead of `X`: `SELECT K,Z FROM "myMeas" WHERE time()...` it is considered as a column by InfluxDB. It means that it doesn't recognise existing `Field Keys` on that measurement

So I understand what you say, but, as I explained, on the same way InfluxDB is able to return me the field keys, wouldn't be possible to check for those existing keys and use the wildcard expansion to show me all of them?

Thanks again!!
Greetings

**Comment by mark-rushakoff** [comment] 2017-03-09 16:08
> I am collecting a lot of metrics whose values are almost always 0 (~98%). In order to save disk space, we are not sending those values to Influx if they are not different than 0.

InfluxDB's storage engine is designed to efficiently compress repetitive values. How much disk space savings did you measure by omitting fields?

**Comment by sbengo** [comment] 2017-03-09 18:06
Hi @mark-rushakoff.

First of all, I have to ask you:
- There is some place on InfluxDB docs that talks about compression and quantify how much disk space can save and how it works?

We are working on a big project to get metrics of all communications devices that works with SNMP protocol. In order to get the right performance, we are defining disk/cpu/mem requeriments to achieve the proposed scope.

Most of error counters are almost permanently zero: i.e: ifInErrors, ifOutErrors, ifInDiscards  and other specific errors like dot3Stats. According to that, we defined:

````
M (uniq) = 800 devices; 
N (uniq) ~= 50 interfaces by device; 
Z = (4 ifMIB + 14 dot3Stats) = 18 Fields (splitted on 2 measurements)
````

So the total points (`M*N*Z`) written on a single polling will achieve to `720000 points`.

If I am not wrong, InfluxDB uses a mean of `3 bytes` for each field (sizing docs). According to that, required space disk would increase up to `2160000 bytes` for each polling. 

With the non send if zero (98% of them are mostly 0) option, we would reduce *theorically*:
````
Writes : 720000 to 14400
Disk : 2160000 to 14400
````

Thanks again guys!

**Comment by sbengo** [comment] 2017-03-13 09:39
Hi,

Sorry to write to you again, but I'm really excited to know how InfluxDB compress data so it would let me turn off our "non zero report" feature.

We are saving data as `Float`.  As I could read, InfluxDB is using Gorilla compression algorithm (using XOR encoding right?). 

- Do you have some real cases or benchmarks to let me know how much space would I save?

- On the `Hardware Sizing` you said each non-string values requires 3 bytes. These measures have been obtained taking into account the compression done by InfluxDB?

Thanks again!!!!

**Comment by mark-rushakoff** [comment] 2017-03-13 15:16
@sbengo We're having some discussions internally about what we can do better for documenting or reporting benchmarks around compression. Until we get that added to the proper Docs site, you can either run benchmarks on your own data (which will give you the most useful information as not all data compresses the same) or you can refer to some of the white papers listed in our [product comparisons](https://www.influxdata.com/products/#compare).

[Floats are currently encoded with Gorilla](https://github.com/influxdata/influxdb/blob/7d2eac173b6b720c1a5c0a5616a96f3e013a758e/tsdb/engine/tsm1/float.go), [booleans take 1 bit per value](https://github.com/influxdata/influxdb/blob/7d2eac173b6b720c1a5c0a5616a96f3e013a758e/tsdb/engine/tsm1/bool.go), [ints are zig-zag encoded](https://github.com/influxdata/influxdb/blob/7d2eac173b6b720c1a5c0a5616a96f3e013a758e/tsdb/engine/tsm1/int.go), and [strings are snappy encoded](https://github.com/influxdata/influxdb/blob/7d2eac173b6b720c1a5c0a5616a96f3e013a758e/tsdb/engine/tsm1/string.go).

**Comment by jsternberg** [comment] 2017-05-08 18:25
I'm going to close this for now since I don't think there's anything actionable here. If you have any other questions about the system, you can direct them to our community website at https://community.influxdata.com or open another issue if you find a bug or have a feature request.

**Closed by jsternberg** 2017-05-08 18:25 UTC
Labels: area/queries
