### ISSUE TITLE
Got response:'204 No Content' no data found in influxdb

### ISSUE THREAD

**Issue by Satisheupure** [influxdata/influxdb#6157] opened 2016-03-30 16:15 UTC
Successfully installed influxdb on windows and everything is working as expected locally. But having trouble posting data from outside using http api.

I am able to connect to admin panel locally through

http://localhost:8083/
I am using below command for posting data from a remote server:

curl -i -XPOST 'http://172.29.6.195:8086/write?db=telegraf' --data-binary 'test_load,host=njxap1dbadm01 value=13.64'
I am getting below success message:

HTTP/1.1 204 No Content
Request-Id: d3b58c0c-f620-11e5-80a1-000000000000
X-Influxdb-Version: unknown
Date: Wed, 30 Mar 2016 02:40:55 GMT
log on server side:

[http] 2016/03/29 22:40:55 172.29.18.10 - - [29/Mar/2016:22:40:55 -0400] POST /write?db=telegraf HTTP/1.1 204 0 - curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2 d3b58c0c-f620-11e5-80a1-000000000000 0
Even though I got the sucess message on client side some how the data is not getting saved on the database.

I checked for the data from admin panel and returning no data.Checked with curl get also no results.

I have retention policy of 1day for my database. Please help me resolve with the issue of why the data is not getting saved to database.

**Comment by mark-rushakoff** [comment] 2016-03-30 19:56
@Satisheupure This looks like a duplicate of https://github.com/influxdata/influxdb/issues/6061.

For now, add `-H 'Content-Type: text/plain'` to your curl command as a workaround. That issue is in the 0.12 milestone, so you should not need this workaround after the 0.12 release.

**Closed by mark-rushakoff** 2016-03-30 19:56 UTC
Labels: category/writes
