### ISSUE TITLE
influxd --session-length has no effect

### ISSUE THREAD

**Issue by dnr** [influxdata/influxdb#17142] opened 2020-03-09 01:36 UTC
I'm trying to configure influxd 2 on a local network to not require logging in (at least not very often). The `--session-length` flag seems the obvious one to change, and I changed it to one year (in minutes), but it seems to have no effect and I'm prompted to log in frequently.

I'm running it in docker.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run influxd 2.0.0-beta with `--session-length=525600`
2. Log in to the web UI and view a dashboard
3. Wait 24 hours
4. Visit the same url again (in the same browser session)

__Expected behavior:__
I expect to see the dashboard and not be prompted to log in.

__Actual behavior:__
I get prompted to log in.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
`Linux 5.3.0-24-generic x86_64`
* InfluxDB version: Run `influxd version` and copy the output here
`InfluxDB 2.0.0-beta.5 (git: 2295247a5) build_date: 2020-03-09T01:32:06Z`
* Other relevant environment details: Container runtime, disk info, etc
`docker top`:
```
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                15978               15957               0                   Mar04               ?                   00:52:05            influxd --reporting-disabled --bolt-path=/influx/influxd.bolt --engine-path=/influx/engine --session-length=525600
```

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

From `docker inspect`:
```
...
        "Args": [
            "--reporting-disabled",
            "--bolt-path=/influx/influxd.bolt",
            "--engine-path=/influx/engine",
            "--session-length=525600"
        ],
...
        "Image": "sha256:cc6ce7f90cdd0a6f921ae6f127f09f110bdf250c3e1336bab0a363ed25977cfe",
...
        "Config": {
...
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive"
            ],
...
            "Cmd": [
                "--reporting-disabled",
                "--bolt-path=/influx/influxd.bolt",
                "--engine-path=/influx/engine",
                "--session-length=525600"
            ],
...
            "Image": "quay.io/influxdb/influxdb:2.0.0-beta",
...
        },
...
```

__Logs:__
Include snippet of errors in log.
```
ts=2020-03-09T01:22:47.341672Z lvl=info msg=Unauthorized log_id=0LMFedNW000 error="session has expired"
```

**Comment by russorat** [comment] 2020-03-10 18:52
@dnr thanks for opening this. We will take a look.

**Comment by andig** [comment] 2021-06-09 06:11
Any progress on this? The current behaviour is really annoying.

**Comment by kristinarobinson** [comment] 2021-06-11 22:08
@andig Sorry I closed this in error, because my team isn't directly involved in the fix.  Here's an update.  The session auto-logout has been increased from 4 hours to 8 hours, or at least it's the process of being increased on a region by region basis.  The back end teams are working on coordinating a change to implement an active session timeout, that is, your session timeout limit will be reset every time you are active within the system.  I don't have an ETA on that work, however, as I'm not on those teams, and I haven't checked in on that project recently.  I hope that helps.

**Comment by Asalem1** [comment] 2021-06-17 16:26
Removing the UI team label since session management is handled by the compute & e-commerce team in unison

**Comment by nuwandavek** [comment] 2022-01-25 18:42
Has there been any update on this? Either increasing session timeout or having a config to remove auth (for local networks) would be an awesome fix.
Thank you!

**Comment by ssuchter** [comment] 2022-03-11 18:43
I also agree - it'd be nice to not have to log so frequently into the influxd instances where I don't need this level of security.

**Comment by samhld** [comment] 2022-03-11 21:37
@asalem1 this issue seems to be in reference to OSS, no?

**Comment by divinitus** [comment] 2022-03-11 22:04
> @dnr are you (still) experiencing this in OSS?

I am. Logging into OSS instance that often is definitely annoying.

**Comment by dnr** [comment] 2022-03-11 23:44
Yes, this is still annoying.

**Comment by ssuchter** [comment] 2022-03-15 16:01
I'm running:

InfluxDB 2.1.1
Server: [657e183](https://github.com/influxdata/influxdb/tree/657e1839de)
Frontend: [cc65325](https://github.com/influxdata/ui/tree/cc65325)

No, I'm not restarting the InfluxDB process overnight, or with any regularity. My instance tends to stay up for weeks to months.

**Comment by divinitus** [comment] 2022-03-15 16:15
Mine is: 
InfluxDB 2.1.1
Server: [657e183]
Frontend: [cc65325]

It's in a container under podman.

**Comment by ssuchter** [comment] 2022-03-15 16:28
FWIW, I'm not running containerized; it's a direct RPM install on Centos Stream 8, running under systemd.

**Comment by lesam** [comment] 2022-03-15 17:42
Aha! I think the issue is that the backend is tracking expiry correctly, but the browser (e.g. Chrome) is not being told about the expiry, and so expires the cookie automatically when the _browser_ restarts. There is a PR above to fix that works for me locally - at least it fixes preserving the cookie across browser restarts.

**Comment by divinitus** [comment] 2022-03-15 17:47
> Aha! I think the issue is that the backend is tracking expiry correctly, but the browser (e.g. Chrome) is not being told about the expiry, and so expires the cookie automatically when the _browser_ restarts. There is a PR above to fix that works for me locally - at least it fixes preserving the cookie across browser restarts.

The scenario for me is to have FF98 open all the time. I open a new tab, navigate to InfluxDB -> login -> watch the graphs -> close the tab. 
When i try to access it again i open a tab -> navigate to influx -> bang, have to login again. 

So at least in my dictionary this is not a browser restart. It's a new tab-close tab cycle.

**Comment by samhld** [comment] 2022-03-16 03:20
@divinitus do you have the ability to test the PR Sam Arnold mentioned: https://github.com/influxdata/influxdb/pull/23201

Perhaps that will work for tab closure as well?

**Closed** 2022-03-18 12:04 UTC
Labels: kind/bug, team/compute, severity/sev-3, v2-prod-bug

**Comment by josevnz** [comment] 2022-10-15 14:29
This is an annoying bug; I end using Grafana UI instead of Influxdb to run queries because of this bug, as the timeout is too short even for medium datasets.

**Comment by sstewart-hirez** [comment] 2022-11-08 15:32
Yes I am actually using Grafana UI as well so I don't have to login all of the time

**Comment by logmod** [comment] 2022-11-09 10:27
@lesam From what I can see, the way server-side session cookies are handled by InfluxDB is clearly understood so its just a matter of making this feature available/visible to users either by configuration or by a change to the login UI. I would even be fine with a decent default like 8h or 12h but the current setting is way too short. InfluxDB is not a banking app but a monitoring tool.

Practically all solutions with a web-interface nowadays have the option to set a userdefined "keep me logged in" flag. If the InfluxDB session timeout annoys so many people why can't this be changed?

**Comment by Bosma** [comment] 2022-11-16 18:13
InfluxDB 2.5 OSS web UI's cookie expires after an hour. I'd prefer a way to change it, it's annoying to have to re-log all the time.

**Comment by Klaital** [comment] 2023-01-04 22:16
Has there been any progress on this? I'd like to set up an always-on dashboard for my home automation. I'm running the OSS version on-prem, so I do not need high security. 

I appreciate the suggestion to just use Grafana as the UI instead. I know that will do the job.

**Comment by aerogus** [comment] 2023-01-05 10:24
I also always be logged out after a couple of minutes.
I use v2.6.1, the last one at the date.
I'd wan't a feature to be always logged in for a entire day.
I don't understand why this issue has been closed.
Where is the session length configurable ?
thx

**Comment by andreo141** [comment] 2025-04-20 19:11
Does anybody know what the maximum session length is?
