### ISSUE TITLE
Couldn't Install InfluxDB on Mac OS X EI Capitan V 10.11.6

### ISSUE THREAD

**Issue by dinesh4747** [influxdata/influxdb#7848] opened 2017-01-17 08:42 UTC
Hi All -

I was trying to install Influx DB on My Local Machine through the following commands using "brew"

brew update
brew install influxdb
ln -sfv /Users/z0025g0/Library/LaunchAgents/homebrew.mxcl.influxdb.plist ~/Library/LaunchAgents
ln -sfv /Users/z0025g0/Library/LaunchAgents/homebrew.mxcl.influxdb.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.influxdb.plist

After the installation I could also very well able to start the InfluxDB Process using below command and output result as follows:

34363bcbaf1a:etc z0025g0$ influxd -config /usr/local/etc/influxdb.conf
[run] 2017/01/17 12:02:41 InfluxDB starting, version v1.1.1, branch master, commit e47cf1f2e83a02443d7115c54f838be8ee959644
[run] 2017/01/17 12:02:41 Go version go1.7.4, GOMAXPROCS set to 8
[run] 2017/01/17 12:02:41 Using configuration at: /usr/local/etc/influxdb.conf
run: open server: listen: listen tcp :8088: bind: address already in use

The problem i face here is I am not seeing the Influxdb process runs on the default port 8083 and it strangely runs on 8088

Following command clearly proves that as well

34363bcbaf1a:etc z0025g0$ ps -ef|grep influxdb
1199232726 70029 1 0 Mon11AM ?? 0:07.94 /usr/local/opt/influxdb/bin/influxd -config /usr/local/etc/influxdb.conf
1199232726 77754 47290 0 12:04PM ttys002 0:00.00 grep influxdb
34363bcbaf1a:etc z0025g0$ lsof -Pan -p 70029 -i
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
influxd 70029 z0025g0 3u IPv6 0xebf20faaca0dcf29 0t0 TCP *:8088 (LISTEN)
influxd 70029 z0025g0 6u IPv6 0xebf20faaed8cbee9 0t0 TCP *:8086 (LISTEN)

In the config file I see that bind-address = :8086 is commented out as mentioned below and i have also tried uncommenting out and still doesnt works for me

[http]

Determines whether HTTP endpoint is enabled.

enabled = true

The bind address used by the HTTP service.

bind-address = ":8086"

I am actually looking to open the InfluxDB console in my local browser and configure the data source but that is not working I tried connecting to http://localhost:8083 0r either 8088 which actually runs but couldn't make it work

Could some one please help me with that here

**Comment by mark-rushakoff** [comment] 2017-01-17 16:59
Duplicate of https://github.com/influxdata/influxdb/issues/7760.

**Closed by mark-rushakoff** 2017-01-17 16:59 UTC
