### ISSUE TITLE
Unable to load series from storage (inconsistent state?)

### ISSUE THREAD

**Issue by gpomykala** [influxdata/influxdb#10543] opened 2018-12-06 15:38 UTC
System info: linux64 + arm32, InfluxDB v1.6.0rc0

My InfluxDB instance does not start anymore after some moderate usage.
I am getting a following on startup:
`
2018-12-06T15:27:41.164852Z	info	Open store (end)	{"log_id": "0CD1xQ0l000", "service": "store", "trace_id": "0CD1xQQ0001", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "4.322ms"}
run: open server: open tsdb store: invalid series segment
`
It turns out that somehow the data segment file /var/lib/influxdb/data/testEventsDatabase/_series/00/000 is filled with NULL chars and InfluxDB expects a magic header "SSEG" on the beginning. 
I cannot explain how the storage ended up in such state.

It is worth mentioning InfluxDB <1.5.0 starts normally with no error with same data storage (why? how?). 
Data folder dump attached.

Note: apply #10541 for debugging otherwise influxd process locks itself and hangs instead of showing an error

[influx_dump.tar.gz](https://github.com/influxdata/influxdb/files/2653701/influx_dump.tar.gz)

**Comment by jacobmarble** [comment] 2019-05-06 22:59
I've confirmed that the attached series file contains only zeros using this command:
```
for i in {0..7}; do xxd data/_internal/_series/0$i/0000 | grep -v "0000 0000 0000 0000 0000 0000 0000 0000"; done
```

A normal database, with only the _internal database, spews a lot more than this.

The code that creates series segment files is pretty clear:
- create the segment file as `foo.initializing`
- write the header
- truncate to write zeros
- close, rename, re-open

https://github.com/influxdata/influxdb/blob/72f85341bd5f76ffa28ab84c32e7066128265ccc/tsdb/series_segment.go#L59-L88

I'll review with another engineer tomorrow.

**Comment by jacobmarble** [comment] 2019-05-07 05:27
Just saw the bit about <1.5.0 starting normally. That's because there was no series file before 1.5. The series file goes along with the TSI index; it moves certain mappings to mmap-backed files on disk.

**Comment by benbjohnson** [comment] 2019-05-07 19:07
@jacobmarble I took a look at the `v1.7.6` and the `v1.6.x` code. The only thing I can think of is that the code may be flushing the metadata from the `Truncate()` call but not flushing the underlying data.

So this code here:

https://github.com/influxdata/influxdb/blob/01c8dd416270f424ab0c40f9291e269ac6921964/tsdb/series_segment.go#L67-L75

Should be:

```go
// Write header to file and close.
hdr := NewSeriesSegmentHeader()
if _, err := hdr.WriteTo(f); err != nil {
	return nil, err
} else if err := f.Truncate(int64(SeriesSegmentSize(id))); err != nil {
	return nil, err
} else if err := f.Sync(); err != nil {
	return nil, err
} else if err := f.Close(); err != nil {
	return nil, err
}
```

What do you think?

**Comment by jacobmarble** [comment] 2019-05-07 21:14
That's a good idea.

I have repro'd the issue with @gpomykala's data, then deleted the series segment files and it looks like they are re-created correctly on start. I have an idea for recovery:
> If series file is corrupt (fails to open) then delete the series segment and try again

**Comment by jacobmarble** [comment] 2019-05-07 21:24
Turns out that re-created series segment files do not have the same IDs as before, so index entries point to incorrect data.

A suitable manual recovery in this situation is to delete the series file **and** the TSI indexes, then recreate the TSI indexes, which is a manual process.

**Comment by jacobmarble** [comment] 2019-05-09 15:59
@gpomykala the current theory is that your environment is hitting a normal situation described in Linux (but not BSD) `man 2 close`:
> A successful close does not guarantee that the data has been successfully saved to disk, as the kernel uses the buffer cache to defer writes.  Typically, filesystems do not flush buffers when a file is closed.  If you need to be sure that the data is physically stored on the underlying disk, use fsync(2).  (It will depend on the disk hardware at this point.)

#13836 is the remedy. #13860 backports to InfluxDB 1.7

**Comment by mschnelte** [comment] 2019-05-10 09:05
I am not sure if I completely agree with closing this issue. The PR #13836 will prevent the zeros written to disc, ok. 
However - in the spirit of robustness - should you not also harden the influxdb startup to not hang on startup in case of such or similar issues of corrupted data?

**Comment by jacobmarble** [comment] 2019-05-10 18:26
@mschnelte I agree, so reopened.

**Comment by jacobmarble** [comment] 2019-05-14 02:18
#13836 and #10541 have been backported to the 1.7 branch, which is what I'm using to check this behavior. The process exits with status 1, and logs indicate the segment that is problematic. @gpomykala are you not seeing this behavior?
```
2019-05-14T01:46:19.279663Z     info    InfluxDB starting       {"log_id": "0FP092fl000", "version": "unknown", "branch": "unknown", "commit": "unknown"}
2019-05-14T01:46:19.279745Z     info    Go runtime      {"log_id": "0FP092fl000", "version": "go1.12.4", "maxprocs": 8}
2019-05-14T01:46:19.280941Z     info    Using data dir  {"log_id": "0FP092fl000", "service": "store", "path": "/Users/jacobmarble/influxdb/data"}
2019-05-14T01:46:19.281011Z     info    Compaction settings     {"log_id": "0FP092fl000", "service": "store", "max_concurrent_compactions": 4, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2019-05-14T01:46:19.281027Z     info    Open store (start)      {"log_id": "0FP092fl000", "service": "store", "trace_id": "0FP0934G000", "op_name": "tsdb_open", "op_event": "start"}
2019-05-14T01:46:19.281305Z     error   Unable to open series file      {"log_id": "0FP092fl000", "path": "/Users/jacobmarble/influxdb/data/_internal/_series", "partition": 0, "error": "invalid series segment"}
2019-05-14T01:46:19.281321Z     info    Open store (end)        {"log_id": "0FP092fl000", "service": "store", "trace_id": "0FP0934G000", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.295ms"}
run: open server: open tsdb store: invalid series segment
exit status 1
```

From here, manual intervention is required. The data (TSM files) are intact, but the series file is not. Since TSI depends on the series file, the manual steps to recover are:
- delete index files and series file (data/dbname/_series)
- rebuild TSI index (series file should implicitly be created)

Your dump files don't contain TSI indexes, so I assume you're using inmem.

**Comment by gpomykala** [comment] 2019-05-28 09:01
Hi,
I confirm that since race condition had been fixed the process exits with
an error indicating a problem with a series file.

wt., 14.05.2019, 04:19 użytkownik Jacob Marble <notifications@github.com>
napisał:

**Comment by jacobmarble** [comment] 2019-05-28 15:00
Great!

**Closed by jacobmarble** 2019-05-28 15:00 UTC
Labels: 1.x, kind/bug
