### ISSUE TITLE
During backup, the tmp file is not deleted.

### ISSUE THREAD

**Issue by limhwanhee** [influxdata/influxdb#20732] opened 2021-02-09 08:17 UTC
__Steps to reproduce:__

- I ran influxdb with windows binary file.
- Then, I proceeded with the backup.
- **influxd backup -portable -db TEST "C:\test"**
- The backup was successful.
- However, a tmp folder was created, which is a large file size.
![image](https://user-images.githubusercontent.com/26052547/107333944-73f88580-6af9-11eb-9db3-943b44347a60.png)

- I've seen a pull request that said it solved this problem, but it didn't.
[16289](https://github.com/influxdata/influxdb/issues/16289#issuecomment-756983595)

Below is the tmp file removal failure log.

`2021-02-09T07:53:31.283452Z     warn    backup could not remove temporary snapshot directory    {"log_id": "0SDS9LbG000", "engine": "tsm1", "path": "C:\\Users\\219034\\.influxdb\\data\\TEST\\autogen\\2\\3.tmp", "error": "remove C:\\Users\\219034\\.influxdb\\data\\TEST\\autogen\\2\\3.tmp\\000000344-000000002.tsm: Access is denied."}`

__Expected behavior:__

- The backup should be performed successfully and no tmp folder should be left.

__Actual behavior:__

- The backup was performed successfully, but the tmp file was not removed.

__Environment info:__

* System info: Windows 10 Pro 64bit
* InfluxDB version: InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)

__Config:__
- Default

**Comment by danxmoran** [comment] 2021-02-09 14:01
Note for later, so we don't forget: the same code is in 2.x, so any fixes should apply there as well

**Comment by cbonte** [comment] 2021-02-10 21:48
A similar issue was reported here : #16289
From some tests, I noticed that some commits resolved the issue in my case (https://github.com/influxdata/influxdb/issues/16289#issuecomment-756983595)

But for an unknown reason, the commits disappeared in between 1.8.4-rc3 and 1.8.4-rc4. I opened an issue to undestrand why : #20685

**Comment by lesam** [comment] 2021-09-07 19:25
This is definitely a duplicate of #16289 , the errors there are also 'Access Denied' ( see https://github.com/influxdata/influxdb/issues/16289#issuecomment-827352936) . This is a known issue, fixed on Linux but still work to be done on Windows.

**Closed by lesam** 2021-09-07 19:25 UTC
Labels: area/backup and restore, area/storage, 1.x, area/2.x
