### ISSUE TITLE
writing duplicate points  and   Why  the two points  with the same (measurement name, tag set，timestamp) can be query   in the db.

### ISSUE THREAD

**Issue by superwood** [influxdata/influxdb#6853] opened 2016-06-16 07:19 UTC
```
select * from mobvista where time=1465689600000000000 and product='M' and channel='ADNRealTime';
name: mobvista
--------------
time			channel		click		cost		impression	install	product	profit		revenue	source
1465689600000000000	ADNRealTime	8.4437569e+07	35274.09	8.825309e+06	60101	M	22137.410000000003	57411.5	M
1465689600000000000	ADNRealTime	8.4437569e+07	35274.09	8.825309e+06	60101	M	22137.410000000003	57411.5	M
```

**Comment by gunnaraasen** [comment] 2016-06-16 18:29
What is the InfluxDB version? Can you provide the raw line protocol points and the output of the following query?

```
select * from mobvista where time=1465689600000000000 and product='M' and channel='ADNRealTime' group by *
```

**Comment by jeffdeville** [comment] 2016-06-17 18:07
I've got the same problem. Restarting the database seems to flush the cache and fix the problem.  I'm on 0.13.0.

**Comment by gunnaraasen** [comment] 2016-06-17 23:14
@superwood @jeffdeville Can you check if the behavior occurs in 1.0.0-beta1 and also provide steps to reproduce.

**Comment by jeffdeville** [comment] 2016-06-17 23:56
Yeah, beta1 also has the problem.  Hard to provide specific steps in my case, because this is a big migration from my existing system to influx. I'll think about whether there's a way to capture a script of the entire process easily, so I can send that to you.

**Comment by gunnaraasen** [comment] 2016-06-18 01:19
@jeffdeville I realized the results above aren’t duplicates. They’re off by two months, which is expected since the `time > now() - 60d` period doesn’t overlap precisely with the `group by time(60d)` period, which snaps to logical boundaries.

**Comment by jeffdeville** [comment] 2016-06-18 17:09
@gunnaraasen I've created a ruby script, and DM'd it to you in slack that replicates the problem.

**Comment by superwood** [comment] 2016-06-20 10:11
@gunnaraasen   

 I'm on 0.13.0 too. 

> select * from mobvista where time>=1465689600000000000 and product='M' and channel='ADNRealTime' group by *
name: mobvista
tags: channel=ADNRealTime, product=M, source=M
time			click		cost		impression	install	profit			revenue
----			-----		----		----------	-------	------			-------
1465747200000000000	7.5566267e+07	31886.99	7.746903e+06	56041	19662.98		51549.97
1465833600000000000	8.7419948e+07	37193.69	9.286737e+06	63580	20055.54		57249.23
1465920000000000000	8.9109145e+07	37728.38	9.547496e+06	63226	19946.11		57674.49
1466006400000000000	8.9289676e+07	37382.99	1.0331212e+07	64025	19322.65		56705.64
1466092800000000000	9.3959255e+07	40479.31	1.2326814e+07	69703	20231.950000000004	60711.26
1466179200000000000	9.6476343e+07	49188.2		1.7912145e+07	83380	21690.83		70879.03
1466265600000000000	9.681162e+07	53595.38	1.9197923e+07	92420	21784.450000000004	75379.83

**Comment by superwood** [comment] 2016-06-20 10:14
But   restart the influxdb  seems  fix the problem. 


> select * from mobvista where time>=1465689600000000000 and product='M' and channel='ADNRealTime' group by *
name: mobvista
tags: channel=ADNRealTime, product=M, source=M
time			click		cost		impression	install	profit			revenue
----			-----		----		----------	-------	------			-------
1465747200000000000	7.5566267e+07	31886.99	7.746903e+06	56041	19662.98		51549.97
1465833600000000000	8.7419948e+07	37193.69	9.286737e+06	63580	20055.54		57249.23
1465920000000000000	8.9109145e+07	37728.38	9.547496e+06	63226	19946.11		57674.49
1466006400000000000	8.9289676e+07	37382.99	1.0331212e+07	64025	19322.65		56705.64
1466092800000000000	9.3959255e+07	40479.31	1.2326814e+07	69703	20231.950000000004	60711.26
1466179200000000000	9.6476343e+07	49188.2		1.7912145e+07	83380	21690.83		70879.03
1466265600000000000	9.681162e+07	53595.38	1.9197923e+07	92420	21784.450000000004	75379.83

**Comment by superwood** [comment] 2016-06-20 10:16
There is the  the output of the following query.


> select * from mobvista where time>=1465689600000000000 and product='M' and channel='ADNRealTime' group by *
name: mobvista
tags: channel=ADNRealTime, product=M, source=M

time			click		cost		impression	install	profit			revenue


----			-----		----		----------	-------	------			-------
1465747200000000000	7.5566267e+07	31886.99	7.746903e+06	56041	19662.98		51549.97
1465833600000000000	8.7419948e+07	37193.69	9.286737e+06	63580	20055.54		57249.23
1465920000000000000	8.9109145e+07	37728.38	9.547496e+06	63226	19946.11		57674.49
1466006400000000000	8.9289676e+07	37382.99	1.0331212e+07	64025	19322.65		56705.64
1466092800000000000	9.3959255e+07	40479.31	1.2326814e+07	69703	20231.950000000004	60711.26
1466179200000000000	9.6476343e+07	49188.2		1.7912145e+07	83380	21690.83		70879.03
1466265600000000000	9.681162e+07	53595.38	1.9197923e+07	92420	21784.450000000004	75379.83

**Comment by e-dard** [comment] 2016-06-20 10:21
@gunnaraasen did you get anywhere with the repro script?

**Comment by superwood** [comment] 2016-06-20 10:27
@gunnaraasen  How to fix it ?      Restart db  is not a good  idea.

**Comment by gunnaraasen** [comment] 2016-06-20 16:30
@e-dard I was able to reproduce the duplicate points on 1.0.0-beta1 with the script and the duplicates disappear after a restart of `influxd`.

**Comment by superwood** [comment] 2016-06-22 15:48
@gunnaraasen  @e-dard   restart db  is the only solution?

**Comment by gunnaraasen** [comment] 2016-06-22 22:36
Restarting the database fixes the issue. We're still not able to consistently reproduce the issue, which is making this bug hard to track down.

**Comment by gunnaraasen** [comment] 2016-06-23 00:40
@superwood @jeffdeville Can you check if https://github.com/influxdata/influxdb/pull/6897 resolves the duplicate point issue?

**Comment by jeffdeville** [comment] 2016-06-23 00:43
Did it fix it for the script I sent you?

**Comment by superwood** [comment] 2016-06-23 03:13
@gunnaraasen 
 I will  try and see what the result would be.

**Comment by brewneaux** [comment] 2016-06-27 19:56
I'm still getting duplicate points on version 1.1.0~n201606270800.  See also https://github.com/influxdata/influxdb/issues/6632

**Comment by jwilder** [comment] 2016-07-18 22:54
@jeffdeville @superwood #7027 may fix this issue.  This sounds similar to #6946 and restarting the DB causes the duplicates to disappear.

**Comment by jwilder** [comment] 2016-07-19 02:06
Closing this as a duplicate of #6946.

**Closed by jwilder** 2016-07-19 02:06 UTC
Labels: category/writes
