### ISSUE TITLE
Arithmetic inside aggregation function

### ISSUE THREAD

**Issue by maded2** [influxdata/influxdb#6886] opened 2016-06-21 13:39 UTC
## Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

Allow Arithmetic operations inside aggregation functions

Example:

```
Price          OrderSize
100             2
150             3
200             4
```

select sum( Price * OrderSize ) from Orders

expecting the following result: 1450

Currently, I've to store the 'Price * OrderSize' in a separate column so that I can compute the sum, which is costing me alot of storage.

**Comment by jsternberg** [comment] 2016-06-21 13:53
Closing as a duplicate of #5971. Thanks!

**Closed by jsternberg** 2016-06-21 13:53 UTC
