### ISSUE TITLE
Performance degradation on influx 0.11 and memory saturation on high volume.

### ISSUE THREAD

**Issue by sjahn90** [influxdata/influxdb#6131] opened 2016-03-28 01:25 UTC
We are conducting stress test with influxdb 0.10 and 0.11 based TSM engine.
When we start to test on influx db 0.10, we can write 200,000 points per sec. But when we change to influxdb 0.11 on same machine, the result is too different, writing 50,000 points per sec. It looks like to similar influx db 0.8 performance.

To find the number of points per sec, we used _internal database.
https://docs.influxdata.com/influxdb/v0.10/troubleshooting/statistics/.

Is there any write performance issue on influx 0.11 ?

H/W spec is 1 CPU (ES 2620 v3, hex core), 32M/M, 4 x SSD(500M). Our goal is to write 10,000,000 ~ 15,000,000 points every 5 minutes based on 100,000 measurements (no tag, 5 values).

Our test scripts is like this. It is to generate many points on multiple clients 
for (i = 0; i < 20; i++)
 ./wrk -t1 -c1 -d30 -s influx_test.lua &

wrk is HTTP benchmarking tool. https://github.com/wg/wrk

influx_test.lua is to write batch job(1000 point per 1 batch) into influx db.

Another issue is memory saturation during stress test. To mitigate memory saturation, we've changed cache-max-memory-size (2.5G) and awl-flush-cold-interval(1m) on influx 0.10. But the issue is still remained.
Could you give more tips to solve memory issue ?

**Comment by jwilder** [comment] 2016-03-28 15:32
@sjahn90 Can you attach your `influx_test.lua` script?

**Comment by mark-rushakoff** [comment] 2016-03-28 15:53
@sjahn90 can you also elaborate on the memory saturation you're observing?

Operating system caching can make it appear that InfluxDB (or any Go program) is consuming large amounts of memory, when in reality, the operating system is treating otherwise unused memory as cache for the filesystem, etc.; and that memory is actually available for the operating system to assign to other processes as necessary.

**Comment by sjahn90** [comment] 2016-03-29 01:15
@mark-rushakoff When we run top command, we found that influxdb used more than 30G. And then use swap memory. If there is no memory issue, we will increase the number of measurement until more than 10,000,000.
 
@jwilder we attached script. For the number of point per write, we can set as follow.
./wrk -t1 -c1 -d30 http://localhost:8086 -s influx_test.lua -- 1 1 1000. 1000 means the number of point per write for batch job. You can change the value.


[wrk_influx010_write.lua.txt](https://github.com/influxdata/influxdb/files/192702/wrk_influx010_write.lua.txt)

**Comment by sjahn90** [comment] 2016-03-29 02:34
To find quickly memory issue, it's better to increase the measurement from 100,000 to 1,000,000. To do so, have to change variable in test script. The total number of measument = max_metric_cnt * max_pop_cnt * max_si_cnt

local max_metric_cnt = 10
local max_pop_cnt = 10 => 100
local max_si_cnt = 1000

**Comment by jwilder** [comment] 2016-03-31 00:16
@sjahn90 I was able to reproduce with your script.  This is regression introduced by #5816. 

#5816 added stats tracking per measurement.  This test script is creating 100,000 measurements (or more) which creates a lot of lock contention on the stats lock [here](https://github.com/influxdata/influxdb/blob/0.11/influxvar.go#L14).  
```
goroutine 130 [semacquire]:
sync.(*Mutex).Lock(0xcbb8c8)
	/usr/local/go1.4.3/src/sync/mutex.go:66 +0xd3
github.com/influxdata/influxdb.NewStatistics(0xc20d240fc0, 0x1b, 0x867730, 0xb, 0xc20d23d770, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxvar.go:14 +0x41
github.com/influxdata/influxdb/tsdb.NewMeasurement(0xc20d244300, 0x5, 0xc2080e6a00, 0x5)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:407 +0x37c
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).CreateMeasurementIndexIfNotExists(0xc2080e6a00, 0xc20d244300, 0x5, 0xb5)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:127 +0xad
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).CreateSeriesIndexIfNotExists(0xc2080e6a00, 0xc20d244300, 0x5, 0xc20d23cd50, 0xc20d23cc30)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:106 +0x8e
github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xc208432b40, 0xc209fa6000, 0x2686, 0x3000, 0x0, 0x0)
```

This lock ends up being held for a long time due to some sorting in the `expvar` package:

```
goroutine 47 [runnable]:
sort.medianOfThree(0xf122f0, 0xc20d2531a0, 0x176a, 0x1764, 0x175e)
	/usr/local/go1.4.3/src/sort/sort.go:79
sort.doPivot(0xf122f0, 0xc20d2531a0, 0x173b, 0x176b, 0xf, 0x176c)
	/usr/local/go1.4.3/src/sort/sort.go:109 +0x137
sort.quickSort(0xf122f0, 0xc20d2531a0, 0x173b, 0x176b, 0x13)
	/usr/local/go1.4.3/src/sort/sort.go:173 +0xa9
sort.quickSort(0xf122f0, 0xc20d2531a0, 0x16d8, 0x179a, 0x15)
	/usr/local/go1.4.3/src/sort/sort.go:180 +0x178
sort.quickSort(0xf122f0, 0xc20d2531a0, 0x1552, 0x185b, 0x17)
	/usr/local/go1.4.3/src/sort/sort.go:180 +0x178
sort.quickSort(0xf122f0, 0xc20d2531a0, 0x0, 0x26f4, 0x1b)
	/usr/local/go1.4.3/src/sort/sort.go:180 +0x178
sort.Sort(0xf122f0, 0xc20d2531a0)
	/usr/local/go1.4.3/src/sort/sort.go:200 +0x7b
sort.Strings(0xc20c0ae000, 0x26f4, 0x3000)
	/usr/local/go1.4.3/src/sort/sort.go:276 +0x82
expvar.Publish(0xc20d251d40, 0x29, 0xf13650, 0xc2084a9000)
	/usr/local/go1.4.3/src/expvar/expvar.go:261 +0x38d
expvar.NewMap(0xc20d251d40, 0x29, 0x0)
	/usr/local/go1.4.3/src/expvar/expvar.go:287 +0xc3
github.com/influxdata/influxdb.NewStatistics(0xc20d251d40, 0x29, 0x867730, 0xb, 0xc20d251d70, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/influxvar.go:20 +0xda
github.com/influxdata/influxdb/tsdb.NewMeasurement(0xc20b9a4340, 0x14, 0xc2080e6910, 0x14)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:407 +0x37c
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).CreateMeasurementIndexIfNotExists(0xc2080e6910, 0xc20b9a4340, 0x14, 0x14)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:127 +0xad
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).CreateSeriesIndexIfNotExists(0xc2080e6910, 0xc20b9a4340, 0x14, 0xc20b9a8060, 0xc20b99df80)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/meta.go:106 +0x8e
github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xc208424900, 0xc20b5d2000, 0x3e8, 0x400, 0x0, 0x0)
	/Users/jason/go/src/github.com/influxdata/influxdb/tsdb/shard.go:236 +0x276
```

Stats with the locks in `0.11.0`:

```
$ wrk -t1 -c2 -d10s "http://127.0.0.1:8086" -s ./wrk_influx010_write.lua.txt -- 1 4 1000
thread 1 created
total_data_points: 100000, total_req_count: 100, my_req_count: 25
Running 10s test @ http://127.0.0.1:8086
  1 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   972.15ms  689.26ms   1.93s    66.67%
    Req/Sec     1.22      1.64     4.00     77.78%
  9 requests in 10.09s, 1.26KB read
  Socket errors: connect 0, read 0, write 0, timeout 3
Requests/sec:      0.89
Transfer/sec:     127.59B
------------------------------
thread 1 made 12 requests and got 9 responses
```

Stats w/ the locks removed:

```
$ wrk -t1 -c2 -d10s "http://127.0.0.1:8086" -s ./wrk_influx010_write.lua.txt -- 1 4 1000
thread 1 created
total_data_points: 100000, total_req_count: 100, my_req_count: 25
Running 10s test @ http://127.0.0.1:8086
  1 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.86ms   12.98ms 105.99ms   79.12%
    Req/Sec   144.73     38.03   202.00     68.00%
  1457 requests in 10.10s, 203.47KB read
Requests/sec:    144.21
Transfer/sec:     20.14KB
------------------------------
thread 1 made 1459 requests and got 1457 responses
```

@mark-rushakoff I think we need to revisit how measurement stats are collected.  We don't see this behavior w/ `influx_stress` because it creates a single measurement with tags to create 100k series.  The script in this issue creates 100k measurements (no tags).

@sjahn90 A workaround would be to use fewer measurements with more tags instead of unique measurements until we figure out a good fix for this.

**Closed** 2016-03-31 16:35 UTC
Labels: category/performance

**Comment by sjahn90** [comment] 2016-04-01 00:29
@jwilder Thanks for your support. We'll try your workaround until influxdb 0.12.

**Comment by jwilder** [comment] 2016-04-01 01:09
@sjahn90 0.11.1 will have the fix. It's available now.
