### ISSUE TITLE
Unable to install InfluxDB 0.12 on Ubuntu 15.10

### ISSUE THREAD

**Issue by poznachowski** [influxdata/influxdb#6253] opened 2016-04-07 12:48 UTC
My setup:
```
➜  info uname -a
Linux dziesio-laptop 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
➜  info cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

When I try to install InfluxDB 0.12 I get:
```
sudo dpkg -i influxdb_0.12.0-1_amd64.deb 
(Reading database ... 252789 files and directories currently installed.)
Preparing to unpack influxdb_0.12.0-1_amd64.deb ...
Unpacking influxdb (0.12.0-1) over (0.12.0-1) ...
Setting up influxdb (0.12.0-1) ...
Failed to execute operation: Operation not supported
dpkg: error processing package influxdb (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 influxdb
```

It seems to work fine on Ubuntu 15.04.

**Comment by blahspam** [comment] 2016-04-20 21:36
I was also receiving the `Operation not supported` error when installing via apt. This seems to occur because, in my case at least, the service was masked (confirmed with `systemctl list-unit-files`)

I was able to work around it by unmasking the service manually:

```
systemctl unmask influxdb.service
``` 

I was then able to enable and start the service normally. 

Hope this helps

**Comment by jsternberg** [comment] 2016-09-19 20:30
This seems to be caused by masking the service as @blahspam has mentioned. I'm going to close this since I'm not sure what we should do if the service is masked. If there is some standard procedure for debian packages and what to do when a service is masked, please send it to me and I'll see if we can adhere to it. Thanks.

**Closed by jsternberg** 2016-09-19 20:30 UTC
Labels: area/packaging
