### ISSUE TITLE
[0.9.3] Non-admin can't select database in the web UI

### ISSUE THREAD

**Issue by malaakso** [influxdata/influxdb#3922] opened 2015-09-01 12:28 UTC
I have created an admin and some regular users for databases and enabled authentication. There seems to be no way for the regular users to use the web UI, since it is impossible to list or select the database they have privileges on. Maybe USE database_name should be allowed on the web UI?

**Comment by beckettsean** [comment] 2015-09-01 17:59
@malaakso what version of the database are you running?

**Comment by malaakso** [comment] 2015-09-01 18:01
I'm running 0.9.3.

**Comment by jsternberg** [comment] 2016-08-12 16:51
Duplicate of #4785.

**Closed by jsternberg** 2016-08-12 16:51 UTC
Labels: admin
