### ISSUE TITLE
[0.11.0] Queries involving relative time span past now()

### ISSUE THREAD

**Issue by 121watts** [influxdata/influxdb#5646] opened 2016-02-12 01:07 UTC
The following query should only return 60 points from the database

```
use _internal
```

```
SELECT max(fieldsCreate) AS fieldsCreate FROM "shard" WHERE time > now() - 1h GROUP BY time(1m)
```

a few thousand instead.

The current work around I've used is:

```
SELECT max(fieldsCreate) AS fieldsCreate FROM "shard" WHERE time > now() - 1h AND time < now() GROUP BY time(1m)
```

**Comment by rossmcdonald** [comment] 2016-02-12 14:22
Dupe of #5636. Implicit upper bounds with the new query engine have issues. This should hopefully be fixed by #5641.

**Closed by rossmcdonald** 2016-02-12 14:22 UTC
