### ISSUE TITLE
[feature request] Interpolation option with group by time

### ISSUE THREAD

**Issue by esecules** [influxdata/influxdb#4464] opened 2015-10-15 21:52 UTC
Is it possible to add an option to group by time queries that will help normalize irregularities seen when data sources operate at an irregular frequency? It would be nice to see something that if there are more than 1 points in a time slice it would choose the last one, and if there are 0 it will choose whatever the most recent point is. 

I am trying to do a stacked graph of disk usage grouped by machine and time, but some machines report faster than others, so It ends up looking like a sawtooth pattern because not all of the the machines are included in each time slice.

It would not be feasible to increase the time slice that I group by since I would be double counting some of the faster machines, unless I could nest the sum() and the last() aggregate functions. (i think)

**Comment by beckettsean** [comment] 2015-10-15 21:57
Related to https://github.com/influxdb/influxdb/issues/3099

**Comment by beckettsean** [comment] 2016-02-24 20:11
Also related to https://github.com/influxdata/influxdb/issues/5040

**Comment by rbetts** [comment] 2018-01-30 20:52
closing this as a duplicate of #5040; we currently separate interpolate as fill from aggregate (as reduce).

**Closed by rbetts** 2018-01-30 20:52 UTC
Labels: area/queries, kind/feature request
