### ISSUE TITLE
SHOW TAG VALUES WITH KEY WHERE fails if the tag name is "name"

### ISSUE THREAD

**Issue by sofixa** [influxdata/influxdb#6581] opened 2016-05-09 10:54 UTC
### Bug report

InfluxDB 0.11.1 running on top of Debian Jessie(8.4)

I have a measurement, virtualmachine, which contains data like this(simplified version):
```
host=vcenter-01.adm,cluster=cluster-01,name=vmname-01,datastore=blabla32 cpu_usage_average=1531513,mem_usage_average=135313
```

Using Grafana, i've tried to create a template variable with the datastore(a tag) of a currently selected VM(by the tag name, in another template variable).

Expected behavior:

```
SHOW TAG VALUES WITH KEY ="datastore" WHERE "name" =~ /$name/	
```
I hoped that would give me the datastore on which $name is residing.

However, I get all the datastores, regardless of the value of $name.

I find this behaviour only with the tag "name", if i filter on the tag $host, i get proper data(filtered by host).

I'll probably end up using SELECT instead of SHOW VALUES, but nonetheless i find it weird that the tag "name" doesn't work properly(contrary to other tags).

**Comment by jsternberg** [comment] 2016-05-09 12:38
Can you try this with 0.12 or newer? This seems similar to #6034.

**Comment by sofixa** [comment] 2016-05-09 13:04
Frankly, i am a bit scared because we have ~7.66 Million series and InfluxDB's startup takes ~40mins.
I'll try to do a cleanup of all the data and update to 0.12.

**Comment by jsternberg** [comment] 2016-05-09 13:06
Ok. When I tried to run it against a copy of v0.11.0, it worked for me. Can you try launching a local server and giving me a reproducer? This works for me:

```
> create database mydb
> use mydb
Using database mydb
> insert cpu,host=server01,name=jsternberg value=2
> show tag values with key = host where "name" = 'jsternberg'
name: cpu
---------
key     value
host    server01

> show tag values with key = host where "name" = 'h'
> show tag values with key = host where "name" =~ /j/
name: cpu
---------
key     value
host    server01

> show tag values with key = host where "name" =~ /h/
```

**Comment by sofixa** [comment] 2016-05-09 13:14
Maybe something changed between 0.11 and 0.11.1? I'll give it a few more tries on our test server.

**Comment by sofixa** [comment] 2016-05-09 13:34
Btw, with your example, to reproduce the problem i'm encountering, add extra data with another tag value for "name", like this
```
insert cpu,host=server06,name=jserg value=531
```

And then 
```
show tag values with key = host where "name" = 'jsternberg'
```
will show server06, altough it shouldn't.

**Comment by jsternberg** [comment] 2016-05-09 13:37
Ah, I can reproduce now. No need to try upgrading to 0.12.

**Comment by sofixa** [comment] 2016-05-09 13:49
So this won't work in 0.12 as well? Bummer.
What's even worse is that i can't seem to use a select query in Grafana's template variables, since it uses only the value from the first column from the InfluxDB result, which is the timestamp...

**Comment by jsternberg** [comment] 2016-05-09 16:15
This will be in 0.13.

I'll leave this ticket open until we merge it back to master so we don't forget to merge it back.

**Comment by sofixa** [comment] 2016-05-09 16:22
Cool, thanks.

**Closed** 2016-05-11 17:04 UTC
Labels: category/queries

**Comment by pf23** [comment] 2018-05-15 03:49
Seems like I met similar issue. 
![image](https://user-images.githubusercontent.com/11000915/40035748-d55af152-5835-11e8-8871-047f422bad8f.png)

But the test case works fine for me. 
![image](https://user-images.githubusercontent.com/11000915/40035777-f8e5d510-5835-11e8-8cb7-69747bc900d2.png)

Could anyone give any advice?
