### ISSUE TITLE
[0.9.4.2] HTTP API: Columns do not match values in some JSON returns

### ISSUE THREAD

**Issue by RuneKokNielsen** [influxdata/influxdb#4453] opened 2015-10-15 12:50 UTC
Hello there

While working on generically parsing data fetched through the HTTP API I stumbled upon some weird behavior which I assume to be a bug.

When I use the *-selector to select all columns then the returned data will be ordered so that the ordering in the "columns"-data matches the ordering in the "values"-data. This is a good property since it allows for generic interpretation.

However, when I issue a query with specific selectors the ordering of the returned "columns"-data and "values"-data wont always match. The "columns"-data consistently match the ordering in the query (which I assume is intended behaviour) while the "values"-data will be ordered in a non-predictable way.

EXAMPLE 1 (no tags):
Query:
`SELECT value, time FROM test WHERE tag1='-1' AND tag2='0'`
Result:
```
{
    "results": [
        {
            "series": [
                {
                    "name": "test",
                    "columns": [
                        "value",
                        "time"
                    ],
                    "values": [
                        [
                            "2015-10-15T11:17:58.894608Z",
                            23.041
                        ],
                        [
                            "2015-10-15T11:17:59.238897Z",
                            23.073
                        ],(...)
```

In this example the "time" and "value" attributes are interchanged in the "values"-data but not in the "columns"-data.

EXAMPLE 2 (two tags):
Query:
`SELECT tag1, tag2, value, time FROM test WHERE tag1='-1' AND tag2='0'`
Result:
```
{
    "results": [
        {
            "series": [
                {
                    "name": "test",
                    "columns": [
                        "tag1",
                        "tag2",
                        "value",
                        "time"
                    ],
                    "values": [
                        [
                            "2015-10-15T11:17:58.894608Z",
                            "0", (tag2 value)
                            23.041,
                            "-1" (tag1 value)
                        ],
                        [
                            "2015-10-15T11:17:59.238897Z",
                            "0", (tag2 value)
                            23.073,
                            "-1" (tag1 value)
                        ],(...)
```

Again the "columns"-data match the ordering in the query. The data in "values", however, is ordered by time - tag - value - tag which does not seem logical. 

I would expect the ordering in the "values"-data to always match the query or alternatively the ordering in the "columns"-data to match the ordering in the "values"-data.

I am running Ubuntu 14.10 64-bit. InfluxDB was installed using the deb package from https://influxdb.com/docs/v0.9/introduction/installation.html downloaded yesterday and uses the default configuration.

**Comment by beckettsean** [comment] 2015-10-15 17:38
related to  https://github.com/influxdb/influxdb/issues/3821

**Comment by beckettsean** [comment] 2015-10-15 17:40
@GaryLazerEyes apologies I read quickly and didn't notice the column mismatch in your second example. This does appear to be a bug, although not one I've seen in the CLI return format, which just parses the JSON.

**Comment by GaryLazerEyes** [comment] 2015-10-16 11:18
I just checked and the issue is also visible through CLI as seen in the example below where time and value is interchanged:

 ```
> SELECT value, manifold_id, time FROM test WHERE tag1='-1' AND tag2='0' LIMIT 10
name: test
--------------
value				manifold_id	time
2015-10-16T10:05:45.689645Z	-1		21.771
2015-10-16T10:05:46.044321Z	-1		21.876
2015-10-16T10:05:46.367773Z	-1		21.924
2015-10-16T10:05:46.688701Z	-1		21.997
2015-10-16T10:05:47.021792Z	-1		22.005
2015-10-16T10:05:47.35441Z	-1		22.051
2015-10-16T10:05:47.687872Z	-1		22.073
2015-10-16T10:05:48.021238Z	-1		22.139
2015-10-16T10:05:48.353449Z	-1		22.233
2015-10-16T10:05:48.686912Z	-1		22.238
 ```

**Comment by otoolep** [comment] 2015-10-16 14:06
This is a known issue, which we hope to fix soon. Everything should be fine if `time` is select first.

https://github.com/influxdb/influxdb/issues/3779

**Comment by jsternberg** [comment] 2016-05-17 23:43
This is for an older version of the software and I don't think this issue exists anymore in the latest version. I'm going to close this issue. If you encounter this again, please open a new issue. Thank you.

**Closed by jsternberg** 2016-05-17 23:43 UTC
Labels: category/queries
