### ISSUE TITLE
EOF returned when creating already existing bucket

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#11224] opened 2019-01-17 17:42 UTC
If you try and create a bucket that already exists you get an `EOF`, which is not helpful.

#### Repro

With fresh `.influxdbv2`

`$ influx setup`

```
⇒  influx bucket find
ID			Name		Retention	Organization	OrganizationID
03433857f5c1e000	eddbucket	0s		eddorg		03433857f581e000

edd@Alameda:~/go/src/github.com/influxdata/influxdb|master
⇒  influx bucket create -n eddbucket
EOF
```

**Comment by jademcgough** [comment] 2019-01-23 00:57
I can't repro this:
```
influx --token xxx bucket create -n jadebucket --org jadeorg
Error: Bolt/CreateBucket: <conflict> bucket with name jadebucket already exists.
```

The EOF may have been caused by https://github.com/influxdata/influxdb/issues/10776, which is now resolved.

**Comment by jademcgough** [comment] 2019-01-23 00:58
Closing, but feel free to reopen if it's still an issue.

**Closed by jademcgough** 2019-01-23 00:58 UTC
Labels: area/cli
