### ISSUE TITLE
Flaky: Flux end to end tests

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#12891] opened 2019-03-26 11:20 UTC
I got this red run on a PR: https://circleci.com/gh/influxdata/influxdb/36696

```
--- FAIL: TestFluxEndToEnd (23.09s)
    --- PASS: TestFluxEndToEnd/aggregate_empty_window.flux (0.42s)
    --- FAIL: TestFluxEndToEnd/aggregate_fill_window.flux (0.61s)
    --- FAIL: TestFluxEndToEnd/aggregate_window.flux (0.53s)
    --- FAIL: TestFluxEndToEnd/limit_offset.flux (0.58s)
    --- FAIL: TestFluxEndToEnd/lowestCurrent.flux (0.53s)
```

I've attached the build file.

[build_36696_step_108_container_0.txt](https://github.com/influxdata/influxdb/files/3007865/build_36696_step_108_container_0.txt)

**Comment by aanthony1243** [comment] 2019-04-02 01:19
@e-dard I can dig deeper into this this week, but it looks like if there's something flaky (e.g. they sometimes pass), that it's likely the write-path in the test isn't reliable.  will try to figure if the reliability is expected (e.g. it works but is slower than the test expects) or if it seems to be something more critical in how the test framework is set up.  

but if you look at the diffs printed from the tests, the test query returns with zero rows and no errors, which usually is the case when no data comes across from storage.

**Comment by e-dard** [comment] 2019-04-02 09:58
@aanthony1243 I would be surprised if this was to do with the write path since it's synchronous—clients are blocked until the write is made readable.

**Comment by aanthony1243** [comment] 2019-04-02 13:23
@e-dard this involves the `to` function which is sort-of-on and sort-of-off the write path.  it reuses some of the same code, but I'm not sure that it blocks in the way that you describe.  could you point me to where that block occurs in the standard write path?  it would be idea if `to` would follow the same convention as closely as possible.

**Comment by e-dard** [comment] 2019-04-02 14:05
If you call `storage.Engine.WritePoints` then it will block until it's readable.

**Comment by jlapacik** [comment] 2019-04-11 19:37
When a Flux end-to-end test succeeds, it should return 3 query results with the following names:

* want
* got
* diff

In the case that it is run against influxdb, there should also be a result labeled `to1`. This is because tables written to a bucket as a result of a call to `to` will be implicitly yielded to the client.

So far when I get test failures, I only see results labeled `want`, `diff`, and `to1`. This seems to suggest that the write to the bucket is performed but that the query itself is never actually executed.

If the an error occurred where the write did not happen or did not persist, then I would expect to get an empty result with a label `got`. But this is not happening. There is no `got` label.

**Comment by wolffcm** [comment] 2019-04-12 17:40
I just ran `go test ./query/stdlib/testing/end_to_end_test.go -count=100` from `flux-staging` on `influxdb` and it seemed to have hanged, and dumped the stacks of the goroutines.

Most of it scrolled out of iterm2's buffer, and several stacks were irrelevant, but there were these:

```
goroutine 513573 [chan receive]:
testing.(*T).Run(0xc000988a00, 0x23b3203, 0xc, 0xc0089da810, 0xc009995001)
    /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:917 +0x37e
command-line-arguments_test.runEndToEnd(0xc009995000, 0xc000167680, 0x87, 0x90)
    /Users/cwolff/workspace/github.com/influxdata/influxdb/query/stdlib/testing/end_to_end_test.go:149 +0x106
command-line-arguments_test.TestFluxEndToEnd(0xc009995000)
    /Users/cwolff/workspace/github.com/influxdata/influxdb/query/stdlib/testing/end_to_end_test.go:136 +0x4f
testing.tRunner(0xc009995000, 0x258e558)
    /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
    /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:916 +0x357

goroutine 513614 [runnable]:
github.com/influxdata/flux/semantic.function.freeVars(0xc007c01830, 0xc002d47a00, 0x2, 0x2, 0x2809e20, 0xc00b3c7038, 0x23ab8f8, 0x6, 0xc0056f2de0, 0xc00bafc1b8, ...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/poly_types.go:383 +0x16c
github.com/influxdata/flux/semantic.Scheme.freeVars(0x2809ee0, 0xc001cbde00, 0xc00a0ff760, 0x3, 0x3, 0xc0056f2de0, 0xc0072af420, 0x1b, 0x1b)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/poly_types.go:836 +0x42
github.com/influxdata/flux/semantic.(*Env).freeVars(0xc005091a50, 0xc0056f2de0, 0x36ca468, 0x0, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/env.go:52 +0xf4
github.com/influxdata/flux/semantic.ConstraintGenerator.scheme(0xc0056f2de0, 0xc005091a50, 0xc005091a60, 0x6a55008, 0xc006d9f9c0, 0x2809ee0, 0xc00015b3c0, 0x0, 0x0, 0x0, ...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/constraints.go:99 +0xb1
github.com/influxdata/flux/semantic.ConstraintGenerator.typeof(0xc0056f2de0, 0xc005091a50, 0xc005091a60, 0x6a55008, 0xc006d9f9c0, 0x27f4640, 0xc00b63e180, 0xc00bafdb78, 0x100dbf9, 0xc008c71dd0, ...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/constraints.go:149 +0x5783
github.com/influxdata/flux/semantic.ConstraintGenerator.Done(0xc0056f2de0, 0xc005091a50, 0xc005091a60, 0x6a55008, 0xc006d9f9c0, 0x27f4640, 0xc00b63e180)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/constraints.go:71 +0xe4
github.com/influxdata/flux/semantic.ScopedVisitor.Done(...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/walk.go:389
github.com/influxdata/flux/semantic.walk(0x27da0c0, 0xc005091a80, 0x27f4640, 0xc00b63e180)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/walk.go:354 +0x1d2
github.com/influxdata/flux/semantic.walk(0x27da0c0, 0xc005091a70, 0x27f45c0, 0xc00b63eba0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/walk.go:79 +0xea0
github.com/influxdata/flux/semantic.Walk(...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/walk.go:6
github.com/influxdata/flux/semantic.GenerateConstraints(0x27f45c0, 0xc00b63eba0, 0xc006456420, 0xc0056f2cc0, 0x6a55008, 0xc006d9f9c0, 0xc000160a90, 0xc00bafe408, 0x100bc55)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/constraints.go:26 +0x1fa
github.com/influxdata/flux/semantic.InferTypes(0x27f45c0, 0xc00b63eba0, 0x6a55008, 0xc006d9f9c0, 0xc006d9f9c0, 0x0, 0xc00bafe478, 0x100dbf9)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/semantic/inference.go:6 +0xec
github.com/influxdata/flux/compiler.Compile(0xc00b5b3d10, 0x2803a00, 0xc0000d4ad8, 0xc009bc6f60, 0x214f800, 0xc009bc6fc0, 0xc0063db320, 0xc0063db320)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/compiler/compiler.go:22 +0x230
github.com/influxdata/flux/compiler.(*CompilationCache).Compile(0xc00bafe868, 0x2803a00, 0xc0000d4ad8, 0x6, 0xc0063db3a8, 0xc00b5b3f40, 0xc00bafe974)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/compiler/compiler.go:355 +0xbc
github.com/influxdata/flux/compiler.CompileFnParam(0xc00b5b3d10, 0x2804000, 0x278e8f0, 0x2804000, 0x278e8f8, 0x10, 0x2199360, 0x20, 0xc00b5b3ef0, 0x10, ...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/compiler/compiler.go:379 +0x142
github.com/influxdata/flux/stdlib/universe.NewDropKeepMutator(0x27bda00, 0xc00bc13d40, 0x2199360, 0x22dc701, 0xc0066dab00)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/stdlib/universe/schema_mutators.go:178 +0xf9
github.com/influxdata/flux/stdlib/universe.(*DropOpSpec).Mutator(0xc00bc13d40, 0x1, 0x1, 0xc0066dab00, 0xc000070800)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/stdlib/universe/schema_functions.go:391 +0x37
github.com/influxdata/flux/stdlib/universe.NewSchemaMutationTransformation(0x27ff4a0, 0xc00b5b3ef0, 0x27d4cc0, 0xc00a3d7d80, 0x27d5ec0, 0xc00a3d7040, 0xc0098ebf10, 0xc00bafea88, 0x100bb28)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/stdlib/universe/schema_functions.go:470 +0x1ae
github.com/influxdata/flux/stdlib/universe.createSchemaMutationTransformation(0x825a2362c2730af6, 0x742f5d62f924a39d, 0x1, 0x27d5ec0, 0xc00a3d7040, 0x2800f40, 0xc00aff3340, 0x0, 0x8, 0xc0066daa60, ...)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/stdlib/universe/schema_functions.go:455 +0x149
github.com/influxdata/flux/execute.(*createExecutionNodeVisitor).Visit(0xc00a3d7900, 0x2810640, 0xc0066286c0, 0x2810640, 0xc006629200)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/execute/executor.go:215 +0x99c
github.com/influxdata/flux/plan.walk(0x2810640, 0xc0066286c0, 0x2590188, 0xc00baff0e0, 0xc00bafef50, 0x0, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/plan/walk.go:88 +0x19e
github.com/influxdata/flux/plan.walk(0x2810640, 0xc004313cb0, 0x2590188, 0xc00baff0e0, 0xc00bafef50, 0x0, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/plan/walk.go:82 +0x15d
github.com/influxdata/flux/plan.(*Spec).BottomUpWalk(0xc00aff2a80, 0xc00baff0e0, 0xc008bcf7a0, 0x80)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/plan/walk.go:60 +0x2fd
github.com/influxdata/flux/execute.(*executor).createExecutionState(0xc0066da9b0, 0x27ee5c0, 0xc00aff2fc0, 0xc00aff2a80, 0xc00b8beee0, 0x80, 0x22dc980, 0x2329701)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/execute/executor.go:109 +0x1b7
github.com/influxdata/flux/execute.(*executor).Execute(0xc0066da9b0, 0x27ee5c0, 0xc00aff2fc0, 0xc00aff2a80, 0xc00b8beee0, 0x0, 0x0, 0x0, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/execute/executor.go:72 +0x57
github.com/influxdata/flux/lang.(*Program).Start(0xc00b8bee00, 0x27ee5c0, 0xc00aff2fc0, 0xc00b8beee0, 0x0, 0x36aca20, 0xc004313830, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/lang/compiler.go:244 +0x159
github.com/influxdata/flux/lang.(*AstProgram).Start(0xc00a919380, 0x27ee680, 0xc00a9193e0, 0xc00b8beee0, 0x2, 0xc00baff2c8, 0x1, 0x1)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/lang/compiler.go:311 +0x172
github.com/influxdata/flux/control.(*Controller).executeQuery(0xc0075dc070, 0xc001616120, 0xc00a9193b0, 0xc00a919301)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/control/controller.go:225 +0xb5
github.com/influxdata/flux/control.(*Controller).enqueueQuery(0xc0075dc070, 0xc001616120, 0x27d9f40, 0xc00b8bec80)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/control/controller.go:214 +0xdd
github.com/influxdata/flux/control.(*Controller).Query(0xc0075dc070, 0x27ee680, 0xc00a9192c0, 0x27d9f40, 0xc00b8bec80, 0xc00c942770, 0x27ee680, 0xc00a9192c0, 0xc00d5c3a40)
	/Users/cwolff/go/pkg/mod/github.com/influxdata/flux@v0.25.1-0.20190412140526-01ec679ec0db/control/controller.go:100 +0xda
github.com/influxdata/influxdb/query/control.(*Controller).Query(0xc00b6ae148, 0x27ee680, 0xc00a919230, 0xc00d5c3a40, 0x0, 0x0, 0x0, 0x0)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/query/control/controller.go:40 +0x1bc
github.com/influxdata/influxdb/query.ProxyQueryServiceAsyncBridge.Query(0x27be4e0, 0xc00b6ae148, 0x27ee680, 0xc00a919230, 0x27bd660, 0xc00b8becc0, 0xc00d5c3a40, 0x0, 0x0, 0x0, ...)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/query/bridges.go:94 +0x11c
github.com/influxdata/influxdb/http.(*FluxHandler).handleQuery(0xc006a10bc0, 0x27e3a00, 0xc00b8be020, 0xc001d38a00)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/http/query_handler.go:113 +0x4b5
net/http.HandlerFunc.ServeHTTP(0xc0046fd730, 0x27e3a00, 0xc00b8be020, 0xc001d38a00)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1995 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x27e3a00, 0xc00b8be020, 0xc001d38600, 0x0, 0x0, 0x0)
	/Users/cwolff/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1a9
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc006a10b80, 0x27e3a00, 0xc00b8be020, 0xc001d38600)
	/Users/cwolff/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x93d
github.com/influxdata/influxdb/http.(*APIHandler).ServeHTTP(0xc0068ac820, 0x27e3a00, 0xc00b8be020, 0xc001d38600)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/http/api_handler.go:219 +0x9a5
github.com/influxdata/influxdb/http.(*AuthenticationHandler).ServeHTTP(0xc0017f1cc0, 0x27e3a00, 0xc00b8be020, 0xc001d38500)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/http/authentication_middleware.go:86 +0x54a
github.com/influxdata/influxdb/http.(*PlatformHandler).ServeHTTP(0xc00c0bfb60, 0x27e3a00, 0xc00b8be020, 0xc001d38500)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/http/platform_handler.go:70 +0xd4
github.com/influxdata/influxdb/http.(*Handler).ServeHTTP(0xc009d8a990, 0x27e74c0, 0xc00c4ca2a0, 0xc001d38500)
	/Users/cwolff/workspace/github.com/influxdata/influxdb/http/handler.go:166 +0x21c
net/http.serverHandler.ServeHTTP(0xc00aff75f0, 0x27e74c0, 0xc00c4ca2a0, 0xc001d38100)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000109f40, 0x27ee5c0, 0xc0025f4500)
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.12/libexec/src/net/http/server.go:2884 +0x2f4
```

**Comment by aanthony1243** [comment] 2019-04-15 19:57
above looks like a crash when running `keep` with a boolean row function to identify columns to keep.  We can try to reproduce using `keep_fn.flux` since that's the only test that uses that feature.

**Comment by jlapacik** [comment] 2019-04-16 17:00
Putting this back on the backlog. So far from what I have seen, test failures occur only for queries that can be pushed down to storage entirely. Queries that are evaluated in any way by Flux do not exhibit this behavior.

I have been able to confirm that writes are persisting to storage and read cursors are also populated. In fact we always receive non-empty tables from storage. However I noticed that for the above mentioned problematic queries, the source node:

https://github.com/influxdata/influxdb/blob/9d0c91f5f0f9ff65537704af25c606aa3842afb1/query/stdlib/influxdata/influxdb/source.go#L26

has two downstream transformations - one of type `*execute.consecutiveTransport` and the other of type `*execute.result`. I'm not sure why it two downstream transformations (it should only have one) but honestly I'm not sure which one is correct.

Note the order that tables are piped to each transformation seems to have an effect on whether the test passes or fails. In particular I noticed that sometimes tables are piped to the `*consecutiveTransport` first and other times tables are piped to `*result` first. It seems that when tables are piped to the `*consecutiveTransport` transformation first, the end-to-end test passes, otherwise it fails. This was just something I observed although I don't really think it matters as the real question is why both of the above types of transformations are included in the below list to begin with.

https://github.com/influxdata/influxdb/blob/9d0c91f5f0f9ff65537704af25c606aa3842afb1/query/stdlib/influxdata/influxdb/source.go#L28

**Comment by jsternberg** [comment] 2019-05-14 16:46
@jlapacik do you think this could be related? https://github.com/influxdata/flux/pull/1216

I ran into this when dealing with reference counts and meta queries. Anything that comes directly from a source and doesn't go to consecutive transport causes this issue. I thought this only affected meta queries, but I'm wondering if it's been the cause of these flaky end to end tests by your comment.

**Comment by jsternberg** [comment] 2019-05-14 17:59
I think I found the issue. The reason why @jlapacik sees the above is because `*execute.result` usually refers to a `yield()` and `consecutiveTransport` is usually another transformation.

While the above code change will probably be needed, the issue seems to be from the storage implementation of read. In the storage implementation of read, the `Do` method can only be called on a table once. It doesn't use `RefCount` to determine if the table is still being used so it can only be called once and then it doesn't work anymore. When there are multiple transformations like in the above with `yield()` and `diff()`, then we get the race condition.

I'll begin working on a fix. The fix will probably involve using `RefCount` which means we'll need the above change too so `RefCount` is used properly.

**Comment by jsternberg** [comment] 2019-05-14 20:30
I fixed the reference count issue and ran into another with how results are returned. A problem that we currently have is that results aren't returned based on which one is ready first. So if you have multiple results and result 2 is ready before result 1, then it will still read result 1 first. But, if result 1 depends on result 2 having been read first, you'll get a deadlock.

This happens because I modified the table to only close itself after all references have been used and to wait until the table had been read before continuing. I figured we could fix that later for performance, but it would be functionally correct. But, it blocks forever because the result is never read and it can't continue processing tables while it is waiting for the first table to be released.

There's two things that come to my mind immediately.

1. Modify the influxdb source to copy the incoming input so it can continue processing the stream even though the table hasn't been consumed yet. This is probably the easiest and most constructive solution since it should probably be doing this anyway. Caveat: It might increase memory usage of a single stream since it would emit more than one table at a time. Uncaveat: This would force us to actually used `sync.Pool` to build the tables which we should be doing and I've wanted a push in that direction for awhile. Uncaveat: I think we already do this copy, but it's not exposed. It might be as simple as a call to `Retain()` and `Release()` to implement this.
2. Modify the interface for reading results to somehow select over multiple results to process results concurrently/in a threaded way. It will require a breaking change. I like this one, but I think it will require some discussion for how to change the interface. I don't have a strong love for the current interface, but I don't want to make this worse by moving to another interface that is a breaking change. Caveat: Still going to have to do the first at some point because waiting until a table has been completely processed before continuing probably isn't a good thing to do.

**Comment by jsternberg** [comment] 2019-05-14 20:34
An extra addendum to the first option. The table implementation does not currently put all of the values within the stream into a single buffer. It does copy data into an arrow buffer, but it doesn't shove an entire dataset into memory. We might have to go with option 2 or think of an option 3.

**Comment by jsternberg** [comment] 2019-05-15 15:29
Another idea is a temporary workaround. We can create a function `testing.noop()` that gets added automatically and copies the tables for the tests specifically.

This wouldn't be a permanent solution, but it would be a band-aid to get this working in a way so that we can freely write tests while we find a more permanent solution. The problem happens anytime a source has more than one child and the "fix" I made will deadlock if one of those two children is a `yield()`. In any other circumstance, this problem won't happen.

**Comment by affo** [comment] 2019-05-15 16:59
This is related: https://github.com/influxdata/influxdb/issues/13898

**Comment by jsternberg** [comment] 2019-05-15 21:22
https://github.com/influxdata/flux/issues/1281

**Closed** 2019-05-30 17:31 UTC
Labels: area/flux, area/tests, flaky test
