### ISSUE TITLE
Unable to get scalar value in Flux in InfluxDB task

### ISSUE THREAD

**Issue by alespour** [influxdata/influxdb#20781] opened 2021-02-19 08:27 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Flux functions for working with scalar values (`tableFind` etc) fail with `no execution context for ... to use` when used in InfluxDB task

__Expected behavior:__
Should work the same way as when used in scripts executed as "normal" query in Explorer etc.

__Actual behavior:__
Fails with `no execution context for tableFind to use`.

__Environment info:__

* InfluxDB version: 2.0.3

**Comment by alespour** [comment] 2021-02-19 08:28
Also reported in the community slack: https://influxcommunity.slack.com/archives/CH8RV8PK5/p1612575999112100

**Comment by danxmoran** [comment] 2021-02-19 18:29
Duplicate of #17666 (I think)

**Comment by danxmoran** [comment] 2021-03-05 00:03
Closing this as a duplicate, please track #17666 for progress

**Closed by danxmoran** 2021-03-05 00:03 UTC
Labels: area/2.x, area/queries, area/tasks, duplicate
