### ISSUE TITLE
InfluxDB 2.0 API: API design not consistent about org & orgID

### ISSUE THREAD

**Issue by kilik52** [influxdata/influxdb#14371] opened 2019-07-18 01:57 UTC
in API:

````
POST /write
````

The API only accept org, and do not accept orgID.

but in API:

````
POST /buckets
````

The API only accept orgID, and do not accept org.

In my opinion, you should either stick to orgID or accept both.

**Comment by bednar** [comment] 2019-07-18 12:07
For the `POST /write` an org parameter could be `Organization.name` or `Organization.id`.

This bug is probably a duplicate of https://github.com/influxdata/influxdb/issues/13906.

**Closed** 2019-10-23 14:14 UTC
Labels: wontfix
