### ISSUE TITLE
Issue to Handle more than Billions of data

### ISSUE THREAD

**Issue by josephthanaraja** [influxdata/influxdb#16631] opened 2020-01-22 19:13 UTC
We are using InfluxDB to store **billions** of data for a year(atleast) but we are getting MOM frequently while retrieving the data for more than a day. Can you please confirm the HIGH LOAD memory to handle this scenario or do we need any special setup?.
High load recommendations
   CPU: 8+
   RAM: 32+ GB
   IOPS: 1000+
We are using 1.7.6-alpine version (running as a container - k8). Appreciate your help.

**Comment by russorat** [comment] 2020-01-31 17:49
@josephthanaraja thanks for connecting. If you haven't already, I'd suggest reading through the docs here to understand where InfluxDB uses memory: https://docs.influxdata.com/influxdb/v1.7/concepts/storage_engine/#the-influxdb-storage-engine-and-the-time-structured-merge-tree-tsm

You will definitely want to have TSI enabled on this instance. InfluxDB will eat as much memory as you give it, so increasing memory would be my first suggestion. For a load this size, dedicated hardware is usually recommended. If you still want to use k8s, you will probably want the entire node dedicated to this instance.

Let me know if that helps. Feel free to join us on Slack if you have more questions: https://influxdata.com/slack

**Comment by russorat** [comment] 2020-01-31 17:50
I'm going to close this issue since it's more of a question and not a bug/feature request.

**Closed by russorat** 2020-01-31 17:50 UTC
