### ISSUE TITLE
v0.10 order by problem

### ISSUE THREAD

**Issue by zhang8h** [influxdata/influxdb#5883] opened 2016-03-02 07:08 UTC
```
select * from c201 where time<1456898400s and time>1456894800s

select * from c201 where time<1456898400s and time>1456894800s  order by time desc
```
The results they get are not the same

request:

`select * from c201 where time<1456898400s and time>1456894800s`

response:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "c201",
                    "columns": [
                        "time",
                        "temperature"
                    ],
                    "values": [
                        [
                            "2016-03-02T05:06:44Z",
                            17.51
                        ],
                        [
                            "2016-03-02T05:16:44Z",
                            17.52
                        ],
                        [
                            "2016-03-02T05:26:44Z",
                            17.51
                        ],
                        [
                            "2016-03-02T05:36:44Z",
                            17.51
                        ],
                        [
                            "2016-03-02T05:46:44Z",
                            17.52
                        ],
                        [
                            "2016-03-02T05:56:44Z",
                            17.52
                        ]
                    ]
                }
            ]
        }
    ]
}
```

request:

`select * from c201 where time<1456898400s and time>1456894800s  order by time desc`

response:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "c201",
                    "columns": [
                        "time",
                        "temperature"
                    ],
                    "values": [
                        [
                            "2016-03-02T05:16:44Z",
                            17.52
                        ],
                        [
                            "2016-03-02T05:06:44Z",
                            17.51
                        ]
                    ]
                }
            ]
        }
    ]
}
```

Not all have this problem

**Comment by rossmcdonald** [comment] 2016-03-03 15:24
This is a duplicate of https://github.com/influxdata/influxdb/issues/4944. The query engine underwent a large refactor for the 0.11 release with https://github.com/influxdata/influxdb/pull/5196, so this issue should no longer occur with the latest nightlies.

**Closed by rossmcdonald** 2016-03-03 15:24 UTC
