### ISSUE TITLE
Create org error response content is empty

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#10936] opened 2018-06-20 20:07 UTC
According to swagger 2.0 API documentation, response schema for an error should include error code and a error message. 
What happens is when creating an org that already exists, then error response content is an empty string. And, if I understand it correctly, it should be JSON response in the form o (according to the swagger API docs for 2.0):
` {"code": <ERROR CODE>, "message":"ERROR MESSAGE"}  `

Since I am following the swagger API doc for creating the org, then blow items looks like bugs:
- The current response content is empty
- status_code is 500 (Internal Server Error), should it be 400?
- The error is reported in headers: `'X-Influx-Error': 'organization with name gershon-test-org already exists'`

**Comment by goller** [comment] 2019-01-15 00:38
Dupe of #11057

**Closed by goller** 2019-01-15 00:38 UTC
Labels: area/api, kind/bug
