### ISSUE TITLE
weird behavior with SELECT regex

### ISSUE THREAD

**Issue by schmurfy** [influxdata/influxdb#7655] opened 2016-11-25 12:21 UTC
I am using influxdb 1.0.2 with kapacitor (not relevant to my issue), kapacitor is writing alerts to my database with a `level_tag` tag and a `level` field, I started with only the field, then only the tag then both hitting the wall with my head the whole time...

What I want is to list all alerts where the level does not match a regex (these lines are one I insert myself), if I query the database with the influxdb client I get the correct results:

```bash
$ influx -pretty -format json -database metrics -execute 'SELECT * FROM alerts WHERE level_tag !~ /^NOTIFY_.+/ GROUP BY "res_name", "app_name", "host", "id" ORDER BY time DESC LIMIT 10'
```

but if I execute the same query with curl, it seems like the WHERE clause is ignored and I get results including NOTIFY_UP and NOTIFY_DOWN levels which should not be there:

```bash
$ curl 'http://127.0.0.1:8086/query?db=metrics&q=SELECT%20*%20FROM%20alerts%20WHERE%20level_tag%20!~%20/%5ENOTIFY_.+/%20GROUP%20BY%20%22res_name%22,%20%22app_name%22,%20%22host%22,%20%22id%22%20ORDER%20BY%20time%20DESC%20LIMIT%2010'
```

The results are here for both queries: https://gist.github.com/schmurfy/ad092a7e766ef7e929bd11af7d54d217

If I look at influxdb logs (set to verbose), the two queries looks identical to me:

```
2016-11-25T12:12:42Z.053377 [query] 2016/11/25 12:12:42 SELECT * FROM metrics.raw.alerts WHERE level_tag !~ /^NOTIFY_.+/ GROUP BY res_name, app_name, host, id ORDER BY time DESC LIMIT 10

2016-11-25T12:12:54Z.095068 [query] 2016/11/25 12:12:54 SELECT * FROM metrics.raw.alerts WHERE level_tag !~ /^NOTIFY_. / GROUP BY res_name, app_name, host, id ORDER BY time DESC LIMIT 10
```

I don't even know if that's a bug but I am going crazy, I have no clue what is happening.
At first I thought it was because I only had a level field, then I added the tag with same results.

**Comment by shanexu** [comment] 2016-11-26 11:06
This is not a bug.

The curl command should be written in this way.

```
curl 'http://127.0.0.1:8086/query?db=metrics&q=SELECT%20*%20FROM%20alerts%20WHERE%20level_tag%20!~%20%2F%5ENOTIFY_.%2B%2F%20GROUP%20BY%20%22res_name%22%2C%20%22app_name%22%2C%20%22host%22%2C%20%22id%22%20ORDER%20BY%20time%20DESC%20LIMIT%2010'
```
you missed encode ```+``` in your regex expression.

**Comment by jsternberg** [comment] 2016-11-27 17:37
I think @shanexu is right. Encode the `+` and it works fine. I'm going to close this. If you think there's still an issue, please comment and I can reopen the issue.

**Closed by jsternberg** 2016-11-27 17:37 UTC

**Comment by schmurfy** [comment] 2016-11-28 09:49
good catch, what got me is:
- the library I use did not escape the +
- the browser (firefox here) did not escape it either when you type it in the url

good catch, thanks !
