### ISSUE TITLE
Feature request: Trigger warning if user tries to write data which would be dropped by retention policy immediately

### ISSUE THREAD

**Issue by Damu112** [influxdata/influxdb#8759] opened 2017-08-29 12:44 UTC
### Trigger warning if user tries to write data which would be dropped by retention policy immediately

__Proposal:__ If one tries to insert a point into a retention policy which would immediately drop the point, the user should receive a warning.

__Current behavior:__ The point is accepted with a HTTP 204 code, making the user think it has been inserted (which is actually true).

__Desired behavior:__ Trigger a warning so the user can see their mistake.

__Use case:__ When inserting historical data with points well in the past, it may happen that the default retention policy will drop these points right after writing them. For a user, this looks like Influx did not write the points. In fact, if writing to a new series/measurement, not even the series/measurement shows up. It is likely that a user will have to do a lot of debugging work to find out what is happening.

**Comment by e-dard** [comment] 2017-10-12 10:59
This is a dupe of https://github.com/influxdata/influxdb/issues/8392, which was fixed in the 1.3.0 release

**Closed by e-dard** 2017-10-12 10:59 UTC
