### ISSUE TITLE
[UI - Alerts] Create check - when adding a threshold with a negative value, leading minus '-' sign is ignored 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/influxdb#17782] opened 2020-04-17 11:10 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

In the alerts section

1. Click  Create > threshold alert 
2. Click Configure Check
3. Click add "Crit" threshold 
4. Choose the type "is inside range"
5. In the lower input type "-123"

__Expected behavior:__
Describe what you expected to happen.

Expected the value to be "-123"

__Actual behavior:__
Describe What actually happened.

The leading "-" sign is discarded and the value is "123"

_work around_

Enter the positive value then use arrow key to move cursor to head of input and add "-".  Or use control's increment, decrement arrows.  (However, not a testable or recommended permanent solution.)

__Environment info:__

* System info: Run `uname -srm` and copy the output here
```
Linux 4.15.0-96-generic x86_64
```
* InfluxDB version: Run `influxd version` and copy the output here
Detected in nightly builds 
```
version=nightly commit=9495ec1c4e build_date=2020-04-17T08:20:51Z
```
* Other relevant environment details: Container runtime, disk info, etc
Browser: __Chrome 80__

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

Started with e2e testing enabled. 

```
--e2e-testing=true
```

__Nightly Tests__

Wanted to add the negative value use case to nightly tests.

**Comment by Asalem1** [comment] 2020-12-01 18:39
Can't reproduce this. Gonna close this out

**Closed by Asalem1** 2020-12-01 18:39 UTC
Labels: area/ui, kind/bug, monitoring-and-alerting, selenium/nightly, severity/sev-4, team/monitoring
