### ISSUE TITLE
TSM list for feature complete

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb#4977] opened 2015-12-03 20:11 UTC
This is a list of items to be completed on TSM after the December 8th release to make it feature complete. There will still be more testing, but once this is done we'll only be testing.

### Features
- [x] Deduplicate points with same timestamp that exist in multiple TSM files (@jwilder)
- [x] Fix compaction planning so that it works past the first compaction step size (@pauldix)
- [x] Update compaction to run multiple levels at the same time (@jwilder)
- [x] Update compaction planning logic to include tombstones (@jwilder)
- [x] Backup/restore (@pauldix)
- [x] Migrate b1 and bz1 shards to TSM files (@otoolep)
- [ ] Stats and diagnostics (@otoolep)
- [ ] Different logging options: snapshots, WAL, compactions, filestore, etc (including turning logging off) (@otoolep)
- [ ] Queries against files that have just been compacted need to point to new files (@jwilder)
- [ ] Add checksum verification to TSM inspect tool
- [ ] Modify tombstone to write multiple immutable files instead of updating a single tombstone file 

### Testing
- [x] Crash testing
- [ ] Race testing
- [ ] Many TSM files (1M series with 2k TSM files)
- [x] Startup testing (how long does it take to startup and answer queries with large database)
- [ ] Write 1B points across 500k series (throughput)
- [ ] Same as above while querying (check if throughput drops)
- [ ] Time to count query a specific series after writing
- [ ] Time to count query all series after writing
- [ ] Drops/deletes during writes and queries
- [ ] Writes and queries while closing
- [x] Test 1M, 10M series
- [x] Test 10B points
- [x] Test 50B points
- [ ] Test 1T points

### Performance
- [ ] Performance optimizations
- [ ] Performance comparisons with b1 and bz1
- [ ] Performance comparison with old TSM1

cc @jwilder @otoolep

**Comment by ivanscattergood** [comment] 2015-12-18 15:22
Hi 
Great to see that you will be looking at  the startup time
>Startup testing (how long does it take to startup and answer queries with large database)

We have been running a 0.9.6.1 database for a week using tsm1. We are recording about 0.5 million datapoints (over 1 million series) every 10 minutes. The performance and stability is MUCH better than 0.9.5 and the first iteration of TSM. 

However we restarted the database last night and it took 1.5hrs to start accepting connections.

**Comment by pauldix** [comment] 2015-12-18 15:24
@ivanscattergood My guess is that you have thousands of underlying TSM files. There was a bug where compactions weren't continuing.

Should be fixed in the lastest nightly and there are other fixes/performance enhancements coming soon.

**Comment by ivanscattergood** [comment] 2015-12-18 15:27
Awesome, I'll look to put the nightly into our dev area next week!

**Comment by jwilder** [comment] 2015-12-18 15:31
@ivanscattergood watch #5142 which has fixes for your issues.

**Comment by toddboom** [comment] 2015-12-28 21:25
**Crash Testing - Notes**

Using `influx_stress`, I wrote 5B points across 100k series in 5k batches. While running under full write load, I ran the following script with `watch -n 60` for the entire duration of the test:

```bash
#!/bin/bash

sudo kill -9 `pidof influxd`
sleep 1s
sudo service influxdb start
```
The test completed without errors, and had an overall write throughput of 170k/s on the branch with @jwilder's most recent compaction updates. This was performed on bare metal hardware with 1x quad-core CPU, 32GB RAM, and all data being written to a 1.2TB PCIe SSD.

**Comment by pauldix** [comment] 2015-12-28 21:27
@toddboom cool, how long did it take? How many crashes did you create over that time?

**Comment by toddboom** [comment] 2015-12-28 21:42
@pauldix The rough math is `5B / 170k/sec = 29.4k sec`, so just a bit over 8 hours. There would have been one crash per minute, so approximately 490 over the course of the data being written.

**Comment by daviesalex** [comment] 2015-12-29 20:29
@toddboom , @pauldix , can I suggest you run this test through at least one new shard creation and monitor that? We have a box up now for 5 days, and saw a shard creation earlier that used nearly 100G of RAM (when it is has been running for 5 days with a very stable RSS at ~10G). I suspect that would panic many "normal" boxes, and the memory usage after the shard creation is ~50% more than it was before, so its possible that over time that will slowly increase to run the box out of RAM.

![image](https://cloud.githubusercontent.com/assets/1106249/12041616/bdb6e1ea-ae6a-11e5-85e0-3e34f6b2421e.png)

As a test, it would be good to kill the process during new shard creation too to make sure we dont end up in a state that we cant restart from.

**Comment by pauldix** [comment] 2015-12-29 20:34
@daviesalex You're saying you saw the spike when it create a new shard for the next 7 day block of time?

Seems really odd as the creation of a shard shouldn't really do anything to memory. Although if you're writing to many shards at once you'd see the memory go up since there's a WAL cache for each shard.

**Comment by daviesalex** [comment] 2015-12-29 20:37
@pauldix, that happened around that time but we are checking  more. Digging more (we only just noticed this huge RSS spike!), it seems around the same time we also ran some new queries - trying to see if we can reproduce this massive spike.

This of course raises another question, that this tsm test suite should probably run  small numbers of intensive and large numbers of simple simultaneous queries against this data to be more real-world...

**Comment by pauldix** [comment] 2015-12-29 20:39
@daviesalex A query is a much more likely suspect for a big memory spike like that. That wouldn't be a problem in TSM, but in the query engine itself. We have a bunch of work being done on the query engine. Watch #5196 for more deatils

**Comment by daviesalex** [comment] 2015-12-29 20:46
@pauldix, we cant reproduce running the same query (we can get a few GB of RAM to be used, but not anything like 90G). However, happy to wait for that PR to merge and report if we see this again. 

I guess the full load test (with queries) will need to wait for that PR to land to avoid chasing bugs that are already fixed in that branch... we will watch and test as soon as its ready.

**Comment by toddboom** [comment] 2016-01-07 07:49
**50B Point Test - Notes**

Using `influx_stress`, I wrote 50B points across 50k series in 5k batches. The test took about 49h to complete, with an overall write throughput of 280k/s. I ran the client and server on the same machine, running on physical hardware (32GB RAM, 1x 4-core CPU, SSD).

Total size of data on disk after completion was 106GB, which comes out to approximately 2.12 bytes per point. The server took 3 minutes on the nose to become available again after a restart.

I set the `influx_stress` tool to space points 1m apart in order to force the creation of more shards. In the end, there were 102 shards created in total.

<img width="833" alt="50b across 50k series" src="https://cloud.githubusercontent.com/assets/53132/12165083/b2e17a08-b4cf-11e5-981e-22684210b4bd.png">

**Comment by beckettsean** [comment] 2016-01-07 18:57
> approximately 2.12 bytes per point.

:heart: !

**Comment by toddboom** [comment] 2016-01-08 08:45
### 1M and 10M Series Tests - Notes

With the fixes from @jwilder earlier today in #5308, I re-ran the 5B point tests on 1M and 10M series.

**For 1M series:**
```
Total Requests: 1000000
        Success: 1000000
        Fail: 0
Average Response Time: 84.489102ms
Points Per Second: 340262
```
<img width="821" alt="5b across 1m series go 1 4 2" src="https://cloud.githubusercontent.com/assets/53132/12193797/c6926d48-b59f-11e5-9e1f-a53dfc7498ce.png">

**For 10M series:**
```
Total Requests: 1018569
        Success: 1000000
        Fail: 18569
Average Response Time: 114.79202ms
Points Per Second: 194729
```
<img width="820" alt="5b across 10m series go 1 4 2" src="https://cloud.githubusercontent.com/assets/53132/12193800/c91a4d2e-b59f-11e5-932d-42b2f37e7bab.png">

It should be noted that the failures in the 10M series example were due to the `engine: cache maximum memory size exceeded` message, despite increasing the `cache-max-memory-size` setting to 1GB.

Disk utilization on the higher-cardinality test is greatly improved over the previous test runs. It should be noted that both examples have a ~20GB offset shown on the graphs, so the initial difference at the end of the write test was approximately 11GB vs 43GB (which was formerly > 200GB for the same test). With the latest changes, the 43GB was compacted down to 12GB within about an hour after the test completed.

These were both build using Go 1.4.2, and tested on machines with 2x 6-core CPUs (`Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz`) and 128GB RAM.

**Comment by toddboom** [comment] 2016-01-08 20:19
I'm also going to rerun the above test with Go 1.5.2 to get some comparisons.

**Comment by toddboom** [comment] 2016-01-08 20:31
Marking the startup testing item complete due to the work that @jwilder has done with mmap settings. Loading 100GB of data in < 1m is good enough for MVP.

**Comment by toddboom** [comment] 2016-01-09 06:16
So, I reran the 1M and 10M series tests with Go 1.5.2 so that I could compare against the previous runs with Go 1.4.3.

Here are the results for 1M series:
```
Average Response Time: 154.572476ms (82.9% increase in latency)
Points Per Second: 226938 (33.3% decrease in throughput)
```

Here are the results for 10M series:
```
Average Response Time: 191.018208ms (66.4% increase in latency)
Points Per Second: 160178 (17.7% decrease in throughput)
```

Those are pretty significant performance hits with Go 1.5.2. My vote would be to stay with Go 1.4.3 for the v0.10.0 release.

Go 1.6beta1 seems promising, but the final version won't be released before the end of January, and we should spend at least a few weeks with it before we use it for an official release.

A a site note, memory utilization looks pretty similar across both versions.

**Comment by daviesalex** [comment] 2016-01-09 15:10
@toddboom not sure if you saw #5217 - we saw exactly the same thing in production. The difference made the difference between being able to keep InfluxDB up and not. Strongly +1 your suggestion (with a view to move to 1.6 in a few months).

The main benefit of 1.5 is supposed to be reduced jitter in latency due to a max GC time of 10ms, but we saw far worse latencies and i'd be surprised if anybody saw overall better performance - rendering the change all negative as far as we can see!

**Comment by toddboom** [comment] 2016-01-10 02:57
@daviesalex actually, your graphs in #5217 were what inspired me to run the tests on our end to see how it looked in longer-term tests. thanks for the info!

**Comment by zstyblik** [comment] 2016-01-10 13:14
@toddboom now, for the stupid question. since you, InfluxData, are aware of this fact, why are nightly builds being built by golang v1.5.2 and not v1.4.x? Yes, I know we can build it ourselves with golang v1.4.x(and some people actually do), but that's not really the point.

**Comment by toddboom** [comment] 2016-01-11 06:54
@zstyblik we didn't want to jump too quickly between versions until we'd completed enough testing to feel confident about the decision. we'll be changing the version for the nightly builds soon, in addition to changing it for the upcoming v0.10.0 release as well.

**Comment by toddboom** [comment] 2016-01-12 06:47
Some more numbers:

**100B points across 50k series**
```
Total Requests: 20000000
        Success: 20000000
        Fail: 0
Average Response Time: 59.605432ms
Points Per Second: 368122
```

**100B points across 100k series**
```
Total Requests: 20000000
        Success: 20000000
        Fail: 0
Average Response Time: 66.056913ms
Points Per Second: 346418
```

**Comment by jwilder** [comment] 2016-02-01 22:30
All unfinished feature items converted to new issues.  Closing this as we've made it the default engine in `0.10`.

**Closed by jwilder** 2016-02-01 22:30 UTC
Labels: tsm
