### ISSUE TITLE
How to get inserted timestamp

### ISSUE THREAD

**Issue by yukozh** [influxdata/influxdb#9989] opened 2018-06-21 01:12 UTC
__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by e-dard** [comment] 2018-07-02 14:49
Dupe of #9990

**Closed by e-dard** 2018-07-02 14:49 UTC
