### ISSUE TITLE
Segfaults in 1.7.7 with TSI enabled

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#14455] opened 2019-07-25 17:21 UTC
(Log attached at bottom)

__Environment info:__

* InfluxDB OSS 1.7.7
* TSI enabled

__Config:__
```
bind-address = ":8088"
reporting-disabled = false

[admin]
bind-address = ":8083"
enabled = true
https-certificate = "/etc/ssl/influxdb.pem"
https-enabled = false

[[collectd]]
enabled = false

[continuous_queries]
enabled = true
log-enabled = true
run-interval = "1s"

[coordinator]
log-queries-after = "5s"
max-concurrent-queries = 0
max-select-buckets = 0
max-select-point = 0
max-select-series = 0
query-timeout = "0s"
write-timeout = "10s"

[data]
cache-max-memory-size = "8g"
cache-snapshot-memory-size = 26214400
cache-snapshot-write-cold-duration = "10m"
compact-full-write-cold-duration = "4h"
dir = "/var/lib/influxdb/data"
engine = "tsm1"
index-version = "tsi1"
max-concurrent-compactions = 0
max-points-per-block = 0
max-series-per-database = 0
query-log-enabled = true
trace-logging-enabled = false
wal-dir = "/var/lib/influxdb/wal"
wal-logging-enabled = true

[[graphite]]
enabled = false

[http]
auth-enabled = false
bind-address = ":8086"
enabled = true
https-certificate = "/etc/ssl/influxdb.pem"
https-enabled = false
https-private-key = ""
log-enabled = false
max-connection-limit = 0
max-row-limt = 10000
pprof-enabled = false
realm = "InfluDB"
shared-secret = ""
write-tracing = false

[meta]
dir = "/var/lib/influxdb/meta"
logging-enabled = true
retention-autocreate = true

[monitor]
store-database = "_internal"
store-enabled = true
store-interval = "10s"

[[opentsdb]]
enabled = false

[retention]
check-interval = "30m0s"
enabled = true

[shard-precreation]
advance-period = "30m0s"
check-interval = "10m0s"
enabled = true

[subscriber]
enabled = true
http-timeout = "30s"

[[udp]]
enabled = false
```

__Logs:__
[influxdb_segfault_out.log](https://github.com/influxdata/influxdb/files/3432631/influxdb_segfault_out.log)

**Comment by samhld** [comment] 2019-07-29 16:24
They moved back to in-mem and are not experiencing this panic anymore but it would still be good to know what caused this in TSI.  Given their use case, I recommend they stay on TSI for future workloads.

**Comment by samhld** [comment] 2019-07-29 18:43
Roblox (the prospective customer who experienced this issue) has a restart time of multiple hours now that they're using in-mem indexing.  This is not only unacceptable for them in production but making troubleshooting extremely difficult.  The goal is still get them successfully running TSI.

**Comment by jacobmarble** [comment] 2019-08-05 17:44
This will be difficult to reproduce. The panic originates from here:
https://github.com/influxdata/roaring/blob/fc520f41fab6dcece280e8d4853d87a09a67f9e0/bitmapcontainer.go#L910

So element `k` doesn't exist in `arrayContainer.content` which is weird because `c` is just `len(container)`.

**Comment by e-dard** [comment] 2019-08-05 17:55
@jacobmarble trace it back to InfluxDB and it should be possible to audit the code to understand where the race is, and if we already fixed it.

**Comment by samhld** [comment] 2019-08-06 15:28
Update from prospect per Jacob:
```
We have been experiencing the issue from within 24 hours or starting the new instances of influxdb. That would put the total data size at around 200GB or less when this started.

Shard duration is 6h and we have seen this within 24 hours of starting a 4w retention policy (which is then changed to 2w).

I used influx_inspect report -detailed on shards from 7/23 to get these values (I didn't want to run this against shards that might actually be used). The report tells me that between all three shards there are 7,371,644 series.
```

**Comment by samhld** [comment] 2019-08-06 17:08
@jacobmarble , Issue occurred on 1.7.2 as well

**Comment by samhld** [comment] 2019-08-07 18:25
From user:
"""
I've started an experiment to add a few more data points and narrow down the problem I haven't a been running it too long, but I have some preliminary results that might help with the debugging.

Hypothesis: The change which is causing the observed segfaults is using the tsi1 index

Process: Keeping one server unchanged as the control, modify one server in each of the following ways then observe for future segfaults:
server 1: change retention length 4w -> 2w
server 2: change shard duration length from 6h -> 12h
server 3: change indexing method tsi1 -> inmem

So far, I have observed that server 1 and 2 are still seg faulting. I have not gathered enough data to confirm is server 2 is still seg faulting on a 6h interval or if the interval has changed (I would expect it to change to 12h if anything), but there are definitely still seg faults occuring. Server 3 has not seg faulted since the setting change (~24h/4 shard changes).

This is still not conclusive. I will let you know once I have enough data to really state anything with strong confidence, but right now it's at least a hint I think.
"""

**Comment by e-dard** [comment] 2019-08-07 18:30
@samhld I have been investigating this issue today and have a pretty good understanding of the issue. I'm figuring out the most appropriate way to resolve it.

**Comment by samhld** [comment] 2019-08-07 19:16
@e-dard great!  I'll keep an eye out!

**Comment by jacobmarble** [comment] 2019-09-16 15:50
@e-dard please share your theory on what's happening so that someone else can continue making progress on this.

**Comment by e-dard** [comment] 2019-09-18 09:40
@jacobmarble I shared it internally on the linked EAR (August 8th update).

**Comment by jacobmarble** [comment] 2019-09-23 15:45
This probably isn't an issue in 2.x because of @zeebo 's limit work.

Ask @e-dard for more info about root cause and possible repro.

**Comment by foobar** [comment] 2020-01-10 08:52
I'm seeing the same issue with v1.7.9. Can you reopen this?

**Comment by foobar** [comment] 2020-01-13 12:45
> This will be difficult to reproduce. The panic originates from here:
> 
> https://github.com/influxdata/roaring/blob/fc520f41fab6dcece280e8d4853d87a09a67f9e0/bitmapcontainer.go#L910
> 
> So element `k` doesn't exist in `arrayContainer.content` which is weird because `c` is just `len(container)`.

From the crash log, it's not an out-of-range panic. The index is valid but the memory itself is not. 
```
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6ce031daac pc=0x95e125]
```
Above message says memory address `0x7f6ce031daac` is not mapping to the process address space (`code=0x1`). 
Given that the TSI uses mmap and the roaring bitmap container also makes use the mapped data, I'd guess it's a race-condition that the log file gets unmap'd while the query is still using the mmap'd slice .

The log does show that there was TSI compaction at the time of crash.

I've not figured out the exact scenario to reproduce this bug anyway.

```
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: ts=2019-07-22T18:00:10.255627Z lvl=info msg="Removing index file" log_id=0GnOmxlG000 index=tsi tsi1_partition=6 trace_id=0GniIOyl000 op_name=tsi1_compact_to_level tsi1_level=2 path=/var/lib/influxdb/data/PerfmonWeb/4w/93/index/5/L1-00000001.tsi
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: ts=2019-07-22T18:00:10.256615Z lvl=info msg="TSI level compaction (end)" log_id=0GnOmxlG000 index=tsi tsi1_partition=6 trace_id=0GniIOyl000 op_name=tsi1_compact_to_level tsi1_level=2 op_event=end op_elapsed=3096.944ms
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: ts=2019-07-22T18:00:10.342589Z lvl=info msg="TSI log compaction (start)" log_id=0GnOmxlG000 index=tsi tsi1_partition=1 trace_id=0GniIaPW000 op_name=tsi1_compact_log_file tsi1_log_file_id=3 op_event=start
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: unexpected fault address 0x7f6ce031daac
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: fatal error: fault
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6ce031daac pc=0x95e125]
Jul 22 13:00:10 chi1-ldb18 influxd[92934]: goroutine 126724

**Comment by cmd-influx** [comment] 2020-02-14 15:03
This is unrelated to EAR 1315, please ignore it.

**Comment by 8none1** [comment] 2020-04-09 16:15
Ben could you put this on your list after malloc and OOB backup errors.  Ideally to start no later than w/c April 20, but sooner if it works.

**Comment by benbjohnson** [comment] 2020-06-01 15:15
This issue also seems to be caused by closing iterators too soon. A fix has been merged in: https://github.com/influxdata/influxdb/pull/18203

**Comment by 8none1** [comment] 2020-06-22 15:21
Is this one fixed now? Can we close it?

**Comment by 8none1** [comment] 2020-07-06 09:39
No movement for two weeks, assuming that this is all done with now.  I'm unassigning  engineering, but give me a shout if you need more help.

**Comment by samhld** [comment] 2020-07-06 16:10
@8none1 I'm not who you're relying on to know if this is closable.   As I understood it, this was a bug that edge cases came across.  If it is not, the prospect that brought this up is no longer interested in InfluxDB and this is okay to close.

If it is, it should be fixed right?  Or has it been?

**Comment by 8none1** [comment] 2020-07-07 08:23
Yeah, the seg fault is fixed.  I think that's probably a wrap for this issue then.

**Closed by 8none1** 2020-07-07 08:23 UTC
Labels: 1.x, panic

**Comment by lmagdanello** [comment] 2021-07-13 14:18
Hi,

I'm experiencing this same problem, both in version 1.7.7 and 1.8.6.
Is there a version prior to 2.0 that fixes this problem?

**Comment by hkarira1** [comment] 2023-10-11 05:49
`Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: unexpected fault address 0x7f6fe40fab01
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: fatal error: fault
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6fe40fab01 pc=0x9d3f7e]
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: goroutine 1197190554 [running]:
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: runtime.throw(0x151e28d, 0x5)
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: #011/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc00c73da70 sp=0xc00c73da40 pc=0x42f482
Sep 28 22:48:03 us-infra-influx-2 influxd[23109]: runtime.sigpanic()`

We are still getting Segmentation issues with Version 1.7.9. The influxd service restarted soon after the segmentation violation which started causing write failures. Has the issue resurfaced again ?

**Comment by Satish2007** [comment] 2024-03-30 12:07
Issue: InfluxDB Restarting Automatically Randomly

Error in Logfile:
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: unexpected fault address 0x7b35af7b5000
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: fatal error: fault
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7b35af7b5000 pc=0x12a1fd0]
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: goroutine 11953909117 [running]:
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: runtime.throw(0x169e54a, 0x5)
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: #011/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc2e2d8cc18 sp=0xc2e2d8cbe8 pc=0x431272
Mar 28 06:52:02 influx influxd-systemd-start.sh[14374]: runtime.sigpanic()
…
…
…
Mar 28 06:52:09 influx influxd-systemd-start.sh[14374]: #011/usr/local/go/src/net/http/server.go:2928 +0x384
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Failed with result ‘exit-code’.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Consumed 1month 6d 13h 29min 42.403s CPU time.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Scheduled restart job, restart counter is at 1.
Mar 28 06:52:10 influx systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Mar 28 06:52:10 influx systemd[1]: influxdbsud.service: Consumed 1month 6d 13h 29min 42.403s CPU time.
Mar 28 06:52:10 influx systemd[1]: Starting InfluxDB is an open-source, distributed, time series database…
Mar 28 06:52:10 influx influxd-systemd-start.sh[116443]:
Mar 28 06:52:10 influx influxd-systemd-start.sh[116440]: InfluxDB started
Mar 28 06:52:10 influx systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Mar 28 06:52:10 influx influxd-systemd-start.sh[116441]: ts=2024-03-28T06:52:10.842072Z lvl=info msg=“InfluxDB starting” log_id=0oCy7trW000 version=1.8.10 branch=1.8 commit=688e697c51fd

System Environment:
Operating System: Ubuntu 22.04 on Azure
InfluxDB Version: 1.8.10
CPU: 32vCPU
RAM: 128GB
Database Size: 80GB
Disk Type: SSD
cache-max-memory: 32GB
Index Type: TSM

Any help/suggestions are appreciated in advance.
