### ISSUE TITLE
Influxdb v2.0.7 - Impossible to delete data filtering for _field column in predicate

### ISSUE THREAD

**Issue by dsilletti** [influxdata/influxdb#22111] opened 2021-08-08 18:06 UTC
Hi, I am not able to delete data from influxdb v2.0.7, the command does not return error but the serie is still there. This is the command I use: influx delete --org 'myorg' --bucket 'mybucket' --start '2021-06-20T18:56:00Z' --stop '2022-08-20T19:04:00Z' --predicate '_measurement="mqtt_consumer" AND _field="myfield"'

I have the same result also using the python connector.
I need to delete only a particular _field, using --predicate '_measurement="mqtt_consumer" ' it works but it deletes all fields.

**Comment by danxmoran** [comment] 2021-08-09 16:11
@dsilletti this is a known limitation of delete-with-predicate: it's not possible to filter on `_field`. I'm going to close this as a duplicate of #20399, please track that issue for any progress updates

**Closed by danxmoran** 2021-08-09 16:11 UTC
Labels: duplicate
