### ISSUE TITLE
[0.12] create database if not exists never returning

### ISSUE THREAD

**Issue by cheribral** [influxdata/influxdb#6376] opened 2016-04-14 03:19 UTC
### Bug report

**System info:** [Include InfluxDB version, operating system name, and other relevant details]
Branch  Build Time  Commit                      Version
0.12            e094138084855d444195b252314dfee9eae34cab    0.12.1

**Steps to reproduce:**
1. send a "create database if not exists" query via the API

**Expected behavior:** 
The query should come back immediately

**Actual behavior:** 
The query never returns

**Additional info:** 
This happens when upgrading from .11 to .12.  If I roll back, things work again.  Leaving this upgraded means that none of our telegraf agents can report stats because they time out when sending the create database query.

**Comment by e-dard** [comment] 2016-04-14 14:07
@cheribral can you reproduce this on a fresh InfluxDB setup, i.e., specifying a new `Dir` location? Would be useful to know if this is down to your existing Influx system or not.

**Comment by cheribral** [comment] 2016-04-17 22:31
Things work with a blank database, but if we start it on our existing data from 0.11, it starts to hang.  I tried restoring from a backup into 0.12 as well with no difference.

**Comment by codeb2cc** [comment] 2016-04-18 02:45
This happens occasionally when I use telegraf 0.12.0 with InfluxDB 0.12.1. 

Telegraf's log: 

```
2016/04/18 10:23:00 Gathered metrics, (10s interval), from 8 inputs in 124.70712ms
2016/04/18 10:23:05 ERROR: Post http://XX.XX.XX.XX:8686/write?consistency=&db=docker&precision=s&rp=default: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/04/18 10:23:05 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
```

InfluxDB's log:

```
[http] 2016/04/18 08:04:34 XX.XX.XX.XX - telegraf [18/Apr/2016:08:04:34 +0800] GET /query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22docker%22 HTTP/1.1 401 145 - InfluxDBClient 21de6575-04f9-11e6-860e-000000000000 939.701µs
```

I've checked the InfluxDB's log. The error occurred right after the WAL operation:

```
[http] 2016/04/18 07:59:24 XX.XX.XX.XX - telegraf [18/Apr/2016:07:59:24 +0800] POST /write?consistency=&db=docker&precision=s&rp=default HTTP/1.1 204 0 - InfluxDBClient 691a8d2f-04f8-11e6-8426-000000000000 2.145649ms
[tsm1wal] 2016/04/18 07:59:34 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/04/18 07:59:34 tsm1 WAL writing to /data/var/lib/influxdb/8686/wal/docker/default/6
[tsm1] 2016/04/18 07:59:34 /data/var/lib/influxdb/8686/data/docker/default/6 database index loaded in 1.316µs
[http] 2016/04/18 07:59:44 XX.XX.XX.XX - telegraf [18/Apr/2016:07:59:44 +0800] GET /query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22docker%22 HTTP/1.1 401 145 - InfluxDBClient 750290b3-04f8-11e6-842f-000000000000 568.525µs
[http] 2016/04/18 07:59:44 XX.XX.XX.XX - telegraf [18/Apr/2016:07:59:44 +0800] GET /query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22docker%22 HTTP/1.1 401 145 - InfluxDBClient 7502a405-04f8-11e6-8430-000000000000 438.32µs
```

**Comment by jsternberg** [comment] 2016-04-19 13:19
Next time that the database locks, can you try using `SHOW QUERIES` and then issuing a SIGQUIT with Ctrl+\ and posting the panic?

**Comment by cheribral** [comment] 2016-04-21 23:49
Just wanted to update that I haven't forgotten about this, but since I reported this, a new problem has cropped up which prevents me from getting far enough to do what you suggested.  I'll open another ticket for that though.

**Comment by codeb2cc** [comment] 2016-04-25 02:59
`SHOW QUERIES` returns nothing. Issuing a SIGQUIT gets thousands of this: 

```
goroutine 696778 [select, 160 minutes]:
github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints(0xc20805e320, 0xc225c7056c, 0x6, 0xc225c70582, 0x7, 0x1, 0xc2260c6000, 0x1be, 0x200, 0x0, ...)
	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:233 +0x8a1
github.com/influxdata/influxdb/services/httpd.(*Handler).serveWrite(0xc2080742d0, 0x7f00d29c12f8, 0xc219abf2e0, 0xc221aea410, 0xc219d8a150)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:485 +0x16ae
github.com/influxdata/influxdb/services/httpd.*Handler.(github.com/influxdata/influxdb/services/httpd.serveWrite)·fm(0x7f00d29c12f8, 0xc219abf2e0, 0xc221aea410, 0xc219d8a150)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:108 +0x4f
github.com/influxdata/influxdb/services/httpd.func·005(0x7f00d29c12f8, 0xc219abf2e0, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:659 +0x3c4
net/http.HandlerFunc.ServeHTTP(0xc2080ee8a0, 0x7f00d29c12f8, 0xc219abf2e0, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·006(0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:691 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080f0530, 0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·007(0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:700 +0xba
net/http.HandlerFunc.ServeHTTP(0xc2080ee8c0, 0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·008(0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:738 +0x3f4
net/http.HandlerFunc.ServeHTTP(0xc2080f0560, 0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·009(0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:748 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080f0580, 0x7f00d29c1220, 0xc219abf280, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·010(0x7f00d29c1220, 0xc219abf260, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:756 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080ee8e0, 0x7f00d29c1220, 0xc219abf260, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/influxdata/influxdb/services/httpd.func·012(0x7f00d29c11e8, 0xc21f4e1220, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:775 +0x197
net/http.HandlerFunc.ServeHTTP(0xc2080ee900, 0x7f00d29c11e8, 0xc21f4e1220, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc20802e0b8, 0x7f00d29c11e8, 0xc21f4e1220, 0xc221aea410)
	/tmp/influxdb/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc2080742d0, 0x7f00d29c11e8, 0xc21f4e1220, 0xc221aea410)
	/tmp/influxdb/src/github.com/influxdata/influxdb/services/httpd/handler.go:187 +0x467
net/http.serverHandler.ServeHTTP(0xc208e180c0, 0x7f00d29c11e8, 0xc21f4e1220, 0xc221aea410)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc223ba9540)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 696826 [semacquire, 160 minutes]:
sync.(*RWMutex).RLock(0xc20a9d8f90)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/influxdata/influxdb/tsdb.(*MeasurementFields).Field(0xc20a9d8f90, 0xc215850380, 0x10, 0xc20a9d8f90)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:583 +0x2f
github.com/influxdata/influxdb/tsdb.(*Shard).validateSeriesAndFields(0xc217174360, 0xc22602c000, 0x3e8, 0x400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:329 +0x924
github.com/influxdata/influxdb/tsdb.(*Shard).WritePoints(0xc217174360, 0xc22602c000, 0x3e8, 0x400, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:237 +0x147
github.com/influxdata/influxdb/tsdb.(*Store).WriteToShard(0xc208032380, 0xe, 0xc22602c000, 0x3e8, 0x400, 0x0, 0x0)
	/tmp/influxdb/src/github.com/influxdata/influxdb/tsdb/store.go:634 +0x165
github.com/influxdata/influxdb/cluster.(*PointsWriter).writeToShard(0xc20805e320, 0xc219abf1c0, 0xc223beda5c, 0x6, 0xc223beda72, 0x7, 0xc22602c000, 0x3e8, 0x400, 0x0, ...)
	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:249 +0xd4
github.com/influxdata/influxdb/cluster.func·001(0xc219abf1c0, 0xc223beda5c, 0x6, 0xc223beda72, 0x7, 0xc22602c000, 0x3e8, 0x400)
	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:212 +0x98
created by github.com/influxdata/influxdb/cluster.(*PointsWriter).WritePoints
	/tmp/influxdb/src/github.com/influxdata/influxdb/cluster/points_writer.go:213 +0x513

```

**Comment by mark-rushakoff** [comment] 2017-01-11 18:26
Closing this due to age. Please open a new issue if you're experiencing something similar on v1.1.

**Closed by mark-rushakoff** 2017-01-11 18:26 UTC
Labels: area/queries
