### ISSUE TITLE
Data spontaneously dropped from shard, retention policy possibly fails

### ISSUE THREAD

**Issue by daviskirk** [influxdata/influxdb#8937] opened 2017-10-09 14:58 UTC
### Bug report

__System info:__ influxdb:1.3.3, running in docker persisted via host mount

__Steps to reproduce:__

1. Write data to default database (starting using influx 0.10)
2. Upgrade database and continue to write 
3. Change shard duration from 1 week to 3 months
4. Change retention policy to 3650d
5. Continue writing

__Expected behavior:__

Writes continue and data is persisted for 10 years in line with the retention policy (and the expiration date of the shards).  

__Actual behavior:__ 

* 50% of the series from a shard (`378 default      autogen          2017-01-16T00:00:00Z 2017-04-10T00:00:00Z 2027-04-08T00:00:00Z`) are no longer queryable (there is a 3 month hole in all the data) 
* Writes continue to succeed (for the other 50% of time series)
* The shard itself was not empty (300MB vs. 550MB before)
* In the client code there were no "drop shard" commands used, `delete from` is used with specific time series (but never for exactly the shard period) 

__Additional info:__ 

The relevant part of the output of `show shard groups`:

```
220 default      autogen          2016-12-19T00:00:00Z 2016-12-26T00:00:00Z 2026-12-24T00:00:00Z
197 default      autogen          2016-12-26T00:00:00Z 2017-01-02T00:00:00Z 2026-12-31T00:00:00Z
196 default      autogen          2017-01-02T00:00:00Z 2017-01-09T00:00:00Z 2027-01-07T00:00:00Z
195 default      autogen          2017-01-09T00:00:00Z 2017-01-16T00:00:00Z 2027-01-14T00:00:00Z
293 default      autogen          2017-01-16T00:00:00Z 2017-01-23T00:00:00Z 2027-01-21T00:00:00Z
378 default      autogen          2017-01-16T00:00:00Z 2017-04-10T00:00:00Z 2027-04-08T00:00:00Z
432 default      autogen          2017-04-10T00:00:00Z 2017-07-03T00:00:00Z 2027-07-01T00:00:00Z
433 default      autogen          2017-07-03T00:00:00Z 2017-09-25T00:00:00Z 2027-09-23T00:00:00Z
563 default      autogen          2017-09-25T00:00:00Z 2017-12-18T00:00:00Z 2027-12-16T00:00:00Z
564 default      autogen          2017-12-18T00:00:00Z 2018-03-12T00:00:00Z 2028-03-09T00:00:00Z
```

Output of `show retention policies on "default"`:
```
name     duration   shardGroupDuration replicaN default
----     --------   ------------------ -------- -------
autogen  87600h0m0s 2016h0m0s          1        true
```

**Comment by mmuller99** [comment] 2017-10-10 14:11
Can confirm, have the same issue after upgrade and transferring to tsm

**Comment by rbetts** [comment] 2017-10-10 15:12
When you write "Write data to default database (starting using influx 0.10)", did you upgrade directly from version 0.10 to version 1.3.3?  What was the upgrade path you followed?

**Comment by daviskirk** [comment] 2017-10-10 16:43
In my case, I upgraded incrementally.  I can't say exactly which versions I went through exactly but 1.0, 1.1 and 1.2 were used on the way.  I'm also not sure the data wasn't dropped at the exact moment I upgraded to 1.3.3 or if it was a delayed response.

**Comment by gunnaraasen** [comment] 2017-10-12 18:54
If you were upgrading from 0.10, did you do the meta store conversion [described here](http://docs.influxdata.com/influxdb/v1.3/administration/upgrading/#upgrade-from-0-10-or-0-11-to-1-3)?

**Comment by mmuller99** [comment] 2017-10-12 19:44
In our case we upgraded from 1.2.4 to 1.3.0 directly, then incrementally to 1.3.5.

**Comment by daviskirk** [comment] 2017-10-12 20:04
Yes, in out case, we did the meta store conversion as described.  It seemed at the time (probably about a year ago) that everything worked ok.  The actual issue occurred at 1.3.3, but at that time we had been off 0.10 for a long time.  The last upgrade we performed was from 1.3.0 to 1.3.3.

**Comment by stuartcarnie** [comment] 2017-10-13 14:47
@daviskirk do you still have the data from 0.10?

**Comment by mmuller99** [comment] 2017-10-16 15:22
We just did a clean influxdb 1.3.6(tsi1 enabled) reprojection of data in dev from 2016-12-26 to 2017-10-16 and were left with some gaps in the data again.  Where the data went in successfully but the data is not coming out on queries. I can provide the db and which specific series' have gaps

**Comment by stuartcarnie** [comment] 2017-10-16 15:26
@mmuller99 that would be helpful. Can you snapshot the data directory in its current state before additional compactions take place.

* Can you describe the process you use to load the data.
* Did you perform any deletes?

**Comment by stuartcarnie** [comment] 2017-10-16 15:27
I will take the entire db if you don't mind providing it and the queries too

**Comment by mmuller99** [comment] 2017-10-16 15:34
@stuartcarnie where can I reach you? As I can't make the data available publicly

**Comment by daviskirk** [comment] 2017-10-16 15:54
@stuartcarnie Sorry, unfortunately I don't have a backup of data from the 0.10 deployment.  The newer data I'm afraid I can't provide because of confidentiality issues.

**Comment by stuartcarnie** [comment] 2017-10-16 16:04
@mmuller99 I'm going to find out how you can get the files to me. How big is the db when compressed?

**Comment by stuartcarnie** [comment] 2017-10-16 16:25
@mmuller99 we're going to create a location for you to upload the data

**Comment by stuartcarnie** [comment] 2017-10-16 16:45
@mmuller99 I have credentials for you – is your `remotemetering.net` email ok?

**Comment by stuartcarnie** [comment] 2017-10-16 18:50
@daviskirk were you using the TSI1 index?

**Comment by mmuller99** [comment] 2017-10-17 07:10
@stuartcarnie small subset of our data, compressed to 36mb. Yeah the `remotemetering.net` is good

**Comment by mmuller99** [comment] 2017-10-17 11:51
Did a reprojection again with no drop series command beforehand and it seems to be fine.

In our normal operating environment we do need to do a drop series though before we do a reprojection, as in our case data changes historically and with a different time interval between points.

**Comment by daviskirk** [comment] 2017-10-17 12:13
@stuartcarnie No, in the 1.3 versions we haven't upgraded to TSI1, we left the default (which should be still inmem in 1.3.3)

**Comment by stuartcarnie** [comment] 2017-10-17 13:24
@mmuller99 can your provide the output of `show shards` too please?

**Comment by stuartcarnie** [comment] 2017-10-17 13:29
@mmuller99 if you could provide the exact steps you use to reproduce the issue (every command), that would be incredibly helpful

**Comment by mmuller99** [comment] 2017-10-17 13:43
@stuartcarnie will provide the steps in the ftp along with the data

**Comment by mmuller99** [comment] 2017-10-18 07:55
@stuartcarnie can check the ftp

**Comment by stuartcarnie** [comment] 2017-10-18 21:08
@mmuller99 narrowed the issue to TSI in your case. If I remove the index path and disable TSI, the data shows up.

**Comment by jwilder** [comment] 2017-10-19 00:19
The original issue reported by @daviskirk should be fixed by #8981.

**Comment by mmuller99** [comment] 2017-10-19 16:58
@stuartcarnie Nice!

**Comment by jwilder** [comment] 2017-10-20 15:12
Fixed via #8981

**Closed by jwilder** 2017-10-20 15:12 UTC
Labels: area/storage, proposed

**Comment by mmuller99** [comment] 2017-11-07 09:13
@stuartcarnie @jwilder should this be fixed in 1.3.7 or only in 1.4.0? We have done a clean full reproject on production with a fresh 1.3.7 and still have the same problem

**Comment by stuartcarnie** [comment] 2017-11-08 14:41
@mmuller99 are you still using TSI?

**Comment by mmuller99** [comment] 2017-11-08 14:50
@stuartcarnie yes, we are

**Comment by stuartcarnie** [comment] 2017-11-08 15:13
@mmuller99 TSI has undergone a series of significant improvements in 1.4

**Comment by mmuller99** [comment] 2017-11-08 15:20
@stuartcarnie what do you propose we do?  Wait it out, and if we do, do you think the issue will be resolved?

**Comment by stuartcarnie** [comment] 2017-11-08 16:19
@mmuller99 can you provide a list of steps that will repeatedly reproduce the issue with TSI enabled?

**Comment by mmuller99** [comment] 2017-11-08 16:44
@stuartcarnie I have attempted several times to reproduce the problem by running the same processes on a test instance.  Writing, dropping, writing forward again, doing a full series re-project etc etc to no avail.  The issue has to have something to do with time passing like compactions.

The best I can give you is that sample DB that I sent you?

**Comment by jwilder** [comment] 2017-11-08 16:59
@mmuller99 Are you essentially writing to the same measurement/series that you previously dropped?  You can get inconsistencies currently with concurrent write/deletes to the same measurement/series while a compaction runs to evict tombstones series.  That is a different root issue than what was occurring in this bug though.  

We're still working on a fix for that.  If that is happening for you, some workarounds you could try for now are to:
1. Allow the shards that have deletes pending (noted by `*.tombstone` files in the shard) to compact.  They are usually scheduled fairly quickly, but depends on what else is going on in the system.
2. If you see inconsistencies, you can rebuild the `tsi` index manually.

**Comment by mmuller99** [comment] 2017-11-08 17:28
@jwilder that is correct, due to our data changing historically.  Before we did the full clean re-project exercise, we did a manual rebuild of the index of all the shards, due to experiencing [#9025](https://github.com/influxdata/influxdb/issues/9025). After the re-index the gaps were still present and with the release of 1.3.7 we decided to do the clean run.

Is there any way that I can see if the compactions have been done?

Thanks for the response

**Comment by jwilder** [comment] 2017-11-08 17:40
@mmuller99 You can look in the shards dir for `*.tombstone` files.  If they exist, the deletes have not fully compacted yet you could wait to write the data again.

**Comment by mmuller99** [comment] 2017-11-08 17:49
@jwilder no tombstone files present

[DB files.txt](https://github.com/influxdata/influxdb/files/1454888/DB.files.txt)

**Comment by jwilder** [comment] 2017-11-08 17:53
@mmuller99 The workaround I'm suggesting is to avoid the index getting inconsistent.   If won't fix it if it's already inconsistent.   If it's inconsistent now, you would need to rebuild it manually.  To avoid the inconsistency, you could try:
1. Drop your series
2. Wait for compactions to complete (if there are no tombstone files) in the shard dirs, then they should have compacted.
3. Then re-insert data again.

If the issue is due to index inconsistency, this _may_ help.

**Comment by mmuller99** [comment] 2017-11-08 17:56
@jwilder thanks, will give it a go.  We have been re-projecting instantly after the drop.

**Comment by daviskirk** [comment] 2017-11-29 09:53
This is still happening in 1.3.7 (non - tsi), different deployment and different time period than the original bug filing but otherwise the same.  An entire shard just disappears.
