### ISSUE TITLE
Not all buckets are surfaced in `bucket list` or `export all`

### ISSUE THREAD

**Issue by jmmk** [influxdata/influxdb#20725] opened 2021-02-08 18:18 UTC
__Steps to reproduce:__
Have 20 or more existing buckets. This may seem like a lot, but this is on a recently-upgraded Influx that had several `<db>/autogen` buckets that were created by default in Influx 1.x and were carried over by `influxd upgrade`

1. `influx bucket create -n test -r 365d`
2. `influx bucket list`
3. `influx export all`

__Expected behavior:__
The newly-created bucket should be shown when listing or exporting all buckets.

__Actual behavior:__
The bucket is only shown when using `influx bucket list -n test` and only exported when using `influx export --bucket-names test`

__Environment info:__

* System info: `Linux 4.4.0-1085-aws x86_64`
* InfluxDB version: `InfluxDB 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z`

---

The workaround of course is to delete buckets until there are 20 or less. The problem is that there is no indication that data is being truncated. `bucket list` and `export all` do not have any paging capability.

**Comment by danxmoran** [comment] 2021-02-09 14:05
Duplicate of #20079

**Comment by lesam** [comment] 2022-03-16 19:25
This has been fixed - tried on latest version:

```
influx bucket ls
ID                      Name            Retention       Shard group duration    Organization ID         Schema Type
c5517c0d24b01f0b        _monitoring     168h0m0s        24h0m0s                 1327db29a38845f0        implicit
f88f4b1f26dddd1e        _tasks          72h0m0s         24h0m0s                 1327db29a38845f0        implicit
aa2ed9e9037afc9e        bucket-1        infinite        168h0m0s                1327db29a38845f0        implicit
75599d1c31b764c1        bucket-10       infinite        168h0m0s                1327db29a38845f0        implicit
e28a081f5f579ec1        bucket-11       infinite        168h0m0s                1327db29a38845f0        implicit
f02ffe587f8697d6        bucket-12       infinite        168h0m0s                1327db29a38845f0        implicit
7d2a530633a8561a        bucket-13       infinite        168h0m0s                1327db29a38845f0        implicit
7034812e2d4a65f5        bucket-14       infinite        168h0m0s                1327db29a38845f0        implicit
7a4203caf6e5ce97        bucket-15       infinite        168h0m0s                1327db29a38845f0        implicit
0306b08a08deb346        bucket-16       infinite        168h0m0s                1327db29a38845f0        implicit
fd8b6f62f980bf64        bucket-17       infinite        168h0m0s                1327db29a38845f0        implicit
9dae33c6c1b41836        bucket-18       infinite        168h0m0s                1327db29a38845f0        implicit
cf7ac21103249fa5        bucket-19       infinite        168h0m0s                1327db29a38845f0        implicit
e55b722db098fc52        bucket-2        infinite        168h0m0s                1327db29a38845f0        implicit
2b34ff749489acf8        bucket-20       infinite        168h0m0s                1327db29a38845f0        implicit
dfcb58264daa0a6b        bucket-21       infinite        168h0m0s                1327db29a38845f0        implicit
84fec7991d13acf4        bucket-22       infinite        168h0m0s                1327db29a38845f0        implicit
e399c0cea469e08f        bucket-23       infinite        168h0m0s                1327db29a38845f0        implicit
2abea56c7f41396a        bucket-24       infinite        168h0m0s                1327db29a38845f0        implicit
26f83d2aeff9333a        bucket-25       infinite        168h0m0s                1327db29a38845f0        implicit
70764a0d422654cf        bucket-26       infinite        168h0m0s                1327db29a38845f0        implicit
f68b2dd59023cc90        bucket-27       infinite        168h0m0s                1327db29a38845f0        implicit
07838e021efce0bc        bucket-28       infinite        168h0m0s                1327db29a38845f0        implicit
aac1e972fec4360f        bucket-29       infinite        168h0m0s                1327db29a38845f0        implicit
6c55391ec02a9dda        bucket-3        infinite        168h0m0s                1327db29a38845f0        implicit
b701d1998cfa0965        bucket-30       infinite        168h0m0s                1327db29a38845f0        implicit
57688b97217249d8        bucket-31       infinite        168h0m0s                1327db29a38845f0        implicit
5a0865fb4ae74565        bucket-32       infinite        168h0m0s                1327db29a38845f0        implicit
a09c8d5fde0256c8        bucket-33       infinite        168h0m0s                1327db29a38845f0        implicit
ee9b1aeb8073a11f        bucket-34       infinite        168h0m0s                1327db29a38845f0        implicit
821d637d002e66d0        bucket-35       infinite        168h0m0s                1327db29a38845f0        implicit
f8a44944035ed56e        bucket-36       infinite        168h0m0s                1327db29a38845f0        implicit
789966a6b0b07905        bucket-37       infinite        168h0m0s                1327db29a38845f0        implicit
7be043b16746c142        bucket-38       infinite        168h0m0s                1327db29a38845f0        implicit
f5fe7bdbceee4f7c        bucket-39       infinite        168h0m0s                1327db29a38845f0        implicit
8c311148bc74695e        bucket-4        infinite        168h0m0s                1327db29a38845f0        implicit
dbe4f2675739c4be        bucket-40       infinite        168h0m0s                1327db29a38845f0        implicit
caececfe388c2d56        bucket-5        infinite        168h0m0s                1327db29a38845f0        implicit
781dc83dbc3c611c        bucket-6        infinite        168h0m0s                1327db29a38845f0        implicit
a9261baf2eed8855        bucket-7        infinite        168h0m0s                1327db29a38845f0        implicit
4de5f68a9268eb3e        bucket-8        infinite        168h0m0s                1327db29a38845f0        implicit
5b34445455fc7a57        bucket-9        infinite        168h0m0s                1327db29a38845f0        implicit
905246928a83c110        test            infinite        168h0m0s                1327db29a38845f0        implicit
```

**Closed by lesam** 2022-03-16 19:25 UTC
Labels: area/api, area/api-docs, area/2.x
