### ISSUE TITLE
collectd plugin is not working and stopped the influxdb service.

### ISSUE THREAD

**Issue by holmesii** [influxdata/influxdb#5836] opened 2016-02-25 18:04 UTC
I have one server A installed InfluxDB (0.10), and a second server B installed CollectD. 
I tried to enable the collectD plugin in server A, in config file: /etc/influxdb/influxdb.conf, Here is the configure part: 
```
[collectd]
  enabled = true
  bind-address = "127.0.0.1:25826"

  database = "collectd-scheduler"
  typesdb = "/usr/share/collectd/types.db"

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching
  # will buffer points in memory if you have many coming in.

  batch-size = 5000 # will flush if this many points get buffered
  batch-pending = 10 # number of batches that may be pending in memory
  batch-timeout = "10s" # will flush at least this often even if we haven't hit buffer limit
  read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.
```
However, when I restart the service, it doesn't work. Influx is now working. but I can manually run influxd. 

Originally, there is no typesdb file existed in server A:  typesdb = "/usr/share/collectd/types.db", 
I created the folder collectd and wget the types.db file from: https://github.com/collectd/collectd/blob/master/src/types.db

If I disable this plugin in influxdb.conf file, I can start influxdb service. 

Any idea and can you help me? Thank you!

**Comment by rossmcdonald** [comment] 2016-02-25 18:47
@holmesii Regarding:

> However, when I restart the service, it doesn't work.

What do you mean by "it doesn't work?" Does the service come up at all? Or does it crash? Can you provide the logs from the InfluxDB instance?

**Comment by holmesii** [comment] 2016-02-25 18:55
the service does not work. I can't run influx command. But if I disable=false for collectd, I can start the service and run influx command. But the weird thing is that I can manually run "influxd". 

The other thing is that if I use "service influxdb restart", I can see looks all executions are [OK], however, I can't run influx command, it said:
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.

BTW, How can I get the influxdb log for you? Thanks!

**Comment by holmesii** [comment] 2016-02-25 19:04
2016/02/25 17:57:39 InfluxDB starting, version 0.10.1, branch HEAD, commit df902a4b077bb270984303b8e4f8a320e3954b40, built 2016-02-18T20:44:27.807242
2016/02/25 17:57:39 Go version go1.4.3, GOMAXPROCS set to 1
2016/02/25 17:57:39 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/02/25 17:57:39 Starting meta service
[meta] 2016/02/25 17:57:39 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/02/25 17:57:39 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/02/25 17:57:39 Node at localhost:8088 [Follower]
[metastore] 2016/02/25 17:57:40 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[meta] 2016/02/25 17:57:40 127.0.0.1 - - [25/Feb/2016:17:57:40 +0000] GET /?index=0 HTTP/1.1 200 249 - Go 1.1 package http 43621c63-dbe9-11e5-8001-000000000000 1.285339ms
[store] 2016/02/25 17:57:40 Using data dir: /var/lib/influxdb/data
[tsm1wal] 2016/02/25 17:57:40 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/02/25 17:57:40 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/1
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/_internal/monitor/1/_00001.wal, size 698094
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/_internal/monitor/1/_00005.wal, size 3427
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/_internal/monitor/1/_00009.wal, size 0
[tsm1wal] 2016/02/25 17:57:40 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/02/25 17:57:40 tsm1 WAL writing to /var/lib/influxdb/wal/telegraf/default/2
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/telegraf/default/2/_00001.wal, size 341143
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/telegraf/default/2/_00005.wal, size 8995
[cacheloader] 2016/02/25 17:57:40 reading file /var/lib/influxdb/wal/telegraf/default/2/_00009.wal, size 0
[handoff] 2016/02/25 17:57:40 Starting hinted handoff service
[monitor] 2016/02/25 17:57:40 'hh' registered for diagnostics monitoring
[handoff] 2016/02/25 17:57:40 Using data dir: /var/lib/influxdb/hh
[subscriber] 2016/02/25 17:57:40 opened service
[monitor] 2016/02/25 17:57:40 Starting monitor system
[monitor] 2016/02/25 17:57:40 'build' registered for diagnostics monitoring
[monitor] 2016/02/25 17:57:40 'runtime' registered for diagnostics monitoring
[monitor] 2016/02/25 17:57:40 'network' registered for diagnostics monitoring
[monitor] 2016/02/25 17:57:40 'system' registered for diagnostics monitoring
[cluster] 2016/02/25 17:57:40 Starting cluster service
[shard-precreation] 2016/02/25 17:57:40 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/02/25 17:57:40 Starting snapshot service
[copier] 2016/02/25 17:57:40 Starting copier service
[admin] 2016/02/25 17:57:40 Starting admin service
[admin] 2016/02/25 17:57:40 Listening on HTTP: [::]:8083
[continuous_querier] 2016/02/25 17:57:40 Starting continuous query service
[httpd] 2016/02/25 17:57:40 Starting HTTP service
[httpd] 2016/02/25 17:57:40 Authentication enabled: false
[httpd] 2016/02/25 17:57:40 Listening on HTTP: [::]:8086
[collectd] 2016/02/25 17:57:40 Starting collectd service
run: open server: open service: Open(): Line 5: Exactly 4 fields required "html>"

**Comment by rossmcdonald** [comment] 2016-02-25 19:09
@holmesii It looks like the problem is here:

https://github.com/kimor79/gollectd/blob/master/gollectd.go#L330

When the service is attempting to parse the `types.db` file. Can you verify that the `types.db` file is valid? It looks like it has an `html>` tag, which is invalid.

**Comment by holmesii** [comment] 2016-02-25 19:13
I don't know. But could you please provide me a valid one? In my server A, I can't find any collectD DB types file.

**Comment by rossmcdonald** [comment] 2016-02-25 19:24
@holmesii The link to the `types.db` you pasted [above](https://github.com/collectd/collectd/blob/master/src/types.db) is valid. Have you verified that the contents of the file on disk match what is shown through Github?

**Comment by holmesii** [comment] 2016-02-25 19:32
I think I did something wrong, I wget the wrong file. But I then have the corrected file. But the same issue. I now can see the DB transferred from collectD in Server B. However, I don't see any data. Looks like I have to set up the user/privileges in influxDB in server A and also allow authentication. 

Do you have a detailed instruction for collectD in influxdb? Thanks!

**Comment by rossmcdonald** [comment] 2016-02-25 19:41
@holmesii I believe all of the documentation we have is [here](https://github.com/influxdata/influxdb/tree/master/services/collectd). Do you have user authentication enabled in InfluxDB? Unfortunately I'm not sure if the collectd endpoint requires auth or not.

**Comment by holmesii** [comment] 2016-02-25 19:44
yes, I have encrypt enabled in collectD. In fluxdb, I tried to have http enabled. But then I can't login my influxdb. I currently have two users:
>show users
user   admin
xxxx   true

Not sure what does it mean?

**Comment by gabrieljames** [comment] 2016-02-29 08:22
I'm having problems getting InfluxDB to work with collectD 

The documentation is pretty light weight at Influx, serious lack of example configuration files, and there seems to be a lot of changes between versions and the syntax used in the configuration files.

Ubuntu 14.0 LTS 

/etc/influxdb/influxdb.conf
[collectd]
  enabled = true
  bind-address = "127.0.0.1"
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db
**This causes the service to fail**

[collectd]
  enabled = true
  # bind-address = "127.0.0.1"
  # database = "collectd"
  # typesdb = "/usr/share/collectd/types.db
**The service starts but does not have any data**

That is the situation with the bind-address? What are valid names?
localhost? hostname? 127.0.0.1? 
Are ports required?

Early versions on the internet suggest ports are required?

Please provide better documentation on the website

**Comment by rossmcdonald** [comment] 2016-02-29 20:52
@gabrieljames The port needs to be specified in the `bind-address`, but the IP/hostname is optional. For example setting `bind-address = ":1234"` should bind the plugin to port `1234` on all interfaces.

**Comment by gabrieljames** [comment] 2016-02-29 20:59
Thank you, apologies for the grumpy tone.

Please can this be updated on your installation guides at the website?

bind-address = ":1234" 
In the case above is that UDP or TCP?

My understanding is that port 25826 is used or recommended by collectd

**Comment by rossmcdonald** [comment] 2016-02-29 21:04
@gabrieljames There is some documentation [here](https://github.com/influxdata/influxdb/tree/master/services/collectd) (also linked further up in this issue) that has a [configuration example](https://github.com/influxdata/influxdb/tree/master/services/collectd#config-example). The default port is `25826`, with traffic being UDP.

**Comment by holmesii** [comment] 2016-02-29 21:06
Yes, I was using TCP instead of UDP. And all problems resolved. 

Thank you!

**Comment by gabrieljames** [comment] 2016-02-29 21:10
Great, will jump into again and feedback. 

I was referring to the documentation on the influxdata website https://docs.influxdata.com/influxdb/v0.10/administration/config/#collectd

But good there is more documentation on GitHub, will delve into it..

**Comment by rossmcdonald** [comment] 2016-02-29 21:41
@gabrieljames I'm going to go ahead and close this issue, but let us know if you continue to run into issues. I've also created a [PR](https://github.com/influxdata/docs.influxdata.com/pull/282) to help update the documentation.

**Closed by rossmcdonald** 2016-02-29 21:41 UTC
Labels: category/plugins

**Comment by lin-credible** [comment] 2017-03-15 10:28
@rossmcdonald  #8140  ❤️
