### ISSUE TITLE
task: run logs for task, without run ID filter, are returned out of order

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#12649] opened 2019-03-15 17:02 UTC
Partial snippet of a run of `./influx task log find --task-id $TASK_ID`, from commit 769a1a8a10c850db3784882800335e7fbaf008a3, starting from a clean database:

```
2019-03-15T16:29:10.025517Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:29:10.03849Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:29:10.038975Z: Completed successfully
2019-03-15T16:23:50.016591Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:23:50.02234Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:23:50.022931Z: Completed successfully
2019-03-15T16:29:20.02472Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:29:20.02567Z: Run failed to begin execution: <not found> authorization not found
2019-03-15T16:29:20.027534Z: Failed
2019-03-15T16:26:10.019925Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:26:10.031145Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:26:10.031892Z: Completed successfully
2019-03-15T16:27:20.021239Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:27:20.030387Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:27:20.030717Z: Completed successfully
2019-03-15T16:28:00.020105Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:28:00.041691Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:28:00.042065Z: Completed successfully
2019-03-15T16:28:50.02453Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:28:50.030148Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:28:50.030554Z: Completed successfully
2019-03-15T16:29:40.027231Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:29:40.030268Z: Run failed to begin execution: <not found> authorization not found
2019-03-15T16:29:40.031667Z: Failed
2019-03-15T16:23:40.015503Z: Started task from script: "option task = {every: 10s, name: \"z\"} from(bucket:\"a\") |> range(start: -10s)"
2019-03-15T16:23:40.024535Z: {"total_duration":0,"compile_duration":0,"queue_duration":0,"plan_duration":0,"requeue_duration":0,"execute_duration":0,"concurrency":0,"max_allocated":0,"metadata":null,"scanned_values":0,"scanned_bytes":0}
2019-03-15T16:23:40.024873Z: Completed successfully
```

Notice the minutes of the timestamps go 29, 23, 29, 26...

**Comment by mark-rushakoff** [comment] 2019-03-18 21:33
Deprioritizing this for now. I don't think anything in the UI shows the output of `/api/v2/tasks/:id/logs`; when you view the logs for an individual run (as is the case in the UI), this is not an issue.

**Comment by lyondhill** [comment] 2019-09-05 15:00
This is now working as intended, the ordering was fixed with a update to the script we use to pull from influxdb.

**Closed** 2019-09-16 15:38 UTC
Labels: area/tasks, kind/bug, team/compute
