### ISSUE TITLE
struct field Cells repeats in http/dashboard_service.go:144 and dashboard.go:75

### ISSUE THREAD

**Issue by oiooj** [influxdata/influxdb#12321] opened 2019-03-02 17:53 UTC
```
http/dashboard_service.go:144:2: struct field Cells repeats json tag "cells" also at ../dashboard.go:75
```

This issue blocked #12320 tests , we need fix it.

**Comment by mark-rushakoff** [comment] 2019-03-05 22:24
Thanks. This is a duplicate of https://github.com/influxdata/influxdb/issues/11254.

**Closed by mark-rushakoff** 2019-03-05 22:24 UTC
