### ISSUE TITLE
Split results when using a regex to select data from multiple measurements

### ISSUE THREAD

**Issue by xo4n** [influxdata/influxdb#7230] opened 2016-08-29 12:06 UTC
Influxdb splits measurement values in separate output results when it should be part of the same measurement result set

That happens when querying several measurements using a regex and when the time interval spreads through what I assume are 2 different internal data shards  

__System Info:__
 influxdb 1.0.0~rc1  running on Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux

__Steps to reproduce:__
Use a regex in a query to extract data from several measurements. Time interval should go through different  internal shards  ( I am assuming it is that because it happens on weekly basis at midnight, see image attached below)
  
```
SELECT mean("value") FROM /interface-bce.*packets.rx/ WHERE "host" = 'mc1-sfo' AND time > now() - 10h  GROUP BY time(3h)
```

__Expected behavior__: 

```
SELECT mean("value") FROM /interface-bce.*packets.rx/ WHERE "host" = 'mc1-sfo' AND time > now() - 10h  GROUP BY time(3h)
name: interface-bce0.if_packets.rx
----------------------------------
time   			mean
1472428800000000000    	7.500417686746984
1472439600000000000    	7.248924287037038
1472450400000000000    	8.01831603703704
1472461200000000000    	13.073001392781322

name: interface-bce1.if_packets.rx
----------------------------------
time   			mean
1472428800000000000    	14035.236673156622
1472439600000000000    	9240.856418725012
1472450400000000000    	5628.426898156491
1472461200000000000    	6277.791677018038
```

__Actual behavior:__ 

Data for the same measurement is split in 2 result sets with the breaking point being at midnight 

```

> SELECT mean("value") FROM /interface-bce.*packets.rx/ WHERE "host" = 'mc1-sfo' AND time > now() - 2d GROUP BY time(3h)
name: interface-bce0.if_packets.rx
----------------------------------
time   			mean
1472288400000000000    	8.480295829268295
1472299200000000000    	8.828108395370373
1472310000000000000    	9.066861218518536
1472320800000000000    	8.993078010185187
1472331600000000000    	8.200322429629633
1472342400000000000    	7.332781469444439
1472353200000000000    	7.023150565740741
1472364000000000000    	7.86769319351852
1472374800000000000    	8.853294167592578
1472385600000000000    	9.520298317592593
1472396400000000000    	9.870746028703701
1472407200000000000    	10.030028218518519
1472418000000000000    	8.846663225000007
1472428800000000000
1472439600000000000
1472450400000000000
1472461200000000000

name: interface-bce1.if_packets.rx
----------------------------------
time   			mean
1472288400000000000    	6002.7814098188155
1472299200000000000    	8935.1677967787
1472310000000000000    	10631.79456984908
1472320800000000000    	10907.312854782405
1472331600000000000    	10954.77894227777
1472342400000000000    	11852.386950513888
1472353200000000000    	8453.646293356484
1472364000000000000    	5974.488352962958
1472374800000000000    	5763.556632840735
1472385600000000000    	9316.327096708324
1472396400000000000    	12015.311824718514
1472407200000000000    	12879.036636799063
1472418000000000000    	13769.936364505556
1472428800000000000
1472439600000000000
1472450400000000000
1472461200000000000

name: interface-bce0.if_packets.rx
----------------------------------
time   			mean
1472288400000000000
1472299200000000000
1472310000000000000
1472320800000000000
1472331600000000000
1472342400000000000
1472353200000000000
1472364000000000000
1472374800000000000
1472385600000000000
1472396400000000000
1472407200000000000
1472418000000000000
1472428800000000000    	7.654913410185194
1472439600000000000    	7.248924287037038
1472450400000000000    	8.01831603703704
1472461200000000000    	13.88830539344262

name: interface-bce1.if_packets.rx
----------------------------------
time   			mean
1472288400000000000
1472299200000000000
1472310000000000000
1472320800000000000
1472331600000000000
1472342400000000000
1472353200000000000
1472364000000000000
1472374800000000000
1472385600000000000
1472396400000000000
1472407200000000000
1472418000000000000
1472428800000000000    	14607.881179037968
1472439600000000000    	9240.856418725012
1472450400000000000    	5628.426898156491
1472461200000000000    	6111.722678218152
```

__Additional info:__ 

![influxdb_multiple_measurement](https://cloud.githubusercontent.com/assets/9038651/18050857/6716b12a-6df1-11e6-9c84-014fa8e6cc46.png)

**Comment by jsternberg** [comment] 2016-08-29 13:07
Seems like a duplicate of #7220.

**Closed by jsternberg** 2016-08-29 13:07 UTC
