### ISSUE TITLE
An InfluxDB error has occurred when trying to save a Data Explorer query as a Task

### ISSUE THREAD

**Issue by nisley** [influxdata/influxdb#16454] opened 2020-01-08 21:00 UTC
Build a query and try o save it as a task:

An InfluxDB error has occurred 

![image](https://user-images.githubusercontent.com/1389799/72015432-98a76d00-3216-11ea-8fc4-4d78e05db568.png)

**Comment by nisley** [comment] 2020-01-08 21:01
Experienced in both Cloud 2 and OSS beta

**Comment by russorat** [comment] 2020-01-08 21:13
dupe of #16452

**Closed by russorat** 2020-01-08 21:13 UTC
