### ISSUE TITLE
Influxdb-1.6.0 - In Windows (404 Page Not found)

### ISSUE THREAD

**Issue by josly15** [influxdata/influxdb#9668] opened 2018-04-01 01:18 UTC
### Bug report

__System info:__ [Include InfluxDB version : influxdb-1.6.0, Windows 10

__Steps to reproduce:__

1. [First Step] 
     On windows 10, I have configured Config file by making below changes
   
[meta]
  dir = "C:\\Users\\rohan\\influxdb\\meta"
  
[data]
  dir = "C:\\Users\\rohan\\influxdb\\data"
 
  wal-dir = "C:\\Users\\rohan\\influxdb\\wal"
  
2. [Second Step]
 [http]
  # Determines whether HTTP endpoint is enabled.
   enabled = true
   bind-address = ":8086"
  auth-enabled = false
   log-enabled = true

3.  Tried running : influxd -config influxdb.conf - No error observed
4.  On browser : http://localhost:8086

__Expected behavior:__ [What you expected to happen]  - Influx page should display

__Actual behavior:__ [What actually happened] - 404  page Not found

__Additional info:__ [Include gist of relevant config, logs, etc.] : Attached snapshot & config file saved in txt file

![2018_03_31_21_00_12_c_windows_system32_cmd exe_influxd_config_influxdb conf](https://user-images.githubusercontent.com/18605599/38168908-aab18f72-3528-11e8-9a0a-73a393baad2f.png)
[influxdb.txt](https://github.com/influxdata/influxdb/files/1866032/influxdb.txt)

**Comment by timhallinflux** [comment] 2018-04-01 19:49
Keep in mind that you are running a nightly...1.6.0 hasn't been released.  So there may be issue as we are still underdevelopment.  1.5.1 is the current stable release.  You can grab that off the downloads page: https://portal.influxdata.com/downloads

Try: curl -sl -I localhost:8086/ping  or GET http://localhost:8086/ping to test for the availability of the database.

There isn't a page that appears at that endpoint when you attempt to access it through the browser.

If you want to use a UI -- try using Chronograf https://docs.influxdata.com/chronograf/v1.4/introduction/getting-started/

Hope that helps!

**Comment by dgnorton** [comment] 2018-04-01 20:43
@josly15 Start with Tim's advice about testing the `/ping` endpoint to make sure InfluxDB is running and reachable.

In addition to Chronograf as a graphical UI, there is also a command line interface that comes with InfluxDB. You can try running the `influx` command in a shell window. If it connects, type `help` for a list of commands.

Also, check out the [Developers](https://www.influxdata.com/developers/) section on the website. You'll find links to Documentation and the Community site. The InfluxDB docs have examples for writing and reading data using the HTTP API. The community site is a good resource to search for usage questions or post if you don't find an answer.

I'm closing this issue because, as Tim mentioned, there isn't a page that loads at the root endpoint. A 404 is the expected behavior.

**Closed by dgnorton** 2018-04-01 20:43 UTC
