### ISSUE TITLE
pencil menu clips on dashboard cell

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#12053] opened 2019-02-21 16:57 UTC
![image](https://user-images.githubusercontent.com/4805997/53186837-a92b0680-35b6-11e9-95ce-f4ce7deb05a6.png)

**Comment by alexpaxton** [comment] 2019-02-23 00:52
Dupe of https://github.com/influxdata/influxdb/issues/11579

**Closed by alexpaxton** 2019-02-23 00:52 UTC
Labels: epic/dashboardsui
