### ISSUE TITLE
Duplicated rows

### ISSUE THREAD

**Issue by michalg42** [influxdata/influxdb#6721] opened 2016-05-25 10:05 UTC
System info: Influx 0.13.0, Linux Mint 17.2

Steps to reproduce:

Using these file as data source: http://speedy.sh/agpPb/Test.json , having it in directory /home/michal/debug/

And this code:

```
var request = require('request');
var fs = require('fs');

const files = fs.readdirSync('/home/michal/debug/');

const promises = files.map((el2, index) => new Promise((resolve) => {
  fs.readFile('/home/michal/debug/' + el2, (err, res) => {
    const file = JSON.parse(res.toString());
    const data = file.map((el) => 'test30,type='+el[1].type+',id='+el[1].id+',format='+el[1].format+' value='+el[0].value+' '+el[0].time).join('\n');
    request({
      host: {
        name: 'localhost',
        port: 8086,
      },
      url: 'http://localhost:8086/write?u=admin&p=secretpassword&database=test&precision=ms&db=test',
      pool: {},
      body: data,
      method: 'POST',
      originalUrl: 'write?u=admin&p=secretpassword&database=test&precision=ms&db=test'
    }, (err, res) => {
      resolve('Done');
    });
  });
}));

Promise.all(promises).then((res) => {
  console.log(res);
});
```

In Influx terminal executing query:

```
SELECT * FROM test30 WHERE time >= '2016-01-10' AND time < '2016-01-11' AND type = 'O' AND format='daily';
```

Expected behavior: One row with date pointing to 10 january 2016.

Actual behavior: It depends, I executed it many times (what can be seen in measurement number :)), sometimes it works as it should, but sometimes I see three, five, two same results.
I'm not sure if it's issue with selecting and displaying data or writing data, but I thought that Influx shouldn't allow us to add same row multiple times, and, what is more, in the file there is only one record with this time and tags.

**Comment by brewneaux** [comment] 2016-05-27 16:07
This appears to be a duplicate of https://github.com/influxdata/influxdb/issues/6632

Should they be merged? Its also a really big deal, as this completely goes against the expected behavior.

**Comment by jwilder** [comment] 2016-07-19 00:42
Dup of #6632

**Closed by jwilder** 2016-07-19 00:42 UTC
