### ISSUE TITLE
Performance for queries with tag <> '' seems significantly degraded with 0.13 and 1.0.0-rc1

### ISSUE THREAD

**Issue by xiam** [influxdata/influxdb#7243] opened 2016-08-30 14:07 UTC
### Bug report

There's a significant speed difference between 0.12 and 0.13+ when using a query like this:

```
select sum(value) from visitors where ip <> ''
```

It takes 2.5s on 0.12:

```
time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m2.506s
user    0m0.004s
sys     0m0.004s
```

But on 0.13 it takes 35s

```
 time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m34.780s
user    0m0.003s
sys     0m0.003s

```

And on 1.0.0-rc1 it takes 47s.

```
time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"
name: visitors
--------------
time    sum
0       235673


real    0m46.913s
user    0m0.005s
sys     0m0.017s
```

All 3 cases make the processor go to the top, in the first case it stays there for 3 seconds while on the other two cases it stays on top for much longer.

In this dataset `ip` is a string representation of an IPv4 address, series looks like this:

```
show series
...
visitors,ip=254.247.144.250
visitors,ip=254.248.148.130
visitors,ip=254.248.166.225
visitors,ip=254.248.215.152
visitors,ip=254.248.218.103
...
```

Speed seems to improve when using `= '254.248.148.130'` (fastest!) and `<> '254.248.148.130'` (still decent) but not as good when using `<> ''`, in this dataset, there's no tag with the `''` value (there's however the possibility that this tag could be empty at some point).

The current dataset I am using to test has about 18k different values on this tag, if the database is larger, influxdb 0.13+ takes more time to compute a query like that, even tho when the same query takes a few seconds on 0.12. I could generate a larger dataset if this one doesn't produce a noticeable effect on your end.

Thanks.

__System info:__ Influxdb 0.13 and 1.0.0-rc1, Ubuntu Linux (3.13.0-24-generic)

__Steps to reproduce:__

1. Import this dataset [square_holes.tar.gz](https://github.com/influxdata/influxdb/files/444993/square_holes.tar.gz) with `influxd restore -database square_holes`, you can also generate a dataset with [this program](https://gist.github.com/xiam/c61c53f2e463c344824ce563ed39eec8). The database I attached has about 18k different values, which seems to be enough to demonstrate this behaviour.
2. Compare this command `time influx -database square_holes -execute "select sum(value) from visitors where ip <> ''"` on 0.12, 0.13 and 1.0.0-rc1. 

__Expected behavior:__ Query performance is better or equal on greater versions.

__Actual behavior:__ Query performance, for this particular case, was degraded.

__Additional info:__

* [block.txt](https://github.com/influxdata/influxdb/files/445058/block.txt)
* [goroutine.txt](https://github.com/influxdata/influxdb/files/445060/goroutine.txt)
* [heap.txt](https://github.com/influxdata/influxdb/files/445063/heap.txt)
* [vars.txt](https://github.com/influxdata/influxdb/files/445065/vars.txt)
* [iostat.txt](https://github.com/influxdata/influxdb/files/445066/iostat.txt)
* [shards.txt](https://github.com/influxdata/influxdb/files/445067/shards.txt)
* [stats.txt](https://github.com/influxdata/influxdb/files/445068/stats.txt)
* [diagnostics.txt](https://github.com/influxdata/influxdb/files/445069/diagnostics.txt)

**Comment by jsternberg** [comment] 2016-08-30 19:09
So I think the cause of this was a bugfix to make empty tags work correctly. Looking at the code, I would guess that `<> 'someval'` will perform the same as 0.12's performance of `<> ''` (which you report that it does) because those use the same code. #3773 goes into some detail on this.

So basically, `<> ''` is telling it to include every series that has any value for that tag. I think the current behavior is correct, but we might be able to improve the performance of this.

**Comment by pkieltyka** [comment] 2016-08-30 19:25
@jsternberg I'm trying to understand as well the issue.. a few questions.

1. how come between versions the performance is so different?
2. why would it be a problem to search for an empty string of an indexed value in influx to the extent it takes 47s to search through a few megabytes of data?

**Comment by pkieltyka** [comment] 2016-08-30 19:27
perhaps there is another way to structure/query the data? the intent is to find the sum in the series where a tag is of a particular value, in this case an empty string

**Comment by jsternberg** [comment] 2016-08-30 19:33
1. how come between versions the performance is so different?

A bug was fixed in 0.13 that made it work correctly, but that seems to have been at the cost of performance. The previous way (that was wrong) performed much faster. I think, in 0.12, using `WHERE tag <> ''` would just return everything instead of not returning the series that had a blank tag for that key.

2. why would it be a problem to search for an empty string of an indexed value in influx to the extent it takes 47s to search through a few megabytes of data?

This is where things become a little more complicated and I have to speculate a little. The reason why it's difficult is because we don't index nothing. To do so would be impossible since every series that doesn't specify a tag key has an implicit value of an empty string. We can't index every possible string value on the planet, so we don't even try. So in order to fulfill this query, we instead take a list of every series that has a value (these are indexed) and combine them into a single array. I think this is causing a lot of memory to be allocated and for the performance to be slower especially if you have a high cardinality with that tag key.

Any operation comparing against a tag value that is anything other than the empty string will perform a lot better. We do have to optimize this case though.

**Comment by pkieltyka** [comment] 2016-08-30 19:37
cool that makes sense. perhaps you could make an exception for the empty string? otherwise, we will probably just pick "<>" as a token for ourselves to represent an empty value. we'll do that for now. thanks for the quick replies.

**Comment by e-dard** [comment] 2016-08-30 21:23
@xiam thanks for providing such a detailed issue! It makes our jobs a lot easier. 👍

**Comment by jsternberg** [comment] 2016-09-01 16:56
Thanks for the help! This is merged into the 1.0 branch. It, unfortunately, did not make the 1.0.0-rc2, but it will be in the final 1.0.0. It is also currently in master.

**Closed by jsternberg** 2016-09-01 16:56 UTC
Labels: performance, regression

**Comment by xiam** [comment] 2016-09-01 17:39
Awesome! thanks a lot.

**Comment by VojtechVitek** [comment] 2016-09-01 18:03
Thanks a lot, @e-dard @jsternberg!
