### ISSUE TITLE
Question: can't start influxd v0.10.0 on rasp B2 - madvise

### ISSUE THREAD

**Issue by forcie** [influxdata/influxdb#5589] opened 2016-02-09 12:30 UTC
Hi,

I can't seem to be able to start influxd freshly compiled on a Raspberry PI 2.
I get the following error:
run: open server: open meta service: raft: new bolt store: madvise: function not implemented
(Full output here: http://pastebin.com/yUGum3Y6)

Am I missing something?
Any advise appreciated. Thanks

**Comment by rossmcdonald** [comment] 2016-02-09 13:24
@forcie From your output it says it was compiled on `2015-12-31T01:11:17+0000`. Can you try compiling from master again?

You can compile for ARM using the `build.py` script:

```
./build.py --package --version=0.10.1 --arch=arm --pkgarch=armhf
```

**Comment by forcie** [comment] 2016-02-09 13:35
Thanks rossmcdonald for your answer,
That's not the output I meant to pass as reference, but I did attempt to install a package compiled in December.
Today I rebuilt influxd and I get exactly the same error:
```
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2016/02/09 14:29:22 InfluxDB starting, version v0.10.0, branch master, commit af1a22da763414b6cc2f8c12f25b107521c19a30, built 2016-02-09T10:19:15.537860
2016/02/09 14:29:22 Go version go1.4.3, GOMAXPROCS set to 4
2016/02/09 14:29:22 no configuration provided, using default settings
[meta] 2016/02/09 14:29:22 Starting meta service
[meta] 2016/02/09 14:29:22 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/02/09 14:29:22 Using data dir: /root/.influxdb/meta
run: open server: open meta service: raft: new bolt store: madvise: function not implemented
```

**Comment by rossmcdonald** [comment] 2016-02-09 13:46
@forcie Ah, thanks. I can't say I've ever seen that message before. Did you compile InfluxDB with the `build.py` script? If so, can you paste the output?

**Comment by forcie** [comment] 2016-02-09 14:05
I first tried `package.sh` but ran into trouble. `build.py` seemed to have done the trick though:
```
> ./build.py --package

Checking environment:
- GOPATH -> /home/forcie/.gvm/pkgsets/go1.4.3/influxdb:/home/forcie/.gvm/pkgsets/go1.4.3/global
- GOBIN -> None
- GOROOT -> /home/forcie/.gvm/gos/go1.4.3
!! WARNING: Your current directory is not under your GOPATH. This may lead to build failures.

Checking for dependencies:
- git -> /usr/bin/git
- go -> /home/forcie/.gvm/gos/go1.4.3/bin/go
- gvm (optional) -> /home/forcie/.gvm/bin/gvm
- fpm (optional) -> /usr/local/bin/fpm
- rpmbuild (optional) -> ?

Retrieving Go dependencies...
Moving back to branch 'master'...

-------------------------

Build Plan:
- version: v0.10.0
- commit: af1a22d
- branch: master
- platform: linux
- arch: arm
- ARM version: 6
- nightly? false
- race enabled? false

Starting build...
Building 'build/influx_stress'...
Building 'build/influxd'...
Building 'build/influx_inspect'...
Building 'build/influx'...
Building 'build/influx_tsm'...

-------------------------

Packaging...
Creating package filesystem at root: /tmp/influxdb-build.YqldHq/linux/arm/influxdb-v0.10.0-1
Copying scripts and sample configuration to build directory
Packaging directory '/tmp/influxdb-build.YqldHq/linux/arm/influxdb-v0.10.0-1' as 'deb'...
MD5(build/influxdb_v0.10.0-1_arm.deb) = 4a4cd1703f2306cd7885e845954f3d30
Packaging directory '/tmp/influxdb-build.YqldHq/linux/arm/influxdb-v0.10.0-1' as 'rpm'...


Executed command failed!
-- Command run was: fpm -f -s dir --log error --vendor InfluxData --url https://github.com/influxdata/influxdb --after-install scripts/post-install.sh --before-install scripts/pre-install.sh --after-remove scripts/post-uninstall.sh --license MIT --maintainer support@influxdb.com --directories /var/log/influxdb --directories /var/lib/influxdb --description "Distributed time-series database." --config-files /etc/influxdb/influxdb.conf --config-files /etc/logrotate.d/influxdb --name influxdb -a arm -t rpm --version v0.10.0 --iteration 1 -C /tmp/influxdb-build.YqldHq/linux/arm/influxdb-v0.10.0-1 -p build --depends coreutils --rpm-posttrans scripts/post-install.sh
-- Failure was: {:timestamp=>"2016-02-09T15:01:52.604469+0100", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}


Stopping.
./build.py --package  94.40s user 11.06s system 91% cpu 1:55.44 total

```
As you can see it ends with an error regarding rpmbuild that I don't have. However the deb package is already in the folder `build` so I figured it was not too important.

**Comment by rossmcdonald** [comment] 2016-02-09 14:11
@forcie That's correct. As long as you don't need the RPM, then you can ignore that last error.

Is `influxd` starting correctly now? Or are you still seeing that error?

**Comment by forcie** [comment] 2016-02-09 14:44
@rossmcdonald thank you very much for following up again. Unfortunately, however the way I try to start `influxd`, I keep getting the same error:
```
> ./influxd 

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2016/02/09 15:43:00 InfluxDB starting, version v0.10.0, branch master, commit af1a22da763414b6cc2f8c12f25b107521c19a30, built 2016-02-09T14:00:12.222704
2016/02/09 15:43:00 Go version go1.4.3, GOMAXPROCS set to 4
2016/02/09 15:43:00 no configuration provided, using default settings
[meta] 2016/02/09 15:43:00 Starting meta service
[meta] 2016/02/09 15:43:00 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/02/09 15:43:00 Using data dir: /home/jean/.influxdb/meta
run: open server: open meta service: raft: new bolt store: madvise: function not implemented
```

**Comment by rossmcdonald** [comment] 2016-02-09 14:53
@benbjohnson Have you seen the error above before? It mentions both bolt and raft, so I'm not sure which is the cause.

**Comment by forcie** [comment] 2016-02-09 15:04
@rossmcdonald Truth is I'm new with Go and InfluxDB. It's the first time I try to use these tools. I have thus never seen these errors but then again I have no experience with InfluxDB.
Do you think I could be missing requirements and need to install "raft" or "bolt"?

**Comment by rossmcdonald** [comment] 2016-02-09 15:12
@forcie It's possible, though I think a missing dependency should have stopped you from building the binary at all. Can you try the same build command as before, except adding a `--update`?

```
./build.py --package --update --version=0.10.1 --arch=arm --pkgarch=armhf
```

That should update the Go dependencies in case they were outdated.

**Comment by forcie** [comment] 2016-02-09 15:52
I ran the command as instructed. This time I received "unrecognized import path" errors that might be due to my rather messed up paths:
http://pastebin.com/1kN1riL7

**Comment by rossmcdonald** [comment] 2016-02-09 16:13
@forcie Yes, your `GOPATH` must be under where the InfluxDB repository is located. For example, if you have InfluxDB cloned to `/home/forcie/go/src/github.com/influxdb/influxdb`, then your `GOPATH` must be set to `export GOPATH=/home/forcie/go`.

There is some documentation on this [here](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#cloning-a-fork).

**Comment by forcie** [comment] 2016-02-09 16:29
@rossmcdonald I followed your advise and fixed the inconsistencies:
InfluxDB cloned to `/home/forcie/.gvm/pkgsets/go1.4.3/global/src/github.com/influxdb/influxdb`
`GOPATH` is `/home/jean/.gvm/pkgsets/go1.4.3/global`
I then ran this exact command `./build.py --package --update --version=0.10.1 --arch=arm --pkgarch=armhf`
It went all the way to the deb packaging with success.
Unfortunately it did not solve my problem:
```
> build/influxd                                                           

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2016/02/09 17:28:10 InfluxDB starting, version 0.10.1, branch master, commit aacacbc4c3c4b19eeef40027f8309b464e185572, built 2016-02-09T16:27:13.500801
2016/02/09 17:28:10 Go version go1.4.3, GOMAXPROCS set to 4
2016/02/09 17:28:11 no configuration provided, using default settings
[meta] 2016/02/09 17:28:11 Starting meta service
[meta] 2016/02/09 17:28:11 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/02/09 17:28:11 Using data dir: /home/forcie/.influxdb/meta
run: open server: open meta service: raft: new bolt store: madvise: function not implemented
```
Would you have any other idea by any chance?

**Comment by markusr** [comment] 2016-02-09 19:39
Maybe it is a problem with ARMv6 and ARMv7. 
Can you try:
`./build.py --arch=arm --pkgarch=armhf --goarm=7 --platform=linux --version=0.10.1 --package --clean`

**Comment by benbjohnson** [comment] 2016-02-09 21:56
@rossmcdonald @forcie I'm not sure what level of support there is for ARMv7 in Go 1.4. Can you try building with Go 1.5?

**Comment by forcie** [comment] 2016-02-09 22:41
@rossmcdonald  @markusr thank you very much for your suggestions. I tried both thoroughly but no luck, I still get the same result with the newly built binary.
Not sure what I'm doing wrong.

**Comment by markusr** [comment] 2016-02-10 11:07
@nsteinmetz
Can you share your build or instructions since you have compiled and started it successfully on rpi2?
#5560

**Comment by nsteinmetz** [comment] 2016-02-10 12:01
Hi there,

I did try to run ìndluxd`` by itself and will check later but InfluxDB UI was up & running and my app could still feed InfludDB from what I could see.

So my build process:

```
$ wget https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
$ chmod +x gvm-installer 
$ ./gvm-installer
Cloning from https://github.com/moovweb/gvm.git to /home/pi/.gvm
No existing Go versions detected
Installed GVM v1.0.22
Please restart your terminal session or to get started right away run
 `source /home/pi/.gvm/scripts/gvm`
$ source /home/pi/.gvm/scripts/gvm
$ gvm install go1.4.3
Downloading Go source...
Installing go1.4.3...
 * Compiling...
$ gvm use go1.4.3 --default
Now using version go1.4.3
mkdir $HOME/gocodez
export GOPATH=$HOME/gocodez
go get github.com/influxdb/influxdb
cd $GOPATH/src/github.com/influxdb/influxdb
./build.py --package --version=0.10.1 --arch=arm --pkgarch=armhf
```

I could start indluxdb via systemd.

Will check ``influxd``output this evening and let you know.

**Comment by nsteinmetz** [comment] 2016-02-10 13:42
From @forcie, I see:

```
[metastore] 2016/02/09 17:28:11 Using data dir: /home/forcie/.influxdb/meta
```
I supposed the ``/etc/influxdb/influxdb.conf`` file has been changed from default one.

@forcie, could you try with the default configuration file via: 

```
influxd config > /etc/influxdb/influxdb.conf.generated
```

Replace yours and test to see if it comes from here...

**Comment by rossmcdonald** [comment] 2016-02-10 13:58
@nsteinmetz If a configuration is not provided (as is the case here, since @forcie is just running the `influxd` binary directly and not through a packaged install), then it will default to the running user's home directory, so I don't think that's the issue. 

The packaged configuration does still default to `/etc/influxdb/influxdb.conf` though.

**Comment by forcie** [comment] 2016-02-10 15:39
@nsteinmetz Thanks for the suggestion, I tried anyway just to make sure but no luck :(

**Comment by nsteinmetz** [comment] 2016-02-10 19:56
Works for me:

```
pi@cixi ~ $ sudo systemctl stop influxdb
pi@cixi ~ $ influxd

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2016/02/10 20:54:12 InfluxDB starting, version 0.10.1, branch master, commit 7d03cd859e0d5249facb227982929637d98d33cd, built 2016-02-09T20:41:38.857330
2016/02/10 20:54:12 Go version go1.4.3, GOMAXPROCS set to 4
2016/02/10 20:54:12 no configuration provided, using default settings
[meta] 2016/02/10 20:54:12 Starting meta service
[meta] 2016/02/10 20:54:12 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/02/10 20:54:12 Using data dir: /home/pi/.influxdb/meta
[metastore] 2016/02/10 20:54:12 Node at localhost:8088 [Follower]
[metastore] 2016/02/10 20:54:14 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[meta] 2016/02/10 20:54:14 127.0.0.1 - - [10/Feb/2016:20:54:14 +0100] GET /?index=0 HTTP/1.1 200 70 - Go 1.1 package http 0fa64c04-d030-11e5-8001-000000000000 10.633246ms
[meta] 2016/02/10 20:54:14 127.0.0.1 - - [10/Feb/2016:20:54:14 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 0fa911e0-d030-11e5-8003-000000000000 11.594905ms
[meta] 2016/02/10 20:54:14 127.0.0.1 - - [10/Feb/2016:20:54:14 +0100] GET /?index=2 HTTP/1.1 200 76 - Go 1.1 package http 0fa89e05-d030-11e5-8002-000000000000 22.63221ms
[store] 2016/02/10 20:54:14 Using data dir: /home/pi/.influxdb/data
[handoff] 2016/02/10 20:54:14 Starting hinted handoff service
[monitor] 2016/02/10 20:54:14 'hh' registered for diagnostics monitoring
[handoff] 2016/02/10 20:54:14 Using data dir: /home/pi/.influxdb/hh
[subscriber] 2016/02/10 20:54:14 opened service
[monitor] 2016/02/10 20:54:14 Starting monitor system
[monitor] 2016/02/10 20:54:14 'build' registered for diagnostics monitoring
[monitor] 2016/02/10 20:54:14 'runtime' registered for diagnostics monitoring
[monitor] 2016/02/10 20:54:14 'network' registered for diagnostics monitoring
[monitor] 2016/02/10 20:54:14 'system' registered for diagnostics monitoring
[cluster] 2016/02/10 20:54:14 Starting cluster service
[monitor] 2016/02/10 20:54:14 Storing statistics in database '_internal' retention policy '', at interval 10s
[shard-precreation] 2016/02/10 20:54:14 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/02/10 20:54:14 Starting snapshot service
[copier] 2016/02/10 20:54:14 Starting copier service
[admin] 2016/02/10 20:54:14 Starting admin service
[admin] 2016/02/10 20:54:14 Listening on HTTP: [::]:8083
[continuous_querier] 2016/02/10 20:54:14 Starting continuous query service
[httpd] 2016/02/10 20:54:14 Starting HTTP service
[httpd] 2016/02/10 20:54:14 Authentication enabled: false
[httpd] 2016/02/10 20:54:14 Listening on HTTP: [::]:8086
[retention] 2016/02/10 20:54:14 Starting retention policy enforcement service with check interval of 30m0s
[run] 2016/02/10 20:54:14 Listening for signals
2016/02/10 20:54:14 Sending anonymous usage statistics to m.influxdb.com
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 15a43472-d030-11e5-8005-000000000000 19.957545ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:14 +0100] GET /?index=3 HTTP/1.1 200 116 - Go 1.1 package http 0fac9c46-d030-11e5-8004-000000000000 10.034679448s
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 15a86b8f-d030-11e5-8007-000000000000 13.389839ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] GET /?index=4 HTTP/1.1 200 139 - Go 1.1 package http 15a8424f-d030-11e5-8006-000000000000 19.750203ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 15ac0197-d030-11e5-8009-000000000000 15.284354ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] GET /?index=5 HTTP/1.1 200 140 - Go 1.1 package http 15abbeab-d030-11e5-8008-000000000000 19.461872ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 15af2c05-d030-11e5-800a-000000000000 11.906257ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] GET /?index=6 HTTP/1.1 200 123 - Go 1.1 package http 15af2c06-d030-11e5-800b-000000000000 14.12853ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] POST /execute HTTP/1.1 200 28 - Go 1.1 package http 15b208ce-d030-11e5-800d-000000000000 10.51455ms
[meta] 2016/02/10 20:54:24 127.0.0.1 - - [10/Feb/2016:20:54:24 +0100] GET /?index=7 HTTP/1.1 200 156 - Go 1.1 package http 15b1c48d-d030-11e5-800c-000000000000 15.078105ms
[tsm1wal] 2016/02/10 20:54:24 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/02/10 20:54:24 tsm1 WAL writing to /home/pi/.influxdb/wal/_internal/monitor/1
```

**Comment by rossmcdonald** [comment] 2016-02-10 20:06
@nsteinmetz @forcie What operating system are each of you running?

**Comment by nsteinmetz** [comment] 2016-02-10 20:08
Rapbian Jessie (lite?)

**Comment by forcie** [comment] 2016-02-11 08:45
@nsteinmetz I understand it works for most people, which is why I'm determine to fix it.
@rossmcdonald You might find that I run an unexpected system for what I'm trying to do... I run Xbian: [http://www.xbian.org/](http://www.xbian.org/) but it's based on a minimal debian so I assumed it would work just as nicely.

**Comment by markusr** [comment] 2016-02-11 10:53
@forcie 
May be this is a kernel issue. As I understand it `TRANSPARENT_HUGEPAGE`must be enabled in the kernel config. 

Can you post: 
`cat /sys/kernel/mm/transparent_hugepage/enabled`

and your [kernel config](http://superuser.com/questions/287371/obtain-kernel-config-from-currently-running-linux-system)?

**Comment by forcie** [comment] 2016-02-11 12:42
@markusr thanks, you might be on to something..
There's nothing in `/sys/kernel/mm/`:
```
rpi2# cd /sys/kernel/mm
rpi2# ls -la
total 0
drwxr-xr-x 2 root root 0 Feb 11 13:06 .
drwxr-xr-x 6 root root 0 Feb 11 13:06 ..
rpi2# 
```
I'm afraid the kernel was not even compiled with what is necessary :(
Here's the config though: [http://pastebin.com/raw/XmZ2Xz1P](http://pastebin.com/raw/XmZ2Xz1P)

**Comment by markusr** [comment] 2016-02-12 10:50
@forcie 
I think we can close this issue here. I recommend that you switch to Rapbian or compile your own kernel.

**Comment by rossmcdonald** [comment] 2016-02-12 14:17
Agreed. @forcie I'd recommend trying Raspbian (or even Pidora) if you need InfluxDB to work on your Raspberry Pi. Unfortunately we can't support custom-compiled kernels.

@markusr @nsteinmetz Thank you for the help here.

**Closed by rossmcdonald** 2016-02-12 14:17 UTC
Labels: category/packaging

**Comment by forcie** [comment] 2016-02-12 16:11
@markusr @nsteinmetz @rossmcdonald Thanks to you all!
I will try compiling my own kernel (I really want to confirm that was the issue now), and will keep you posted!
