### ISSUE TITLE
Return an error for any queries that can't complete due to invalid data types

### ISSUE THREAD

**Issue by corylanou** [influxdata/influxdb#3818] opened 2015-08-24 21:34 UTC
Currently, you can get into a scenario where you have the same field in multiple shards with different underlying data types.  This is due to how shards are created.  This is NOT a recommended strategy, and hopefully one users only end up in by accident.

There are two things that can happen.

1. When issuing a query that requires math against the specified field, if at least one of the shards has the correct data type, we can return just the data we can do arithmetic on.
1. If none of the shards have an underlying data type that is usable (such as `string` when the `sum` aggregate function is used), then we should return an error to the user stating that the query they asked for is invalid against the fields they specified.

Example:

```sql
select sum(bytes) from usage
```

If all of the data written to `bytes` was a `string`, an error should be returned.  However, if it was a `float` or an `int` then it would be fine.  If it was mixed, with both `string` and `int`, then only the `int`s would be added and returned, ignoring the non-valid data types.

**Comment by beckettsean** [comment] 2015-08-24 22:10
@corylanou in the event of mixed types, how would the user know that only partial results had been returned? Can we put an error in the return as well?

**Comment by peekeri** [comment] 2015-09-17 13:42
I got bitten by this today and took quite some time to figure out that the datatype of the field I was trying to SUM() over was actually stored as string.

I would very much like SUM or any other arithmetic function to fail hard in case there are any shards with data type that is not applicable to the operation that is being performed. I found getting 0 as a result of SUM very confusing, but clearly an error somewhere. On the other hand, if I would get only partial results, that would be both very confusing and extremely hard to spot.

**Comment by jsternberg** [comment] 2016-05-16 22:23
In the latest version, we fail if you are trying to use a field that doesn't work with an aggregate. We also now have #6529 for selecting a specific type and better support for casting types from different shards to the appropriate type.

I'm going to close this since I think the issue is outdated. Please reopen if I am mistaken.

**Closed by jsternberg** 2016-05-16 22:23 UTC
Labels: category/error handling, category/queries
