### ISSUE TITLE
Nested variables no longer work

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17593] opened 2020-04-03 04:00 UTC
in previous versions of the app, variables could be defined to depend on other variables. That looks like it has been removed.

`v.bucket`
```
buckets()
  |> filter(fn: (r) => r.name !~ /^_/)
  |> rename(columns: {name: "_value"})
  |> keep(columns: ["_value"])
```

`v.agent_host`
```
import "influxdata/influxdb/v1"
v1.tagValues(bucket: v.bucket, tag: "host", predicate: (r) => r._measurement == "sflow")
```

`v.agent_host` is never populated even though `v.bucket` is set

![image](https://user-images.githubusercontent.com/4805997/78322899-e9341b00-7524-11ea-8f52-5fffb4166795.png)

**Comment by ebb-tide** [comment] 2020-04-03 18:09
dupe of https://github.com/influxdata/influxdb/issues/17606

**Closed** 2020-04-03 18:10 UTC
Labels: kind/bug, regression, team/monitoring
