### ISSUE TITLE
Don't panic on invalid/unparsable configuration file (low)

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [influxdata/influxdb#20760] opened 2021-02-16 08:08 UTC
If the configuration file contains an error, the current version panics. For instance consider this - invalid - configuration file:

```
user@server cwd $ cat /etc/influxdb/config.toml
bolt-path = "/var/lib/influxdb/influxd.bolt"
engine-path = "/var/lib/influxdb/engine"
reporting-disable = True
```

This will failt to parse (it should be `true` instead of `True`) and call `panic()`.

Although not neccessarily wrong, panic makes an administration nervous ;)

__Expected behavior:__
Influxd starts, fail to parse the configuration file, print an error and exit normally with an exit code > 0.

e.g. something like
```
user@server cwd $ /usr/bin/influxd
Invalid config file: While parsing config: (3, 21): keys cannot contain new lines
user@server cwd $ echo $?
1
```

__Actual behavior:__
Influxd starts but panics on invalid configuration file
```
user@server cwd $ /usr/bin/influxd
panic: invalid config file caused panic: While parsing config: (3, 21): keys cannot contain new lines

goroutine 1 [running]:
github.com/influxdata/influxdb/v2/kit/cli.NewCommand(0xc000b2a000, 0xc000b1d740, 0xc000292b00)
        /home/circleci/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:69 +0x37f
github.com/influxdata/influxdb/v2/cmd/influxd/launcher.NewInfluxdCommand(0x3a4f000, 0xc000122000, 0xc000b2a000, 0xc)
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/cmd.go:42 +0x11a
main.main()
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:36 +0x23e
```
**Nitpicking:** The error is a little bit misleading too.

__Environment info:__

* OS: CentOS 8.3, Debian 10, Debian 11
* InfluxDB version: `InfluxDB 2.0.4 (git: 4e7a59bb9a) build_date: 2021-02-08T17:47:02Z`

**Comment by danxmoran** [comment] 2021-02-16 15:15
Duplicate of #20491

**Comment by danxmoran** [comment] 2021-03-05 00:04
Closing this as a duplicate, please track #20491 for progress

**Closed by danxmoran** 2021-03-05 00:04 UTC
Labels: area/2.x, area/configuration, duplicate, panic
