### ISSUE TITLE
Influx2 doesnt work with docker

### ISSUE THREAD

**Issue by angelademarco** [influxdata/influxdb#21766] opened 2021-06-30 13:42 UTC
Same problem as others, but for me inserts and queries crash de container with OOM after a while using the most default configuration, even with no memory limitations set.

Influx version: 2.0.4

To reproduce just start the container and start inserting data (3mi records should do it) in a machine with about 4gb of ram

**Comment by danxmoran** [comment] 2021-07-07 14:46
Closing as a duplicate of #21765

**Closed by danxmoran** 2021-07-07 14:46 UTC
