### ISSUE TITLE
After restarting Influxdb Data present on disk but Not queryable 

### ISSUE THREAD

**Issue by stevebang** [influxdata/influxdb#10101] opened 2018-07-18 15:49 UTC
_From @singhankur on July 18, 2018 13:5_

```
Influxdb version 1.5.1
index-version = "tsi1"
```

Influxdb is restarted because of 
**fatal error: runtime: out of memory,** this is caused by some **lvl=warn msg="Detected slow query:**

after this influxdb service is down, then after restarting the influx via command 

`sudo service influxdb start
`

Data for all databases is present in data directory
but for few databases the data is not queryable, 
while accessing via query. No result is returned 

when the restart happens, for the problematic databases data is only present from the beginning of the day when the influxdb got restarted 

_Copied from original issue: influxdata/docs.influxdata.com#1723_

**Comment by stuartcarnie** [comment] 2018-07-19 15:35
Duplicate of #10100

**Closed by stuartcarnie** 2018-07-19 15:35 UTC
