### ISSUE TITLE
Unable to convert a user to owner in the org

### ISSUE THREAD

**Issue by urjitbhatia** [influxdata/influxdb#19570] opened 2020-09-16 02:05 UTC
List the minimal actions needed to reproduce the behavior.

1. Create an org
2. Create a user from the cli
3. Use the api to make the user an owner in the org (post request to https://influxdb.example.com/api/v2/orgs/{orgid}/owners)

__Expected behavior:__
User gets converted from a member to being an owner

__Actual behavior:__
```
{
  "code": "internal error",
  "message": "Unexpected error when assigning user to a resource: mapping for user 064fc7110879b000 already exists"
}
```

__Environment info:__

`Linux 4.14.186-146.268.amzn2.x86_64 x86_64`
`InfluxDB 2.0.0-beta.16 (git: 50964d732c) build_date: 2020-08-07T20:18:07Z`

cc @gianu

**Comment by russorat** [comment] 2021-05-20 23:28
i'm going to close this for now since it was opened against a pre-release version of influxdb. if you are still facing this problem, please open a new issue with the details.

**Closed by russorat** 2021-05-20 23:28 UTC
Labels: area/api, kind/bug

**Comment by aguegu** [comment] 2022-05-20 05:10
For who anyone run to this issue. The cause is that the user could not be member and owner at the same time. So to be an org owner, it has to be removed as a member.
