### ISSUE TITLE
docker pull quay.io not working

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#20416] opened 2020-12-24 00:25 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

0. On a machine running arm64 ubuntu 20.10 64 bit:
1. Go to our downloads page at https://portal.influxdata.com/downloads/
2. Run the command `docker pull quay.io/influxdb/influxdb:v2.0.3`
3. Get error message that image platform (linux/amd64) doesn't match host platform (linux/arm64/v8). See below:

![image](https://user-images.githubusercontent.com/20701/103045906-3173ed00-453b-11eb-8838-1e2433ae972f.png)

You can see more in this Twitter thread: 

https://twitter.com/jgaltieri/status/1340379803220774912

... feel free to reach out to the user directly.

__Expected behavior:__
Successful installation of InfluxDB 2.0.3

__Actual behavior:__
Error message above

__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by danxmoran** [comment] 2020-12-24 00:36
This is on our roadmap for 2.0.4.

**Comment by galtaforce** [comment] 2020-12-24 19:33
As requested by @alsargent:

`ubuntu@pi4nvr:~$ uname -srm
Linux 5.8.0-1010-raspi aarch64`

**Comment by danxmoran** [comment] 2021-01-05 22:55
Duplicate of #17840

**Comment by danxmoran** [comment] 2021-01-11 18:53
@galtaforce I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling quay.io/influxdb/influxdb:nightly on your arm64 machines and let me know how it goes?

**Comment by galtaforce** [comment] 2021-01-11 23:00
> @galtaforce I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machine and let me know how it goes?

It works!

**Comment by danxmoran** [comment] 2021-02-08 18:14
`quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`

**Closed by danxmoran** 2021-02-08 18:14 UTC
Labels: arch/arm, area/2.x, area/docker, area/packaging
