### ISSUE TITLE
Operations on different resultsets using similar-nested query

### ISSUE THREAD

**Issue by dstreppa** [influxdata/influxdb#6905] opened 2016-06-23 15:15 UTC
### Feature Request

__Proposal:__ [Description of the feature]
It should be nice to perform mathematical operations (+,-, ...) on results of different queries.

Example queries:
query_E = SELECT sum(value) AS E FROM trevano_CPT_roof WHERE item='Pyranometer' AND signal='IrrEst' and time>='2016-05-27T00:00:00Z' and time<='2016-05-27T23:59:59Z'
name: trevano_CPT_roof

query_H = SELECT sum(value) AS H FROM trevano_CPT_techroom WHERE item='Inverter1' AND signal='kW_tot' and time>='2016-05-27T00:00:00Z' and time<='2016-05-27T23:59:59Z'
name: trevano_CPT_techroom

__Current behavior:__ [What you would like to happen]

query_E
----------------------
time			E
1464307200000000000	2.749669275633156e+07

query_H
--------------------------
time			H
1464307200000000000	242451.45200008276

__Desired behavior:__  [Why is this important (helps with prioritizing requests)]

SELECT E/H AS ratio FROM query_E, query_H

--------------------------
time			H
1464307200000000000	242451.45200008276/2.749669275633156e+07

__Use case:__ 
Sometimes I need to perform simple calculations between results directly on Grafana. Typically this happens when I have to calculate and show ratios as in the example above.

**Comment by srikara** [comment] 2016-06-24 17:05
+1

**Comment by jsternberg** [comment] 2016-09-09 20:42
Duplicate of #3552.

**Closed by jsternberg** 2016-09-09 20:42 UTC
