### ISSUE TITLE
New version of InfluxDB needs curl, but it isn't listed in dependencies in repo

### ISSUE THREAD

**Issue by Aneadiel** [influxdata/influxdb#22321] opened 2021-08-27 13:33 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install InfluxDB from official repo on debian
2. Update InfluxDB via apt-get
3. restart InfluxDB service

__Expected behavior:__
InfluxDB starts

__Actual behavior:__
Influx DB start fails because curl is not present in path.
Package is missing hard dependency curl.

__Environment info:__
Linux 4.19.0-10-amd64 x86_64
InfluxDB v1.8.9 (git: 1.8 d9b56321d579)

__Config:__
Default conf

**Comment by wbaker85** [comment] 2021-09-03 17:59
Duplicate of https://github.com/influxdata/influxdb/issues/22225, which was closed by https://github.com/influxdata/influxdb/pull/22253

**Closed by wbaker85** 2021-09-03 17:59 UTC
