### ISSUE TITLE
[feature request] continuous query to back up all my daily data into lower precision weekly data

### ISSUE THREAD

**Issue by akruman** [influxdata/influxdb#4708] opened 2015-11-09 09:23 UTC
It could be very useful for continuous queries; so i could put one query to back all my high precision 1 day retention data, into lower precision 1 week retention data.

something like:
```
CREATE CONTINUOUS QUERY rp1w_query ON mydb BEGIN
SELECT max(*) INTO "rp1w1".:MEASUREMENT FROM /.&#42;/ GROUP BY time(1m) 
END
```

**Comment by erdii** [comment] 2015-11-09 09:30
+1!

**Comment by beckettsean** [comment] 2015-11-09 19:29
This is really a request to support wildcard field key matching in the functions, so that each field does not have to be explicitly declared.

**Comment by ddaka** [comment] 2016-01-20 12:37
+1

**Comment by zstyblik** [comment] 2016-01-20 13:33
@akruman it was possible to do this with eg. the data from Telegraf 0.2.4, resp. the way the data was structured. It's not possible to do it with Telegraf 0.10.0, because all the fields are in the same table now.

> CREATE CONTINUOUS QUERY cq_1m_avg_tdb2 ON testdb2 BEGIN SELECT MEAN(value) AS "value", MAX(value) AS "max", PERCENTILE(value, 95) as p95 INTO testdb2."1m".:MEASUREMENT FROM testdb2."1s"./.*/ WHERE time > now() - 10m GROUP BY time(1m), * END

That's one of the CQs we used to have.

btw it'd would be great to stop with unproductive `+1` thing.

**Comment by beckettsean** [comment] 2016-03-05 00:42
This is doable now with a user defined function in Kapacitor, although it might not be very easy.

Effectively a dupe of https://github.com/influxdata/influxdb/issues/5750, which is newer, but more concise.

**Closed by beckettsean** 2016-03-05 00:42 UTC
Labels: category/continuous queries, category/feature request
