### ISSUE TITLE
dropping a database and recreating it immediately yields strange behaviour

### ISSUE THREAD

**Issue by erdii** [influxdata/influxdb#4636] opened 2015-11-02 13:00 UTC
Hello fellas! I'm on OS X 10.11.1 and InfluxDB 0.9.4.1

While developing i often re-create my Test-DB via InfluxCLI and run client tests against my Influx server instance so my influxCLI looks like this:

```
> drop database rsmq_monitor
> create database rsmq_monitor
> drop database rsmq_monitor
> create database rsmq_monitor
...
```

after doing so Influx does really strange things:
- node-influx (a influx javascript client) returns with this error when trying to drop a measurement that was inserted after recreating the database: [Error: open /usr/local/var/influxdb/wal/rsmq_monitor/default/22/01.000007.wal: no such file or directory]
- SHOW MEASUREMENTS lists measurements that have been INSERTed after recreating the DB but SELECT \* FROM {measurement} just yields an empty result

**Comment by beckettsean** [comment] 2015-11-02 17:37
Probably a duplicate of https://github.com/influxdb/influxdb/issues/3551

**Comment by e-dard** [comment] 2016-11-30 16:33
Closing as no longer relevant to current InfluxDB version.

**Closed by e-dard** 2016-11-30 16:33 UTC
