### ISSUE TITLE
select not return any data when time < 8h

### ISSUE THREAD

**Issue by ydp** [influxdata/influxdb#7122] opened 2016-08-08 08:26 UTC
When I select data from influxdb using time range less than 8h, there is no data return, when is is greater than 8h, it return the data, please see the below statements and results:

```
SELECT count("millsec") FROM "resin-teacher-access" WHERE time > now() - 9h;
time				count
2016-08-07T23:17:05.449541909Z	63998

SELECT count("millsec") FROM "resin-teacher-access" WHERE time > now() - 9h and time < now() - 8h;
time				count
2016-08-07T23:17:19.810658049Z	495

SELECT count("millsec") FROM "resin-teacher-access" WHERE time > now() - 8h and time < now() - 7h;
```

the first sql return 63998 points; second return 495 points, but the last one return none.

I guess it has something to do with the timezone, but do not understand why

**Comment by jsternberg** [comment] 2016-08-08 14:07
Have you checked if there are any points between 8h and 7h? You can try this query to see if there are any points.

```
SELECT "millsec" FROM "resin-teacher-access" WHERE time > now() - 8h and time < now() - 7h LIMIT 1;
```

Your first query says "everything within the last 9 hours. Your second query says "everything between 9h ago and 8h ago". Your third query says "everything between 8h ago and 7h ago". The count from the first query could be from points in the 7h to now range and there could be no points in the 8h to 7h range.

**Comment by ydp** [comment] 2016-08-09 02:58
sorry, I found that IT is caused by retention policy，

**Comment by jsternberg** [comment] 2016-08-09 03:00
Ok. I'm going to close this then. If you have any more questions for usage, please send a message to the [mailing list](https://groups.google.com/forum/#!forum/influxdb) and someone will help you there.

**Comment by ydp** [comment] 2016-08-09 03:12
@jsternberg  It has data points between 8h and 7h; after several hour, I found that more data loss, when time > now() - 12h, no points return; but when I change the retention policy from **duration=3d & shard duration=3d** to **duration=3d & shard duration=1d**; I got some data back, at least **the latest insert data can be selected**,  BUT the data before I modify retention policy still cannot be selected, unless I set a very large time range.

I think there may be some issue here, but I am not sure what cause it is

AND thanks for your reply.  Just let you know, in my wrong retention policy case, below query would not return points if x < 8, so from query view, there is no points, but absolutely I can say there is points in db, also I checked the WAL log size, it grows with time.

`SELECT count("millsec") FROM "resin-teacher-access" WHERE time > now() - **x**h`

**Comment by jsternberg** [comment] 2016-08-09 03:14
I'm going to reopen to investigate before I close this since there's now some new information. Thanks!

**Comment by ydp** [comment] 2016-08-09 03:16
Ok, I will send questions there next time.
Now that my latest data is back, I would not worry this for now, Thanks again for your reply. @jsternberg

**Comment by jsternberg** [comment] 2016-08-09 04:29
@ydp did you ever try checking each hour interval to see which intervals didn't have data?

**Comment by jsternberg** [comment] 2016-08-11 22:00
We're going to close this because we can't reproduce it ourselves. If you run into this again, please comment here again so we can figure out the underlying cause. Thanks!

**Closed by jsternberg** 2016-08-11 22:00 UTC
