### ISSUE TITLE
[0.9.3] after altering retention policy data appears to be going in, but not query-able

### ISSUE THREAD

**Issue by esecules** [influxdata/influxdb#4290] opened 2015-10-01 17:57 UTC
Since I discovered that backups are broken in this release I wanted to extend my retention policies. After extending them from 720h to INF I couldn't get any new data when I query my data with "WHERE time > now - 10m". Only the data from before I updated the retention policy shows up. (Though in the logs all writes have a 204 status code) I tried altering the retention policy to  365d, but still no luck. I can query the data without the time limiting clause and get everything from the beginning of time until now but that is not reasonable.

**Comment by esecules** [comment] 2015-10-01 18:06
I moved it back to 720h and "WHERE time ..." queries are working again. but im still wondering whether the data that went in while the retention time was long is recoverable, and what the limit is on how long a retention policy can be and whether it can be changed on the fly?

**Comment by beckettsean** [comment] 2015-10-01 22:24
@esecules can you paste in the output from `SHOW RETENTION POLICIES ON <db>`?

Even better, can you paste in the `ALTER RETENTION POLICY` queries you ran?

**Comment by beckettsean** [comment] 2015-10-01 22:26
> and what the limit is on how long a retention policy can be 

Retention policies can be any time range from 1 hour to infinite.

> and whether it can be changed on the fly

It should work, although I have not verified this recently.

**Comment by esecules** [comment] 2015-10-01 22:39
Alter:
```
alter retention policy events on my_db duration INF
alter retention policy events on my_db duration 365d
```

show: (I only have the output from when the policy was for 365d in my terminal history)
```
> show retention policies on my_db
name			duration	replicaN	default
default			0		    1		    false
events		8760h0m0s	    1		    true
```
During the time the retention policy was 365d I interseted some points into a test measurement and then ran these queries
```
root@influx:/# curl -i -XPOST 'http://localhost:8086/write?db=my_db' --data-binary 'test,serial=test points=1'
HTTP/1.1 204 No Content
Request-Id: 73a1d624-6863-11e5-b976-000000000000
X-Influxdb-Version: 0.9.3
Date: Thu, 01 Oct 2015 17:40:05 GMT



> SELECT points FROM "test" where time > now() - 1h
> SELECT points FROM "test"
name: test
--------------------------
time				points
2015-10-01T17:40:05.570577745Z	1
2015-10-01T17:40:20.654936237Z	1
2015-10-01T17:42:50.447394364Z	1

```

**Comment by otoolep** [comment] 2015-10-02 03:17
Please show us the output of `SHOW SHARDS`. You should be aware that shards created before you modify a retention policy will not be changed. So it is possible you still have shards whose end-time is much longer than you expect.

**Comment by esecules** [comment] 2015-10-02 15:10
@otoolep do o have to get into that bad state first?

**Comment by otoolep** [comment] 2015-10-02 15:10
What do you mean by bad state?

**Comment by esecules** [comment] 2015-10-02 16:01
```
> SHOW SHARDS
ERR: error parsing query: found SHARDS, expected CONTINUOUS, DATABASES, FIELD, GRANTS, MEASUREMENTS, RETENTION, SERIES, SERVERS, TAG, USERS at line 1, char 6

```

**Comment by otoolep** [comment] 2015-10-02 16:08
OK, you need to upgrade to 0.9.4.1 to get the latest diagnostic code. It will be much easier to help you then.

**Comment by otoolep** [comment] 2015-10-02 16:08
https://influxdb.com/download/index.html

**Comment by ZhukovAlexey** [comment] 2016-03-26 17:06
Hmm, have the same thing with one of the database on 0.11 version.

**Comment by MikeSchroll** [comment] 2016-07-30 04:53
Sounds similar to https://github.com/influxdata/influxdb/issues/5878

**Comment by beckettsean** [comment] 2016-09-27 21:43
dupe of #5878

**Closed by beckettsean** 2016-09-27 21:43 UTC
