### ISSUE TITLE
Influxdb 0.9.6 hangs after starting hinted handoff service and never starts others

### ISSUE THREAD

**Issue by shredder12** [influxdata/influxdb#5905] opened 2016-03-04 01:26 UTC
OS - Ubuntu 14.04.3, 64-bit
Influxdb - 0.9.6
Package - Pre-built

I recently started having these strange issues where HTTP service won't be started by Influxdb. I've spend a lot of time trying to debug this but no luck. It comes up on some restarts and not on others. After a while, it stopped starting HTTP service completely.

Logs

```
[metastore] 2016/03/03 17:10:15 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/03/03 17:10:15 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[influxdb1.stg:8088]
[metastore] 2016/03/03 17:10:15 Node at influxdb1.stg:8088 [Follower]
[metastore] 2016/03/03 17:10:16 Node at influxdb1.stg [Leader]. peers=[influxdb1.stg:8088]
[metastore] 2016/03/03 17:10:16 spun up monitoring for 1
[store] 2016/03/03 17:10:16 Using data dir: /var/lib/influxdb/data
[metastore] 2016/03/03 17:10:16 Updated node id=1 hostname=influxdb1.stg:8088
[metastore] 2016/03/03 17:10:16 node '2' removed
[metastore] 2016/03/03 17:10:16 removing peer for node id 2, influxdb3.stg:8088
[wal] 2016/03/03 17:10:37 WAL starting with 25600 ready series size, 0.60 compaction threshold, and 20971520 partition size threshold
[wal] 2016/03/03 17:10:38 WAL writing to /var/lib/influxdb/wal/_internal/monitor/1
...
... more
[wal] 2016/03/03 17:10:39 WAL writing to /var/lib/influxdb/wal/_internal/monitor/285
[handoff] 2016/03/03 17:10:39 Starting hinted handoff service
[monitor] 2016/03/03 17:10:39 'hh' registered for diagnostics monitoring
[handoff] 2016/03/03 17:10:39 Using data dir: /var/lib/influxdb/hh
```

This started happening after my attempt to create a cluster. It failed, but the primary node(influxdb1.stg) kept running and accepting data(for days). I updated peers.json to reflect only itself, but I still see it disconnecting node 2(influxdb3.stg) in the logs. I don't see any attempt to contact other non-existent raft nodes(checked using tcpdump).

any thoughts why this might be happening or how can I debug this further?

**Comment by jonseymour** [comment] 2016-03-04 03:35
One thing you might try is grabbing a stack trace from the process when it is in the "hung" state, e.g.

`kill -QUIT  {influxd-process-id}`

this will yield a stack trace that might indicate where a goroutine is failing to make progress.

Best to leave the process for 5 minutes or so, so any hung goroutines will be easily identified.

If you can post the resulting stacktrace as a gist I can have a look at it for you.

**Comment by shredder12** [comment] 2016-03-04 04:12
@jonseymour  Thanks. Here you go
https://gist.github.com/shredder12/f3ff6752efdb38d2ded6

**Comment by jonseymour** [comment] 2016-03-04 05:36
@shredder12 this arose after a failed attempt to enable clustering?

Are you now trying to run in a standalone setup?

Could you paste links to gists containing a copy of your configuration file and the meta/node.json file?

**Comment by jonseymour** [comment] 2016-03-04 06:17
This looks similar to the issue that occurred in #5161 although there are some differences.

You might want to consider updating to v0.10.2 as that area of the code has changed considerably since v0.9.6.1 so there won't be many people trying to solve this kind of issue.

**Comment by jonseymour** [comment] 2016-03-04 07:26
It does appear these two goroutines are deadlocked.

```
goroutine 10 [select, 165 minutes]:
github.com/hashicorp/raft.(*Raft).processLog(0xc2080621c0, 0xc2081fd980, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:1140 +0x200
github.com/hashicorp/raft.(*Raft).processLogs(0xc2080621c0, 0x9f9, 0xc2081180a0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:1123 +0x444
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080621c0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:872 +0x3d2
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080621c0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:826 +0x876
github.com/hashicorp/raft.(*Raft).run(0xc2080621c0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:602 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:252 +0x27
github.com/hashicorp/raft.func·011()
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select, 165 minutes]:
github.com/hashicorp/raft.(*Raft).RemovePeer(0xc2080621c0, 0xc208160cf0, 0x27, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:380 +0x29d
github.com/influxdb/influxdb/meta.(*localRaft).removePeer(0xc20805f260, 0xc208160cf0, 0x27, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/state.go:325 +0x149
github.com/influxdb/influxdb/meta.(*storeFSM).applyRemovePeerCommand(0xc20806a3c0, 0xc208160c00, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/store.go:1888 +0x325
github.com/influxdb/influxdb/meta.func·031(0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/store.go:1821 +0x682
github.com/influxdb/influxdb/meta.(*storeFSM).Apply(0xc20806a3c0, 0xc20811cc80, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/meta/store.go:1867 +0x2f4
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080621c0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:564 +0xdfc
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/raft.go:253 +0x27
github.com/hashicorp/raft.func·011()
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.QrWAFdTR6B/src/github.com/hashicorp/raft/state.go:153 +0xe3
```

I need to re-read the raft spec to see if this can happen, but I think that issue was likely caused by an attempt to remove a node from a cluster which didn't complete succeed and then, during restarts, a code path which would have executed without locking if it had executed to completion on first attempt, is not causing a deadlock because it is executing on a different node that the node it was originally executed on.

If you could describe in the detail:

- what the original topology was
- what you tried to change it to
- what happened when you tried to change it to this topology
- what it is now
- what you would like it to be

it might be possible to recommend next steps.

**Comment by jonseymour** [comment] 2016-03-04 09:09
You wrote:

> but I still see it disconnecting node 2(influxdb3.stg) in the logs. I don't see any attempt to contact other non-existent raft nodes(checked using tcpdump).

Can you post a gist of the logs which show that - as much of the logs as you can please.

**Comment by jonseymour** [comment] 2016-03-04 10:40
I dug into a bit further and reviewed the changes between v0.9.6.1  and v0.10.0. 

This problem has been fixed in 0.10.0 because Influx no longer attempts to send an application command to the raft cluster in order to remove a raft peer, rather a local raft.RemovePeer operation is executed and influx relies on Raft to propagate this to operation to its peers. This avoids the circumstances that led to this deadlock.

So, my recommendation at this point would be provide the information requested above, with a view to getting your  0.9.6.1 server started again and once you are happy it is recovered, migrate it to v0.10.2.

**Comment by shredder12** [comment] 2016-03-04 23:22
Thank you for the detailed analysis @jonseymour 

>     what the original topology was
Just a single server.
>     what you tried to change the topology to
A 3 node cluster
>     what happened when you tried to change it to this topology
I believe it worked. However, since I was only going for solution to have data replication I realized subscription feature might be a better alternative. This is when I tore down the cluster. The primary node continued to work fine for days after this event. The two new nodes were deactivated. 
>     what you tried in order to recover
There was nothing to recover. All the data was in the primary(initial) node and it was functional.
>     what the topology is now
Back to single server in the state explained above.
>     what you would like the topology to be
Data available on multiple nodes so that I have failover.
>     how important it is for you to preserve all the data in the cluster
This is still a test environment. But I am trying to preserve data to able to solve any similar issue in production, if any.

You are right regarding the deadlock though. I was able to see connection attempts to influxdb3.stg during startup of influxdb1.stg, right when it says(in logs) that the other node is being removed from the cluster. I checked it using tcpdump. I missed them earlier because I was checking for these during hung state.

I tried provisioning a fake influxdb3.stg and let it successfully send a removal message, but that didn't help.

Is there anyway I can update raft.db and remove any reference to influxdb3.stg? And do you think that would work?

**Comment by jonseymour** [comment] 2016-03-05 22:49
Can you paste a listing of your meta directory tree?

So: `find meta -ls`

And also the contents of your meta/node.json  file?

I am going to see if I can reproduce this deadlock locally and if so I will create a temporary fix that works around the issue. If anyone else has seen this issue and knows a procedure for getting past it, let us know!

**Comment by jonseymour** [comment] 2016-03-05 22:53
Also, if you can send me (jon@wildducktheories.com) a .tgz  containing the contents of your meta directory it might help me test a workaround.

**Comment by jonseymour** [comment] 2016-03-06 01:07
I haven't been able to reproduce the deadlock on v0.9.6.1.

Do you happen to remember exactly what steps you took to remove the extra nodes from your cluster?

I am interested to know the relative order of any of the following actions:

- any stop or start of a server
- any drop server commands
- any kill signal sent to a server
- any edits to any configuration files

Did any process hang during this procedure? Did you have to restart any server during this procedure? Was there any case where a command was issued and then a server was killed almost immediately afterwards? 

The purpose of these questions is to try and create a reproducible scenario for creating the original deadlock. It doesn't matter if you can't remember exactly. If you have any influxd log files that cover the time period during which you removed the servers, that would help immensely.

**Comment by e-dard** [comment] 2016-03-08 11:25
Hi @shredder12. Would it be possible for you to update to `0.10.2`, which is out latest release?

**Comment by shredder12** [comment] 2016-03-09 00:13
@jonseymour @e-dard I upgraded the server to 0.10.2 and you were right, the code base is different. The server didn't hang this time and services were up. I see the following cluster configuration.

```
> SHOW SERVERS
name: data_nodes
----------------
id      http_addr                               tcp_addr
1       influxdb1.stg.:8088 influxdb1.stg.:8088
3       influxdb3.stg.:8088 influxdb3.stg.:8088
4       influxdb2.stg.:8088 influxdb2.stg.:8088


name: meta_nodes
----------------
id      http_addr                               tcp_addr
1       influxdb1.stg.:8088 influxdb1.stg.:8088
2       influxdb3.stg.:8088 influxdb3.stg.:8088
```
I want to go back to a single node setup, so I tried dropping the servers. But I am not able to do so using cli.

```
> DROP SERVER 3
ERR: error parsing query: found SERVER, expected SERIES, CONTINUOUS, MEASUREMENT, SERVER, SUBSCRIPTION at line 1, char 6
```

There is nothing mentioned in the documentation either. Any suggestions?

**Comment by jonseymour** [comment] 2016-03-09 00:33
I think the syntax may now actually be DROP DATA SERVER 3. If this this works, the message probably needs to be fixed.

**Comment by shredder12** [comment] 2016-03-09 00:52
@jonseymour indeed. that worked. However, doing the same for meta doesn't work.
```
> drop meta server 2;
ERR: peer is unknown
```

Thoughts?

**Comment by jonseymour** [comment] 2016-03-09 01:12
That message is generated by the underlying raft layer which seems like it might be out of sync with the influx topology. Does SHOW SERVERS still show server 2?

**Comment by shredder12** [comment] 2016-03-09 01:21
@jonseymour yes, it still shows meta server '2'. Surprisingly, there were references to data nodes 3,4 in the logs, after dropping them.
```
[handoff] 2016/03/08 16:54:35 failed to determine if node 3 is active: node not found
```
Restarting after this resulted in an error during startup.

```
[metaclient] 2016/03/08 16:16:01 failure getting snapshot from influxdb1.stg:8088: Get http://influxdb1.stg:8088?index=0: read tcp 10.0.2.28:8088: connection reset by peer
```

This is obviously wrong since the meta HTTP service should be 8091 in new release. So, I removed node.json and restarted. It did start but then everything came back in show servers(including deleted data nodes).

**Comment by jonseymour** [comment] 2016-03-09 01:31
My familiarity with the clustering code is fairly limited. I am happy to help look at it, as a learning experience if nothing else, but I am going to need a .tgz containing the contents of your meta directory so that I can play with it.

**Comment by e-dard** [comment] 2016-11-30 15:29
No longer relevant to current InfluxDB version

**Closed by e-dard** 2016-11-30 15:29 UTC
