### ISSUE TITLE
Open segment limit reached error when writing data to InfluxDB 3

### ISSUE THREAD

**Issue by anshul-raman** [influxdata/influxdb#25141] opened 2024-07-11 04:55 UTC
## Describe Development Experience Issue:

Hi, i'm doing some testing on influxDB 3, but i'm encountering the following error when using the write_lp API

```
failed to write data: transactions,senderID="4cd3377d-2766-457e-88a3-7c345c544db0",receiverID="357d4b9d-d80f-48e1-938b-6639a8734af4",paymentType="CASH",currencyCode="USD" paymentAmount=1056.28,transactionID="8065cac3-2422-4a6d-a7a0-e7baf46fac63" 1720675888684992846: ApiError { code: 500, message: "write buffer error: error from buffer segment: open segment limit reached: 100" }
```

What could be the possible cause, is it because of my test data or something else ? What is open segment limit ?

**Comment by hiltontj** [comment] 2024-07-11 14:10
@anshul-raman - because the project is in an early development stage, my general advice would be to wait until an alpha or some form of release is announced before testing this as a viable time series database for your needs. The underlying architecture is still evolving and the root cause of errors like this may be addressed in the time leading up to such a release.

However, I can elaborate on your questions a bit: **currently**, when writes come in, they are written to a segment based on the timestamp of the line written. By default, segments are 1-hour in length, so if you write timestamps that are spread across many 1-hour windows, it will open a segment for each 1-hour window of time. There is a limit of 100 open segments at a time, as per the error, so if you are writing timestamps that are spread across more than 100 1-hour windows before the server has a chance to persist data and close the segments, then you will encounter this error.

You can change the segment duration on server start with the `--segment-duration` CLI argument, the same logic applies, but with whatever segment duration you provide. From `influxdb3 serve --help` valid segment durations are:

> Valid values: 1m, 5m, 10m, 15m, 30m, 1h, 2h, 4h

I hope this is helpful, but I will reiterate: all of this may change in the coming months as the architecture evolves.

**Closed** 2024-07-12 09:07 UTC
Labels: v3
