### ISSUE TITLE
InfluxDB not on DockerHub

### ISSUE THREAD

**Issue by alsargent** [influxdata/influxdb#20450] opened 2021-01-05 22:09 UTC
Not sure if this is a feature request or a bug, but given that a [user wasted two hours](https://twitter.com/tfgallacher/status/1345409561881149441) trying to debug an issue related to our not being on DockerHub, I'll file it as the latter.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Go to https://hub.docker.com/_/influxdb
2. Look for InfluxDB 2.0
3. View text implying that 2.0 isn't yet GA: "In the future, the latest tag for this image will point to the latest released implementation of influxdb 2.0. This will happen when the first general available release for 2.0 exists."

__Expected behavior:__
InfluxDB 2.0 should be available on DockerHub

__Actual behavior:__
Users aren't seeing InfluxDB 2.0 on DockerHub.

Yes, we're on Quay.io, but some users are expecting us to be on DockerHub as well. 

![image](https://user-images.githubusercontent.com/20701/103705354-be696e00-4f5f-11eb-9e4d-41e20bda6044.png)

**Comment by timhallinflux** [comment] 2021-01-05 22:45
Not a bug. This is something we call out in the docs. New install is available only in Quay.io. When we address the upgrade path for existing Docker users, we'll publish to Docker Hub.

**Comment by danxmoran** [comment] 2021-01-05 22:53
Duplicate of #16649

**Closed** 2021-01-06 01:13 UTC
Labels: area/2.x, area/docker, area/packaging
