### ISSUE TITLE
non-admin users can't run USE in the CLI

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#6397] opened 2016-04-15 20:05 UTC
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB 0.12.1, Ubuntu 14.04, not a fresh install (upgraded from 0.10 over time)

__Steps to reproduce:__

1. enable authentication in the config file
1. create an admin user
1. create a non-admin user with `ALL` privileges to an existing database

__Expected behavior:__ [What you expected to happen]

non-admin user with `ALL` privs can `USE <database>`

__Actual behavior:__ [What actually happened]

non-admin user gets an auth error

Connecting directly to the database works:

```
# influx -username 'mydb' -password 'mmydb' -database 'mydb'
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.12.1
InfluxDB shell 0.12.1
> show measurements
name: measurements
------------------
name
ambiguous
cpu
string1
strings
```

However, the `mydb` user cannot issue a USE command, because the CLI has a behind the scenes `SHOW DATABASES` command that fails:

```
# influx -username 'mydb' -password 'mmydb'
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.12.1
InfluxDB shell 0.12.1
> use mydb
ERR: error authorizing query: mydb not authorized to execute statement 'SHOW DATABASES', requires admin privilege
```

**Comment by jsternberg** [comment] 2016-04-18 14:02
@beckettsean should we allow non-admins to use `SHOW DATABASES`? What should the required privileges be?

**Comment by beckettsean** [comment] 2016-04-19 17:23
If non-admins can run `SHOW DATABASES` it would be important that the command only return a list of the databases to which they have at least one read or write privilege. If there are 10 databases on the instance and a user only has read access to one, they should not be able to retrieve the entire list of databases.

Alternately we could remove the `SHOW DATABASES` command from the CLI on `USE`. I think we're only doing that so we can give a meaningful "no database found" error when someone runs `USE` against a non-existent database. 

I think it warrants a more involved discussion. @jwilder @pauldix @gunnaraasen your thoughts?

**Comment by gunnaraasen** [comment] 2016-04-19 18:34
I agree we should allow non-admin users to see only databases where they have either read or write privileges. Looks like this is a duplicate of https://github.com/influxdata/influxdb/issues/4785.

**Comment by katirena** [comment] 2016-04-29 08:12
This would be useful for the Admin UI also. As right you can't query data with non-admin user, as it can't get the list of databases.

**Comment by jsternberg** [comment] 2016-07-14 16:44
Closing this in favor of #4785 since they are duplicates. A hack has already been included to get around this right now, so now we just need to fix the underlying problem.

**Closed by jsternberg** 2016-07-14 16:44 UTC
