### ISSUE TITLE
Can't add labels to things

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#11734] opened 2019-02-06 22:51 UTC
![kapture 2019-02-06 at 14 50 39](https://user-images.githubusercontent.com/10937678/52379195-9f35cf00-2a1e-11e9-8768-52698ce276d3.gif)

**Comment by alexpaxton** [comment] 2019-02-09 01:18
This seems intertwined with #11624 and #11774

**Comment by OfTheDelmer** [comment] 2019-02-12 16:10
Could not reproduce #11774 but it may have been resolved by the labels api fixes. This issue seems like a dupe of #11624

**Closed by OfTheDelmer** 2019-02-12 16:10 UTC
Labels: epic/labelsui
