### ISSUE TITLE
Use of parameter "chunk_size" with "GROUP BY" causes invalid JSON response

### ISSUE THREAD

**Issue by mhodson-qxbranch** [influxdata/influxdb#7000] opened 2016-07-11 21:32 UTC
### Bug report

__System info:__

Ubuntu 14.04.4 LTS, 64-bit (trusty)
InfluxDB 0.13.0 (installed from package)

__Steps to reproduce:__

The following script reproduces the issue.

https://gist.github.com/mhodson-qxbranch/2516ed2308c28d2c6d8ff543bf63d979

__Expected behavior:__

Expect these queries to return a single JSON response with a single "results" section.

__Actual behavior:__

The current response is multi-line, one per series, with each line being an independent valid JSON response with a unique set of tags.

__Additional info:__

The effect of this bug when for example using the ruby bindings is that a JSON parse error is raised.

As a work-around, multi-line response parsing and merging of the resulting hash (or equivalent) can be performed on the client. However it is not known if this work-around has any edge cases (it depends whether any top-level item other than "results" is possible in the hash).

This should be fixed on the server-side.

**Comment by phemmer** [comment] 2016-07-12 03:01
I suspect this isn't a bug, but intentional. The format you describe is known as JSON streaming: https://en.wikipedia.org/wiki/JSON_Streaming
It's useful to prevent from having to load the entire response payload into memory, which can be extremely expensive with tens of thousands of records.

Though I could find no documentation stating that this is the expected behavior, so at the very least that should at least be done.

**Comment by mhodson-qxbranch** [comment] 2016-07-12 03:18
I had never heard of that. Good pickup. The issue for myself as an end-user was via the official Ruby bindings, which throw a JSON parse error when this occurred. I've stood up a fork to address it which seems to work (https://github.com/mhodson-qxbranch/influxdb-ruby/tree/support-chunk-size) but will have to take it through the process of review. There's no PR yet.

If your experienced devs could consider where this might occur, and what the proper action is, we can compare notes and at least stand up a robust solution for the Ruby client?

**Comment by mhodson-qxbranch** [comment] 2016-07-12 03:19
The alternative of course within a single response is still to perform the merge on the server side. That would alleviate any client-side issues.

**Comment by jsternberg** [comment] 2016-07-14 02:44
If chunking is enabled, the response that's returned will be streaming JSON with each batch being a maximum size of the chunk size. If you have multiple series get returned, they get streamed as separate batches even if they haven't hit the chunk size.

I hope this PR helps clarify the behavior: influxdata/docs.influxdb.com#530. I'm going to close this since I don't think there's any action to take for the database itself. Please comment and I can reopen if there is something I'm missing. Thanks.

**Closed by jsternberg** 2016-07-14 02:44 UTC

**Comment by mhodson-qxbranch** [comment] 2016-07-20 02:19
No problem. I'm updating the PR for influxdb-ruby to support this feature.
