### ISSUE TITLE
Installing influx-cli without installing influxdb completely

### ISSUE THREAD

**Issue by Tabrizian** [influxdata/influxdb#7432] opened 2016-10-08 17:28 UTC
Is it possible to only install influxdb client and not installing the influxdb completely?

**Comment by jsternberg** [comment] 2016-10-12 16:05
Duplicate of #6657.

**Closed by jsternberg** 2016-10-12 16:05 UTC

**Comment by markddavidoff** [comment] 2020-06-26 01:44
> Duplicate of #[6657](https://github.com/influxdata/build-scripts/issues/7).
