### ISSUE TITLE
Checks fails with naming collision when renaming check and no error to user

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16257] opened 2019-12-17 23:12 UTC
![image](https://user-images.githubusercontent.com/17263167/71042001-67d48c00-20df-11ea-894c-5bfc34b4e6f2.png)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a check in the UI
2. create a 2nd check
3. rename check to same name of 1st check (if no naming collision observed already)
4. should see errors in network tab

__Expected behavior:__
Expected to be notified of naming collision.

__Actual behavior:__
Fails silent, no toast or anything.

NOTE: was also confused I couldn't name or put description when creating it 🤔

**Comment by ebb-tide** [comment] 2019-12-17 23:20
dupe of https://github.com/influxdata/influxdb/issues/16128

**Closed** 2019-12-27 02:05 UTC
Labels: kind/bug, team/monitoring
