### ISSUE TITLE
influxdb USES a lot of memory. How do I configure it

### ISSUE THREAD

**Issue by evildao** [influxdata/influxdb#17162] opened 2020-03-10 01:51 UTC
__Proposal:__
configure db use max memory

__Current behavior:__
influxdb USES a lot of memory

__Desired behavior:__
configure max memory

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
oom

**Comment by russorat** [comment] 2020-03-10 20:20
@evildao thank you for the issue. There are a lot of things that might cause InfluxDB to use a lot of memory. Make sure you read through: https://docs.influxdata.com/influxdb/v1.7/concepts/storage_engine/#storage-engine to understand the different scenarios. 

Also, check out these configuration options that might help:
https://docs.influxdata.com/influxdb/v1.7/administration/config/#index-version-inmem

If the issue is from large queries, we have options for that as well:
https://docs.influxdata.com/influxdb/v1.7/administration/config/#query-timeout-0s

**Comment by evildao** [comment] 2020-03-11 02:26
version 2.0-beta5
![搜狗截图20200311102320](https://user-images.githubusercontent.com/6054838/76376179-a302f600-6382-11ea-9f7a-b79f16978654.png)

**Comment by russorat** [comment] 2020-03-11 16:50
@evildao thanks! there are no config options to limit memory usage in 2.0 beta yet. 

Can you give some additional details about the system you are running this on and the amount of data you are writing to the instance?

**Comment by evildao** [comment] 2020-03-12 02:20
![image](https://user-images.githubusercontent.com/6054838/76480791-bda0a200-644a-11ea-83e8-dad91cf6842e.png)

docker run

![image](https://user-images.githubusercontent.com/6054838/76480907-02c4d400-644b-11ea-9a2f-7136ab05f638.png)
![image](https://user-images.githubusercontent.com/6054838/76480946-1b34ee80-644b-11ea-876e-e74d7e21f658.png)

**Comment by russorat** [comment] 2021-05-20 20:11
We now have more configuration options for managing memory. check them out here: https://docs.influxdata.com/influxdb/v2.0/reference/config-options/

Closing this for now since it's open against a beta.

**Closed by russorat** 2021-05-20 20:11 UTC

**Comment by Doc999tor** [comment] 2021-06-03 15:00
I don't see any difference with v2.0.5
What configuration option should I use for flushing the memory cache to the disk? 
After the upgrade to 2.0.5 I set `storage-cache-max-memory-size: 400mb, storage-cache-snapshot-memory-size: 25mb` - influx continues OOM crashing even I rise it `storage-cache-max-memory-size` to 800mb

**Comment by russorat** [comment] 2021-06-03 16:12
@Doc999tor thanks for the update. Could you open a new bug specifically about memory cache options not working in 2.0.5 with the details of your system so we can take a look?
