### ISSUE TITLE
Query with multiple time ranges return no data

### ISSUE THREAD

**Issue by ryantxu** [influxdata/influxdb#7451] opened 2016-10-11 23:07 UTC
This may be expected, but when I query with multiple time ranges, it gets no results.

### Bug report

__System info:__ 

| Branch	| Commit	 | Version  |
|---|---|---|
| master	| "37992377a55fbc138b2c01edd4deffed64b53989"	| "1.0.0" |

__Steps to reproduce:__

1. Index some data
2. Query for one time range:
   
    ```SELECT count(field) FROM trend WHERE (time > now() - 10m AND time < now() - 9m)```

This gives me 60 samples.

3. Query for another time range:

    ```SELECT count(field) FROM trend WHERE (time > now() - 5m AND time < now() - 4m)```

This also gives me 60 samples

3. Query for both time ranges

    ```SELECT count(field) FROM trend WHERE (time > now() - 10m AND time < now() - 9m) OR (time > now() - 5m AND time < now() - 4m)```

__Expected behavior:__ 

I would expect 120 samples -- since we selected over two ranges.  Or an error if selecting multiple ranges is not allowed

__Actual behavior:__ 

response is OK, but no results

**Comment by jwilder** [comment] 2016-10-11 23:21
This is a duplicate of #3290.

**Closed by jwilder** 2016-10-11 23:21 UTC
