### ISSUE TITLE
[0.12.0] Error parsing query when running multiple queries

### ISSUE THREAD

**Issue by bogdanveres** [influxdata/influxdb#6220] opened 2016-04-05 15:28 UTC
I added a new graph in Grafana (2.6.0) with two queries:

SELECT mean("CPU") FROM "DEVICE_2_LIVE" WHERE $timeFilter GROUP BY time($interval)
SELECT mean("MemoryUsage") FROM "DEVICE_2_LIVE" WHERE $timeFilter GROUP BY time($interval)

InfluxDB response:

{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1",
  "message": "error parsing query: found SELECT, expected ; at line 2, char 1"
}

If I change the query to:

SELECT mean("CPU") FROM "DEVICE_2_LIVE" WHERE $timeFilter GROUP BY time($interval);
SELECT mean("MemoryUsage") FROM "DEVICE_2_LIVE" WHERE $timeFilter GROUP BY time($interval)

Only the first value is retrieved from database.
Here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/3493668/14287483/7e524de4-fb5b-11e5-985e-6f9bf8c6dd1d.png)
![image](https://cloud.githubusercontent.com/assets/3493668/14287535/a95f5b62-fb5b-11e5-9e53-7d5d6cf686f0.png)

This issue appeared after I updated the InfluxDB to 0.12.0. If I use a single query the graph is displayed. I also tested with Grafana 3.0.0 beta 2 and it's also reproducible.

**Comment by wgrcunha** [comment] 2016-04-05 17:45
:+1:

**Comment by clrung** [comment] 2016-04-05 19:36
:+1:

**Comment by ljagiello** [comment] 2016-04-05 20:34
Looks like it's connected with that change: https://github.com/influxdata/influxdb/pull/6004

**Comment by sstarcher** [comment] 2016-04-05 21:06
So the break on influx's side was on purpose according to #6004

**Comment by andybrier** [comment] 2016-04-06 02:04
is there any bug fix for this?

**Comment by ljagiello** [comment] 2016-04-06 03:28
IMHO it's an issue on grafana side not on influxdb side.

**Comment by mnietz** [comment] 2016-04-06 14:02
:+1:

**Comment by jsternberg** [comment] 2016-04-06 18:57
Closing this since this comment lends me to believe that this is an issue on Grafana's side: https://github.com/influxdata/influxdb/issues/5728#issuecomment-206499641

If anybody has more information about this bug that differs from what is mentioned in that comment thread, please reopen with more information so we can try to reproduce the problem. Thanks.

**Closed by jsternberg** 2016-04-06 18:57 UTC

**Comment by emanzx** [comment] 2016-04-08 11:26
![image](https://cloud.githubusercontent.com/assets/2576990/14382351/ac378d6c-fdbf-11e5-9b89-6533391f9f8a.png)

it seem not only support grafana but also the admin console of influxdb

**Comment by jsternberg** [comment] 2016-04-08 17:28
@emanzx unfortunately I'm not able to reproduce that on my machine. When I use a semi-colon, I get two results. Can you run the same query using the `influx` binary and see if the result is different?

**Comment by emanzx** [comment] 2016-04-08 17:48
I try to run on the influx cli.. Seem like it produce two result. But the
admin web interface still not produce two result. I have compile the latest
source. Its still the same, by the way I manage to hack grafana to works by
patching some code and edit angular.js file based on what I found on
google.

On Saturday, April 9, 2016, Jonathan A. Sternberg <notifications@github.com>
wrote:

> @emanzx <https://github.com/emanzx> unfortunately I'm not able to
> reproduce that on my machine. When I use a semi-colon, I get two results.
> Can you run the same query using the influx binary and see if the result
> is different?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6220#issuecomment-207526835>
>


-- 
“Your time is limited, so don’t waste it living someone else’s life. Don’t
be trapped by dogma – which is living with the results of other people’s
thinking. Don’t let the noise of other’s opinions drown out your own inner
voice. And most important, have the courage to follow your heart and
intuition. They somehow already know what you truly want to become.
Everything else is secondary.” - Steve Jobs’ Stanford Commencement Address
<http://www.youtube.com/watch?v=UF8uR6Z6KLc>

Muhammad al-iman Bin Mohd Zain
Student of Horticultural Sciences
Faculty of Agriculture
Universiti Putra Malaysia
Serdang, Selangor.
013-2823637

**Comment by Dual-Boot** [comment] 2016-04-09 16:07
Hi,

 same issue since I updated influxdb too.
This is why I think the problem is link to influxdb and not grafana.
To have more than one graph on the same panel, I need to delete the 2 others queries and add in the first query 2 more "field" and select the name field.
   But after, I can not rename the name fiel with field measurement using "ALIAS BY"
My goal is to have CPU usage System, User, IO wait on the same panel and with correct table legend and not for example "cpu.mean", "cpu.mean_1", "cpu_mean_2"

  Regards,

**Comment by gseven** [comment] 2016-04-14 18:14
Same here.

**Comment by mnietz** [comment] 2016-04-14 18:15
It's fixed in Grafana3beta3, see here

https://github.com/grafana/grafana/issues/4533#issuecomment-208962918

**Comment by Dual-Boot** [comment] 2016-04-14 18:42
@mnietz I know that, but what about grafan 2.6 (debian package) ?
Thank you.

**Comment by IngaFeick** [comment] 2016-07-06 14:58
Heyho,
we too need this fixed for grafana 2.6. Any plans?
