### ISSUE TITLE
stuff separated by comma(s) inside parenthesis generate extra columns with empty title

### ISSUE THREAD

**Issue by lipoteFR** [influxdata/influxdb#9570] opened 2018-03-13 22:42 UTC
First trouble with 1.5.0 : https://github.com/influxdata/influxdb/issues/9562
To reproduce bug see below

**Comment by lipoteFR** [comment] 2018-03-14 08:28
`#!/bin/env python
from influxdb import InfluxDBClient
client = InfluxDBClient( host='<ip>', port=8086 )

client.drop_measurement('test_bug')
p = [{ "measurement" : "test_bug"
     , "time"        : "2018-03-14T09:00:00Z"
     , "tags"        : {"tag_key": "tag_value"}
     , "fields"      : { "value": 0.64} } ]

client.write_points(p)

result = client.query("SELECT * FROM test_bug")
print result
#exit(8)
p = [{ "measurement" : "test_bug"
     , "time"        : "2018-03-14T08:00:00Z"
     , "tags"        : {"tag_key": "tag_value **(toto, titi)**"}
     , "fields"      : { "value": 0.64} } ]

client.write_points(p)

result = client.query("SELECT * FROM test_bug")
print result

`
gives
ResultSet({'(u'test_bug', None)': 
[{u'tag_key': u'tag_value', u'value': 0.64, u'time': u'2018-03-14T09:00:00Z'}]})

ResultSet({'(u'test_bug', None)': 
[{**u'': None**, u'tag_key': u'tag_value (toto, titi)', u'value': 0.64, u'time': u'2018-03-14T08:00:00Z'}
,{**u'': None**, u'tag_key': u'tag_value', u'value': 0.64, u'time': u'2018-03-14T09:00:00Z'}]})

Because tag_value contains (toto,tutu) a new column appear 
it brakes every thing
Ma base est toute cassée (crote)

**Comment by e-dard** [comment] 2018-03-14 10:34
Thanks for these repro steps. I can now repro the issue. I'm going to close this issue as it's a duplicate of #9545. I'll update with status there.

**Closed by e-dard** 2018-03-14 10:34 UTC
