### ISSUE TITLE
2.1.1 - unable to copy token when creating API token

### ISSUE THREAD

**Issue by aaronmarcus** [influxdata/influxdb#23135] opened 2022-02-19 17:00 UTC
__Steps to reproduce:__
1. Install influxdb 2.1.1
2. quick start
3. create API token

__Expected behavior:__
After creating the token a modal box appears with the token in, to copy to clipboard

__Actual behavior:__
No modal appears, but the token is added to the token list
A message box saying "API token was created successfully" appears top right

__Environment info:__
* InfluxDB version: 2.1.1

**Comment by aaronmarcus** [comment] 2022-02-19 17:01
This error means I am unable to do almost anything from the CLI tool, as I cannot attach a token to a request

**Comment by sgramsch** [comment] 2022-03-25 22:39
Hi,
same here, Docker image influxdb:2.1-alpine

- click on "Generate API Token"
- select "All Access API Token"
- add a description
- click "Save"
- Token is not shown

![influxdb_token](https://user-images.githubusercontent.com/16152782/160210617-56dbdb36-b8d9-40e4-b95c-e348298ef0d5.gif)

There is a workaround:

- open the developer console (F12)
- select the network tab
- create a token
- you will find your token in the response:

![Tokens InfluxDB](https://user-images.githubusercontent.com/16152782/160211085-85ecf943-31df-4ca9-9fa3-f395170c8c36.png)

**Comment by KillingJacky** [comment] 2022-08-08 07:10
the issue is still there, v2.3.0

**Comment by JustANewGuy** [comment] 2022-08-13 08:47
Just got bit by this after finally deciding to upgrade from 1.8
Cant believe it still exists, thx @sgramsch for the work around

**Comment by MattBrauer** [comment] 2022-09-18 21:05
The existence of this bug is a truly ridiculous waste of time.

**Comment by sbachstein** [comment] 2023-02-15 19:51
This issue is still present in the most recent version (2.6.1).

**Comment by jeffreyssmith2nd** [comment] 2023-02-15 21:13
Closing this issue as resolved.

On versions prior to 2.5, after creating a token, the user can click on the token name to see the token and copy from there.

On versions 2.5+, the token will be show one time upon creation.

These are the expected behaviors.

**Closed by jeffreyssmith2nd** 2023-02-15 21:13 UTC
