### ISSUE TITLE
[ReOpen #8822] Lost all data after DELETE command

### ISSUE THREAD

**Issue by max3163** [influxdata/influxdb#9116] opened 2017-11-15 12:59 UTC
I've test the latest version of Influxb with the fix #8981 but I still have the issue.
See in attachment a new log file, the issue appear at '2017-11-13T16:16:22Z' when I start send 10 queries in a row to delete each time one point.

[log2.txt](https://github.com/influxdata/influxdb/files/1474752/log2.txt)

After that, one week of data is lost in all the database.
The issue appear in our backup server with no writer just some queries from grafana.

**Comment by jwilder** [comment] 2017-11-15 18:34
@max3163 Are you using `tsi` or `inmem`?

I have not been able to reproduce this issue with the pattern of deletes that you sending.  I did find two other issues in #9117 that will be in a the next 1.4.2 release.

**Comment by max3163** [comment] 2017-11-16 13:09
Hi @jwilder 

We use the default one ( inmem so ?  ) but I tested with tsi1 option with the same result ... 
I installed the nightly version of influxdb to test too, the problem is worst. I can't delete a specific point without lost directly all data from the events measurement for the specif tag ... And with many delete in a row, I lost as before 6-7 days ( or more ) of all data from all measurements ...
The difference in the nightly version is the execution time of the delete, rly faster, no compaction between each query.

**Comment by jwilder** [comment] 2017-11-16 13:48
Do you have a script that I can run to try and reproduce this issue? 

What type of hardware (file system,drive types, mounting options, etc.) are you using for storage? Are thes directly attached SSDs?

**Comment by jwilder** [comment] 2017-11-16 23:05
I was able to reproduce data appearing to be deleted.  I'm not sure sure if it's exactly what you are seeing or not though.  The issue I was seeing is a query bug.  Deleting data that just happens to cover the first block of a series can cause all the remaining data in that series to abruptly disappear. After a compaction occurs, the data can re-appear.  The data is still on disk, it's just not getting returned due to the query bug.

@max3163 If you are able to test #9129 and let me know if that resolves your issue, that would be great.

**Comment by max3163** [comment] 2017-11-17 13:52
@jwilder 

I tested the nightly build version and still the issue. 
When I delete one or two point in the events measurement, all of them for the selected tag are deleted, like the time is not considered. 

Log : [log3.txt](https://github.com/influxdata/influxdb/files/1482488/log3.txt)

But if I restart influxdb instance, data reappear... 
If I try many delete in a row... 2 or 3 times, after I lost all data, for the last 7 days on all measurements of the database, and even with a restart, this time, the data aren't present.

**Comment by jwilder** [comment] 2017-11-17 14:02
@max3163 What commit are you running from the nightly?

**Comment by max3163** [comment] 2017-11-17 14:06
=> aa99a56bf122efc5a5d74dd22c10651ebfab4031

![image](https://user-images.githubusercontent.com/13835366/32950994-a0b0c37e-cba8-11e7-802c-9114a7bdc72c.png)

Proc = Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
Mem : 8Go
Mount on : /dev/mapper/vgl_xxxx_tech-lvl_data on /tech/data/influxdb type ext4 (rw,relatime,nodelalloc,data=ordered)

**Comment by jwilder** [comment] 2017-11-17 14:28
Are there writes to theses series/measurements occurring at the day time as the deletes/queries?

This issue sounds more like the inmem index is getting inconsistent with the data stored since a restart fixes it.

**Comment by max3163** [comment] 2017-11-17 14:49
Yes , data occurring at the same day time of the deletes queries points.
A restart fixes only for data lost on the ' events ' measurement, when no over data are lost. 
But when I lost all data during last few day, the restart doesn't fixes it.

**Comment by jwilder** [comment] 2017-11-17 14:54
What are the other measurements names that disappear when you run the delete?

**Comment by max3163** [comment] 2017-11-17 14:56
All others measurements of the database : 

batch
custom
events
filesystem
generic
introscope
jmeter
jmxagent
log
mongodb
monitor
mq
process
statslog
...

**Comment by jwilder** [comment] 2017-11-17 22:46
@max3163 Unfortunately, I have been unsuccessful in reproducing what you are seeing with current master build.  If you are able to figure out some steps that would allow me to reproduce this, that would be very helpful.

**Comment by max3163** [comment] 2017-11-20 09:17
I will try to make a little program to reproduce the behaviour.

**Comment by max3163** [comment] 2017-11-22 14:11
@jwilder  
How can I send you in private a short export file from the events measurement with a short script to show you a part of our problem ?

**Comment by jwilder** [comment] 2017-11-22 16:47
@max3163 You could email it or send a dropbox link to me: jason at influxdb.com.  Would that work?

**Closed** 2017-11-28 15:51 UTC
Labels: review

**Comment by max3163** [comment] 2017-11-29 14:18
I've just install the latest nightly build :

Branch | Build Time | Commit | Version
-- | -- | -- | --
master | "" | "df96d3064afddbcce17eba8ee78b4c5303fd7c84" | "1.5.0~n201711290800"

But I encounter exactly the same behaviour than before. 
I just delete one point on the events measurement and I can't query data from the tag serie just after. All series is lost..

**Comment by jwilder** [comment] 2017-11-29 17:48
@max3163 I have a followup fix (#9179) that should have been part of #9168.  I'm hoping this resolves the issue you saw in df96d30.
