### ISSUE TITLE
[0.10.1] http-bind-address not working as expected (cannot cluster)

### ISSUE THREAD

**Issue by gtirloni** [influxdata/influxdb#5874] opened 2016-03-01 13:24 UTC
When http-bind-address is set to ":8091", InfluxDB only listens on the 127.0.0.1 address, preventing other nodes from connecting. Config:

    [meta]
      enabled = true
      dir = "/var/lib/influxdb/meta"
      bind-address = ":8088"
      http-bind-address = ":8091"
      retention-autocreate = true
      election-timeout = "1s"
      heartbeat-timeout = "1s"
      leader-lease-timeout = "500ms"
      commit-timeout = "50ms"
      cluster-tracing = false

Connections:

    $ netstat -antp |grep 8091
    tcp        0      0 127.0.0.1:8091          0.0.0.0:*               LISTEN      18625/influxd       
    tcp        0      0 127.0.0.1:8091          127.0.0.1:58086         ESTABLISHED 18625/influxd       
    tcp        0      0 127.0.0.1:58087         127.0.0.1:8091          ESTABLISHED 18625/influxd       
    tcp        0      0 127.0.0.1:8091          127.0.0.1:58087         ESTABLISHED 18625/influxd       
    tcp        0      0 127.0.0.1:58086         127.0.0.1:8091          ESTABLISHED 18625/influxd       

If http-bind-address is set to "IP:8091", InfluxDB only listens on IP (expected) but it causes the following error when starting:

    [metaclient] 2016/03/01 13:18:39 failure getting snapshot from localhost:8091: Get http://localhost:8091?index=0: dial tcp 127.0.0.1:8091: connection refused

Environment: 3 hybrid nodes running CentOS 7.2 and InfluxDB 0.10.1-1 (RPM)

**Comment by rossmcdonald** [comment] 2016-03-01 14:16
@gtirloni If you haven't already, please read through the [clustering documentation](https://docs.influxdata.com/influxdb/v0.10/clustering/cluster_setup/). With v0.10, the IP address must be specified in order to receive external communication.

Regarding the last error:

```
[metaclient] 2016/03/01 13:18:39 failure getting snapshot from localhost:8091: Get http://localhost:8091?index=0: dial tcp 127.0.0.1:8091: connection refused
```

I have a feeling this was caused by the original configuration, where InfluxDB is still expecting to find a node at `localhost:8091`, instead of `<IP>:8091`. In order to fix that, you'll need to wipe your data directory (typically `/var/lib/influxdb`) in order to clear the current meta configuration. Please note that this will wipe any data that you have stored inside the database, so only remove that directory if you don't need to keep any data.

**Comment by gtirloni** [comment] 2016-03-01 14:18
I do need to keep the data though. Does it mean changing the server IP address in the future means I need to erase the data too?

**Comment by rossmcdonald** [comment] 2016-03-01 14:27
@gtirloni I would recommend using hostnames instead of IP addresses in the future, where you just specify the hostname in the `bind-address` parameter instead of the IP (ex: `influx1:8091`).

I'm not sure if there is a way to fix this issue without wiping the data directory, though. Clustering is still considered experimental with 0.10, so I would recommend using a single instance if you are storing critical data. What does the output of `SHOW SERVERS` look like? And which servers have you been writing data to? It may be possible to fix this by dropping the servers and re-adding them.

**Comment by gtirloni** [comment] 2016-03-01 14:37
It seems tweaking /var/lib/influxdb/meta/node.json from "localhost:8091" to "10.10.10.1:8091" worked around the issue (although localhost:8091 is back there now, but I don't see the snapshot errors anymore).


    > show servers
    name: data_nodes
    ----------------
    id	http_addr	tcp_addr
    1	localhost:8086	localhost:8088
    
    
    name: meta_nodes
    ----------------
    id	http_addr		tcp_addr
    1	10.10.10.1:8091	localhost:8088
    2	localhost:8091		localhost:8088
    3	10.10.10.2:8091	localhost:8088
    4	10.10.10.3:8091	localhost:8088

Now I need to figure out how the >20GiB of data I have can get replicated over to the new nodes. I'll check the docs/code.

Thanks for helping out.

**Comment by rossmcdonald** [comment] 2016-03-01 14:40
@gtirloni You also want to make sure that all `bind-address` parameters in your configuration are set with the same IP/hostname (per the docs), as the `localhost` references everywhere are going to cause more issues.

Regarding:

> Now I need to figure out how the >20GiB of data I have can get replicated over to the new nodes.

I don't believe there's a way to increase the replication factor after the data has already been written, but I'm not 100% sure. Please open a new issue if you run into issues increasing the RF.

**Comment by jsternberg** [comment] 2016-05-17 17:10
I'm going to close this since we no longer support clustering in the open source version of the software.

**Closed by jsternberg** 2016-05-17 17:10 UTC
Labels: category/clustering, category/configuration
