### ISSUE TITLE
[BUG] Backup stopped working after upgrade to 1.3.2

### ISSUE THREAD

**Issue by skladd** [influxdata/influxdb#8677] opened 2017-08-09 08:06 UTC
After yesterday's upgrade to version 1.3.2 (from 1.3.1 via Debian repo), backup fails with this error message:

`influxd backup -database telegraf /tmp/influxbackup`

```
2017/08/09 10:05:21 backing up db=telegraf since 0001-01-01 00:00:00 +0000 UTC
2017/08/09 10:05:21 backing up metastore to /tmp/influxbackup/meta.01
2017/08/09 10:05:21 backing up db=telegraf rp=autogen shard=169 to /tmp/influxbackup/telegraf.autogen.00169.00 since 0001-01-01 00:00:00 +0000 UTC
2017/08/09 10:05:21 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/08/09 10:05:22 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/08/09 10:05:23 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2017/08/09 10:05:24 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2017/08/09 10:05:25 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2017/08/09 10:05:26 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2017/08/09 10:05:27 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2017/08/09 10:05:28 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2017/08/09 10:05:29 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2017/08/09 10:05:30 Download shard 169 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2017/08/09 10:05:31 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0
```
Version: 1.3.2
OS: Debian jessie on x86_64

**Comment by skladd** [comment] 2017-08-09 09:19
On another server, where influxdb was installed much later (thus a more recent version), backup still works after the upgrade.

**Comment by skladd** [comment] 2017-08-10 07:38
I was able to successfully perform the backup after downgrading to 1.3.1-1 (from deb file luckily still in apt cache) and manually restarting influxdb daemon.

The failing influxdb instance was originally installed back in 2016, version 1.0.0:
```
Start-Date: 2016-09-29  16:17:27
Commandline: apt-get install influxdb
Install: influxdb:amd64 (1.0.0-1)
```

**Comment by duvidcz** [comment] 2017-08-10 10:27
I have same problem with windows version 1.3.2 -1

**Comment by codylewandowski** [comment] 2017-08-10 19:05
We have ~10 databases we just upgraded to 1.3.2-1 today that we are now seeing the same issue on.

**Comment by marcofl** [comment] 2017-08-11 13:56
same issue here:
```
2017/08/11 15:42:54 backing up db=icinga2 since 2017-08-10 13:42:54 +0000 UTC
2017/08/11 15:42:54 backing up metastore to /srv/storage/influxdb-prebackup/tmp.o0B6CT8vC4/meta.00
2017/08/11 15:42:54 backing up db=icinga2 rp=6weeks shard=471 to /srv/storage/influxdb-prebackup/tmp.o0B6CT8vC4/icinga2.6weeks.00471.00 since 2017-08-10 13:42:54 +0000 UTC
2017/08/11 15:42:54 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/08/11 15:42:55 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/08/11 15:42:56 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2017/08/11 15:42:57 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2017/08/11 15:42:58 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2017/08/11 15:42:59 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2017/08/11 15:43:00 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2017/08/11 15:43:01 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2017/08/11 15:43:02 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2017/08/11 15:43:03 Download shard 471 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2017/08/11 15:43:04 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0
```
downgrade to 1.3.1 solved the issue. 

looks like the fix from https://github.com/influxdata/influxdb/pull/8378/commits somehow got reverted

**Comment by skladd** [comment] 2017-08-18 06:28
Works for me again since latest nightly: 1.4.0~n201708170800-0
Thank you!

**Comment by skladd** [comment] 2017-08-21 06:53
Apparently the patch did not make it into 1.3.3.

**Comment by davidbru** [comment] 2017-08-21 20:11
Can confirm, that in 1.3.3 it's also not working for me.

**Comment by dgnorton** [comment] 2017-08-21 20:19
It will be in 1.3.4.

**Comment by ayush-sharma** [comment] 2017-08-23 15:37
This is broken in 1.3.3.

Metastore backup is fine but database backups produce errors. Can't get it to work on Mac or Ubuntu. I can also confirm that the backup directories have correct permissions, so it doesn't seem to be that.

```
2017/08/23 20:24:14 backing up db=test since 0001-01-01 00:00:00 +0000 UTC
2017/08/23 20:24:14 backing up metastore to /tmp/JIuZnHpa/test/meta.00
2017/08/23 20:24:14 backing up db=test rp=autogen shard=2 to /tmp/JIuZnHpa/test/test.autogen.00002.00 since 0001-01-01 00:00:00 +0000 UTC
2017/08/23 20:24:14 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2017/08/23 20:24:15 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2017/08/23 20:24:16 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2017/08/23 20:24:17 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2017/08/23 20:24:18 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2017/08/23 20:24:19 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2017/08/23 20:24:20 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2017/08/23 20:24:21 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2017/08/23 20:24:22 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2017/08/23 20:24:23 Download shard 2 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2017/08/23 20:24:24 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0

```

**Comment by skladd** [comment] 2017-08-24 06:28
1.3.4 is out, backup works again. Thanks!

**Comment by jigarshahindia** [comment] 2018-01-09 03:00
influx --version
InfluxDB shell version: 1.4.2

Same issue
influxd  backup -database test /tmp/backup

2018/01/09 08:27:20 backing up metastore to /tmp/backup/meta.02
2018/01/09 08:27:20 backing up db=test rp=autogen shard=13 to /tmp/backup/test.autogen.00013.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:20 backing up db=test rp=autogen shard=21 to /tmp/backup/test.autogen.00021.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:20 backing up db=test rp=autogen shard=29 to /tmp/backup/test.autogen.00029.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:20 backing up db=test rp=autogen shard=37 to /tmp/backup/test.autogen.00037.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:20 backing up db=test rp=autogen shard=45 to /tmp/backup/test.autogen.00045.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:20 backing up db=test rp=autogen shard=53 to /tmp/backup/test.autogen.00053.01 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:21 backing up db=test rp=autogen shard=61 to /tmp/backup/test.autogen.00061.00 since 0001-01-01 00:00:00 +0000 UTC
2018/01/09 08:27:21 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...
2018/01/09 08:27:22 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...
2018/01/09 08:27:23 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...
2018/01/09 08:27:24 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...
2018/01/09 08:27:25 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...
2018/01/09 08:27:26 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...
2018/01/09 08:27:27 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...
2018/01/09 08:27:28 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...
2018/01/09 08:27:29 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...
2018/01/09 08:27:30 Download shard 61 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...
2018/01/09 08:27:31 backup failed: copy backup to file: err=<nil>, n=0
backup: copy backup to file: err=<nil>, n=0

**Comment by iliketosneeze** [comment] 2018-03-23 10:18
I am getting the same on 1.5.0. Are there any updates on this?
```
2018/03/23 05:01:23 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (0)...                                                                        
2018/03/23 05:01:24 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (1)...                                                                        
2018/03/23 05:01:25 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (2)...                                                                        
2018/03/23 05:01:26 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (3)...                                                                        
2018/03/23 05:01:27 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (4)...                                                                        
2018/03/23 05:01:28 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (5)...                                                                        
2018/03/23 05:01:29 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (6)...                                                                        
2018/03/23 05:01:30 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (7)...                                                                        
2018/03/23 05:01:31 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (8)...                                                                        
2018/03/23 05:01:32 Download shard 27 failed copy backup to file: err=<nil>, n=0.  Retrying (9)...                                                                        
2018/03/23 05:01:33 backup failed: copy backup to file: err=<nil>, n=0               
backup: copy backup to file: err=<nil>, n=0                                          
```

**Comment by rbetts** [comment] 2018-03-26 12:43
@dgnorton Can you work on reproducing this David?

**Comment by dgnorton** [comment] 2018-03-26 12:53
@iliketosneeze this looks like #9618. In your case, is the `ifnluxd` binary 1.5.0 and the running instance (the source) an older version of `influxd`?

**Comment by iliketosneeze** [comment] 2018-03-26 13:40
@dgnorton We are using 1.5.0 for both the running instance and the backup.

**Comment by dgnorton** [comment] 2018-03-26 17:05
@iliketosneeze is TSI enabled?

**Comment by amerenda** [comment] 2018-03-26 18:14
@dgnorton I'm having this issue on influxd-1.5.0-1 with TSI enabled.

**Comment by iliketosneeze** [comment] 2018-03-27 08:57
@dgnorton Yes, we have TSI enabled as well.

**Comment by dgnorton** [comment] 2018-03-28 17:25
I have been able to reproduce this. In the repro, it happens fairly often but not every time.
#### Setup using AWS
* One m4.10xlarge instance with 100GB gp2 storage
  * `ssh` into InfluxDB instance and update config to use `tsi1` index
    * `sudo systemctl stop influxdb.service`
    * `sudo sed -i.bak 's/# bind-address = "127.0.0.1:8088"/bind-address = ":8088"/' /etc/influxdb/influxdb.conf`
    * `sudo sed -i.bak 's/# index-version = "inmem"/index-version = "tsi1"/' /etc/influxdb/influxdb.conf`
    * `sudo systemctl start influxdb.service`
* One m4.10xlarge instance running the [`inch` tool](https://github.com/influxdata/inch) to generate high cardinality load.
  * inch -host http://10.0.7.177:8086 -p 1000 -t "10,10,10,10,10,10,10"
* Once `inch` is generating load, `ssh` into the InfluxDB instance and start creating backups.
  * `rm bak/* && influxd backup -database stress bak/`

**Comment by aanthony1243** [comment] 2018-04-09 18:53
@dgnorton  the above repro seems to occur if another snapshot is being taken at the same time, as in the case of periodic compactions.  I've seen it fail out after 10 attempts.  I've also seen it fail 5, 6 times and then succeed.  We could consider this to be a resource/locking error, but regardless this scenario doesn't seem to be a blocker.  

@iliketosneeze   does the problem happen consistently, like 20/50/100% of the time?  Or more sporadically?  Could you share the influxd logs from the time of the backup?

**Comment by iliketosneeze** [comment] 2018-04-10 15:16
@aanthony1243 It's not 100%, but it is very often. I also seems to depend on the size of the db/shards. Smaller ones don't seem to do it that often.
I have uploaded the logs from a time the backups were failing: [https://gist.github.com/iliketosneeze/bc37b54f03219bba69266779185c9f61](https://gist.github.com/iliketosneeze/bc37b54f03219bba69266779185c9f61)

**Comment by aanthony1243** [comment] 2018-04-10 15:40
@iliketosneeze   I don't see any of the errors in your gist that I saw when reproducing above, but the symptoms are still there. It happens more frequently on larger DB/shards because there's a resource competition when taking shard snapshots.  If another process holds the resource for too long the backup will fail.   We're looking into the root cause now.

**Comment by aanthony1243** [comment] 2018-04-13 01:49
@iliketosneeze   we've adjusted the backup to use an exponential backoff to give the server  more time to free resources.  It's out in the just-released 1.5.2.    If you continue to see frequent occurrence of this after upgrading, please open a new issue and we will follow up.

**Closed by aanthony1243** 2018-04-13 01:49 UTC
Labels: area/backup and restore

**Comment by aanthony1243** [comment] 2018-09-27 13:28
it sounds like you are prepared to tolerate some down time.  It should be safe to stop influxd, move the entire influxdb directory to a new location, and then update your influxdb config to use that new location.

**Comment by sjlongland** [comment] 2018-09-29 07:31
This is true, that is safe enough, but how about back-up?  We'll ultimately want to bump these up to the latest release before long (there are a *lot* of features in the newer InfluxDB), but doing so without a good back-up is a risky proposition.

In the meantime we need to be able to back up that instance, and do so without disruption.  We do these backups on a daily basis, re-starting InfluxDB every 24 hours will likely not be welcome.  How do we safely back up the data without shutting down InfluxDB?

**Comment by aanthony1243** [comment] 2018-10-01 13:43
I misunderstood your issue. you can check the influxdb logs on the server side to see if an error is being logged when nothing is returned on the connection.  If you find something, perhaps we should open it as a new issue and continue from there?

**Comment by samvruggink** [comment] 2018-10-01 14:05
I have the same issue. I found out that whenever I mount my volume under `/var/lib/influxdb/` it fails to backup and when I restart my instance container it cannot read the data anymore.

When I mount my volume under `/var/lib/backup` where `backup` is my own folder the backup works. I have no clue how to fix this issue. I'm using Microsoft Azure with Instance containers and File Shares.
