### ISSUE TITLE
how to do 'SELECT LAST(*) FROM Msr GROUP BY time(1s) fill(previous)'?

### ISSUE THREAD

**Issue by BrannonKing** [influxdata/influxdb#5978] opened 2016-03-10 22:04 UTC
I would like a query that dumps me all fields into CSV with every cell filled. I have a lot of fields (300-ish). I can write a program to query the list of fields and then generate the query. That just doesn't seem ideal.

**Comment by jsternberg** [comment] 2016-03-14 21:19
I think it's reasonable to allow the wildcard syntax for some function calls like `last()`, but as a workaround, you can do something like this in the upcoming if you know at least one of the field names:

```
SELECT last(value), * FROM cpu
```

You'll have to remove the `last` column or ignore it, but it will get you what you want.

**Comment by BrannonKing** [comment] 2016-03-31 23:24
Your usage of the * works as long as you don't put a limit on the query. It seems that adding limit (and also group by) causes some kind of infinite loop.

**Comment by beckettsean** [comment] 2016-06-02 15:44
related to #5750, probably a dupe

**Comment by jsternberg** [comment] 2016-08-09 05:32
Duplicate of #5750. Closing this since that's now implemented.

**Closed by jsternberg** 2016-08-09 05:32 UTC
Labels: category/functions, category/queries
