### ISSUE TITLE
moving_average in grafana always missing on left and sometimes missing completely

### ISSUE THREAD

**Issue by jfbeaumont** [influxdata/influxdb#7752] opened 2016-12-21 02:26 UTC
When using influxdb behind grafana, the moving_average function is systematically missing a number (N) of points on the left which seems to be related to moving_average(func(), N). When zooming and having less than N points available, the moving_average series is missing completely.

Here is a screenshot of what I mean. The moving average line is the red one.
![capture d ecran 2016-12-20 a 21 24 31](https://cloud.githubusercontent.com/assets/692031/21375336/cfb25b78-c6fa-11e6-89e8-77eed5ed7903.png)

Is there a workaround to get the moving average series to show completely?

Thx!

**Comment by desa** [comment] 2016-12-21 19:22
@jfbeaumont Whats the exact query that is getting sent to Influx?

**Comment by jfbeaumont** [comment] 2016-12-21 22:07
@desa thanks for your reply!

I agree with you that computing the moving average for let say 30 points can have a undefined results for the first 29 points but I wouldn't mind if influxdb was trying to do the best it can with what it has. It would be fine if the moving average was noisier at the beginning but I understand it might not be a good idea in all cases.

I can definitely live with a graph like that where my first month of data is not "averaged":

![image](https://cloud.githubusercontent.com/assets/692031/21407750/177e390a-c79f-11e6-81bd-09a74fe1f1c6.png)

But the problem I have is when I zoom:

![image](https://cloud.githubusercontent.com/assets/692031/21407864/aaddea74-c79f-11e6-9d31-e2ce1220cd24.png)

Now I still have 29 (I didn't count! but I'm guessing) points missing although the data does exist. Maybe this is something I can fix with my query? Here it is:

SELECT moving_average(sum("cpuTime"),30)/moving_average(sum("wallClockTime"),30) FROM "cpu" WHERE $timeFilter GROUP BY time($interval) fill(null)

Thank you!

**Comment by desa** [comment] 2016-12-21 22:58
I think the issue is that the default zoom out in Grafana increases the value of  `$interval` in query. Manually setting `$interval` in the query should fix that issue.

**Comment by jfbeaumont** [comment] 2016-12-21 23:04
I modified my query like so:

`SELECT moving_average(sum("cpuTime"),30)/moving_average(sum("wallClockTime"),30) FROM "cpu" WHERE $timeFilter GROUP BY time(**30d**) fill(null)
`
But it doesn't look like it's working. The moving_average series disappears.

Thanks for your help!

**Comment by desa** [comment] 2016-12-21 23:05
Try making id `1d`

**Comment by jfbeaumont** [comment] 2016-12-21 23:09
No luck!

With 1s:

SELECT moving_average(sum("cpuTime"),30)/moving_average(sum("wallClockTime"),30) FROM "cpu" WHERE $timeFilter GROUP BY time(1s) fill(null)

![image](https://cloud.githubusercontent.com/assets/692031/21409472/7f50c7f6-c7a8-11e6-9edf-cec51fe19f25.png)

With 1d:

SELECT moving_average(sum("cpuTime"),30)/moving_average(sum("wallClockTime"),30) FROM "cpu" WHERE $timeFilter GROUP BY time(1d) fill(null)

![image](https://cloud.githubusercontent.com/assets/692031/21409488/96c83e3c-c7a8-11e6-89b7-4df0a5f93113.png)

**Comment by desa** [comment] 2016-12-21 23:17
Check the InfluxDB logs to see what query it's actually receiving.

**Comment by jsternberg** [comment] 2016-12-24 04:49
I think you might be able to use `fill(0)` to do what you want. That function skips null values, but it will use values from fill.

I'm not 100% sure if I understand the problem, but it's worth a try.

**Comment by shubhamod1** [comment] 2017-10-05 10:19
Hey,
I started using Grafana with MySQL as datasource . But while quering data is coming on series mode . But i am not able to set the time range and ZOOM IN from UI . It says data-point outside the time range ,but they are in the time range.

**Comment by stephanMettler** [comment] 2017-11-18 04:53
Are you looking for the **min-time interval** ? Or getting this error on **all** your queries? 

**Invalid interval string, expecting a number followed by one of "Mwdhmsy"**

there is also a similar option in the Datasource-Selection-ui!
![Image of grafana](https://image.ibb.co/isZThm/grafana.png)

**Comment by rbetts** [comment] 2018-02-01 20:47
Closing - we think this functions as designed.

**Closed by rbetts** 2018-02-01 20:47 UTC
Labels: area/queries, area/query language

**Comment by drkovalskyi** [comment] 2018-07-21 09:13
While it functions as designed it can still be a problem in some cases. Basically one needs more data for averaging than the default query provides. I needed a weekly average of data rates and in order to avoid missing points I changed "$timeFilter" to "$timeFilter - 7d" in the query and now it all works as intended, i.e I get extra data to have the moving average defined for all points in the time window. It's a kludge, but it works.
