### ISSUE TITLE
use native embed pkg to embed static assets

### ISSUE THREAD

**Issue by foobar** [influxdata/influxdb#21495] opened 2021-05-18 11:22 UTC
Go 1.16 has introduced package embed which helps embedding static files into binary. Currently influxdb uses `go-bindata` to generate static assets. It can be replaced with go1.16+ embed

**Comment by danxmoran** [comment] 2021-07-22 18:58
Everything but UI files has been converted to use `go:embed`. #21652 tracks addressing some issues we hit while trying to include the UI; closing this one as a duplicate of that.

**Closed by danxmoran** 2021-07-22 18:58 UTC
Labels: area/2.x, kind/tech-debt
