### ISSUE TITLE
time OR does not work

### ISSUE THREAD

**Issue by alex09x** [influxdata/influxdb#7070] opened 2016-07-26 21:55 UTC
Query
SELECT _count FROM table where time = 1469404800000000000 or time = 1468800000000000000 or time = 1468195200000000000;
Return empty result

Log
[query] 2016/07/27 00:21:41 SELECT _count FROM table WHERE time = 1469404800000000000 OR time = 1468800000000000000 OR time = 1468195200000000000
[httpd] 2016/07/27 00:21:41 127.0.0.1 - - [27/Jul/2016:00:21:41 +0300] POST /query?chunked=true&db=rusiem&epoch=ns&q=SELECT+_count+FROM+table+where+time+%3D+1469404800000000000+or+time+%3D+1468800000000000000+or+time+%3D+1468195200000000000%3B HTTP/1.1 200 46 - InfluxDBShell/0.13.0 f2208ead-5376-11e6-9967-000000000000 916.175µs

Query
SELECT _count FROM table where time = 1469404800000000000;
Return result
1469404800000000000	4
1469404800000000000	3
1469404800000000000	1

Help please!!

Version influxdb_0.13.0_amd64.deb

**Comment by jsternberg** [comment] 2016-07-29 20:56
Duplicate of #3290.

**Closed by jsternberg** 2016-07-29 20:56 UTC
