### ISSUE TITLE
tag values are not inserted with continuous query

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#10036] opened 2018-07-04 03:52 UTC
__System info:__ influxdb 1.5.2

__Steps to reproduce:__

0. Send data to influxdb using collectd
1. Seed a new table with data using this query:
SELECT value AS newname INTO tableA FROM tableB GROUP BY host,instance
2. Create a continuos query as follows:
CREATE CONTINUOUS QUERY mycq ON collectd
BEGIN
    SELECT distinct(value) AS newname FROM tableA GROUP BY time(1m),host,instance
END
3. Run a query on the data
SELECT * FROM tableA GROUP BY host,instance

__Expected behavior:__
I expect to see rows in the table like this:
```
name: tableA
tags: host=hostname, instance=myprog
time               host       instance   newname
----               ----       ---------  ------
153673620000000000 hostname   myprog     123
...
153673620000000000 hostname   myprog     123
```

__Actual behavior:__ [What actually happened]

```
name: tableA
tags: host=hostname, instance=myprog
time               host                instance   newname
----               ----                ---------  ------
153643620000000000 hostname                        123
...
153673620000000000                                 123
```

What's wrong is that the entries in the output of SELECT do not fill in the "host" column of the table like the initial table seeding does however if I do:
SELECT * FROM tableA WHERE time = 153673620000000000
then all of the columns are correct.

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by e-dard** [comment] 2018-07-09 11:39
@yellowpattern thanks for the ticket—your actual and expected output look the same. Did you maybe copy and paste something incorrectly?

**Comment by yellowpattern** [comment] 2018-07-10 01:06
It could be a cut-paste problem - I also have to be sensitive about the data itself (which makes it a bit difficult too.) Lets see if converting the text to code helps.

My workaround is a cron job that runs every 15 minutes that does the SELECT-INTO with "time > now() - 15m".

**Comment by e-dard** [comment] 2018-07-10 10:54
Thanks @yellowpattern I can now see what you mean.

**Comment by lukaszdudek-silvair** [comment] 2019-03-05 10:27
It looks like a duplicate of  #7627.

**Comment by yellowpattern** [comment] 2019-07-23 08:29
This is still a problem.

**Closed** 2019-10-28 09:24 UTC
Labels: 1.x, area/queries, wontfix

**Comment by yellowpattern** [comment] 2019-10-28 12:24
It might be related to #7627 but not identical.
