### ISSUE TITLE
Issue with hourly Continuous Queries for IST timezone (+530)

### ISSUE THREAD

**Issue by dhakadamit** [influxdata/influxdb#6074] opened 2016-03-21 16:45 UTC
Due to lack of timezone support, the continuous queries create hourly data in UTC. Since, in India, we are 5:30 hours ahead, the data ends beings calculated at 9:30 IST, 10:30 IST instead of hourly calculations like 9:00 IST, 10:00 IST.

Any ideas?

**Comment by joelegasse** [comment] 2016-03-22 14:57
This is a duplicate of #2074

**Closed by joelegasse** 2016-03-22 14:57 UTC
