### ISSUE TITLE
Inconsistent behavior for queries with very small time units

### ISSUE THREAD

**Issue by pbooth** [influxdata/influxdb#4645] opened 2015-11-03 17:26 UTC
I'm finding it difficult to get consistent behavior when querying Influxdb (from grafana fwiw) for *very* finely grained data. See below for data written approx 50,000 times per second, where I am trying to create a scatter plot at sub-millisecond resolution:

```
> SELECT COUNT(value) FROM "latency_micros" WHERE  time > 1446134760s and time < 1446134762s GROUP BY time(1ms) LIMIT 3
name: latency_micros
--------------------
time                            count
2015-10-29T16:06:00Z            51
2015-10-29T16:06:00.001Z        50
2015-10-29T16:06:00.002Z        51

> SELECT COUNT(value) FROM "latency_micros" WHERE  time > 1446134760s and time < 1446134762s GROUP BY time(500u) LIMIT 3
ERR: time dimension must have one duration argument
> SELECT COUNT(value) FROM "latency_micros" WHERE  time > 1446134760s and time < 1446134762s GROUP BY time(500000n) LIMIT 3
ERR: error parsing query: found n, expected ) at line 1, char 112
```

Is there a different level of support for different time units?

Puzzled,

**Comment by beckettsean** [comment] 2015-11-03 17:43
@jackzampolin can you investigate and try to repro?

**Comment by jackzampolin** [comment] 2015-11-03 18:01
@beckettsean On it!

**Comment by jackzampolin** [comment] 2015-11-03 19:08
### Data Set:

```
> select * from latency_micros where time > now() - 10m
name: latency_micros
--------------------
time			    latency	   value
1446575910000000000	one	        1
1446575910000000001	two	        1
1446575910000000002	one	        2
1446575910000000003	two	        2
1446575910000000004	one	        3
1446575910000000005	two	        3
1446575910000000006	one	        4
1446575910000000007	two	        4
1446575910000000008	one	        5
1446575910000000009	two	        5
```

### Queries 

GROUP BY time(1ms)
```
> select count(value) from latency_micros where time > 1446575909999999999 group by time(1ms) limit 3
name: latency_micros
--------------------
time			    count
1446575910000000000	9
1446575910001000000	
1446575910002000000	
```
GROUP BY time(1u)
```
> select count(value) from latency_micros where time > 1446575909999999999 group by time(1u) limit 3
name: latency_micros
--------------------
time		  	    count
1446575910000000000	9
1446575910000001000	
1446575910000002000	
```
GROUP BY time(500n)
```
> select count(value) from latency_micros where time > 1446575909999999999 group by time(500n) limit 3
ERR: error parsing query: found n, expected ) at line 1, char 91
```

Per the [querying time syntax documentation](https://influxdb.com/docs/v0.9/query_language/data_exploration.html#time-syntax-in-queries) it does not appear that we support nanosecond precision in queries.

I was not able to reproduce the microsecond error. What version of InfluxDB are you running?

**Comment by jsternberg** [comment] 2016-05-18 02:13
This is an older issue and has probably been fixed in a newer version. I'm going to close this issue. Please try a newer version and comment on this issue if you still are experiencing this issue. Thank you.

**Closed by jsternberg** 2016-05-18 02:13 UTC
