### ISSUE TITLE
Select mean and percentile within one query and group by gives non-distinct lines

### ISSUE THREAD

**Issue by DAfanasyev** [influxdata/influxdb#8164] opened 2017-03-19 16:52 UTC
System info: 
- Ubuntu 16.04
- InfluxDB 1.2
- Grafana 4.1.2 (commit: v4.1.2)

I'm using JMeter plugin to push metrics into InfluxDB (https://github.com/NovaTecConsulting/JMeter-InfluxDB-Writer)

Here is how plugin stores information (some measurements are skipped):
```
> show field keys
name: requestsRaw
fieldKey     fieldType
--------     ---------
errorCount   integer
responseTime integer
...

> show tag keys
name: requestsRaw
tagKey
------
requestName
...
```

Then I'm trying to create an overview table with mean and 90th percentile for each "requestName" in Grafana using following InfluxQL request:
```
select mean("responseTime"), percentile("responseTime", 90) from "requestsRaw" group by "requestName"
```

Actual behavior:
```
> select mean("responseTime"), percentile("responseTime", 90) from "requestsRaw" group by "requestName"
name: requestsRaw
tags: requestName=Main
time mean              percentile
---- ----              ----------
0    731.0807017543859 

name: requestsRaw
tags: requestName=Root
time mean               percentile
---- ----               ----------
0    51.316569200779725 61

name: requestsRaw
tags: requestName=Threads
time mean               percentile
---- ----               ----------
0    46.776649746192895 53

name: requestsRaw
tags: requestName=Main
time mean percentile
---- ---- ----------
0         749
```

Expected behavior:
```
> select mean("responseTime"), percentile("responseTime", 90) from "requestsRaw" group by "requestName"
name: requestsRaw
tags: requestName=Main
time mean              percentile
---- ----              ----------
0    731.0807017543859 749

name: requestsRaw
tags: requestName=Root
time mean               percentile
---- ----               ----------
0    51.316569200779725 61

name: requestsRaw
tags: requestName=Threads
time mean               percentile
---- ----               ----------
0    46.776649746192895 53
```

I've also noticed that group by doesn't return distinct result only when percentile function is used (at least in my case):
```
> select mean("responseTime"), max("responseTime") from "requestsRaw" group by "requestName"
name: requestsRaw
tags: requestName=Main
time mean              max
---- ----              ---
0    731.0807017543859 1016

name: requestsRaw
tags: requestName=Root
time mean               max
---- ----               ---
0    51.316569200779725 310

name: requestsRaw
tags: requestName=Threads
time mean               max
---- ----               ---
0    46.776649746192895 324
```

**Comment by DAfanasyev** [comment] 2017-03-19 19:47
Might be similar to https://github.com/influxdata/influxdb/issues/8072.

I've also just noticed that it works with percentile("responseTime", 99).

**Comment by jsternberg** [comment] 2017-03-20 16:43
Closing this in favor of #8167.

**Comment by luhn** [comment] 2017-04-27 23:53
I've been experiencing this issue too.  After upgrading to v1.2.3, which fixes #8167, this issue remains.  It seems this is a separate issue than #8167 and is yet unresolved.

**Comment by jsternberg** [comment] 2017-04-28 03:36
I'll take a look at this tomorrow then.

**Comment by jsternberg** [comment] 2017-04-28 16:24
@luhn do you have a reproducer I could look at? @DAfanasyev does this still affect you?

**Comment by luhn** [comment] 2017-04-28 16:33
The query I'm seeing it on is something like this:

```
SELECT percentile("duration", 95), percentile("duration", 99) FROM "measurement" WHERE time > now() - 8h GROUP BY "context", "view_name"
```

I'll see if I can make something reproducible.

**Comment by luhn** [comment] 2017-04-28 17:37
Okay, here's a data file and a sample query, along with the output I'm seeing. 
 https://gist.github.com/luhn/dbc791f6164cc7c12737502a6860be0d

**Comment by jsternberg** [comment] 2017-04-28 18:14
Hm... curious. The `v1.2.3` tag has it not working but it's working on master now.

I'll see if I can find the commit that fixes it.

**Comment by jsternberg** [comment] 2017-04-28 18:25
Looks like it's fixed as of be3bce5. Unfortunately, I do not envision me being able to backport that easily. Is it alright if this fix comes as part of 1.3? I believe we're planning on formally releasing v1.2.3 sometime this week and it's probably unlikely we'll get a v1.2.4 before v1.3.0 is released.

**Comment by luhn** [comment] 2017-04-28 19:39
I'm eager to upgrade to 1.3, so personally I have no problem with not backporting it.

I'll probably try out the nightly build in the meantime.  Any idea when 1.3 will be released?

**Comment by jsternberg** [comment] 2017-05-01 15:22
I would expect 1.3 to land sometime in June. No promises, but that's the current estimated timeframe. Keep an eye out for the release candidate!

**Closed by jsternberg** 2017-05-01 15:22 UTC
