### ISSUE TITLE
UI: variables in UI show up after being deleted

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#18483] opened 2020-06-12 15:27 UTC
![image](https://user-images.githubusercontent.com/17263167/84518450-9645b500-ac85-11ea-8a74-d7f24cdf9937.png)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a variable via a template and grab the stack ID 
   ```INFLUX_OUTPUT_JSON=true influx apply -f pkger/testdata/variables.yml --org-id $ORG_ID``` 
   note: this outputs only the stackID
2. load up UI and go to variables list page under settings
3. delete the stack by the ID provided above `influx stacks rm --stack-id $STACK_ID --org-id $ORG_ID`
4. refresh page of UI, variables show up in view, but not in response from server

__Expected behavior:__
To show the response from server

__Actual behavior:__
Looks to provide some cached data

__Environment info:__

System: Darwin 18.7.0 x86_64
Browser: FF

**Comment by desa** [comment] 2020-06-23 21:13
Confirmed with @jsteenb2 that this happens despite a call to the API being made and it returning no results.

**Comment by zoesteinkamp** [comment] 2020-07-16 15:59
the new commands would be

NFLUX_TOKEN=token
INFLUX_ORG_ID=orgid go run ./cmd/influx  stacks rm --stack-id STACK_ID

NFLUX_TOKEN=token
INFLUX_ORG_ID=orgid go run ./cmd/influx apply --skip-verify  -f pkger/testdata/variables.yml

**Comment by 121watts** [comment] 2020-11-02 17:55
this might have been fixed with the recent changes.

**Comment by zoesteinkamp** [comment] 2020-11-09 23:35
im going to go ahead and take a look at this, see if i can recreate the original issue

**Comment by zoesteinkamp** [comment] 2020-11-20 22:41
Can confirm this is now fixed! yay! Im going to delete the branch and close this issue

**Comment by russorat** [comment] 2021-02-08 17:09
To repro easily:
1. load https://github.com/influxdata/community-templates/blob/master/linux_system/linux_system.yml template in your instance
2. Click to the variables page to see the variables
3. load https://github.com/influxdata/community-templates/blob/master/raspberry-pi/raspberry-pi-system.yml into your instance
4. Click the variables page to see the variables with additional labels
5. On the templates page, delete the rasberry pi template
6. Click back to the variables page to see the variables are still there but no labels
7. refresh the page and see that the variables disappear.

the expected behavior is that after deleting the rasberry pi template and clicking on the variables page, no variables are displayed.

**Comment by joelfried** [comment] 2021-02-11 20:13
Been digging into this some and this seems like a distinct variables bug not due to caching.  If the user adds any two variables to their system the steps above will work properly.  I've attached a video showing that the bug is not reproducible with two variables added (foo and bar - each was hard coded to a value of "1" but I don't think their contents matter) but by deleting those two variables so that there are no other variables in the system the behavior then occurs as described above.

https://user-images.githubusercontent.com/22055730/107692764-476c7700-6c7b-11eb-8aa6-599525da4fc2.mp4

**Comment by russorat** [comment] 2021-02-11 21:09
the API request to the `/variables` endpoint that happens when you click between tabs does not contain those variables after they have been deleted, yet they still show up in the UI. that feels like a UI state caching issue thingy to me. The api is returning the correct information.

**Comment by joelfried** [comment] 2021-02-11 21:14
That is true but if you have two or more variables that will be left on the variables tab after your deletions are complete, they do disappear correctly (See around 0:50 of the video).  If it were purely caching it wouldn't matter what other data was also cached alongside it.

**Comment by russorat** [comment] 2021-03-09 21:05
Could you attach the PR this is fixed in?

**Comment by ShmuelLotman** [comment] 2021-03-11 15:32
Fixed in the following (merged) PR: https://github.com/influxdata/ui/pull/702

**Closed** 2021-03-12 19:21 UTC
Labels: area/templates, kind/bug, severity/sev-4, team/ui
