### ISSUE TITLE
UI throws exception for notification endpoint

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16218] opened 2019-12-12 22:08 UTC
Steps: 
1. create a notification endpoint via the API 
2. acccess the alerts list page

![image](https://user-images.githubusercontent.com/17263167/70752810-3bd49780-1ce8-11ea-8b34-25cc034257a6.png)

![image](https://user-images.githubusercontent.com/17263167/70752990-9ff75b80-1ce8-11ea-9744-85ff1e2d6eb8.png)

![image](https://user-images.githubusercontent.com/17263167/70753031-b3a2c200-1ce8-11ea-91e5-1d9dd8383554.png)

This is experienced when using pkger.

**Comment by drdelambre** [comment] 2020-02-19 21:19
can you try reproing this one @jsteenb2? we changed a lot of code in that area, and idk how to create an endpoint via api.

**Comment by Asalem1** [comment] 2020-03-05 23:32
There are pkgs in the influxdb codebase that can be used to reproduce this.
`run influx pkg -f $influxdb/pkger/testdata/notification_endpoints.yml` and specify your `org` and it should work

**Comment by Asalem1** [comment] 2020-06-09 21:07
Did a walkthrough with @jsteenb2 and it looks like this is no longer an issue so I'm gonna go ahead and close it

**Closed by Asalem1** 2020-06-09 21:07 UTC
Labels: kind/bug, severity/sev-3, team/monitoring
