### ISSUE TITLE
engine: error syncing wal [1.5.0]

### ISSUE THREAD

**Issue by jimaek** [influxdata/influxdb#9544] opened 2018-03-10 17:40 UTC
### Bug report

__System info:__  Influx 1.5.0, centos 7.4 

__Expected behavior:__ No errors

__Actual behavior:__ 
error in logs
```
 msg="Write failed" log_id=06l6Q99G000 service=write shard=256 error="engine: error syncing wal"

```

__Additional info:__ Every hour at 02 minutes I get the following output in logs https://gist.github.com/jimaek/987355f99b5c5137fd586004105a04e9
The shard number changes everytime.

[iostat.txt](https://github.com/influxdata/influxdb/files/1799619/iostat.txt)
[profiles.tar.gz](https://github.com/influxdata/influxdb/files/1799620/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/influxdb/files/1799621/vars.txt)

**Comment by e-dard** [comment] 2018-03-12 16:21
@jwilder ^^

**Comment by jimaek** [comment] 2018-03-12 19:00
Now it seems to be happening at random. It happened at 18:05 but didn't the hour before that. Not sure what is the logic here.

**Comment by jwilder** [comment] 2018-03-12 19:17
@jimaek Can you describe your disk setup?  Are you using a direct attached SSD, HDD, etc..?  Is there a RAID configuration in the mix?  What other processes are running on the host?

That errors hints at your disk being saturated for a period of time.  If you can grab some profiles when the error is occurring that would be helpful.

**Comment by jimaek** [comment] 2018-03-12 19:30
Dedicated server with directly attached SSD in software raid 1.
No other processes, its dedicated to influx.

Its almost impossible to run a profile during the error as it happens only for 1 second or so

**Comment by jwilder** [comment] 2018-03-12 19:42
Can you run `iostat -xzt 1` and collect the output for a while?  When you see the error, we can look at the disk utilization around the time of the error and see if disk saturation is the likely cause or not.

**Comment by jimaek** [comment] 2018-03-12 20:07
I managed to do it. 
Error log https://gist.github.com/jimaek/e49648166d0d5d4311373b3d5147a05e
iostat attached
[test.txt.gz](https://github.com/influxdata/influxdb/files/1804371/test.txt.gz)

**Comment by jimaek** [comment] 2018-03-12 20:09
This is the server where its running https://www.hetzner.com/dedicated-rootserver/px91-ssd

**Comment by jwilder** [comment] 2018-03-12 21:40
@jimaek It does look like your disks are saturated during the time of these errors.

The errors are logged at `Mar 12 21:05:27`.  About 5 seconds before up til this time `sda` and `sdb` approach and hit 100% utilization (last column).  What is strange is that at this time the IOPS are around 400-500 which is not much for an SSD.  Then at `03/12/2018 09:05:28 PM` (1 second after the errors),  utilization drops down to ~30% and IOPS are in the 2000-5000 range which is more consistent with SSD performance.  

* There may be something going on w/ the RAID 1 configuration you have.  RAID setups have generally caused problems with the the DB and we don't recommend them.  You may want to check any logs for your RAID setup to see if errors are reported.  
* I'm not sure what your write volume is, but if you have a lot of concurrent, small writes, it's possible that could be causing issues.  You might be able to experiment w/ setting `wal-fsync-delay = "10ms"` to see if that helps or not.
* I saw a CQ had just finished at the beginning of the logs.  It's possible the CQ is thrashing the page cache by having to read a lot of data off disk.  Perhaps disable the CQ that ran, or all CQs via `[continous_queries] enabled = false` and see if that is the cause.  If so, you may need to add IOPS, RAM or rework the CQs.

I'm going to close this because the error logged indicates that we timed out waiting for the wal to `fsync` and a write error is returned to the client.  The error is due to the disks being saturated which I can only speculate what the root cause might be now.

```
03/12/2018 09:05:22 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           8.38    0.00    2.35    9.72    0.00   79.55

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00   123.00    0.00  707.00     0.00 257167.00   727.49    98.46  117.37    0.00  117.37   1.32  93.20
sda               0.00   123.00    1.00  713.00     4.00 260239.00   728.97    94.69  112.20   62.00  112.27   1.30  92.70
md2               0.00     0.00    2.00  907.00     8.00 323208.00   711.15     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:23 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.55    0.00    0.92    9.74    0.00   82.79

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00    0.00  365.00     0.00 185859.00  1018.41    99.90  268.99    0.00  268.99   2.74 100.00
sda               0.00     0.00    2.00  430.00     8.00 218627.00  1012.20    73.68  204.31   57.50  204.99   2.10  90.80
md2               0.00     0.00    1.00  456.00     4.00 233472.00  1021.78     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:24 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.72    0.00    1.09   10.99    0.00   80.20

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00    0.00  343.00     0.00 174082.00  1015.06   117.04  334.46    0.00  334.46   2.92 100.00
sda               0.00     0.00    1.00  357.00     4.00 181762.00  1015.45    29.70   74.15   59.00   74.19   1.78  63.90
md2               0.00     0.00    1.00  304.00     4.00 155648.00  1020.67     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:25 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.91    0.00    1.01   12.23    0.00   79.85

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00    0.00  363.00     0.00 185346.00  1021.19   122.35  328.02    0.00  328.02   2.75 100.00
sda               0.00     0.00    2.00  367.00     8.00 186882.00  1012.95    24.98   76.24   58.50   76.33   1.80  66.40
md2               0.00     0.00    2.00  304.00     8.00 155648.00  1017.36     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:26 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.80    0.00    1.17   11.91    0.00   79.11

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00    0.00  346.00     0.00 175619.00  1015.14   116.74  364.38    0.00  364.38   2.89 100.00
sda               0.00     0.00    1.00  329.00     4.00 167427.00  1014.73    44.35  121.97   49.00  122.19   2.19  72.40
md2               0.00     0.00    1.00  456.00     4.00 233472.00  1021.78     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:27 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.72    0.00    1.43   12.85    0.00   78.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00    22.00    0.00  553.00     0.00 279311.00  1010.17   128.22  233.40    0.00  233.40   1.81 100.00
sda               0.00    22.00    2.00  550.00     8.00 276343.00  1001.27    61.71  119.22   63.00  119.42   1.80  99.40
md2               0.00     0.00    2.00  398.00     8.00 189812.00   949.10     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:28 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          11.12    0.00    3.29    3.37    0.00   82.22

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00  1817.00    0.00 4254.00     0.00 53877.00    25.33     4.51    4.03    0.00    4.03   0.08  32.00
sda               0.00  1817.00    0.00 4185.00     0.00 19981.00     9.55     0.18    0.04    0.00    0.04   0.04  18.30
md2               0.00     0.00    0.00 4960.00     0.00 19984.00     8.06     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:29 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          10.30    0.00    1.84    4.61    0.00   83.25

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00   841.00    0.00 1750.00     0.00  8716.00     9.96     0.59    0.34    0.00    0.34   0.34  58.80
sda               0.00   841.00    0.00 1750.00     0.00  8716.00     9.96     0.08    0.05    0.00    0.05   0.05   8.00
md2               0.00     0.00    0.00 2152.00     0.00  8712.00     8.10     0.00    0.00    0.00    0.00   0.00   0.00

03/12/2018 09:05:30 PM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          14.55    0.00    2.17    0.75    0.00   82.53

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00  1311.00    0.00 2853.00     0.00 14217.00     9.97     0.13    0.05    0.00    0.05   0.05  13.40
sda               0.00  1311.00    0.00 2854.00     0.00 14221.00     9.97     0.13    0.05    0.00    0.05   0.05  13.30
md2               0.00     0.00    0.00 3453.00     0.00 14228.00     8.24     0.00    0.00    0.00    0.00   0.00   0.00
```

**Closed by jwilder** 2018-03-12 21:40 UTC

**Comment by jimaek** [comment] 2018-03-13 08:53
We do get about 1000 writes per second of small data but the load is consistent. Why the error happens only once per hour? If its a setting somewhere then maybe I could lower it to happen every 30 minutes or so to even out the load?

**Comment by e-dard** [comment] 2018-03-13 10:12
@jimaek rather than 1,000 writes per second of small batches of data, consider batching them up into fewer, larger writes. Ideally batches of 10,000 points. This could help with your IO utilisation.

**Comment by jimaek** [comment] 2018-03-13 10:14
Not possible unfortunately. But it would be helpful if there was some kind of documentation on what config changes we could do to optimize Influx for our use-case.

**Comment by wangmh1** [comment] 2019-04-23 05:40
I also encountered the same problem，but IO reading and writing is no problem.
The following is the log information:
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2913a7b-6571-11e9-b34f-6c92bfa10808 316
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2913393-6571-11e9-b349-6c92bfa10808 499
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a28a1d1d-6571-11e9-af6f-6c92bfa10808 46956
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a28a1c06-6571-11e9-af6d-6c92bfa10808 46953
ts=2019-04-23T02:43:54.471624Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a290a57e-6571-11e9-b2d8-6c92bfa10808 10793
ts=2019-04-23T02:43:54.471721Z lvl=error msg="[500] - \"engine: error syncing wal\"" log_id=0Efsi~4G000 service=httpd
ts=2019-04-23T02:43:54.471767Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.471786Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2924622-6571-11e9-b414-6c92bfa10808 258
ts=2019-04-23T02:43:54.471853Z lvl=error msg="[500] - \"engine: error syncing wal\"" log_id=0Efsi~4G000 service=httpd
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a290a5c2-6571-11e9-b2d9-6c92bfa10808 10945
ts=2019-04-23T02:43:54.471879Z lvl=error msg="[500] - \"engine: error syncing wal\"" log_id=0Efsi~4G000 service=httpd
ts=2019-04-23T02:43:54.471921Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.471959Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.471922Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.471930Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2924d68-6571-11e9-b418-6c92bfa10808 208
ts=2019-04-23T02:43:54.472018Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2924ba6-6571-11e9-b416-6c92bfa10808 329
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2924e82-6571-11e9-b419-6c92bfa10808 211
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a290a731-6571-11e9-b2da-6c92bfa10808 11135
[httpd] 172.17.1.15 - - [23/Apr/2019:10:43:54 +0800] "POST /write?db=test HTTP/1.1" 500 38 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_181)" a2924f38-6571-11e9-b41a-6c92bfa10808 194
ts=2019-04-23T02:43:54.472016Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472278Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472285Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472321Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472337Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472352Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472324Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472337Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"
ts=2019-04-23T02:43:54.472409Z lvl=info msg="Write failed" log_id=0Efsi~4G000 service=write shard=30 error="engine: error syncing wal"

The following is the IO information:

2019年04月23日 10时43分45秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          18.18    0.00    4.50    0.41    0.00   76.92

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00 9077.00     0.00 36244.50     7.99     0.29    0.03    0.00    0.03   0.03  28.70
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    0.62    0.62    0.00   0.38   0.30

2019年04月23日 10时43分46秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          16.76    0.00    4.39    0.47    0.00   78.38

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    0.62    0.62    0.00   0.12   0.10
sda               0.00     0.00    0.00 10519.00     0.00 33030.50     6.28     0.29    0.03    0.00    0.03   0.03  29.30
sdd               0.00     0.00    0.00    2.00     0.00     5.00     5.00     0.00    0.00    0.00    0.00   0.00   0.00

2019年04月23日 10时43分47秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          14.88    0.00    4.36    0.50    0.00   80.25

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00 10705.00     0.00 33452.00     6.25     0.31    0.03    0.00    0.03   0.03  31.30
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.00    0.00    0.00    0.00   0.00   0.00

2019年04月23日 10时43分48秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          16.84    0.00    4.33    0.51    0.00   78.33

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    1.00    1.00    0.00   0.12   0.10
sda               0.00     0.00    0.00 10871.00     0.00 34000.00     6.26     0.31    0.03    0.00    0.03   0.03  31.40

2019年04月23日 10时43分49秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          14.90    0.00    4.33    0.47    0.00   80.29

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00 10430.00     0.00 35284.00     6.77     0.31    0.03    0.00    0.03   0.03  30.60
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.00    0.12    0.12    0.00   0.12   0.10

2019年04月23日 10时43分50秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.44    0.00    3.96    0.51    0.00   78.09

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.00    0.00    0.00    0.00   0.00   0.00
sda               0.00     0.00    0.00 11115.00     0.00 34629.00     6.23     0.32    0.03    0.00    0.03   0.03  31.50
sdb               0.00     0.00    1.00    0.00   128.00     0.00   256.00     0.00    1.00    1.00    0.00   1.00   0.10

2019年04月23日 10时43分51秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          18.59    0.00    3.56    0.35    0.00   77.50

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00 7981.00     0.00 33145.50     8.31     0.24    0.03    0.00    0.03   0.03  24.20
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    1.00    1.00    0.00   0.12   0.10

2019年04月23日 10时43分52秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          21.22    0.00    4.41    0.38    0.00   73.99

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00 8519.00     0.00 53438.00    12.55     0.29    0.04    0.00    0.04   0.03  26.80

2019年04月23日 10时43分53秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          19.97    0.00    4.86    0.44    0.00   74.72

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    1.38    1.38    0.00   0.50   0.40
sda               0.00     0.00    0.00 9249.00     0.00 62951.50    13.61     0.34    0.04    0.00    0.04   0.03  29.90
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    1.00    1.00    0.00   0.25   0.20

2019年04月23日 10时43分54秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          19.94    0.00    4.37    0.54    0.00   75.15

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    1.00    0.00   128.00     0.00   256.00     0.00    4.00    4.00    0.00   4.00   0.40
sda               0.00     0.00    0.00 11202.00     0.00 60943.50    10.88     0.36    0.03    0.00    0.03   0.03  35.10

2019年04月23日 10时43分55秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          24.14    0.00    4.14    0.35    0.00   71.37

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    0.62    0.62    0.00   0.12   0.10
sda               0.00     0.00    0.00 7916.00     0.00 77102.50    19.48     0.35    0.04    0.00    0.04   0.04  28.80
sdb               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    0.75    0.75    0.00   0.12   0.10

2019年04月23日 10时43分56秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          24.16    0.00    4.23    0.44    0.00   71.17

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    0.00    1.00     0.00     4.00     8.00     0.00    0.00    0.00    0.00   0.00   0.00
sda               0.00     0.00    0.00 9702.00     0.00 81664.00    16.83     0.36    0.04    0.00    0.04   0.03  29.60

2019年04月23日 10时43分57秒
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          22.38    0.00    4.22    0.44    0.00   72.96

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdc               0.00     0.00    8.00    0.00  2048.00     0.00   512.00     0.01    1.62    1.62    0.00   0.75   0.60
sda               0.00     1.00    0.00 9100.00     0.00 105561.00    23.20     0.43    0.05    0.00    0.05   0.03  29.80

 %util does not reach 100%
