### ISSUE TITLE
Modify default query end time

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#6680] opened 2016-05-19 16:58 UTC
Running queries without specifying time boundaries will use now() as the default end time.
Consider changing default end time from now() to something like MaxInt in order for the query engine to retrieve all timestamps when no time boundaries are specified.

Related deprecated PR:  https://github.com/influxdata/influxdb/pull/5089

**Comment by beckettsean** [comment] 2016-05-20 16:28
duplicate of #4461

**Closed by beckettsean** 2016-05-20 16:28 UTC
Labels: category/queries
