### ISSUE TITLE
Request for aarch64 (arm64) docker container for 2.0.0 beta

### ISSUE THREAD

**Issue by jsrz** [influxdata/influxdb#18202] opened 2020-05-22 15:56 UTC
__Proposal:__
Please create a quay.io/influxdb/influxdb:2.0.0-beta docker image that works on aarch64 (arm64). Ideally with the same tag as the current image (2.0.0-beta) so that things can be architecture agnostic.

__Current behavior:__
Running the current beta on an Arm machine (AWS M6g) I see the following:

```
$ docker run quay.io/influxdb/influxdb:2.0.0-beta
standard_init_linux.go:211: exec user process caused "exec format error"
```

__Desired behavior:__
The desired behavior is for influxd to startup in the container.

__Alternatives considered:__
I've built the Arm binaries, and built a container myself, and it works. However, we'd want Arm users to be able to just run the container and not go through the trouble of building a container themselves.

__Use case:__
Arm is gaining more adoption in the cloud. For example, the AWS A1 and M6g instances are Arm based instances. This would also help developers on smaller single board systems like the Raspberry Pi.

**Comment by mildebrandt** [comment] 2020-07-14 21:35
The arm AWS instance types are 20%-40% cheaper than the equivalent x86 instances....this would be great to make it easier to migrate over.

**Comment by pcgeek86** [comment] 2020-10-30 16:11
Keep in mind that Raspberry Pi OS still doesn't have a production release for 64-bit. As of today, they're still in preview. Hence, I would request that this issue be expanded to include 32-bit (arm32v7) ARM container images.

**Comment by danxmoran** [comment] 2020-12-15 15:08
@jsrz @mildebrandt we're still working on setting up official Docker images for ARM64, but in the meantime...

The InfluxDB 2.0.3 release includes an updated ARM64 build. You can download the binaries and use them to build your own image: https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.3_linux_arm64.tar.gz

Please let me know how it goes if you try it out!

**Comment by danxmoran** [comment] 2020-12-15 15:10
@pcgeek86 if you're still hoping for arm32v7 support, could you open a separate issue? It'll help us make sure we don't lose anything while tracking & prioritizing issues.

**Comment by danxmoran** [comment] 2021-01-05 22:55
Duplicate of #17840

**Comment by danxmoran** [comment] 2021-01-11 18:54
@jsrz @mildebrandt I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machines and let me know how it goes?

**Comment by jsrz** [comment] 2021-01-11 19:38
Hello, I gave the nightly a try. Only had time to do manual influx write/query. It worked on my Arm64 machine!

**Comment by mildebrandt** [comment] 2021-01-11 20:11
Julio is a lot faster than I am. It'll be a couple days before I can give it a try. Given his initial poke at it, sounds like a potential winner.

**Comment by dbuos** [comment] 2021-01-29 23:12
> @jsrz @mildebrandt I'm testing out our Docker cross-build and manifest setup. If you're still interested, could you try pulling `quay.io/influxdb/influxdb:nightly` on your arm64 machines and let me know how it goes?

It works like a charm in my Graviton2 k8s cluster on AWS, thanks a lot @danxmoran, I'm looking forward for the stable version.

**Comment by danxmoran** [comment] 2021-02-08 18:14
`quay.io/influxdb/influxdb:v2.0.4` is now live. It should resolve correctly to the ARM64 build when you `docker pull`

**Closed by danxmoran** 2021-02-08 18:14 UTC
Labels: arch/arm, area/2.x, area/docker, area/packaging
