### ISSUE TITLE
[feature request] Filter based on aggregation

### ISSUE THREAD

**Issue by eliperelman** [influxdata/influxdb#4381] opened 2015-10-09 03:31 UTC
All the issues that were previously raised on this subject appeared to be closed, so I'm not sure what the state of it was, but I thought I would raise it just to be safe.

It would be nice to filter based on an aggregation, my use case being:

`SELECT mean(value) FROM series WHERE count(value) = 30`

Basically only collect these numbers where we have enough values for it to be significant.

**Comment by ewildgoose** [comment] 2015-10-09 13:44
In SQL you would use WHERE as the "filter" for rows into an aggregation, GROUP BY for the aggregation and HAVING as a filter on the aggregation output

So your proposal is basically to introduce a "HAVING count(value) > 30" or similar

No opinion on this, but perhaps this widens/clarifies the scope of what you are asking?

In the meantime, I *think* you need to do this using continuous queries, this seems to be the only way to do nested queries at present. So you would "SELECT mean(xx), count(xx)..." and then filter that result on the count column.

**Comment by ShijunK** [comment] 2016-04-28 13:20
Yes, something like SQL Having clause will be very helpful. When working with large data set and try to pick up out liner, even with existing tools like group by, aggregation function, still tons of results.

**Comment by jsternberg** [comment] 2016-05-17 23:51
This is a duplicate of #5266. I'm going to close this in favor of that issue.

**Closed by jsternberg** 2016-05-17 23:51 UTC
Labels: category/feature request
