### ISSUE TITLE
Dashboard list view exception fails to load all dashboards

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#15455] opened 2019-10-17 18:18 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a label that is associated with a dashboard and do not add properties to the label (done through API in my case)
2. load up the dashboards list page in the UI
3. observe that no dashboards will render b/c of an exception getting thrown
4. exception is found [here](https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/inlineLabels/InlineLabels.tsx#L68)

__Expected behavior:__
Dashboard list view to populate with my dashboards

__Actual behavior:__
![image](https://user-images.githubusercontent.com/17263167/67035887-654dba00-f0cf-11e9-8213-607697ba5b38.png)

__Environment info:__

* System info: Run `Darwin 18.7.0 x86_64
* InfluxDB version: 2.0

__Config:__
- basic

__Logs:__
UI exception:

```
TypeError: "e.properties is undefined"
    get currentLabels/< InlineLabels.tsx:68
    get currentLabels InlineLabels.tsx:63
    get selectedLabels InlineLabels.tsx:46
    render InlineLabels.tsx:37
    render errors.tsx:41
    React 11
    Redux 14
    x queryStringConfig.ts:10
    h resizeLayout.ts:7
    Redux 3
    getLabels index.ts:82
backend.js:6:2315
```

**Comment by desa** [comment] 2019-10-17 18:21
Components should gracefully handle malformed data.

**Comment by ebb-tide** [comment] 2019-10-17 19:05
In this case, labels created through the API do not contain the properties required by the UI. This isn't really an issue with components failing gracefully or not, but the flexibility we've allowed the API vs the requirements of the UI. The underlying reason for this issue is that the oats generated client doesn't include the "apply defaults to labels" step that we had in the other client.

**Comment by desa** [comment] 2019-10-17 20:45
> This isn't really an issue with components failing to fail gracefully, but a conflict between the flexibility we've allowed the API vs the requirements of the UI.

Totally agree. However, we shouldn't crash the component just because that data that comes back isn't valid.

**Comment by ebb-tide** [comment] 2019-10-23 23:21
issue #15554 is also caused by not applying defaults to labels.

**Comment by ebb-tide** [comment] 2020-01-13 18:37
@121watts would you mind checking whether this might be fixed by the labels service layer

**Comment by 121watts** [comment] 2020-01-13 18:47
@ebb-tide this should get taken care of when i normalize dashboards and labels.  feel free to patch it now though

**Closed** 2020-01-24 17:14 UTC
Labels: kind/bug, team/monitoring
