### ISSUE TITLE
InfluxDB 0.11.0 RC breaks windows completely

### ISSUE THREAD

**Issue by mvadu** [influxdata/influxdb#6042] opened 2016-03-17 02:48 UTC
Up until last week master branch was compatible with windows (e.g. PR #5999), but now 0.11.0RC breaks basic `create database` itself, and is not compatible with Windows. Going by #5359 you are still [committed to providing windows support by 0.11 ](https://github.com/influxdata/influxdb/issues/5359#issuecomment-183142936)), and this is back pedaling.

```go
[monitor] 2016/03/17 08:11:04 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:04 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:14 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:14 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:24 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:24 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:34 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:34 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:44 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:44 failed to store statistics: database not found: _internal
[monitor] 2016/03/17 08:11:54 failed to create database '_internal', failed to create storage: rename influxdb\meta\meta.dbtmp influxdb\meta\meta.db: Cannot create a file when that file already exists.
[monitor] 2016/03/17 08:11:54 failed to store statistics: database not found: _internal
```

![image](https://cloud.githubusercontent.com/assets/8618235/13834863/7afe1bd4-ec18-11e5-8f30-ea11b503ecbd.png)

**Comment by e-dard** [comment] 2016-03-17 16:01
Appears to be duplicate of #6030

**Closed** 2016-03-18 17:13 UTC
