### ISSUE TITLE
nested or sub query support

### ISSUE THREAD

**Issue by lukebigum** [influxdata/influxdb#6218] opened 2016-04-05 15:16 UTC
This is a feature request / discussion about if it's even feasible to do nested or "sub" queries.

I have a use case where I would like to combine several different series (in different measurements and with different tags) into one "value" with one query (or nested query). I would then be able to display this one single value in existing dashboards like Chronograf or Grafana.

As an example to explain why this might be useful, imagine several machines as part of a complex system reporting transaction latency, where a transaction crosses three servers: A -> B -> C. Each of these metrics is a collected into a different series. What would be nice is single query to show the total latency of the transaction. Doing this in (normal) SQL would look something like:

```
SELECT A.value + B.value + C.value AS total_latency
FROM (SELECT value from SeriesA) AS A,
(SELECT value from SeriesB) AS B,
(SELECT value from SeriesC) AS C
```

Of course such a feature would probably add a lot of complexity to InfluxDB, and moves it a little more towards it being a data processing engine, so I can understand if you don't want to consider such a feature.

The workaround is to use some external App / Script to do the three queries independently and munge the data together to get the total result. That makes it a lot harder to add into pretty dashboards though.

**Comment by jsternberg** [comment] 2016-04-05 22:31
This seems to be a duplicate of #4619. I'm going to close this in favor of the other request, although the syntax you have proposed would roughly be similar to the syntax we would use.

Thanks!

**Closed by jsternberg** 2016-04-05 22:31 UTC
