### ISSUE TITLE
0.9.6.1 crashed

### ISSUE THREAD

**Issue by matwey** [influxdata/influxdb#5276] opened 2016-01-05 20:39 UTC
Hello,

influxdb has just crashed. I suppose this is due to bad query

`select (value) from ...`

This is reproducible. From logs I see the following:

```
янв 05 23:32:46 eagle influxd[1859]: [query] 2016/01/05 23:32:46 SELECT (value) FROM taxandria."default"."massdimm.seeing"
янв 05 23:32:46 eagle influxd[1859]: panic: interface conversion: interface {} is float64, not map[string]interface {}
янв 05 23:32:46 eagle influxd[1859]: goroutine 67566 [running]:
янв 05 23:32:46 eagle influxd[1859]: github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc820132000, 0xc8203f8000, 0xbb
янв 05 23:32:46 eagle influxd[1859]: /home/abuild/rpmbuild/BUILD/go/src/github.com/influxdb/influxdb/tsdb/raw.go:524 +0x14be
янв 05 23:32:46 eagle influxd[1859]: github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc820132000)
янв 05 23:32:46 eagle influxd[1859]: /home/abuild/rpmbuild/BUILD/go/src/github.com/influxdb/influxdb/tsdb/raw.go:446 +0xb5
янв 05 23:32:46 eagle influxd[1859]: github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc8200c29c0, 0xc82026b9e0, 0xc82026b6e0)
янв 05 23:32:46 eagle influxd[1859]: /home/abuild/rpmbuild/BUILD/go/src/github.com/influxdb/influxdb/tsdb/raw.go:143 +0x52b
янв 05 23:32:46 eagle influxd[1859]: created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
янв 05 23:32:46 eagle influxd[1859]: /home/abuild/rpmbuild/BUILD/go/src/github.com/influxdb/influxdb/tsdb/raw.go:59 +0x67
янв 05 23:32:46 eagle influxd[1859]: goroutine 1 [chan receive, 4691 minutes]:
янв 05 23:32:46 eagle influxd[1859]: main.(*Main).Run(0xc820055f10, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
янв 05 23:32:46 eagle influxd[1859]: /home/abuild/rpmbuild/BUILD/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0xa39
```

**Comment by beckettsean** [comment] 2016-01-06 08:59
duplicate of https://github.com/influxdata/influxdb/issues/5189

**Closed by beckettsean** 2016-01-06 08:59 UTC
