### ISSUE TITLE
[0.10.0] Cluster losing data on restart

### ISSUE THREAD

**Issue by scarhand** [influxdata/influxdb#5817] opened 2016-02-24 06:33 UTC
### Description
When running an influx cluster influx seems to lose some data when the cluster is fully restarted. Previously created databases can not be found. Recreating the database and inserting some new data brings back (some of) the old data.

We are running an influx cluster of three nodes, two data/meta nodes and a meta node, in docker containers. If we restart the entire cluster, influx can't remember which databases it had. The data is obviously also not available. 

## Steps to reproduce
The problem is fairly easy to reproduce.
- Create a cluster of 3 nodes
- Create a database
- Insert some data
- Wait for a few minutes
- Take the cluster down
- Recreate the cluster
After the cluster has started for the second time, the created database and its data seem to be gone.
If we then recreate the database and insert some new data in it, the old data is available again.

Data that is somehow considered too old will be lost forever.

For convenience I have created a set of scripts that will do all of the above.
To reproduce, check out the repo and run run.sh.
```
$ git clone git@github.com:scarhand/influx-cluster-losing-data.git
$ cd influx-cluster-losing-data
$ ./run.sh
```

When the script is running, or has finished, the influx logs for each instance can be retrieved by running `docker logs influx-node-1`, `docker logs influx-node-2` and `docker logs influx-node-3`. 
The script does not automatically shutdown the containers at the end. To stop the containers run `stop.sh`. This does stop and remove the containers, thus losing the logs.

### Software versions

Influx: 
- Installed from apt repository
- version 0.10.0
- branch 0.10.0
- commit b8bb32ecad9808ef00219e7d2469514890a0987a
- built 2016-02-04T17:06:04.850564

Host:
- Ubuntu 15.10
- Linux 4.2.0-27-generic x86_64

Docker:
- version 1.10.2
- build c3959b1

Docker image:
- debian:jessie

**Comment by e-dard** [comment] 2016-02-24 14:51
@scarhand thanks so much for the detailed report!

Unfortunately I'm unable to reproduce this. I've tested the approach locally using a 3-node cluster with the `0.10` release.

Here's my steps (I used the CLI client):

 - start three data/meta nodes;
 - create `mydb` on node 1;
 - insert the four points from your script;
 - select `*` from `cpu_load_short` on all the nodes. Each node returns correct data;
 - shutdown each `influxd` process. Wait couple of minutes.
 - bring up each process, wait few seconds for consensus to be formed etc.
 - run `show servers` to confirm everything is back;
 - run `select * from cpu_load_short` on any node, all data is present.
 - run `insert cpu_load_short,host=server_extra value=0.42` on a node.
 - run `select * from cpu_load_short` on any node, all data is present.

Could you try and reproduce without using Docker? At the moment I'm inclined to think this might be a Docker/network configuration error somewhere.

**Comment by tinco** [comment] 2016-02-24 15:24
Hi @e-dard thanks for trying to reproduce this. It might very well be some kind of incompatibility with Docker. Reproducing it outside Docker is however not very useful to us as we will not run influx outside a docker container.

Are you familiar with the influx source? Do you perhaps know of how it the situation could arise where influx starts with data in its directory, but does not expose it to queries until it has written data itself? Would this be a weird replication state? A failure of finding the shard? (I noticed that without sharding influxdb internally puts everything on a single shard) Some missing metadata that gets created upon insert?

**Comment by e-dard** [comment] 2016-02-24 15:39
Hi @tinco. The first thing to say is that clustering is at a very early state in `0.10`, and with the `0.11` release we expect to have it in a more stable state. However, for fully replicated clusters, your use-case of inserting some points and querying them from any node works in `0.10`.

> Do you perhaps know of how it the situation could arise where influx starts with data in its directory, but does not expose it to queries until it has written data itself? 

This could happen if the data node does not know about the databases in the cluster. Each node first checks the meta nodes for databases, and then caches the result. I wonder if you actually have a problem with meta nodes sharing the snapshots.

Would it be possible to attach the three docker container logs?

**Comment by scarhand** [comment] 2016-02-24 16:55
Please see attached log files. *.first.txt is from the first run. *.second.txt is from the second run.

[influx-node-1.first.txt](https://github.com/influxdata/influxdb/files/145047/influx-node-1.first.txt)
[influx-node-1.second.txt](https://github.com/influxdata/influxdb/files/145051/influx-node-1.second.txt)
[influx-node-2.first.txt](https://github.com/influxdata/influxdb/files/145052/influx-node-2.first.txt)
[influx-node-2.second.txt](https://github.com/influxdata/influxdb/files/145050/influx-node-2.second.txt)
[influx-node-3.first.txt](https://github.com/influxdata/influxdb/files/145049/influx-node-3.first.txt)
[influx-node-3.second.txt](https://github.com/influxdata/influxdb/files/145048/influx-node-3.second.txt)

**Comment by e-dard** [comment] 2016-02-24 17:40
@scarhand thanks for these. I noticed in your second container runs the line `Cleaning meta dir`. I dug around your repo a bit and see that you're deleting the `/data/meta` folder when restarting the nodes. That doesn't seem like a sensible thing to do!

**Comment by e-dard** [comment] 2016-02-24 17:44
@scarhand when I bring all the nodes down and delete the meta folders, then bring them back up I get similar behaviour, so that solves that. :smile:

**Comment by scarhand** [comment] 2016-02-24 18:59
@e-dard The meta dir is being deleted to 'solve' another problem. Influx won't start if it can't find the nodes listed in peers.json and nodes.json. Since the clustering uses raft, I assumed that the raft.db was also used for clustering. The snapshots dir was empty, so the easiest solution was to completely delete the meta-dir.

If the cluster somehow goes down and only one node restarts it can't fully startup because it can't find any of the other nodes. When the meta dir is empty, or there is no meta-dir, it can start up.

I've just tested some scenarios. By removing only the .json files I can restart the cluster with all the data intact.  
Not removing the .json files en starting a single node causes the node to hang.

Are these issues resolved in the upcoming releases?

**Comment by e-dard** [comment] 2016-02-24 19:05
@scarhand yes they are. There are some big improvements to clustering coming in `0.11`. While it will take some rejigging in terms of configuration file, I would encourage you to try nightly releases to see the differences.

The main difference in terms of configuration with the current `master` branch is that you need to specify all the nodes in the `-join` args. So you might start a 3-node cluster as follows:

```bash
$ influxd -config /path/n1/config.toml -join hosta:8091,hostb:8091,hostc:8091
$ influxd -config /path/n2/config.toml -join hosta:8091,hostb:8091,hostc:8091
$ influxd -config /path/n3/config.toml -join hosta:8091,hostb:8091,hostc:8091
```

You should find however that you can a node process and restart it, and it will rejoin the cluster no problems.

We're still a few weeks away from the `0.11` release, but expect a beta of the next release in a couple of weeks.

I'm going to close this issue for now, but feel free to open another if you have any more issues.

**Closed by e-dard** 2016-02-24 19:05 UTC
