### ISSUE TITLE
Limit the number of appends made to 'influx_history' file

### ISSUE THREAD

**Issue by tokudan** [influxdata/influxdb#5436] opened 2016-01-24 21:26 UTC
I'm using an awk script to generate queries that feed into influx to back-fill continuous queries, something like:
./migrate.awk | influx
The result is that my $HOME/.influx_history grew to 40 GB, filling my filesystem to 100%.
I would have expected influx to only save the last e.g. 1000 lines at the end, not saving every single line.

Version: 0.9.6.1+dfsg1-4 (Debian unstable package)

**Comment by rossmcdonald** [comment] 2016-01-25 20:56
Yes, it looks like the current implementation is naive, simply appending on every parse:

https://github.com/influxdata/influxdb/blob/0.10.0/cmd/influx/cli/cli.go#L191

Changing this to a feature request to add a limit to the number of appends.

**Comment by sczk** [comment] 2016-01-27 02:55
I've got a PR here that shows a proposed solution: https://github.com/influxdata/influxdb/pull/5460

Please ignore the notice about commit 7b2505d above, it's from an old fork that I deleted. 40e04d8 is correct and on the PR.

***

Influx is using the [Liner](https://github.com/peterh/liner) library for the ReadHistory / AppendHistory / WriteHistory functions.


**PROBLEM**: 
When the influx console is started, ReadHistory reads the entire buffer from ~/.influx_history into memory, for [up to 1000 lines](https://github.com/peterh/liner/blob/master/common.go#L65-L96). 

Each time a command is entered into the console, [AppendHistory](https://github.com/influxdata/influxdb/blob/0.10.0/cmd/influx/cli/cli.go#L191) is called. This appends to the history buffer we have in memory which has a [limit of 1000 entries](https://github.com/dbehnke/influxdb-gb/blob/4ee5f88c4f5233e3b98d7885e1347582aacdff70/vendor/src/github.com/peterh/liner/common.go#L62) as well. This call by itself is fine.

Now things start to get hairy. (WriteHistory)[https://github.com/influxdata/influxdb/blob/0.10.0/cmd/influx/cli/cli.go#L192] is called. Not only does this function ignore the HistoryLimit, but it appends the history buffer in memory to the file. Additionally, when exit() is issued, WriteHistory writes that entire buffer to ~/.influx_history again. You can see how this will cause the file to quickly grow exponentially...

**FIX**: On the [liner library example page](https://github.com/peterh/liner/), it looks like they open the historyFile with os.Open (read-only), and then attempt to re-create the file each time using os.Create() before WriteHistory is called. This prevents the growth problem by using WriteHistory as intended. I also modified the file open functions for Read/Write History and closed the files immediately after finished with them. I didn't see a need to use defer since the handles to the files are not re-used elsewhere.

**PROPOSED SOLUTION**: I've created a function called saveHistory that calls WriteHistory after clearing the ~/.influx_history file. I added historyFilePath to the CommandLine struct to make this easier. I replaced the calls to WriteHistory with my saveHistory function.

**Comment by rossmcdonald** [comment] 2016-01-27 23:16
Fixed by #5460. Thanks, @sczk!

**Closed by rossmcdonald** 2016-01-27 23:16 UTC
Labels: category/feature request, difficulty/low, status/help-wanted
