### ISSUE TITLE
Deleting not possible after upgrading to 2.0.3 OSS / unclear State of indexes

### ISSUE THREAD

**Issue by lephisto** [influxdata/influxdb#20633] opened 2021-01-28 13:29 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Take a 1.8 Instance and Migrate to 2.0.3
2. Continue writing into the bucket
3. Try deleting Data by tag (or any other --predicate

__Expected behavior:__
Data get's deleted

__Actual behavior:__
Data won't delete because InfluxDB v2.0.3 OSS complains about mixed index types:

`influx delete --bucket "telegraf/autogen" --predicate '_measurement="devax_forecast" AND type="forecast_erst"' -o Lalelu --start '1970-01-01T00:00:00Z' --stop $(date +"%Y-%m-%dT%H:%M:%SZ")
Error: Failed to delete data: unable to delete: cannot delete data. DB contains shards using both inmem and tsi1 indexes. Please convert all shards to use the same index type to delete data.: cannot delete data. DB contains shards using both inmem and tsi1 indexes. Please convert all shards to use the same index type to delete data.`

__Environment info:__

* System info: Linux 4.4.0-198-generic x86_64
* InfluxDB version: InfluxDB 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z
* Other relevant environment details: //

__Config:__
Pretty much default

InfluxDB V2.0.3 works normal after the Upgrade, just the deletion of Data within buckets that contain Data which was migrated from V1.8 is not Working. I couldn't find a function to convert all Indexes from inmem to tsi1.

**Comment by danxmoran** [comment] 2021-01-28 16:15
Duplicate of #20257

This is a known issue, to be fixed in 2.0.4. In the meantime, you could try using the 1.x `influx_inspect buildtsi` CLI command to generate missing indices (I haven't tried it myself, but the storage layout on disk is the same so it might Just Work).

**Comment by lephisto** [comment] 2021-01-28 23:51
> 
> 
> Duplicate of #20257
> 
> This is a known issue, to be fixed in 2.0.4. In the meantime, you could try using the 1.x `influx_inspect buildtsi` CLI command to generate missing indices (I haven't tried it myself, but the storage layout on disk is the same so it might Just Work).

This was a bit tricky since on debian based Systems the 1.x and 2.x packages don't coexist nicely. Had to just pull the binary from another 1.x Installation. Buildtsi ran fine, the delete works now, I can delete by Tag, however the Tag is still listed in "show tag values [..], but all records associated with it got deleted. How can I get rid of that tag?

**Comment by danxmoran** [comment] 2021-02-03 19:35
> however the tag value is still listed in "show tag values [..], but all records associated with it got deleted. How can I completely get rid of that tag?

That sounds like a bug in our delete-by-predicate implementation, I'll open a separate issue for it.

**Comment by danxmoran** [comment] 2021-02-03 21:29
@lephisto actually, could you open the issue for the tag not disappearing properly? I wasn't able to reproduce based on your description, but I want to be sure all the details are captured.

**Comment by lephisto** [comment] 2021-02-05 09:42
Will do so.

**Comment by danxmoran** [comment] 2021-02-05 15:53
Thanks! Closing this one, then

**Closed by danxmoran** 2021-02-05 15:53 UTC
Labels: area/2.x, area/storage
