### ISSUE TITLE
v0.10.0 PANIC

### ISSUE THREAD

**Issue by rafaelvittoruthes** [influxdata/influxdb#5908] opened 2016-03-04 13:58 UTC
After running some queries, the cluster went down.

[cluster] 2016/03/04 10:51:38 accept remote connection from 10.41.9.72:45833
[cluster] 2016/03/04 10:51:38 close remote connection from 10.41.9.72:45833
[tsm1wal] 2016/03/04 10:51:38 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/04 10:51:38 tsm1 WAL writing to /var/lib/influxdb/wal/teste/default/24
[cluster] 2016/03/04 10:51:38 close remote connection from 10.41.9.72:36571
panic: runtime error: index out of range

goroutine 933 [running]:
github.com/influxdb/influxdb/models.scanTo(0xc21460f0eb, 0x13, 0x22, 0x0, 0xc20843733d, 0x41d413, 0xc208437340, 0x410868, 0x7fb791228f68)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/models/points.go:892 +0xad
github.com/influxdb/influxdb/models.newFieldsFromBinary(0xc21460f0eb, 0x13, 0x22, 0xc208437350)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/models/points.go:1396 +0x10d
github.com/influxdb/influxdb/models.(*point).unmarshalBinary(0xc21350e5a0, 0xc216844920)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/models/points.go:1298 +0x3b
github.com/influxdb/influxdb/models.(*point).Fields(0xc21350e5a0, 0xc21460f8f0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/models/points.go:1211 +0x41
github.com/influxdb/influxdb/tsdb.(*Shard).validateSeriesAndFields(0xc20817edc0, 0xc20806e0b0, 0xb, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/shard.go:413 +0x7e5
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc20817edc0, 0xc20806e0b0, 0xb, 0xb, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/shard.go:202 +0xa6
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc2080842c0, 0x18, 0xc20806e0b0, 0xb, 0xb, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/tsdb/store.go:442 +0x14e
github.com/influxdb/influxdb/cluster.(*Service).processWriteShardRequest(0xc2080ac000, 0xc208178d80, 0x207, 0x207, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cluster/service.go:214 +0x4b1
github.com/influxdb/influxdb/cluster.(*Service).handleConn(0xc2080ac000, 0x7fb791220ca8, 0xc208088030)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cluster/service.go:162 +0x62a
github.com/influxdb/influxdb/cluster.func·003()
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cluster/service.go:112 +0x74
created by github.com/influxdb/influxdb/cluster.(*Service).serve
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cluster/service.go:113 +0x428

goroutine 1 [chan receive, 12628 minutes]:
main.(*Main).Run(0xc208039700, 0xc20800a010, 0x6, 0x6, 0x0, 0x0)
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7a1
main.main()
        /tmp/tmp.n7AHL1nb9U/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall, 12628 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x35

**Comment by jonseymour** [comment] 2016-03-04 14:19
This is a duplicate of #5664 which was fixed with #5716 in master, due for release in 0.11.0

The interim work around  on 0.10.x is to ensure that all columns of SELECT INTO statements used in continuous queries that have arithmetic expressions are assigned an explicit, non-blank, alias.

So instead of:

`select count(value)/60 into "summary" from "foobar" where time > now() - 1h group by time(5m)`

write:

`select count(value)/60 as **countDiv60** into "summary" from "foobar" where time > now() - 1h group by time(5m)
`

**Comment by jonseymour** [comment] 2016-03-04 14:22
BTW: if you want to build your own variant v0.10.2 that includes the fix, you can merge 9491846 into a branch based on the v0.10.2 tag.

**Comment by jonseymour** [comment] 2016-03-04 20:35
There is a PR ( #5911 ) available to have the fixes in #5716 merged into the 0.10.0 maintenance branch.

**Comment by rafaelvittoruthes** [comment] 2016-03-04 23:17
Thank you very much.
I'll patch the 0.10.0
Regards

Enviado do meu iPhone

**Comment by e-dard** [comment] 2016-03-07 11:14
Thanks for the report @rafaelvittoruthes. I'm going to close this as the issue should be resolved. Please re-open or open a new issue if you have any other problems.

**Closed by e-dard** 2016-03-07 11:14 UTC
