### ISSUE TITLE
how 2 get version in v2.x

### ISSUE THREAD

**Issue by live-xy** [influxdata/influxdb#14166] opened 2019-06-20 02:01 UTC
In  Influx db 1.x ,
we can get version through `/ping `

but in 2.x 
it doesn't works 
and `/healthy` doesn't return version .... 

so...
anyway to get version of 2.x ?
or `ping` would works in next version ? 

thx !

**Comment by bednar** [comment] 2019-06-20 07:07
This bug is duplicate of https://github.com/influxdata/influxdb/issues/13907.

**Closed** 2019-06-25 23:21 UTC
Labels: duplicate
