### ISSUE TITLE
Variable Template Query Tag Values does not work for each bucket

### ISSUE THREAD

**Issue by cmd-influx** [influxdata/influxdb#17606] opened 2020-04-03 16:37 UTC
Tools US 2.x Cluster
Dashboard Log File Studies V1.x - Shards

Variable shard defined as query:

import "influxdata/influxdb/v1"
v1.tagValues(bucket: v.bucket, tag: "shard_id")

The above sometimes works and sometimes does not based on the bucket.  For the following bucket, I actually created a cell to show that the value appears valid.

https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0569ce471d8dd000?lower=2020-04-01T01%3A00%3A00.000Z&upper=2020-04-01T02%3A00%3A00.000Z

![image](https://user-images.githubusercontent.com/49156476/78383921-3c4eb200-75a7-11ea-8ff0-8842ac83ff43.png)

I have run through a few dozen buckets (log files from customers) and sometimes the drop down works for the variable, other times it fails.  The l-creditkarma-apr bucket does not enable the drop down but the tag value list should just have the 10 numbers as shown above.

![image](https://user-images.githubusercontent.com/49156476/78384116-96e80e00-75a7-11ea-930a-b5a84bd94cfb.png)

Ping me if you cannot repro the problem or if the bucket shown above is gone.

**Comment by ebb-tide** [comment] 2020-04-03 18:03
The shard variable is a query type variable that depends on another variable (v.bucket).

**Comment by ebb-tide** [comment] 2020-04-03 18:10
dupe of #17593

**Comment by drdelambre** [comment] 2020-04-04 02:48
while more stuff started showing up, this didn't get fixed in the tools cluster. Check out the buckets variable in the data explorer as an example, also.. the shard value dropdown isn't loading even though the v1.tagOutput For shard is showing up

**Closed** 2020-04-06 20:48 UTC
Labels: kind/bug, regression, severity/sev-2, team/monitoring
