### ISSUE TITLE
[0.10.0-nightly] Retention policy not working

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5207] opened 2015-12-23 10:34 UTC
Hello,

I have retention policy with DURATION of 1hour.

```
1s      1h0m0s          1               true
```

However, when I query the data, the data for the past 2+ hours are being returned. This isn't exactly what I was expecting or what I expect to see.

```
SELECT * FROM testdb2."1s".wave

2015-12-23T08:00:01Z	"server01"			2
[...]
2015-12-23T10:24:10Z	"server01"			1
```

I have retention enabled and scheduled for every 30 minutes.

```
[retention]
  enabled = true
  check-interval = "30m"
```

Therefore, it would be sort of alright(not exactly, but...) to see data (up to) 30 minutes past the retention policy, eg. to see data for 1h-1:30h.

I was about to say that retention job isn't working, but log says otherwise:

```
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 retention policy shard deletion check commencing
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 retention policy enforcement check commencing
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 deleted shard group 177 from database testdb2, retention policy 1s
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 deleted shard group 178 from database testdb2, retention policy 1m
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 deleted shard group 179 from database testdb2, retention policy 1h
Dec 23 10:26:56 coreos01 docker[12240]: [retention] 2015/12/23 10:26:56 deleted shard group 176 from database testdb2, retention policy 1d
```

I've checked logs and retention policy enforcement is being run on regular basis ever since this instance is up. Also, query shows less data as well now. 1h 30min worth of data, to be precise. I wonder, are stale/cached data being served here?

Version is 0.10.0-nightly-3264ab0. Storage Engine is TSM1. I believe I've "updated" from 0.9.6.1.

**Comment by otoolep** [comment] 2015-12-23 14:55
If you restart the node, is the data still visible?

**Comment by zstyblik** [comment] 2015-12-23 15:27
@otoolep yes, and I'm getting 2.5h worth of data now.

**Comment by zstyblik** [comment] 2015-12-23 15:31
```
SELECT * FROM testdb2."1s".wave

2015-12-23T13:00:01Z	"server01"			2
[...]
2015-12-23T15:26:32Z	"server01"			1
```

There is one thing that comes to my mind. This data show fields from other retention policies. I mean, I have a CQ which takes data, calculates mean(`AS value`), max, p95 and puts it into another retention policy. Yet I can see empty fields max and p95 here - in the selection of input data. Is that a common and wanted thing? May be data are quantum leaping somehow. In other words, storage engine(TSM) bug?

> cq_1m_avg       CREATE CONTINUOUS QUERY cq_1m_avg ON telegraf BEGIN SELECT mean(value) INTO telegraf."1m".:MEASUREMENT FROM telegraf."1s"./.*/ WHERE time > now() - 1w GROUP BY time(1m), * END

**Comment by otoolep** [comment] 2015-12-23 19:42
@jwilder -- if shards that have been mmap()ed are deleted underneath the code, do we need to something else to ensure this data is no longer visible when queried?

**Comment by jwilder** [comment] 2015-12-23 19:55
The shard needs to be closed before they are deleted.  I believe the code already does that though.  If you remove the file while it's still mmap'd, the code will likely panic.

**Comment by zstyblik** [comment] 2015-12-23 22:10
@jwilder I haven't manually removed any files, if that's what you're suggesting. However, it's a Docker instance, therefore unclean shutdowns(kill) are likely.

**Comment by dswarbrick** [comment] 2015-12-24 01:06
I have noticed that disk space is not returned when shards are deleted, and `lsof` reveals that the file descriptors are still open, despite the file having been unlinked.
```
$ sudo lsof -u influxdb | grep DEL
influxd 644 influxdb  DEL    REG                9,0            35520569 /srv/influxdb/data/perfdb/default/5/000000774-000000003.tsm
influxd 644 influxdb  DEL    REG                9,0            35520539 /srv/influxdb/data/perfdb/default/5/000000758-000000005.tsm
influxd 644 influxdb  DEL    REG                9,0            35520525 /srv/influxdb/data/perfdb/default/5/000000758-000000004.tsm
influxd 644 influxdb  DEL    REG                9,0            35520537 /srv/influxdb/data/perfdb/default/5/000000569-000000005.tsm
influxd 644 influxdb  DEL    REG                9,0            35520519 /srv/influxdb/data/perfdb/default/5/000000569-000000004.tsm
influxd 644 influxdb  DEL    REG                9,0            35520535 /srv/influxdb/data/perfdb/default/5/000000379-000000005.tsm
influxd 644 influxdb  DEL    REG                9,0            35520524 /srv/influxdb/data/perfdb/default/5/000000379-000000004.tsm
influxd 644 influxdb  DEL    REG                9,0            35520798 /srv/influxdb/data/perfdb/default/5/000000190-000000005.tsm
influxd 644 influxdb  DEL    REG                9,0            35520794 /srv/influxdb/data/perfdb/default/5/000000190-000000004.tsm
influxd 644 influxdb  DEL    REG                9,0            35520548 /srv/influxdb/data/perfdb/default/2/000000230-000000003.tsm
influxd 644 influxdb  DEL    REG                9,0            35520595 /srv/influxdb/data/perfdb/default/2/000000190-000000005.tsm
influxd 644 influxdb  DEL    REG                9,0            35520591 /srv/influxdb/data/perfdb/default/2/000000190-000000004.tsm
```
Shard 5 was allegedly just deleted about half an hour ago, whilst shard 2 should have been deleted yesterday. Neither are still visible in the directory, but their disk space is still being occupied.

This smells a lot like the similar issue I found, where FDs were being held open for files that had been compacted.

**Comment by jwilder** [comment] 2015-12-24 01:13
@dswarbrick What build are you running?  There is a fix in https://github.com/influxdb/influxdb/commit/3893bc60e155661594e9d456223efe483eaa2b60 that should fix that.

**Comment by dswarbrick** [comment] 2015-12-24 01:15
@jwilder This is on 0.9.6.1.

**Comment by jwilder** [comment] 2015-12-24 01:17
@dswarbrick Ok.  That _should_ be fixed in the latest nightlies then.

**Comment by zstyblik** [comment] 2016-01-04 09:35
Funny enough, this led to the dataloss. I mean, `SHOW MEASUREMENTS` shows no data at all any more. Sadly, no logs from that period of time :(

I will try again with the nightly.

**Comment by dswarbrick** [comment] 2016-01-04 18:51
@jwilder Confirmed, the latest nightlies fix the stale FD issue (but unfortunately introduce an oom-kill issue, as I describe in #5257)

**Comment by jwilder** [comment] 2016-01-08 17:01
Is this issue still occurring with current nightly builds?

**Comment by dswarbrick** [comment] 2016-01-08 17:43
@jwilder I haven't seen the stale FD problem occur since your comment above, 16 days ago.

**Comment by zstyblik** [comment] 2016-01-08 17:45
@jwilder I'd say it's fixed in nightly.

**Closed** 2016-01-08 18:17 UTC
Labels: tsm
