### ISSUE TITLE
[0.9.5-nightly-952f1d5] last point is always 0

### ISSUE THREAD

**Issue by ecables** [influxdata/influxdb#4282] opened 2015-09-30 18:40 UTC
I use Grafana to visualize data in InfluxDB. Often times data hasn't been fully collected in the current minute, so we use time picker offsets, such as -1m or -2m to represent all but the last minute, or last two minutes, in our query.

What I'm finding, is that periodically InfluxDB returns the last point as 0, always, regardless of if data exists. This is represented in the screen recording below. In the recording I am modifying the query to be now() - 1m, now() - 2m, now() -3m, and so on. You can see that the last point is always zero, even if the previous query returned data for that time period.

Sample queries:
`SELECT sum(value) FROM db.rp.measurement WHERE tag =~ /.*/ AND time > now() - 15m AND time < now() - 1m GROUP BY time(1m) fill(0)`
`SELECT sum(value) FROM db.rp.measurement WHERE tag =~ /.*/ AND time > now() - 15m AND time < now() - 2m GROUP BY time(1m) fill(0)`
`SELECT sum(value) FROM db.rp.measurement WHERE tag =~ /.*/ AND time > now() - 15m AND time < now() - 3m GROUP BY time(1m) fill(0)`

![always-zero](https://cloud.githubusercontent.com/assets/5559459/10202853/b3d62252-6767-11e5-8486-4827f287adec.gif)

**Comment by ecables** [comment] 2015-10-01 20:45
What's interesting is when the last point populates with a value, the first point in the query becomes 0.

The below was generated by repeatedly issuing the following example query beginning at 55s into the minute, through 5s into the next minute:
`SELECT sum(value) FROM db.rp.measurement WHERE tag =~ /.*/ AND time > now() - 15m AND time < now() - 2m GROUP BY time(1m) fill(0)`

![more-zero](https://cloud.githubusercontent.com/assets/5559459/10233284/6c2e6d02-6842-11e5-98ec-d47ca5fc91aa.gif)

**Comment by beckettsean** [comment] 2015-10-01 22:20
Sounds very similar to https://github.com/influxdb/influxdb/issues/3926, although in that issue the first or last value were null, not zero.

**Comment by beckettsean** [comment] 2015-10-01 22:22
However, in this case there's a `fill(0)` in effect, so I'm guessing this is a recurrence of #3926, although that was fixed by https://github.com/influxdb/influxdb/pull/4038.

@corylanou you fixed the last issue, thoughts on this one?

**Comment by ecables** [comment] 2015-10-01 22:38
Here's the output when I remove `fill(0)`.

<img width="1041" alt="screen shot 2015-10-01 at 3 38 47 pm" src="https://cloud.githubusercontent.com/assets/5559459/10235582/798bdc2c-6852-11e5-917d-0572775ef40f.png">

**Comment by beckettsean** [comment] 2015-10-01 23:14
Thanks, @ecables.

@corylanou this looks like a regression of #3926 in the latest 0.9.5 nightlies.

**Comment by jsternberg** [comment] 2016-04-07 15:34
The query engine has had a complete refactor since this issue and I don't think it's relevant anymore. If the issue exists in the latest version, it might be fixed by #6222.

I'm going to close this since it's targeting the old query engine. Please reopen if this is still an issue.

**Closed by jsternberg** 2016-04-07 15:34 UTC
Labels: category/queries
