### ISSUE TITLE
Continuous Queries does not run : influxdb-0.11.0-1

### ISSUE THREAD

**Issue by deepujain** [influxdata/influxdb#6572] opened 2016-05-06 23:16 UTC
Query: 
```
CREATE CONTINUOUS QUERY bu ON ep RESAMPLE EVERY 1m
BEGIN
    SELECT count(distinct(eId)) as units INTO bualerts FROM ep."default".epdetail WHERE time > now() - 30d GROUP BY time(1d), businessUnit fill(none)
END
```

I want to run this query every 1m but it never runs.

when i run `select * from bualerts` , i do not see any results. 

When i manually run the query contained within continuous query, it runs.

InfluxDB: influxdb-0.11.0-1

**Comment by deepujain** [comment] 2016-05-07 00:16
I still could not get the CQ to run every 1m (automatically)

Continuous queries does not give true caching experience. The cache is limited to the duration for which the target measurement holds the data. Any query beyond that would simply return nothing even though data has been collected. Also running continuous query with group by(1y) every hour might take minutes to complete. 

Should there not be a mem cache layer on top of influx DB to provide true caching behavior.

**Comment by deepujain** [comment] 2016-05-07 18:16
Unable to convert below query into CQ

I want to speed up below query:
SELECT count(distinct(eId)) FROM "epdetail" WHERE "alertId" = '5'  AND "channelId" =~ /^$channelId$/  AND "siteId" =~ /^$siteId$/  AND "experimentId" =~ /^$experimentId$/ AND "businessUnit" =~ /^$businessUnit$/  AND $timeFilter GROUP BY time($interval) fill(none)

Hence am writing a CQ. (Lets keep the CQ syntax aside)

SELECT count(distinct(eId)) as units, channelId, siteId, experimentId, businessUnit INTO modQTAlerts FROM ep."default"."epdetail" WHERE "alertId" = '5'  AND time > now() - 120d GROUP BY time(1d) fill(none) 
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported

OR
> SELECT eId, channelId, siteId, experimentId, businessUnit INTO modQTAlerts FROM ep."default"."epdetail" WHERE "alertId" = '5'  AND time > now() - 120d GROUP BY time(1d) fill(none) 
ERR: error parsing query: GROUP BY requires at least one aggregate function
> 

How do i convert above query into CQ

**Comment by deepujain** [comment] 2016-05-07 18:16
And how do make it run automatically ?

**Comment by deepujain** [comment] 2016-05-16 18:21
Any suggestions on how to make below CQ to run every hour ?

SELECT count(distinct(eId)) as units INTO channelIdAlerts FROM ep."default".epdetail WHERE time > now() - 120d GROUP BY time(1d), channelId fill(none)

**Comment by deepujain** [comment] 2016-05-16 21:07
I did this
CREATE CONTINUOUS QUERY bualerts ON ep RESAMPLE EVERY 1m BEGIN SELECT count(distinct(eId)) AS units INTO ep."default".bualerts FROM ep."default".epdetail WHERE time > now() - 120d GROUP BY time(1d), businessUnit fill(none) END
drop measurement bualerts
select from bualerts
select from bualerts
and it never ran after a minute
any suggestions ?


Also, I am unable to find a active community for InfluxDB to post questions. Is it google group or groups.io or gitter or github ?

**Comment by jsternberg** [comment] 2016-05-17 14:16
We use GitHub only for feature requests and bugs. For general questions, use the google group.

Before I start trying to reproduce your issue, does it still happen on 0.13?

**Comment by deepujain** [comment] 2016-05-17 14:31
Ok. will move to gg. So is the syntax correct ? And i did not move to 0.13
as that means migrating existing production dataset to it.



On Tue, May 17, 2016 at 7:16 AM, Jonathan A. Sternberg <
notifications@github.com> wrote:

> We use GitHub only for feature requests and bugs. For general questions,
> use the google group.
>
> Before I start trying to reproduce your issue, does it still happen on
> 0.13?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6572#issuecomment-219731169>
>



-- 
Deepak

**Comment by jsternberg** [comment] 2016-05-17 14:51
Based on the first query in the original comment, the query looks mostly correct, but is missing something.

```
CREATE CONTINUOUS QUERY bu ON ep RESAMPLE EVERY 1m
BEGIN
    SELECT count(distinct(eId)) as units INTO bualerts FROM ep."default".epdetail WHERE time > now() - 30d GROUP BY time(1d), businessUnit fill(none)
END
```

The time clause here is ignored and a time range is generated by the continuous query service whenever it wants to calculate an interval. If you want to calculate the last 30 days every 1 minute, you would need to use `RESAMPLE FOR 30d`. Each bucket would still encompass only 1 day. With the current query, I think it will only resample the last day every 1 minute.

**Comment by deepujain** [comment] 2016-05-17 17:30
I tried andit did not work.

> drop measurement bualerts

> select * from bualerts

> SHOW CONTINUOUS QUERIES


name: _internal

---------------

name query



name: anomaly

-------------

name query



name: development

-----------------

name query



name: ep

--------

name query

bu CREATE CONTINUOUS QUERY bu ON ep RESAMPLE EVERY 1m BEGIN SELECT
count(distinct(eId)) AS units INTO ep."default".bualerts FROM
ep."default".epdetail WHERE time > now() - 30d GROUP BY time(1d),
businessUnit fill(none) END


> select * from bualerts

>

time: 10.25 AM

wait (go on coffee break)

time: 10.30 AM

> select * from bualerts

>


====

Questions

0. Not working.

1. I have *120 days* of data and i want to run the *above query for last
120 days* (and data is collected once every day , hence groupby (1d))

2. I want the above query to run *every 1m* (to test it out, if its
working) and later change it to run *every 1h*. (as i do not know when the
backend process will complete during the day).


Regards,

Deepak



On Tue, May 17, 2016 at 7:52 AM, Jonathan A. Sternberg <
notifications@github.com> wrote:

> Based on the first query in the original comment, the query looks mostly
> correct, but is missing something.
>
> CREATE CONTINUOUS QUERY bu ON ep RESAMPLE EVERY 1m
> BEGIN
>     SELECT count(distinct(eId)) as units INTO bualerts FROM ep."default".epdetail WHERE time > now() - 30d GROUP BY time(1d), businessUnit fill(none)
> END
>
> The time clause here is ignored and a time range is generated by the
> continuous query service whenever it wants to calculate an interval. If you
> want to calculate the last 30 days every 1 minute, you would need to use RESAMPLE
> FOR 30d. Each bucket would still encompass only 1 day. With the current
> query, I think it will only resample the last day every 1 minute.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/influxdb/issues/6572#issuecomment-219742671>
>



-- 
Deepak

**Comment by jsternberg** [comment] 2016-05-17 18:32
@deepujain I think it would be better to move this to the [InfluxDB mailing list](https://groups.google.com/forum/#!forum/influxdb). I'm going to close this issue since it isn't a feature request or bug. Thanks.

**Closed by jsternberg** 2016-05-17 18:32 UTC
