### ISSUE TITLE
Influxdb slowly uses more memory overnight until 100% (64GB) with ~3MB of data

### ISSUE THREAD

**Issue by MarvinJWendt** [influxdata/influxdb#23167] opened 2022-03-07 00:17 UTC
Hi, this is rather a question, as I don't know if this is a bug or not.

My InfluxDBs (v2.1) memory usage went insane overnight. Can someone explain me possible causes?
![image](https://user-images.githubusercontent.com/31022056/156948585-4ad36a73-29e8-41ec-9d7b-5f0b0ba9303b.png)

The data folder of InfluxDB is **~3 MB**.
I am using it inside a docker container.

Is this a memory leak, or am I doing something wrong? Thanks!

`influxdb.cardinality(bucket: "system", start: -1y)` = `66`
`influxdb.cardinality(bucket: "instl_metrics", start: -1y)` = `3`
`influxdb.cardinality(bucket: "appwrite_metrics", start: -1y)` = `40`
`influxdb.cardinality(bucket: "traefik_metrics", start: -1y)` = `269`

**Comment by lesam** [comment] 2022-03-11 22:22
Would you be able to attach profiles so we can see where your memory is being used?

https://docs.influxdata.com/influxdb/v2.1/reference/internals/runtime/#get-all-runtime-profiles

**Comment by lesam** [comment] 2022-03-11 22:24
Also we have seen some issues with scrapers, that are fixed in the upcoming version. Do you have any scrapers configured?

**Comment by MarvinJWendt** [comment] 2022-03-12 22:04
Hi @lesam, I have InfluxDB unfortunately reset since then, but I did not use any scraper. I guess a query had hung up, because I was experimenting a bit with the dashboards at the time it started going up. After a restart of the container there were no more problems.

**Comment by lesam** [comment] 2022-03-14 13:18
Thanks @MarvinJWendt, glad it is working for you now. Unfortunately I don't think this is enough to reproduce / identify the issue, so I'm going to close it. But if you see the issue again we'd really appreciate info about how to reproduce and/or profiles.

**Closed by lesam** 2022-03-14 13:18 UTC

**Comment by SimonMayerhofer** [comment] 2022-08-22 21:16
Hi @lesam, I have the same issue with around 33MB of data.

`influxdb.cardinality(bucket: "primoco", start: -1y)` = `173`
`influxdb.cardinality(bucket: "primoco", start: -5y)` = `348`

After a restart of my influx docker container around 500MB of RAM are used. Last restart was at 18:35. Now 4h later at 22:20 around 1GB more is used
Here are the profiles:
[all.gz](https://github.com/influxdata/influxdb/files/9397410/all.gz)

Regarding reproduction of the issue: the data is confidential, I'm currently not able to provide it to you, to test it. But if absolutely necessary I'll anonymize everything and provide you data + code to reproduce it. But as this will be probably a few hours of work for me, I'd prefer not to, if not necessary.

But here's additional information I can give you:

1) I have around 4000 data points. So quite less data.
2) Every 2 minutes (same issue existed when I did it with every 15 minutes) the following happens:
-  I load all the data into influx into a new bucket "new", rename the "active" one to "old", rename "new" to "active", delete "old". So basically import all ~4000 datapoints again. The renaming happens, so that there is a minimum of downtime, as the longest part is the importing, which is done in the background that way.
-  This is necessary and can't be done differently.
- After the new data is imported a script runs to process the data and saves it in an own measurement. I first did this with a task every 5 minutes, but changed it now, that it's done once after importing the data. Same issue existed when I did it as a task. This processing task takes around 10s - 15s. After that all extensive calculation is over.


<details>
<summary>The processing script</summary>

Quick description of what happens here: The data is financial data of 30 accounts. ~4000 Entries in total. It's calculating the cumulative sum of each account for any point in time + 3 more series which add up these cumulative sums of these accounts (once all negative accounts, once all positive and once the total sum of all accounts).

```
import "strings"

escape = (v) => {
  v1 = strings.replace(v: v, t: " ", u: "\\ ", i: 99999)
  v2 = strings.replace(v: v1, t: ",", u: "\\,", i: 99999)
  v3 = strings.replace(v: v2, t: "=", u: "\\=", i: 99999)
  return v3
}

negateOutgoingTransfers = (r, account) => ({
  r with
  _value: if r["Entry Type"] == "Transfer" and r["Account"] == escape(v:account) then (r["_value"] * -1.0) else r["_value"]
})

getAccountValues = (tables=<-, account) =>
  tables
    |> filter(fn: (r) => r["Account"] == escape(v:account) or r["Counter Account"] == escape(v:account))
	|> map(fn: (r) => ({r with name: account}))
    |> map(fn: (r) => negateOutgoingTransfers(r, account))
	|> group(columns: ["name"])
	|> sort(columns: ["_time"], desc: false)

data = from(bucket: "primoco")
  |> range(start: 1970-01-01T00:00:00Z)
  |> drop(columns: ["_start", "_stop"])
  |> filter(fn: (r) => r["_measurement"] == "bookings")
  |> filter(fn: (r) => r["_field"] == "Value")

accountNames = [
  "Account a0",
  "Account a1",
  "Account a2",
  "Account a3",
  "Account a4",
  "Account a5",
  "Account a6",
  "Account a7",
  "Account a8",
  "Account a9",
  "Account a10",
  "Account a11",
  "Account a12",
  "Account a13",
  "Account a14",
  "Account a15",
  "Account a16",
  "Account a17",
  "Account a18",
  "Account a19",
  "Account a20",
  "Account a21",
  "Account a22",
  "Account a23",
  "Account a24",
  "Account a25",
  "Account a26",
  "Account a27",
  "Account a28",
  "Account a29"
]

a0  = data |> getAccountValues(account: accountNames[0])
a1  = data |> getAccountValues(account: accountNames[1])
a2  = data |> getAccountValues(account: accountNames[2])
a3  = data |> getAccountValues(account: accountNames[3])
a4  = data |> getAccountValues(account: accountNames[4])
a5  = data |> getAccountValues(account: accountNames[5])
a6  = data |> getAccountValues(account: accountNames[6])
a7  = data |> getAccountValues(account: accountNames[7])
a8  = data |> getAccountValues(account: accountNames[8])
a9  = data |> getAccountValues(account: accountNames[9])
a10 = data |> getAccountValues(account: accountNames[10])
a11 = data |> getAccountValues(account: accountNames[11])
a12 = data |> getAccountValues(account: accountNames[12])
a13 = data |> getAccountValues(account: accountNames[13])
a14 = data |> getAccountValues(account: accountNames[14])
a15 = data |> getAccountValues(account: accountNames[15])
a16 = data |> getAccountValues(account: accountNames[16])
a17 = data |> getAccountValues(account: accountNames[17])
a18 = data |> getAccountValues(account: accountNames[18])
a19 = data |> getAccountValues(account: accountNames[19])
a20 = data |> getAccountValues(account: accountNames[20])
a21 = data |> getAccountValues(account: accountNames[21])
a22 = data |> getAccountValues(account: accountNames[22])
a23 = data |> getAccountValues(account: accountNames[23])
a24 = data |> getAccountValues(account: accountNames[24])
a25 = data |> getAccountValues(account: accountNames[25])
a26 = data |> getAccountValues(account: accountNames[26])
a27 = data |> getAccountValues(account: accountNames[27])
a28 = data |> getAccountValues(account: accountNames[28])
a29 = data |> getAccountValues(account: accountNames[29])

accounts = [a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29]

saveBalance = (tables=<-) => tables
  |> cumulativeSum()
  |> map(fn: (r) => ({
    r with _measurement: "account-balance",
	_field: r.name
  }))
  |> keep(columns: ["_time", "_value", "_measurement", "_field"])
  |> to(bucket: "primoco")

a0 |> saveBalance()
a1 |> saveBalance()
a2 |> saveBalance()
a3 |> saveBalance()
a4 |> saveBalance()
a5 |> saveBalance()
a6 |> saveBalance()
a7 |> saveBalance()
a8 |> saveBalance()
a9 |> saveBalance()
a10 |> saveBalance()
a11 |> saveBalance()
a12 |> saveBalance()
a13 |> saveBalance()
a14 |> saveBalance()
a15 |> saveBalance()
a16 |> saveBalance()
a17 |> saveBalance()
a18 |> saveBalance()
a19 |> saveBalance()
a20 |> saveBalance()
a21 |> saveBalance()
a22 |> saveBalance()
a23 |> saveBalance()
a24 |> saveBalance()
a25 |> saveBalance()
a26 |> saveBalance()
a27 |> saveBalance()
a28 |> saveBalance()
a29 |> saveBalance()

calcTotal = (v) => if exists v then v else 0.0
calcAsset = (v) => if exists v then (if v > 0 then v else 0.0) else 0.0
calcLiability = (v) => if exists v then (if v < 0 then v else 0.0) else 0.0

accountSums = union(tables: accounts)
  |> pivot(
    rowKey:["_time"],
    columnKey: ["name"],
    valueColumn: "_value"
  )
  |> sort(columns: ["_time"], desc: false)
  |> cumulativeSum(columns: accountNames)

  |> map(fn: (r) => ({
    r with _measurement: "account-balance",
	_field: "Total",
    _value: 0.0 +
    calcTotal(v:r["Account a0"]) +
    calcTotal(v:r["Account a1"]) +
    calcTotal(v:r["Account a2"]) +
    calcTotal(v:r["Account a3"]) +
    calcTotal(v:r["Account a4"]) +
    calcTotal(v:r["Account a5"]) +
    calcTotal(v:r["Account a6"]) +
    calcTotal(v:r["Account a7"]) +
    calcTotal(v:r["Account a8"]) +
    calcTotal(v:r["Account a9"]) +
    calcTotal(v:r["Account a10"]) +
    calcTotal(v:r["Account a11"]) +
    calcTotal(v:r["Account a12"]) +
    calcTotal(v:r["Account a13"]) +
    calcTotal(v:r["Account a14"]) +
    calcTotal(v:r["Account a15"]) +
    calcTotal(v:r["Account a16"]) +
    calcTotal(v:r["Account a17"]) +
    calcTotal(v:r["Account a18"]) +
    calcTotal(v:r["Account a19"]) +
    calcTotal(v:r["Account a20"]) +
    calcTotal(v:r["Account a21"]) +
    calcTotal(v:r["Account a22"]) +
    calcTotal(v:r["Account a23"]) +
    calcTotal(v:r["Account a24"]) +
    calcTotal(v:r["Account a25"]) +
    calcTotal(v:r["Account a26"]) +
    calcTotal(v:r["Account a27"]) +
    calcTotal(v:r["Account a28"]) +
    calcTotal(v:r["Account a29"]) +
	0.0
  }))
  |> yield(name:"Total") // net worth
  |> to(bucket: "primoco")

  |> map(fn: (r) => ({
	r with  _field: "Assets",
    _value: 0.0 +
    calcAsset(v:r["Account a0"]) +
    calcAsset(v:r["Account a1"]) +
    calcAsset(v:r["Account a2"]) +
    calcAsset(v:r["Account a3"]) +
    calcAsset(v:r["Account a4"]) +
    calcAsset(v:r["Account a5"]) +
    calcAsset(v:r["Account a6"]) +
    calcAsset(v:r["Account a7"]) +
    calcAsset(v:r["Account a8"]) +
    calcAsset(v:r["Account a9"]) +
    calcAsset(v:r["Account a10"]) +
    calcAsset(v:r["Account a11"]) +
    calcAsset(v:r["Account a12"]) +
    calcAsset(v:r["Account a13"]) +
    calcAsset(v:r["Account a14"]) +
    calcAsset(v:r["Account a15"]) +
    calcAsset(v:r["Account a16"]) +
    calcAsset(v:r["Account a17"]) +
    calcAsset(v:r["Account a18"]) +
    calcAsset(v:r["Account a19"]) +
    calcAsset(v:r["Account a20"]) +
    calcAsset(v:r["Account a21"]) +
    calcAsset(v:r["Account a22"]) +
    calcAsset(v:r["Account a23"]) +
    calcAsset(v:r["Account a24"]) +
    calcAsset(v:r["Account a25"]) +
    calcAsset(v:r["Account a26"]) +
    calcAsset(v:r["Account a27"]) +
    calcAsset(v:r["Account a28"]) +
    calcAsset(v:r["Account a29"]) +
	0.0
  }))
  |> yield(name:"Assets")
  |> to(bucket: "primoco")

  |> map(fn: (r) => ({
	r with _field: "Liabilities",
    _value: 0.0 +
    calcLiability(v:r["Account a0"]) +
    calcLiability(v:r["Account a1"]) +
    calcLiability(v:r["Account a2"]) +
    calcLiability(v:r["Account a3"]) +
    calcLiability(v:r["Account a4"]) +
    calcLiability(v:r["Account a5"]) +
    calcLiability(v:r["Account a6"]) +
    calcLiability(v:r["Account a7"]) +
    calcLiability(v:r["Account a8"]) +
    calcLiability(v:r["Account a9"]) +
    calcLiability(v:r["Account a10"]) +
    calcLiability(v:r["Account a11"]) +
    calcLiability(v:r["Account a12"]) +
    calcLiability(v:r["Account a13"]) +
    calcLiability(v:r["Account a14"]) +
    calcLiability(v:r["Account a15"]) +
    calcLiability(v:r["Account a16"]) +
    calcLiability(v:r["Account a17"]) +
    calcLiability(v:r["Account a18"]) +
    calcLiability(v:r["Account a19"]) +
    calcLiability(v:r["Account a20"]) +
    calcLiability(v:r["Account a21"]) +
    calcLiability(v:r["Account a22"]) +
    calcLiability(v:r["Account a23"]) +
    calcLiability(v:r["Account a24"]) +
    calcLiability(v:r["Account a25"]) +
    calcLiability(v:r["Account a26"]) +
    calcLiability(v:r["Account a27"]) +
    calcLiability(v:r["Account a28"]) +
    calcLiability(v:r["Account a29"]) +
	0.0
  }))
  |> yield(name:"Liabilities")
  |> to(bucket: "primoco")
```

</details>

3) There is very less accessing of the data. Maybe twice a day. So there's no correlation between accessing the data and the issue.

4) I'm currently running on influx 2.3, but issue existed also with earlier versions.

5) I limited the RAM usage of my docker container to 4GB, so that the host doesn't run out of memory.

Let me know if you need further information from my side or how I can help to debug this issue.
Current workaround is to restart influx on a regular basis.

**Comment by lesam** [comment] 2022-08-23 18:23
@SimonMayerhofer - from the profile, the major source of memory usage you have is the prometheus metrics system. I believe this is because you have a new bucket every 2 minutes and that adds a small amount of overhead into the metrics system each time (when the bucket is deleted I don't think that the metric tags etc for that bucket are removed). 

You could try disabling metrics ( https://docs.influxdata.com/influxdb/v2.4/reference/config-options/#metrics-disabled ) but I think this just disables the endpoint that allows scraping metrics, and not the overhead that is causing you problems.

In any case, I doubt this is related to the original issues you cite as it seems closely related to creating and deleting buckets so often.

**Comment by SimonMayerhofer** [comment] 2022-08-24 11:53
Hi @lesam thanks for your help!

> You could try disabling metrics ( https://docs.influxdata.com/influxdb/v2.4/reference/config-options/#metrics-disabled ) but I think this just disables the endpoint that allows scraping metrics, and not the overhead that is causing you problems.

I tried it and you're right. Same issue exists.

> In any case, I doubt this is related to the original issues you cite as it seems closely related to creating and deleting buckets so often.

Okay thanks. How to proceed? Should I open a separate issue?

**Comment by lesam** [comment] 2022-08-24 12:14
You can open a separate issue, but I don't think this use case of having so much bucket churn is very common, so it likely will not be addressed quickly.

I'd recommend re-examining whether you need to create so many 'new' buckets.
