### ISSUE TITLE
Following Docs to Create and Setup InfluxDB 2.0 on MacOS leads to server internal error

### ISSUE THREAD

**Issue by bmoscon** [influxdata/influxdb#21133] opened 2021-04-03 16:42 UTC
Following this guide:

https://docs.influxdata.com/influxdb/v2.0/get-started/

I 
1. Installed with homebrew
2. ran `influxd` in a terminal
3. Navigated to localhost:8086

This resulted in a 500 Internal Server Error

I see nothing in the logging in the terminal that would indicate whats wrong, and searching the usual places for logs yielded no influx log file.

The contents of the term are:

```
$ influxd
2021-04-03T16:16:09.492923Z	info	Welcome to InfluxDB	{"log_id": "0TI8AN50000", "version": "2.0.4", "commit": "none", "build_date": "2021-04-03T16:16:06Z"}
2021-04-03T16:16:09.540755Z	info	Resources opened	{"log_id": "0TI8AN50000", "service": "bolt", "path": "/Users/bryant/.influxdbv2/influxd.bolt"}
2021-04-03T16:16:09.869427Z	info	Using data dir	{"log_id": "0TI8AN50000", "service": "storage-engine", "service": "store", "path": "/Users/bryant/.influxdbv2/engine/data"}
2021-04-03T16:16:09.869543Z	info	Compaction settings	{"log_id": "0TI8AN50000", "service": "storage-engine", "service": "store", "max_concurrent_compactions": 8, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2021-04-03T16:16:09.869573Z	info	Open store (start)	{"log_id": "0TI8AN50000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "start"}
2021-04-03T16:16:09.869826Z	info	Open store (end)	{"log_id": "0TI8AN50000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.255ms"}
2021-04-03T16:16:09.869894Z	info	Starting retention policy enforcement service	{"log_id": "0TI8AN50000", "service": "retention", "check_interval": "30m"}
2021-04-03T16:16:09.869932Z	info	Starting precreation service	{"log_id": "0TI8AN50000", "service": "shard-precreation", "check_interval": "10m", "advance_period": "30m"}
2021-04-03T16:16:09.870082Z	info	Starting query controller	{"log_id": "0TI8AN50000", "service": "storage-reads", "concurrency_quota": 10, "initial_memory_bytes_quota_per_query": 9223372036854775807, "memory_bytes_quota_per_query": 9223372036854775807, "max_memory_bytes": 0, "queue_size": 10}
2021-04-03T16:16:09.870771Z	info	Configuring InfluxQL statement executor (zeros indicate unlimited).	{"log_id": "0TI8AN50000", "max_select_point": 0, "max_select_series": 0, "max_select_buckets": 0}
2021-04-03T16:16:10.299117Z	info	Starting	{"log_id": "0TI8AN50000", "service": "telemetry", "interval": "8h"}
2021-04-03T16:16:10.299100Z	info	Listening	{"log_id": "0TI8AN50000", "transport": "http", "addr": ":8086", "port": 8086}
```

__Environment info:__

Env:

Darwin 20.3.0 x86_64

version:
InfluxDB 2.0.4 (git: none) build_date: 2021-04-03T16:40:31Z

__Config:__

All default. I literally ran `brew install influxdb` and then `influxd`

__Logs:__

I was unable to find the log file, and searching the web documentation did not yield its location. Perhaps put the path in the template?

I should also mention that configuring the system with `influx setup` worked, but I still cannot log into the UI, I am greeted only with the 500 internal server error. This prevents me from accessing the auth token that was created at setup

**Comment by josephpeacock** [comment] 2021-04-07 22:07
I am having the same problem, following the setup steps with brew exactly.

macOS Catalina, 10.15.7

And I found someone on the influxdata community page with a [similar issue](https://community.influxdata.com/t/500-internal-server-error/19031), so it doesn't seem to be isolated. I did start up influxdb with log-level=debug to try to learn more, but only got very basic access logs (you can see I also tried curling the endpoint):

```
influxd run --log-level=debug
2021-04-07T21:50:18.089430Z	info	Welcome to InfluxDB	{"log_id": "0TN_smvG000", "version": "2.0.4", "commit": "none", "build_date": "2021-04-07T21:50:13Z"}
2021-04-07T21:50:18.139506Z	info	Resources opened	{"log_id": "0TN_smvG000", "service": "bolt", "path": "/Users/joepeacock/.influxdbv2/influxd.bolt"}
2021-04-07T21:50:18.509654Z	debug	buckets find	{"log_id": "0TN_smvG000", "store": "new", "took": "0.345ms"}
2021-04-07T21:50:18.510058Z	info	Using data dir	{"log_id": "0TN_smvG000", "service": "storage-engine", "service": "store", "path": "/Users/joepeacock/.influxdbv2/engine/data"}
2021-04-07T21:50:18.510184Z	info	Compaction settings	{"log_id": "0TN_smvG000", "service": "storage-engine", "service": "store", "max_concurrent_compactions": 4, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2021-04-07T21:50:18.510221Z	info	Open store (start)	{"log_id": "0TN_smvG000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "start"}
2021-04-07T21:50:18.510546Z	info	Open store (end)	{"log_id": "0TN_smvG000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.327ms"}
2021-04-07T21:50:18.510623Z	info	Starting retention policy enforcement service	{"log_id": "0TN_smvG000", "service": "retention", "check_interval": "30m"}
2021-04-07T21:50:18.510858Z	info	Starting precreation service	{"log_id": "0TN_smvG000", "service": "shard-precreation", "check_interval": "10m", "advance_period": "30m"}
2021-04-07T21:50:18.511096Z	info	Starting query controller	{"log_id": "0TN_smvG000", "service": "storage-reads", "concurrency_quota": 10, "initial_memory_bytes_quota_per_query": 9223372036854775807, "memory_bytes_quota_per_query": 9223372036854775807, "max_memory_bytes": 0, "queue_size": 10}
2021-04-07T21:50:18.512667Z	info	Configuring InfluxQL statement executor (zeros indicate unlimited).	{"log_id": "0TN_smvG000", "max_select_point": 0, "max_select_series": 0, "max_select_buckets": 0}
2021-04-07T21:50:18.965112Z	info	Starting	{"log_id": "0TN_smvG000", "service": "telemetry", "interval": "8h"}
2021-04-07T21:50:18.965114Z	info	Listening	{"log_id": "0TN_smvG000", "transport": "http", "addr": ":8086", "port": 8086}
2021-04-07T21:50:24.512697Z	debug	Request	{"log_id": "0TN_smvG000", "service": "http", "method": "GET", "host": "localhost:8086", "path": "/", "query": "", "proto": "HTTP/1.1", "status_code": 500, "response_size": 26, "content_length": 0, "referrer": "", "remote": "127.0.0.1:63361", "user_agent": "Firefox", "took": "0.175ms", "body": ""}
2021-04-07T21:51:21.957574Z	debug	Request	{"log_id": "0TN_smvG000", "service": "http", "method": "GET", "host": "localhost:8086", "path": "/", "query": "", "proto": "HTTP/1.1", "status_code": 500, "response_size": 26, "content_length": 0, "referrer": "", "remote": "127.0.0.1:63361", "user_agent": "Firefox", "took": "0.086ms", "body": ""}
2021-04-07T21:54:00.775895Z	debug	Request	{"log_id": "0TN_smvG000", "service": "http", "method": "GET", "host": "localhost:8086", "path": "/", "query": "", "proto": "HTTP/1.1", "status_code": 500, "response_size": 26, "content_length": 0, "referrer": "", "remote": "[::1]:63416", "user_agent": "curl", "took": "0.083ms", "body": ""}
2021-04-07T21:54:06.800416Z	debug	Request	{"log_id": "0TN_smvG000", "service": "http", "method": "GET", "host": "localhost:8086", "path": "/", "query": "", "proto": "HTTP/1.1", "status_code": 500, "response_size": 26, "content_length": 0, "referrer": "", "remote": "[::1]:63417", "user_agent": "curl", "took": "0.059ms", "body": ""}
```

**Comment by josephpeacock** [comment] 2021-04-07 23:10
If anyone else is having a similar issue - I was able to use docker as a workaround, install docker desktop if you haven't, and run 

```
docker run -p 8086:8086 \
      -v $PWD:/var/lib/influxdb2 \
      influxdb:2.0
```
with pwd being the directory where you want to store data associated with the InfluxDB container.

**Comment by samsieber** [comment] 2021-04-15 16:30
I also tried running with sudo, which made no difference.

**Comment by samsieber** [comment] 2021-04-15 16:37
Version 2.0.4 downloaded from the website did work.

**Comment by tobiasbrodd** [comment] 2021-04-29 19:39
Does anyone know when this will get fixed? I get the exact same error. However, using the binaries from the website gave me this error:
`Error: up: reading migrations: migration "record shard group durations in bucket metadata": migration specification not found`

**Comment by danxmoran** [comment] 2021-04-29 19:56
@tobiasbrodd the migration error would be caused by downgrading from 2.0.5->2.0.4, which is likely to have happened if you `brew install`ed influxdb in the past few days. We discovered a serious bug in 2.0.5 the day after tagging it so we held off from adding it to our downloads page, but it looks like Homebrew has some automation that still found it and updated the formula.

We've just released 2.0.6 and added it to the downloads page, can you give that a try?

**Comment by tobiasbrodd** [comment] 2021-04-29 20:09
@danxmoran I deleted the `.influxdbv2 `file and then the 2.0.4 installation worked so yes, probably caused by the downgrade.

The 2.0.6 version also works! Thanks!

**Comment by thecodejunkie** [comment] 2021-05-13 12:42
@danxmoran I seem to be experiencing this issue with 6.0.4 on macOS Big Sur 11.2.3 (haven't updated to latest patch because co-workers have been experiencing some issues with it) 

I installed influxdb, using brew, about 15 minutes ago

```sh
influx version
Influx CLI 2.0.6 (git: none) build_date: 2021-05-13T12:37:56Z
```

```sh
influxd

2021-05-13T12:35:27.235667Z	info	Welcome to InfluxDB	{"log_id": "0U5RRcWl000", "version": "2.0.6", "commit": "none", "build_date": "2021-05-13T12:35:16Z"}
2021-05-13T12:35:27.336330Z	info	Resources opened	{"log_id": "0U5RRcWl000", "service": "bolt", "path": "/Users/[REDACTED]/.influxdbv2/influxd.bolt"}
2021-05-13T12:35:27.388471Z	info	Bringing up metadata migrations	{"log_id": "0U5RRcWl000", "service": "migrations", "migration_count": 15}
2021-05-13T12:35:32.217703Z	info	Using data dir	{"log_id": "0U5RRcWl000", "service": "storage-engine", "service": "store", "path": "/Users/[REDACTED]/.influxdbv2/engine/data"}
2021-05-13T12:35:32.217991Z	info	Compaction settings	{"log_id": "0U5RRcWl000", "service": "storage-engine", "service": "store", "max_concurrent_compactions": 6, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2021-05-13T12:35:32.218012Z	info	Open store (start)	{"log_id": "0U5RRcWl000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "start"}
2021-05-13T12:35:32.218144Z	info	Open store (end)	{"log_id": "0U5RRcWl000", "service": "storage-engine", "service": "store", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.133ms"}
2021-05-13T12:35:32.218189Z	info	Starting retention policy enforcement service	{"log_id": "0U5RRcWl000", "service": "retention", "check_interval": "30m"}
2021-05-13T12:35:32.218216Z	info	Starting precreation service	{"log_id": "0U5RRcWl000", "service": "shard-precreation", "check_interval": "10m", "advance_period": "30m"}
2021-05-13T12:35:32.218365Z	info	Starting query controller	{"log_id": "0U5RRcWl000", "service": "storage-reads", "concurrency_quota": 1024, "initial_memory_bytes_quota_per_query": 9223372036854775807, "memory_bytes_quota_per_query": 9223372036854775807, "max_memory_bytes": 0, "queue_size": 1024}
2021-05-13T12:35:32.220462Z	info	Configuring InfluxQL statement executor (zeros indicate unlimited).	{"log_id": "0U5RRcWl000", "max_select_point": 0, "max_select_series": 0, "max_select_buckets": 0}
2021-05-13T12:35:32.667940Z	info	Starting	{"log_id": "0U5RRcWl000", "service": "telemetry", "interval": "8h"}
2021-05-13T12:35:32.667972Z	info	Listening	{"log_id": "0U5RRcWl000", "service": "tcp-listener", "transport": "http", "addr": ":8086", "port": 8086}
```

I can run the `influx setup` guide without issues, but whenever I try and browse the UI I get the sams 500 error

![image](https://user-images.githubusercontent.com/50543/118126893-3b6a8f80-b3f9-11eb-9704-84b268f8530a.png)

I've tried deleting my `.influxdbv2` folder but the problem remains

**Comment by danxmoran** [comment] 2021-05-13 13:06
@thecodejunkie the brew formula hasn't been fixed yet, please download the binary directly from our [downloads portal](https://portal.influxdata.com/downloads/).

**Comment by thecodejunkie** [comment] 2021-05-13 14:04
@danatinflux thanks, that solved it! Any ETA on an updated brew formula?

**Comment by danatinflux** [comment] 2021-05-13 15:13
I think you meant @danxmoran . :)

**Comment by thecodejunkie** [comment] 2021-05-13 15:48
@danatinflux Whops! I sure did 😄 

/cc @danxmoran

**Comment by danxmoran** [comment] 2021-05-13 19:11
Homebrew/homebrew-core#77226 should address this

**Comment by danxmoran** [comment] 2021-05-21 18:25
Fixes have merged into `homebrew-core`, closing this.

**Closed by danxmoran** 2021-05-21 18:25 UTC
Labels: area/2.x, area/packaging, os/darwin
