### ISSUE TITLE
reproducible corruption:  rows merged from 2 inserts when overwriting

### ISSUE THREAD

**Issue by dylan-ferreira** [influxdata/influxdb#7262] opened 2016-09-06 21:44 UTC
## System info:
Reproduced on 3 instances of InfluxDB:

Influxd: 0.13.0
OS: Ubuntu Trusty 14.04
System: 2xSSD hdd, 256GB RAM, 32 cores

Influxd: 0.13.0
OS: Mac OS X 10.11.6 (15G1004)
System: Macbook Pro 15 (Mid 2015), 16GB RAM

Influxd: 1.0.0-rc2
OS: Mac OS X 10.11.6 (15G1004)
System: Macbook Pro 15 (Mid 2015), 16GB RAM

## Details:
[influx_issue.zip](https://github.com/influxdata/influxdb/files/457843/influx_issue.zip)

When inserting data (via HTTP) that collides with existing timestamps, I occasionally get rows that contain a mix of field data from multiple inserts.

The test I've put together (see attached) inserts rows in batches of 8000 with a precision of 1 second to encourage collisions.  The rows contain 3 fields:
- "batchcounter": an number incrementing once for each 8000 sample batch I post.
- "counter1" & "counter2": a per-sample incrementing number set by the same variable.

```
fields := map[string]interface{}{
        "batchcounter": batchcounter,
        "counter1":     counter,
        "counter2":     counter,
}
```
The idea being "counter1" & "counter2" always match on insert and should always match in the database.

When running the attached test concurrently (I ran 10 workers) against the same database, I find a small percentage of my resulting rows show a difference between "counter1" & "counter2".

Query: `SELECT * FROM testcounter WHERE counter1 != counter2`
```
{
    "results": [
        {
            "series": [
                {
                    "name": "testcounter",
                    "columns": [
                        "time",
                        "batchcounter",
                        "counter1",
                        "counter2",
                        "version"
                    ],
                    "values": [
                        [
                            "2016-09-05T19:39:34Z",
                            138,
                            1263999,
                            975999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:40:10Z",
                            320,
                            2567999,
                            2767999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:40:14Z",
                            338,
                            2711999,
                            2895999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:40:45Z",
                            512,
                            4103999,
                            4271999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:41:18Z",
                            699,
                            5599999,
                            5543999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:41:33Z",
                            757,
                            6063999,
                            6223999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:41:36Z",
                            805,
                            6255999,
                            6447999,
                            "0.0.1"
                        ],
                        [
                            "2016-09-05T19:42:23Z",
                            1100,
                            8807999,
                            8751999,
                            "0.0.1"
                        ]
                    ]
                }
            ]
        }
    ]
```

**Comment by jsternberg** [comment] 2016-09-07 16:29
Does this issue continue if you stop the insertion programs? There was an issue with reinserting data in 0.13 that was related to TSM, but this also be an issue with an old key cursor seeing old data. Here's an example I got while running 4 workers:

```
> select * from testcounter where counter1 != counter2
name: testcounter
-----------------
time                    batchcounter    counter1        counter2        version
1473265400000000000     359             2879999         2879999         0.0.1

> select * from testcounter where counter1 != counter2
```

It immediately went away on the second command and the values appear to be the same. Is it possible this is due to an iterator reading an old value and then immediately clearing itself up?

**Comment by dylan-ferreira** [comment] 2016-09-07 17:33
Hi, Thanks!

Yeah, I was trying to track down another problem with unexpected negative numbers in my data and came across this.  In another test, I noticed (as you mentioned) that sometimes recently populated fields go blank, and are populated again on a subsequent query.  From this observation I wrote this new test, and yeah,  It's a bit of a blunt stick.

The rows with the issue remain after I stop the insertion program, and even survive an influxd shutdown & restart.

**Comment by jsternberg** [comment] 2016-09-07 17:39
I wonder if it's possible that you wrote two points at the same time and, since they were written at slightly different times, you got one field from one point and one field from another point that were inserted at the same time.

@jwilder is it possible for two points written at the same time to half-write each of the points?

**Comment by dylan-ferreira** [comment] 2016-09-12 02:18
Tested this with the latest v1.0.0 release on Ubuntu Trusty (same system described above) and got a couple of corrupt rows within the first 2 minutes (running 10 parallel inserters).

**Comment by jsternberg** [comment] 2016-09-16 18:54
I've confirmed with @jwilder that this is expected behavior. When you perform an insert with multiple fields, these fields are written to different series and they are not committed in the same transaction. That means, if you write to the same point, it is possible to have a race condition between writing one field and writing the second field.

**Closed by jsternberg** 2016-09-16 18:54 UTC
Labels: area/queries, area/tsm, kind/bug
