### ISSUE TITLE
panic:runtime error: invalid memory address or nil pointer dereference when filter tags

### ISSUE THREAD

**Issue by qli-aa** [influxdata/influxdb#9604] opened 2018-03-20 02:58 UTC
influxdb ver == 1.5.0

with previous version 1.4.x, I can add grafana template with below query and filter tags
SHOW TAG VALUES WITH KEY = "a" where "b" =~ /xxx/

but with influxdb 1.5.0, I got errors:
ERR: SHOW TAG VALUES WITH KEY = a WHERE b =~ /xxx/ [panic:runtime error: invalid memory address or nil pointer dereference]

**Comment by dgnorton** [comment] 2018-03-20 14:15
Duplicate of #9548 and will be fixed in 1.5.1.

**Closed by dgnorton** 2018-03-20 14:15 UTC
Labels: panic
