### ISSUE TITLE
Implement Min and Max pushdown optimization

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb#18635] opened 2020-06-22 15:31 UTC
Do everything except for the storage bits, which is a separate issue.

NOTE: Currently each planner rule uses its own feature flag for min/max. It would be simpler to consolidate those flags to be a single flag for min and a single flag for max. Meaning that each planner rule would consult the same flag for min and max respectively. 

DOD:
- End to end _test.flux tests that demonstrate correctness
- launcher test for OSS
- Pipeline for idpe
- Add test cases to verify that rule works right
- Turn on feature flag in tools, and then production clusters

**Comment by wolffcm** [comment] 2020-06-22 15:37
Deployment steps are:
- Turn on the feature flag for your user in tools. Test manually, show that it's correct, and if relevant, faster
- Once your satisfied, enable for the whole tools cluster. Let bake for an hour at least (look at queryd health dashboard)
- Deploy to production clusters, start with us-west-2, 25% of traffic. Bake for an hour
- Turn it on for all of us-west-2, let bake 1 hour
- Turn on everywhere

**Comment by jsternberg** [comment] 2020-07-23 21:22
All of the test cases for this are complete so we are going through the process of toggling the feature flags.

**Comment by jsternberg** [comment] 2020-07-24 15:04
This is on in tools and we're going to let it bake for a week before turning it on in production.

**Comment by jsternberg** [comment] 2020-07-24 15:14
This was intended to include `group |> min/max` so I'll write the tests for that and then close this.

**Comment by jsternberg** [comment] 2020-07-24 20:58
There's more extensive work to do with group so we will cover it as part of a separate issue.

**Closed by jsternberg** 2020-07-24 20:58 UTC
Labels: team/query
