### ISSUE TITLE
[0.10.0.n1454400035] Dividing by zero causes connection to close

### ISSUE THREAD

**Issue by gerrickw** [influxdata/influxdb#5523] opened 2016-02-03 03:01 UTC
Summary:
When performing a query that divides two fields and the denominator is zero it causes the connection to close unexpectedly. This is fairly annoying when creating graphs dynamically and 10 out of 40 show connection closed error as one point out of hundreds had a zero.

Steps to reproduce:
1. Submit two points on the same measurement with different field names at the same time.
2. Query such as: SELECT mean(in_rate) / mean(out_rate) from networking where pool =~ /foo$/ and time > 1454423689s and time < 1454423909s GROUP BY time(1m) fill(none)
3. Notice: In cases where out_rate has a 0, influxdb 8083 site returns, "200 OK - Could not connect to http://server:8086/
4. The same can be done by...  SELECT mean(in_rate) / 0 from networking where pool =~ /foo$/ and time > 1454423689s and time < 1454423909s GROUP BY time(1m) fill(none)

Version:
2016/02/02 16:27:36 InfluxDB starting, version 0.10.0.n1454400035, branch master, commit fd85ae5b7fada9142aac66603200e6cc124f9aed, built 2016-02-02T08:01:46.972758

**Comment by e-dard** [comment] 2016-02-03 12:38
Thanks for the report @gerrickw. Is this the first time you've seen this issue, or has it happened with previous versions of Influx?

**Comment by gerrickw** [comment] 2016-02-03 20:38
I was using a master build from a week or so ago and had the same problem. I grabbed the latest to see if the issue continued to happen.

Before this I only had one field per measurement, but was reading math can not be done between separate measurements. (Which is disappointing) But either way I was setting up graphing and noticed connection resets were happening sometimes and when researching appears to be due to zeros.

Thanks for your help.

**Comment by e-dard** [comment] 2016-02-04 18:24
Yep. Looks like infinity is not being handled properly, and the result is being attempted to be marshalled into JSON.

**Comment by seiflotfy** [comment] 2016-02-04 23:21
I am getting something similar
```
 ERR: invalid character 'j' looking for beginning of value.
```
I also think it has something to do with the JSON. Would returning a maxInt make sense?

**Comment by e-dard** [comment] 2016-02-05 00:27
> Would returning a maxInt make sense?

Probably not, since the result of dividing by zero is undefined, while max int is very much a defined number. :)

I think an error would probably be more appropriate.

**Comment by mark-rushakoff** [comment] 2016-02-05 15:01
Possible dupe of https://github.com/influxdata/influxdb/issues/5427.

**Comment by e-dard** [comment] 2016-02-05 15:16
Closing as dupe of #5427

**Closed by e-dard** 2016-02-05 15:16 UTC

**Comment by gerrickw** [comment] 2016-02-05 20:57
> Probably not, since the result of dividing by zero is undefined, while max int is very much a defined number. :)

> I think an error would probably be more appropriate.

@e-dard If this is expected to return an error, could you give a proper solution of how I should generate a percent of two metrics without the query erroring out?  To me invalid response will be the same as an error as I will have no graph.  I am wanting to generate a percent between two metrics and currently I get no result as one point out of hundreds happen to have a zero in a graph.

Thanks,
Gerrick W

**Comment by zstyblik** [comment] 2016-02-06 09:42
@gerrickw wouldn't be possible to use CQs to pre-calculate `mean()` and then `... WHERE out_rate > 0 ...`?

**Comment by gerrickw** [comment] 2016-02-09 01:36
@e-dard @zstyblik That would be slightly crazy having hundreds of measurement CQs for the only purpose of dividing two fields... Is erroring out a request really expected?  Possibly another solution could be following what the fill result should be fill(none), fill(0), fill(null), etc?  If the denominator is zero, and fill is zero it becomes zero for that point, null is null, etc?

**Comment by e-dard** [comment] 2016-02-09 15:21
@gerrickw typically you would use something like `HAVING` to filter out aggregations that don't meet certain requirements. Unfortunately Influx doesn't support that yet.

Erroring out does seem like the right thing to do, and many other DBs won't let you get a result from dividing by zero.

I think currently your best bet might be to create the CQs for your means, and then select from those result sets using a `WHERE` to filter out the `0` mean values.

**Comment by gerrickw** [comment] 2016-02-10 00:21
> Erroring out does seem like the right thing to do, and many other DBs won't let you get a result from dividing by zero.

@e-dard By database you mean time series engine then I disagree.  Influxdb isn't mysql nor postgres.  It is a timeseries database.  Graphite handles this perfectly through a query.  If we are attempting to correlate this to another SQL database there are case statements for fields. 

https://stackoverflow.com/questions/22207567/query-giving-division-by-zero-error-in-postgresql

Being as I'll be making ~6000 CQs this doesn't seem like the proper solution to me and unfortunately a blocker for me migrating to influxdb.  Is there a feature/bug/improvement request that I can file to solve this issue?

Thanks for your help
