### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb#4102] opened 2015-09-15 14:56 UTC
Hello,

InfluxDB 0.9.4 is ready to be uploaded to Debian, but the tests are not deterministic.

In Debian, we run the tests when we build the packages. It is important to us that the tests are deterministic. For example, we have infrastructure that builds packages and check for reproductibility (build twice and compare). That is just one of the many reasons why deterministic tests are important to us.

If that helps, tests have started to be flaky as of InfluxDB 0.9.3, and this was the reason I could not upload 0.9.3.

I am here to help. Please let me know if there is anything I can do.

If I can identify a group of failing tests, I can disable them (or preferably fix them) until the issue is fixed upstream.

```
--- FAIL: TestWAL_CompactAfterTimeWithoutWrite (4.55s)
    wal_test.go:346: expected first data point but got one with key: [0 0 0 0 0 0 0 5]
```

```
--- FAIL: TestServer_Query_Tags (7.99s)
    server_test.go:1312: test init failed: invalid status code: code=500, body=timeout
```

I am currently running the tests over and over again to try to identify if there is a specific group of failing tests, of if it is just general.

**Comment by otoolep** [comment] 2015-09-15 15:13
Thanks @aviau, we're trying to address this.

I have also seen the first issue, and it's not clear what is causing it. The second may be addressed by increasing the write-timeout during our tests, perhaps the underlying test framework is under load, we're not sure. I'm going to look into that.

**Comment by aviau** [comment] 2015-09-15 15:15
Whenever you find a fix, you don't have to make a new 0.9.4 release. I can simply apply a patch.

**Comment by aviau** [comment] 2015-09-15 18:49
New failure:
```
--- FAIL: TestCluster_Restart (8.71s)
    store_test.go:1158: read response size: EOF
```

**Comment by otoolep** [comment] 2015-09-15 18:52
>But a good rule of thumb is that tests should not depend on the system load.

Of course. We have some flaky tests and we're trying to hard to determine the root cause.

**Comment by otoolep** [comment] 2015-09-15 18:54
I will say we've had some luck bringing out these failures when we've artificially starved the system of CPU (cpulimit). When the system slows down the races are more easily exposed.

**Comment by otoolep** [comment] 2015-09-15 18:58
>I notice that there is a time.Sleep in this particular test(TestWAL_CompactAfterTimeWithoutWrite). It is best to replace those by code that tries to assert a state, and eventually times out.

OK, didn't know about that one. Yeah, should definitely replace that. Thanks @aviau

**Comment by jsternberg** [comment] 2016-04-07 13:17
@aviau I'm going through the backlog of tickets and found this one. It's been a long time since this ticket has been looked at, so do you know if the flaky unit tests are still there so that we can compile a list of which ones we need to fix?

Thanks.

**Comment by jsternberg** [comment] 2016-05-17 23:39
I'm going to close this due to inactivity. If you can find flaky tests and help us identify them, please open a new issue so that we can work on ensuring the unit tests are deterministic. Thanks.

**Closed by jsternberg** 2016-05-17 23:39 UTC
