### ISSUE TITLE
[Question / Feature] Grouping unknown frequency of occupancy metrics with sum and mean 

### ISSUE THREAD

**Issue by mattheworiordan** [influxdata/influxdb#7030] opened 2016-07-19 14:13 UTC
I am not sure if this is solveable currently in Influx so it's quite possibly a feature request.  Please close this issue and point me in the right direction if this is possible.
### Feature Request

**Proposal:** 

Occupancy metrics, like total connection count for example, are easily queried currently with a simple query such as `select mean(connection_count) from connections group by time(1m)`, and regardless of how many times that metric has been recorded in Influx, this will give you a fairly good idea of what the connection count was for that period.

However, if for example you had 10 routers, and each router was publishing it's own connection count, you will want to know what the average connection count was per router per period being queried, and then add those averages up i.e. two operations.

**Current behavior:** 

Take the following data:

```
ID | connection_count | time
A  | 10               | 1 Jan 2016 10:00:00
B  | 15               | 1 Jan 2016 10:00:01
C  | 20               | 1 Jan 2016 10:00:02
A  | 10               | 1 Jan 2016 10:00:10
B  | 15               | 1 Jan 2016 10:00:11
C  | 20               | 1 Jan 2016 10:00:12
A  | 10               | 1 Jan 2016 10:00:20
B  | 15               | 1 Jan 2016 10:00:21
C  | 20               | 1 Jan 2016 10:00:22
```

If you wanted to know what the total connection count was for that 1m period, you could either do:

```
select sum(connection_count) from from connections group by time(1m)
```

which would give you `180`, the wrong figure.  The connection count is 45.

Or you could use mean:

```
select mean(connection_count) from from connections group by time(1m)
```

but would give you `15` which too is the wrong figure.

**Desired behavior:**

Ideally what you need is a way to group and sum, and allow that to be returned as a total.  So pseudo query such as 

```
select sum(select mean(connection_count) as connection_count, time from from connections group by ID, time(1m)) group by time(1m)
```

Clearly that is the WRONG syntax, but I think it demonstrates the requirement.

**Use case:** 

Because currently without this there is no sensible way to calculate occupancy metrics i.e. absolute values.  For example, in Grafana we need to query the above but grouped by data centre. This is unfortunately not possible because the grouping by data_centre either sums or means the values from each router.

**Comment by jsternberg** [comment] 2016-08-01 18:42
I think this is a duplicate of #4619.

**Closed** 2016-11-17 06:48 UTC
