### ISSUE TITLE
Backup and restore -portable not restoring users after disaster

### ISSUE THREAD

**Issue by rda0** [influxdata/influxdb#9685] opened 2018-04-05 20:48 UTC
### Bug report

__System info:__ InfluxDB v1.5.1 (pre-built pkg), 64-bit Debian 9.4 (stretch)

Please note, I am a new InfluxDB user and may have done some things wrong:

1. Setup the backup using the recommended `-portable` method, make a backup
2. Read about the TSI feature, enabled it and convert the database 
3. Start InfluxDB, no more data shown in Grafana, errors shown in logs
4. Stop InfluxDB, remove data, restart InfluxDB, restore from backup
5. No data shown in Grafana, because no users are defined
6. Manually re-create users
7. All seems good

__Steps to reproduce:__

1. Backup: `# /usr/bin/influxd backup -portable /var/backups/influxdb/20180405-001501`

2. Enable TSI in config: `index-version = "tsi1"`

3. Restart, stop and build tsi:

```
# systemctl restart influxd
# systemctl stop influxd
# cd /var/lib/influxdb/
# influx_inspect buildtsi -datadir /var/lib/influxdb/data -waldir /var/lib/influxdb/wal
```

[build_tsi.txt](https://github.com/influxdata/influxdb/files/1881705/build_tsi.txt)
[tree.txt](https://github.com/influxdata/influxdb/files/1881710/tree.txt)
[log.txt](https://github.com/influxdata/influxdb/files/1881730/log.txt)

4. Disable TSI: `# index-version = "inmem"`

```
# systemctl restart influxd
# systemctl stop influxdb.service
# rm -r data/ meta/ wal/
# systemctl restart influxd
# influxd restore -portable /var/backups/influxdb/20180405-001501
2018/04/05 21:14:08 Meta info not found for shard 9 on database _internal. Skipping shard file 20180404T221501Z.s9.tar.gz
2018/04/05 21:14:08 Meta info not found for shard 12 on database _internal. Skipping shard file 20180404T221501Z.s12.tar.gz
2018/04/05 21:14:08 Meta info not found for shard 13 on database _internal. Skipping shard file 20180404T221501Z.s13.tar.gz
2018/04/05 21:14:08 Meta info not found for shard 15 on database _internal. Skipping shard file 20180404T221501Z.s15.tar.gz
2018/04/05 21:14:08 Restoring shard 14 live from backup 20180404T221501Z.s14.tar.gz
2018/04/05 21:14:43 Meta info not found for shard 8 on database _internal. Skipping shard file 20180404T221501Z.s8.tar.gz
2018/04/05 21:14:43 Meta info not found for shard 11 on database _internal. Skipping shard file 20180404T221501Z.s11.tar.gz
2018/04/05 21:14:43 Meta info not found for shard 18 on database _internal. Skipping shard file 20180404T221501Z.s18.tar.gz
2018/04/05 21:14:43 Restoring shard 5 live from backup 20180404T221501Z.s5.tar.gz
2018/04/05 21:15:55 Meta info not found for shard 7 on database _internal. Skipping shard file 20180404T221501Z.s7.tar.gz
# systemctl restart influxd
```

5. No users shown:

```
# influx
Connected to http://localhost:8086 version 1.5.1
InfluxDB shell version: 1.5.1
> show users
ERR: error authorizing query: create admin user first or disable authentication
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> show databases
ERR: error authorizing query: create admin user first or disable authentication
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

6. Create users manually:

```
# influx
Connected to http://localhost:8086 version 1.5.1
InfluxDB shell version: 1.5.1
> CREATE USER isg WITH PASSWORD 'secret' WITH ALL PRIVILEGES
> CREATE USER rda WITH PASSWORD 'secret'
> GRANT ALL ON rda TO rda
```

__Expected behavior:__ InfluxDB is exactly the same after a restore, as before I destroyed it.

__Actual behavior:__ Users are not restored

__Additional info:__ `/etc/influxdb/influxdb.conf`:

```
reporting-disabled = true
[meta]
  dir = "/var/lib/influxdb/meta"
[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  wal-fsync-delay = "100ms"
  query-log-enabled = true
[coordinator]
[retention]
[shard-precreation]
[monitor]
[http]
  bind-address = "127.0.0.1:8086"
  auth-enabled = true
  realm = "InfluxDB"
  access-log-path = "/var/log/influxdb/access.log"
[ifql]
[logging]
[subscriber]
[[graphite]]
[[collectd]]
[[opentsdb]]
[[udp]]
[continuous_queries]
```

**Comment by rda0** [comment] 2018-04-06 06:28
Is it possible to restore the metadir from a (`-portable`) backup? Can't seem to find a way to do this. I see the `20180404T163203Z.meta` file and looks like it contains some password hashes.

Or do I need a legacy backup for what I want? I successfully restored as follows:

```
influxd backup /var/backups/influxdb/legacy
influxd backup -database _internal /var/backups/influxdb/legacy
influxd backup -database rda /var/backups/influxdb/legacy
systemctl stop influxdb
rm -r /var/lib/influxdb/*
systemctl start influxdb
systemctl stop influxdb
influxd restore -metadir /var/lib/influxdb/meta /var/backups/influxdb/legacy
influxd restore -database _internal -datadir /var/lib/influxdb/data /var/backups/influxdb/legacy
influxd restore -database rda -datadir /var/lib/influxdb/data /var/backups/influxdb/legacy
chown -R influxdb:influxdb /var/lib/influxdb/*
systemctl start influxdb
```

**Comment by dgnorton** [comment] 2018-04-09 14:26
@rda0 backup / restore handles the data but not the users. If it's something you do often or want to ensure quick recovery, you could maintain a script that creates users and permissions.

**Comment by dgnorton** [comment] 2018-04-10 12:30
@rda0 I'm closing this issue since that is the expected behavior for backup / restore regarding users.

**Closed by dgnorton** 2018-04-10 12:30 UTC

**Comment by rda0** [comment] 2018-04-13 07:27
Yes, thank you. I was just expecting backup / restore also handles users, because I saw user info in the `.meta` file. While I hope it is never needed, we need to be able to do:
- disaster recovery in the worst case
- restore a database online incl. users and permissions

Here are [some scripts](https://influxdb.phys.ethz.ch/backup_restore.html) that should help do this quickly using the legacy method. Users and permissions are saved, but have to be restored manually.

## Backup

```bash
#!/bin/bash

# Load influx credentials
if [ -f ~/.influx_admin ]; then
  . ~/.influx_admin
fi

BACKUPDIR="/var/backups/influxdb"
DATE="$(date +%Y%m%d-%H%M%S)"
FORMATS="json csv column"

umask 077

mkdir -p "${BACKUPDIR}/${DATE}"
mkdir -p "${BACKUPDIR}/${DATE}/meta"
mkdir -p "${BACKUPDIR}/${DATE}/data"
mkdir -p "${BACKUPDIR}/${DATE}/user"

USERS="$(/usr/bin/influx -format=csv -execute "show users" | tail -n +2 | cut -d',' -f1)"
DATABASES="$(/usr/bin/influx -format=csv -execute "show databases" | tail -n +2 | cut -d',' -f2)"

echo "backup users..."

echo "${USERS}" > "${BACKUPDIR}/${DATE}/user/users"
echo "${DATABASES}" > "${BACKUPDIR}/${DATE}/user/databases"

for FORMAT in ${FORMATS};
do
  /usr/bin/influx -format="${FORMAT}" -execute "show users" > "${BACKUPDIR}/${DATE}/user/users.${FORMAT}"
  /usr/bin/influx -format="${FORMAT}" -execute "show databases" > "${BACKUPDIR}/${DATE}/user/databases.${FORMAT}"
done

for USER in ${USERS};
do
  for FORMAT in ${FORMATS};
  do
    /usr/bin/influx -format="${FORMAT}" -execute "show grants for ${USER}" > "${BACKUPDIR}/${DATE}/user/grants_${USER}.${FORMAT}"
  done
done

echo "backup database meta..."

/usr/bin/influxd backup "${BACKUPDIR}/${DATE}/meta"

for DB in ${DATABASES};
do
  echo "backup database ${DB}..."
  mkdir -p "${BACKUPDIR}/${DATE}/data/${DB}"
  /usr/bin/influxd backup -database "${DB}" "${BACKUPDIR}/${DATE}/data/${DB}"
done
```

## Restore offline

```bash
#!/bin/bash

BACKUPDIR="${1}"
TARGETDIR="/var/lib/influxdb"
DATABASES=$(<"${BACKUPDIR}/user/databases")

print_usage() {
  echo -e "Usage: ${0} backupdir"
  echo -e "\n    Full InfluxDB offline restore."
  echo -e "\nOptions:\n"
  echo "    backupdir"
  echo "        Backup directory"
}

if [ "$#" -lt 1 ] || [ "$#" -gt 1 ]; then
  print_usage
  exit 1
fi

echo "This will restore InfluxDB:"
echo "from:  ${BACKUPDIR}"
echo "to:    ${TARGETDIR}"
echo

read -p "Are you absolutely sure? [y/N]" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo
  echo "restore database meta..."
  
  /usr/bin/influxd restore -metadir "${TARGETDIR}/meta" "${BACKUPDIR}/meta"
  
  for DB in ${DATABASES};
  do
    echo "restore database ${DB}..."
    /usr/bin/influxd restore -database "${DB}" -datadir "${TARGETDIR}/data" "${BACKUPDIR}/data/${DB}"
  done
  
  chown -R influxdb:influxdb "${TARGETDIR}"/*
else
  echo
  echo "aborted."
fi
```

## Restore database online

```bash
#!/bin/bash

BACKUPDIR="${1}"
DB="${2}"
DB_NEW="${3}"

print_usage() {
  echo -e "Usage: ${0} backupdir database [new_database]"
  echo -e "\n    Single InfluxDB online database restore."
  echo -e "\nOptions:\n"
  echo "    backupdir"
  echo "        Backup directory"
  echo "    database"
  echo "        Database to restore from"
  echo "    new_database"
  echo "        Database to restore to (if different than from)"
}

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  print_usage
  exit 1
fi

echo "This will restore (online) InfluxDB database:"
echo "name:  ${DB}"
if [ "$#" -eq 3 ]; then
  echo "to:    ${DB_NEW}"
fi
echo "from:  ${BACKUPDIR}/data/${DB}"
echo

read -p "Are you sure? [y/N]" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo
  
  if [ "$#" -eq 2 ]; then
    echo "restore database ${DB}..."
    /usr/bin/influxd restore -online -db "${DB}" "${BACKUPDIR}/data/${DB}"
  elif [ "$#" -eq 3 ]; then
    echo "restore database ${DB} to ${DB_NEW}..."
    /usr/bin/influxd restore -online -db "${DB}" -newdb "${DB_NEW}" "${BACKUPDIR}/data/${DB}"
  fi

  echo  
  echo "grant privileges manually ('GRANT priv ON db TO user'):"
  echo "user:db,priv"
  echo "------------"
  grep -E "^${DB}\b" "${BACKUPDIR}"/user/grants_*.csv | sed -e 's/.*user\/grants_//g' -e 's/\.csv//g'
else
  echo
  echo "aborted."
fi
```

**Comment by lafrech** [comment] 2020-12-09 15:54
> I'm closing this issue since that is the expected behavior for backup / restore regarding users.

I don't mean to rant but this might be useful to mention (if not highlight) in the docs because users may expect metadata backup to contain all needed information to restore users and permissions. Especially since there is no other straightforward migration feature documented.

The feature would be nice, of course, but at least mentioning this "limitation" in the docs would prevent users from a bad surprise.

@rda0 Thanks for sharing.
