### ISSUE TITLE
[cloud/v3] Casting BIGINT to TIMESTAMP doesn't seem to work anymore

### ISSUE THREAD

**Issue by NotiArie** [influxdata/influxdb#24581] opened 2024-01-18 16:03 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Open data explore on InfluxDB Cloud
2. Execute the folowing query: SELECT 1705590600000000000::TIMESTAMP

__Expected behaviour:__
I would expect a timestamp

__Actual behaviour:__
An exception is thrown:
Error while planning query: Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Compute error: Overflow happened on: 1705590600000000000 * 1000000000: rpc error: code = InvalidArgument desc = Error while planning query: Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Compute error: Overflow happened on: 1705590600000000000 * 1000000000

__Environment info:__

* InfluxDB Cloud

As workaround I use the following query:
SELECT 1705590600000000000::BIGINT UNSIGNED::TIMESTAMP

On older versions of InfluxDB, unsigned big ints are not allowed to cast to timestamp

**Comment by philjb** [comment] 2024-02-06 16:43
@btasker - this is reported as a issue in cloud serverless.

**Comment by btasker** [comment] 2024-02-06 17:25
This looks like a SQL issue (it's being run via the Cloud UI which doesn't accept InfluxQL) so doesn't fall under my purview. 

I've flagged up internally.

**Comment by helenosheaa** [comment] 2024-02-12 17:37
The Cloud UI does accept InfluxQL as well these days but anyway I think the problem is _probably_ coming from InfluxQL-IOx, when direct casting an integer using ::timestamp IOx will default to treat it as seconds (we will work on fixing this)

@NotiArie Workaround in the meantime would be to use [to_timestamp_seconds](https://docs.influxdata.com/influxdb/cloud-dedicated/reference/sql/functions/time-and-date/#to_timestamp_seconds) or [to_timestamp_mills](https://docs.influxdata.com/influxdb/cloud-dedicated/reference/sql/functions/time-and-date/#to_timestamp_millis) etc to explicitly specify the precision to use.

**Comment by mhilton** [comment] 2024-02-21 10:48
This was changed in datafusion (the query engine used by influxdb v3) in [November](https://github.com/apache/arrow-datafusion/pull/8193). The stated intention being to make `timestamp` conversions behave consistently, and be consistent with the same queries run in postgresql.

If you need subsecond accuracy for your timestamps then the functions [`to_timestamp_millis`](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#to-timestamp-millis),  [`to_timestamp_micros`](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#to-timestamp-micros), or [`to_timestamp_nanos`](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#to-timestamp-nanos) can be used to perform explicit conversions.

**Comment by NotiArie** [comment] 2024-02-21 15:03
Thanks, 
Both functions to_timestamp and to_timestamp_nanos work fine and are returning the timestamp with nanoseconds precision.

BTW, funny thing is that SELECT 1705590600000000000::BIGINT UNSIGNED::TIMESTAMP does work even with negative numbers.

**Comment by helenosheaa** [comment] 2024-02-21 16:30
thanks for the report, as theres a workaround and this was a change in Datafusion closing this as there's no further action needed

**Closed by helenosheaa** 2024-02-21 16:30 UTC
Labels: v3
