### ISSUE TITLE
Allow using log scale with Y-axis

### ISSUE THREAD

**Issue by dsnet** [influxdata/influxdb#23005] opened 2021-12-18 01:17 UTC
Environment info:
* System info: Linux 4.15.0-163-generic
* InfluxDB version: InfluxDB 2.1.1
* Other relevant environment details: n/a

![image](https://user-images.githubusercontent.com/6354026/146624029-3f9b0fcd-5d3d-49a0-83c5-fd01a2c2c43b.png)

The Y-axis is by default in linear scale. Could an option be provided that scales the Y-axis logarithmically? This makes it so that series with large values do not overwhelm series with small values.

**Comment by timhallinflux** [comment] 2022-02-01 18:43
this is a duplicate of https://github.com/influxdata/influxdb/issues/20551

Closing in favor of that issue.

**Closed by timhallinflux** 2022-02-01 18:43 UTC
