### ISSUE TITLE
panic: segmentation violation code=0x1 in roaring.localintersect2by2

### ISSUE THREAD

**Issue by caihuanong** [influxdata/influxdb#10609] opened 2019-01-04 02:48 UTC
__System info: __ InfluxDB shell version: 1.7.2, Centos 6 x86_64 GNU/Linux,

__Steps to reproduce:__  some select after upgrate from 1.3.7 to 1.7.2, I use the comand "influx_inspect buildtsi -database cube -max-cache-size 10073741824 -max-log-file-size 10485760 -datadir /opt/influxdb/data -waldir /opt/influxdb/wal" to change my db to tsi type, but I have not changed the _internal

__Expected behavior:__  no panic

__Additional info:__
ts=2019-01-04T02:29:12.582516Z lvl=info msg="Executing query" log_id=0CmfNe40000 service=query query="SELECT mean(incr) AS avg FROM cube_cloud.thirtydays.if_octets_rx WHERE _tenant_id =~ /^(039da7a214e54456bf17d5dcc190195b)$/ AND _namespace =~ /^(netmonitor)$/ AND host_port =~ /^(SH-YY-2-B06-NE40-C-EXT_GigabitEthernet2_0_7)$/ AND time >= '2019-01-04T01:59:00Z' AND time < '2019-01-04T02:29:00Z' GROUP BY *, time(1m) LIMIT 14400"
unexpected fault address 0x7f7de9b953fd
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f7de9b953fd pc=0x97ed4d]

goroutine 643753 [running]:
runtime.throw(0x11fcfa4, 0x5)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc3cee7a510 sp=0xc3cee7a4e0 pc=0x42df92
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc3cee7a560 sp=0xc3cee7a510 pc=0x443895
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.localintersect2by2(0x7f7de9b953fd, 0x1, 0x12f251, 0x7f7de9b825a9, 0x1, 0x13897b, 0xc1854b91bc, 0x0, 0x1, 0x11)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/setutil.go:330 +0x2d fp=0xc3cee7a570 sp=0xc3cee7a560 pc=0x97ed4d
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.intersection2by2(0x7f7de9b953fd, 0x1, 0x12f251, 0x7f7de9b825a9, 0x1, 0x13897b, 0xc1854b91bc, 0x0, 0x1, 0x2)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/setutil.go:255 +0x121 fp=0xc3cee7a5d0 sp=0xc3cee7a570 pc=0x97ea71
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).andArray(0xc22cb452c0, 0xc20e787140, 0x137c9a0, 0xc39e1e6820)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:807 +0x109 fp=0xc3cee7a648 sp=0xc3cee7a5d0 pc=0x950e29
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.(*arrayContainer).and(0xc22cb452c0, 0x137c9a0, 0xc20e787140, 0x137c9a0, 0xc39e1e6820)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/arraycontainer.go:506 +0x22a fp=0xc3cee7a690 sp=0xc3cee7a648 pc=0x94f33a
github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring.And(0xc40686b7a0, 0xc40686b8f0, 0xc39e1e64e0)
        /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/roaring/roaring.go:1005 +0x122 fp=0xc3cee7a720 sp=0xc3cee7a690 pc=0x961e62
github.com/influxdata/influxdb/tsdb.(*SeriesIDSet).And(0xc39e1e64a0, 0xc39e1e64e0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/series_set.go:170 +0xba fp=0xc3cee7a750 sp=0xc3cee7a720 pc=0x9a862a
github.com/influxdata/influxdb/tsdb.IntersectSeriesIDIterators(0x7f50a5904948, 0xc39e1e64c0, 0x7f50a5904948, 0xc39e1e6500, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:527 +0x18c fp=0xc3cee7a7c8 sp=0xc3cee7a750 pc=0x98a91c
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc3b97f92b0, 0x1, 0x1, 0xc00003a820, 0x0, 0x0, 0x0, 0xc1854b9170, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1970 +0x258 fp=0xc3cee7a880 sp=0xc3cee7a7c8 pc=0x9948a8
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc3b97f92b0, 0x1, 0x1, 0xc00003a820, 0x0, 0x0, 0x0, 0xc1854b9170, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1954 +0xf7 fp=0xc3cee7a938 sp=0xc3cee7a880 pc=0x994747
github.com/influxdata/influxdb/tsdb.IndexSet.measurementSeriesByExprIterator(0xc3b97f92b0, 0x1, 0x1, 0xc00003a820, 0x0, 0x0, 0x0, 0xc1854b9170, 0xc, 0x10, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:1893 +0xb1 fp=0xc3cee7a9f8 sp=0xc3cee7a938 pc=0x993e51
github.com/influxdata/influxdb/tsdb.IndexSet.TagSets(0xc3b97f92b0, 0x1, 0x1, 0xc00003a820, 0x0, 0x0, 0x0, 0xc00003a820, 0xc1854b9170, 0xc, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/index.go:2545 +0xef fp=0xc3cee7acc8 sp=0xc3cee7a9f8 pc=0x99a7ff
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createCallIterator(0xc0812ca900, 0x1361780, 0xc0d01b5800, 0xc18d9205f0, 0xc, 0xc0d01b5920, 0x135e500, 0xc0d01b5920, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2378 +0x264 fp=0xc3cee7aef0 sp=0xc3cee7acc8 pc=0xed1d34
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc0812ca900, 0x1361780, 0xc0d01b5800, 0xc18d9205f0, 0xc, 0x135e500, 0xc0d01b5920, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:2339 +0x379 fp=0xc3cee7b1e0 sp=0xc3cee7aef0 pc=0xed1479
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc000d3e000, 0x1361780, 0xc0d01b5800, 0xc104ea49b0, 0x135e500, 0xc0d01b5920, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:861 +0x120 fp=0xc3cee7b390 sp=0xc3cee7b1e0 pc=0x9adbe0
github.com/influxdata/influxdb/tsdb.Shards.CreateIterator(0xc39e1560e0, 0x1, 0x1, 0x1361780, 0xc0d01b5800, 0xc104ea49b0, 0x135e500, 0xc0d01b5920, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/tsdb/shard.go:1305 +0x13a fp=0xc3cee7b550 sp=0xc3cee7b390 pc=0x9b12fa
github.com/influxdata/influxdb/tsdb.(*Shards).CreateIterator(0xc36d5cc8e0, 0x1361780, 0xc0d01b5800, 0xc104ea49b0, 0x135e500, 0xc0d01b5920, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb5 fp=0xc3cee7b6b0 sp=0xc3cee7b550 pc=0x9cf9c5
github.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc3f9d7e300, 0x1361780, 0xc0d01b5800, 0xc104ea49b0, 0x135e500, 0xc0d01b5920, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:208 +0x3d5 fp=0xc3cee7b870 sp=0xc3cee7b6b0 pc=0xa6e375
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xc3cee7ce98, 0x1361780, 0xc0d01b5800, 0xc3cee7bcf8, 0xc3cee7bcb0, 0xc0d01b5920, 0x1, 0x1)
        /go/src/github.com/influxdata/influxdb/query/select.go:581 +0x13a fp=0xc3cee7bb58 sp=0xc3cee7b870 pc=0x8f43aa
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc1a75dae98, 0x1361780, 0xc0d01b5800, 0xc0d01b5920, 0x135e500, 0xc0d01b5920, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:605 +0xd5 fp=0xc3cee7bcd8 sp=0xc3cee7bb58 pc=0x8e1d55
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xc0d01b5920, 0x1361780, 0xc0d01b5800, 0xc1a75dae98, 0xc1a75da378, 0x3, 0x4, 0x0, 0xc1a75e2180)
        /go/src/github.com/influxdata/influxdb/query/select.go:513 +0xd0 fp=0xc3cee7bf80 sp=0xc3cee7bcd8 pc=0x8f33a0
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc3cee7ce98, 0x1361780, 0xc0d01b5800, 0xc0d01b5920, 0x2030e7, 0x2030e7, 0x4214a8, 0xc39e1e61a0)
        /go/src/github.com/influxdata/influxdb/query/select.go:557 +0xd41 fp=0xc3cee7ce48 sp=0xc3cee7bf80 pc=0x8debb1
github.com/influxdata/influxdb/query.buildExprIterator(0x1361780, 0xc0d01b5800, 0x135e500, 0xc0d01b5920, 0x7f50a59048f8, 0xc3f9d7e300, 0xc39e1a44e0, 0x1, 0x1, 0x135e500, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:154 +0x1f4 fp=0xc3cee7cfd8 sp=0xc3cee7ce48 pc=0x8ddb44
github.com/influxdata/influxdb/query.buildFieldIterator(0x1361780, 0xc0d01b5800, 0x135e500, 0xc0d01b5920, 0x7f50a59048f8, 0xc3f9d7e300, 0xc39e1a44e0, 0x1, 0x1, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:851 +0x44b fp=0xc3cee7d1d0 sp=0xc3cee7cfd8 pc=0x8e47bb
github.com/influxdata/influxdb/query.buildCursor(0x1361780, 0xc0d01b5800, 0xc34155fa00, 0x7f50a59048f8, 0xc3f9d7e300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:736 +0xc7c fp=0xc3cee7d660 sp=0xc3cee7d1d0 pc=0x8e2b9c
github.com/influxdata/influxdb/query.(*preparedStatement).Select(0xc19d815340, 0x1361780, 0xc0d01b5800, 0x1363880, 0x1d43138, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/query/select.go:119 +0x180 fp=0xc3cee7d8e0 sp=0xc3cee7d660 pc=0x8dd7a0
github.com/influxdata/influxdb/query.Select(0x1361940, 0xc39e19e0c0, 0xc34155f700, 0x134bac0, 0xc00059cfc0, 0x1363880, 0x1d43138, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/select.go:96 +0xfe fp=0xc3cee7d968 sp=0xc3cee7d8e0 pc=0x8dd58e
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc0001e3c00, 0x1361940, 0xc39e19e0c0, 0xc34155f700, 0xc330566f0f, 0xa, 0x0, 0x0, 0x1363880, 0x1d43138, ...)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:638 +0x113 fp=0xc3cee7da20 sp=0xc3cee7d968 pc=0xa74313
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc0001e3c00, 0xc34155f700, 0xc39e19e0c0, 0x0, 0x0)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:542 +0x99 fp=0xc3cee7dbc8 sp=0xc3cee7da20 pc=0xa736a9
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc0001e3c00, 0x1362640, 0xc34155f700, 0xc39e19e0c0, 0x1, 0x1)
        /go/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:64 +0x2400 fp=0xc3cee7dce8 sp=0xc3cee7dbc8 pc=0xa71120
github.com/influxdata/influxdb/query.(*Executor).executeQuery(0xc0004ac0f0, 0xc36d5cc400, 0xc330566f0f, 0xa, 0x0, 0x0, 0x1363880, 0x1d43138, 0x2710, 0x0, ...)
        /go/src/github.com/influxdata/influxdb/query/executor.go:334 +0x355 fp=0xc3cee7df68 sp=0xc3cee7dce8 pc=0x883f15
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc3cee7df70 sp=0xc3cee7df68 pc=0x45d9c1
created by github.com/influxdata/influxdb/query.(*Executor).ExecuteQuery
        /go/src/github.com/influxdata/influxdb/query/executor.go:236 +0xc9

**Comment by e-dard** [comment] 2019-01-07 17:30
Closing as duplicate of #10529.

**Closed by e-dard** 2019-01-07 17:30 UTC
Labels: panic
