### ISSUE TITLE
partitioned results

### ISSUE THREAD

**Issue by r0bj** [influxdata/influxdb#7252] opened 2016-09-01 16:37 UTC
### Bug report

__System info:__
influxdb: 1.0.0~rc1
OS: ubuntu 14.04

__Steps to reproduce:__

host1 data:
```
> SELECT last("used") FROM "mem" WHERE "host" =~ /^(memcache-s1)$/ AND "dc" =~ /SJC$/ AND time > 1472687966s and time < 1472688024s GROUP BY time(10s), "host", "dc" fill(0)

name: mem
tags: dc=SJC, host=memcache-s1
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	25384742912
1472687980000000000    	25384648704
1472687990000000000    	25386901504
1472688000000000000    	25385308160
1472688010000000000    	25389359104
1472688020000000000    	25392300032
```

host2 data:
```
> SELECT last("used") FROM "mem" WHERE "host" =~ /^(memcache-s2)$/ AND "dc" =~ /SJC$/ AND time > 1472687966s and time < 1472688024s GROUP BY time(10s), "host", "dc" fill(0)

name: mem
tags: dc=SJC, host=memcache-s2
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	59788009472
1472687980000000000    	59793158144
1472687990000000000    	59789357056
1472688000000000000    	59788029952
1472688010000000000    	59787685888
1472688020000000000    	59786649600
```

So far so good.
But combining those two hosts within regex I'm getting:
```
> SELECT last("used") FROM "mem" WHERE "host" =~ /^(memcache-s1|memcache-s2)$/ AND "dc" =~ /SJC$/ AND time > 1472687966s and time < 1472688024s GROUP BY time(10s), "host", "dc" fill(0)
name: mem
tags: dc=SJC, host=memcache-s1
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	25384742912
1472687980000000000    	25384648704
1472687990000000000    	25386901504
1472688000000000000    	0
1472688010000000000    	0
1472688020000000000    	0

name: mem
tags: dc=SJC, host=memcache-s2
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	59788009472
1472687980000000000    	59793158144
1472687990000000000    	59789357056
1472688000000000000    	0
1472688010000000000    	0
1472688020000000000    	0

name: mem
tags: dc=SJC, host=memcache-s1
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	0
1472687980000000000    	0
1472687990000000000    	0
1472688000000000000    	25385308160
1472688010000000000    	25389359104
1472688020000000000    	25392300032

name: mem
tags: dc=SJC, host=memcache-s2
time   			last
----   			----
1472687960000000000    	0
1472687970000000000    	0
1472687980000000000    	0
1472687990000000000    	0
1472688000000000000    	59788029952
1472688010000000000    	59787685888
1472688020000000000    	59786649600
```

Somehow data are split into four hosts.
Ploting graph with those results is giving strange results as we can expect.

Is there any rational explanation behind this?

**Comment by jsternberg** [comment] 2016-09-01 16:58
Duplicate of #7220. We reverted the change that caused this and rc2 should be fine. Thanks!

**Closed by jsternberg** 2016-09-01 16:58 UTC
