### ISSUE TITLE
Telegraf data through UDP fail to parse

### ISSUE THREAD

**Issue by hcsaustrup** [influxdata/influxdb#8785] opened 2017-09-04 12:45 UTC
We've got a bunch of nodes configured with Telegraf, shipping metrics off to InfluxDB through UDP. We have noticed that they're not being parsed correctly, even though the contents look find when inspected with tcpdump/wireshark. This works fine with TCP, but we see significant performance improvements when using UDP, so we'd like to stick to this if possible.

Eamples:

``
Failed to parse points: unable to parse 'system,role=platform_api,***=devops,cluster=devops,***=***,name=***,host=***,***=platform_api  10:25" 1504528280000000000': invalid field format service=udp
``
``
Failed to parse points: unable to parse 'system,host=***,name=***,***=***,cluster=devops,role=platform_api,***=***,***=platform_api uptime_format="21 days 1504528300000000000': unbalanced quotes service=udp
``

Is I look in the actual packet being submitted, it looks kind of like this (not exactly the same data, but close):

``
system,***=go_server,***=***,name=***,host=***,role=go_server,cluster=gocd,***=gocd uptime=1852144i,uptime_format="21 days, 10:29" 1504528510000000000
``

Obviously there is some faulty chopping up and gluing together going on here ;-)

Versions:

telegraf-1.3.5-1.x86_64 (also tested 1.2.0, 1.3.0 and nightly (20170905) - same result)
influxdb-1.3.5-1.x86_64
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by phemmer** [comment] 2017-09-04 16:38
You have to escape the spaces in tags. See https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#special-characters

> For tag keys, tag values, and field keys always use a backslash character \ to escape:
> commas ,
> equal signs =
> spaces

Also from the same doc slight above:

> Line Protocol allows users to double and single quote measurement names, tag keys, tag values, and field keys. It will, however, assume that the double or single quotes are part of the name, key, or value.

**Comment by phemmer** [comment] 2017-09-04 16:42
Nevermind. I misread the provided data.

**Comment by danielnelson** [comment] 2017-09-15 01:27
This was caused by a bug in Telegraf and was fixed in 1.4.0.

**Closed by danielnelson** 2017-09-15 01:27 UTC
