### ISSUE TITLE
influxdb systemd daemon fails to start up again after offline compaction

### ISSUE THREAD

**Issue by codyshepherd** [influxdata/influxdb#21757] opened 2021-06-28 22:33 UTC
There are a lot of moving parts to this reproducer, but I haven't found an easier way to quickly run the 1.8.6 deb with influx_tools on the latest Ubuntu LTS image. 

__Steps to reproduce:__

1. Launch a VM running the latest Ubuntu 20.04, I used AWS running ami-03d5c68bab01f3496, but e.g. a Multipass VM should work as well
2. ssh to the VM and follow [installation instructions](https://docs.influxdata.com/influxdb/v1.8/introduction/install/) to install influxdb 1.8.6
3. Confirm the daemon has started correctly: `systemctl status influxdb`
4. on the VM, download and setup go and libc6, the latter of which is required for influx_tools to work on the host (an alternate to hacking around libc6 could be to install the influxdb deb on a more recent Ubuntu release, but ~repos.influxdb.com is not configured to support releases more recent than Focal~ although repos now support groovy & hirsute, using the LTS still seems like the best course): 
```
sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/groovy.list                    
sudo sed -i 's/focal/groovy/g' /etc/apt/sources.list.d/groovy.list                   
sudo apt-get update                                   
sudo apt-get install -y libc6 -t groovy
```

<choose YES option in ncurses menu>

```
go_version=$(curl https://golang.org/VERSION?m=text)                            
go_endpoint="$go_version.linux-amd64.tar.gz"                                    
                                                                                  
wget "https://dl.google.com/go/$go_endpoint" -O "/home/ubuntu/$go_endpoint"     
sudo rm -rf /usr/local/go                                                            
sudo tar -C /usr/local -xzf "/home/ubuntu/$go_endpoint"
export GOPATH=/home/ubuntu/go/bin
export PATH=$PATH:/usr/local/go/bin:$GOPATH
```
5. Clone influxdb repo, checkout out `1.8`, and build the `influx_tools` binary -- this can be done either on the VM or on a local machine, and the binary scped to the host:
```
git clone https://github.com/influxdata/influxdb.git
cd influxdb
git checkout -b 1.8 origin/1.8
go build -o influx_tools ./cmd/influx_tools/
```
6. Follow [instructions to create NOAA_water_database and add sample data](https://docs.influxdata.com/influxdb/v1.8/query_language/sample-data/). Note that generating hot shards will require more data than this. Additional data can be added to the DB via: `i=0; while [ $i -lt 10000 ]; do curl -i -XPOST "http://localhost:8086/write?db=NOAA_water_database" --data-binary "weather,location=us-midwest temperature=82 14658$i"; i=$((i+1)); done`
7. Take the database offline: `sudo systemctl stop influxdb`
8. Confirm the daemon has stopped: `systemctl status influxdb`
9. Run an offline compaction: 
```
shards=$(sudo find /var/lib/influxdb/data/NOAA_water_database/autogen/ -maxdepth 1 -mindepth 1)

for shard in $shards; do echo $shard; if [ "$(sudo find $shard -maxdepth 1 -type f | grep -i '.*\.tsm')"  ]; then sudo /home/ubuntu/influx_tools compact-shard -force -verbose -path $shard; else echo "no shard"; fi done
```
10. Try to restart influxdb: `sudo systemctl start influxdb`

__Expected behavior:__
The influxdb daemon starts up successfully

__Actual behavior:__
The influxdb daemon fails to start.

Output of `systemctl status influxdb`:

```
● influxdb.service - InfluxDB is an open-source, distributed, time series database
     Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-06-28 22:20:57 UTC; 4s ago
       Docs: https://docs.influxdata.com/influxdb/
    Process: 33405 ExecStart=/usr/bin/influxd -config /etc/influxdb/influxdb.conf $INFLUXD_OPTS (code=exited, status=217/USER)
   Main PID: 33405 (code=exited, status=217/USER)

Jun 28 22:20:57 ip-172-31-3-128 systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 5.
Jun 28 22:20:57 ip-172-31-3-128 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Jun 28 22:20:57 ip-172-31-3-128 systemd[1]: influxdb.service: Start request repeated too quickly.
Jun 28 22:20:57 ip-172-31-3-128 systemd[1]: influxdb.service: Failed with result 'exit-code'.
Jun 28 22:20:57 ip-172-31-3-128 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.
```

Output after editing /lib/systemd/system/influxdb.service to set `Restart=no` and running `sudo systemctl daemon-reload; sudo systemctl start influxdb`:

```
● influxdb.service - InfluxDB is an open-source, distributed, time series database
     Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-06-28 22:23:29 UTC; 2s ago
       Docs: https://docs.influxdata.com/influxdb/
    Process: 33466 ExecStart=/usr/bin/influxd -config /etc/influxdb/influxdb.conf $INFLUXD_OPTS (code=exited, status=217/USER)
   Main PID: 33466 (code=exited, status=217/USER)

Jun 28 22:23:29 ip-172-31-3-128 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Jun 28 22:23:29 ip-172-31-3-128 systemd[33466]: influxdb.service: Failed to determine user credentials: No such process
Jun 28 22:23:29 ip-172-31-3-128 systemd[33466]: influxdb.service: Failed at step USER spawning /usr/bin/influxd: No such process
Jun 28 22:23:29 ip-172-31-3-128 systemd[1]: influxdb.service: Main process exited, code=exited, status=217/USER
Jun 28 22:23:29 ip-172-31-3-128 systemd[1]: influxdb.service: Failed with result 'exit-code'.
```

__Environment info:__

* System info: Run `uname -srm` and copy the output here

`Linux 5.4.0-1045-aws x86_64`

* InfluxDB version: Run `influxd version` and copy the output here

`InfluxDB v1.8.6 (git: 1.8 v1.8.6)`

* Other relevant environment details: Container runtime, disk info, etc

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Relevant syslog contents:

```
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
Jun 28 22:20:56 ip-172-31-3-128 systemd[33401]: influxdb.service: Failed to determine user credentials: No such process
Jun 28 22:20:56 ip-172-31-3-128 systemd[33401]: influxdb.service: Failed at step USER spawning /usr/bin/influxd: No such process
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: influxdb.service: Main process exited, code=exited, status=217/USER
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: influxdb.service: Failed with result 'exit-code'.
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 1.
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Jun 28 22:20:56 ip-172-31-3-128 systemd[1]: Started InfluxDB is an open-source, distributed, time series database.
```

**Comment by lesam** [comment] 2021-07-20 17:47
When this is fixed we should also clean up the hack in https://github.com/influxdata/influxdb/pull/21762/files

**Comment by lesam** [comment] 2021-11-10 12:52
Closing - this is expected behaviour when compacting as root, since new files are generated owned by root instead of owned by the influxdb user.

**Comment by lesam** [comment] 2021-11-10 12:53
A fix for this use case would be to run the offline compaction as the influxdb user with `sudo -u influxdb`

**Closed by lesam** 2021-11-10 12:52 UTC
