### ISSUE TITLE
Adding a label to a dashboard from the UI returns a 400 error

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/influxdb#11774] opened 2019-02-08 18:44 UTC
![add-label-error](https://user-images.githubusercontent.com/2433762/52498832-b0055280-2b8e-11e9-832b-f4470b8997e1.gif)
<img width="531" alt="screen shot 2019-02-08 at 10 46 13 am" src="https://user-images.githubusercontent.com/2433762/52498858-c8756d00-2b8e-11e9-93e5-8a10841ff113.png">

**Comment by OfTheDelmer** [comment] 2019-02-12 15:58
![screen shot 2019-02-12 at 10 55 53 am](https://user-images.githubusercontent.com/4994741/52648622-d4c23880-2eb4-11e9-95c9-237f60975bbb.png)

Unable to reproduce. It may have been an issue that was fixed by the labels api fixes.

**Closed by OfTheDelmer** 2019-02-12 15:58 UTC
Labels: kind/bug
