### ISSUE TITLE
queries should be able to access closest point before query time range

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5943] opened 2016-03-09 00:00 UTC
There are a number of cases, most importantly `DERIVATIVE()` and `FILL(previous)`, where the previous vaule of the field is important. However, there is no way to find that value now.

If there are no matching points in the time range, `FILL(previous)` will simply fail, which isn't the expected behavior. It should be able to grab the last recorded value and use that, even if it's from a point before the query time range.

**Comment by BrannonKing** [comment] 2016-03-11 22:02
+1. Go back until you have data!

**Comment by jsternberg** [comment] 2016-04-28 18:43
This works correctly for aggregate queries, but does not work for raw queries. So if you have data every 10 seconds, you can do this and it will work correctly:

```
SELECT derivative(first(value)) FROM cpu WHERE time > now() - 10m GROUP BY time(1m)
```

But this won't work with the same data:

```
SELECT derivative(value) FROM cpu WHERE time > now() - 10m
```

**Comment by beckettsean** [comment] 2016-04-28 20:19
@jsternberg what would be the behavior with `fill(previous)`?

Why does the latter query fail? Provided there are at least two points in the range, shouldn't that return something?

**Comment by jsternberg** [comment] 2016-04-28 20:20
I can do `fill(previous)`, but it just hasn't been done yet.

**Comment by beckettsean** [comment] 2016-06-20 15:33
@jsternberg do you know the current status of this feature?

**Comment by jsternberg** [comment] 2016-06-20 15:35
We haven't made any progress on it. It still only applies to aggregate queries and does not apply to `fill(previous)`.

**Comment by beckettsean** [comment] 2016-06-20 16:12
@jsternberg would it help if I opened a new issue explicitly for `fill(previous)`?

**Comment by jsternberg** [comment] 2016-06-20 16:13
Yes. We can do the same thing for `fill(previous)` as we did for `derivative()` as a temporary stopgap.

**Comment by beckettsean** [comment] 2016-06-20 16:33
Opened https://github.com/influxdata/influxdb/issues/6878 specifically for `fill(previous)`

**Comment by jsternberg** [comment] 2016-06-28 16:29
I've got an interesting edge case for this. So say that we are doing the following query:

```
SELECT mean(value) FROM cpu
    WHERE time >= '2010-01-01T12:05:00Z'
        AND time < '2010-01-01T13:05:00Z'
    GROUP BY time(10m) FILL(previous)
```

The start time of the query is in the middle of an interval. If there are no points in the `12:00 - 12:10` range, how should the previous interval be sampled? Should it look at `11:55 - 12:05` or `11:50 - 12:00`? It seems like it would use the latter to be consistent, but then we have a weird case where `11:50 - 12:00` get looked at for an interval and `12:00 - 12:05` just gets ignored.

**Comment by beckettsean** [comment] 2016-06-28 17:25
@jsternberg it's not terribly intuitive, but to be consistent with the behavior of `GROUP BY time(x, y)` I think we want the 11:50-12:00 bucket for the previous, assuming there's nothing between 12:00 and 12:10. The other buckets in the query will be on xx:x0 boundaries, so the previous bucket should be, too.

If there's data between 12:00 and 12:05, then I think we should use those value(s). The user asked for 10 minute buckets but started them off-center, if you will. That means that they want 10m groupings, but starting at 12:05, so the first and last grouping will have half a bucket's worth of data. If there's data in the other half of the bucket we should use it. It was excluded from the time range, but the `fill(previous)` explicitly says go back until there's data if there's none in the provided range. 

If the user wanted to actually use the 11:55-12:05 bucket they would use `GROUP BY time(10m,5m)` to start the `10m` buckets on the `xx:x5` boundary instead of `xx:x0`. If there were then nothing in the 12:05-12:15 bucket, it would look to the previous bucket for the value.

**Comment by stettix** [comment] 2016-09-22 10:39
+1

**Comment by skladd** [comment] 2017-07-17 08:02
I'm also hitting this issue trying to calculate the distance traveled from odometer values:
`SELECT DIFFERENCE(LAST("odometer")) FROM "gps" WHERE time [...] GROUP BY time(1d)`
The first distance is missing if there is a data gap at the beginning of the time range.
My workaround now is to to query the "real" last value separately, query the odometer values and perform the calculation outside of InfluxDB.

**Comment by matejsp** [comment] 2019-07-24 20:10
This issue is very important and needs to be resolved. Doing multiple queries to get latest value outside the range has also bigger performance impact.

Why is bot closing as wontfix?

**Comment by matejsp** [comment] 2019-07-25 06:04
Is this duplicate of #6878 ?

**Closed** 2019-10-30 06:27 UTC
Labels: 1.x, area/queries, difficulty/high, flux/triaged, kind/feature-request, support, wontfix

**Comment by hildeb** [comment] 2019-11-07 09:48
Reopen, since still annoying everybody

**Comment by lelmarir** [comment] 2020-09-23 15:20
here a solution using flux:

```
import "experimental"

bucket = "test/autogen"
measurement = "mymeasurement"
field = "v"
start = 2020-09-17T13:50:00Z
stop = 2020-09-17T14:10:00Z
aggregateWindowEvery = 1ms

previous = from(bucket: bucket)
  |> range(start:  experimental.subDuration(d: 24h, from: start), stop: start)
  |> filter(fn: (r) => r._measurement == measurement and (r._field == field))
  |> last()
  |> aggregateWindow(every: 1s, fn:mean, createEmpty: false)
  
running = from(bucket: bucket)
  |> range(start: start, stop: stop)
  |> filter(fn: (r) => r._measurement == measurement and (r._field == field))
  |> fill(usePrevious: true)
  |> aggregateWindow(every: aggregateWindowEvery, fn: mean, createEmpty: false)
  
union(tables: [previous, running])
  |> window(every: inf)

```

**Comment by tillsc** [comment] 2021-01-24 18:55
My approach was slightly different: https://gist.github.com/tillsc/2d71f3e89409049833e75ed22689ad40

**Comment by Cjkeenan** [comment] 2021-09-08 07:05
> here a solution using flux:
> 
> ```
> import "experimental"
> 
> bucket = "test/autogen"
> measurement = "mymeasurement"
> field = "v"
> start = 2020-09-17T13:50:00Z
> stop = 2020-09-17T14:10:00Z
> aggregateWindowEvery = 1ms
> 
> previous = from(bucket: bucket)
>   |> range(start:  experimental.subDuration(d: 24h, from: start), stop: start)
>   |> filter(fn: (r) => r._measurement == measurement and (r._field == field))
>   |> last()
>   |> aggregateWindow(every: 1s, fn:mean, createEmpty: false)
>   
> running = from(bucket: bucket)
>   |> range(start: start, stop: stop)
>   |> filter(fn: (r) => r._measurement == measurement and (r._field == field))
>   |> fill(usePrevious: true)
>   |> aggregateWindow(every: aggregateWindowEvery, fn: mean, createEmpty: false)
>   
> union(tables: [previous, running])
>   |> window(every: inf)
> ```

Forgive my ignorance, but is this type of fix implementable using Grafana? It is crazy that an issue like this has not been fixed in the 5+ years it has been reported.
