### ISSUE TITLE
v1,0-beta1 GROUP BY returns multiple same timestamps?!

### ISSUE THREAD

**Issue by ckdarby** [influxdata/influxdb#6877] opened 2016-06-20 14:36 UTC
### Bug report

__System info:__ 

```
Branch	Build Time	Commit						Version
master			bf3c22689b68a6d03d20eac695a7049a7c78b21d	1.0.0-beta1
```

```
name: network
-------------
hostname
kappatron

name: runtime
-------------
GOARCH	GOMAXPROCS	GOOS	version
amd64	1		linux	go1.6.2

name: system
------------
PID	currentTime			started				uptime
2787	2016-06-20T14:33:48.173023573Z	2016-06-18T21:20:54.006175158Z	41h12m54.166849308s
```

__Steps to reproduce:__

```
select count(value) from requests where time > now() - 3h GROUP BY time(15m)
name: requests
--------------
time			count
1466421300000000000	11212
1466422200000000000	45422
1466423100000000000	351
1466422200000000000	494
1466423100000000000	10902
1466422200000000000	428
1466423100000000000	8988
1466422200000000000	762
1466423100000000000	15185
1466422200000000000	214
1466423100000000000	13442
1466422200000000000	553
1466423100000000000	12090
1466424000000000000	27621
1466424900000000000	22248
1466425800000000000	34879
1466426700000000000	41229
1466427600000000000	45568
1466428500000000000	44769
1466429400000000000	45917
1466430300000000000	46072
1466431200000000000	11998
1466422200000000000	26
1466423100000000000	86
1466424000000000000	0
1466424900000000000	0
1466425800000000000	0
1466426700000000000	0
1466427600000000000	0
1466428500000000000	0
1466429400000000000	0
1466430300000000000	0
1466431200000000000	33484
1466432100000000000	27096
```

__Expected behavior:__ Groupby returns a non-repeated timestamp

__Actual behavior:__ Has duplicate timestamps

**Comment by ckdarby** [comment] 2016-06-20 20:45
@jsternberg I just attempted with beta2 & this still happens

**Comment by jsternberg** [comment] 2016-06-20 20:48
This might be related to #6738.

**Comment by jsternberg** [comment] 2016-06-20 20:50
@ckdarby is there any chance you can make a tarball of your data, wal, and meta directories and upload it somewhere for me to check? If it's not possible for some reason, have you found any way to reproduce this consistently?

**Comment by ckdarby** [comment] 2016-06-21 02:12
@jsternberg I ran with 0.13 and everything works fine now. #6738 was exactly what I was experiencing.

Unable to tarball due to the nature of data.

It was always reproducible. Different spots in the data. Passing in about 200 million 1 value measurements across a span of 6 days. Data was sent to influxdb in non-ordered fashion.

These are the tags:
'endpoint' (string)
'domain' (string)
'status' (int)

For fields just value. Sending time with precision nanosecond.

**Comment by jsternberg** [comment] 2016-06-21 05:24
Ok then. I'm going to close this as a duplicate of #6738. I think the problem still exists, but I'm not really sure at this point. Did you do anything to try and modify the database or did it just fix itself when you upgraded?

Thanks.

**Closed by jsternberg** 2016-06-21 05:24 UTC

**Comment by ckdarby** [comment] 2016-06-21 06:55
I purged the install, deleting everything, installed 0.13 and reimported
the same data without any issue.
