### ISSUE TITLE
[regression 1.2] Regexp on measurement names not working

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#7932] opened 2017-02-02 12:54 UTC
With v1.2.0 regular expressions against measurement names don't match.

v1.2.0 behavior:

```
> create database test

> use test
Using database test

> insert regextest,tag1=test value=1

> select value from regextest
name: regextest
time                value
----                -----
1486038960091877204 1

> select value from /regextest/
> 
> select value from /^regextest$/
> 
> select value from /^regex.*/
> 

```

v1.1.1 behavior:

```
> create database test

> use test
Using database test

> insert regextest,tag1=test value=1

> select value from regextest
name: regextest
time                value
----                -----
1486038960091877204 1

> select value from /regextest/
name: regextest
time                value
----                -----
1486038960091877204 1

> select value from /^regex.*/
name: regextest
time                value
----                -----
1486038960091877204 1
```

Regexp on fields works with 1.2 so this should only be affecting matching on measurement names.

**Comment by kostasb** [comment] 2017-02-02 13:17
Also there's a problem that occurs both in 1.2 and 1.1.1 (might be unrelated to the original case).

The following repro case oom's my 2GB RAM machine:

```
> create database test
> show measurements
> 
> insert regextest,tag1=test value=1 1486038960091877204
> insert regextest,tag1=test value=1 1486040575387858089
> SELECT mean(value) FROM test.autogen./^regex*/ where time > 10m GROUP BY time(1m)

Killed
```

**Comment by kizniche** [comment] 2017-02-03 00:29
I'm also experienced this issue, however only with one of two systems I've tested (both running 1.2.0). I cannot figure what's different about the systems, though. It took me a while to narrow it down to the measurement name regex in influxdb.

**Comment by dgnorton** [comment] 2017-02-03 16:44
Repro script... https://gist.github.com/dgnorton/333d6cf22ab96163589c56c4bf4932c0

**Comment by jsternberg** [comment] 2017-02-03 17:35
This is a duplicate of #7877.

**Closed by jsternberg** 2017-02-03 17:35 UTC
Labels: kind/bug, support
