### ISSUE TITLE
[0.10.0-nightly] Derivatives grouped by time broken

### ISSUE THREAD

**Issue by kjeacle** [influxdata/influxdb#5507] opened 2016-02-02 11:18 UTC
In recent v0.10.0 nightly builds, querying derivatives grouped by time returns no results. This was working in early v0.10.0 builds but stopped somewhere around the first beta release.

Currently running 0.10.0.n1454400035-0 with TSM installed from dpkg -i influxdb_nightly_amd64.deb on Ubuntu server 15.10.

DERIVATIVE queries work, and GROUP BY TIME queries work, but not together.

```
> select derivative(max(value)) from snmp_rx where host = 'router.domain.name' and type_instance = '1342177290' and time > now() - 6h GROUP by time(1h)
name: snmp_rx
-------------
time                    derivative
1454389200000000000
1454392800000000000
1454396400000000000
1454400000000000000
1454403600000000000
1454407200000000000
```

The above query should return derivative values for the last six hours but returns nothing. The database is being populated by collectd. No changes on the collectd side or on the queries. The output stopped after an upgrade to a recently nightly.

**Comment by rossmcdonald** [comment] 2016-02-02 15:02
This may be a dupe of #5474. Can you try the solution from that issue and let us know if the problem persists?

**Comment by kjeacle** [comment] 2016-02-03 09:57
I am collecting router interface traffic stats.

My ID was 3 and no queries returned data.

For some interfaces, setting it to 1 retrieves all data and solves the problem.

For other interfaces, however, setting it to 1 retrieves data up to 01-Feb-2016 while setting it to 2 retrieves data after 01-Feb-2016.

Is there a way to fix this so all queries work? If not, and I have to lose some data, what's the best option for collecting data from now on?

**Comment by rossmcdonald** [comment] 2016-02-03 15:02
@kjeacle Regarding:

> what's the best option for collecting data from now on?

This was caused by a broken upgrade path that made it into one of the nightlies. In the cases we've seen, switching the ID back to 1 resolves the issue, though. Can you send us the output from a `SHOW SERVERS` run on this instance when the node ID is set to 3?

@jwilder Do you have any ideas on a fix here?

**Comment by kjeacle** [comment] 2016-02-03 15:12
Node ID set to 3:

````
> show servers
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8088  localhost:8088
2       localhost:8086  localhost:8088


name: meta_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8091  localhost:8088
````

**Comment by jwilder** [comment] 2016-02-03 19:15
@kjeacle If you run `show shards` you should see the shards and owners of those shards.  I suspect you have shards that are owned by node 2 and some by node 1.  They should all be the node 1 if you have only a single node.  Unfortunately, there isn't a way to fix the shard owners manually right now.

One option to fix this going forward would be to update your `node.json` node ID to 1 and run `drop data server 2` which will remove node id 2.  The shards that were owned by node 2 will no longer be queryable though, but new data written should all land on node 1.

**Closed** 2016-02-04 00:07 UTC

**Comment by kjeacle** [comment] 2016-02-04 10:59
I tried ```drop data server 2``` but now the log file just fills with the messages below and any attempt to access data causes a panic and the database restarts itself. The data is completely inaccessible now.

```
[monitor] 2016/02/04 10:47:29 failed to store statistics: write failed
[handoff] 2016/02/04 10:47:34 failed to determine if node 2 is active: node not found
[monitor] 2016/02/04 10:47:39 failed to store statistics: write failed
[monitor] 2016/02/04 10:47:49 failed to store statistics: write failed
[handoff] 2016/02/04 10:47:50 failed to determine if node 2 is active: node not found
```

Here's what ````show shards```` looks like:
````
name: snmp
----------
id      database        retention_policy        shard_group     start_time              end_time                expiry_time  owners
2       snmp            default                 2               2016-01-04T00:00:00Z    2016-01-11T00:00:00Z    2016-01-11T00:00:00Z  1
6       snmp            default                 6               2016-01-11T00:00:00Z    2016-01-18T00:00:00Z    2016-01-18T00:00:00Z  1
14      snmp            default                 14              2016-01-18T00:00:00Z    2016-01-25T00:00:00Z    2016-01-25T00:00:00Z  1
22      snmp            default                 22              2016-01-25T00:00:00Z    2016-02-01T00:00:00Z    2016-02-01T00:00:00Z  1
33      snmp            default                 30              2016-02-01T00:00:00Z    2016-02-08T00:00:00Z    2016-02-08T00:00:00Z  1
34      snmp            default                 30              2016-02-01T00:00:00Z    2016-02-08T00:00:00Z    2016-02-08T00:00:00Z


name: _internal
---------------
id      database        retention_policy        shard_group     start_time              end_time                expiry_time  owners
26      _internal       monitor                 26              2016-01-28T00:00:00Z    2016-01-29T00:00:00Z    2016-02-05T00:00:00Z  1
27      _internal       monitor                 27              2016-01-29T00:00:00Z    2016-01-30T00:00:00Z    2016-02-06T00:00:00Z  1
28      _internal       monitor                 27              2016-01-29T00:00:00Z    2016-01-30T00:00:00Z    2016-02-06T00:00:00Z
29      _internal       monitor                 28              2016-01-30T00:00:00Z    2016-01-31T00:00:00Z    2016-02-07T00:00:00Z  1
30      _internal       monitor                 28              2016-01-30T00:00:00Z    2016-01-31T00:00:00Z    2016-02-07T00:00:00Z
31      _internal       monitor                 29              2016-01-31T00:00:00Z    2016-02-01T00:00:00Z    2016-02-08T00:00:00Z  1
32      _internal       monitor                 29              2016-01-31T00:00:00Z    2016-02-01T00:00:00Z    2016-02-08T00:00:00Z
35      _internal       monitor                 31              2016-02-01T00:00:00Z    2016-02-02T00:00:00Z    2016-02-09T00:00:00Z
36      _internal       monitor                 31              2016-02-01T00:00:00Z    2016-02-02T00:00:00Z    2016-02-09T00:00:00Z  1
37      _internal       monitor                 32              2016-02-02T00:00:00Z    2016-02-03T00:00:00Z    2016-02-10T00:00:00Z
38      _internal       monitor                 32              2016-02-02T00:00:00Z    2016-02-03T00:00:00Z    2016-02-10T00:00:00Z  1
39      _internal       monitor                 33              2016-02-03T00:00:00Z    2016-02-04T00:00:00Z    2016-02-11T00:00:00Z
40      _internal       monitor                 33              2016-02-03T00:00:00Z    2016-02-04T00:00:00Z    2016-02-11T00:00:00Z  1
41      _internal       monitor                 34              2016-02-04T00:00:00Z    2016-02-05T00:00:00Z    2016-02-12T00:00:00Z
42      _internal       monitor                 34              2016-02-04T00:00:00Z    2016-02-05T00:00:00Z    2016-02-12T00:00:00Z  1
````

There are shards with no owner (presumably previously owned by ID 2).

Is there any way out of this or must I wipe everything and start from scratch?
