### ISSUE TITLE
Install InfluxDB as a service with systemd

### ISSUE THREAD

**Issue by mriepe-lab** [influxdata/influxdb#22383] opened 2021-09-03 01:59 UTC
I'm unable to download influxdb2-2.0.8-linux-amd64.deb

ubuntu@ubuntu:/tmp$ wget https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-linux-amd64.deb
--2021-09-03 01:55:24--  https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-linux-amd64.deb
Resolving dl.influxdata.com (dl.influxdata.com)... 13.226.101.92, 13.226.101.63, 13.226.101.129, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|13.226.101.92|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-03 01:55:25 ERROR 404: Not Found.

I get an error message 
HTTP request sent, awaiting response... 404 Not Found
2021-09-03 01:55:25 ERROR 404: Not Found.

**Comment by nsteinmetz** [comment] 2021-09-03 17:30
Correct link is:

```
https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-amd64.deb
```

**Comment by Houssem12-ai** [comment] 2022-12-24 15:26
@nsteinmetz  thank you for proving this correct link:  https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-amd64.deb
The issue is that the link provided in the documentation is incorrect, how can we manage to correct it ?

**Comment by jeffreyssmith2nd** [comment] 2022-12-28 14:17
Closing this in favor of #24008

**Closed by jeffreyssmith2nd** 2022-12-28 14:17 UTC
