### ISSUE TITLE
Docker: influxdb 2.0.6 arm64 claims to be 2.0.5

### ISSUE THREAD

**Issue by andig** [influxdata/influxdb#21511] opened 2021-05-19 17:52 UTC
Docker log:

```
admin@NAS:~$ sudo docker logs -f influxdb2
2021-05-19T17:50:09.807499591Z	info	found existing boltdb file, skipping setup wrapper	{"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
ts=2021-05-19T17:50:30.904083Z lvl=info msg="Welcome to InfluxDB" log_id=0UDRr1yl000 version=2.0.6 commit=4db98b4c9a build_date=2021-04-29T16:48:12Z
```

gui:

<img width="172" alt="Screenshot 2021-05-19 at 19 51 11" src="https://user-images.githubusercontent.com/184815/118860498-c1944380-b8db-11eb-867c-ee9e5a7c2d58.png">

**Comment by danxmoran** [comment] 2021-05-19 17:54
Duplicate of influxdata/influxdata-docker#484

This will be fixed in 2.0.7

**Closed** 2021-05-19 18:00 UTC
