### ISSUE TITLE
Bug report: additional points are returned from query in foreign time zone including dst change.

### ISSUE THREAD

**Issue by mschuwalow** [influxdata/influxdb#9469] opened 2018-02-21 11:23 UTC
### Bug report

__System info:__ Influxdb 1.4, Fedora 26

__Steps to reproduce:__

1. Run aggregation query on foreign time zone that includes a dst change. In this case GROUP BY time(1w). For example: SELECT count(menge) FROM "events"."autogen"."created" WHERE time >= '2013-01-13T23:00:00Z' AND time < '2018-02-18T23:00:00Z' AND tag=~/tag_value/ GROUP BY time(1w, +4d) FILL(null) TZ('Europe/Berlin')

__Expected behavior:__ One point for every week is returned.

__Actual behavior:__  One point for every week is returned and 2 points for the weeks including dst changes are returned. 
__Additional info:__  Query result: 
[created.zip](https://github.com/influxdata/influxdb/files/1743784/created.zip)

**Comment by jsternberg** [comment] 2018-02-21 15:57
For context, here's the section that I think is being reported here:

```
3/25/2013 12:00:00.000000000 AM,1370
4/1/2013 12:00:00.000000000 AM,0
4/1/2013 1:00:00.000000000 AM,1464
4/8/2013 12:00:00.000000000 AM,1674
```

Am I correct? If it is, that definitely looks like a bug.

**Comment by jsternberg** [comment] 2018-03-15 14:54
@MSchuwalow is there any chance you could export the data from around that time so we could reproduce this locally? Anonymized data is fine.

**Comment by jsternberg** [comment] 2018-03-15 15:59
This appears to be related to #9130. I'm going to treat #9130 as the official issue, but keep this open temporarily.

**Comment by jsternberg** [comment] 2018-03-15 17:19
This seems to happen when the additional group by offset causes the window to move over a daylight saving time location. So the +4d in this issue goes from thursday to monday, which skips over the daylight saving time offset that happens on sunday and causes the offset to be introduced to the wrong interval.

I think the additional point may be because the code that fills in missing points is using a different method to fill those points. I think I'm closing in on the issue, but this code is very sensitive and difficult to get correct.

**Comment by RedShift1** [comment] 2018-04-05 08:43
Can confirm this bug, here's a testcase:

```
# influx
Connected to http://localhost:8086 version 1.5.1
InfluxDB shell version: 1.5.1
> create database tztest
> use tztest
Using database tztest
> exit

# 2018-03-24T16:00:00+00:00
curl -i -XPOST 'http://localhost:8086/write?db=tztest&precision=s' --data-binary 'load,tag=x value=1 1521907200'
# 2018-03-25T16:00:00+00:00
curl -i -XPOST 'http://localhost:8086/write?db=tztest&precision=s' --data-binary 'load,tag=x value=2 1521993600'
# 2018-03-26T16:00:00+00:00
curl -i -XPOST 'http://localhost:8086/write?db=tztest&precision=s' --data-binary 'load,tag=x value=3 1522080000'

curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=tztest" --data-urlencode "q=SELECT SUM(\"value\") FROM \"load\" WHERE time >= '2018-03-19' AND time < '2018-04-02' GROUP BY time(1w,4d) tz('Europe/Brussels')"
```
Result:

```
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "load",
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "2018-03-19T00:00:00+01:00",
                            3
                        ],
                        [
                            "2018-03-26T00:00:00+02:00",
                            null
                        ],
                        [
                            "2018-03-26T01:00:00+02:00",
                            3
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by RedShift1** [comment] 2018-04-05 08:44
Can you guide me to where in the code these points are generated?

**Comment by jsternberg** [comment] 2018-04-05 15:35
It's a bug in the `IteratorOptions.Window` function. That function will generate the wrong start and end times if the offset moves over a DST boundary.

**Closed** 2019-07-31 11:29 UTC
Labels: 1.x, area/queries, kind/bug, wontfix

**Comment by RedShift1** [comment] 2019-08-01 19:40
The issue has not been resolved.

**Comment by haniha** [comment] 2019-09-23 08:16
any updates on this ?
is there any workaround to remove extra window manually?

**Comment by RedShift1** [comment] 2019-09-23 08:56
This makes me question if the data retrieved is correct. There is currently no workaround. Don't count on this ever being fixed.
