### ISSUE TITLE
Bug: Creating a new notification rule fails with error `invalid options; Err: loc 18:12-29:216: expected RPAREN, got EOF`

### ISSUE THREAD

**Issue by bpalani** [influxdata/influxdb#15000] opened 2019-09-06 05:45 UTC
Bug: Creating a new notification rule fails with error `invalid options; Err: loc 18:12-29:216: expected RPAREN, got EOF` due to `Add Tag Filter` panel which is expecting an input. Error seems to go away as soon as the panel is removed. 
Therefore ask here is to not show the panel by default when creating a new rule.

![image](https://user-images.githubusercontent.com/10112209/64403974-3d2e5e00-d02f-11e9-9bfd-124cc491644e.png)

**Comment by russorat** [comment] 2019-09-06 17:36
i think 1 was fixed in https://github.com/influxdata/influxdb/issues/14869

**Comment by desa** [comment] 2019-09-06 18:58
I think this is caused by the data that is sent over to the server are empty

```
tagValues: [{key: "", value: "", ...}]
```

**Closed** 2019-09-07 01:53 UTC
Labels: blocking release, kind/bug, team/monitoring
