### ISSUE TITLE
ViewSwitcher should do magical things

### ISSUE THREAD

**Issue by TCL735** [influxdata/influxdb#18225] opened 2020-05-26 18:47 UTC
Plot types should not require manually parsed Flux results as props. With notable exceptions, generally we want to send in raw Flux to Giraffe.

Depends on https://github.com/influxdata/giraffe/issues/186

Ultimately we want
https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/ViewSwitcher.tsx#L6-L15
and
https://github.com/influxdata/influxdb/blob/master/ui/src/shared/components/ViewSwitcher.tsx#L33-L34
to become something like this:
https://github.com/influxdata/influxdb/blob/master/ui/src/notebooks/index.ts#L34-L51

**Comment by drdelambre** [comment] 2020-10-13 19:52
to capture the offline conversation i had with palak; there is a migration path here.
 1. remove view option interdependancies: this is the magic part where we have view options being defined in their own folders. this shores us up as it were against chasing down bugs caused by having implicit relationships between view options. eg: i have a component that renders an axes label editing interface. in one view property type, that is called `axes.x.label`, in another its `xAxisLabel`. the current implementation has a lot of branching based on this, but no clear indicator on why, or specifically which view property types create this condition.
 1. normalize the view option types: now that we've isolated side effects, we can tackle this individually within our system. we just take a stance, like "all axes within every view property type within the system should follow this format: { insert contract }", and then we perform migrations on each view property type until we have the types normalized.
 1. generate views based on type definitions in giraffe: have one component that represents the interaction of "edit meta data about an axis", and when a view property type has an `axes` defined in it, render that interaction for each axes defined.

After these steps, we now have the ui repo in charge of rendering + styles around editing view properties, and giraffe being the source of truth for what a view property is. division of responsibility, one source of truth, [insert dogma here], but it should help keep our bugs isolated and features easier to implement

**Comment by kristinarobinson** [comment] 2020-10-15 16:55
Keeping the issue open, and in progress, but removing from the Giraffe Beta epic, since code changes are NOT in the Giraffe repo.

**Comment by Palakp41** [comment] 2020-10-26 17:22
I will close this issue. I have created a new issue with the remaining work to normalize graph types for data explorer: #19822

**Closed by Palakp41** 2020-10-26 17:22 UTC
Labels: kind/tech-debt, team/monitoring
