### ISSUE TITLE
Click to add a function in the script editor adds it to the same line

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#16993] opened 2020-02-24 23:07 UTC
in previous versions, the function was added as a new line after the cursor. 

![Kapture 2020-02-24 at 15 06 21](https://user-images.githubusercontent.com/4805997/75199216-58914080-5717-11ea-8463-5f8a51ebb16c.gif)

**Comment by desa** [comment] 2020-03-02 17:55
Dupe of https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/16668

**Closed by desa** 2020-03-02 17:55 UTC
Labels: kind/bug, monaco, regression, severity/sev-3, team/monitoring
