### ISSUE TITLE
Feature request.  Mechanism to interrupt long-running queries from influx CLI

### ISSUE THREAD

**Issue by mac01021** [influxdata/influxdb#8090] opened 2017-03-02 17:58 UTC
### Feature Request

__Proposal:__   Allow `ctrl-c` to interrupt a long running query from the command-line client

__Current behavior:__ I run a `select * from ...` forgetting to include a `where` or `limit` clause and then am forced to wait until the query completes before I can do more in the current session.

__Desired behavior:__ I should be able to terminate the query.

__Use case:__ Helps thoughtless, brainless data explorers like me whenever they log in.

**Comment by mark-rushakoff** [comment] 2017-03-02 18:21
Closing as duplicate of #6563.

**Closed by mark-rushakoff** 2017-03-02 18:21 UTC
