### ISSUE TITLE
[0.11.0] Select statements return odd results for some functions when series has a large number of points

### ISSUE THREAD

**Issue by mjdesa** [influxdata/influxdb#5556] opened 2016-02-05 23:08 UTC
The following queries were ran against an instance with 1 series and 10 million points in that series. The series was generated with `influx_stress` with the configuration found in this gist.
[influx_stress config](https://gist.github.com/mjdesa/bdf3416da6989d5de51f)

Mean works just fine.
```
> select mean(value) from cpu
name: cpu
---------
time	mean
0	499.44555559997156
```

However,

```
> select count(value) from cpu
name: cpu
---------
time	count
0	60480
0	60480
0	60480
0	60480
....
0	60480
0	60479
0	60480
...
0	60480
0	20801
0	60480
...
0	60480
````

```
> select min(value) from cpu
name: cpu
---------
time	min
0	0
...
0	0
```

```
> select max(value) from cpu
name: cpu
---------
time	max
0	999
...
0	999
```

```
> select sum(value) from cpu
name: cpu
---------
time	sum
0	3.0241464e+07
0	3.0242999e+07
...
0	3.0277734e+07
0	1.0418961e+07
0	3.0283981e+07
0	3.0149376e+07
0	3.0168619e+07
...
0	3.0168315e+07
0	3.0162964e+07
0	3.0225513e+07
0	3.0183283e+07
0	3.0101842e+07
0	3.0216514e+07
...
0	3.0231895e+07
0	3.022347e+07
...
0	3.0313508e+07
0	3.0257853e+07
0	3.0284292e+07
0	3.0247962e+07
...
0	3.0152689e+07
```

**Comment by zstyblik** [comment] 2016-02-06 09:22
@mjdesa I'm not sure if I'm seeing the same issue with v0.10.0 and Grafana, but what happens is that I run query like:

```
SELECT mean(load1) FROM system
WHERE [probably] time > now() - 30m
GROUP BY host
```

and what happens is that eg. values for one specific host are missing past, say, 2-3minutes on the "right side". But this could be issue with Telegraf or WAL.
Another issue I'm seeing is that values are missing on the "left" side. Almost like somehow no data would fit the last minute of `now() - 30m`. However, data are there, that I'm sure of. If I select bigger time range, no such thing occurs.
Last, but not least, this could be issue with Grafana, although I somewhat doubt it.

**Comment by mjdesa** [comment] 2016-02-08 17:58
@zstyblik with the `0.11.0` release we've been rewriting our query engine. I believe the issues I'm seeing were introduced in the branch for this https://github.com/influxdata/influxdb/pull/5196 PR.

**Comment by zstyblik** [comment] 2016-02-08 20:18
@mjdesa I see. Ok, moving on.

**Comment by jsternberg** [comment] 2016-02-08 20:27
@mjdesa this looks like a symptom of multi-shard queries not having been implemented yet. So each shard returned a count rather than an aggregated total.

Can you try it again with the latest in @benbjohnson's query-engine branch? We just merged support for multi-shard queries about an hour ago.

**Comment by mjdesa** [comment] 2016-02-08 21:55
@jsternberg every thing looks good to me.

**Comment by jsternberg** [comment] 2016-02-09 17:17
Confirmed that this works now.

**Closed by jsternberg** 2016-02-09 17:17 UTC
