### ISSUE TITLE
invalid spdelta x_cgo_mmap on startup

### ISSUE THREAD

**Issue by daviesalex** [influxdata/influxdb#6836] opened 2016-06-14 10:10 UTC
Seen on 1.0.0-beta1 (bf3c22689b68a6d03d20eac695a7049a7c78b21d)

```
[tsm1] 2016/06/14 05:05:20 compactions enabled for: /data/influxdb-data/metrics/tg_udp/default/56
[store] 2016/06/14 05:05:20 /data/influxdb-data/metrics/tg_udp/default/56 opened in 22m33.0214011s
invalid spdelta x_cgo_mmap 0x9f1fa0 0x9f1fac 0x0 -1
[shard] 2016/06/14 05:11:00 /data/influxdb-data/metrics/tg_udp/default/154 database index loaded in 24m41.618159551s
[tsm1] 2016/06/14 05:11:00 compactions enabled for: /data/influxdb-data/metrics/tg_udp/default/154
[store] 2016/06/14 05:11:00 /data/influxdb-data/metrics/tg_udp/default/154 opened in 28m12.064336595s
```

Startup appears to be continuing; will update if it starts or not. However, what does this mean?

Startup appears to be continuing. It seems that startup is now doing an incredible number of small IO operations; kswapd has two cores spinning 100% and is the liming factor. Unsure if this is in any way related.

**Comment by jwilder** [comment] 2016-06-14 16:59
That might be a go 1.6.2 bug.  Nothing in `influxdb` prints that.  Is it reproducible with go 1.7beta1?  There are some similar issues in the Golang repo and indicate it my be fixed by https://go-review.googlesource.com/#/c/18322/.  That issue hints at the source of the issue is related to profiling.

**Comment by daviesalex** [comment] 2016-06-15 08:25
@jwilder great minds; I built HEAD from 1.7 immediately after and didnt see that exact error. So we can probably forget about this; its not a Influx issue- just a Go issue.

We now have the problem that its both extremely slow and we just cant start the daemon without it OOM'ing. I'm going to continue to working on why later. Its doing absolutely insane amounts of IO during startup; 25,000 4k IOPS per second for an hour before it OOM's.  I suspect this put the profiler under extreme stress. 

Its not 100% clear to me if this is a regression, or if this is simply because our data size has increased (to ~3.5TB). That does not feel like a lot, but it appears the current startup design is a big problem for us and we are going to have to improve it; reading a hundreds of 2GB files in 4k IOPs appears to only scale so far!

[The root cause solution here is #6000 - CQs just dont work for us and this is the reason we have so much data - we plan to have somebody work on that over the next month, too]

**Comment by jwilder** [comment] 2017-05-10 18:02
Going to close this as we are no longer on go 1.6 and this doesn't appear to be re-occurring anymore.

**Closed by jwilder** 2017-05-10 18:02 UTC
Labels: area/go runtime
