### ISSUE TITLE
aliasing not working with top function

### ISSUE THREAD

**Issue by clementodot** [influxdata/influxdb#5483] opened 2016-01-30 17:13 UTC
Hello,

I was trying to alias a "top" column but it doesn't seems to work:

select top(cpu_load_avg_mhz,vm,3) as some_alias from vsphere_vm_stats

Anyhow, I don't get how it could work: what is it suppose to alias ? The "top" column ? What if I want to alias the "vm" column ?

vsphere_vm_stats
time	top	vm
2016-01-29T23:58:03Z	8030	"SWEBMPAQ91"
2016-01-30T00:58:02Z	5086	"SNHD1CDR"
2016-01-30T02:58:03Z	5160	"SVPUDBASIROCCO"

Thanks.

**Comment by rossmcdonald** [comment] 2016-02-04 23:16
Duplicate of #4949, which should be fixed by #5130

**Closed by rossmcdonald** 2016-02-04 23:16 UTC
