### ISSUE TITLE
Time is different if I do math on the fields in a SELECT

### ISSUE THREAD

**Issue by scotloach** [influxdata/influxdb#8353] opened 2017-05-03 14:11 UTC
### Directions
_GitHub Issues are reserved for actionable bug reports and feature requests._
_General questions should be sent to the [InfluxDB Community Site](https://community.influxdata.com)._

_Before opening an issue, search for similar bug reports or feature requests on GitHub Issues._
_If no similar issue can be found, fill out either the "Bug Report" or the "Feature Request" section below.
_Erase the other section and everything on and above this line._

### Bug report

__System info:__ InfluxDB 1.2.2 on Fedora 25

__Steps to reproduce:__
The following query demonstrates this.  If I didn't do the math on the fields, I get a single results row as I would expect.

```
SELECT MAX("peak")/10.0*8 AS "peak",SUM("gauge")/620602.559674*8 AS "gauge" FROM m WHERE "tag1"="val1" AND time >= '2017-04-25T15:01:10Z' GROUP BY tag2, tag3
```
__Expected behavior:__ 

```
name: m
tags: tag2=valX, tag3=valY
time                 peak   gauge
----                 ----   -----
2017-04-25T15:01:10Z  3078.4      0.07711215375124872
```

__Actual behavior:__ 

```
name: m
tags: tag2=valX, tag3=valY
time                 peak   gauge
----                 ----   -----
2017-04-25T15:01:10Z        0.07711215375124872
2017-05-01T01:50:00Z 3078.4
```
__Additional info:__ 

https://community.influxdata.com/t/time-in-response-is-different-if-i-do-math-in-the-select-clause/797

**Comment by jsternberg** [comment] 2017-05-03 14:51
This looks like a duplicate of #8167.

**Closed by jsternberg** 2017-05-03 14:51 UTC
