### ISSUE TITLE
Add API to get list of rules that match a check

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#14773] opened 2019-08-23 13:45 UTC
We'll need an API that can return a list of rules that match a check. Specifically based on the tags added and the tags present on some of the data that is returned by a query.

**Comment by jademcgough** [comment] 2019-08-23 15:43
duplicate of #14330

**Comment by desa** [comment] 2019-08-23 15:53
ah cool, let me close this

**Closed** 2019-08-23 15:57 UTC
Labels: team/api, team/monitoring
