### ISSUE TITLE
Unable to return average SUM by tag grouping

### ISSUE THREAD

**Issue by foxx** [influxdata/influxdb#6823] opened 2016-06-11 13:00 UTC
I'm trying to return the average total across all tags over a period of 5 seconds.

However if I use `GROUP BY time(5s)` with `SUM()` then it gives me the total for the 5 seconds, rather than the mean average for each second. It doesn't allow me to use nested functions, such as `SUM(MEAN(value))`, and so far the only fix seems to be adding a math operator `/ 5` onto the `SUM()`, as seen below.

```
SELECT 
  SUM(value) / 5 
  FROM "freeswitch.gateway_channel_count" 
  WHERE time > now() - 1m 
  GROUP BY time(5s);
```

Is there a better way to achieve this?

**Comment by beckettsean** [comment] 2016-06-20 06:14
Nested functions is a duplicate of https://github.com/influxdata/influxdb/issues/834, which has been consolidated into https://github.com/influxdata/influxdb/issues/5930 until it is scheduled.

As for another way to achieve it, you can use a continuous query to calculate and store the results of the first function, and then apply the second function to the stored results.

I don't quite know exactly what you mean by "average total across all tags over a period of 5 seconds". Do you want the mean of the sum per tag grouped into 5 second intervals? If so, first calculate the sum per tag in 5s intervals, then take the mean of the results.

```
CREATE CQ...
 SELECT SUM(value) AS sum5s INTO foo FROM ... GROUP BY time(5s), tagname
END
```

Then `SELECT MEAN(sum5s) FROM foo GROUP BY time(5s)`

**Closed by beckettsean** 2016-06-20 06:14 UTC

**Comment by foxx** [comment] 2016-06-20 09:16
Thanks for the detailed reply, solves my problem, thank you!
