### ISSUE TITLE
500 Internal Server Error when running Flux in InfluxDB 1.7.5

### ISSUE THREAD

**Issue by danielnelson** [influxdata/influxdb#13136] opened 2019-04-03 21:44 UTC
Ran into some unexpected error responses with InfluxDB 1.7.5 with flux enabled, while tring to guess my way though some simple queries.

#### Steps:
-  enable flux in influxd.conf
-  restart influxd
```
$ influx -type flux
Connected to http://localhost:8086 version 1.7.5
InfluxDB shell version: 1.7.5
Enter a Flux query
> from(bucket:"telegraf/autogen")
Error: unknown server error: 500 Internal Server Error
> buckets()
Error: unknown server error: 500 Internal Server Error
> buckets
&{buckets {map[] [] {{map[kind:2] [] [kind]}} } 0x9611e0 false}
```

#### Expected:

Successful response with results or a non 500 error message.  No errors or responses containing Go structures.

**Comment by rbetts** [comment] 2019-04-04 16:19
@nathanielc - note this was against 0.12 .. or whatever flux was in 1.7.5.

**Comment by conet** [comment] 2019-04-09 16:15
Isn't this a duplicate of #13010?

**Closed** 2019-07-09 21:25 UTC
Labels: kind/bug, team/query

**Comment by wormiedk** [comment] 2019-07-31 17:16
I have the same issue in influx 1.7.7
Enabled flux in influxd.conf

`pi@domopi:~ $ influx -type flux
Connected to http://localhost:8086 version 1.7.7
InfluxDB shell version: 1.7.7
> from(bucket:"telegraf/autogen")
Error: unknown server error: 500 Internal Server Error
> buckets()
Error: panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1025516 [running]:
runtime/debug.Stack(0xb3fde0, 0xb57ed0, 0x1870fd0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1.1(0x96142d0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:269 +0x88
panic(0xb57ed0, 0x1870fd0)
	/usr/local/go/src/runtime/panic.go:513 +0x194
runtime/internal/atomic.goLoad64(0xdb889a4, 0x1, 0x8)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:124 +0x1c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/memory.(*Allocator).count(0xdb889a0, 0x10, 0x20, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/memory/allocator.go:59 +0x38
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/memory.(*Allocator).Allocate(0xdb889a0, 0x10, 0x3a58318, 0x1)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/memory/allocator.go:27 +0x44
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*Allocator).account(0x3a58308, 0x1, 0x10)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/allocator.go:29 +0x30
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*Allocator).AppendStrings(0x3a58308, 0x0, 0x0, 0x0, 0x9133e08, 0x1, 0x1, 0x0, 0x9133e18, 0x3)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/allocator.go:174 +0x17c
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*ColListTableBuilder).AppendString(0xa908ecc, 0x0, 0x747a7e0, 0x11, 0x1, 0x3ce7cc0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/table.go:925 +0xc8
github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb.(*BucketsDecoder).Decode(0xdb88a60, 0xf74f00, 0x0, 0x0, 0xc8a4a70)
	/go/src/github.com/influxdata/influxdb/flux/stdlib/influxdata/influxdb/buckets.go:85 +0x3cc
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*sourceIterator).Do(0x93a81e0, 0xa908fa8, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/source_iterator.go:53 +0xdc
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*sourceIterator).Run(0x93a81e0, 0xf74ec8, 0xdb88980)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/source_iterator.go:74 +0x40
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do.func1(0xdef0120, 0x96142d0, 0xf74ec8, 0xdb88980, 0xf6e958, 0x93a81e0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:276 +0x7c
created by github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute.(*executionState).do
	/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/execute/executor.go:255 +0xac
`
