### ISSUE TITLE
Selected Fields Staying Selected Even When Their Measurement Is De-Selected In Query Builder

### ISSUE THREAD

**Issue by samhld** [influxdata/influxdb#18164] opened 2020-05-19 17:54 UTC
__Issue:__
When selecting a Measurement, you see the Fields associated with it.  When you select 1-n Fields from that Measurement and then change your mind and select another Measurement, the previously selected Fields are still displayed as "available" even when they don't exist as part of the newly selected Measurement.  This happens when the original Measurement is specifically de-selected. 

__Expected behavior:__
Only Fields that belong to the selected Measurement should show up as options for selection.

__Actual behavior:__
Fields from previously selected Measurements stay "available" for newly selected Measurements they don't belong to.

In the below image, `Bytes50thPercentile` is a Field in a Kafka-related Measurement and not one in the `netstat` Measurement:
![Screen Shot 2020-05-19 at 10 49 25 AM](https://user-images.githubusercontent.com/4852912/82360946-fadf5e00-99be-11ea-9756-6f4cddd28fe3.png)

**Comment by desa** [comment] 2020-05-29 21:59
I think this is a duplicate of https://github.com/influxdata/influxdb/issues/15625

**Closed by desa** 2020-05-29 21:59 UTC
Labels: area/ui, area/vis, kind/bug, severity/sev-4, team/monitoring
