### ISSUE TITLE
Influx has too many threads and killed by OOM when he try to execute too many queries, but should skip them.

### ISSUE THREAD

**Issue by topflow-admin** [influxdata/influxdb#21740] opened 2021-06-24 11:40 UTC
InfluxDB OSS version: InfluxDB 2.0.7 (git: 2a45f0c037) build_date: 2021-06-04T19:17:40Z (running in docker container)
Hardware: 64Gb RAM, 2Tb SSD (aws ec2 m5.4xlarge)

Hello! 

My Influx 2.0 running in docker container and has OOM when I try to execute hundred queries from many processes. 
I've tried to change influxd configuration fields: 2 concurrent queries limit, 1 query queue size, 100000000 query memory bytes limit, 10000000 query initial memory bytes. But Influx still create too many influxd threads (when he should just skip all queries and put in queue just one of them) and use too many RAM and will be killed just in seconds after queries has started.

Redefined fields in config:
```
query-concurrency: 2
query-initial-memory-bytes: 10000000
query-max-memory-bytes: 3200000000
query-memory-bytes: 100000000
query-queue-size: 1
```

Result of `influxd print-config`:
```
assets-path: ""
bolt-path: /root/.influxdbv2/influxd.bolt
e2e-testing: false
engine-path: /root/.influxdbv2/engine
feature-flags: {}
http-bind-address: :8086
http-idle-timeout: 3m0s
http-read-header-timeout: 10s
http-read-timeout: 0s
http-write-timeout: 0s
influxql-max-select-buckets: 0
influxql-max-select-point: 0
influxql-max-select-series: 0
key-name: ""
log-level: info
metrics-disabled: false
nats-max-payload-bytes: 1048576
nats-port: -1
no-tasks: false
pprof-disabled: false
query-concurrency: 2
query-initial-memory-bytes: 10000000
query-max-memory-bytes: 3200000000
query-memory-bytes: 100000000
query-queue-size: 1
reporting-disabled: false
secret-store: bolt
session-length: 60
session-renew-disabled: false
storage-cache-max-memory-size: 200000000
storage-cache-snapshot-memory-size: 100000000
storage-cache-snapshot-write-cold-duration: 10m0s
storage-compact-full-write-cold-duration: 4h0m0s
storage-compact-throughput-burst: 50331648
storage-max-concurrent-compactions: 0
storage-max-index-log-file-size: 1048576
storage-retention-check-interval: 30m0s
storage-series-file-max-concurrent-snapshot-compactions: 0
storage-series-id-set-cache-size: 0
storage-shard-precreator-advance-period: 30m0s
storage-shard-precreator-check-interval: 10m0s
storage-tsm-use-madv-willneed: false
storage-validate-keys: false
storage-wal-fsync-delay: 0s
store: bolt
testing-always-allow-setup: false
tls-cert: ""
tls-key: ""
tls-min-version: "1.2"
tls-strict-ciphers: false
tracing-type: ""
vault-addr: ""
vault-cacert: ""
vault-capath: ""
vault-client-cert: ""
vault-client-key: ""
vault-client-timeout: 0s
vault-max-retries: 0
vault-skip-verify: false
vault-tls-server-name: ""
vault-token: ""
```

Query template (each query has 30 minute len):
```
from(bucket: "{bucket}") 
  |> range(start: {start}, stop: {stop})
  |> filter(fn: (r) => r["_measurement"] == "{measurement}")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> filter(fn: (r) => r["{tag1}"] == "{value1}")
  |> filter(fn: (r) => r["{tag2}"] == "{value2}")
```

Cardinality: 435, number has calculated with flux request:
```
from(bucket: "buck")
  |> range(start: -1y)
  |> last()
  |> toString()
  |> group()
  |> count()
```

5 second after Influx has started requests processing (and 5 second right before Influx killed by OOM):
![Снимок экрана 2021-06-24 в 14 28 50](https://user-images.githubusercontent.com/81387313/123256678-e9d61a00-d4f9-11eb-8fb7-3f26e1f06f2c.png)

**Comment by angelademarco** [comment] 2021-06-30 09:04
I've a similar problem, but in my case it also crashes when inserting a lot of data, also crashes when querying a lot of data. The same version also running in a docker container.

**Comment by danxmoran** [comment] 2021-07-23 21:44
@topflow-admin would you mind sharing the full docker command you're using the run the container? I'm not able to reproduce the behavior you're seeing. When I set `query-queue-size: 1` then almost all of my concurrent requests fail immediately with `Error: failed to execute query: 400 Bad Request: queue length exceeded`

**Comment by dgnorton** [comment] 2021-09-07 21:05
@topflow-admin and @angelademarco can you share the information @danxmoran requested above? Thanks

**Comment by dgnorton** [comment] 2021-09-10 18:50
Closing since we can't repro and don't have info to debug.

**Closed by dgnorton** 2021-09-10 18:50 UTC
Labels: area/queries, kind/perf, area/2.x
