### ISSUE TITLE
Support incremental backups

### ISSUE THREAD

**Issue by freeseacher** [influxdata/influxdb#7361] opened 2016-09-26 08:36 UTC
### Feature Request

__Proposal:__ Support incremental backups. Currently each shard can be backed up individually. 

__Current behavior:__ According to https://docs.influxdata.com/influxdb/v1.0/administration/backup_and_restore/ 
`InfluxDB does not yet support incremental backups`

__Desired behavior:__ DB size can be very big so taking full backup each time is simply overkill.

**Comment by desa** [comment] 2016-09-27 16:39
@freeseacher does the `since` flag not achieve what you're looking for?

> -since <date> - This flag can be used to create a backup since a specific date, where the date must be in RFC3339 format (for example, 2015-12-24T08:12:23Z). This flag is important if you would like to take incremental backups of your database. If not specified, all timeranges within the database will be backed up.

**Comment by freeseacher** [comment] 2016-09-27 19:59
ok. maybe. but how do i restore that backups to make them one peace ?

**Comment by desa** [comment] 2016-09-27 20:33
It should be the same as a regular restore

```
influxd backup -since <date> -database <mydatabase> <path-to-backup>
influxd restore -metadir <path-to-meta-dir> -datadir <path-to-data-dir> <path-to-backup>
```

**Comment by jsternberg** [comment] 2016-09-27 20:42
I'm going to close this since it seems this is a support question that should go to the [mailing list](https://groups.google.com/forum/#!forum/influxdb). If it turns out that what you want isn't available, please comment here with details and I'll reopen this issue. Thanks.

**Closed by jsternberg** 2016-09-27 20:42 UTC

**Comment by freeseacher** [comment] 2016-09-27 20:51
ok. than probably that is not feature request but documentation bug/misundersanding. 
thx.

**Comment by joseppla** [comment] 2016-11-25 09:40
Maybe I'm wrong but I'm trying to get an incremental backup using exactly the same command that appears in the documentation and I'm getting a full backup every time I try, it's making a backup of all shards when it's supposed to backup only 1 because of the since parameter. There's any issue with shit parameter?

**Comment by desa** [comment] 2016-12-05 18:26
@joseppla if the `-since` flag isn't working correctly could you open an issue detailing the steps to reproduce the issue.
