### ISSUE TITLE
Debian package has influxdb2 with version "wb-test-2.test"

### ISSUE THREAD

**Issue by xPaw** [influxdata/influxdb#22844] opened 2021-11-08 18:32 UTC
See https://repos.influxdata.com/debian/dists/bullseye/stable/binary-amd64/Packages

```
Package: influxdb2
Version: wb-test-2.test
```

dpkg refuses to install it:
```
dpkg: error processing archive /var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'influxdb2':
 'Version' field value 'wb-test-2.test': version number does not start with digit
```

**Comment by szerwi** [comment] 2021-11-08 18:54
Same problem on Ubuntu

**Comment by wbaker85** [comment] 2021-11-08 20:52
Hi - thanks for the bug report. There was a problem with our build process for the `2.1` release that resulted in the wrong git tag being used for the deb/rpm packages. Unfortunately it picked up a tag that was used for testing instead of the correct `v2.1.0` sem ver tag. We're working on fixing this now.

**Comment by mrh666** [comment] 2021-11-08 22:41
Confirmed bug for Ubuntu 20.04:
```
# apt-get install influxdb2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  influxdb2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/108 MB of archives.
After this operation, 179 MB of additional disk space will be used.
dpkg: error processing archive /var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'influxdb2':
 'Version' field value 'wb-test-2.test': version number does not start with digit
Errors were encountered while processing:
 /var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Please fix!

**Comment by Qarasique** [comment] 2021-11-09 06:24
Same. Debian 11

**Comment by JBlond** [comment] 2021-11-09 08:47
```
Get:31 https://repos.influxdata.com/debian bullseye/stable amd64 influxdb2-cli amd64 2.2.0 [5,325 kB]
Fetched 121 MB in 2s (74.4 MB/s)
dpkg-deb: error: parsing file '/tmp/dpkg-deb.C8stH0/control' near line 2 package 'influxdb2':
 'Version' field value 'wb-test-2.test': version number does not start with digit
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/influxdb2_wb-test-2.test_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
Extracting templates from packages: 100%

dpkg: error processing archive /tmp/apt-dpkg-install-J13T7U/13-influxdb2_wb-test-2.test_amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'influxdb2':
 'Version' field value 'wb-test-2.test': version number does not start with digit
Selecting previously unselected package influxdb2-cli.
Preparing to unpack .../14-influxdb2-cli_2.2.0_amd64.deb ...
Unpacking influxdb2-cli (2.2.0) ...
Replacing files in old package influxdb2 (2.0.9) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-J13T7U/13-influxdb2_wb-test-2.test_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


sudo apt list --upgradable
Listing... Done
influxdb2/unknown wb-test-2.test amd64 [upgradable from: 2.0.9]
N: There is 1 additional version. Please use the '-a' switch to see it
```

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
uname -r
5.10.0-9-amd64
```

**Comment by pouya-eghbali** [comment] 2021-11-09 14:26
A workaround:

```sh
$ apt-get -d install influx2
$ dpkg-deb -R /var/cache/apt/archives/influxdb2_wb-test-2.test_arm64.deb ./influx2
$ vim ./influx2/DEBIAN/control
```

Note: this is for the arm version on ubuntu, change the package name in the second command to the proper architecture.

Change the VERSION to 2.1, save, then

```sh
$ dpkg-deb -b ./influx2 influx2.deb
$ dpkg -i influx2.deb
```

**Comment by wbaker85** [comment] 2021-11-09 18:28
This should be fixed now. We have pushed a hot-fix release [v2.1.1](https://github.com/influxdata/influxdb/releases/tag/v2.1.1) with the correct versions for the deb and rpm packages and updated our repo server.

Let me know if you continue to see issues, and also if the problem is taken care of on your end!

**Comment by JBlond** [comment] 2021-11-10 08:54
@wbaker85 Thank you, the update went smooth as usual.

**Comment by wbaker85** [comment] 2021-11-10 10:13
Thanks @JBlond - going to close this issue out now since all indications are that the problem is fixed.

**Closed by wbaker85** 2021-11-10 10:13 UTC
