### ISSUE TITLE
v1 auths do not seem to be working

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#19931] opened 2020-11-07 01:01 UTC
i was working through an upgrade of influxdb 1.x and was not able to write data into the new 2.0 instance using the `/write` api and the v1 auth credentials.

to repro:
1. set up an influxdb 1.x instance from scratch using the default configuration options
2. load some data into that instance so you have something to upgrade.
3. shut down the 1.x instance and run the 2.0 `influxd upgrade` command in the latest RC4 binary
4. start influxdb 2.0
5. grab the token from the UI and use the `influx v1 auth create` command to create a new v1 auth
6. try to write data into 2.0 using the v1 auth you just made and the `/write` endpoint.

no matter what i try, i get the message:
`{"code":"unauthorized","message":"Unauthorized"}`

I was trying to do it this way:
```
curl -u russ:something --request POST http://localhost:8086/write\?db\=telegraf\&rp\=autogen --data-binary "measurement,host=host1 field1=2i,field2=2.0 1577836800000000000"
{"code":"unauthorized","message":"Unauthorized"}
```
i verified the db/rp mapping is there from the dbrps endpoint:
```
curl --request GET http://localhost:8086/api/v2/dbrps\?orgID\=84369b2ddc1ebb8b \
--header "Authorization: Token =="
{
	"content": [
		{
			"id": "0693dfc08bbe8000",
			"database": "telegraf",
			"retention_policy": "autogen",
			"default": true,
			"organization_id": "84369b2ddc1ebb8b",
			"bucket_id": "18da3926266760db"
		}
	]
}
```

**Comment by stuartcarnie** [comment] 2020-11-08 01:04
Can you provide the exact `influx v1 auth create` command you executed?

**Comment by stuartcarnie** [comment] 2020-11-08 01:14
The problem is creating a token manually is a two-step process:

1. Create a token “foo”, which is equivalent to the username from 1.x:

    ```
    influx v1 auth create --auth-token foo --write-bucket 7425a44ac4116e88 --read-bucket 7425a44ac4116e88
    ```

2. Assign a password to token “foo”, which creates the bcrypt hash:

    ```
    influx v1 auth set-password --name foo
    ```

    will be prompted for the password

**Comment by stuartcarnie** [comment] 2020-11-08 01:27
The more I think about this, the UI for the CLI tool is just wrong. It was lifted from the v2 `auth` command, but should be clearer. We should change `--auth-token` to `--username` to be clearer from a 1.x perspective. Creating an auth token, by default, should prompt for a password and only create the token if it has both.

**Comment by stuartcarnie** [comment] 2020-11-08 21:56
Verified auth is working when passwords are set, so closing this in favour of improving the `influx v1 auth create` command via #19933

**Closed by stuartcarnie** 2020-11-08 21:56 UTC
Labels: rc-bugs
