### ISSUE TITLE
database compacting is frequently aborted

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#14608] opened 2019-08-09 15:36 UTC
OS: CentOS 6.10
Influxdb version: 1.7.6

As part of some cleanup, I'm deleting close to 10,000 data series from influxdb ("DROP SERIES ...") from a script that I wrote to automate this. The deletion rate is one series every few seconds. I assume that a "DROP SERIES" is a trigger to make influxdb kick off a database compaction. For reasons unknown, influxdb seems to be pretty bad at deciding on whether or not to compact something as each attempt is aborted.

```
ts=2019-08-09T15:30:32.156603Z lvl=info msg="Beginning compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktUN0000 op_name=tsm1_compact_group tsm1_files_n=4
ts=2019-08-09T15:30:32.156613Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktUN0000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/collectd/autogen/410/000000511-000000002.tsm
ts=2019-08-09T15:30:32.156625Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktUN0000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/collectd/autogen/410/000000511-000000003.tsm
ts=2019-08-09T15:30:32.156634Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktUN0000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/collectd/autogen/410/000000511-000000004.tsm
ts=2019-08-09T15:30:32.156654Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktUN0000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/collectd/autogen/410/000000511-000000005.tsm
ts=2019-08-09T15:30:32.236085Z lvl=info msg="Aborted compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0H9ktPc0000 op_name=tsm1_compact_group error="compactions disabled"
ts=2019-08-09T15:30:32.236129Z lvl=info msg="TSM compaction (end)" log_id=0H8GbAO0000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0H9ktPc0000 op_name=tsm1_compact_group op_event=end op_elapsed=1295.477ms
ts=2019-08-09T15:30:34.208387Z lvl=info msg="TSM compaction (start)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group op_event=start
ts=2019-08-09T15:30:34.208446Z lvl=info msg="Beginning compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_files_n=4
ts=2019-08-09T15:30:34.208459Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000002.tsm
ts=2019-08-09T15:30:34.208481Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000003.tsm
ts=2019-08-09T15:30:34.208491Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000004.tsm
ts=2019-08-09T15:30:34.208501Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000005.tsm
ts=2019-08-09T15:30:35.023739Z lvl=info msg="Aborted compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktT3W000 op_name=tsm1_compact_group error="compactions disabled"
ts=2019-08-09T15:30:35.023799Z lvl=info msg="TSM compaction (end)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktT3W000 op_name=tsm1_compact_group op_event=end op_elapsed=3201.040ms
```

**Comment by yellowpattern** [comment] 2019-08-09 15:38
Another log sample that includes reference to the DROP SERIES command:

```
ts=2019-08-09T15:30:33.513122Z lvl=info msg="Executing query" log_id=0H8GbAO0000 service=query query="DROP SERIES FROM ps WHERE host = 'host1' AND instance = 'fred' AND type = 'percent' AND type_instance = 'cpu_unk13577'"
ts=2019-08-09T15:30:33.753264Z lvl=info msg="Aborted compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0H9ktICl000 op_name=tsm1_compact_group error="compactions disabled"
ts=2019-08-09T15:30:33.753316Z lvl=info msg="TSM compaction (end)" log_id=0H8GbAO0000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=0H9ktICl000 op_name=tsm1_compact_group op_event=end op_elapsed=4709.521ms
ts=2019-08-09T15:30:33.834124Z lvl=info msg="TSM compaction (start)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group op_event=start
ts=2019-08-09T15:30:33.834171Z lvl=info msg="Beginning compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_files_n=8
ts=2019-08-09T15:30:33.834184Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000282-000000001.tsm
ts=2019-08-09T15:30:33.834198Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000283-000000001.tsm
ts=2019-08-09T15:30:33.834220Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000284-000000001.tsm
ts=2019-08-09T15:30:33.834232Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000285-000000001.tsm
ts=2019-08-09T15:30:33.834243Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=4 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000286-000000001.tsm
ts=2019-08-09T15:30:33.834255Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=5 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000287-000000001.tsm
ts=2019-08-09T15:30:33.834266Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=6 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000288-000000001.tsm
ts=2019-08-09T15:30:33.834279Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=0H9kt_vW000 op_name=tsm1_compact_group tsm1_index=7 tsm1_file=/var/lib/influxdb/data/collectd/autogen/618/000000289-000000001.tsm
ts=2019-08-09T15:30:34.052148Z lvl=info msg="Aborted compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9kt33G000 op_name=tsm1_compact_group error="compactions disabled"
ts=2019-08-09T15:30:34.052202Z lvl=info msg="TSM compaction (end)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9kt33G000 op_name=tsm1_compact_group op_event=end op_elapsed=8886.802ms
ts=2019-08-09T15:30:34.208387Z lvl=info msg="TSM compaction (start)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group op_event=start
ts=2019-08-09T15:30:34.208446Z lvl=info msg="Beginning compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_files_n=4
ts=2019-08-09T15:30:34.208459Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000002.tsm
ts=2019-08-09T15:30:34.208481Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000003.tsm
ts=2019-08-09T15:30:34.208491Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000004.tsm
ts=2019-08-09T15:30:34.208501Z lvl=info msg="Compacting file" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktbO0000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/collectd/autogen/394/000000517-000000005.tsm
ts=2019-08-09T15:30:35.023739Z lvl=info msg="Aborted compaction" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktT3W000 op_name=tsm1_compact_group error="compactions disabled"
ts=2019-08-09T15:30:35.023799Z lvl=info msg="TSM compaction (end)" log_id=0H8GbAO0000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=0H9ktT3W000 op_name=tsm1_compact_group op_event=end op_elapsed=3201.040ms
```

**Comment by jacobmarble** [comment] 2019-09-16 17:27
Duplicate of #14426

**Closed by jacobmarble** 2019-09-16 17:27 UTC
Labels: 1.x

**Comment by tgreeniaus** [comment] 2023-06-22 22:25
How is this a duplicate of #14426?  In that issue there was a temporary file that exists, in this issue it is aborting because compactions are disabled.  I am also doing a lot of DELETE operations from a database and getting this compaction issue and the database is becoming slower and slower to delete stuff from it seems.  I'm on a 64-bit Linux with 8GB of RAM so I don't think it is the 32-bit issue discussed in #14426:

# uname -a
Linux xdh-n-1000000 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
