### ISSUE TITLE
[0.9.2-rc1]  aggregate functions do not take all records in consideration in the presence of tags and absence of a group by time() clause

### ISSUE THREAD

**Issue by samidalouche** [influxdata/influxdb#3437] opened 2015-07-22 21:17 UTC
How to reproduce
```bash
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

curl -G "https://gist.githubusercontent.com/samidalouche/72c7e1cdcf0435d2115e/raw/69e4f442344e02a5db068105e48c15c70104acdb/gistfile1.txt" -o input.video_download-requests
curl -i -XPOST 'http://localhost:8086/write?db=mydb&precision=ms' --data-binary "@input.video_download-requests"

QRY_KO="select sum(value) from \"kpi.video_downloads.requested.tic\" where time > '2015-05-21T00:00:00.000Z' and time < '2015-06-23T00:00:00.000Z' group by accountId"
QRY_OK="select sum(value) from \"kpi.video_downloads.requested.tic\" where time > '2015-05-21T00:00:00.000Z' and time < '2015-06-23T00:00:00.000Z' group by accountId, time(52w)"


curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=$QRY_KO"
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=$QRY_OK"
```

This is what I get on my freshly-installed influxdb 0.9.2-rc1 on Mac OS X

```bash
Samis-MacBook-Pro:influxdb-aggregates samidalouche$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=$QRY_OK"
{
    "results": [
        {
            "series": [
                {
                    "name": "kpi.video_downloads.requested.tic",
                    "tags": {
                        "accountId": "0291e400-62c1-4709-bfbb-fdeec06c54c4"
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "2014-11-06T00:00:00Z",
                            40
                        ]
                    ]
                },
                {
                    "name": "kpi.video_downloads.requested.tic",
                    "tags": {
                        "accountId": "984f31d7-f329-434e-8b15-ee6921d6e2c6"
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "2014-11-06T00:00:00Z",
                            24
                        ]
                    ]
                }
            ]
        }
    ]
}Samis-MacBook-Pro:influxdb-aggregates samidalouche$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=$QRY_KO"
{
    "results": [
        {
            "series": [
                {
                    "name": "kpi.video_downloads.requested.tic",
                    "tags": {
                        "accountId": "0291e400-62c1-4709-bfbb-fdeec06c54c4"
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "2015-05-10T23:59:59.998996Z",
                            20
                        ]
                    ]
                },
                {
                    "name": "kpi.video_downloads.requested.tic",
                    "tags": {
                        "accountId": "984f31d7-f329-434e-8b15-ee6921d6e2c6"
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "2015-05-10T23:59:59.998996Z",
                            12
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by beckettsean** [comment] 2015-08-25 22:06
@samidalouche So the count that returns 40 and 24 is the correct count?

**Comment by beckettsean** [comment] 2015-08-25 22:07
Can you reproduce this with 0.9.3-rc2?

**Comment by jsternberg** [comment] 2016-04-06 19:51
We've had a complete refactor of the query engine since this bug was filed, so I'm going to close this as I don't think the issue still exists.

If this issue still exists with the latest version of InfluxDB, please reopen with more details so we can fix the issue. Thanks.

**Closed by jsternberg** 2016-04-06 19:51 UTC
