### ISSUE TITLE
[Feature Request] IN operator for tags in WHERE clauses

### ISSUE THREAD

**Issue by pkittenis** [influxdata/influxdb#7700] opened 2016-12-07 16:14 UTC
### Feature Request

__Proposal:__ 

Add `IN` operator as a valid `WHERE` clause for tags.

__Current behavior:__ Not supported. Can only `GROUP BY` tag and filter results on wanted tag values client side instead.

__Desired behavior:__ `SELECT` query returns data for values `WHERE <tag> IN ('val1', 'val2', ..)`

__Use case:__ 

Client wants data for a _specific set_ of tag values, and there are many values for the tag in the DB.

While `GROUP BY` on a tag works well, it will return data for all tag values of the grouped by tag. Some schemas have hundreds/thousands of unique tag values for a tag, in particular for tags such as `host`/`hostname` across the entire DB or per `region` where `region` is another tag.

In those cases, telling the DB to only select values for example `WHERE "host" IN ('my_host1', 'my_host2', 'my_host3')` rather than all hosts can allow the DB to only process data we are interested in and save on processing time.

Currently can only be done client side after a query like `SELECT <..> WHERE <..> GROUP BY time(<..>), 'host'`, followed by client side filtering on wanted tag values. This forces InfluxDB to process data the user will not be using and can cause performance degradation on tags with hundreds/thousands of unique values.

Thank you for reading and for all the great work.

**Comment by jwilder** [comment] 2016-12-07 21:44
You should be able to use `... (<tag> = 'val1' OR <tag> = 'val2' ...)`.  Does that not work?

**Comment by jwilder** [comment] 2016-12-07 21:47
Closing this since it's a duplicate of #2157

**Closed by jwilder** 2016-12-07 21:47 UTC
Labels: area/query language, kind/feature request

**Comment by pkittenis** [comment] 2016-12-08 11:33
Apologies, searched for any existing requests but missed that one. Yes, multiple ORs should work for the time being, thanks for pointing that out.

**Comment by ishita07-danaher** [comment] 2020-02-11 13:50
Hi..I was trying to implement something similar using both reg ex and 'OR' .
Where these approaches fail :

1) Reg ex : if the value I have passed is contained in the column value, it reads that though it shouldn't. Reg ex is similar to 'contains'..I want to compare the exact same value.

2) OR : I want data for both values not either of them. 

Please suggest another approach for IN clause.
