### ISSUE TITLE
0.11 regression: select count(distinct())

### ISSUE THREAD

**Issue by Tinche** [influxdata/influxdb#6123] opened 2016-03-25 15:57 UTC
I've just upgraded our local instance to 0.11 (using apt, running on Ubuntu). The query:

````
SELECT count(distinct(username)) FROM ngs_metrics."default"."webserver-to-webserver" WHERE time > now() - 30d GROUP BY time(1d) fill(0)
````
used to work on 0.10, but now returns nothing. `username` is a field, not a tag.

**Comment by Tinche** [comment] 2016-03-25 16:30
Playing around some more,
```
select count(distinct("username")) from "webserver-to-webserver" WHERE time > now() - 18d GROUP BY time(1d)
```
works, but bumping up the range
```
select count(distinct("username")) from "webserver-to-webserver" WHERE time > now() - 19d GROUP BY time(1d)
```
returns nothing. That might be the cutoff when we actually started recording usernames for this measurement.

**Comment by jsternberg** [comment] 2016-03-25 21:12
Do you have a reproducer I could try?

**Comment by jsternberg** [comment] 2016-04-03 20:22
Hello @Tinche. I'm going to close this since not enough information has been given for us to reproduce the bug. If you run into the issue again and can give us more info, please reopen with that information and I'll take a look at it as soon as I can.

Thank you.

**Closed by jsternberg** 2016-04-03 20:22 UTC
Labels: category/queries, need more info
