### ISSUE TITLE
Influx bucket pagination issue

### ISSUE THREAD

**Issue by Mikolaj6** [influxdata/influxdb#23865] opened 2022-11-07 13:41 UTC
Influx pagination doesn't work as expected. 

__Steps to reproduce:__

1.  Create new influx instance, add more than X buckets (at least X+1)
2. Add a token for reading all buckets 
3. Use influx API to get X buckets:
`curl --request GET "http://<host>:<port>/api/v2/buckets?limit=X" --header "Authorization: Token <read_all_token>" --header "Accept: application/json" --header "Content-Type: application/json"`
There will be at least 1 bucket that will not be in the returned list.
4. Create read access token for this bucket.
5. Run the same query as before but use the newly created token. You can also change X to anything between 1 and X.
`curl --request GET "http://<host>:<port>/api/v2/buckets?limit=X" --header "Authorization: Token <read_one_bucket_token>" --header "Accept: application/json" --header "Content-Type: application/json"`
6. You will get an empty list.
7. Increase limit value (it can also by achieved by adding offset):
`curl --request GET "http://<host>:<port>/api/v2/buckets?limit=<Total number of buckets>" --header "Authorization: Token <read_one_bucket_token>" --header "Accept: application/json" --header "Content-Type: application/json"`
8. Returned list will contain this one bucket.

__Expected behavior:__
I would expect on step 6 to get a list with bucket that access token from step 4 has access to.

__Actual behavior:__
I get an empty list despite limit being at least 1.

Based on my tests it seems that pagination is implemented by first applying limits and offsets on ALL buckets and then by filtering using access tokens. I would expect that filtering should be applied first and pagination later. 

I think this issue also creates problems in grafana's influx datasource. When you try to create a datasource that uses an access token which can read from a small subset of buckets and none of these buckets are in the first 20 listed buckets (default limit for API calls), the datasource creation process will fail with error "no buckets found".

__Environment info:__

* InfluxDB version: Tested on both 2.2 and 2.4, didn't test on 2.5

**Comment by jeffreyssmith2nd** [comment] 2022-11-07 21:02
2.5.1 fixes the issue where you would only see the first 20 buckets if a larger limit was posted. The rest of the behavior sounds like what we have described at https://github.com/influxdata/influxdb/issues/23751

**Comment by Mikolaj6** [comment] 2022-11-08 09:05
Yes, that seems to be the same issue. Thanks for pointing it out.

I didn't find any info about this bucket limit in release notes for v2.5 or v2.5.1.

**Comment by jeffreyssmith2nd** [comment] 2022-11-08 14:40
Yeah I see that wasn't captured clearly in the notes, it was fixed as part of the work to backup all buckets in an influxdb instance since that's the situation that highlighted the issue to us.

I'm going to close this as a duplicate of the other and link this main comment to the other for additional info, thanks for the detailed report.

**Closed by jeffreyssmith2nd** 2022-11-08 14:40 UTC
