### ISSUE TITLE
A incorrect tag is inserted

### ISSUE THREAD

**Issue by Tancen** [influxdata/influxdb#16005] opened 2019-11-21 12:50 UTC
InfluxDB version: 1.7.8

![image](https://user-images.githubusercontent.com/3649637/69339396-33b4a980-0ca0-11ea-9553-319a39f32ca0.png)

![image](https://user-images.githubusercontent.com/3649637/69339500-6d85b000-0ca0-11ea-9b1b-08e7622ea797.png)

**Comment by russorat** [comment] 2019-11-22 19:00
@Tancen thanks for reporting. I'm having trouble recreating with 1.7.9. Is there some other process that is writing data or something i'm missing here?

```
> use fastenergy_data
Using database fastenergy_data
> select * from fastenergy_data
> insert count_121,id=100000000407 point_229_0=100i
> select * from count_121
name: count_121
time                id           point_229_0
----                --           -----------
1574449078209796000 100000000407 100
> insert count_121,id_1_1=100000000408 point_229_0=100i
> select * from count_121
name: count_121
time                id           id_1_1       point_229_0
----                --           ------       -----------
1574449078209796000 100000000407              100
1574449140375362000              100000000408 100
```

**Comment by Tancen** [comment] 2019-11-23 04:46
I found the cause of this bug.

![image](https://user-images.githubusercontent.com/3649637/69472876-5dcf9f80-0d64-11ea-8f44-19adec2bcf12.png)

The table that is copied has also the same bug, But I don't how to reappear.

**Comment by Tancen** [comment] 2019-11-25 10:13
@russorat

**Comment by russorat** [comment] 2019-11-25 17:18
@Tancen the issue is that when you do `INSERT INTO`, you need to add a `GROUP BY *` in order to preserve the Tags. The reason you see an `id` and an `id_1` is that the new table has a tag named `id` and a field named `id`, so the UI is adding a `_1` to differentiate it.

`select * into test_tmp from test group by *`

See the docs here: https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#rename-a-database

I'm closing this since it isn't a bug. If you have additional questions, a good place to ask would be the community slack channel: https://influxdata.com/slack

```
> create database test
> use test
Using database test
> insert test,id=1 a=3
> insert test,id=1 a=4
> insert test,id=1 a=5
> insert test,id=1 a=6
> select * into test_tmp from test group by *
name: result
time written
---- -------
0    4
> insert test,id=1 a=7
> insert test_tmp,id=1 a=7
> select * from test_tmp
name: test_tmp
time                a id
----                - --
1574702057628832000 3 1
1574702059200302000 4 1
1574702060962138000 5 1
1574702062823355000 6 1
1574702114008865000 7 1
```

**Closed by russorat** 2019-11-25 17:18 UTC
Labels: 1.x, need more info
