### ISSUE TITLE
A custom variable with a reference to another custom variable does not work in dashboards

### ISSUE THREAD

**Issue by xpg934** [influxdata/influxdb#20757] opened 2021-02-14 15:53 UTC
__Steps to reproduce:__

1. Add a new custom variable, for example "bucket" with the query:

```
buckets()
  |> filter(fn: (r) => r.name !~ /^_/)
  |> rename(columns: {name: "_value"})
  |> keep(columns: ["_value"])
```

2. Add another one custom variable, for example "host" with the query, that references to v.bucket:

```
import "influxdata/influxdb/schema"
schema.tagValues(bucket: v.bucket, tag: "host")
```

3. Go to Dashboards in UI and create new dashboard with one cell (any type of graph) for query like this:

```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["host"] == v.host)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user" or r["_field"] == "usage_system")
  |> filter(fn: (r) => r["cpu"] == "cpu-total")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

4. Close that dashboard and open it again => Variable "bucket" will be set by first item from list of its values, but "host" variable will be empty !!!, and there is no list of values.

5. Change variable "bucket" to any other, than back to first selected -> variable "host" now ok, available list of values.

__Expected behavior:__
All variable values should be set when dashboard opened.

__Actual behavior:__
Only variables without reference to another custom variable is set when dashboard is opened.

__Environment info:__

* System info: Linux 4.19.0-9-amd64 x86_64
* InfluxDB version: InfluxDB 2.0.3 (git: fe04d346df) build_date: 2020-12-15T01:00:16Z
* Other relevant environment details: clean setup without docker.

**Comment by hoorayimhelping** [comment] 2021-02-19 20:14
duplicate of #18828

**Closed by hoorayimhelping** 2021-02-19 20:14 UTC
Labels: team/ui
