### ISSUE TITLE
[InfluxDB V0.12.0] High memory usage (RES, VIRT) observed

### ISSUE THREAD

**Issue by junyhu** [influxdata/influxdb#6718] opened 2016-05-25 02:07 UTC
hi there,
I'm seeing heap usage is under 1g but RES is 3.8g with influxDB v0.12.0.

There are around 5k measurements in my influxDB, and # of series is around 5k also. see details in below screenshot pls.
![image](https://cloud.githubusercontent.com/assets/18591250/15525783/6398db50-225f-11e6-872e-8f7c14544631.png)
while checking heap usage it's showing around 1g.
![image](https://cloud.githubusercontent.com/assets/18591250/15525825/b472f5c4-225f-11e6-8b82-bd66804a08cc.png)

However, with top command i found that 3.8G memory space has been occupied by influxDB process.
![image](https://cloud.githubusercontent.com/assets/18591250/15525849/e3defb28-225f-11e6-81ac-7244b383ae5e.png)

By using below commands i took two heap.txt and goroutine.txt files within 14 hours.
curl -o heap.txt http://localhost:8086/debug/pprof/heap?debug=1
curl -o goroutine.txt http://localhost:8086/debug/pprof/goroutine?debug=1
[heap.txt](https://github.com/influxdata/influxdb/files/280859/heap.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/280860/goroutine.txt)
[heap_after14 hours.txt](https://github.com/influxdata/influxdb/files/280861/heap_after14.hours.txt)
[goroutine_after 14 hours.txt](https://github.com/influxdata/influxdb/files/280862/goroutine_after.14.hours.txt)

Can someone help me understand why influxdb takes 3.8G RAM? We don't have much data and i believe it should not reach so much high memory usage.

Thanks
Iris

**Comment by jwilder** [comment] 2016-05-25 02:15
It looks like a client may be leaking query connections.  Are your clients closing connections or re-using them appropriately?

**Comment by junyhu** [comment] 2016-05-25 03:09
@jwilder thanks for the suggestion! Actually yesterday i just ran a query **select * from "tsm1_cache"** and then RES increased from less than 1G to 3.8G, and heap increased from avg 500M to avg 1G.
I understand the query i provided might reach to a lot of shards as i didn't give a time filter. What I don't understand is...after 14 hours, still heap & RES remain high even the query has finished execution for a while.

**Comment by jwilder** [comment] 2016-05-25 03:19
@junyhu The profiles show a lot of query goroutines still running so it looks like something is repeatedly querying the database and leaving a connection open.  When or if the heap will go down and be released to the OS is partially controlled by how the go garbage collector works.  If a connection is still open, the memory used by the connection can't be freed and it will also hold onto system resources.

**Comment by junyhu** [comment] 2016-05-25 09:15
@jwilder Grafana keeps querying data from influxDB to display dashboards. That's why you see many open query connection i guess.... Is it possible to set a max query connection in influxDB or some sort of approaches to close connection from Grafana side? Any idea..?

**Comment by jwilder** [comment] 2016-05-25 14:48
@junyhu The current nightlies have a config option to limit http connections.  See #6601.  It's not available in 0.12 or 0.13.

**Comment by zhiwzhao** [comment] 2016-05-30 02:54
@jwilder ,the problem is when influxdb has lots of query load (lots of query, or select * from a large measurement), the memory will be very high. we can understand as influxdb need to process this load, but the high memory keep there even when the load is over. seems it does not want to go down. please check if there is memory leak.

**Comment by junyhu** [comment] 2016-06-16 02:53
@jwilder, adding more observations

on May 30th we restarted influxdb and then both heap and RES back to normal. Heap: 1G->208MB; RES: 5.2G -> 374MB
However, after two weeks, heap was increased to ~1G again, and RES usage was increased to ~ 3.7G
We also observed that goroutine num is keeping increased like below
![image](https://cloud.githubusercontent.com/assets/18591250/16104020/25f6586a-33b0-11e6-9a71-e40ed5193de5.png)

I did pprof for goroutine three times and find below items are occupying most of goroutine. Is it a sign of goroutine leak or something?

1st one
![image](https://cloud.githubusercontent.com/assets/18591250/16104054/658f5904-33b0-11e6-9cb5-1dd855fc35bd.png)

2nd one
![image](https://cloud.githubusercontent.com/assets/18591250/16104063/734de916-33b0-11e6-8434-247316d1ad21.png)

3rd one
![image](https://cloud.githubusercontent.com/assets/18591250/16104067/7f671010-33b0-11e6-9a80-2032241bd412.png)

**Comment by junyhu** [comment] 2016-06-17 06:28
@jwilder still goroutine number and heap usage is increasing today. I'm adding top/iostat output for your information.

Top
![image](https://cloud.githubusercontent.com/assets/18591250/16142331/ebb1f708-3496-11e6-91f2-738840c69845.png)

iostat
![image](https://cloud.githubusercontent.com/assets/18591250/16142417/b75b8c2a-3497-11e6-873e-f06de495d3d5.png)

**Comment by BrannonKing** [comment] 2016-07-11 21:44
I too see the same thing in the beta2 build: query memory never goes down. It's a super scary bug.

**Comment by carbolymer** [comment] 2016-07-17 20:08
I've ran into similar memory issues: #5440

**Comment by jwilder** [comment] 2016-07-19 00:49
@junyhu Please see my [comment](https://github.com/influxdata/influxdb/issues/6718#issuecomment-221463260) above.  The goroutine leak you are seeing is open HTTP client connections that are not being closed.  A client is not closing them so they are remaining open.  If you upgrade to the 1.0 releases, there is a `[http].max-connection-limit` setting you can set to limit the number of connections which may help identify the problem client.

**Closed** 2016-11-17 00:54 UTC
