### ISSUE TITLE
Convert SHOW TAG KEYS to distributed query

### ISSUE THREAD

**Issue by dgnorton** [influxdata/influxdb#3295] opened 2015-07-10 19:52 UTC

**Comment by li-ang** [comment] 2015-11-04 03:44
Is the issue fixed? I test it ok .

**Comment by beckettsean** [comment] 2015-11-04 18:29
@li-ang this issue applies only to clusters. The query is known to work on single node systems, but there are some cluster-specific features yet to be completed.

**Comment by li-ang** [comment] 2015-11-05 01:40
I mean I test is ok on 0.9.4 influxdb cluster with three node and the replication of the retention policy is 3.

**Comment by beckettsean** [comment] 2015-11-05 05:45
@li-ang A fully replicated cluster is effectively the same as a single instance for queries. Every node has all the data and can answer any query independently. In a non-fully replicated cluster, nodes have to ask other nodes for data, which is what this issue covers.

**Comment by li-ang** [comment] 2015-11-05 05:54
@beckettsean Got it! Thank you very!

**Comment by Styx13** [comment] 2015-11-30 22:07
Hello, is that issue supposed to be fixed ?

I am currently running with `v0.9.5-rc1` with a 8 nodes cluster.

`SHOW TAG KEYS FROM ...` generates the following error:
`Server returned error: write message type: write tcp [::1]:45760->[::1]:8098: use of closed network connection`

It is interesting that the `SHOW TAG VALUES FROM "measurement_name" WITH KEY = "tag_key"` works fine.

Could the issue with the `SHOW TAG KEYS` be similar to the `SHOW MEASUREMENT` issue from #4927 and #4833.

BTW `SHOW MEASUREMENTS` seems fixed and runs almost properly since I applied commit: f8040269d96c1faff47d73ca9a2cc872bf948165.
(I still run into an issue where I get `Server returned error: read message type: read tcp [::1]:57346->[::1]:8093: i/o timeout` with a database of ~2700 series with ~40000 datapoint each)

**Comment by beckettsean** [comment] 2015-12-01 00:20
@Styx13 the issue is not closed, so it is not fixed. This is a cluster-specific issue, which is why @li-ang did not hit it when testing on a single node.

**Comment by CrazyJvm** [comment] 2015-12-12 15:46
please refer to PR: https://github.com/influxdb/influxdb/pull/5101

**Comment by toddboom** [comment] 2016-03-23 01:17
Closing this out because it's no longer applicable.

**Closed by toddboom** 2016-03-23 01:17 UTC
Labels: 2 - Working, category/queries, review
