### ISSUE TITLE
cannot hide the query of a data explorer tab

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17177] opened 2020-03-10 17:29 UTC
there's no way to hide the results of a query tab anymore.

![image](https://user-images.githubusercontent.com/4805997/76341180-e8a7bc00-62b9-11ea-8a54-2c54f2bcd30d.png)

**Comment by Asalem1** [comment] 2020-03-10 19:21
This is a duplicate of #17167

**Closed by Asalem1** 2020-03-10 19:21 UTC
Labels: kind/bug, regression, team/monitoring
