### ISSUE TITLE
Influxdb 2.0 cloud - changes to notification endpoints do not "stick"

### ISSUE THREAD

**Issue by robansaldo** [influxdata/influxdb#17478] opened 2020-03-27 20:09 UTC
If you create an alert notification endpoint and later modify the endpoint, the modifications show up in the GUI, but are not reflected in the behavior of the endpoint.

For example:
1- Create an http notification endpoint with a POST URL of https://dev.kittenfight.com/api/test and save the endpoint. Wait until you receive a notification - POSTs to desired URL successful.
2 - Change the POST URL to https://prod.kittenfight.com/api/test and save the endpoint. Notifications will continue to be POSTed to https://dev.kittenfight.com/api/test even though GUI reflects the new endpoint URL.

This behavior extends to the name of the notification endpoint. If you change the name of the endpoint, the history continues to show the old endpoint name and does not reflect the new name.

**Comment by ebb-tide** [comment] 2020-03-30 16:43
dupe of : https://github.com/influxdata/idpe/issues/6569 closing this issue in favor of the other one.

**Comment by robansaldo** [comment] 2020-03-31 14:00
https://github.com/influxdata/idpe/issues/6569 returns a 404.

**Comment by ebb-tide** [comment] 2020-03-31 22:20
sorry about that- keeping this open.

**Comment by ebb-tide** [comment] 2020-05-20 00:03
This is actually trickier than I originally thought- when the notification rule task is created, it is created with the notification endpoint specified, when the original NE is altered, any new NR's created with it will inherit the changes, while the NR created with the old NE will not change, therefore continuing to behave as if it has not been changed. So. changes to NE do 'stick', but the rule task using them is not changed.

**Closed** 2021-06-11 21:35 UTC
Labels: kind/bug, monitoring-and-alerting, team/compute, team/ui
