### ISSUE TITLE
Sort order with moving average is wrong for standard (ASC) 

### ISSUE THREAD

**Issue by norges** [influxdata/influxdb#7896] opened 2017-01-27 08:25 UTC
### Bug report

__System info:__ 1.2.0 ,Debian Linux Kernel 2.6.32

__Steps to reproduce:__

1. generate a query with a moving average i.e: `SELECT all_night_HRV_index FROM "sleep"` or even `SELECT all_night_HRV_index FROM "sleep" ORDER BY time ASC`

__Expected behavior:__  The results should be sorted increased in time

__Actual behavior:__the results are not sorted

If you need more data form me let me know.

**Comment by e-dard** [comment] 2017-01-27 19:04
@norges you mention moving average but you queries seem to specify the measurement `all_night_HRV_index`. Do you have some exact queries, and is this easy to repro with some test data?

**Comment by norges** [comment] 2017-01-28 07:17
Sorry this was an error in the statements.

I have reproduced it with some test data which I share under: https://gist.github.com/norges/afc37e6e547587fc4cc8a566075aea9b

I wrote this data via the admin Interface.

I used the query `select moving_average(value,10) from test ORDER BY time ASC`
The result is not ordered like I think it should, I have attached the start of the query output a a screenshot.

![moving_average_issue](https://cloud.githubusercontent.com/assets/2143057/22395049/0d0ad572-e532-11e6-8cec-af24e31e31ee.jpg)

I hope this helps to reproduce the issue.

**Comment by robinsonjj** [comment] 2017-01-29 10:32
suspect that this bug has the same root cause as the issue in #7887?

**Comment by e-dard** [comment] 2017-01-30 13:15
@robinsonjj yes, quite possibly.

**Comment by jsternberg** [comment] 2017-05-03 14:49
I'm pretty sure this is fixed by #8214.

**Closed by jsternberg** 2017-05-03 14:49 UTC
Labels: area/functions, kind/bug, need more info
