### ISSUE TITLE
[0.10.1 to 0.10.3 upgrade] Requires to chown recursively ?

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/influxdb#5980] opened 2016-03-10 23:05 UTC
Hi,

I noticed on two machines (Debian/64 bits & Debian/ARM) that for the 0.10.1 to 0.10.3 upgrade path, I needed to ``chown -R influxdb: /var/lib/influxdb`` so that influxdb restarts well.

Upgrade went smoothly (ie no special warning) but after the upgrade, I could not connect with ``influx`` and port 8083/8086 were not opened.

On ARM, I noticed that a file had a permission issue (was owned by root) ; on Debian 64 bits, I did not see any error but doing the ``chown`` command solved the point.

```
pi@cixi /var/lib/influxdb $ grep -i "permission denied"  /var/log/influxdb/influxd.log 
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 127] open /var/lib/influxdb/wal/station/default/127/_00002.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
run: open server: open tsdb store: [shard 127] open /var/lib/influxdb/wal/station/default/127/_00002.wal: permission denied
run: open server: open tsdb store: [shard 130] open /var/lib/influxdb/wal/_internal/monitor/130/_00025.wal: permission denied
```

Once I chowned the files back to ``influxdb:``, InfluxDB started well and all expected ports were opened (especially 8083 & 8086).

On ARM box, I also did an upgrade with ``influxdb_tsm``, otherwise it failed to restart.

Hope it can be useful for someone.

**Comment by rossmcdonald** [comment] 2016-03-10 23:11
@nsteinmetz Did you convert the shards on the first machine with the `influx_tsm` tool? The permissions may have been set incorrectly after the conversion was completed, but I can't think of a reason why the permissions would be incorrect other than that. 

I'll run through an upgrade from 0.10.1 to 0.10.3 to see if I can reproduce.

**Comment by jonseymour** [comment] 2016-03-10 23:14
Of course, if you run influx_tsm as the root user, but normally run influxd with a non-root user, this will be a problem. One improvement might be for influx_tsm to either warn the user or refuse to convert shards that are not owned by the same user as the current user.

**Comment by nsteinmetz** [comment] 2016-03-10 23:21
@rossmcdonald:

I did the converstion only on the ARM box with ``influx_tsm`` tool indeed ; on the 64 bits one, I started from 0.10.1 version, so directly with TSM format. 

On 64 bits box, I did not check permissions ; I just tried what I did on the ARM one and it just worked. So I can't confirm it's a permission issue in this context.

@jonseymour: I did the migration with ``sudo`` as by default, my standard user could not run it. So indeed it explains the point. Maybe ``influx_tsm`` should be run as ``influxdb`` user or as root but with a ``chown influxdb: -R ...`` at the end to keep a proper permission context.

What is weird is that when I made a ``systemctl status influxdb``, it was reported as active and running. Port 8088 & 8091 were up but others were not.

**Comment by nsteinmetz** [comment] 2016-03-10 23:33
Weird, reviewing the log on the 64 bits machine, I don't see anything wrong.

```
[run] 2016/03/10 23:38:52 Signal received, initializing clean shutdown...
[run] 2016/03/10 23:38:52 Waiting for clean shutdown...
[cluster] 2016/03/10 23:38:52 cluster service accept error: network connection closed
[snapshot] 2016/03/10 23:38:52 snapshot listener closed
[copier] 2016/03/10 23:38:52 copier listener closed
[shard-precreation] 2016/03/10 23:38:52 Precreation service terminating
[continuous_querier] 2016/03/10 23:38:52 continuous query service terminating
[retention] 2016/03/10 23:38:52 retention policy enforcement terminating
[monitor] 2016/03/10 23:38:52 shutting down monitor system
[monitor] 2016/03/10 23:38:52 terminating storage of statistics
[handoff] 2016/03/10 23:38:52 shutting down hh service
[subscriber] 2016/03/10 23:39:12 closed service
[meta] 2016/03/10 23:39:13 server closed
[run] 2016/03/10 23:39:13 server shutdown completed
2016/03/10 23:39:13 InfluxDB starting, version 0.10.3, branch 0.10.0, commit f55169eaca706f78e2d66edb0b8e62861712a747, built 2016-03-09T17:13:16.236131
2016/03/10 23:39:13 Go version go1.4.3, GOMAXPROCS set to 1
2016/03/10 23:39:13 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/03/10 23:39:13 Starting meta service
[meta] 2016/03/10 23:39:13 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/03/10 23:39:13 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/03/10 23:39:13 Node at 127.0.0.1:8088 [Follower]
[metastore] 2016/03/10 23:39:15 Node at 127.0.0.1:8088 [Leader]. peers=[127.0.0.1:8088]
[metastore] 2016/03/10 23:39:15 Node at 127.0.0.1:8088 [Follower]. peers=[127.0.0.1:8088]
[metastore] 2016/03/10 23:39:16 Node at 127.0.0.1:8088 [Leader]. peers=[127.0.0.1:8088]
[meta] 2016/03/10 23:39:16 127.0.0.1 - - [10/Mar/2016:23:39:16 +0100] GET /?index=0 HTTP/1.1 200 898 - Go 1.1 package http ebe6915e-e710-11e5-8001-000000000000 3.420544ms
[store] 2016/03/10 23:39:16 Using data dir: /var/lib/influxdb/data
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/23
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/23/000000001-000000001.tsm (#0) opened in 763.874µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/23/_00005.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/24
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/24/000000001-000000001.tsm (#0) opened in 360.265µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/24/_00005.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/25
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/25/000000001-000000001.tsm (#0) opened in 386.284µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/25/_00004.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/26
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/26/000000001-000000001.tsm (#0) opened in 344.193µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/26/_00003.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/27
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/27/000000001-000000001.tsm (#0) opened in 310.823µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/27/_00004.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/29
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/29/000000001-000000001.tsm (#0) opened in 297.199µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/29/_00003.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/30
[filestore]2016/03/10 23:39:16 /var/lib/influxdb/data/_internal/monitor/30/000000001-000000001.tsm (#0) opened in 260.859µs
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/30/_00003.wal, size 0
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:16 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/31
[cacheloader] 2016/03/10 23:39:16 reading file /var/lib/influxdb/wal/_internal/monitor/31/_00001.wal, size 9508910
[cacheloader] 2016/03/10 23:39:17 reading file /var/lib/influxdb/wal/_internal/monitor/31/_00002.wal, size 0
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/12
[filestore]2016/03/10 23:39:17 /var/lib/influxdb/data/comptaonline/default/12/000000005-000000002.tsm (#0) opened in 816.04µs
[cacheloader] 2016/03/10 23:39:17 reading file /var/lib/influxdb/wal/comptaonline/default/12/_00013.wal, size 0
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/2
[filestore]2016/03/10 23:39:17 /var/lib/influxdb/data/comptaonline/default/2/000000001-000000001.tsm (#0) opened in 437.285µs
[cacheloader] 2016/03/10 23:39:17 reading file /var/lib/influxdb/wal/comptaonline/default/2/_00016.wal, size 0
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/20
[filestore]2016/03/10 23:39:17 /var/lib/influxdb/data/comptaonline/default/20/000000005-000000002.tsm (#0) opened in 735.104µs
[cacheloader] 2016/03/10 23:39:17 reading file /var/lib/influxdb/wal/comptaonline/default/20/_00011.wal, size 0
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:17 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/28
[filestore]2016/03/10 23:39:17 /var/lib/influxdb/data/comptaonline/default/28/000000001-000000001.tsm (#0) opened in 562.728µs
[cacheloader] 2016/03/10 23:39:17 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00004.wal, size 10495524
[cacheloader] 2016/03/10 23:39:25 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00005.wal, size 1367215
[cacheloader] 2016/03/10 23:39:26 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00006.wal, size 0
[tsm1wal] 2016/03/10 23:39:27 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:27 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/4
[filestore]2016/03/10 23:39:27 /var/lib/influxdb/data/comptaonline/default/4/000000005-000000002.tsm (#0) opened in 5.469664ms
[cacheloader] 2016/03/10 23:39:27 reading file /var/lib/influxdb/wal/comptaonline/default/4/_00016.wal, size 0
[handoff] 2016/03/10 23:39:27 Starting hinted handoff service
[monitor] 2016/03/10 23:39:27 'hh' registered for diagnostics monitoring
[handoff] 2016/03/10 23:39:27 Using data dir: /var/lib/influxdb/hh
[subscriber] 2016/03/10 23:39:27 opened service
[monitor] 2016/03/10 23:39:27 Starting monitor system
[monitor] 2016/03/10 23:39:27 'build' registered for diagnostics monitoring
[monitor] 2016/03/10 23:39:27 'runtime' registered for diagnostics monitoring
[monitor] 2016/03/10 23:39:27 'network' registered for diagnostics monitoring
[monitor] 2016/03/10 23:39:27 'system' registered for diagnostics monitoring
[cluster] 2016/03/10 23:39:27 Starting cluster service
[shard-precreation] 2016/03/10 23:39:27 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/03/10 23:39:27 Starting snapshot service
[copier] 2016/03/10 23:39:27 Starting copier service
[admin] 2016/03/10 23:39:27 Starting admin service
[admin] 2016/03/10 23:39:27 Listening on HTTP: 127.0.0.1:8083
[continuous_querier] 2016/03/10 23:39:27 Starting continuous query service
[httpd] 2016/03/10 23:39:27 Starting HTTP service
[httpd] 2016/03/10 23:39:27 Authentication enabled: false
[httpd] 2016/03/10 23:39:27 Listening on HTTP: 127.0.0.1:8086
[retention] 2016/03/10 23:39:27 Starting retention policy enforcement service with check interval of 30m0s
[run] 2016/03/10 23:39:27 Listening for signals
[monitor] 2016/03/10 23:39:27 Storing statistics in database '_internal' retention policy '', at interval 10s
2016/03/10 23:39:27 Sending anonymous usage statistics to m.influxdb.com
[run] 2016/03/10 23:39:30 Signal received, initializing clean shutdown...
[run] 2016/03/10 23:39:30 Waiting for clean shutdown...
[copier] 2016/03/10 23:39:30 copier listener closed
[cluster] 2016/03/10 23:39:30 cluster service accept error: network connection closed
[snapshot] 2016/03/10 23:39:30 snapshot listener closed
[shard-precreation] 2016/03/10 23:39:30 Precreation service terminating
[continuous_querier] 2016/03/10 23:39:30 continuous query service terminating
[retention] 2016/03/10 23:39:30 retention policy enforcement terminating
[monitor] 2016/03/10 23:39:30 shutting down monitor system
[monitor] 2016/03/10 23:39:30 terminating storage of statistics
[handoff] 2016/03/10 23:39:30 shutting down hh service
[subscriber] 2016/03/10 23:39:50 closed service
[meta] 2016/03/10 23:39:50 server closed
[run] 2016/03/10 23:39:51 server shutdown completed
2016/03/10 23:39:51 InfluxDB starting, version 0.10.3, branch 0.10.0, commit f55169eaca706f78e2d66edb0b8e62861712a747, built 2016-03-09T17:13:16.236131
2016/03/10 23:39:51 Go version go1.4.3, GOMAXPROCS set to 1
2016/03/10 23:39:51 Using configuration at: /etc/influxdb/influxdb.conf
[meta] 2016/03/10 23:39:51 Starting meta service
[meta] 2016/03/10 23:39:51 Listening on HTTP: 127.0.0.1:8091
[metastore] 2016/03/10 23:39:51 Using data dir: /var/lib/influxdb/meta
[metastore] 2016/03/10 23:39:51 Node at 127.0.0.1:8088 [Follower]
[metastore] 2016/03/10 23:39:52 Node at 127.0.0.1:8088 [Leader]. peers=[127.0.0.1:8088]
[metastore] 2016/03/10 23:39:53 Node at 127.0.0.1:8088 [Follower]. peers=[127.0.0.1:8088]
[metastore] 2016/03/10 23:39:54 Node at 127.0.0.1:8088 [Leader]. peers=[127.0.0.1:8088]
[meta] 2016/03/10 23:39:54 127.0.0.1 - - [10/Mar/2016:23:39:54 +0100] GET /?index=0 HTTP/1.1 200 898 - Go 1.1 package http 02a48ae6-e711-11e5-8001-000000000000 3.346228ms
[store] 2016/03/10 23:39:54 Using data dir: /var/lib/influxdb/data
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/23
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/23/000000001-000000001.tsm (#0) opened in 1.0505ms
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/23/_00006.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/24
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/24/000000001-000000001.tsm (#0) opened in 451.075µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/24/_00006.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/25
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/25/000000001-000000001.tsm (#0) opened in 348.072µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/25/_00005.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/26
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/26/000000001-000000001.tsm (#0) opened in 574.725µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/26/_00004.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/27
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/27/000000001-000000001.tsm (#0) opened in 493.235µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/27/_00005.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/29
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/29/000000001-000000001.tsm (#0) opened in 486.292µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/29/_00004.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/30
[filestore]2016/03/10 23:39:54 /var/lib/influxdb/data/_internal/monitor/30/000000001-000000001.tsm (#0) opened in 403.399µs
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/30/_00004.wal, size 0
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:54 tsm1 WAL writing to /var/lib/influxdb/wal/_internal/monitor/31
[cacheloader] 2016/03/10 23:39:54 reading file /var/lib/influxdb/wal/_internal/monitor/31/_00001.wal, size 9508910
[cacheloader] 2016/03/10 23:39:55 reading file /var/lib/influxdb/wal/_internal/monitor/31/_00003.wal, size 0
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/12
[filestore]2016/03/10 23:39:55 /var/lib/influxdb/data/comptaonline/default/12/000000005-000000002.tsm (#0) opened in 679.569µs
[cacheloader] 2016/03/10 23:39:55 reading file /var/lib/influxdb/wal/comptaonline/default/12/_00014.wal, size 0
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/2
[filestore]2016/03/10 23:39:55 /var/lib/influxdb/data/comptaonline/default/2/000000001-000000001.tsm (#0) opened in 473.42µs
[cacheloader] 2016/03/10 23:39:55 reading file /var/lib/influxdb/wal/comptaonline/default/2/_00017.wal, size 0
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/20
[filestore]2016/03/10 23:39:55 /var/lib/influxdb/data/comptaonline/default/20/000000005-000000002.tsm (#0) opened in 727.02µs
[tsm1wal] 2016/03/10 23:39:55 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/28
[filestore]2016/03/10 23:39:55 /var/lib/influxdb/data/comptaonline/default/28/000000001-000000001.tsm (#0) opened in 802.693µs
[cacheloader] 2016/03/10 23:39:55 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00004.wal, size 10495524
[cacheloader] 2016/03/10 23:39:59 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00005.wal, size 1367215
[cacheloader] 2016/03/10 23:40:00 reading file /var/lib/influxdb/wal/comptaonline/default/28/_00007.wal, size 0
[tsm1wal] 2016/03/10 23:40:00 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2016/03/10 23:40:00 tsm1 WAL writing to /var/lib/influxdb/wal/comptaonline/default/4
[filestore]2016/03/10 23:40:00 /var/lib/influxdb/data/comptaonline/default/4/000000005-000000002.tsm (#0) opened in 925.734µs
[cacheloader] 2016/03/10 23:40:00 reading file /var/lib/influxdb/wal/comptaonline/default/4/_00017.wal, size 0
[handoff] 2016/03/10 23:40:00 Starting hinted handoff service
[monitor] 2016/03/10 23:40:00 'hh' registered for diagnostics monitoring
[handoff] 2016/03/10 23:40:00 Using data dir: /var/lib/influxdb/hh
[subscriber] 2016/03/10 23:40:00 opened service
[monitor] 2016/03/10 23:40:00 Starting monitor system
[monitor] 2016/03/10 23:40:00 'build' registered for diagnostics monitoring
[monitor] 2016/03/10 23:40:00 'runtime' registered for diagnostics monitoring
[monitor] 2016/03/10 23:40:00 'network' registered for diagnostics monitoring
[monitor] 2016/03/10 23:40:00 'system' registered for diagnostics monitoring
[cluster] 2016/03/10 23:40:00 Starting cluster service
[shard-precreation] 2016/03/10 23:40:00 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2016/03/10 23:40:00 Starting snapshot service
[copier] 2016/03/10 23:40:00 Starting copier service
[admin] 2016/03/10 23:40:00 Starting admin service
[admin] 2016/03/10 23:40:00 Listening on HTTP: 127.0.0.1:8083
[continuous_querier] 2016/03/10 23:40:00 Starting continuous query service
[httpd] 2016/03/10 23:40:00 Starting HTTP service
[httpd] 2016/03/10 23:40:00 Authentication enabled: false
[httpd] 2016/03/10 23:40:00 Listening on HTTP: 127.0.0.1:8086
[retention] 2016/03/10 23:40:00 Starting retention policy enforcement service with check interval of 30m0s
[run] 2016/03/10 23:40:00 Listening for signals
[monitor] 2016/03/10 23:40:00 Storing statistics in database '_internal' retention policy '', at interval 10s
2016/03/10 23:40:00 Sending anonymous usage statistics to m.influxdb.com
```

After that, it worked well.

**Comment by joelegasse** [comment] 2016-03-10 23:38
Permissions and system administration are fun things, right? :-)

The "easy" answer is just to document that you should run the `influx_tsm` tool as the same user that you use to run your `influxd` process. Although I think doing something intelligent with the permissions (as per @jonseymour's suggestion) would be a much better user experience (as evidenced by this issue).

Since `influx_tsm` doesn't read in the `influxd` config, we could just try to update the permissions of the created directories to match the existing shards. I'll play with it tomorrow and see if I can get it working nicely.

**Comment by joelegasse** [comment] 2016-03-11 22:25
Just to update this issue, I didn't like anything I tried for getting the tool to update the permissions to match existing shards, so we decided to go with documenting that the tool should be run as the same user running the database.

**Comment by s1m0** [comment] 2016-03-13 16:34
Doesn't that mean that the influxdb user has to have write permissions on the backup location? That wasn't the case when I did the conversion so running it as root was my only option. So I had the same permissions problem after the conversion and had to run the recursive chmod to resolve. I think I opened an issue at the time.

**Comment by joelegasse** [comment] 2016-03-14 16:44
This really comes around to system administration, so yes, the user that runs the database will need write access to the backup location. I'm going to close this issue, as it will be documented in #5993

**Closed by joelegasse** 2016-03-14 16:44 UTC
Labels: category/packaging

**Comment by jonseymour** [comment] 2016-03-15 00:13
Seems reasonable to me.
