### ISSUE TITLE
InfluxDB 2: "influx v1 auth delete" ends in unauthorized

### ISSUE THREAD

**Issue by virtualdreams** [influxdata/influxdb#20619] opened 2021-01-27 09:49 UTC
Can't delete v1 auth token.

```sh
influx v1 auth delete -t foo2 --id 06fbcdf2e3595000
```

List:
```
ID                      Description     Name / Token    User Name       User ID                 Permissions
06fcb4ab911d7000                        foo             admin           06fbcdf2e3595000        [read:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31 write:orgs/d4e088bc64d4ace5/buckets/27fc9
abbd06e9b31]
06fcb831a35d7000                        foo2            admin           06fbcdf2e3595000        [read:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31 write:orgs/d4e088bc64d4ace5/buckets/27fc9
abbd06e9b31]
```

Result:
```
Error: Unauthorized access.
See 'influx v1 auth delete -h' for help
```

This makes no sense, because i can list and create tokens.

**Comment by danxmoran** [comment] 2021-01-27 15:41
@virtualdreams the error message is misleading. You're passing an ID from the `User ID` column, but the CLI / API expect one of the values from the `ID` column.

**Comment by virtualdreams** [comment] 2021-01-27 17:33
No, it doesn't work:

```
./influx v1 auth delete -t foo3 --id 06fbcdf2e3595000
Error: Unauthorized access.
See 'influx v1 auth delete -h' for help

./influx v1 auth delete -t foo3 --id 06fcb4ab911d7000
Error: Unauthorized access.
See 'influx v1 auth delete -h' for help
```

It doesn't matter whuch id i use.

**Comment by danxmoran** [comment] 2021-01-27 17:45
(I'm not able to reproduce this, so bear with me)

Does it work if you don't pass `-t`?

**Comment by virtualdreams** [comment] 2021-01-27 18:15
Yes, it deleted the first entry. But no further entries.

```sh
influx v1 auth delete --id 06fcb4ab911d7000
ID                      Description     Name / Token    User Name       User ID                 Permissions                                                                                  Deleted
06fcb4ab911d7000                        foo             admin           06fbcdf2e3595000        [read:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31 write:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31]    true

influx v1 auth delete  --id 06fcb4ab911d7000
Error: Authorization not found.
See 'influx v1 auth delete -h' for help

influx v1 auth list
ID                      Description     Name / Token    User Name       User ID                 Permissions
06fcb831a35d7000                        foo2            admin           06fbcdf2e3595000        [read:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31 write:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31]
06fccf51ecdd7000                        foo3            admin           06fbcdf2e3595000        [read:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31 write:orgs/d4e088bc64d4ace5/buckets/27fc9abbd06e9b31]
```

**Comment by danxmoran** [comment] 2021-01-27 18:51
That's expected, the API only supports one delete at a time.

The `-t` argument is a global flag for the `influx` CLI, used to override the authentication token used in all API requests. The reuse of "token" in this context is unfortunate. If you'd like to delete v1 auths by name, the `--username` flag is what should be used. For example:
```
influx v1 auth delete --username foo2
```

**Comment by virtualdreams** [comment] 2021-01-27 19:01
Yes this works fine. This should be better explained or the token option removed.  
It is not clear to which table the option `--username` references `Name / Token` or `User Name`.

And why the token belongs to "admin"?

**Comment by lesam** [comment] 2021-09-17 19:19
Summary:

## Issue 1: -t argument is confusing when a token could be taken as input

e.g.:

```
> ./influx v1 auth delete -h
NAME:
   influx v1 auth delete - Delete authorization

USAGE:
   influx v1 auth delete [command options] [arguments...]

OPTIONS:
   --host value                     HTTP address of InfluxDB [$INFLUX_HOST]
   --skip-verify                    Skip TLS certificate chain and host name verification [$INFLUX_SKIP_VERIFY]
   --configs-path value             Path to the influx CLI configurations [$INFLUX_CONFIGS_PATH]
   --active-config value, -c value  Config name to use for command [$INFLUX_ACTIVE_CONFIG]
   --http-debug
   --json                           Output data as JSON [$INFLUX_OUTPUT_JSON]
   --hide-headers                   Hide the table headers in output data [$INFLUX_HIDE_HEADERS]
   --token value, -t value          Authentication token [$INFLUX_TOKEN]
   --id value                       The ID of the authorization
   --username value                 The username of the authorization
```

Here the token is mixed with other arguments. I think moving it earlier in the list (with `--skip-verify and --host`) would help, and maybe change the help text to `   --token value, -t value          Token to authenticate request [$INFLUX_TOKEN]`.

## Issue 2: `--username` actually refers to `Name / Token` column, not `User Name` column.

Not sure what the right naming is, maybe @russorat can comment. In the code we call this the `Token`, but we set it with `./influx v1 auth create --username ...`.

My best guess is we should rename the list columns:

CURRENT:
```
> ./influx v1 auth create -o myorg -d cool --username dude --password password --read-bucket 0044f7260b9995f9
--write-bucket 0044f7260b9995f9
ID                      Description     Name / Token    User Name       User ID                 Permissions
082947d04a5e8000        cool            dude            sam             082946bc581e8000        [read:orgs/57e8bd7743d5f77d/buckets/0044f7260b9995f9 write:orgs/57e8bd7743d5f77d/buckets/0044f7260b9995f9]
```

PROPOSED:
```
> ./influx v1 auth create -o myorg -d cool --username dude --password password --read-bucket 0044f7260b9995f9
--write-bucket 0044f7260b9995f9
ID                      Description     Username    Creator Name       Creator ID                 Permissions
082947d04a5e8000        cool            dude            sam             082946bc581e8000        [read:orgs/57e8bd7743d5f77d/buckets/0044f7260b9995f9 write:orgs/57e8bd7743d5f77d/buckets/0044f7260b9995f9]
```

**Comment by russorat** [comment] 2021-09-17 21:53
I agree with the proposed changes. Also, we are moving to calling them API Tokens, if that helps clarify things.

**Comment by lesam** [comment] 2021-09-20 16:23
After changes:

```
> ./influx v1 auth list
ID                      Description             Username        v2 User Name    v2 User ID              Permissions
082d006fa1324000        my first v1 token       dude            sam             082d001dd1324000        [write:orgs/9aebecf29c3ffd0d/buckets/8bcaafa0c7b887c3]
> ./influx v1 auth delete -h
NAME:
   influx v1 auth delete - Delete authorization

USAGE:
   influx v1 auth delete [command options] [arguments...]

COMMON OPTIONS:
   --host value                     HTTP address of InfluxDB [$INFLUX_HOST]
   --skip-verify                    Skip TLS certificate chain and host name verification [$INFLUX_SKIP_VERIFY]
   --configs-path value             Path to the influx CLI configurations [$INFLUX_CONFIGS_PATH]
   --active-config value, -c value  Config name to use for command [$INFLUX_ACTIVE_CONFIG]
   --http-debug
   --json                           Output data as JSON [$INFLUX_OUTPUT_JSON]
   --hide-headers                   Hide the table headers in output data [$INFLUX_HIDE_HEADERS]
   --token value, -t value          Token to authenticate request [$INFLUX_TOKEN]

OPTIONS:
   --id value        The ID of the authorization
   --username value  The username of the authorization

> ./influx v1 auth delete --username dude
ID                      Description             Username        v2 User Name    v2 User ID              Permissions                   Deleted
082d006fa1324000        my first v1 token       dude            sam             082d001dd1324000        [write:orgs/9aebecf29c3ffd0d/buckets/8bcaafa0c7b887c3] true
```

**Closed** 2021-09-20 17:57 UTC
Labels: area/auth, area/compat-v1x, area/2.x
