### ISSUE TITLE
Database uses too many resources

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#5912] opened 2016-03-04 21:13 UTC
I run InfluxDB ver. 0.10.2 with default config on KVM with Ubuntu 14.04.4 LTS.
My instance has 2x CPU, 4GB RAM and it uses normal (not SSD) HDD.

By using Python in 1h I've added just 2 millions of data rows into 8 measurements 
(2 tags with hundreds of different values, and about 4 numeric fields each).
During this complex operation 95% of memory has been used
and due to database timeouts, huge lags and the only I can do was server restart...

But even after restart (and EVERY next restart...) InfluxDB process is still
uses a lot of CPU and over 80% of memory - in just 2-3 minutes without any
external tasks! After 10 minutes server needs another restart because influx
by processing inserted data forever causes enormous lags and load over 10.0.
Also influx web and API services are unavailable at least a few minutes directly after restart.

I've spent a lot of time for testing and implementation it for my software, 
but at this moment InfluxDB is the most buggy database I ever used :-(
Is InfluxDB even close to be production ready??

**Comment by gunnaraasen** [comment] 2016-03-04 22:49
I understand you're frustrated but I'm closing this issue because it is neither a bug report nor a feature request.

InfluxDB is handling hundreds of thousands of points per second in many production deployments, I suspect your memory issues stem from having too many series and are not due to a bug in the database itself. Please read the documentation on [schema design](https://docs.influxdata.com/influxdb/v0.10/concepts/schema_and_data_layout/) and send any questions to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

If you do stumble upon a reproducible bug, we'd like to hear about it here with steps to reproduce the issue.

**Closed by gunnaraasen** 2016-03-04 22:49 UTC

**Comment by mehdipourfar** [comment] 2018-04-16 16:35
I have the same problem. I admit that I have too many series but even without any connection, influxdb is using lots of CPU processes. I wonder what it is doing. (data has been entered about a 30 hours ago)
