### ISSUE TITLE
[0.11.0] Selecting from a series that doesn't exist causes panic

### ISSUE THREAD

**Issue by mjdesa** [influxdata/influxdb#5555] opened 2016-02-05 22:52 UTC
I initially thought that selecting from a series that didn't exist caused the panic, but now I'm unsure if that is correct, however I can fairly consistently reproduce a panic by running `influx_stress` with this configuration

```
[provision]
  [provision.basic]
    enabled = true
    address = "localhost:8086"
    database = "stress"
    reset_database = true

[write]
  [write.point_generator]
    [write.point_generator.basic]
      point_count = 10000000
      series_count = 1
      tick = "10s"
      jitter = true
      precision = "s"
      measurement = "cpu"
      start_date = "2006-Jan-02"
      [[write.point_generator.basic.tag]]
        key = "host"
        value = "server"
      [[write.point_generator.basic.tag]]
        key = "location"
        value = "us-west"
      [[write.point_generator.basic.field]]
        key = "value"
        value = "float64" # supported types: float64, int, bool


  [write.influx_client]
    [write.influx_client.basic]
      enabled = true
      addresses = ["localhost:8086"] # stress_test_server runs on port 1234
      database = "stress"
      precision = "s"
      batch_size = 10000
      batch_interval = "0s"
      concurrency = 10
      ssl = false
      format = "line_http" 
[read]
  [read.query_generator]
    [read.query_generator.basic]
      template = "SELECT count(value) FROM cpu where host='server-%v'"
      query_count = 250

  [read.query_client]
    [read.query_client.basic]
      enabled = true
      addresses = ["localhost:8086"]
      database = "stress"
      query_interval = "100ms"
      concurrency = 1
```

The panic is usually hit shortly after starting `influx_stress` and induces the panic

```
[meta] 2016/02/05 22:45:15 127.0.0.1 - - [05/Feb/2016:22:45:15 +0000] GET /?index=16 HTTP/1.1 200 272 - Go 1.1 package http 1fb4c1cc-cc5a-11e5-8049-000000000000 138.16317ms
[query] 2016/02/05 22:45:15 SELECT count(value) FROM stress."default".cpu WHERE host = 'server-4'
[http] 2016/02/05 22:45:15 127.0.0.1 - - [05/Feb/2016:22:45:15 +0000] POST /write?db=stress&precision=s HTTP/1.1 204 0 - Go 1.1 package http 1fc37305-cc5a-11e5-804d-000000000000 44.248392ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x61bfef]

goroutine 207 [running]:
github.com/influxdb/influxdb/tsdb.(*Shard).CreateIterator(0x0, 0x7f52c8b59aa8, 0xc209a2c390, 0x1041330, 0x0, 0x0, 0xc20ba42220, 0x1, 0x1, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/shard.go:388 +0xdf
github.com/influxdb/influxdb/tsdb.func·007(0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/shard.go:436 +0xcb
github.com/influxdb/influxdb/tsdb.Shards.CreateIterator(0xc20c48a0c0, 0x8, 0x8, 0x7f52c8b59aa8, 0xc209a2c390, 0x1041330, 0x0, 0x0, 0xc20ba42220, 0x1, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/shard.go:443 +0x1c3
github.com/influxdb/influxdb/tsdb.(*Shards).CreateIterator(0xc20c6d7960, 0x7f52c8b59aa8, 0xc209a2c390, 0x1041330, 0x0, 0x0, 0xc20ba42220, 0x1, 0x1, 0x0, ...)
	<autogenerated>:67 +0xfa
github.com/influxdb/influxdb/influxql.buildExprIterator(0x7f52c8b59aa8, 0xc209a2c390, 0x7f52c8b59ec8, 0xc20c6d7960, 0x7f52c8b59aa8, 0xc209a2c390, 0x1041330, 0x0, 0x0, 0xc20ba42220, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/select.go:199 +0x15d4
github.com/influxdb/influxdb/influxql.func·033(0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/select.go:133 +0x4f6
github.com/influxdb/influxdb/influxql.buildFieldIterators(0xc20e2b00d8, 0x1, 0x1, 0x7f52c8b59ec8, 0xc20c6d7960, 0x0, 0x0, 0x1041330, 0x0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/select.go:162 +0x103
github.com/influxdb/influxdb/influxql.Select(0xc2084901a0, 0x7f52c8b59ec8, 0xc20c6d7960, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/select.go:67 +0xd6d
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).PlanSelect(0xc20800acd0, 0xc2084901a0, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:275 +0x6ff
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).planStatement(0xc20800acd0, 0x7f52c8b59ce0, 0xc2084901a0, 0xc20815824e, 0x6, 0x2710, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:524 +0x1a4
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc20800acd0, 0x0, 0x7f52c8b59ce0, 0xc2084901a0, 0xc20815824e, 0x6, 0xc208158f60, 0x2710, 0xc2081583c0, 0x0, ...)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:648 +0x8f
github.com/influxdb/influxdb/tsdb.func·004()
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:172 +0xa1d
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:227 +0x242
```

[full panic](https://gist.github.com/mjdesa/099e706ecbdb29df28b2)

**Comment by zstyblik** [comment] 2016-02-06 09:31
@mjdesa I can try to reproduce on Monday, because if ``selecting from a series that didn't exist caused the panic'' is true, then I should be able to reproduce it even with Telegraf and small set of data, shouldn't I?

**Comment by seiflotfy** [comment] 2016-02-08 07:28
I can't replicate :(
What version of influx are you using. I am on master and according to the stacktrace the error is on line 388:
```
/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/shard.go:388 +0xdf
```
which says

```go
var seriesToAddShardTo []string
```

**Comment by zstyblik** [comment] 2016-02-08 08:01
I've tried to run the query against the data we have and no luck with crashing the instance.

**Comment by mjdesa** [comment] 2016-02-08 17:51
@seiflotfy @zstyblik The build was against the branch for this PR https://github.com/influxdata/influxdb/pull/5196

**Comment by benbjohnson** [comment] 2016-02-08 18:06
@mjdesa Can you try with this commit? https://github.com/benbjohnson/influxdb/pull/24

**Comment by mjdesa** [comment] 2016-02-08 22:04
@benbjohnson seems like its fixed

**Comment by jsternberg** [comment] 2016-02-09 17:17
Closing this since it seems to be fixed in the query engine branch.

**Closed by jsternberg** 2016-02-09 17:17 UTC
Labels: panic
