### ISSUE TITLE
can influxdb suport having like regular sql?

### ISSUE THREAD

**Issue by qianlnk** [influxdata/influxdb#6892] opened 2016-06-22 10:35 UTC
for example:
how can I run the query like this:
select difference("value") from "mymeasurement"
where time > now() - 3h 
group by time(10m)
having difference("value") != 0

Thank you for your time！

**Comment by jsternberg** [comment] 2016-06-22 13:14
I'm not entirely sure what you mean. If you're just talking about the `HAVING` clause, there's an issue #5266 for that.

**Comment by jsternberg** [comment] 2016-06-22 13:54
I think this is just a duplicate of #5266 so I'm going to close this. If I'm wrong, please comment with some more clarification and I'll reopen the ticket. Thanks.

**Closed by jsternberg** 2016-06-22 13:54 UTC
