### ISSUE TITLE
Panic on version 0.10.3-1 Centos x64

### ISSUE THREAD

**Issue by waqark3389** [influxdata/influxdb#6182] opened 2016-04-01 09:19 UTC
I have been running 0.10.3-1 for a few days now and yesterday, influx stopped responding and had crashed. Is this a known issue? Also I can see data using the administration portal at port 8083 but grafana does not seem to pick up older data? The actual data is still there. Here is the entry from the log file upon panic. 

```
[retention] 2016/03/31 17:13:34 retention policy shard deletion check commencing
panic: close of closed channel

goroutine 671 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*Engine).Close(0xc20a248820, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/engine.go:147 +0x3e
github.com/influxdb/influxdb/tsdb.(*Shard).close(0xc20b0466e0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/tsdb/shard.go:150 +0x54
github.com/influxdb/influxdb/tsdb.(*Shard).Close(0xc20b0466e0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/tsdb/shard.go:145 +0x89
github.com/influxdb/influxdb/tsdb.(*Store).DeleteShard(0xc208088580, 0x169, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/tsdb/store.go:134 +0xe4
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208117800)
        /tmp/influxdb/src/github.com/influxdb/influxdb/services/retention/service.go:130 +0x8ab
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/influxdb/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b8

goroutine 1 [chan receive, 59 minutes]:
main.(*Main).Run(0xc20802d700, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0x7a1
main.main()
        /tmp/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0xdc

goroutine 6 [syscall, 60 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.3/src/os/signal/signal_unix.go:27 +0x35

goroutine 18 [chan receive, 60 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080e04b0, 0x0, 0x0, 0x0, 0x0)
        /tmp/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:135 +0x80

```

**Comment by e-dard** [comment] 2016-04-01 11:23
@waqark3389 thanks for the report. This is fixed in `0.11`. This looks like a dupe of #5244.

**Closed by e-dard** 2016-04-01 11:23 UTC
