### ISSUE TITLE
Error when installing Influx 1.8 from Debian repo

### ISSUE THREAD

**Issue by lhotamir** [influxdata/influxdb#21365] opened 2021-05-04 05:52 UTC
I am installing Influx 1.8 from https://repos.influxdata.com/debian when building a docker image. Since today I am getting an error after executing following script.
```
...
curl -fsSL https://repos.influxdata.com/influxdb.key | apt-key add -      && echo "deb https://repos.influxdata.com/debian buster stable" | tee /etc/apt/sources.list.d/influxdb.list     && cat /etc/apt/sources.list.d/influxdb.list     && apt-get update && apt-get install influxdb
...
Err:4 https://repos.influxdata.com/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
Reading package lists...
W: GPG error: https://repos.influxdata.com/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
E: The repository 'https://repos.influxdata.com/debian buster InRelease' is not signed.
```

**Comment by piotrekfus91** [comment] 2021-05-04 06:07
Same goes for Ubuntu 20.04:
```
Err:3 https://repos.influxdata.com/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
Reading package lists... Done
W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
E: The repository 'https://repos.influxdata.com/ubuntu focal InRelease' is not signed.
```

**Comment by Tetha** [comment] 2021-05-04 09:03
Hello,

we are seeing similar errors on CentOS8 with telegraf with the influxdb RPM repository:

```
Failed to validate GPG signature for telegraf-1.15.2-1.x86_64
```

**Comment by danieltarff-bbc** [comment] 2021-05-04 11:11
I notice the influxdb.key in https://repos.influxdata.com/ was modified a few hours ago, which probably isn't a coincidence

<img width="450" alt="Screenshot 2021-05-04 at 12 10 33" src="https://user-images.githubusercontent.com/16315095/116995291-cf3dac80-acd1-11eb-9de1-7048667750a4.png">

**Comment by danxmoran** [comment] 2021-05-04 13:05
We're in the process of rotating our GPG keys and re-generating all the signature files. I'll leave this issue open until the process is complete.

**Comment by karthick-rn** [comment] 2021-05-06 16:04
We are facing this issue for the second time. The first was back in December and we had reached out to support@influxdata.com highlighting the download failed due to mismatch in the checksum caused by an updated RPM signature. At the time, fortunately we had the old RPM to compare against the updated RPM to check if any content was modified, and it appeared nothing had changed. Manually comparing the old and new RPM & updating the checksum in our project becomes tedious every time the RPM is re-signed. Also, if we can't rely on the checksum not changing for a previously released version, that's pretty concerning. We'd be curious to know if in the future re-signing the existing RPMs can be avoided which will guarantee the integrity of the package.

**Comment by psteinbachs** [comment] 2021-05-06 18:31
We very much appreciate the reports and comments, and definitely understand the frustration.  We've posted an explanation of what happened at https://community.influxdata.com/t/gpg-key-change-week-of-may-3rd-2021/19772 and are committed to improving our process moving forward.

**Comment by ctubbsii** [comment] 2021-05-06 18:48
@psteinbachs The blog post indicates that the signing key was changed. That's fine, but if I were to make a suggestion, you probably shouldn't re-sign all your RPMs when the signing key changes. That changes their bits, and makes a perfectly fine release artifact signed using an older key look like it has been subsequently compromised. Even reverting back to the old key will not fix the issue, if it is re-signed, because the timestamp when signed the second time will be different from the first and the bits will be different, even with the same key.

If you need to re-sign, I recommend bumping the version or appending a 1-up sequence to the file name (for RPMs, this can be done with the standard RPM naming convention of `[name]-[version]-[release].[arch].rpm` and bumping the `Release:` sequence number in the SPEC file), so the previous release artifact's bits don't change for a given file name, and the same file downloaded at different times will always have the same bits. This is how Fedora tags release artifacts; each one only gets signed once, and any change and re-sign needs to have a version/release bump.

See also: apache/fluo-muchos#381 and apache/fluo-muchos#391

**Comment by beinbliss** [comment] 2023-01-27 14:48
The same thing is happening again.

**Comment by jeffreyssmith2nd** [comment] 2023-01-27 15:23
Please see the blog post detailing our recent GPG key rotation https://www.influxdata.com/blog/linux-package-signing-key-rotation/

**Comment by Bensge** [comment] 2023-02-10 22:58
@jeffreyssmith2nd you should probably update the install instructions on your website as they still use the old key. I just ran into this. Very frustrating when the install instructions don't work

**Comment by ctubbsii** [comment] 2023-02-11 00:06
Honestly, I can't believe InfluxDB still doesn't know how to correctly sign artifacts, and continues to re-sign old release artifacts when keys are rotated, but without bumping the version of the release artifact. This makes their artifacts look like they have been compromised when a particular version's bits change. I would have thought this would be fixed at some point in the past 2 years since it was reported here, but I guess not. It seems the goal is to have all their downloads signed with the current key, but that's not how anybody else on the internet manages old release artifacts, and it's highly suspicious... because users can't easily tell if something changed or it was just re-signed. Honestly, this is really dumb behavior.

**Comment by mephmanx** [comment] 2023-02-26 00:20
This is affecting me too....   ARGH!  I almost have my entire openstack build complete and then find this putzy issue that I now have to figure out a hack for...

**Comment by bnpfeife** [comment] 2023-02-27 21:33
@ctubbsii @mephmanx @beinbliss 

Hello, I rotated the signing keys in our package repositories this time which included re-signing the RPMs. Our initial thought was that re-signing the packages with the new key would signal that "InfluxData trusts these packages." However, I understand your perspective and I think it's the correct one. I wanted to comment to let everyone know that I'm updating our procedure and documentation so that incrementing the package revision/release is part of the key rotation process.

I also would like to apologize for the issues that this has caused.

**Comment by jeffreyssmith2nd** [comment] 2023-02-28 15:07
Closing this as completed as I believe @bnpfeife's explanation sufficiently covers it.

**Closed by jeffreyssmith2nd** 2023-02-28 15:07 UTC

**Comment by ctubbsii** [comment] 2023-03-02 20:30
I'm still not sure re-releasing, even with a revision bump, every time you re-key is a good idea... unless you're going to keep all the old revisions in the repo as well (are you?). The whole point is that users should be able to download a particular release, perhaps cache it, and then later re-download it repeatedly, knowing that nothing has changed. If you make the old one no longer available, then this fails. If you re-sign the binary, this fails. If you change some feature but keep the same version and recompile, this fails. If the artifact is corrupted or compromised, this fails (but this is the only time you actually want it to fail). If you bump the revision, but only the key has changed, then you have a bunch of users upgrading to the new revision, even though they don't need to.

Maybe just stop changing previous releases... use the new key to sign new releases, and leave the old ones alone?

**Comment by bnpfeife** [comment] 2023-03-02 22:24
Below are my personal thoughts, and not necessarily representative of InfluxData:

I believe that there are two scenarios. The first scenario is where the signing key expires and a new one is installed. In that scenario, we could just deprecate the old key and not re-sign the packages. The other scenario is where the signing key is compromised. As mentioned [here](https://www.influxdata.com/blog/linux-package-signing-key-rotation/), the CircleCI data breach is what incited this last key rotation. In this scenario, we will leave the original packages available (and untouched), but also provide a re-signed and package-revision incremented package.

I understand that this will cause some machines running to attempt an upgrade. However, I suspect that's a minor nuisance compared to previous issue of mutating the package bits. If they're not pulling the latest package already, they're likely using a versionlock plugin. In which case, pushing a package-revision isn't likely to cause an upgrade.

**Comment by raleighlittles** [comment] 2023-05-08 07:26
FYI if you're like me and gave up on installing influxDB after this error, but you want to undo your mistake, you can delete `/etc/apt/sources.list.d/influxdata.list`.
