### ISSUE TITLE
Select by day of week

### ISSUE THREAD

**Issue by spuder** [influxdata/influxdb#1154] opened 2014-11-20 16:44 UTC
It would be nice if the query language supported relative dates. 

Example. How many data points have there been during this work week? 

```
SELECT * FROM foo WHERE time > DAYOFWEEK(sunday)
```

or

```
SELECT * FROM foo WHERE time > DAYOFWEEK(1)
```

**Comment by damajor** [comment] 2015-03-17 21:37
>or
>
>' SELECT * FROM foo WHERE time > DAYOFWEEK(1)'

I disagree, just because Sunday is not the first day of the week in every country in the world.

But I support an idea very similar to yours.

`SELECT * FROM foo WHERE time = week(26)`
> Return every records from within the duration of the 26th week of the current year.

This implies regional settings somewhere (to take care of the first day of the week between regions). The server level is too high for that, it may be better at db or series level.

I'm looking forward to see the team include several functions related to dates in the new versions of InfluxDB.

**Comment by eMerzh** [comment] 2015-10-29 22:17
Hi, 

stumble upon a case where i wanted to group by day of week...
having a day of week if definitely a good idea has we try to work with time database :)

it can be super useful in cases like having a graph of values by day of weeks or filter by day of weeks to detect a pattern, ...: 
- [Monday: 12, Thuesday: 11 ....]
- [Monday 05/10/2015,Monday 12/10/2015,.... ]

**Comment by jonseymour** [comment] 2016-04-04 07:59
I recently had a requirement similar to this. I wanted to compare timeseries from different days, aligned by the same time of day. The workaround I ended up with was rebasing the data I wanted to a common base timestamp and then adding the original date as a tag. This then allowed me to visualise the different days in the same graph within grafana.

**Comment by jwilder** [comment] 2016-08-17 20:34
Related #3290

**Comment by rbetts** [comment] 2017-10-27 17:09
Closing as a duplicate of influxdata/influxdb#2071.

**Closed by rbetts** 2017-10-27 17:09 UTC
Labels: area/queries, kind/feature request
