### ISSUE TITLE
2.0.0-alpha19: Mapped variables use the key instead of the mapped value in queries

### ISSUE THREAD

**Issue by ginoledesma** [influxdata/influxdb#15942] opened 2019-11-15 23:01 UTC
__Steps to reproduce:__

1. Create a new variable called `Resolution` of type `map`. For example, using the CSV format:
```
a.10 seconds,"10s"
b.30 seconds,"30s"
```
2. Create a Flux query that references this variable
```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage_user")
  |> filter(fn: (r) => r.cpu == "cpu-total")
  |> map(fn: (r) => ({r with _variable: v.Resolution}))
```
3. View the results using the Raw Data format

__Expected behavior:__
The `_variable` field should display the mapped value (`10s`)

__Actual behavior:__
The `_variable` field shows the key of the variable (`a.10 seconds`)

__Environment info:__

* System info: Linux 4.15.0-1052-aws x86_64
* InfluxDB version: 2.0.0-alpha.19 ce3e2969a 2019-10-30T23:33:54Z

**Comment by ginoledesma** [comment] 2019-12-17 00:26
Bug still present in 2.0.0-alpha20 and 2.0.0-alpha21

**Comment by Asalem1** [comment] 2020-03-05 17:27
Duplicate of #17026 - fixed in this PR:

https://github.com/influxdata/influxdb/pull/17072

**Closed by Asalem1** 2020-03-05 17:27 UTC
Labels: kind/bug, regression
