### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in models.appendField

### ISSUE THREAD

**Issue by kraj** [influxdata/influxdb#9521] opened 2018-03-06 20:42 UTC
__System info:__ [ latest master as of f627a2d48dd98244cfe30a759572e59852dd62ad]

__Steps to reproduce:__

1. Create a workspace on aarch64 machine
2. built influxdb
3. launch influxd

__Expected behavior:__ it should not crash

__Actual behavior:__  a segfault is noticed and daemon exits

Stacktrace

```
2018-03-06T03:29:24.656886Z     info    Finished compacting files       {"log_id": "06fLY_D0000", "engine": "tsm1", "tsm1_strategy": "full", "tsm1_optimize": false, "trace_id": "06fLYhdl000", "op_name": "tsm1_compact_group", "groups": 2, "files": 1, "duration": "13.259ms"}
2018-03-06T03:29:24.656953Z     info    TSM compaction (end)    {"log_id": "06fLY_D0000", "engine": "tsm1", "tsm1_strategy": "full", "tsm1_optimize":
false, "trace_id": "06fLYhdl000", "op_name": "tsm1_compact_group", "op_event": "end", "op_elapsed": "13.291ms"}




panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x7f836f8aa4]

goroutine 59 [running]:
github.com/influxdata/influxdb/models.appendField(0x0, 0x0, 0x0, 0x5567f8ec5c, 0x5, 0x7f83edf5a0, 0x44205d2060, 0xed2300224, 0x7f84447dc0, 0x4420480640)
        /mnt/a/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:2268 +0x4c
github.com/influxdata/influxdb/models.Fields.MarshalBinary(0x442013e150, 0x7, 0x442013e510, 0x1)
        /mnt/a/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:2261 +0x1f4
github.com/influxdata/influxdb/models.NewPoint(0x5567f8f44d, 0x7, 0x442013e510, 0x1, 0x1, 0x442013e150, 0x0, 0xed2300224, 0x7f84447dc0, 0x0, ...)
        /mnt/a/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:1293 +0x90
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0x442001a000)
        /mnt/a/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/monitor/service.go:450 +0x3c4
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
        /mnt/a/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/monitor/service.go:126 +0x2e4
```

**Comment by e-dard** [comment] 2018-03-07 09:29
Hi,

Can you elaborate further on the steps you took? Also, are you using data directories that have existing data in them from previous versions?

Could you post your config and let us know which index you’re using?

**Comment by kraj** [comment] 2018-03-07 13:32
there is no existing data. This is a new install. and there is no config either. Just binary is run

**Comment by e-dard** [comment] 2018-03-07 13:53
@kraj can you please expand on `Create a workspace on aarch64 machine` and also explain how you launched the server.

The logs you're showing indicate that the server was doing a compaction, which means there must be some data in the database. Did you write data to the database before it panicked?

Finally, could you use the final `1.5.0` release and confirm that causes the same issue? Is this reproducible each time?

**Comment by kraj** [comment] 2018-03-07 17:14
@e-dard 

I built 1.5.0 this morning, I am using odroid-c2 which is a aarch64 based SBC
I cross compile the full rootfs including influxdb, Another point is its using go 1.10.0 but there are
go 1.9 same issue.

```

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2018-03-07T16:59:58.074530Z     info    InfluxDB starting       {"log_id": "06hMKUzW000", "version": "unknown", "branch": "unknown", "commit": "unknown"}
2018-03-07T16:59:58.074641Z     info    Go runtime      {"log_id": "06hMKUzW000", "version": "go1.10", "maxprocs": 4}
2018-03-07T16:59:58.207758Z     info    Using data dir  {"log_id": "06hMKUzW000", "service": "store", "path": "/home/root/.influxdb/data"}
2018-03-07T16:59:58.208115Z     info    Open store (start)      {"log_id": "06hMKUzW000", "service": "store", "trace_id": "06hMKVW0000", "op_name": "tsdb_open", "op_event": "start"}
2018-03-07T16:59:58.208312Z     info    Open store (end)        {"log_id": "06hMKUzW000", "service": "store", "trace_id": "06hMKVW0000", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.208ms"}
2018-03-07T16:59:58.208450Z     info    Opened service  {"log_id": "06hMKUzW000", "service": "subscriber"}
2018-03-07T16:59:58.208640Z     info    Starting monitor service        {"log_id": "06hMKUzW000", "service": "monitor"}
2018-03-07T16:59:58.208690Z     info    Registered diagnostics client   {"log_id": "06hMKUzW000", "service": "monitor", "name": "build"}
2018-03-07T16:59:58.208729Z     info    Registered diagnostics client   {"log_id": "06hMKUzW000", "service": "monitor", "name": "runtime"}
2018-03-07T16:59:58.208764Z     info    Registered diagnostics client   {"log_id": "06hMKUzW000", "service": "monitor", "name": "network"}
2018-03-07T16:59:58.208806Z     info    Registered diagnostics client   {"log_id": "06hMKUzW000", "service": "monitor", "name": "system"}
2018-03-07T16:59:58.208979Z     info    Starting precreation service    {"log_id": "06hMKUzW000", "service": "shard-precreation", "check_interval": "10m", "advance_period": "30m"}
2018-03-07T16:59:58.209024Z     info    Starting snapshot service       {"log_id": "06hMKUzW000", "service": "snapshot"}
2018-03-07T16:59:58.209057Z     info    Starting continuous query service      {"log_id": "06hMKUzW000", "service": "continuous_querier"}
2018-03-07T16:59:58.209106Z     info    Starting HTTP service   {"log_id": "06hMKUzW000", "service": "httpd", "authentication": false}
2018-03-07T16:59:58.209145Z     info    opened HTTP access log  {"log_id": "06hMKUzW000", "service": "httpd", "path": "stderr"}
2018-03-07T16:59:58.209766Z     info    Storing statistics      {"log_id": "06hMKUzW000", "service": "monitor", "db_instance": "_internal", "db_rp": "monitor", "interval": "10s"}
2018-03-07T16:59:58.215424Z     info    Listening on HTTP       {"log_id": "06hMKUzW000", "service": "httpd", "addr": "0.0.0.0:8086", "https": false}
2018-03-07T16:59:58.215609Z     info    Starting retention policy enforcement service   {"log_id": "06hMKUzW000", "service": "retention", "check_interval": "30m"}
2018-03-07T16:59:58.216117Z     info    Sending usage statistics to usage.influxdata.com        {"log_id": "06hMKUzW000"}
2018-03-07T16:59:58.216298Z     info    Listening for signals   {"log_id": "06hMKUzW000"}
panic: runtime error: makeslice: len out of range

goroutine 24 [running]:
strings.(*byteStringReplacer).Replace(0x442043d800, 0x5563de1918, 0x9, 0x19, 0x20)
        /usr/lib/go/src/strings/replace.go:475 +0x90
strings.(*Replacer).Replace(0x4420011b50, 0x5563de1918, 0x9, 0x20, 0x44200900c0)
        /usr/lib/go/src/strings/replace.go:70 +0x3c
github.com/influxdata/influxdb/pkg/escape.String(0x5563de1918, 0x9, 0x20, 0x1c93)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/pkg/escape/strings.go:20 +0x38
github.com/influxdata/influxdb/models.appendField(0x44200900c0, 0x1b, 0x20, 0x5563de1918, 0x9, 0x7fa280e5a0, 0x4420013600, 0x44200900c0, 0x1a, 0x20)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:2268 +0x30
github.com/influxdata/influxdb/models.Fields.MarshalBinary(0x44204a3ad0, 0x7, 0x44204a3c50, 0x1)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:2261 +0x1f4
github.com/influxdata/influxdb/models.NewPoint(0x5563de146d, 0x7, 0x44204a3c50, 0x1, 0x1, 0x44204a3ad0, 0x0, 0xed232119a, 0x7fa2d76dc0, 0x0, ...)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/models/points.go:1293 +0x90
github.com/influxdata/influxdb/monitor.(*Monitor).storeStatistics(0x442001a000)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/monitor/service.go:450 +0x3c4
created by github.com/influxdata/influxdb/monitor.(*Monitor).Open
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/monitor/service.go:126 +0x2e4
```

**Comment by mark-rushakoff** [comment] 2018-03-07 17:23
@kraj if you build with `-race`, are there any data races detected when you run influxd?

**Comment by e-dard** [comment] 2018-03-07 17:35
@kraj can you try running `influxd` with the monitoring service disabled? You can do that either by changing:

```toml
[monitor]
  store-enabled = false
```

or you can do it via env vars `$ INFLUXDB_MONITOR_STORE_ENABLED=false influxd`.

If that works successfully then my hunch is that it could be something to do with a tag/field being written to the `_internal` database.

Could  you tell us what values you have for:

 - your `hostname`;
 - your data directory path; and
 - your wal directory path.

**Comment by kraj** [comment] 2018-03-07 18:16
@e-dard  with

```
INFLUXDB_MONITOR_STORE_ENABLED=false influxd
```

crash is not seen.

**Comment by e-dard** [comment] 2018-03-07 18:58
@kraj can you provide the values I listed above?

**Comment by kraj** [comment] 2018-03-07 19:43
@e-dard 

hostname = odroid-c2-hardkernel
2018-03-07T18:05:03.528581Z     info    Using data dir  {"log_id": "06hQ2rGW000", "service": "store", "path": "/home/root/.influxdb/data"}

I dont set wal dir explicitly, so default is what it is using.

**Comment by kraj** [comment] 2018-03-07 20:23
Now I tried to open CLI shell and create a database and it ends up with another error

```
root@odroid-c2-hardkernel:~# influx
Connected to http://localhost:8086 version unknown
InfluxDB shell version: unknown
> create database zonit
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
regexp.progMachine(0x4420393110, 0x0, 0x0)
        /usr/lib/go/src/regexp/exec.go:75 +0x78
regexp.(*Regexp).get(0x44203acd20, 0x44203b6240)
        /usr/lib/go/src/regexp/regexp.go:219 +0x9c
regexp.(*Regexp).doExecute(0x44203acd20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44203240c0, 0x15, 0x0, 0x44203b70e0, ...)
        /usr/lib/go/src/regexp/exec.go:419 +0x20
regexp.(*Regexp).allMatches(0x44203acd20, 0x44203240c0, 0x15, 0x0, 0x0, 0x0, 0x16, 0x44203077c8)
        /usr/lib/go/src/regexp/regexp.go:683 +0xb8
regexp.(*Regexp).FindAllStringSubmatchIndex(0x44203acd20, 0x44203240c0, 0x15, 0x16, 0x0, 0x0, 0x0)
        /usr/lib/go/src/regexp/regexp.go:1127 +0xac
github.com/influxdata/influxdb/vendor/github.com/influxdata/influxql.Sanitize(0x44203240c0, 0x15, 0x4, 0x0)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/influxql/sanitize.go:35 +0x80
github.com/influxdata/influxdb/cmd/influx/cli.(*CommandLine).mainLoop(0x442044a000, 0x1a, 0x0)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/cmd/influx/cli/cli.go:246 +0x198
github.com/influxdata/influxdb/cmd/influx/cli.(*CommandLine).Run(0x442044a000, 0x0, 0x0)
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/cmd/influx/cli/cli.go:223 +0x534
main.main()
        /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/github.com-influxdata-influxdb/1.0-r0/build/src/github.com/influxdata/influxdb/cmd/influx/main.go:124 +0x728
```

**Comment by kraj** [comment] 2018-03-07 22:25
```

[data]
  dir = "/home/root/.influxdb/data"
  index-version = "inmem"
  wal-dir = "/home/root/.influxdb/wal"
  wal-fsync-delay = "0s"
  query-log-enabled = true
  cache-max-memory-size = 1073741824
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "10m0s"
  compact-full-write-cold-duration = "4h0m0s"
  max-series-per-database = 1000000
  max-values-per-tag = 100000
  max-concurrent-compactions = 0
  trace-logging-enabled = false
```

**Comment by mark-rushakoff** [comment] 2018-03-07 22:36
@kraj how are you building influxdb? Based on your comment here: https://github.com/golang/go/issues/23889#issuecomment-370121149 
it looks like you might be running a custom build of Go. Are you using a custom build of Go, or an official release of Go?

Note that our 1.5 release was built and tested with Go 1.9.

And you still haven't answered on whether you can run with the race detector enabled.

**Comment by e-dard** [comment] 2018-03-08 08:11
Closing as this was on an unsupported version of Go (although it was implied earlier on that the problems were occurring on 1.9) 

Internal testing using the release binary (built with 1.9) does not show this problem.

**Closed by e-dard** 2018-03-08 08:11 UTC
Labels: need more info, panic

**Comment by nefethael** [comment] 2019-02-18 08:26
@e-dard  @kraj Hi, 

I have same issue with go1.11.1  and influxdb v1.7.4, and `INFLUXDB_MONITOR_STORE_ENABLED=false influxd` do solve it as well. 

I didn't try any other GO/influxdb combinations yet.
