### ISSUE TITLE
Add old versions to managed repos.influxdata.com

### ISSUE THREAD

**Issue by Lswith** [influxdata/influxdb#6209] opened 2016-04-05 01:57 UTC
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ Add old versions of influxdata packages to the repos.influxdata.com. This allows people to slowly upgrade to the latest version.

__Current behavior:__ The latest version is the only available package in the repos.influxdata.com repository.

__Desired behavior:__ Version 0.8, 0.9 and 0.10 should be added as well.

__Use case:__ Currently influxdb has breaking changes in the configuration file (influxdb.conf). There are also breaking changes in the api and other parts of the database. By allow users to install old versions from your repository, they can choose when they would like to upgrade to the latest version.

**Comment by rossmcdonald** [comment] 2016-04-05 13:49
This is a duplicate of https://github.com/influxdata/influxdb/issues/5913

The yum repo does contain the older versions, but the apt repo currently does not. We are migrating to a tool that will allow us to keep historical versions with apt, so we will update #5913 once done. We will add the latest stable release of each branch after the 0.8 branch (so `0.9.6`, `0.10.3`, and `0.11.1`), but, since 0.8 has been deprecated for some time now, 0.8 will not be added.

**Closed by rossmcdonald** 2016-04-05 13:49 UTC
Labels: category/packaging
