### ISSUE TITLE
High memory usage after upgrade to 1.5.0 and TSM to TSI migration

### ISSUE THREAD

**Issue by juris** [influxdata/influxdb#9817] opened 2018-05-08 19:30 UTC
### Bug report
__System info:__
Influxdb 1.5.2 (had the same issue with 1.5.0) running inside Docker container on CoreOS.
Docker version 1.12.6
Linux kernel version 4.14.19-coreos
4 databases (8 shards each), takes 16.5 GB on disk.
__Steps to reproduce:__

1. Launch Influxdb 1.4.2
2. Generate some data
3. Migrate to 1.5.0

__Expected behavior:__
Influxdb should consume about 1.2 GB of RAM, as it was with 1.4.2 version 
__Actual behavior:__
Influxdb consumes 4GB

**Comment by dgnorton** [comment] 2018-05-09 13:16
@juris What is the output of `SHOW SERIES CARDINALITY`?

**Comment by juris** [comment] 2018-05-09 13:38
```
> SHOW SERIES CARDINALITY on telegraf
cardinality estimation
----------------------
93828
> SHOW SERIES CARDINALITY on system
cardinality estimation
----------------------
78079
> SHOW SERIES CARDINALITY on _internal
cardinality estimation
----------------------
182
> SHOW SERIES CARDINALITY on f3
cardinality estimation
----------------------
461
```

**Comment by dgnorton** [comment] 2018-05-09 14:26
@juris does it use the same amount of memory if switched back to `inmem` index?

**Comment by juris** [comment] 2018-05-10 08:18
Although I followed migration procedure, it seems that databases are still on TSM. Here's what I get in logs every time before Influxdb gets killed by OOM:
```
ts=2018-05-10T08:13:25.923709Z lvl=info msg="Cache snapshot (start)" log_id=07xFn92G000 engine=tsm1 trace_id=07zHdG8l000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-05-10T08:13:25.923747Z lvl=info msg="Snapshot for path written" log_id=07xFn92G000 engine=tsm1 trace_id=07zHdG8l000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/f3/default/224 duration=0.049ms
ts=2018-05-10T08:13:25.923764Z lvl=info msg="Cache snapshot (end)" log_id=07xFn92G000 engine=tsm1 trace_id=07zHdG8l000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=0.061ms
ts=2018-05-10T08:13:25.923774Z lvl=info msg="Error writing snapshot" log_id=07xFn92G000 engine=tsm1 error="error opening new segment file for wal (1): write /var/lib/influxdb/wal/f3/default/224/_00127.wal: cannot allocate memory"
```

**Comment by nkondratyk** [comment] 2018-05-15 11:37
Hi

The same problem from my side. I have migrated to tsi from tsm but new shards still are creating as tsm

**Comment by e-dard** [comment] 2018-05-30 18:22
@juris `TSI` does a lot more mmaping than `inmem` does. Further, in `1.5` we introduced the Series File, which works on both the `TSI` and `inmem` indexes. The Series File also does a lot of mmaping.

The kernel will page in to RAM as much as needed for for the TSI index and Series File. It will only release those pages when other things need to use the RAM. Just because 1.5 says it's using 4GB RAM doesn't mean it actually needs that, and it doesn't mean it can't give up that memory to other processes if they request more memory.

**Comment by lpic10** [comment] 2018-05-31 07:56
@e-dard I'm following this issue because I have issues with memory too since 1.5.0 and I cannot migrate from 1.4.3 in my env.

My VM has 16 GB of RAM on a RHEL 7 and it is enough to run 1.3.x/1.4.x with TSI, but it is not enough for 1.5.x. This InfluxDB is used mainly to monitor about 20 nodes running kubernetes/docker.

I tried several approaches to migrate, changing shard size, reducing retention, etc, but I faced several issues:

1. Startup time skyrocketed from around 1-2 minutes to 5-10 minutes (or more sometimes). In one of the attempts (using less, bigger shards) it took about 2 hours to load.
2. Much higher memory usage, causing OOM quite often, sometimes before it can finish the startup
3. Much higher I/O usage, so when it finishes the startup (no OOM), no points are ingested due to timeout and no query finish

I'm not 100% sure that 3 occurs because of 2, definitely there is a memory pressure issue... but it seems influxDB 1.5 is really doing much more I/O in this high cardinality scenario.

Maybe there is something specific about this env (the VM itself, OS, slow I/O, etc) that causes this behavior, maybe it is version 1.5 that really requires more resources and this env is already at the edge... but the difference for me is so dramatic that there must be something else.

It is been some time that I'm waiting for some improvement/bug fix related to I/O or memory usage on TSI that motivates me to try to migrate again.

Let me know if I can help in some way, maybe a dump of my DB from 1.4.3 or some additional info.

```
SHOW SERIES CARDINALITY on kubernetes
cardinality estimation
1859698

SHOW SERIES CARDINALITY on telegraf
cardinality estimation
120

SHOW SERIES CARDINALITY on services
cardinality estimation
259092

SHOW SERIES CARDINALITY on _internal
cardinality estimation
1257 

 du -msc /var/lib/influxdb/*
24036   /var/lib/influxdb/data
1       /var/lib/influxdb/meta
127     /var/lib/influxdb/wal
24163   total

```

**Comment by e-dard** [comment] 2018-05-31 09:55
@lpic10 do you have a high write or query load on your instance? A box with 16GB RAM should be plenty to handle the ~2M series you have in the index.

Do you have hundreds of fields??

Some observations:

  - Startup time with TSI using 1.5 should be very quick. Well under a minute, and usually on the order of seconds. If it's taking minutes then something is misconfigured or wrong.
  - 1.5 / TSI shouldn't need much memory or IO to startup.

Some questions:

  * Are you 100 % sure that you correctly converted all your shards to use the TSI index when you upgraded to 1.5. If you were previously using the TSI preview in 1.3/1.4 you will still need to delete all your TSI index directories and run the `buildtsi` tooling.

 * How many shards do you have on your system?

Could you please send the result of `SHOW SHARDS`? Or it that's not possible then a `tree` output starting at the `~/.influxdb/data` directory?

My hunch is that you have shards that have not been correctly converted from `inmem` to TSI, and that they're being scanned/read during startup. We have a feature in the upcoming 1.6 release (it's currently in `master`) that would identify and highlight that for you during startup: https://github.com/influxdata/influxdb/pull/9777

**Comment by lpic10** [comment] 2018-05-31 10:49
Trying to answer your questions:

The load is mainly write, there are not so many users that check the dashboards. 
If I calculated correctly, the ingestion is about 7k points/s .

Currently there are ~130 shards, ~350k series

I performed several attempts at migrating, and for I've used the buildtsi in (most of?) them.

Maybe this will help:
[show_stats.txt](https://github.com/influxdata/influxdb/files/2057847/show_stats.txt)
[tree.txt](https://github.com/influxdata/influxdb/files/2057848/tree.txt)
[show_shards.txt](https://github.com/influxdata/influxdb/files/2057849/show_shards.txt)

**Comment by e-dard** [comment] 2018-05-31 11:09
@lpic10 that's useful thanks.

Couple of things:

> Currently there are ~130 shards, ~350k series

You have over 1.8M series in the index for the `kubernetes` database.

In terms of the number of fields you haves stored (fields are not indexed, so they're not considered in the cardinality estimations).

```
name: shard
tags: database=services, engine=tsm1, id=6919, path=/var/lib/influxdb/data/services/autogen/6919, retentionPolicy=autogen, walPath=/var/lib/influxdb/wal/services/autogen/6919
diskBytes fieldsCreate seriesCreate writeBytes writePointsDropped writePointsErr writePointsOk writeReq writeReqErr writeReqOk
--------- ------------ ------------ ---------- ------------------ -------------- ------------- -------- ----------- ----------
25695959  22281        43454        0          0                  0              15471544      15573    0           15573
```

It looks like shard `6919` in database `services` has a lot of fields being created. 22,000 fields is a lot. Are you aware of why so many are needed? Are you actually measuring and analysing 22,000 different metrics?

Here is another one in the Kubernetes database:

```
name: shard
tags: database=kubernetes, engine=tsm1, id=6920, path=/var/lib/influxdb/data/kubernetes/autogen/6920, retentionPolicy=autogen, walPath=/var/lib/influxdb/wal/kubernetes/autogen/6920
diskBytes fieldsCreate seriesCreate writeBytes writePointsDropped writePointsErr writePointsOk writeReq writeReqErr writeReqOk
--------- ------------ ------------ ---------- ------------------ -------------- ------------- -------- ----------- ----------
300319558 16884        203793       0          0                  0              43172635      43131    0           43131
```

Given the Kubernetes database has ~1.8M series in the index, when you factor in that there are ~16,000 fields spread amongst those series, the TSM cardinality (the cardinality of everything we store and is queryable on disk) could be very high.


You have some anomalies on your filesystem:

  - none of the shards in the `chronograf` database have been converted to TSI.
  - `/data/index` shouldn't exist. It looks like a TSI index was attempted to be built directly on the `/data` directory.
  - Some of the older `_internal` shards need to be converted to TSI. Shards: 4992, 5000, 5014, 5021, 5028, 5035 and 5042.
  - The `services` database is missing a Series File. This is concerning. Possible the building of this could be the reason startup is taking so long and is so slow.

What state was the database in when you sent me the files? I assume it had booted because you ran `SHOW SHARDS` and `SHOW STATS`?

Can you send me the startup logs?

**Comment by lpic10** [comment] 2018-05-31 12:58
Sorry, I think I wasn't clear. I didn't succeed to migrate to 1.5.x and had to rollback.
So all the information you got is from a 1.4.3 release.

There are probably strange things in the folders structure due to migration from pre/alpha TSI releases up to the attempt to run 1.5.x and even a 1.6 nightly.

My last migration attempt was 2-3 weeks ago (version 1.5.2 and nightly build)

> You have over 1.8M series in the index for the kubernetes database.

Yep, that's correct, that info came from an InfluxDB grafana dashboard that does this: 
`SELECT mean("numSeries") FROM "database" WHERE $timeFilter GROUP BY time($interval) fill(null)`
which looking now is obviously wrong.

> It looks like shard 6919 in database services has a lot of fields being created. 22,000 fields is a lot. Are you aware of why so many are needed? Are you actually measuring and analysing 22,000 different metrics?

Certainly there is something wrong. Is there an easy way to find which measurement has so many fields? I tried browsing the measurements in chronograf, but I didn't find anything abnormal

> You have some anomalies on your filesystem:
>    none of the shards in the chronograf database have been converted to TSI.

Yes, I don't think I migrated all databases. The chronograf db is rather small 

>   /data/index shouldn't exist. It looks like a TSI index was attempted to be built directly on the /data directory.

Probably reminiscent from some bug/mistake in some of the TSI migration. I guess this is harmless... 

>   Some of the older _internal shards need to be converted to TSI. Shards: 4992, 5000, 5014, 5021, 5028, 5035 and 5042.

Probably the same, do you think this could cause issue in 1.5.x?

>   The services database is missing a Series File. This is concerning. Possible the building of this could be the reason startup is taking so long and is so slow.

This services database is new (the data on it was stored previously on kubernetes database too). This was created after latest migration attempt about 2-3 weeks ago. So the TSI folder structure is "1.4.x" version only.

> What state was the database in when you sent me the files? I assume it had booted because you ran SHOW SHARDS and SHOW STATS?

So, as I'm running 1.4.3, it was last booted few days ago:
```
name: system
PID  currentTime                    started                      uptime
---  -----------                    -------                      ------
1966 2018-05-31T12:43:25.183982794Z 2018-05-23T02:25:11.2699629Z 202h18m13.914020628s
```

Hope things are a bit more clear now. Do you still want the logs of this boot?

**Comment by lpic10** [comment] 2018-05-31 13:32
BTW, by browsing the measurements in chronograf I got InfluxDB OOM killed... 
```
name: system
PID  currentTime                    started                        uptime
---  -----------                    -------                        ------
4605 2018-05-31T13:31:51.784397586Z 2018-05-31T13:15:05.807223862Z 16m45.977174085s
```

**Comment by e-dard** [comment] 2018-05-31 13:44
@lpic10 if you want to continue to investigate this issue, and get onto 1.5. I think you should do the following process, and provide me with the output/details:

  1) Shutdown influxdb.
  2) Remove all `index` directories recursively under your `data` directory. 
  3) Remove all `_series` directories recursively under your `data` directory.
  3) Follow the upgrade procedure [here](https://docs.influxdata.com/influxdb/v1.5/administration/upgrading/#upgrading-from-1-3-1-4-no-tsi-preview-to-1-5-x-tsi-enabled). Specifically:
  a) set the index to `tsi1` in the config file, or using the env var
  b) Run the buildtsi tool: `influx_inspect buildtsi -datadir ~/.influxdb/data -waldir ~/.influxdb/wal`
  4) Startup the new version of influxdb.

Please provide me with the logs when your start influxdb running 1.5 with TSI enabled.

**Comment by e-dard** [comment] 2018-05-31 13:46
@lpic10 there were some useful fixes in `1.5.2` so please use that version.

**Comment by lpic10** [comment] 2018-06-01 08:54
I did a test here copying this data to a new VM with 20 GB RAM, following the procedure you described.

Note there is a difference in data stored as there is a ~12 hour difference between the copy and this test, actually there is a bit more data in 1.4.3 than in 1.5.3 when this was executed.

Some findings after migration procedure done:

- startup with enough memory was comparable to previous version, around 1-2 minutes
- memory usage (RSS) after initial startup is considerably higher on 1.5.3 than 1.4.3 

```
ps xav output:

1.4.3 after startup 
PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND
90678 ?        Ssl    2:17   1417  7246 38798937 13451420 82.6 /usr/bin/influxd -config /etc/influxdb/influxdb.conf/influxdb.conf

1.5.3 after startup
PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND
14600 ?        Ssl    7:34   3645  8275 34324252 18196008 89.2 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
``` 

This need of more than 16GB may explain why previous attempts failed, or maybe it was just some TSI migration issue on my side. 

Startup log:
[influxdb_start_1.5.3.txt](https://github.com/influxdata/influxdb/files/2061986/influxdb_start_1.5.3.txt)

Show stats after startup, 1.4.3 vs 1.5.3: 

[show_stats_1.4.3.txt](https://github.com/influxdata/influxdb/files/2061706/show_stats_1.4.3.txt)
[show_stats_1.5.3.txt](https://github.com/influxdata/influxdb/files/2061707/show_stats_1.5.3.txt)

@e-dard not sure what could be your findings on that. It seems InfluxDB >= 1.5 requires more memory than 1.3/1.4 in some scenarios with TSI and if there is no reason to believe there is some bug in that regard, it may be needed to be better understood & possibly documented in the upgrade procedure. 

If you want some additional info, let me know.

**Comment by e-dard** [comment] 2018-06-01 11:34
> startup with enough memory was comparable to previous version, around 1-2 minutes 

What disks do you have and what IOPS available? Do you have a very slow CPU? Seems like all that time was spent scanning your TSM files. 

> memory usage (RSS) after initial startup is considerably higher on 1.5.3 than 1.4.3

RSS can be misleading. It's a value that tells you how much memory the OS has handed over to the program. It does not mean that the program is actively using all that memory. In this case (looking at your `show_stats` outputs), 1.4.3 is actively using `HeapInUse = 9309577216` and 1.5.3 is actively using `HeapInUse = 9969082368`.

So 1.5.3 both are under 10GB, and 1.5.3 is only a few hundred megabytes more.

The OS can reclaim memory it's assigned to InfluxDB when it needs it. 

It seems like you're up and running on 1.5.3 with TSI. I think I can close out this issue now?

**Comment by lpic10** [comment] 2018-06-01 12:59
> What disks do you have and what IOPS available? Do you have a very slow CPU? Seems like all that time was spent scanning your TSM files.

These are internal VMs provided by our IT team and I don't have much visibility on the hardware layer, what I can tell is that performance is far from ideal in terms of CPU and I/O.

> It seems like you're up and running on 1.5.3 with TSI. I think I can close out this issue now?

I'm not the original reporter of this ticket, I just hijacked it :) 
Feel free to close if you think there is nothing here.

In my particular case I will setup temporarily this new VM as relay of the prod one and after few days (retention period) when both should contain the same data, I can evaluate better if it is ok to migrate to the new version in terms of resources consumption vs performance.

**Comment by philippreston** [comment] 2018-07-04 14:05
Hey @e-dard 

I am seeing something similar here with continual high memory growth.  

So I was running 1.4 on the TSM index and was getting daily bounces off the influx server because of OOM.  So I was testing migrating to 1.5.4 + the TSI as from reading this could be a source of my memory growth.  This did not seem to resolve my problem, and I see the same pattern with TSI.  I rebuilt my TSI indexes this morning - and I can see the growth is continuing as before.  

So this is the memory growth over the last 7 days.  Note that I moved to TSI at the start of this week

<img width="1981" alt="screen shot 2018-07-04 at 14 50 55" src="https://user-images.githubusercontent.com/4885250/42280820-b8c721e2-7f99-11e8-8d6a-a980cae4bd6e.png">

I am not sure there is something else at play here - as I don't have a high series cardinality, and I am running on a 4-core VM with 16G of RAM:

```
~/Downloads » for db in $(influx --host ch2-tickstack  -execute "SHOW DATABASES" | tail -n 4); do echo "\n$db"; influx --host ch2-tickstack -database $db -execute "SHOW SERIES CARDINALITY"; done

_internal
cardinality estimation
----------------------
2599

telegraf
cardinality estimation
----------------------
22404

playground
cardinality estimation
----------------------
764

chronograf
cardinality estimation
----------------------
6
``` 

From what I have read with these numbers, and 16G RAM, I should have been ok with the in-memory index... Not sure what I have missed.  This is all using the influx docker image.

Thanks

Phil

**Comment by philippreston** [comment] 2018-07-09 16:00
This appears to actually be happening during compacting.  So I can see this in the logging before the crash:

```
ts=2018-07-09T13:52:01.305815Z lvl=info msg="Cache snapshot (start)" log_id=09AmobhW000 engine=tsm1 trace_id=09BprT6G000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-07-09T13:52:01.619601Z lvl=info msg="Snapshot for path written" log_id=09AmobhW000 engine=tsm1 trace_id=09BprT6G000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/telegraf/default/1071 duration=313.801ms
ts=2018-07-09T13:52:01.619674Z lvl=info msg="Cache snapshot (end)" log_id=09AmobhW000 engine=tsm1 trace_id=09BprT6G000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=313.872ms
ts=2018-07-09T13:52:02.305993Z lvl=info msg="TSM compaction (start)" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group op_event=start
ts=2018-07-09T13:52:02.306034Z lvl=info msg="Beginning compaction" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_files=8
ts=2018-07-09T13:52:02.306040Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000409-000000001.tsm
ts=2018-07-09T13:52:02.306044Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000410-000000001.tsm
ts=2018-07-09T13:52:02.306048Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000411-000000001.tsm
ts=2018-07-09T13:52:02.306052Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000412-000000001.tsm
ts=2018-07-09T13:52:02.306056Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=4 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000413-000000001.tsm
ts=2018-07-09T13:52:02.306059Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=5 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000414-000000001.tsm
ts=2018-07-09T13:52:02.306063Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=6 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000415-000000001.tsm
ts=2018-07-09T13:52:02.306066Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=7 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000416-000000001.tsm
ts=2018-07-09T13:52:03.802365Z lvl=info msg="Compacted file" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000416-000000002.tsm.tmp
ts=2018-07-09T13:52:03.802423Z lvl=info msg="Finished compacting files" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group groups=8 files=1 duration=1496.442ms
ts=2018-07-09T13:52:03.802443Z lvl=info msg="TSM compaction (end)" log_id=09AmobhW000 engine=tsm1 tsm1_level=1 tsm1_strategy=level trace_id=09BprX0G000 op_name=tsm1_compact_group op_event=end op_elapsed=1496.456ms
ts=2018-07-09T13:52:04.305895Z lvl=info msg="TSM compaction (start)" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group op_event=start
ts=2018-07-09T13:52:04.305933Z lvl=info msg="Beginning compaction" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_files=4
ts=2018-07-09T13:52:04.305939Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000392-000000002.tsm
ts=2018-07-09T13:52:04.305943Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000400-000000002.tsm
ts=2018-07-09T13:52:04.305947Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_index=2 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000408-000000002.tsm
ts=2018-07-09T13:52:04.305951Z lvl=info msg="Compacting file" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_index=3 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000416-000000002.tsm
ts=2018-07-09T13:52:09.098345Z lvl=info msg="Compacted file" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/telegraf/default/1071/000000416-000000003.tsm.tmp
ts=2018-07-09T13:52:09.098397Z lvl=info msg="Finished compacting files" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group groups=4 files=1 duration=4792.512ms
ts=2018-07-09T13:52:09.098417Z lvl=info msg="TSM compaction (end)" log_id=09AmobhW000 engine=tsm1 tsm1_level=2 tsm1_strategy=level trace_id=09BprdpG000 op_name=tsm1_compact_group op_event=end op_elapsed=4792.526ms
ts=2018-07-09T13:52:23.920360Z lvl=info msg="InfluxDB starting" log_id=09BpsqS0000 version=1.5.4 branch=1.5 commit=4e4e00bc5ab85a3ff5e988c91020cf0399a87026
ts=2018-07-09T13:52:23.920388Z lvl=info msg="Go runtime" log_id=09BpsqS0000 version=go1.9.2 maxprocs=4
```

So you can see the compacting log lines before we hit startup again, and in dmesg I can see:

```
[Mon Jul  9 13:52:21 2018] influxd invoked oom-killer: gfp_mask=0x24000c0, order=0, oom_score_adj=0
[Mon Jul  9 13:52:21 2018] influxd cpuset=2580513cb69be428615ad104c9b9174bea29d7b99247642246a854ab43756211 mems_allowed=0
[Mon Jul  9 13:52:21 2018] CPU: 1 PID: 31021 Comm: influxd Not tainted 4.4.0-77-generic #98-Ubuntu
[Mon Jul  9 13:52:21 2018] [30961]     0 30961  7260849  3066363    7572      29   467500             0 influxd
[Mon Jul  9 13:52:21 2018] Memory cgroup out of memory: Kill process 30961 (influxd) score 971 or sacrifice child
[Mon Jul  9 13:52:21 2018] Killed process 30961 (influxd) total-vm:29043396kB, anon-rss:12244956kB, file-rss:20496kB
```

This could be more in line with https://github.com/influxdata/influxdb/issues/9938.

Any thoughts?

Phil

**Comment by e-dard** [comment] 2018-07-09 18:01
Hi Phil, memory usage for compactions is often determined by the amount of data written that needs to be compacted, not necessarily the size of the index. I'm going to close this as we've detoured away from the original issue, but if you think there is a regression or bug please feel free to open a new issue.

**Closed by e-dard** 2018-07-09 18:01 UTC
Labels: area/tsi
