### ISSUE TITLE
Rapid creation and drop of database leading to 404 database not found error.

### ISSUE THREAD

**Issue by goyalr41** [influxdata/influxdb#5547] opened 2016-02-05 14:17 UTC
During integration tests I am rapidly creating and dropping database plus also writing some points in it. With fresh install/restart of influxdb it works completely fine. But after some time it starts failing intermittently giving 404 error code which means database not found. But it still writes the data to the database. This is for the latest version 0.10.0. Any solutions for this?

I was also facing the similar kind of issue in 0.9.4 version and that eventually corrupted other databases (which were not used for integration tests) writes as well making their writes failing intermittently. Here's the issue in 0.9.4. This still writes to the database but sends the error code.

```
curl -i -XPOST 'http://aoelinfluxpoc001:8086/write?db=testdb' --data-binary 'cpuloadshort1,host=server01 value=0.65'

HTTP/1.1 204 No Content
Request-Id: b05b8497-cc12-11e5-bd2d-000000000000
X-Influxdb-Version: 0.9.4.2
Date: Fri, 05 Feb 2016 14:13:54 GMT

curl -i -XPOST 'http://aoelinfluxpoc001:8086/write?db=testdb' --data-binary 'cpuloadshort1,host=server01 value=0.65'

HTTP/1.1 500 Internal Server Error
Request-Id: b32f307b-cc12-11e5-bd2e-000000000000
X-Influxdb-Version: 0.9.4.2
Date: Fri, 05 Feb 2016 14:14:04 GMT
Content-Length: 8
Content-Type: text/plain; charset=utf-8

timeout
 
curl -i -XPOST 'http://aoelinfluxpoc001:8086/write?db=testdb' --data-binary 'cpuloadshort1,host=server01 value=0.65'

HTTP/1.1 204 No Content
Request-Id: b7b73a0e-cc12-11e5-bd2f-000000000000
X-Influxdb-Version: 0.9.4.2
Date: Fri, 05 Feb 2016 14:14:09 GMT
```

I haven't yet started facing the similar issue for 0.10.0 but I think I may get the same soon as I have started getting database not found error. Any solutions for this?

**Comment by mark-rushakoff** [comment] 2016-02-05 14:56
I'm not familiar enough with the database internals to say whether rapidly creating and deleting a database with the same name is currently expected to work correctly.

As a workaround, could you try making a unique database per test? e.g.

```bash
TEST_DB="testdb-${date +%s}"

curl -i -XPOST "http://aoelinfluxpoc001:8086/write?db=${TEST_DB}" --data-binary '...'
```

**Comment by goyalr41** [comment] 2016-02-08 05:28
Ok thanks this is working but what is the problem with having same name of the database? And why it corrupts other databases as well? Is this something related to corrupting the metastore?

**Comment by jwilder** [comment] 2016-02-08 22:58
@goyalr41 Is this occurring with `0.10.0`?  Can you provide a script to reproduce the error?  When you say there is "corruption", what error are you seeing?

**Comment by goyalr41** [comment] 2016-02-09 19:22
Yup this is occurring with 0.10.0. There is no fix script to make this error appear. Just rapid creation and deletion of the same database leads to it. So, it still writes to the database but throws 404 or 500 status code.
By corruption I mean for the other databases in influxdb which are not used for testing (were only created once), writing to database is successful (point is getting inserted into the database) but the API is throwing 404 or 500 error code for that database as well.

**Comment by jboursiquot** [comment] 2016-03-03 00:39
Yep, we have the same issue on the Enterprise team.

**Comment by joelegasse** [comment] 2016-03-04 14:21
@goyalr41 I'm going to close this issue as we have been unable to reproduce this with the 0.10 releases. I ran a script that has done over 50,000 drop/create/write loops on the same database without issue.

If you can provide the log output leading up to the drop then create database succeeding followed by an immediate write that fails, or steps to reproduce the failure, please open a new ticket with those details.

**Closed by joelegasse** 2016-03-04 14:21 UTC
