### ISSUE TITLE
Unable to proceed with influx 2.0.0 alpha after initial setup

### ISSUE THREAD

**Issue by dkowis** [influxdata/influxdb#15949] opened 2019-11-16 18:41 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. start influxd from scratch, fresh install, no users or anything
    * `influxd --bolt-path /srv/influxdb/influxd.bolt --engine-path /srv/influxdb/engine --log-level debug`
2. go through the web-based initial setup
3. try to log in

__Expected behavior:__
I guess I should log in, and be able to do stuff. I've never used influxdb before :(

__Actual behavior:__
I got an error message on the webui. Nothing in the logs on the server.
`Failed to create influxDB 2.0 OSS Metrics Dashboard`
`Failed to configure InfluxDB Scraper`

Subsequent login attempts fail completely.

__Environment info:__

* System info:
```
root@monitor:~# uname -srm
Linux 5.0.0-36-generic x86_64
```
* InfluxDB version: `2.0.0.alpha-19`
* Other relevant environment details: Native executable.

**Comment by russorat** [comment] 2019-11-22 18:35
@dkowis thanks for opening an issue. I'm not able to reproduce this on my machine. I'm using the latest master branch. Could you try again with Alpha 20 and see if you have the same problem?

![image](https://user-images.githubusercontent.com/4805997/69451274-cfcbc880-0d13-11ea-8ce9-9d0aa318eac5.png)

**Comment by russorat** [comment] 2020-04-03 20:00
I'm closing this for now. If this is still an issue on the latest beta, please reopen.

**Closed by russorat** 2020-04-03 20:00 UTC
