### ISSUE TITLE
[0.10.0] Inconsistent answer in http admin interface

### ISSUE THREAD

**Issue by Oliv4945** [influxdata/influxdb#5683] opened 2016-02-13 23:09 UTC
The command `SHOW CONTINUOUS QUERIES` returns `Query returned no results!` in the http admin interface but returns it in the console with 'influx' binary
```
name: db_note
-------------
name				query
downSampling_10m		CREATE CONTINUOUS QUERY downSampling_10m ON db_note BEGIN SELECT mean(value) AS value INTO db_note.ret_7d_10m.sensorsData FROM _internal.monitor.sensorsData GROUP BY time(10m), * END
```
I am using official Debian package, version 0.10.0

**Comment by zstyblik** [comment] 2016-02-14 05:42
Duplicate of https://github.com/influxdata/influxdb/issues/4688

**Comment by toddboom** [comment] 2016-02-14 05:43
@zstyblik thanks!

**Closed by toddboom** 2016-02-14 05:43 UTC

**Comment by Oliv4945** [comment] 2016-02-14 21:49
Sorry, I did not find it !
