### ISSUE TITLE
Low query performance of 0.9.6 dealing with high res time series

### ISSUE THREAD

**Issue by xrl** [influxdata/influxdb#5351] opened 2016-01-13 21:30 UTC
I am using telegraf to instrument 15 or so servers with a 10s sampling interval. The influxdb host started off very responsive and able to return results for large timespans. Now it is very slow and I am forced to change my time range down to 30 minutes to get a reasonable response time. I am using Grafana 2.5 to query influxdb.

You can see the influx and telegraf configs here: https://gist.github.com/xrl/4dddb71eabd606304065

**Comment by johnseekins** [comment] 2016-01-14 20:13
I know they recommend not having the WAL on the same disk as the data.

```
dir = "/var/lib/influxdb/data"
wal-dir = "/var/lib/influxdb/wal"
```

You could try moving that.

**Comment by beckettsean** [comment] 2016-01-15 02:04
@xrl what are the machine specs of the InfluxDB server, and how many points per second are the telegraf sources writing?

What are some actual queries and their response times from the logs?

**Comment by steverweber** [comment] 2016-01-16 22:20
if viewing a large timespan of data that is granular 10s interval, you might want to create a continuous query.

another fix,   Perhaps try tweaking auto in the "GROUP BY time(auto)"

I wish grafana's group by time(auto) was 1/2 as granular by default,
https://github.com/grafana/grafana/issues/3763

**Comment by jwilder** [comment] 2016-02-08 21:56
This should be fixed after #5196 is merged.

**Comment by steverweber** [comment] 2016-02-08 23:05
wow that's A pull request.

**Comment by jwilder** [comment] 2016-03-18 01:42
Closing since the new query engine has been merged and there are no steps to reproduce this issue.

**Closed by jwilder** 2016-03-18 01:42 UTC
Labels: category/performance, category/queries
