### ISSUE TITLE
RegEx doesn't work fine with string fields

### ISSUE THREAD

**Issue by Ilyasbel** [influxdata/influxdb#10022] opened 2018-07-02 12:56 UTC
**System info:**
CentOS 7 x86_64
InfluxDB OSS v. 1.5.2
Kapacitor OSS v. 1.5.0

**Steps to reproduce:**
1. I have different measurements (10k) all of them with the same schema: Four fields (f1, f2, f3, & f4) and one tag. Fields f1, f2, and f3 are always strings, but f4 can be floats, integers, or strings depending on the measurement. 
2. I'm using this query in Kapacitor to take the data from InfluxDB: 
`SELECT f1, f2, f3, f4 FROM "db_name"."rp_name"./.*/ WHERE ...` 
but when f4 is a string it doesn't return values.
I've tried this query in InfluxDB shell and I have the same problem:
`SELECT f1, f2, f3, f4 FROM "db_name"."rp_name"./.*/ limit 10`

**Expected behavior:** 
`SELECT f1, f2, f3, f4 FROM "db_name"."rp_name"./.*/ limit 10` returns the values of f4 when f4 is a string

**Actual behavior:**
The query doesn't returns the values of f4 when they are strings, but returns the values of f1, f2, and f3

**Additional info:**
I'm using Kapacitor to store only the changes in batch. This is the code and it works fine if f4 is a integer:
```
dbrp "db_name"."rp_1_name"
var q = batch
    |query(''' SELECT f1, f2, f3, f4 FROM "db_name"."rp_1_name"./.*/ WHERE "level"='ALL_SAMPLES' ''')
        .offset(1h)
        .period(1d)
        .every(1d)
        .groupByMeasurement()
    
q
    |changeDetect('f4')
    |influxDBOut()
        .database('db_name')
        .retentionPolicy('rp_2_name')
        .tag('level', 'ONLY_CHANGES')

q
    |changeDetect('f3')
    |influxDBOut()
        .database('db_name')
        .retentionPolicy('rp_2_name')
        .tag('level', 'ONLY_CHANGES')

q
    |changeDetect('f2')
    |influxDBOut()
        .database('db_name')
        .retentionPolicy('rp_2_name')
        .tag('level', 'ONLY_CHANGES')
```

More information: https://github.com/influxdata/kapacitor/issues/1976

**Comment by e-dard** [comment] 2018-07-02 14:34
I think this is very likely the same underlying issue as #10006

**Comment by zeebo** [comment] 2018-07-03 22:30
I agree this is the same underlying issue as #10006 which in turn is the same issue as #8858 which was closed as "working as intended," so the same thing applies here.

**Closed by zeebo** 2018-07-03 22:30 UTC
Labels: area/query language, kind/bug

**Comment by Ilyasbel** [comment] 2018-07-04 13:45
Sorry, @zeebo, but I don't understand why this is a intentional behaviour, I can't see any advantage. Indeed I think this force me to use stream tasks in Kapacitor (and this can be a problem with a big window period and 50k measurements), I think it could negatively affects to CQs, and it's a problem to restore a database that already exists (scroll to Restore examples section in the documentation: https://docs.influxdata.com/influxdb/v1.5/administration/backup_and_restore/#restore)
Maybe I'm missing out, but if I'm not, I think this should be a enhancement feature.

**Comment by e-dard** [comment] 2018-07-09 10:19
@Ilyasbel this is not really desired behaviour, but is instead a trade-off within the query engine. When we say it's working as intended that's what we mean in this case (it's not a bug).

I agree that the behaviour could be better here (because the fields are only different types for different measurements), but it's not clear how much work would be needed to support this. I think it's very unlikely that the behaviour will be changed, but I'm happy to ask within the team if it's something that could be done without too much effort.

**Comment by Ilyasbel** [comment] 2018-07-09 11:08
I understand, if it's something that could be done without too much effort will be great! :) Thank you so much for asking, @e-dard!!

Btw, last week I thought it would be clearer to create a new issue to talk about this, and display the information as a feature request instead of a bug, so I opened the issue #10042

**Comment by Ilyasbel** [comment] 2018-07-24 13:56
Hi, @e-dard! 
Is there any news or any workaround about this?

**Comment by e-dard** [comment] 2018-07-24 14:10
@Ilyasbel I don't think this is going to be prioritised at this time. Sorry.

**Comment by Ilyasbel** [comment] 2018-07-25 08:22
Ok, thanks any way, @e-dard! 
There isn't a workaround, right?
