### ISSUE TITLE
[0.9.6.1] literal backslash in measurement not being respected

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#5378] opened 2016-01-17 13:54 UTC
Think I've found a bug with how backslashes are handled. At the moment it seems that if a measurement name has a literal backslash followed by an _escapable_ character the measurement won't be parsed correctly.

Example, when trying to insert the following measurement with a literal slash followed by an escaped space:

```go
fmt.Println([]byte(`cpu\\ `)) //  [99 112 117 92 92 32]
```

```
> drop database test
> create database test
> use test
Using database test
> insert cpu\\  value=1i 1000000000
> show series
name: cpu
----------
_key
cpu\\

> select * from "cpu\\ "
> select * from "cpu\\"
> select * from "cpu"
> select * from "cpu "
name: cpu
----------
time		value
1000000000	1

>
```

The correct measurement name should be `cpu\ `, that is `cpu` followed by a `\` and a single space ` `.

**Comment by e-dard** [comment] 2016-01-17 20:17
@beckettsean looking through the issues, I think this is the same problem as #4865 isn't it?

**Comment by beckettsean** [comment] 2016-01-20 19:24
@e-dard most likely, yes. Backslashes are problematic because of their ability to escape themselves and spaces.

**Comment by beckettsean** [comment] 2016-01-22 22:55
closing as dupe of #4865

**Closed by beckettsean** 2016-01-22 22:55 UTC
