### ISSUE TITLE
Query Builder doesn't handle tag keys with `.` properly

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb#16114] opened 2019-12-04 17:39 UTC
Flux looks at something like `r.io.kubernetes.pod.name` and treats it like nested objects. If there is a tag key called `io.kubernetes.pod.name` and the user selects it with the query builder, you might end up with a Flux query like this:

```
from(bucket: "infra")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "docker_container_cpu")
  |> filter(fn: (r) => r.io.kubernetes.pod.name == "storage-8" )
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

This will result in an error: `cannot add type constraint @ 4:17-4:714: type error 0:0-0:0: missing object properties (io)`.

This error is resolved by using double quotes around the key, i.e., `"r.io.kubernetes.pod.name"`. The query builder should add those in.

**Comment by drdelambre** [comment] 2020-02-21 16:41
dupe of #15818

**Closed by drdelambre** 2020-02-21 16:41 UTC
Labels: kind/bug, team/monitoring
