### ISSUE TITLE
[feature request] Support of IN clause in query

### ISSUE THREAD

**Issue by pribiswas** [influxdata/influxdb#5626] opened 2016-02-11 06:45 UTC
Suppose I have following points in influxdb:
{account_id: 1, user_id: 1}
{account_id: 2, user_id: 2}
{account_id: 3, user_id: 3}

I just want to select those points where account_id belongs to [1, 2, 3]. Something like:
SELECT * FROM my_series WHERE account_id IN ('1', '2', '3')

Looks like IN CLAUSE is not supported in influx QL. I am using v0.10.0. Is there any plan to support IN clause in future?

**Comment by groblus** [comment] 2016-02-11 09:07
+1

**Comment by rossmcdonald** [comment] 2016-02-11 15:39
@pribiswas I don't believe there are currently any plans to add support for the `IN` clause, but I'll file this as a feature request.

**Comment by cxreg** [comment] 2016-02-18 23:52
+1 from me too, this would be huge.  you can do it with a regex and alternations, but it's clunky and probably doesn't make use of the index.  For example

SELECT * FROM my_series WHERE account_id =~ /^1$|^2$|^3$/

**Comment by cxreg** [comment] 2016-02-19 00:04
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/wjawZZ0RFRE/cydIk0xPZCIJ seems to confirm my notion that this is unindexed.  I would hope and expect that an IN() version would indeed make use of the index here

**Comment by jsternberg** [comment] 2016-04-07 14:23
Closing as a duplicate of #2157.

**Closed by jsternberg** 2016-04-07 14:23 UTC
Labels: category/feature request, category/queries

**Comment by ishita07-danaher** [comment] 2020-02-11 13:50
Hi..I was trying to implement something similar using both reg ex and 'OR' .
Where these approaches fail :

Reg ex : if the value I have passed is contained in the column value, it reads that though it shouldn't. Reg ex is similar to 'contains'..I want to compare the exact same value.

OR : I want data for both values not either of them.

Please suggest another approach for IN clause.
