### ISSUE TITLE
[Feature request] Selector function for the latest X points

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb#7089] opened 2016-07-28 13:36 UTC
**Feature Request**

**Description:**

FIRST and LAST selector functions only retrieve a single point.

We have received feedback from users who ask about retrieving the latest X points.
For the moment the way to achieve this is using ORDER BY TIME DESC and LIMIT clauses. The only additional clause to improve performance is adding time boundaries.
Users usually don't have an indication for the timestamp of the point they are looking for so adding time boundaries can be a challenge.

**Proposal:**

Implement a latest(field,X) selector function, where X is the number of latest points to return (preferably ordered by desc).

**Comment by jsternberg** [comment] 2016-07-30 03:13
I think `ORDER BY time DESC` would be more performant with a change @benbjohnson is working on for lazy iterators. If we can make that more performant, would that work well?

**Comment by kostasb** [comment] 2016-08-01 09:16
@jsternberg The concern is about having to select a measurement unbound by time in order to pick the latest X values. With any large measurement the selected points may not fit into memory and will oom the system before `order by` applies. Do you think a `latest` function could pick up the requested points without having to check against the whole measurement?

**Comment by jsternberg** [comment] 2016-08-02 21:23
I think the issue is mostly that, without the where clause telling us the time range, we're not sure which shards have the last X points of data for every tag. You can have 10 points written in the 1990's for a series and `LIMIT 10` is still supposed to get those. Do we need "The last 10 points from all series" or "The last 10 points from all series that have points written after some time" because these are different questions and, therefore, have to be separate queries. No selector function is going to change that fact since it would have to be implemented in the same way as limit is currently implemented (at least if I'm understanding the issue correctly).

But the lazy iterator change that @benbjohnson is working on in #7107 should order the shards so that we only instantiate iterators for the shards that are actually relevant rather than reading 10 points from every shard in existence. If you have 10 series with 10 points in 10 shards, the current implementation will read 1,000 points and discard 900 of those points. The new implementation should be limited to only reading 100 points rather than 1,000 and won't need to discard any points if we implement it correctly. That might be the reason why the current version doesn't work well in the circumstance you are talking about here.

**Comment by kostasb** [comment] 2016-08-03 12:26
Thanks Jonathan, in order to clear things up: with the upcoming improvements on LIMIT will the following query retrieve exactly 10 points instead of retrieving the whole measurement? (or, more accurately, retrieving 10 values from each shard as you explained).

`SELECT * FROM MEASUREMENT ORDER BY TIME DESC LIMIT 10`

Does the query engine "understand" that it will need to apply the LIMIT clause before the `SELECT * FROM MEASUREMENT ORDER BY TIME DESC` is executed?

If it does work like that it should efficiently satisfy this request.

**Comment by N-Coder** [comment] 2016-10-24 17:50
Doesn't seem to be working in 1.0.2.
When running `SELECT * FROM samples ORDER BY time ASC LIMIT 10` against the measurement "samples" with about 100,000,000 entries it takes about 3 minutes. As soon as I add a time constraint (limiting the amount of entries to 4,620,726 of 99,866,004), the query only takes 4 seconds. With a limit that is even closer to the beginning of the recordings, selecting the first of 272,465 rows only takes 30ms.
All queries return the same data, but the query without the time limit also returns columns in the data set which are empty for all of the 10 selected rows.
@benbjohnson somehow your changes seem to have vanished from the changelog, even though your commit was merged into master. Could you give us an update on this issue?

**Comment by benbjohnson** [comment] 2016-10-24 19:14
@N-Coder The lazy iterator fix I implemented caused a regression and had to be reverted. @jsternberg is looking into the lazy iterators.

**Comment by N-Coder** [comment] 2016-11-17 01:23
So this is probably also related to issues #7303, #7035, #7182 and PR #7455 (didn't see a connection between those issues and this one before, maybe this one can even be merged into one of them).

**Closed** 2019-07-30 23:29 UTC
Labels: 1.x, area/functions, kind/feature request, wontfix
