### ISSUE TITLE
Not able to update the name option in the flux script using API.

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#12093] opened 2019-02-22 00:39 UTC
Updating `name` option in the flux script return an error : 
`cannot update task without content`

I am running  `bf34b35fb4cf980db00e18278cc537f72c2d1b9e@master` of `influxdb`

- Create a task with following params:
```
Organization ID : '0370a22a10634000'
Organization Name : ''
Task Description : 'test_description'
Flux Script: 'option task = {name:"task_1", every: 10m} from(bucket:"read_from_b_query_params") |> range(start: -1h)'
Status : 'active'
Token : 'WL6RhxW2A70nYS8aRcRJYCE8-QdyIn1SoIZnLS7SOxYDP4fkPjt3BxA07Gd7pJEYAtmB992izXzvbUUihUUJfw=='
```

Request Body : 
```
 '{"orgID":"0370a22a10634000", "name":"test_description", "flux":"option task = {name:\"task_1\", every: 10m} from(bucket:\"read_from_b_query_params\") |> range(start: -1h)", "status":"active"}'
```

- Update task: update name in the flux script:
Request Body:

```
{"name": "test_update_task_description_updated"}
```

Request:

```
http://localhost:9999/api/v2/tasks/0370a22c0f20f000,  data={"name": "test_update_task_description_updated"}, headers={'Authorization': u'Token WL6RhxW2A70nYS8aRcRJYCE8-QdyIn1SoIZnLS7SOxYDP4fkPjt3BxA07Gd7pJEYAtmB992izXzvbUUihUUJfw=='}
```

returns error:
```
e_msg = 'failed to update task'
e_code = 'internal error'
e_op = 'None'
e_err = 'cannot update task without content'
error_message = '{u'message': u'failed to update task', u'code': u'internal error', u'error': u'cannot update task without content'}'
```

**Comment by mark-rushakoff** [comment] 2019-02-22 18:01
I'm pretty sure this is a duplicate of #11670, but let's double check after that issue addressed.

**Comment by gshif** [comment] 2019-02-26 19:18
Verified with the master build @2f0dd5873720ff9aaceb35b9b57f61769d2a563c

**Closed** 2019-02-26 19:18 UTC
Labels: area/tasks, kind/bug
