### ISSUE TITLE
Restoring backup causes: Error updating shards: unexpected EOF

### ISSUE THREAD

**Issue by drb-germany** [influxdata/influxdb#9613] opened 2018-03-21 20:23 UTC
We are running InfluxDB 1.5.0 on Windows 7, 64 bit (pre-built) and write quite some data to the database (summing to a few GB per month). 

We create a backup for one day and restore it without problem. When creating a backup for one week or one month there is no problem when creating the backup, but during restore the following error is given:

2018/03/21 .... error updating shards: unexpected EOF
restore: unexpected EOF

- As written above, using only one day as a backup period works.
- Backing up one month of a time-period where only one day of data is in the database and the rest empty (making the backup as small as a one-day backup) and restoring it works fine as well.
- This error is independent whether -portable or -online (legacy) option is used.
- This error is independent whether importing to a new or the same influx instance (using a different database name).

We have tried many different time-ranges, always with the same result once the total size is more than ~200-300 MB. So it looks like this is connected to backups of larger sizes.

The backup is usually restored about 90-95% of the complete time-range. Looks like the last part is always missing.

When we backup one week we have a backup size of approx. 300 MB. One month has about 1.8 GB.
ShardGroupDuration is 168 hours (retention policy duration is 87600 hours, so approx. 10 years).

**Comment by aanthony1243** [comment] 2018-03-27 18:19
Hi, I may need more information to reproduce.   Could you share the command you use to create the backup?  database names can be changed if needed.

**Comment by drb-germany** [comment] 2018-03-27 20:07
Hi. I am on travel until the end of next week, so I will not be able to test and log more details at the moment, sorry. I have, however, tested the issue on two more machines with version 1.5.0 on Windows. In one case I had the same error despite a backup size of only one day, so it seems to be independent of size. 

I was using the following command:

. \influxd.exe backup -portable -database dbname -start 2018-03-01T00:00:00Z - end 2015-12-24T08:12:23Z

**Comment by aanthony1243** [comment] 2018-03-27 20:15
Thank you, I'll try to reproduce this locally and report back early next week.

**Comment by peter-fm** [comment] 2018-03-28 12:14
Here is what I am trying on ununtu 16.04. Influx version: 1.5.1.

The database was generated using the influxdb-java library version 2.7

data in db_test from '2018-03-28T11:17:05.084Z' to '2018-03-28T11:23:41.944Z'
```
use db_test
select count(price) from price : 146049
select count(price) from price where time < '2018-03-28T11:20:08Z' : 89282
select count(price) from price where time > '2018-03-28T11:20:08Z' : 56767
```

create a first backup from start to '2018-03-28T11:20:08Z'
```
influxd backup -database db_test -portable -end 2018-03-28T11:20:08Z /tmp/backup/influxdb/firstbackup
2018/03/28 11:48:28 backup complete:
2018/03/28 11:48:28     /tmp/backup/influxdb/firstbackup/20180328T114827Z.meta
2018/03/28 11:48:28     /tmp/backup/influxdb/firstbackup/20180328T114827Z.s16.tar.gz
2018/03/28 11:48:28     /tmp/backup/influxdb/firstbackup/20180328T114827Z.manifest
```

create a second backup from last backup to end
```
influxd backup -database db_test -portable -start 2018-03-28T11:20:08Z /tmp/backup/influxdb/secondbackup
2018/03/28 11:49:33 backup complete:
2018/03/28 11:49:33     /tmp/backup/influxdb/secondbackup/20180328T114932Z.meta
2018/03/28 11:49:33     /tmp/backup/influxdb/secondbackup/20180328T114932Z.s16.tar.gz
2018/03/28 11:49:33     /tmp/backup/influxdb/secondbackup/20180328T114932Z.manifest
```

delete database 
`DROP DATABASE db_test`

restore attempt from first backup into db_test
```
influxd restore -db db_test -portable /tmp/backup/influxdb/firstbackup
2018/03/28 11:56:19 Restoring shard 16 live from backup 20180328T114827Z.s16.tar.gz
2018/03/28 11:56:19 error updating shards: unexpected EOF
restore: unexpected EOF
```

restore attempt into another database from second backup
```
influxd restore -db db_test -newdb second_db_test -portable /tmp/backup/influxdb/secondbackup
2018/03/28 12:01:08 Restoring shard 16 live from backup 20180328T114932Z.s16.tar.gz
2018/03/28 12:01:08 error updating shards: unexpected EOF
restore: unexpected EOF

```
Any help would be much appreciated.

**Comment by aanthony1243** [comment] 2018-03-28 20:56
Hi, when you are able, I will need the influxdb server logs from the time that you took the backup.

**Comment by peter-fm** [comment] 2018-03-29 12:43
I wasn't saving the logs last time so I reran it again with some similar data (from '2018-03-29T11:12:47.88Z' to '2018-03-29T11:23:14.426Z') with the same result:
```
influxd backup -database db_test -portable -end 2018-03-29T11:17:08Z /tmp/backup/influxdb/firstbackup
influxd backup -database db_test -portable -start 2018-03-29T11:17:08Z /tmp/backup/influxdb/secondbackup
```
`DROP DATABASE db_test`
```
influxd restore -db db_test -portable /tmp/backup/influxdb/firstbackup
influxd restore -db db_test -newdb second_db_test -portable /tmp/backup/influxdb/secondbackup
```
The following logs cover from creating the two backups, dropping db_test and the attempting to restore the two backups as in the last post. 
```
ts=2018-03-29T11:58:26.066181Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.066350Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W001 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.066479Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W002 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.066585Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W003 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.073513Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.073626Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G001 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:26.093762Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G001 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/_internal/monitor/20 duration=20.143ms
ts=2018-03-29T11:58:26.093796Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G001 op_name=tsm1_cache_snapshot op_event=end op_elapsed=20.175ms
ts=2018-03-29T11:58:26.095349Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/_internal/monitor/14 duration=29.181ms
ts=2018-03-29T11:58:26.095374Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=29.202ms
ts=2018-03-29T11:58:26.096923Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/_internal/monitor/1 duration=23.418ms
ts=2018-03-29T11:58:26.096941Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos6G000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=23.434ms
ts=2018-03-29T11:58:26.158148Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W003 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/_internal/monitor/15 duration=91.567ms
ts=2018-03-29T11:58:26.158181Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W003 op_name=tsm1_cache_snapshot op_event=end op_elapsed=91.598ms
ts=2018-03-29T11:58:26.160562Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W001 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/db_test/autogen/22 duration=94.216ms
ts=2018-03-29T11:58:26.160584Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W001 op_name=tsm1_cache_snapshot op_event=end op_elapsed=94.236ms
ts=2018-03-29T11:58:26.702386Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W002 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/temp/autogen/23 duration=635.911ms
ts=2018-03-29T11:58:26.702436Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Pos4W002 op_name=tsm1_cache_snapshot op_event=end op_elapsed=635.959ms
ts=2018-03-29T11:58:27.067699Z lvl=info msg="TSM compaction (start)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group op_event=start
ts=2018-03-29T11:58:27.067739Z lvl=info msg="Beginning compaction" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group tsm1_files=2
ts=2018-03-29T11:58:27.067749Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/15/000000013-000000002.tsm
ts=2018-03-29T11:58:27.067757Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/_internal/monitor/15/000000015-000000001.tsm
ts=2018-03-29T11:58:27.085076Z lvl=info msg="Compacted file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/15/000000015-000000002.tsm.tmp
ts=2018-03-29T11:58:27.085110Z lvl=info msg="Finished compacting files" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group groups=2 files=1 duration=17.424ms
ts=2018-03-29T11:58:27.085125Z lvl=info msg="TSM compaction (end)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Povzl000 op_name=tsm1_compact_group op_event=end op_elapsed=17.430ms
ts=2018-03-29T11:58:28.066284Z lvl=info msg="TSM compaction (start)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group op_event=start
ts=2018-03-29T11:58:28.066326Z lvl=info msg="Beginning compaction" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group tsm1_files=2
ts=2018-03-29T11:58:28.066333Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/14/000000015-000000002.tsm
ts=2018-03-29T11:58:28.066352Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/_internal/monitor/14/000000017-000000001.tsm
ts=2018-03-29T11:58:28.132818Z lvl=info msg="Compacted file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/14/000000017-000000002.tsm.tmp
ts=2018-03-29T11:58:28.132855Z lvl=info msg="Finished compacting files" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group groups=2 files=1 duration=66.588ms
ts=2018-03-29T11:58:28.132871Z lvl=info msg="TSM compaction (end)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078PoztW000 op_name=tsm1_compact_group op_event=end op_elapsed=66.597ms
ts=2018-03-29T11:58:29.066299Z lvl=info msg="TSM compaction (start)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group op_event=start
ts=2018-03-29T11:58:29.066343Z lvl=info msg="Beginning compaction" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group tsm1_files=2
ts=2018-03-29T11:58:29.066351Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1/000000035-000000002.tsm
ts=2018-03-29T11:58:29.066357Z lvl=info msg="Compacting file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group tsm1_index=1 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1/000000037-000000001.tsm
ts=2018-03-29T11:58:29.080983Z lvl=info msg="Compacted file" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group tsm1_index=0 tsm1_file=/var/lib/influxdb/data/_internal/monitor/1/000000037-000000002.tsm.tmp
ts=2018-03-29T11:58:29.081014Z lvl=info msg="Finished compacting files" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group groups=2 files=1 duration=14.733ms
ts=2018-03-29T11:58:29.081030Z lvl=info msg="TSM compaction (end)" log_id=078PojJG000 engine=tsm1 tsm1_strategy=full tsm1_optimize=false trace_id=078Pp2nW000 op_name=tsm1_compact_group op_event=end op_elapsed=14.742ms
ts=2018-03-29T11:58:41.951411Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078Ppq7l000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:41.951528Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078Ppq7l000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/db_test/autogen/22 duration=0.128ms
ts=2018-03-29T11:58:41.951548Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078Ppq7l000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=0.144ms
ts=2018-03-29T11:58:42.139030Z lvl=info msg=EOF log_id=078PojJG000 service=snapshot
ts=2018-03-29T11:58:53.746328Z lvl=info msg="Cache snapshot (start)" log_id=078PojJG000 engine=tsm1 trace_id=078PqZCW000 op_name=tsm1_cache_snapshot op_event=start
ts=2018-03-29T11:58:53.746428Z lvl=info msg="Snapshot for path written" log_id=078PojJG000 engine=tsm1 trace_id=078PqZCW000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/db_test/autogen/22 duration=0.110ms
ts=2018-03-29T11:58:53.746444Z lvl=info msg="Cache snapshot (end)" log_id=078PojJG000 engine=tsm1 trace_id=078PqZCW000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=0.123ms
ts=2018-03-29T11:58:53.942589Z lvl=info msg=EOF log_id=078PojJG000 service=snapshot
[httpd] 127.0.0.1 - - [29/Mar/2018:11:59:08 +0000] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/1.5.1" 963e55ba-3348-11e8-8001-000000000000 83
ts=2018-03-29T11:59:19.555296Z lvl=info msg="Executing query" log_id=078PojJG000 service=query query="DROP DATABASE db_test"
[httpd] 127.0.0.1 - - [29/Mar/2018:11:59:19 +0000] "POST /query?chunked=true&db=&q=DROP+DATABASE+db_test HTTP/1.1" 200 57 "-" "InfluxDBShell/1.5.1" 9cc3f90b-3348-11e8-8002-000000000000 12678
ts=2018-03-29T11:59:37.567406Z lvl=info msg="unexpected EOF" log_id=078PojJG000 service=snapshot
ts=2018-03-29T11:59:47.159168Z lvl=info msg="unexpected EOF" log_id=078PojJG000 service=snapshot
```

**Comment by mathieulongtin** [comment] 2018-04-03 17:40
This is only an issue when using -start and -end.

**Comment by aanthony1243** [comment] 2018-04-04 14:17
@mathieulongtin  we are working on this now.  re:  -database telegraf   there has been some confusion about the flags used in backup vs restore.  We're going to fix/clarify this in a minor release.   in the meantime, please use  `-db telegraf`  to import a single database.

**Comment by mathieulongtin** [comment] 2018-04-04 16:21
I tried both `-database` and `-db`. Didn't seem to change anything. I also use "-portable" as that seems to be the right thing, but that's not clear.

Maybe related, if only using `-start` without `-end`, the entire database is dumped.

**Comment by aanthony1243** [comment] 2018-04-04 16:30
@mathieulongtin   I have a handle on the start/end unexpected EOF bug.  Need a bit of time to reproduce locally and confirm the fix, but it should come soon.  

re: the -db flag.  Could you copy me the commands you used for both the backup and the restore?  we seem to have introduced some confusion with the variety of new options, and a real use-case would help us to clarify the docs + cmd-line UI

**Comment by aanthony1243** [comment] 2018-04-05 20:25
The EOF error has been reproduced and fixed by #9684 .   The change will be shipped in the next minor release, 1.5.2

**Closed by aanthony1243** 2018-04-05 20:25 UTC
Labels: area/backup and restore, kind/bug

**Comment by aanthony1243** [comment] 2018-04-13 01:50
FYI 1.5.2 was released today.

**Comment by sjoshid** [comment] 2020-09-29 20:14
Im getting this same issue even on 1.8.2. I could have provided more details but they are very similar to what others have already posted. 

As already mentioned, it is an issue only when `-start` and `-end` are provided. 

There is one difference in my case. Im exporting 1.5 data and importing in 1.8. I dont think this is an issue because `-since` works fine.
