### ISSUE TITLE
invalid memory address or nil pointer dereference when using regex

### ISSUE THREAD

**Issue by lucianmusat** [influxdata/influxdb#9849] opened 2018-05-16 14:06 UTC
__System info:__: 1.5.2, Centos 7.2

__Steps to reproduce:__
Trying to run a query like:
```SELECT 100 - mean(value) FROM db.autogen.cpu_value WHERE test_id = '4234' AND value > 0 AND type_instance = 'idle' AND host =~ /ahostname/ AND time > '1970-01-01T00:02:00Z'```

__Expected behavior:__ 
Get the mean value back

__Actual behavior:__ 
`ERR: SELECT 100 - mean(value) FROM db.autogen.cpu_value WHERE test_id = '4234' AND value > 0 AND type_instance = 'idle' AND host =~ /ahostname/ AND time > '1970-01-01T00:02:00Z' [panic:runtime error: invalid memory address or nil pointer dereference]`

__Additional info:__ 
Removing the `"AND host =~ /ahostname/"` works and does not crash. Tried with and without spaces around the =~

How can we get the stacktrace? The journal does not even have this error and nothing in /var/log/messages

**Comment by dgnorton** [comment] 2018-05-16 14:15
possibly related to or duplicate of #9798

**Comment by azhurbilo** [comment] 2018-06-08 10:18
influxdb 1.5.2

```
{"lvl":"info","ts":"2018-06-08T10:14:24.605147Z","msg":"Executing query","log_id":"08ZiEXK0000","service":"query","query":"DROP SERIES FROM /docker.*/ WHERE host =~ /gitlab-runner.*/"}
 panic: runtime error: invalid memory address or nil pointer dereference
 #011panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91c0c6]
 goroutine 233629 [running]:
 github.com/influxdata/influxdb/tsdb.SeriesIDIterators.Close(0xc423357000, 0x3, 0x4, 0x0, 0xc458d039c0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:205 +0x66
 github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Close(0xc437298b40, 0xc458d039d8, 0x3)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:368 +0x41
 github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Close(0xc43718b620, 0xc420165310, 0x0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:294 +0x34
 panic(0xce65c0, 0x13059a0)
 #011/usr/local/go/src/runtime/panic.go:491 +0x283
 github.com/influxdata/influxdb/tsdb.(*seriesIDMergeIterator).Next(0xc437298b40, 0xc458d03c88, 0xadbb9f, 0xc43b681560, 0xc458d03c58, 0x4123c7)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:381 +0xd7
 github.com/influxdata/influxdb/tsdb.(*filterUndeletedSeriesIDIterator).Next(0xc43718b620, 0x3a970, 0x3a980, 0xc452ae8000, 0xc42001a000, 0x7f634ea0f5f0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:299 +0x38
 github.com/influxdata/influxdb/tsdb.(*seriesIteratorAdapter).Next(0xc43718b640, 0x0, 0x2710, 0xc452ae8000, 0x0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/index.go:104 +0x49
 github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).DeleteSeriesRange(0xc45027ad80, 0x12c6ae0, 0xc43718b640, 0x8000000000000002, 0x7ffffffffffffffe, 0x0, 0x0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1268 +0xeb
 github.com/influxdata/influxdb/tsdb.(*Shard).DeleteSeriesRange(0xc43b67c540, 0x12c6ae0, 0xc43718b640, 0x8000000000000002, 0x7ffffffffffffffe, 0x0, 0x0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/shard.go:696 +0x8e
 github.com/influxdata/influxdb/tsdb.(*Store).DeleteSeries.func1(0xc43b67c540, 0x0, 0x0)
 #011/go/src/github.com/influxdata/influxdb/tsdb/store.go:1167 +0x584
 github.com/influxdata/influxdb/tsdb.(*Store).walkShards.func1(0xc423c014f0, 0xc45ba66720, 0xc43b67c540)
 #011/go/src/github.com/influxdata/influxdb/tsdb/store.go:816 +0x48
 created by github.com/influxdata/influxdb/tsdb.(*Store).walkShards
 #011/go/src/github.com/influxdata/influxdb/tsdb/store.go:815 +0x87
```

**Comment by FlashSystems** [comment] 2018-10-25 19:00
Currently running influxdb 1.6.3. When using the query `SELECT last("value") FROM "snmp" WHERE ("type" = 'batempty') AND ("type_instance" =~ /[TR].*|WS_.*/) GROUP BY "type_instance"` influx db panics with `[panic:runtime error: invalid memory address or nil pointer dereference]`.

The query worked nicely until I dropped some information (approximately 120 measurements out of 3000000) using `DROP SERIES FROM "snmp" WHERE "type_instance"='T_02';`. Since then the panic occurs.

**Comment by kalidasya** [comment] 2018-10-26 10:46
We also delete from series regularly, that might be the other commonality

**Closed** 2019-07-31 13:29 UTC
Labels: 1.x, area/queries, panic, wontfix
