### ISSUE TITLE
bug(cmd/influx): INFLUX_TOKEN var doesn't map to `-t` or `--token` flag on setup

### ISSUE THREAD

**Issue by williamhuangh** [influxdata/influxdb#19482] opened 2020-09-02 01:55 UTC
```
ubuntu@ip-10-1-28-90:~$ docker exec -it influxdb bash
root@86aa031d9dc6:/$ influx setup -b admin -o admin -u admin -p admin
Welcome to InfluxDB 2.0!
Please type your retention period in hours.
Or press ENTER for infinite.:


You have entered:
  Username:          admin
  Organization:      admin
  Bucket:            admin
  Retention Period:  infinite
Confirm? (y/n): y
```

![Screen Shot 2020-09-01 at 6 54 19 PM](https://user-images.githubusercontent.com/6374091/91923184-9782ee80-ec84-11ea-9506-d4ef40863ccb.png)

```
root@86aa031d9dc6:/# env
HOSTNAME=86aa031d9dc6
PWD=/
HOME=/root
TERM=xterm
INFLUX_TOKEN=admin
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBIAN_FRONTEND=noninteractive
_=/usr/bin/env
```

**Comment by russorat** [comment] 2020-09-15 20:18
@williamhuangh thanks for the issue. we don't automatically set those ENV vars for you. we do create an `influx config` profile for your connection though, so you don't have to use the token anywhere.

if you want to grab the token afterwards, try: `INFLUX_TOKEN=$(influx auth list --json | jq -r '.[].token')`

**Comment by wbaker85** [comment] 2021-12-29 15:34
Closing this since I have confirmed it is fixed with the latest CLI.

**Closed by wbaker85** 2021-12-29 15:34 UTC
