### ISSUE TITLE
Derivatives in continuous queries don't work

### ISSUE THREAD

**Issue by paulstuart** [influxdata/influxdb#6401] opened 2016-04-16 05:24 UTC
### Bug report

Continuous queries containing derivatives appear to run but no data is ever generated 
__System info:__ [InfluxDB 0.12.1, CentOS 6.7 64 bit VM on a dual xeon server with gobs of memory

__Steps to reproduce:__

1. Create a continuous query that uses a derivative grouped on multiple tag values (in initial case)
2. Take CQ from the log, remove the "into" portion, run it in cli or web client.

__Expected behavior:__ [What you expected to happen]

One would expect to see derivatives of the data that is being sampled. 

__Actual behavior:__ [What actually happened]

Instead the records all have unset values.

__Additional info:__ [Include gist of relevant config, logs, etc.]

The time period of the query is the same length as the interval of the derivative and therefor doesn't allow for 2 points to be sampled and compared. Extending the time period (25 seconds seems to do it) and a value of 0 is generated. It seems to take a multiple of 3 sampling periods to capture the derivative.

*Please note, the quickest way to fix a bug is to open a Pull Request.*

### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ [Description of the feature]

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

**Comment by paulstuart** [comment] 2016-04-16 05:56
I realized I had skipped adding the "resample" option, but it still appears to be using the grouping period to generate the time range.

**Comment by paulstuart** [comment] 2016-04-16 15:32
I've tried all permutations of [RESAMPLE [EVERY <interval>] [FOR <interval>]], and the time range is still only for the grouping range.

**Comment by paulstuart** [comment] 2016-04-16 15:33
I believe this is related to #6395

**Comment by jsternberg** [comment] 2016-04-17 06:12
This is a duplicate of #3247. Thank you for the bug report. I'm going to close this since we have another ticket open for this issue.

**Closed by jsternberg** 2016-04-17 06:12 UTC
