### ISSUE TITLE
Change default bucket name to something other than "default"

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/influxdb#11548] opened 2019-01-24 19:44 UTC
InfluxDB originally used the name `default` for the default retention policy. This ended up being very confusing for users and hard to succinctly document. [Here is the original discussion on the topic](https://github.com/influxdata/influxdb/issues/3733). InfluxDB v2 has started using `default` as the default bucket name again. This should be switched to something else.

The earlier we can change this the better.

InfluxDB v1.x uses `autogen` as the retention policy name for the default auto-generated retention policy for new databases. Not sure if `autogen` makes sense in InfluxDB v2.0. @mark-rushakoff suggested using `my_bucket` as the default bucket name until there's a better suggestion.

**Comment by alexpaxton** [comment] 2019-01-24 19:45
Defbuck!

**Comment by russorat** [comment] 2019-01-24 19:45
the issue is that the pre-defined dashboard needs to be created with the bucket chosen. or add bucket as a template variable

**Comment by ebb-tide** [comment] 2019-02-04 17:53
Predefined dashboards could be changed to use the first bucket that is returned for a user. We still need template variables eventually, but this way we would not use 'default'.

**Comment by ebb-tide** [comment] 2019-02-04 17:54
Is it a problem that scraping is set up to write to a new bucket called 'default'?

**Comment by russorat** [comment] 2019-02-04 19:19
@ebb-tide yes! it should be set up to write to the bucket the user created.

**Comment by russorat** [comment] 2019-02-04 19:33
@ebb-tide also, the creation of the pre-defined dashboard needs to use the same bucket name as the user has for the telegraf config.

**Comment by ebb-tide** [comment] 2019-02-04 23:05
@russorat I can make precanned dashboards to work with just the first bucket that is returned for user, this would provide a quick hack that would work until we get macros and we can do what you suggest:
>the creation of the pre-defined dashboard needs to use the same bucket name as the user has for the telegraf config.

**Comment by ebb-tide** [comment] 2019-03-14 17:11
closed by #12533. Dashboards added to accompany telegraf plugins are now created by templates which can accept variables, rather than protoboards which could not. However, templates are initialized at onboarding, and will not exist for users who have previously gone through onboarding.

**Closed by ebb-tide** 2019-03-14 17:11 UTC
Labels: epic/onboardingui, ui/needs-discussion
