### ISSUE TITLE
Influxdb 1.2. Collectd service.  Multiple data sources for measurement don't work correctly.

### ISSUE THREAD

**Issue by cinek810** [influxdata/influxdb#8426] opened 2017-05-25 09:24 UTC
### Bug report

__System info:__ Influxdb 1.2, collectd-4.10

__Steps to reproduce:__  

1. enable collectd service in influxdb 
2. enable df plugin in collectd, configure collectd to send data to influx collectd service
3. check measurements created in influxdb
4. use types.db with:
`df                      used:GAUGE:0:1125899906842623, free:GAUGE:0:1125899906842623`

__Expected behavior:__ 
Expected is to have one measurement df with values stored in fileds named "used" and "free".
At least it's how it's described on mailing list:
[https://mailman.verplant.org/pipermail/collectd/2015-June/006551.html](https://mailman.verplant.org/pipermail/collectd/2015-June/006551.html) 

__Actual behavior:__ 
Two separate measurements 
`df_used`, `df_free` created

__Additional info:__ 
I've tried changing the ds names in types.db from used to df_used, the result was creation of measurement:
`df_df_used`
I suspect that data source is simply concatenated to the measurement name instead of beeing used as filed name in case of multiple values returned from measurement.

**Comment by rbetts** [comment] 2017-05-31 18:59
@cinek810 I've spent some time reading the influxdb collectd service code. I think what is happening is by design - good or bad.

The construction of the InfluxDB measurement name is done here:
https://github.com/influxdata/influxdb/blob/master/services/collectd/service.go#L395 . This, as you guessed, is concatenating collectd's `ValueList.Identifier.Plugin` field and `ValueList.DSName` for each value in the ValueList.

`Identifier.Plugin` is from collectd here: https://github.com/collectd/go-collectd/blob/master/api/main.go#L47

`DSName` is from collected here: https://github.com/collectd/go-collectd/blob/master/api/main.go#L82

Changing this behavior seems pretty straight forward but would require a configuration flag to opt in to the new measurement name encoding.

**Comment by cinek810** [comment] 2017-05-31 21:11
Since in new versions of influxdb we don't have joins it would be desired..
because now it's for example impossible to use collectd standard df plugin
to display percent of drive used..

2017-05-31 21:00 GMT+02:00 Ryan Betts <notifications@github.com>:

**Comment by rbetts** [comment] 2017-06-29 16:55
Resolved by https://github.com/influxdata/influxdb/pull/8523

**Closed by rbetts** 2017-06-29 16:55 UTC
Labels: area/collectd, backlog/testing, in progress
