### ISSUE TITLE
Combinations of AND+OR operators in WHERE doesn't work

### ISSUE THREAD

**Issue by pga23** [influxdata/influxdb#6866] opened 2016-06-17 20:41 UTC
### Bug report

__System info:__ 
Ubuntu 16.04 + IndluxDB v1.0.0-beta1

__Steps to reproduce:__

Insert example data:
```
mydata,reg=1 value=11 100
mydata,reg=2 value=21 100
mydata,reg=1 value=12 200
mydata,reg=2 value=22 200
```

Run the query:
```
SELECT * FROM mydata WHERE (time=100 AND reg='1') OR (time=200 AND reg='2')
```

__Expected behavior:__
Following results set:
```
time    reg   value
100     1     11
200     2     22
```
__Actual behavior:__
No data

__Additional info:__
 `SELECT * FROM mydata WHERE time=100 AND reg='1'`
and
 `SELECT * FROM mydata WHERE time=200 AND reg='2'`
returns data correctly, so by adding OR I expected results of both

**Comment by jsternberg** [comment] 2016-06-17 20:49
I think this is a duplicate of #3290. If I'm wrong, please respond and I can reopen this. Thanks.

**Closed by jsternberg** 2016-06-17 20:49 UTC

**Comment by pga23** [comment] 2016-06-17 21:46
I've already tested it also for the following queries:

`SELECT * FROM test_data WHERE (time='1970-01-01T00:00:00.0000002Z' AND reg='2')`
`SELECT * FROM test_data WHERE (time='1970-01-01T00:00:00.0000001Z' AND reg='1')`
and additionally
`SELECT * FROM test_data WHERE (time='1970-01-01T00:00:00.0000002Z' OR reg='2')`

all above returns correct data.

Combination of above with OR:
`SELECT * FROM test_data WHERE (time='1970-01-01T00:00:00.0000001Z' AND reg='1') OR (time='1970-01-01T00:00:00.0000002Z' AND reg='2')`
returns empty result set.

It looks similar, but I'm not sure if it is the same issue.
