### ISSUE TITLE
0.12.2 duplicated results for a measurement, possible query or storage issue

### ISSUE THREAD

**Issue by ianlutzeigen** [influxdata/influxdb#6632] opened 2016-05-16 03:44 UTC
### Bug report
Hi All, as requested here a bug report: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/t-Cq2TYngJA/2T0ljku6BQAJ

And with the info repeated:
 There are no tags associated with this measurement, so any re-writes should overwrite the existing point.

I am using tags on a meta data table (measurement) which is unrelated to this measurement.

```
> show tag keys
name: EIGEN_META_DATA
---------------------
tagKey
ITEM_NAME

name: METADATA
--------------
tagKey
tag
```

So using the CliTool:

```
> SELECT * FROM "egtesta-c1" WHERE time > 1451606400000ms AND time < 1451649600000ms ORDER BY time LIMIT 10001
name: egtesta-c1
----------------
time			status	value_EIGAI
1451610000000000000	OK	5.995811366641718
1451610000000000000	OK	5.995811366641718
1451613600000000000	OK	-2.9888508672566587
1451613600000000000	OK	-2.9888508672566587
1451617200000000000	OK	25.077066449318792
1451617200000000000	OK	25.077066449318792
1451620800000000000	OK	31.851006703756894
1451620800000000000	OK	31.851006703756894
1451624400000000000	OK	9.170833664095454
1451624400000000000	OK	9.170833664095454
1451628000000000000	OK	26.800614221779156
1451628000000000000	OK	26.800614221779156
1451631600000000000	OK	5.511991831356866
1451631600000000000	OK	5.511991831356866
1451635200000000000	OK	-21.149676035207094
1451635200000000000	OK	-21.149676035207094
1451638800000000000	OK	-13.184388185819813
1451638800000000000	OK	-13.184388185819813
1451642400000000000	OK	-5.454241981957935
1451642400000000000	OK	-5.454241981957935
1451646000000000000	OK	-28.34448642251391
1451646000000000000	OK	-28.34448642251391
```

Not every measurement is exhibiting this:

```
> SELECT * FROM generatedTag9_ANALOG limit 10
name: generatedTag9_ANALOG
--------------------------
time			status	value_EIGAI
1451602800000000000	OK	91.63689704262038
1451602805000000000	OK	91.62940625834233
1451602810000000000	OK	91.62244134904466
1451602815000000000	OK	91.61600244732924
1451602820000000000	OK	91.61008967578343
1451602825000000000	OK	91.6047031469779
1451602830000000000	OK	91.5998429634644
1451602835000000000	OK	91.59550921777381
```

I am wondering if there is crosstalk between databases created in influx? I have definitely seen measurements show up on the Internal database (not on this version, yet), and disappear again.

I have made a backup of the data files (just copying .influxdb folder (I'm on OSX)) to another location); I will shortly blow this db away  (upgrade to v13?) (duplicates break our api), but I have a backup should you need it for diagnosis.

Cheers!
Ian

**Comment by jsternberg** [comment] 2016-05-16 04:00
If you take a backup, be sure to include any directories under `~/.influxdb` such as the meta directory as they may be useful for loading the data.

**Comment by ianlutzeigen** [comment] 2016-05-16 05:49
yep thats the one I have :)

**Comment by jwilder** [comment] 2016-05-19 04:05
@ianlutzeigen Would you be able to test a nightly that includes #6668?

**Comment by jwilder** [comment] 2016-05-19 04:07
Also, if you have a script to reproduce the duplicates, that would be very helpful.

**Comment by ianlutzeigen** [comment] 2016-05-19 05:24
Sorry, I don't have such a script; I do tend to delete loads of test data and re-write as I go about my business; just the nature of how I am writing code around influx, so I do not have a specific reproducible script. I will keep and eye on it... don't think I am in a position to explicitly test it at this moment.

**Comment by brewneaux** [comment] 2016-05-20 20:48
I am also seeing this behavior, but cannot get it to happen again with test/anonymized data, or without using our proprietary loading script.  heres a sample output though:

`> select * from test_stats order by time desc limit 50
name: test_stats
----------------
time                    field1  field2  field3  field4  id      tag1    tag2
1463776920147478000     139999                          3147478 12      0
1463776920147478000     139999                          3147478 12      0
1463776533147477000     39900                           3147477 8       1
1463776443147476000     34999                           3147476 6       0
1463776360147475000     3995                            3147475 1       0
1463776254147474000     19995                           3147474 1       0
1463776214147473000     2990                            3147473 1       0
1463776209147472000     12995                           3147472 1       0
1463776165147471000     81495                           3147471 1       0
1463775800147470000     28995                           3147470 6       0
1463775695147465000     21490                           3147465 1       0
1463775630147464000     3995                            3147464 1       0
1463775319147463000     174294                          3147463 8       1
1463775290147462000     242900                          3147462 12      0
1463775290147462000     242900                          3147462 12      0
1463775254147461000     99999                           3147461 12      0
1463775254147461000     99999                           3147461 12      0
1463775195147460000     1995                            3147460 1       0
1463775025147459000     166416                          3147459 1       1
1463774988147458000     119800                          3147458 8       0
1463774899147457000     119900                          3147457 12      0
1463774899147457000     119900                          3147457 12      0
1463774823147456000     62995   1       1               3147456 1       0
1463774822147455000     9900    1       1               3147455 1       0
1463774817147454000     26998   1       1               3147454 6       0
1463774778147453000     97183   1       1               3147453 6       0
1463774578147452000     278775                          3147452 1       1
1463774557147451000     69999   1       1               3147451 1       0
1463774433147450000     9999    1       1               3147450 1       0
![screen shot 2016-05-20 at 3 47 48 pm](https://cloud.githubusercontent.com/assets/8001107/15441742/45e03d3a-1ea2-11e6-96ff-74837e02e35e.png)

`

**Comment by brewneaux** [comment] 2016-06-01 16:49
@jwilder, I have a file and steps that will add duplicated results. This requires you to have jq installed, but I figure thats pretty normal.

Basically, what I am doing is dropping and re-creating a database, adding in some data, then proving there are no duplicates with the first SELECT.

Then, we drop the measurement, and add the exact same data back in, again checking the SELECT to see that we have some non-unique random-ints or times.

```
curl -i -X POST http://localhost:8086/query --data-urlencode "q=DROP DATABASE test_data"
curl -i -X POST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE test_data"

curl -X POST curl -i -X POST 'http://localhost:8086/write?db=test_data&precision=u' --data-binary @bad_data.line

curl -sS -GET 'http://localhost:8086/query?db=test_data' --data-urlencode 'q=SELECT randomint FROM "test_data" order by time desc limit 50'  | jq -C '[foreach .results[0].series[0].values[] as $item ([[],[]];  $item[1])]|sort' | uniq -c |  grep -v '^ *1 '


curl -i -X POST http://localhost:8086/query --data-urlencode "db=test_data" --data-urlencode "q=DROP MEASUREMENT test_data"

curl -i -X POST 'http://localhost:8086/write?db=test_data&precision=u' --data-binary @bad_data.line

curl -sS -GET 'http://localhost:8086/query?db=test_data' --data-urlencode 'q=SELECT randomint FROM "test_data" order by time desc limit 50'  | jq -C '[foreach .results[0].series[0].values[] as $item ([[],[]];  $item[1])]|sort' | uniq -c |  grep -v '^ *1 '

curl -sS -GET 'http://localhost:8086/query?db=test_data' --data-urlencode 'q=SELECT randomint FROM "test_data" order by time desc limit 50'  | jq -C '[foreach .results[0].series[0].values[] as $item ([[],[]];  $item[0
[influx_test_case.zip](https://github.com/influxdata/influxdb/files/293927/influx_test_case.zip)

])]|sort' | uniq -c |  grep -v '^ *1 '
```

And attached is a data file.

**Comment by jwilder** [comment] 2016-06-01 17:37
@brewneaux Can you reproduce this with the latest nightlies?

**Comment by brewneaux** [comment] 2016-06-01 19:15
Yes, built from source minutes ago on OSX, I still experience this issue.  However, I'm also finding that it is not EXPLICITLY related to dropping measurements.  I'm have a script that populates a lot of back data, and that also causes the issue on a completely fresh install (deleted the .influxdb folder). Writing about 125k points about as fast as it will take them also causes the issue.

**Comment by brewneaux** [comment] 2016-06-01 19:17
To elaborate, so far I have experienced the problem on 0.12, 0.13, master as of 2016-06-01, and it does NOT happen on 0.9.

**Comment by pga23** [comment] 2016-06-12 22:41
I have got EXACTLY the same issue regularly on InfluxDB 0.13 
installed on Ubuntu Server 16.04 (4GB RAM, 2 CPU)

My tests results below - the same data has been inserted into fife databases:
db1.rp.measurement1 - 263471 data points
db1.rp.measurement2 - 13191 data points

db2.rp.measurement1 - 263471 data points
db2.rp.measurement2 - 13191 data points

db3.rp.measurement1 - 263471 data points
db3.rp.measurement2 - 17034 data points (3843 duplicates)

db4.rp.measurement1 - 263471 data points
db4.rp.measurement2 - 13191 data points

db5.rp.measurement1 - 263471 data points
db5.rp.measurement2 - 26727 data points (13536 duplicates!)

I've made above test many times, ALWAYS with some duplicates.
For double sure I inserted CSV data dump from InfluxDB  into MySQL where I have access full SQL
and I definitely we have duplicates, not separate series using different tag values.

I use `influx -import -path` command on localhost for inserting data from files containing 5000 data rows or less, all data files contains DML section for choosing database and retention policy.
Inserts into all databases are made basically in the same time (during a few minutes) by using two celery workers. Due to other data processing process, CPU usage was quite high (between 50% and 90%)

If required I can provide more information including inserted data files, data dumps etc.

I hope this issue can be solved quickly as many queries starts to be useless when data set
contains duplicates.

**Comment by jwilder** [comment] 2016-06-13 01:34
@pga32 Can you reproduce with 1.0beta?

**Comment by pga23** [comment] 2016-06-13 20:39
I already made similar tests on version 1.0.0-beta1 by using six separate databases.
All measurements was without duplicates!
Additionally I added for deeper tests a few times more data - results was also without duplicates,
but I noticed something suspect:

When I've checked counts of records directly after inserts in 4 of 12 used measurements
I had a slightly different result of count(). 15 minutes later when I made
again the same queries, count() for all measurements was correct and the same in all databases.

**Comment by brewneaux** [comment] 2016-06-20 16:57
I'm still getting this on 1.1.0~n201606070800.

**Comment by brewneaux** [comment] 2016-06-27 19:55
Still occuring on 1.1.0~n201606270800

**Comment by ianlutzeigen** [comment] 2016-06-29 06:01
should we expect the fix for this to be in 13.1 ? I am hanging out for a stable release that does not have this problem. Thanks! :)

**Comment by ianlutzeigen** [comment] 2016-06-29 06:04
apologies the  13.1 I was looking at was telegraph, not influx

**Comment by jwilder** [comment] 2016-07-18 22:56
#7027 may fix this

**Comment by jwilder** [comment] 2016-07-19 02:07
Duplicate of #6946

**Closed by jwilder** 2016-07-19 02:07 UTC
