### ISSUE TITLE
Trailing escape character in measurement name

### ISSUE THREAD

**Issue by TysonJones** [influxdata/influxdb#6154] opened 2016-03-30 01:51 UTC
Through unknown circumstances, there are some measurements in my influx dataase which have a measurement name ending in the escape character '\'.
This should be invalid, yet somehow they exist (as seen in the dev console at port 8083, when querying "SHOW MEASUREMENTS").
For example,
`change in cpu time (Owner\`

I have a suspicion (but not a very strong one) that these may have arisen from sending data with empty tag values. E.g. t`ag1=,tag2=notempty`

Regardless, how can I remove these measurements (all data associated with them) from the database? Trying to grab data under these measurements results in an error relating to the invalid trailing escape character in the query (naturally), which will make their deletion tricky.

(Another suspicion of mine is that the presence of these invalid measurement names is making valid measurement names which are an extension of these incorrectly return nothing. I.e. n`ame prefix \ ` makes access of `name prefix \, suffix ` impossible. But again, a mere suspicion).

Thanks

**Comment by e-dard** [comment] 2016-04-01 11:27
@TysonJones this is a known issue and we're looking to fix the line-protocol spec for `0.13`.

Having said that, what version of Influx are you using? I'm not aware of the bug where a measurement ending in a `\` can exist in the system. Can you show the raw output of the `SHOW MEASUREMENTS` query?

**Comment by TysonJones** [comment] 2016-04-04 07:44
Is there any more information about this issue (the creation of these additional measurements)?
Is it guaranteed all data pushed to a measurement will still be stored there under, albeit also under an extra dodgy measurement?

Regarding the `\`: oops, I was viewing the output in an editor also parsing the escapes. The measurement names do indeed correctly end in `\\`. Thanks!

**Comment by e-dard** [comment] 2016-04-04 09:43
@TysonJones all I can really say for the current status is that you should avoid backslash literal characters in your measurements, tags or fields, and only use backslashes to escape characters such as spaces, equals or double quotes. 

In terms of the future improvement to how backslashes will be handled see #6037

**Comment by e-dard** [comment] 2016-04-04 09:44
@TysonJones I'm going to close this issue as it's a duplicate of #6008 and #5231

**Closed by e-dard** 2016-04-04 09:44 UTC
