### ISSUE TITLE
[feature request] config to control max points sampled per query

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#5323] opened 2016-01-09 00:51 UTC
The motivation is keeping a large query from killing the system with OOM.

I propose a configuration setting that sets a maximum number of points to be sampled per query. Let's say `query-max-points = 1000000` and I run a query that will pull 1.5 million points from disk. The query can't know in advance how many points will be pulled, but once the count hits 1 million it should stop and return an error "too many points requested, please restrict your query to a smaller result set". 

In addition, there should be an override flag that can be passed with queries. Something like `SELECT * FROM /.*/ MAX RETURN 200000000`, which would sample up to 200 million points before throwing an error. `-1` could be passed to represent fetch all points that match regardless (current behavior).

Given the existing reserved words, I think perhaps `READ LIMIT` is a reasonable syntax for the query, although maybe too hard for the parser to handle:

`SELECT * FROM /.*/ READ LIMIT 200000000`

**Comment by mhiller** [comment] 2016-01-11 21:12
+1

**Comment by sarat-k** [comment] 2016-01-13 02:43
+ 1

a must have for bigger databases

**Comment by zstyblik** [comment] 2016-01-13 07:37
@beckettsean I hope there is going to be an easy to understand algorithm or rule of thumb to guess how many datapoints is "safe" before OOM strikes.

**Comment by steverweber** [comment] 2016-01-16 21:00
+1

**Comment by steverweber** [comment] 2016-01-16 21:20
I think influxdb already has LIMIT, however a global config per database for LIMIT might be a good idea.

From my POV a TIMEOUT value would be more helpfull.
max seconds a query should run, before giving up and canceling out.

This would reduce risk of long running , slow query's from eating up cpu and memory resources.

Is the main issue to much data is returned, or the query is taking to long clogging the tubes?

**Comment by zstyblik** [comment] 2016-01-16 21:24
> Is the main issue to much data is returned, or the query is taking to long while clogging the tubes?

As stated on the very first line, the issue is OOM killer.

**Comment by steverweber** [comment] 2016-01-16 21:32
related: https://github.com/influxdata/influxdb/issues/1994

**Comment by steverweber** [comment] 2016-01-16 21:33
@zstyblik not sure how i missed that first line

**Comment by jsternberg** [comment] 2016-04-06 19:26
I don't know if we still want to use the query syntax, but I thin this is implemented with the `max-select-point` option in the `[cluster]` section. It should work as of 0.12.

I'm going to change the milestone and close this issue. Please reopen if I've misunderstood something and we still need to work on this more.

**Closed by jsternberg** 2016-04-06 19:26 UTC
Labels: category/feature request, category/performance, category/queries

**Comment by beckettsean** [comment] 2016-04-07 00:50
@jsternberg for clarification, we now have a config setting for max points sampled per query, but there's no way to override it, correct? If I need to run a query larger than `max-select-point` then I have to edit the config file and bounce the process, yes?

**Comment by jsternberg** [comment] 2016-04-07 00:55
Yes. Do we need it per query too? We can reopen this if we need it per query.

**Comment by beckettsean** [comment] 2016-04-07 01:04
@jsternberg we don't need it, I just need to understand what is and isn't possible. Obviously it's a bummer if an admin needs to bounce the process just to make a long-running query succeed, but we can add more complicated user-permissions-based query specific overrides later.

**Comment by steverweber** [comment] 2016-04-07 01:06
yes please create a new issue for this.
