### ISSUE TITLE
InfluxDB Cloud: Flux query cursor falls at the middle of symbols

### ISSUE THREAD

**Issue by melanchall** [influxdata/influxdb#18159] opened 2020-05-19 16:16 UTC
__Steps to reproduce:__

1. Create dashboard in InfluxDB Cloud
2. Create cell by Flux query (not Query builder)
3. Save dashboard and go to query editor again
4. Place cursor to any symbol in query

__Expected behavior:__
Cursor correctly set before or after clicked symbol.

__Actual behavior:__
Cursor set in the middle of symbol. More than that, rightmost position of the cursor is invalid: See screenshot:

![image](https://user-images.githubusercontent.com/26361185/82350926-9c3cd300-9a04-11ea-822e-8bad8ff8395a.png)

__Environment info:__

* InfluxDB Cloud

**Comment by desa** [comment] 2020-05-21 23:34
@melanchall which browser are you using?

**Comment by melanchall** [comment] 2020-05-22 13:15
Google Chrome
Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by melanchall** [comment] 2020-05-28 12:33
Any news on the issue? Bug still exist and very annoying. Unfortunately I can't figure out exact steps to reproduce it. It happens from time to time.

**Comment by desa** [comment] 2020-05-28 21:00
@melanchall I've bumped this in priority.

**Comment by desa** [comment] 2020-05-29 22:02
duplicate of https://github.com/influxdata/influxdb/issues/18026 will track the work for this issue there

**Closed by desa** 2020-05-29 22:02 UTC
Labels: kind/bug, severity/sev-3, team/monitoring
