### ISSUE TITLE
Heavy Virtual Memory usage

### ISSUE THREAD

**Issue by mehar** [influxdata/influxdb#6531] opened 2016-05-02 08:16 UTC
__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
InfluxDB Version: 0.12, 0.11, 0.10
Operating System: Ubuntu 14.04 LTS

__Expected behavior:__ 
Virtual Memory usage should not keep increasing

__Actual behavior:__ 
Virtual Memory keeps growing up to 32GB, killed by kernel afterwards

__Additional info:__ 
Default config

Here is the /var/log/messages snippet

Apr 26 08:08:31  kernel: [7359033.064569] Out of memory: Kill process 25444 (influxd) score 867 or sacrifice child
Apr 26 08:08:31  kernel: [7359033.064629] Killed process 25444 (influxd) total-vm:31725612kB, anon-rss:4889636kB, file-rss:0kB

![influx_diagnostics](https://cloud.githubusercontent.com/assets/261475/14950016/29072aaa-106c-11e6-976b-952ddcd477c1.JPG)

![influx_stats](https://cloud.githubusercontent.com/assets/261475/14950022/31c9646e-106c-11e6-9333-f65dfc602c4f.png)

**Comment by whitelynx** [comment] 2016-05-02 15:59
Possible duplicate of #6243?

**Comment by Joe29** [comment] 2016-05-03 08:20
+1
I have the same setup and the server is being killed by the kernel as well. I can start up influx and it works fine for about 10 minutes before crashing again. Using 32gb memory with 8cpu on ec2 - plenty of IOPS on the drive. Let me know if there is any additional information that I might be able to provide to help solve the issue. I tried increasing the memory settings in the config, but that didn't seem to help.

**Comment by mehar** [comment] 2016-05-03 15:37
Does anyone have an idea on why is it happening, i can share any other details if needed.

**Comment by jwilder** [comment] 2016-05-03 17:21
@mehar @Joe29 When the heap is growing or close to maxing out, can you run the following and the files?

```
curl -o heap.txt http://localhost:8086/debug/pprof/heap?debug=1
curl -o goroutine.txt http://localhost:8086/debug/pprof/goroutine?debug=1
```

**Comment by fkruta** [comment] 2016-05-03 20:26
Saw the pb also on a server with 64Gb 2x4 cores 3.3G Xeon on Ubuntu 12.04
Pretty scary as I was testing with relatively small data-sets. 
Let me know how to help and to test workaround. 
I attach the files here by the files you requested. 
[heap.txt.gz](https://github.com/influxdata/influxdb/files/247691/heap.txt.gz)
[goroutine.txt](https://github.com/influxdata/influxdb/files/247692/goroutine.txt)

**Comment by Joe29** [comment] 2016-05-03 21:54
Here are the files, with influx using ~24gb
Thanks
[goroutine.txt](https://github.com/influxdata/influxdb/files/247832/goroutine.txt)
[heap.txt](https://github.com/influxdata/influxdb/files/247833/heap.txt)

**Comment by jwilder** [comment] 2016-05-03 22:00
@Joe29 It looks like you have a lot of open HTTP connections.  What is writing to your server and can you check if it's is closing connections?

**Comment by Joe29** [comment] 2016-05-03 22:34
I'm using: 
https://github.com/paulgoldbaum/scala-influxdb-client
which in turn looks like it's using:
https://github.com/AsyncHttpClient/async-http-client

Maybe for the most heavy write functions I'll try switching to UDP? Let me know your thoughts. A lost record here or there is fine for my use case.. I'll update this evening (PDT) as to whether or not that helped.

Thanks

**Comment by Joe29** [comment] 2016-05-04 07:21
@jwilder Switching to UDP did the trick. Thanks again.

**Comment by mehar** [comment] 2016-05-05 06:03
[heap.txt](https://github.com/influxdata/influxdb/files/249991/heap.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/249994/goroutine.txt)

This is with influx using 10G of virutal memory and 5G of resident memory, here is the snip from htop
![influx_htop](https://cloud.githubusercontent.com/assets/261475/15037083/3b1b2a34-12b5-11e6-8279-3157de979e83.JPG)

**Comment by jwilder** [comment] 2016-05-05 14:55
@mehar What kind of storage are you using?  SSD? Spinning disk?  It looks like a lot of HTTP connections are open with many blocking on some calls writing and fsyncing the `WAL`.  You might want to monitor you disks and see if they are saturated.

**Comment by mehar** [comment] 2016-05-06 08:28
@jwilder , We don't have an SSD, let me know if the below stats could be of any use
root@FD-DEV-235:~# hdparm -Tt /dev/mapper/sda

/dev/mapper/sda:
 Timing cached reads:   9792 MB in  2.00 seconds = 4899.17 MB/sec
 Timing buffered disk reads: 118 MB in  3.04 seconds =  38.85 MB/sec
root@FD-DEV-235:~# dd if=/dev/zero of=/tmp/output bs=8k count=10k; rm -f /tmp/output
10240+0 records in
10240+0 records out
83886080 bytes (84 MB) copied, 0.103182 s, 813 MB/s


root@FD-DEV-235:~# hdparm -Tt /dev/mapper/sda

/dev/mapper/sda:
 Timing cached reads:   10280 MB in  2.00 seconds = 5143.45 MB/sec
 Timing buffered disk reads:  94 MB in  3.06 seconds =  30.71 MB/sec

**Comment by jwilder** [comment] 2016-05-06 14:21
@mehar Can you run `iostat -xd 1 30` and capture the output when your heap is growing?

**Comment by mehar** [comment] 2016-05-06 16:38
@jwilder Thanks for following up, please find the iostat output below

root@FD-DEV-235:/# iostat -xd 1 30
Linux 3.19.0-25-generic (FD-DEV-235)    Friday 06 May 2016      _x86_64_        (4 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda              12.69   105.89    4.77   82.98    89.52   915.56    22.91     2.92   33.32   22.12   33.96   8.34  73.21
dm-0              0.00     0.00    0.64  161.86    22.17   807.32    10.21     2.47   15.23   43.38   15.12   4.45  72.27
dm-1              0.00     0.00   16.81   27.06    67.26   108.24     8.00    21.98  500.93   18.67  800.60   0.63   2.74

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   146.00    0.00  120.00     0.00  1096.00    18.27     1.04    8.70    0.00    8.70   8.17  98.00
dm-0              0.00     0.00    0.00  267.00     0.00  1080.00     8.09     2.52    9.51    0.00    9.51   3.67  98.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   167.00    0.00  133.00     0.00  1220.00    18.35     0.98    7.40    0.00    7.40   7.31  97.20
dm-0              0.00     0.00    0.00  299.00     0.00  1216.00     8.13     2.36    7.92    0.00    7.92   3.26  97.60
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   168.00    0.00  119.00     0.00  1144.00    19.23     0.95    8.00    0.00    8.00   8.00  95.20
dm-0              0.00     0.00    0.00  287.00     0.00  1152.00     8.03     2.50    8.70    0.00    8.70   3.32  95.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   198.00    0.00  152.00     0.00  1420.00    18.68     0.98    6.45    0.00    6.45   6.47  98.40
dm-0              0.00     0.00    0.00  350.00     0.00  1412.00     8.07     2.13    6.08    0.00    6.08   2.81  98.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   174.00    0.00  123.00     0.00  1408.00    22.89     1.17    9.53    0.00    9.53   8.07  99.20
dm-0              0.00     0.00    0.00  297.00     0.00  1428.00     9.62     2.99   10.07    0.00   10.07   3.34  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   154.00    0.00  113.00     0.00  1092.00    19.33     0.97    8.57    0.00    8.57   8.57  96.80
dm-0              0.00     0.00    0.00  267.00     0.00  1076.00     8.06     2.73   10.22    0.00   10.22   3.63  96.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   150.00    0.00  108.00     0.00  1040.00    19.26     0.94    8.74    0.00    8.74   8.74  94.40
dm-0              0.00     0.00    0.00  258.00     0.00  1036.00     8.03     2.50    9.69    0.00    9.69   3.69  95.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   160.00    0.00  114.00     0.00  1104.00    19.37     0.97    8.49    0.00    8.49   8.49  96.80
dm-0              0.00     0.00    0.00  274.00     0.00  1104.00     8.06     2.97   10.83    0.00   10.83   3.53  96.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   170.00    0.00  121.00     0.00  1188.00    19.64     1.00    8.26    0.00    8.26   7.93  96.00
dm-0              0.00     0.00    0.00  291.00     0.00  1188.00     8.16     2.60    8.93    0.00    8.93   3.30  96.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   160.00    0.00  116.00     0.00  1112.00    19.17     0.97    8.38    0.00    8.38   8.34  96.80
dm-0              0.00     0.00    0.00  276.00     0.00  1112.00     8.06     2.55    9.26    0.00    9.26   3.51  96.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   139.00    0.00  102.00     0.00   968.00    18.98     0.97    9.53    0.00    9.53   9.53  97.20
dm-0              0.00     0.00    0.00  241.00     0.00   968.00     8.03     2.60   10.77    0.00   10.77   4.03  97.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   161.00    0.00  129.00     0.00  1168.00    18.11     0.99    7.66    0.00    7.66   7.69  99.20
dm-0              0.00     0.00    0.00  290.00     0.00  1168.00     8.06     2.41    8.29    0.00    8.29   3.42  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   160.00    0.00  131.00     0.00  1176.00    17.95     0.96    7.33    0.00    7.33   7.30  95.60
dm-0              0.00     0.00    0.00  296.00     0.00  1196.00     8.08     2.03    6.88    0.00    6.88   3.24  96.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00    85.00    0.00   62.00     0.00   592.00    19.10     0.68   10.90    0.00   10.90  11.03  68.40
dm-0              0.00     0.00    0.00  142.00     0.00   572.00     8.06     1.60   11.18    0.00   11.18   4.82  68.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   151.00    0.00  116.00     0.00  1912.00    32.97     1.62   13.93    0.00   13.93   8.38  97.20
dm-0              0.00     0.00    0.00  267.00     0.00  1912.00    14.32     3.34   12.51    0.00   12.51   3.64  97.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   171.00    0.00  136.00     0.00  1228.00    18.06     0.98    7.26    0.00    7.26   7.24  98.40
dm-0              0.00     0.00    0.00  307.00     0.00  1236.00     8.05     2.30    7.48    0.00    7.48   3.21  98.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   131.00    0.00  119.00     0.00  1016.00    17.08     0.98    8.13    0.00    8.13   8.24  98.00
dm-0              0.00     0.00    0.00  250.00     0.00  1008.00     8.06     1.95    7.79    0.00    7.79   3.92  98.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   133.00    0.00  106.00     0.00   940.00    17.74     0.98    9.28    0.00    9.28   9.21  97.60
dm-0              0.00     0.00    0.00  239.00     0.00   964.00     8.07     2.34    9.64    0.00    9.64   4.08  97.60
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   137.00    0.00  113.00     0.00  1028.00    18.19     0.97    8.67    0.00    8.67   8.60  97.20
dm-0              0.00     0.00    0.00  249.00     0.00  1000.00     8.03     2.37    9.75    0.00    9.75   3.92  97.60
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   126.00    0.00  117.00     0.00   980.00    16.75     3.23   27.56    0.00   27.56   8.48  99.20
dm-0              0.00     0.00    0.00  244.00     0.00   984.00     8.07     5.01   20.51    0.00   20.51   4.07  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   157.00    0.00  123.00     0.00  1128.00    18.34     0.96    7.87    0.00    7.87   7.84  96.40
dm-0              0.00     0.00    0.00  280.00     0.00  1128.00     8.06     2.36    8.43    0.00    8.43   3.44  96.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   178.00    0.00  133.00     0.00  1232.00    18.53     0.99    7.46    0.00    7.46   7.46  99.20
dm-0              0.00     0.00    0.00  311.00     0.00  1252.00     8.05     2.58    8.23    0.00    8.23   3.19  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   175.00    0.00  126.00     0.00  1212.00    19.24     0.98    7.84    0.00    7.84   7.81  98.40
dm-0              0.00     0.00    0.00  301.00     0.00  1212.00     8.05     2.62    8.78    0.00    8.78   3.27  98.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   157.00    0.00  106.00     0.00  1080.00    20.38     0.99    9.36    0.00    9.36   9.36  99.20
dm-0              0.00     0.00    0.00  263.00     0.00  1060.00     8.06     2.71   10.31    0.00   10.31   3.77  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   146.00    0.00  107.00     0.00  1688.00    31.55     1.46   13.64    0.00   13.64   9.27  99.20
dm-0              0.00     0.00    0.00  253.00     0.00  1688.00    13.34     3.49   13.79    0.00   13.79   3.92  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   149.00    0.00  123.00     0.00  1100.00    17.89     1.26   10.21    0.00   10.21   8.10  99.60
dm-0              0.00     0.00    0.00  272.00     0.00  1104.00     8.12     3.38   12.40    0.00   12.40   3.66  99.60
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   175.00    0.00  127.00     0.00  1212.00    19.09     0.98    7.81    0.00    7.81   7.75  98.40
dm-0              0.00     0.00    0.00  302.00     0.00  1228.00     8.13     2.51    8.34    0.00    8.34   3.26  98.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   150.00    0.00  118.00     0.00  1100.00    18.64     0.96    8.10    0.00    8.10   8.14  96.00
dm-0              0.00     0.00    0.00  268.00     0.00  1080.00     8.06     2.40    8.93    0.00    8.93   3.58  96.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   130.00    0.00  106.00     0.00   948.00    17.89     0.99    9.32    0.00    9.32   9.32  98.80
dm-0              0.00     0.00    0.00  236.00     0.00   948.00     8.03     2.59   10.97    0.00   10.97   4.19  98.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

**Comment by mehar** [comment] 2016-05-06 16:40
iostat out is not readable in the previous comment, attached file with the same
[influx_iostat.txt](https://github.com/influxdata/influxdb/files/252674/influx_iostat.txt)

**Comment by jwilder** [comment] 2016-05-06 17:16
@mehar It looks lie your disks can't keep up with the workload as can be seen from some of these samples:

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   126.00    0.00  117.00     0.00   980.00    16.75     3.23   27.56    0.00   27.56   8.48  99.20
dm-0              0.00     0.00    0.00  244.00     0.00   984.00     8.07     5.01   20.51    0.00   20.51   4.07  99.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

`% util` is close to 100%.  Your writes are taking ~27ms and there are about 3 requests queued up (in this sample).  It looks like your hard drive is maxing out somewhere between 100-130 IOPS which is causing the WAL fsyncs to block and writes to pile up.  That's a good sign that your disk does not have enough IOPS for your workload.

With spinning disks, you will probably need multiple drives configured in a RAID setup to get enough IOPS.  I'd recommend switching to SSD if possible as well.

**Closed by jwilder** 2016-05-06 17:16 UTC
Labels: category/performance

**Comment by toddboom** [comment] 2016-05-06 17:28
@mehar We did some internal tests with an 8-disk RAID5 array on 15kRPM disks and were seeing ~1800 IOPS, which gives decent performance. for a setup receiving a high-volume of writes, I'd recommend a minimum of about 1000 IOPS.

**Comment by mehar** [comment] 2016-05-07 02:28
@jwilder  @toddboom Thanks for all the information

Now i refactored the code to use a connection pool to connect to influx (20 concurrent connections only), still i see the Virtual Memory growing though not that rapidly (Virtual memory grown to around 2.5G in an hours time while all the connections are continuously writing), Is this expected?
