### ISSUE TITLE
SHOW TAG KEYS now extremely slow, but SHOW TAG VALUES hugely improved

### ISSUE THREAD

**Issue by daveselan** [influxdata/influxdb#8825] opened 2017-09-14 13:22 UTC
Since upgrading from the June nightly builds, SHOW TAG KEYS has become 1000x slower on our larger databases.

Interestingly however SHOW TAG VALUES has sped up by the same amount!  Which is a big win for Grafana dashboards. Thanks.

**Slow TAG KEYS performance on latest database**

```
% influx --version
InfluxDB shell version: 1.4.0~n201709070800

%  time influx -database job_data -execute 'SHOW TAG KEYS FROM "job_stats"'
name: job_stats
tagKey
------
department
group
type
pool
name
number
host
user
version

**real	1m23.075s**
user	0m0.000s
sys	0m0.012s
```

**Fast and expected performance on older databases**

```
% influx --version
InfluxDB shell version: 1.4.0~n201706140800

%  time influx -database job_data -execute 'SHOW TAG KEYS FROM "job_stats"'
name: job_stats
tagKey
------
department
group
type
pool
name
number
host
user
version

**real	0m0.013s**
user	0m0.008s
sys	0m0.000s
```

**Comment by e-dard** [comment] 2017-09-15 10:16
Hi @daveselan `SHOW TAG VALUES` sped up because of the performance work we did here: https://github.com/influxdata/influxdb/pull/8660

Can you just clarify that you're comparing two nightly versions? The _older_ nightly is quite far back; we've had several `1.3.x` patch releases since then. Do you think you could run your test on the latest `1.3.5` release?

Also, could you give an overview of the number of shards you have and also the rough cardinality of your database?

**Comment by e-dard** [comment] 2017-09-26 10:53
@daveselan do you have any more information on this? Did you try the `1.3.5` release? I'm keen to keep on top of any of these regressions but if I don't hear anything in the next few days I'll close out the issue. Cheers.

**Comment by e-dard** [comment] 2017-10-03 10:21
Closing as no further information provided, and the regression has not been reported elsewhere.

**Closed by e-dard** 2017-10-03 10:21 UTC
Labels: area/storage, performance
