### ISSUE TITLE
Save as variable not populating query

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#14074] opened 2019-06-06 17:06 UTC
happening in cloud2

![Kapture 2019-06-06 at 10 05 54](https://user-images.githubusercontent.com/4805997/59051900-c53f7480-8842-11e9-969c-992631a7a698.gif)

**Comment by sanderson** [comment] 2019-06-06 17:33
Duplicate of #13682

**Closed** 2019-06-12 16:32 UTC
Labels: kind/bug, team/data
