### ISSUE TITLE
[0.9.5-nightly] Drop server doesn't succeed

### ISSUE THREAD

**Issue by panda87** [influxdata/influxdb#4649] opened 2015-11-03 20:58 UTC
Im using the latest nightly build of ver 0.9.5 after upgraded from 0.9.4.2.
The main reason I decided to use this version is because of the ability to drop servers (raft and non raft).
I want to upgrade the machines without losing data.

So first I added the 4th server (non raft) to the cluster, and I altered the RETENTION POLICY to REPLICATION 4, this doesn't help ( the new node didn't receive replication data) so i created new RETENTION POLICY with REPLICATION 4 (DEFAULT), this created new shard file (4 replicates) but since it started from the new shard, I couldn't see the old data (unless i'll change back to the old retention).
I also tried to alter the replication factor from 4 to 2 but all the cluster (4 nodes) still got the replicated data.

Then I tried to DROP the new server but got this error `Server returned error: shard not replicated`.

What should I need to do in order to drop one server and add another one instead without losing data?

PS - After create the new retention policy, when I run `SHOW SHARDS` I get `Query returned no results!` - so I even don't know the replication status.

Thanks!

**Comment by otoolep** [comment] 2015-11-04 00:22
@corylanou

**Comment by corylanou** [comment] 2015-11-04 01:16
This is working as intended.  It might be an underlying bug in the shard creation, but the drop server saw that somewhere a shard wasn't replicated based on the meta store, so it stops.  To confirm this, we would need to see what the shards are in terms of what the meta store thinks.  You can always use `DROP SERVER foo FORCE` to continue, but in normal circumstances this would risk data loss.  For this situation, I suspect it would be fine to use `FORCE`

As for altering the RP to a replication of 4, that won't take affect until the next interval of shard creation I believe.  In the future we will be adding services that will backwards populate retention policies when the replication factor changes.

@otoolep does that sound correct?

**Comment by otoolep** [comment] 2015-11-04 01:19
Correct, the new RP replication won't take effect immediately.

@panda87 -- can we see the output of `SHOW SHARDS`?

**Comment by panda87** [comment] 2015-11-04 13:14
Unfortunately as I said, running `SHOW SHARDS` returns `Query returned no results!`.
Do you what should I do to in to see the current shards status?

In addition, I tried to DROP FORCE one of the nodes and add new one instead. It seems the new node look for the dropped node and when adding it, it doesn't find any Leader Raft.

When I run `show servers` on the old (2) nodes I can see the new node, and also their peers.json has changed accordingly but when I run `show servers` I can see 4 nodes (2 old, dropped node, the new one) without Leader.

Any ideas?

**Comment by otoolep** [comment] 2015-11-04 16:12
Can you please show us the output of `SHOW SHARDS` as executed at the CLI? You are using the admin tool, which can hide details.

```
$ ./influx 
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
> show shards
> 
```

**Comment by otoolep** [comment] 2015-11-04 16:12
Same with `SHOW SERVERS`. Please show us the output of this, with the CLI connected to each node. Please run `SHOW SHARDS` when connected to each node as well.

**Comment by panda87** [comment] 2015-11-04 17:02
Node01
```bash
Connected to http://localhost:8086 version 0.9.5-nightly-437f80a
InfluxDB shell 0.9.5-nightly-437f80a
> show shards
name: collectd_metrics_qa
-------------------------
id	start_time	end_time	expiry_time	owners


name: _internal
---------------
id	start_time		end_time		expiry_time		owners
65	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	2
66	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	
67	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	1
68	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	1
69	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	2
70	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	
71	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	
72	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	1
73	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	2
81	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	2
82	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	
83	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	1
84	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	
85	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	1
86	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2
88	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	2
89	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	
90	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	
91	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	1
94	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	2
95	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	
96	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	
97	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	1
106	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	
107	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	
108	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	1
109	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	2


name: collectd_metrics_prod
---------------------------
id	start_time		end_time		expiry_time		owners
101	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2016-11-08T00:00:00Z	1,2


name: test
--------
id	start_time		end_time		expiry_time		owners
98	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2016-11-08T00:00:00Z	1,2


name: collectd_metrics_dev
--------------------------
id	start_time	end_time	expiry_time	owners
```
Node02
```bash
Connected to http://localhost:8086 version 0.9.5-nightly-437f80a
InfluxDB shell 0.9.5-nightly-437f80a
> show shards
name: collectd_metrics_qa
-------------------------
id	start_time	end_time	expiry_time	owners


name: _internal
---------------
id	start_time		end_time		expiry_time		owners
65	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	2
66	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	
67	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	1
68	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	1
69	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	2
70	2015-10-29T00:00:00Z	2015-10-30T00:00:00Z	2015-11-06T00:00:00Z	
71	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	
72	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	1
73	2015-10-30T00:00:00Z	2015-10-31T00:00:00Z	2015-11-07T00:00:00Z	2
81	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	2
82	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	
83	2015-10-31T00:00:00Z	2015-11-01T00:00:00Z	2015-11-08T00:00:00Z	1
84	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	
85	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	1
86	2015-11-01T00:00:00Z	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2
88	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	2
89	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	
90	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	
91	2015-11-02T00:00:00Z	2015-11-03T00:00:00Z	2015-11-10T00:00:00Z	1
94	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	2
95	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	
96	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	
97	2015-11-03T00:00:00Z	2015-11-04T00:00:00Z	2015-11-11T00:00:00Z	1
106	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	
107	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	
108	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	1
109	2015-11-04T00:00:00Z	2015-11-05T00:00:00Z	2015-11-12T00:00:00Z	2


name: collectd_metrics_prod
---------------------------
id	start_time		end_time		expiry_time		owners
101	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2016-11-08T00:00:00Z	1,2


name: test
--------
id	start_time		end_time		expiry_time		owners
98	2015-11-02T00:00:00Z	2015-11-09T00:00:00Z	2016-11-08T00:00:00Z	1,2


name: collectd_metrics_dev
--------------------------
id	start_time	end_time	expiry_time	owners
```

**Comment by otoolep** [comment] 2015-11-04 17:06
Hmmm.

Your system is not happy, since there are many shards in existence that have not been assigned to any nodes. We can dig into this, but you are pushing clustering which is only in alpha state, and you may be hitting bugs we have yet to solve.

Because clustering is only alpha-quality, we have not tested much beyond 3 nodes. If you want a stable system I suggest you restrict your clusters to this size.

**Comment by otoolep** [comment] 2015-11-04 17:07
We hope to implement `DROP SHARD` soon which will help fix up this system but that feature is a few days away at best, perhaps more.

**Comment by otoolep** [comment] 2015-11-04 18:15
If you can come with a precise set of steps that puts your cluster in this state, I would be interested in looking into this.

**Comment by corylanou** [comment] 2015-11-04 18:17
When you issued the drop server, was the node you were dropping already shut down?  That is our current recommended approach, but I have tested both ways and I haven't seen it fail.  I would also be interested if you can repeat the steps that recreate the situation.

**Comment by panda87** [comment] 2015-11-05 06:49
@corylanou No it was not shut down yet at this time.
The steps are the following:
1. Added new node, the 4h, and changed the RP replication to 4. (eventually after that I had 4 replicated instances - of course it took time until it created the new shards).
2. Drop the 3rd node, when I had a problem to do that I used the FORCE command.
3. Then I reduce the replication factor to 3.
4. Tried to add the 4th server to the raft, but it looked for the 3rd node, and in the peers.json file of the new node it, the list was only this hostname, and in the others it was with this node too.
The log says its looking for the 3rd node and I got timeout for leader election, in the other nodes I could see who is the leader.

**Comment by corylanou** [comment] 2015-11-05 13:39
Ok, I think I understand.  You can currently drop a node that is a raft server, but adding a node after that to become raft is a somewhat manual process.  I'm currently finishing out the code that will allow for bringing a raft node back automatically just by adding a new node.  I should have that committed in a day or so.  Let's try that same process once that code is committed.  I suspect it should solve the problem.

**Comment by jsternberg** [comment] 2016-05-18 02:12
Closing this as clustering has been removed from the open source version and `DROP SERVER` has also been removed.

**Closed by jsternberg** 2016-05-18 02:12 UTC
Labels: category/clustering
