### ISSUE TITLE
Curl write old points works in influx 1.2.0 but does not work in 1.2.2 fails silently with no errors

### ISSUE THREAD

**Issue by anguianoa** [influxdata/influxdb#8369] opened 2017-05-08 18:31 UTC
Operating system: ubuntu 14.04
Version influx version 1.2.2

Create file with one endpoint in it called 1.influx, make sure to have an extra line to satisfied the \n requirement.

mymes,id=8f015fbf3258,serverID=eb1578cfb735,component=site,status=COMPLETED localTime=1484327700274i,jobRunTime=0i 1484327700274000000

make this curl call to influx 1.2.2
curl -i -XPOST http://localhost:8086/write?db=mydb --data-binary @1.influx

Expected: Point to be written
Actual: No point written, no errors in log

works in 1.2.0
master b7bb7e8359642b6e071735b50ae41f5eb343fd42 1.2.0

doesn't work 1.2.2
master 1bcf3ae74c6b9c4897dab68d513d056277eb24f7 1.2.2

**Comment by jsternberg** [comment] 2017-05-08 18:55
I'm unable to reproduce this. Can you give me the full procedure you used?

I installed tag v1.2.0. I created a database and wrote the point with curl. Verified the point was there. Installed tag v1.2.2. Dropped the old database and created a new one. Used the same curl command and verified the point was there in the same way.

**Comment by anguianoa** [comment] 2017-05-10 11:10
hmm....

The reason I found it was that I had 5 months of data I was inserting and when I was looking at the data in influx about 20 days where missing.  I did not drop the database.  Also, the 1.2.2 was an upgrade starting from 1.x

**Comment by jsternberg** [comment] 2017-05-10 17:27
If you are able to give me more information, I would love to look at it. But without more information, I can't find a way to look into this more. If you need further help debugging to figure out if it is user error or a bug in the database, someone on our community website might be able to help you: https://community.influxdata.com. If you have more information, please comment again and I'll reopen this. Until then, I'm going to close it due to having no reproducer.

**Closed by jsternberg** 2017-05-10 17:27 UTC
