### ISSUE TITLE
Cannot change "X column" when creating a scatter plot in Influx 2.0

### ISSUE THREAD

**Issue by jackdry** [influxdata/influxdb#18981] opened 2020-07-17 12:52 UTC
**Steps to reproduce:**

1. Run InfluxDB 2.0 docker container.
```
docker run --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-beta
```
2. Write points using CLI tool.
```
influx write -b myBucket -o myOrg -t myToken "mem a=2,b=4"
influx write -b myBucket -o myOrg -t myToken "mem a=4,b=8"
```
3. Go to UI and try to create a scatter plot of a vs b.

![image](https://user-images.githubusercontent.com/32617639/87788270-fdcac380-c834-11ea-98c4-bb0cb89135c4.png)

**Expected behavior:**
- I expected that I would be able to change "X column" to b.

**Actual behavior:**
- I couldn't change the "X column" to b.

**Environment info:**
- System info: Linux 5.3.0-62-generic x86_64
- InfluxDB version: 2.0

**Comment by russorat** [comment] 2020-07-24 19:14
I believe this might have been fixed in  https://github.com/influxdata/influxdb/pull/19044

@zoesteinkamp can you confirm?

**Comment by jackdry** [comment] 2020-07-25 19:24
Thanks for your reply @russorat. So is the docker image not up-to-date? Is there an image I could use where this is fixed?

**Comment by russorat** [comment] 2020-07-27 15:44
It should be in the nightly but i haven't confirmed: `docker pull quay.io/influxdb/influx:nightly`

**Comment by zoesteinkamp** [comment] 2020-07-27 16:51
Russ, I would expect this to be fixed, but let me know if it is not fixed by that PR

**Comment by desa** [comment] 2020-07-31 19:30
Link https://github.com/influxdata/influxdb/issues/18884#issuecomment-663660456

**Comment by desa** [comment] 2020-07-31 19:31
WHEN the user selects scatter plot
THEN the x-axis should represent the domain of the column specified.

**Comment by sjwang90** [comment] 2020-08-24 17:44
Here's some sample data in LP and the Flux query to turn it into a non-timeseries table. Let me know if it's easier to just include a CSV table. 

Sample data:

```
> mlb_standings,League=AL,Name=Twins,host=MBP15-SWANG.local AwayLosses=7,AwayWins=7,City="Minnesota",DayLosses=3,DayWins=6,DivisionLosses=7,DivisionWins=10,GamesBehind=0,HomeLosses=3,HomeWins=12,Key="MIN",LastTenGamesLosses=3,LastTenGamesWins=7,Losses=10,NightLosses=7,NightWins=13,Percentage=0.6551724137931034,RunsAgainst=100,RunsScored=140,Season=2020,SeasonType=1,TeamID=20,WildCardGamesBehind=0,Wins=19 1598290120000000000
> mlb_standings,League=AL,Name=Indians,host=MBP15-SWANG.local AwayLosses=5,AwayWins=10,City="Cleveland",DayLosses=2,DayWins=5,DivisionLosses=8,DivisionWins=11,GamesBehind=1.5,HomeLosses=6,HomeWins=7,Key="CLE",LastTenGamesLosses=3,LastTenGamesWins=7,Losses=11,NightLosses=9,NightWins=12,Percentage=0.6071428571428571,RunsAgainst=84,RunsScored=112,Season=2020,SeasonType=1,TeamID=10,WildCardGamesBehind=0,Wins=17 1598290120000000000
> mlb_standings,League=AL,Name=White\ Sox,host=MBP15-SWANG.local AwayLosses=4,AwayWins=10,City="Chicago",DayLosses=5,DayWins=5,DivisionLosses=7,DivisionWins=12,GamesBehind=2,HomeLosses=8,HomeWins=7,Key="CHW",LastTenGamesLosses=3,LastTenGamesWins=7,Losses=12,NightLosses=7,NightWins=12,Percentage=0.5862068965517241,RunsAgainst=115,RunsScored=145,Season=2020,SeasonType=1,TeamID=16,WildCardGamesBehind=0.5,Wins=17 1598290120000000000
> mlb_standings,League=AL,Name=Tigers,host=MBP15-SWANG.local AwayLosses=6,AwayWins=7,City="Detroit",DayLosses=4,DayWins=4,DivisionLosses=12,DivisionWins=5,GamesBehind=6.5,HomeLosses=9,HomeWins=4,Key="DET",LastTenGamesLosses=8,LastTenGamesWins=2,Losses=15,NightLosses=11,NightWins=7,Percentage=0.4230769230769231,RunsAgainst=151,RunsScored=120,Season=2020,SeasonType=1,TeamID=17,WildCardGamesBehind=5,Wins=11 1598290120000000000
> mlb_standings,League=AL,Name=Royals,host=MBP15-SWANG.local AwayLosses=10,AwayWins=5,City="Kansas City",DayLosses=5,DayWins=2,DivisionLosses=12,DivisionWins=8,GamesBehind=7.5,HomeLosses=7,HomeWins=6,Key="KC",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=17,NightLosses=12,NightWins=9,Percentage=0.39285714285714285,RunsAgainst=122,RunsScored=110,Season=2020,SeasonType=1,TeamID=5,WildCardGamesBehind=6,Wins=11 1598290120000000000
> mlb_standings,League=AL,Name=Rays,host=MBP15-SWANG.local AwayLosses=6,AwayWins=9,City="Tampa Bay",DayLosses=2,DayWins=9,DivisionLosses=8,DivisionWins=17,GamesBehind=0,HomeLosses=4,HomeWins=10,Key="TB",LastTenGamesLosses=2,LastTenGamesWins=8,Losses=10,NightLosses=8,NightWins=10,Percentage=0.6551724137931034,RunsAgainst=126,RunsScored=153,Season=2020,SeasonType=1,TeamID=11,WildCardGamesBehind=0,Wins=19 1598290120000000000
> mlb_standings,League=AL,Name=Yankees,host=MBP15-SWANG.local AwayLosses=6,AwayWins=6,City="New York",DayLosses=3,DayWins=3,DivisionLosses=6,DivisionWins=10,GamesBehind=1,HomeLosses=3,HomeWins=10,Key="NYY",LastTenGamesLosses=4,LastTenGamesWins=6,Losses=9,NightLosses=6,NightWins=13,Percentage=0.64,RunsAgainst=107,RunsScored=135,Season=2020,SeasonType=1,TeamID=29,WildCardGamesBehind=-0.5,Wins=16 1598290120000000000
> mlb_standings,League=AL,Name=Blue\ Jays,host=MBP15-SWANG.local AwayLosses=10,AwayWins=9,City="Toronto",DayLosses=8,DayWins=2,DivisionLosses=8,DivisionWins=7,GamesBehind=4.5,HomeLosses=3,HomeWins=4,Key="TOR",LastTenGamesLosses=4,LastTenGamesWins=6,Losses=13,NightLosses=5,NightWins=11,Percentage=0.5,RunsAgainst=117,RunsScored=117,Season=2020,SeasonType=1,TeamID=3,WildCardGamesBehind=3,Wins=13 1598290120000000000
> mlb_standings,League=AL,Name=Orioles,host=MBP15-SWANG.local AwayLosses=1,AwayWins=8,City="Baltimore",DayLosses=3,DayWins=5,DivisionLosses=8,DivisionWins=7,GamesBehind=4.5,HomeLosses=13,HomeWins=6,Key="BAL",LastTenGamesLosses=7,LastTenGamesWins=3,Losses=14,NightLosses=11,NightWins=9,Percentage=0.5,RunsAgainst=148,RunsScored=139,Season=2020,SeasonType=1,TeamID=19,WildCardGamesBehind=3,Wins=14 1598290120000000000
> mlb_standings,League=AL,Name=Red\ Sox,host=MBP15-SWANG.local AwayLosses=10,AwayWins=5,City="Boston",DayLosses=4,DayWins=2,DivisionLosses=17,DivisionWins=6,GamesBehind=10,HomeLosses=10,HomeWins=4,Key="BOS",LastTenGamesLosses=7,LastTenGamesWins=3,Losses=20,NightLosses=16,NightWins=7,Percentage=0.3103448275862069,RunsAgainst=175,RunsScored=133,Season=2020,SeasonType=1,TeamID=25,WildCardGamesBehind=8.5,Wins=9 1598290120000000000
> mlb_standings,League=AL,Name=Athletics,host=MBP15-SWANG.local AwayLosses=5,AwayWins=7,City="Oakland",DayLosses=4,DayWins=11,DivisionLosses=5,DivisionWins=15,GamesBehind=0,HomeLosses=4,HomeWins=13,Key="OAK",LastTenGamesLosses=3,LastTenGamesWins=7,Losses=9,NightLosses=5,NightWins=9,Percentage=0.6896551724137931,RunsAgainst=111,RunsScored=144,Season=2020,SeasonType=1,TeamID=24,Wins=20 1598290120000000000
> mlb_standings,League=AL,Name=Astros,host=MBP15-SWANG.local AwayLosses=9,AwayWins=5,City="Houston",DayLosses=7,DayWins=6,DivisionLosses=5,DivisionWins=8,GamesBehind=4.5,HomeLosses=4,HomeWins=10,Key="HOU",LastTenGamesLosses=3,LastTenGamesWins=7,Losses=13,NightLosses=6,NightWins=9,Percentage=0.5357142857142857,RunsAgainst=129,RunsScored=144,Season=2020,SeasonType=1,TeamID=30,WildCardGamesBehind=2,Wins=15 1598290120000000000
> mlb_standings,League=AL,Name=Rangers,host=MBP15-SWANG.local AwayLosses=11,AwayWins=3,City="Texas",DayLosses=8,DayWins=3,DivisionLosses=7,DivisionWins=5,GamesBehind=9,HomeLosses=6,HomeWins=7,Key="TEX",LastTenGamesLosses=8,LastTenGamesWins=2,Losses=17,NightLosses=9,NightWins=7,Percentage=0.37037037037037035,RunsAgainst=147,RunsScored=101,Season=2020,SeasonType=1,TeamID=28,WildCardGamesBehind=6.5,Wins=10 1598290120000000000
> mlb_standings,League=AL,Name=Mariners,host=MBP15-SWANG.local AwayLosses=11,AwayWins=4,City="Seattle",DayLosses=6,DayWins=5,DivisionLosses=14,DivisionWins=9,GamesBehind=9.5,HomeLosses=8,HomeWins=7,Key="SEA",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=19,NightLosses=13,NightWins=6,Percentage=0.36666666666666664,RunsAgainst=162,RunsScored=124,Season=2020,SeasonType=1,TeamID=13,WildCardGamesBehind=7,Wins=11 1598290120000000000
> mlb_standings,League=AL,Name=Angels,host=MBP15-SWANG.local AwayLosses=11,AwayWins=4,City="Los Angeles",DayLosses=8,DayWins=4,DivisionLosses=14,DivisionWins=8,GamesBehind=11,HomeLosses=9,HomeWins=5,Key="LAA",LastTenGamesLosses=8,LastTenGamesWins=2,Losses=20,NightLosses=12,NightWins=5,Percentage=0.3103448275862069,RunsAgainst=162,RunsScored=131,Season=2020,SeasonType=1,TeamID=21,WildCardGamesBehind=8.5,Wins=9 1598290120000000000
> mlb_standings,League=NL,Name=Cubs,host=MBP15-SWANG.local AwayLosses=2,AwayWins=5,City="Chicago",DayLosses=5,DayWins=5,DivisionLosses=7,DivisionWins=11,GamesBehind=0,HomeLosses=8,HomeWins=12,Key="CHC",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=10,NightLosses=5,NightWins=12,Percentage=0.6296296296296297,RunsAgainst=118,RunsScored=122,Season=2020,SeasonType=1,TeamID=9,Wins=17 1598290120000000000
> mlb_standings,League=NL,Name=Cardinals,host=MBP15-SWANG.local AwayLosses=6,AwayWins=4,City="St. Louis",DayLosses=4,DayWins=5,DivisionLosses=5,DivisionWins=7,GamesBehind=3,HomeLosses=2,HomeWins=5,Key="STL",LastTenGamesLosses=5,LastTenGamesWins=5,Losses=8,NightLosses=4,NightWins=4,Percentage=0.5294117647058824,RunsAgainst=59,RunsScored=68,Season=2020,SeasonType=1,TeamID=31,WildCardGamesBehind=0,Wins=9 1598290120000000000
> mlb_standings,League=NL,Name=Reds,host=MBP15-SWANG.local AwayLosses=8,AwayWins=6,City="Cincinnati",DayLosses=4,DayWins=1,DivisionLosses=7,DivisionWins=5,GamesBehind=5.5,HomeLosses=7,HomeWins=5,Key="CIN",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=15,NightLosses=11,NightWins=10,Percentage=0.4230769230769231,RunsAgainst=117,RunsScored=106,Season=2020,SeasonType=1,TeamID=2,WildCardGamesBehind=2.5,Wins=11 1598290120000000000
> mlb_standings,League=NL,Name=Brewers,host=MBP15-SWANG.local AwayLosses=9,AwayWins=9,City="Milwaukee",DayLosses=3,DayWins=4,DivisionLosses=9,DivisionWins=7,GamesBehind=5.5,HomeLosses=6,HomeWins=2,Key="MIL",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=15,NightLosses=12,NightWins=7,Percentage=0.4230769230769231,RunsAgainst=130,RunsScored=104,Season=2020,SeasonType=1,TeamID=32,WildCardGamesBehind=2.5,Wins=11 1598290120000000000
> mlb_standings,League=NL,Name=Pirates,host=MBP15-SWANG.local AwayLosses=8,AwayWins=2,City="Pittsburgh",DayLosses=6,DayWins=4,DivisionLosses=8,DivisionWins=6,GamesBehind=8.5,HomeLosses=9,HomeWins=5,Key="PIT",LastTenGamesLosses=6,LastTenGamesWins=4,Losses=17,NightLosses=11,NightWins=3,Percentage=0.2916666666666667,RunsAgainst=133,RunsScored=102,Season=2020,SeasonType=1,TeamID=4,WildCardGamesBehind=5.5,Wins=7 1598290120000000000
> mlb_standings,League=NL,Name=Braves,host=MBP15-SWANG.local AwayLosses=8,AwayWins=6,City="Atlanta",DayLosses=2,DayWins=4,DivisionLosses=7,DivisionWins=12,GamesBehind=0,HomeLosses=4,HomeWins=10,Key="ATL",LastTenGamesLosses=5,LastTenGamesWins=5,Losses=12,NightLosses=10,NightWins=12,Percentage=0.5714285714285714,RunsAgainst=123,RunsScored=145,Season=2020,SeasonType=1,TeamID=26,WildCardGamesBehind=0,Wins=16 1598290120000000000
```

Flux:
```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "mlb_standings")
  |> filter(fn: (r) => r._field == "RunsScored" or r._field == "RunsAgainst" or r._field == "Percentage")
  |> last()
  |> drop(columns: ["_start", "_stop", "GlobalTeamID", "_measurement", "host"])
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> group()
  |> sort(columns: ["Percentage"], desc: false)
```

**Comment by russorat** [comment] 2020-10-07 19:35
@jackdry So it looks like we have added the ability to customize the x-axis via the config panel for scatter plot. does this address your issue?

![image](https://user-images.githubusercontent.com/4805997/95378934-83d93200-0899-11eb-9eb7-afa4a1a311c3.png)

**Comment by Palakp41** [comment] 2020-11-16 21:11
Closing this issue since it has been fixed by: https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/ui/192

**Closed by Palakp41** 2020-11-16 21:11 UTC
Labels: kind/bug, severity/sev-3, team/monitoring
