### ISSUE TITLE
Cluster Setup 

### ISSUE THREAD

**Issue by jgerschk** [influxdata/influxdb#5585] opened 2016-02-09 00:44 UTC
Working on testing some cluster setups for our environment and having a hard time understanding why I only see one data_node when doing show servers

I see three meta_nodes

> show servers
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8086  172.18.48.54:8088

name: meta_nodes
----------------
id      http_addr               tcp_addr
1       172.18.48.54:8091       172.18.48.54:8088
2       172.18.48.55:8091       172.18.48.55:8088
3       172.18.48.56:8091       172.18.48.56:8088

within the [data] section on each node it is setup to true

The thing I am not sure about is the documentation, it states

For each node’s /etc/influxdb/influxdb.conf file, replace each of the following paramaters:
Under the [meta] section, set the bind-address parameter to <hostname>:8088. For example, influx1’s meta bind-address value will be set to influx1:8088.
Under the [meta] section, set the http-bind-address parameter to <hostname>:8091. For example, influx1’s meta http-bind-address value will be set to influx1:8091.

however, within the [meta] section there is NO http-bind-address parameter to change -- so I added it there.

here are the contents of peers.json

["172.18.48.56:8088","172.18.48.54:8088","172.18.48.55:8088"]

I know it has to be me that is FUBARing it.  Suggestions?

This is .10 as well.

**Comment by rossmcdonald** [comment] 2016-02-09 03:23
@jgerschk I believe the issue is that the data `http` address is using `localhost:8086` as the bind address, which is confusing the meta-service (since I'm assuming all of the servers are reporting themselves as `localhost`). In your configuration, can you try setting the http bind address explicitly? For example, on the node you pasted above, this would look like:

```
[http]
bind-address = "172.18.48.54:8086"
```

**Comment by jgerschk** [comment] 2016-02-09 03:37
@rossmcdonald I think you are right.  The docs are not clear here.

It seems like within the [http] section you need to modify those values for the bind-address as well as within the [meta] section.

so basically I removed everything.  modified the configuration for each to read like the config in examples in #5461 

So basically I have now

[meta]
 bind-address = "host01:8088"
 http-bind-address = "host01:8091"

[http]
 bind-address = "host01:8086"

repeat that for 02, and 03 nodes.

The docs really did not make that clear, it only seem to state you needed to change [meta], and I think that is wrong based on my results.  Now I show all the severs correctly, and data is flowing between them correctly.

So I think this could be turned into a PR maybe to update the docs for clusters?

Off topic, is there some document that explains how distribution of queries work in a cluster?

Thanks for the help @rossmcdonald !

**Comment by xiii** [comment] 2016-02-09 12:06
@jgerschk I just had the same confusion too!

**Comment by netixen** [comment] 2016-02-09 12:37
This behaviour is new with 0.10.x.
Right now if you want your cluster to interconnect through a private network while still having the data node http api exposed to a public network, You will have to start the cluster with the [http] bind-address set to a private net ip, then once the cluster is connected bring it down and switch the [http] bind-address to a public ip.

**Comment by rossmcdonald** [comment] 2016-02-09 15:52
It looks like the issue has been fixed from the docs side with this PR (merged already):

https://github.com/influxdata/docs.influxdata.com/pull/215

The update is not live yet, though, but should be updated later today. Regarding:

> Off topic, is there some document that explains how distribution of queries work in a cluster?

Unfortunately not that I'm aware of. I've created this issue: 

https://github.com/influxdata/docs.influxdata.com/issues/220

So that we can track having one added, though.

**Closed by rossmcdonald** 2016-02-09 15:52 UTC
Labels: category/clustering

**Comment by jgerschk** [comment] 2016-02-09 20:45
@rossmcdonald Thank you for the information on both, the documentation being updated on the cluster setup and the new issue for details on how queries work within clusters, etc.

**Comment by shanab** [comment] 2016-02-12 09:56
I had the same problem, but after editing the `bind-address` under `[http]` I am not able to run `influx` CLI anymore. I also tried running:
```
influx -host <hostname>
```
But it didn't work either.

**Comment by shanab** [comment] 2016-02-12 10:13
Never mind. Not sure what I was doing wrong but now it's working.

**Comment by andrey-moor** [comment] 2016-02-17 04:52
I have the same problem: if I don't setup http binding address I see only meta nodes, if I set it up the influx console is unavailable as well as public API. Any plan to mitigate this?

**Comment by rossmcdonald** [comment] 2016-02-17 16:26
@andrey-moor The `[http]` `bind-address` has to be explicitly set with the machine hostname or IP in order to cluster nodes successfully. We are planning on making clustering easier to deploy with future releases, but for 0.10.0 it's a requirement.

Regarding:

> if I set it up the influx console is unavailable as well as public API

If you bind the listening sockets to specific IP's or hostnames, then the API may be unreachable through `localhost` depending on your setup. Specifying the IP/hostname that the service is bound to should bypass this issue.
