### ISSUE TITLE
[0.9.5] multiple `OR tag` clauses return the results from only one clause

### ISSUE THREAD

**Issue by Advoskr** [influxdata/influxdb#4917] opened 2015-11-26 11:31 UTC
Hi! 

I've been tested some Influx quieries and found that OR operator works incorrectly when applied many times to one field.

First of all, i have a series with some points
![image](https://cloud.githubusercontent.com/assets/12170766/11421943/fd61a46a-9448-11e5-824f-a9ade21d1b64.png)

And perform Select for it with AND operator to select specific time range:
Select * from MeasurementEvent where SensorAlias='S1' and (time>3 and time<6)
![image](https://cloud.githubusercontent.com/assets/12170766/11421973/49af3fe4-9449-11e5-9bab-2d8755bcd098.png)

Works well! But when i want to find points, which are out if this range i get very strange result:
Select * from MeasurementEvent where SensorAlias='S1' and (time<3 OR time>6)
![image](https://cloud.githubusercontent.com/assets/12170766/11422021/a9c9c534-9449-11e5-9acf-872d29bc954f.png)

Also, this bug(is it?) affects quieries like this:
Select * from MeasurementEvent where SensorAlias='S1' and (time=3 or time=4)
![image](https://cloud.githubusercontent.com/assets/12170766/11422092/3d938cbe-944a-11e5-9dd0-f7beffff958e.png)

And the last one is really critical to me, since Influx now doesn't support nor join, neither merge.

**Comment by beckettsean** [comment] 2015-11-30 20:05
This is quite possibly related to https://github.com/influxdb/influxdb/issues/3290.

**Comment by beckettsean** [comment] 2015-12-02 01:49
@rkuchan can you repro with 0.9.5?

**Comment by rkuchan** [comment] 2015-12-02 18:07
I'm able to repro with 0.9.5.1:

```
> SELECT water_level FROM h2o_feet WHERE location='santa_monica' AND time = '2015-08-18T00:06:00Z'
name: h2o_feet
--------------
time			water_level
2015-08-18T00:06:00Z	2.116

> SELECT water_level FROM h2o_feet WHERE location='santa_monica' AND time = '2015-08-18T00:12:00Z'
name: h2o_feet
--------------
time			water_level
2015-08-18T00:12:00Z	2.028

> {er_level FROM h2o_feet WHERE location='santa_monica' AND (time = '2015-08-18T00:06:00Z' OR time = '2015-08-18T00:12:00Z')
name: h2o_feet
--------------
time			water_level
2015-08-18T00:12:00Z	2.028
```

**Comment by beckettsean** [comment] 2015-12-02 20:52
@benbjohnson another one for the rework of the query engine

**Comment by maksimru** [comment] 2016-01-24 16:28
"OR" within time query doesnt work:

SELECT MEAN(price) as avg_price FROM symbol_history where symbol_id = '142' and ((time > 1451053800s and time < 1451077200s)) group by time(1d)

Returns:

{"results":[{"series":[{"name":"symbol_history","columns":["time","avg_price"],"values":[["2015-12-25T14
:30:00.000000001Z",202.22999999998783]]}]}]}


SELECT MEAN(price) as avg_price FROM symbol_history where symbol_id = '142' and ((time > 1451053800s and time < 1451077200s) or (time > 1451313000s and time < 1451336400s)) group by time(1d)

Returns:

{"results":[{}]}

Expected more results than in the first query

**Comment by jsternberg** [comment] 2016-03-15 19:01
Closing this since it seems to be a duplicate of #3290. #5152 represents a bug with dealing with tags (which this issue seems to allude to, but doesn't give a working example). I'm going to leave #5152 open since it has a reproducer I can use.

In summary, there are two issues. One is with multiple time intervals and the other is when you mix tag and field conditions using `OR`.

**Closed by jsternberg** 2016-03-15 19:01 UTC
Labels: category/queries, support
