### ISSUE TITLE
Bad TIMESTAMP on LAST(*), but good data

### ISSUE THREAD

**Issue by skapin** [influxdata/influxdb#8280] opened 2017-04-10 16:51 UTC
__System info:__  1.2.2

Hi, I get a bug with LAST(*)
-> I get the CORRECT value, BUT, the timestamp shown is incorrect.

Example: 
```
curl -G ***** -data-urlencode "q=SELECT last(*) FROM motion where time > (now() - 30m)"

{"results":[{"statement_id":0,"series":[{"name":"motion","columns":["time","last_Head","last_Head_sum","last_KneeLeft","last_KneeLeft_sum","last_KneeRight","last_KneeRight_sum","last_SpineBase","last_SpineBase_sum"],"values":[["2017-04-10T07:29:16.415987682Z",0.0803255330398,698.599190639,0.050377132033,727.684313406,0.0238532125401,721.480931178,0.0354184489207,659.068101473]]}]}]}


$ curl -G **** --data-urlencode "q=SELECT * FROM motion where time > (now() - 30m) ORDER BY DESC LIMIT 1"

{"results":[{"statement_id":0,"series":[{"name":"motion","columns":["time","Head","Head_sum","KneeLeft","KneeLeft_sum","KneeRight","KneeRight_sum","SpineBase","SpineBase_sum","session_id"],"values":[["2017-04-10T07:56:44.282417152Z",0.0803255330398,698.599190639,0.050377132033,727.684313406,0.0238532125401,721.480931178,0.0354184489207,659.068101473,"42w0b0uww3y"]]}]}]}
```

Same value, but bad timestamp :) (same error if add a group by)

**Comment by skapin** [comment] 2017-04-10 16:52
@jsternberg here, for you :)

**Comment by jsternberg** [comment] 2017-04-10 16:54
What's the correct timestamp supposed to be? If there is not time grouping, the timestamp should be the time of the point. Can you give me a reproducer that shows the issue?

**Comment by mathiasvr** [comment] 2017-04-10 17:02
Might be related to #7925

**Comment by jsternberg** [comment] 2017-04-10 17:28
I think I might understand now.

So when you do `last(*)` it expands into multiple calls to `last()`. Since there is more than one selector, the selectors get treated as aggregates and the time, when no time grouping is present, will just be the start time of the interval. So in your example, you'll get a timestamp that is 30 minutes before the current time rather than anything related to the actual time.

I think you can get what you want by doing `last(field), *` instead. You need to choose one and exactly one field value that you want to select.

Does that help?

**Comment by skapin** [comment] 2017-04-10 17:34
Well i dont know. what is can see is i ask for the NEWEST entry (regardless of the field). I guess the correct value (as in exemple) but the timestamp mapped with this value is, like you said, the time stamp of the WHERE, and not the timestamp of the VALUE selected.
Same behavious if i remove the WHERE TIME clause, but the result is event more horrible, i get the EPOCH.

**Comment by skapin** [comment] 2017-04-10 17:35
What i should have is the timestamp of the value selected by LAST, like a basic reading of the query seems to said.

**Comment by jsternberg** [comment] 2017-04-10 17:36
I think the easiest way for you to do that is to do `SELECT * FROM ... LIMIT 1 ORDER BY time DESC`. Using `LAST(*)` won't get you what you want.

**Comment by skapin** [comment] 2017-04-10 18:14
Yes, it's what is used in the example, but I must admit I'it not "instinctif" to know last(*) **** will return an unnapropriate timestamp. Something is or, bad explained, or shoudl be blocked as a bad use case usage. 

Thanks a lot anyway :)

**Comment by jsternberg** [comment] 2017-04-10 18:15
I'll file an issue to improve the documentation around wildcards and functions to help alleviate the confusion. Sorry about that.

I'm going to close this since it's a documentation issue.

**Closed by jsternberg** 2017-04-10 18:15 UTC
