### ISSUE TITLE
RedHat 7 repo error 

### ISSUE THREAD

**Issue by compermisos** [influxdata/influxdb#19716] opened 2020-10-09 18:26 UTC
After last update of the influx db repo (at 2020-10-09 01:02)
Centor 7 don't are capable of access the influxdb repo

__Steps to reproduce:__
1. add yum.repo of influx db
2. exec some yum command (P.E. yum search some, or yum install influxdb)

__Expected behavior:__
Influx db repo config sucefull

__Actual behavior:__
the repo is non accesible

__Environment info:__

* System info:Linux 3.10.0-1127.19.1.el7.x86_64 x86_64
** CentOS Linux release 7.8.2003 (Core)

__Logs:__

failure: repodata/2cc236e28fae3579aecc943c0249fb16c44e11ad-primary.sqlite.bz2 from influxdb: [Errno 256] No more mirrors to try.
https://repos.influxdata.com/rhel/7/x86_64/stable/repodata/2cc236e28fae3579aecc943c0249fb16c44e11ad-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found

```sh
# yum search some

**Comment by gunnaraasen** [comment] 2020-10-09 18:47
Thanks for the report. I can confirm our repo seems to be down right now. Steps to reproduce:

1. Follow the instruction to add the InfluxDB repo to yum, then run `sudo yum install influxdb`

```
...
failure: repodata/repomd.xml from influxdb: [Errno 256] No more mirrors to try.
https://repos.influxdata.com/rhel/2/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

**Comment by gunnaraasen** [comment] 2020-10-09 19:21
We're working on rebuilding the metadata. In the meantime, you can manually change the following line in the `/etc/yum.repos.d/influxdb.repo` file.

```
baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
# to...
baseurl = https://repos.influxdata.com/rhel/8/\$basearch/stable
```

**Comment by gunnaraasen** [comment] 2020-10-09 20:36
This should be fixed now.

**Closed by gunnaraasen** 2020-10-09 20:36 UTC
