### ISSUE TITLE
influx CLI: dreadfully slow; even version command takes 1.5 s CPU time

### ISSUE THREAD

**Issue by wfjm** [influxdata/influxdb#18630] opened 2020-06-21 10:26 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. `docker run ... quay.io/influxdb/influxdb:2.0.0-beta`
2. `docker exec -it influxdbv2 bash`
3. `time influx version`

__Expected behavior:__
That trivial actions are quickly performed

__Actual behavior:__
Every command, even a trivial one, takes 2s CPU time
```
time influx version
  Influx CLI 2.0.0-beta.12 (git: ff620782eb) build_date: 2020-06-21T10:17:39Z
  real    0m2.113s
  user    0m2.134s
  sys     0m0.016s
```

I extracted the `influx` program with `docker cp` and executed it one the same host but outside of the docker container. This gives slightly faster execution times, but still values around 1.6s:
```
time ./influx version
Influx CLI 2.0.0-beta.12 (git: ff620782eb) build_date: 2020-06-21T10:21:30Z
real 0m1.639s   user 0m1.671s   sys 0m0.004s
```

__Environment info:__

* System info: Run `uname -srm`: Linux 5.3.0-51-generic x86_64
* InfluxDB version: Run `influxd version`: Influx CLI 2.0.0-beta.12 (git: ff620782eb)
* Other relevant environment details: Container runtime: docker
* `/proc/cpuinfo`: Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz

**Comment by mark-rushakoff** [comment] 2020-06-27 18:04
I’m closing this as a duplicate of #18292. 

I believe we understand why this is happening, but we haven’t yet fixed it.

**Closed** 2020-06-27 18:04 UTC
