### ISSUE TITLE
Creating a Variable leaves previous variable data in the form

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/influxdb#16371] opened 2019-12-31 16:49 UTC
1. Create variable of map type
1. Save
1. Create another variable - previous variable's data is there
1. Reload - it's cleared out.

**Comment by russorat** [comment] 2020-01-15 23:46
dupe of: https://github.com/influxdata/influxdb/issues/16528

**Closed by russorat** 2020-01-15 23:46 UTC
Labels: kind/bug, regression
