### ISSUE TITLE
Building Influxdb 2.0 on Windows 64 bit

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#19526] opened 2020-09-09 19:13 UTC

**Comment by danxmoran** [comment] 2020-12-22 18:24
Duplicate of #17192

**Comment by Kungitoo** [comment] 2020-12-30 11:13
This would def be nice. What are known issues? I tried doing a naive git clone -> build and see the syscalls need to be swapped to platform agnostic ones among other things like they did here I guess https://github.com/revel/revel/issues/1376

**Comment by danxmoran** [comment] 2021-03-05 00:04
Closing this as a duplicate, please track #17192 for progress

**Closed by danxmoran** 2021-03-05 00:04 UTC
Labels: area/2.x, area/build, area/packaging, duplicate, os/windows
