### ISSUE TITLE
CQ is not  copy all data to new measurement

### ISSUE THREAD

**Issue by maxone** [influxdata/influxdb#3756] opened 2015-08-20 07:57 UTC
Does influxDB support down-sampling all data to a new measurement  and also copying all tags to another one?

My CQ statement  ：
```
CREATE CONTINUOUS QUERY jvm_1m ON hawk 

BEGIN 
     SELECT mean(*)  INTO "hawk"."10y".jvm_1m 
     FROM "hawk"."10y".jvm 
     GROUP BY time(1m),*
END

CREATE CONTINUOUS QUERY jvm_1m ON hawk 

BEGIN 
     SELECT mean(ym) as ym ,mean(mm) as mm  INTO "hawk"."10y".jvm_1m 
     FROM "hawk"."10y".jvm 
     GROUP BY time(1m),*
END

ERR: error parsing query: wildcards can not be combined with other fields
```
I changed the statements since it's not working.

```
CREATE CONTINUOUS QUERY jvm_1m ON hawk 

BEGIN 
     SELECT mean(ym) as ym ,mean(mm) as mm INTO "hawk"."10y".jvm_1m 
     FROM "hawk"."10y".jvm 
     GROUP BY time(1m),application,host 
END

```

Though it's working now but i think it's a better idea to emphasize the semantic of * symbol because fields and tags are usually dynamic.

InfluxDB version: 0.9.2 ,0.9.3-rc

**Comment by beckettsean** [comment] 2015-08-21 22:30
@corylanou is this another representation of #3757 or is there something else going on here?

Did the changes that led to #3757 introduce issues with CQs properly preserving tags?

**Comment by beckettsean** [comment] 2015-08-21 22:32
@maxone CQs should support preserving all tags, but there have been recent changes to how `GROUP BY *` is implemented internally, it may have affected this.

**Comment by corylanou** [comment] 2015-08-22 02:29
This error was added as we currently do not support a wildcard and a field.  It needs to be wired back up.  So rather than allow them to create the CQ we throw an error until it gets wired back up.

Here is the issue that is tracking that it needs to be wired back up.  This is a use case however that isn't in that ticket.  I've updated the ticket to show support for the `GROUP BY time(1m), *`

**Comment by brettdh** [comment] 2015-08-28 14:14
Since it was omitted above: I think the referenced issue is #3582. +1 on implementing that, but that might make this a dupe.

**Comment by brettdh** [comment] 2015-08-28 18:11
Just realized that this breaks documented behavior:

https://influxdb.com/docs/v0.9/query_language/continuous_queries.html

"To preserve all tags in your downsampled data, add a `, *` clause to the `GROUP BY` clause of the continuous query."

This is a fatal regression for us (and probably others). Is there any workaround with 0.9.3? The suggestion of `GROUP BY time(1m), tag1, tag2, tag3` does not work for me; it produces empty tags in the downsampled data, along with a strange new `tag1.tag2.tag3` tag.

**Comment by brettdh** [comment] 2015-08-28 20:27
I missed a detail from the above suggested approach - the measurements in the longer retention policies have different names; e.g. `jvm_1m`. If I do this, the above strange behavior goes away, and I see that the tags are preserved in the downsampled data.

Is it the case that measurements in different retention policies must have different names? If so, creating a continuous query that violates this should fail (and I'm happy to open an issue for that). If not - well, the above behavior still seems odd/buggy.

It was my understanding that two measurements in different retention policies on the same database would be distinct, regardless of their names. Is that correct?

**Comment by beckettsean** [comment] 2015-08-28 20:55
@brettdh I believe that measurements "exist" in all retention policies even if they have no data. We're doing a lot of work on CQs this iteration, I encourage you to open a new issue about this behavior so that we explicitly investigate and have a recommendation or resolution.

**Comment by brettdh** [comment] 2015-09-02 15:27
I think that the `tag1.tag2.tag3` behavior earlier must have been user error. I was forming the CQ with `','.join(...)` in python, and the first thing I checked was whether I had accidentally done `'.'.join(...)` instead. I didn't think I had done that, but I can't reproduce the behavior, and if I do `GROUP BY time(5m), tag1.tag2.tag3`, I get the behavior I described. So I will go ahead and blame that on tired eyes failing to distinguish `,` from `.` for now.

**Comment by zachaller** [comment] 2015-12-23 12:21
Its been a while since this has been updated just wondering if things have changed at all trying to use CQ and not all the data is moving over all the tags move just fine here is my CQ

```
CREATE CONTINUOUS QUERY one_min ON telegraf BEGIN SELECT mean(value) AS \"value\" INTO telegraf.\"1min_rollup\".:MEASUREMENT FROM telegraf.\"default\"./.*/ GROUP BY time(1m), * END"
```

But when i have other values i need something like mentioned above, is there a way to accomplish this in 0.9.6+ like with another special keyword similar to :MEASUREMENT

```
CREATE CONTINUOUS QUERY one_min ON telegraf BEGIN SELECT mean(*) INTO telegraf.\"1min_rollup\".:MEASUREMENT FROM telegraf.\"default\"./.*/ GROUP BY time(1m), * END"
```

here is the columns json response block from the non rolled up rp

```
{
                    "name": "rabbitmq_queue",
                    "columns": [
                        "time",
                        "auto_delete",
                        "consumer_utilisation",
                        "consumers",
                        "durable",
                        "host",
                        "memory",
                        "messages",
                        "messages_ack",
                        "messages_ack_rate",
                        "messages_deliver",
                        "messages_deliver_get",
                        "messages_deliver_get_rate",
                        "messages_deliver_rate",
                        "messages_publish",
                        "messages_publish_rate",
                        "messages_ready",
                        "messages_redeliver",
                        "messages_redeliver_rate",
                        "messages_unack",
                        "node",
                        "queue",
                        "service",
                        "url",
                        "vhost"
                    ],
```

**Comment by beckettsean** [comment] 2015-12-28 22:23
@zachaller there is no wildcard to match fields in a CQ, they must be explicitly mentioned to be included.

**Comment by zachaller** [comment] 2015-12-29 00:47
is there a plan to support this, its pretty crazy to have to list all of them especially with plugins like rabbitmq from telegraph, as well as many others This should be supported in CQ or to provided some sort of easy way to do rollups

**Comment by beckettsean** [comment] 2015-12-29 00:51
@zachaller I'm not sure if there is an open feature request for this. I recommend you open one.

**Comment by beckettsean** [comment] 2016-06-28 18:10
All tags are preserved for CQs when using `GROUP BY *`. 

https://github.com/influxdata/influxdb/issues/6910 exists for automatic downsampling and `*` for field key matching.

Closing this issue.

**Closed by beckettsean** 2016-06-28 18:10 UTC
Labels: category/continuous queries
