### ISSUE TITLE
panic:runtime error: invalid memory address or nil pointer dereference when querying "show tag values" and a "where" clause.

### ISSUE THREAD

**Issue by theory14** [influxdata/influxdb#9598] opened 2018-03-18 17:58 UTC
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

InfluxDB:  1.5.0
OS:  FreeBSD 11.1-RELEASE-p8
InfluxDB installed via pkg

Existing system and database.  Upgraded to 1.5.0 from 1.4.2 via pkg upgrade.

__Steps to reproduce:__

1. Issue a query for "show tag values" with a "where" clause

__Expected behavior:__

The results of the query to be returned as it did with 1.4.2.

__Actual behavior:__

Error is returned:  [panic:runtime error: invalid memory address or nil pointer dereference]

__Additional info:__ [Include gist of relevant config, logs, etc.]

This query works:
```show tag values with key = "host"```
This query fails:
``` show tag values with key = "host" where "dev_type" = 'server' ```
with:
```ERR: SHOW TAG VALUES WITH KEY = host WHERE dev_type = 'server' [panic:runtime error: invalid memory address or nil pointer dereference]```

Stack trace from logs:
```
2018-03-18T17:36:35.205214Z	error	SHOW TAG VALUES WITH KEY = host WHERE dev_type = 'server' OR dev_type = 'vm' [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 8629 [running]:
runtime/debug.Stack(0xc424dff9c0, 0xc42c592000, 0x4c)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/influxdb/query.(*QueryExecutor).recover(0xc420163c50, 0xc424dff9c0, 0xc4220bc600)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/query/query_executor.go:451 +0xaf
panic(0xc89700, 0x12a6b70)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/influxdata/influxdb/tsdb.(*MeasurementFields).HasField(0x0, 0xc427416060, 0x8, 0xc42025f220)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/shard.go:1408 +0x26
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByBinaryExprIterator(0xc4256c6000, 0x2b, 0x39, 0xc42025f220, 0xc42822afe0, 0x9, 0x10, 0xc4224031d0, 0x0, 0x8, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/index.go:1833 +0xcd0
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc4256c6000, 0x2b, 0x39, 0xc42025f220, 0xc42822afe0, 0x9, 0x10, 0xe49f40, 0xc4224031d0, 0x0, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/index.go:1786 +0x424
github.com/influxdata/influxdb/tsdb.IndexSet.seriesByExprIterator(0xc4256c6000, 0x2b, 0x39, 0xc42025f220, 0xc42822afe0, 0x9, 0x10, 0xe49f40, 0xc422403230, 0x0, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/index.go:1763 +0x104
github.com/influxdata/influxdb/tsdb.IndexSet.tagValuesByKeyAndExpr(0xc4256c6000, 0x2b, 0x39, 0xc42025f220, 0xe4d840, 0x12d93e0, 0xc42822afe0, 0x9, 0x10, 0xc42105c3b0, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/index.go:2144 +0x183
github.com/influxdata/influxdb/tsdb.IndexSet.MeasurementTagKeyValuesByExpr(0xc4256c6000, 0x2b, 0x39, 0xc42025f220, 0xe4d840, 0x12d93e0, 0xc42822afe0, 0x9, 0x10, 0xc42105c3b0, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/index.go:2293 +0xb78
github.com/influxdata/influxdb/tsdb.(*Store).TagValues(0xc42008e900, 0xe4d840, 0x12d93e0, 0xc42eab6000, 0x39, 0x40, 0xe49f40, 0xc422402fc0, 0x40, 0x100, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/tsdb/store.go:1517 +0x8d5
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeShowTagValues(0xc4202588c0, 0xc4211da680, 0xc42f06fc50, 0x0, 0x0)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:1066 +0x839
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4202588c0, 0xe4d600, 0xc4211da680, 0x0, 0x3, 0xc4201f4070, 0xc4220bc600, 0xc4220bc6c0, 0xc420edc01c, 0x8, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:194 +0x247a
github.com/influxdata/influxdb/query.(*QueryExecutor).executeQuery(0xc420163c50, 0xc424dff9c0, 0xc420edc01c, 0x8, 0xe4d840, 0x12d93e0, 0x2710, 0x0, 0x0, 0x0, ...)
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/query/query_executor.go:389 +0xaa6
created by github.com/influxdata/influxdb/query.(*QueryExecutor).ExecuteQuery
	/wrkdirs/usr/ports/databases/influxdb/work/influxdb-1.5.0/src/github.com/influxdata/influxdb/query/query_executor.go:285 +0xc3
	{"log_id": "06vYlgbW000", "service": "query"}
```

**Comment by e-dard** [comment] 2018-03-19 12:45
Duplicate of #9548. Will be fixed in the `1.5.1` release.

**Closed by e-dard** 2018-03-19 12:45 UTC
