### ISSUE TITLE
uint64 Support

### ISSUE THREAD

**Issue by chorsington** [influxdata/influxdb#7804] opened 2017-01-09 00:38 UTC
### Feature Request

__Proposal:__ uint64 field value support

Influx uses int64 for the integer field.  This is needed so that the field can support negative values.  However in some cases the value is derived from unsigned (uint64) sources, such as SNMP.

This means Influx can only store up to int64:
- `9223372036854775807`
And there is a common requirement to store up to uint64
- `18446744073709551615`

This has come up in several issues, but has never been well explained:

- [#4250](https://github.com/influxdata/influxdb/issues/4250)
- [#7166](https://github.com/influxdata/influxdb/pull/7166)
- [#6570](https://github.com/influxdata/influxdb/issues/6570)

__Current behavior:__ HTTP 400 error (`unable to parse integer 18446696108828101505: strconv.ParseInt: parsing \"18446696108828101505\": value out of range`)

__Desired behavior:__ The uint64 value is written unchanged, without error to Influx.

How should this be supported?  I see a few options (in rough order of priority):
- Using "math/big" and use big integers, benefits are that the client interface does not change
- The ability to change a field's value type after creation
- On creation determine if it is signed or unsigned (> signed, negative etc...)

__Use case:__

Graphite, Cricket, MRTG and many other solutions store uint64 without the client needing to perform any transformation on the value.  As it stands with Influx, the value needs to be transformed to prior to being written to the database.  This needs to be done by the developer of the client.

Unsigned Integers (uint64) are very common, all 64-bit counters in all network equipment are generally unsigned.  So simply performing a SNMP get and inserting into Influx if the value is greater than 9223372036854775807 is not possible, but is on competing platforms.

__System info:__ 
- InfluxDB Admin UI: v1.0.2 Server: v1.0.2
- influxdb==4.0.0 (Python Client)

**Comment by phemmer** [comment] 2017-01-09 01:07
See also #7801

**Comment by sparrc** [comment] 2017-01-09 10:19
dupe of https://github.com/influxdata/influxdb/issues/7801

**Closed by sparrc** 2017-01-09 10:19 UTC
