### ISSUE TITLE
DELETE does not delete row from series

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/influxdb#14612] opened 2019-08-10 12:16 UTC
OS: CentOS 6.10
Influxdb: 1.7.6

Deleting what should be the first row from a series does not work. In fact, the behaviour is down right bizarre. In some instances the SELECT returns nothing, in others it does. This is crazy.

```
Enter an InfluxQL query
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> DELETE FROM geom_stat WHERE type = 'geom_ops' AND time = 0
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> select from geom_stat where time = 0
ERR: error parsing query: found FROM, expected identifier, string, number, bool at line 1, char 8
> select * from geom_stat where time = 0
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> select * from geom_ops where time = 0
> SELECT * FROM geom_stat WHERE time = 0
> SELECT FIRST(*) FROM geom_stat WHERE time = 0
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> DELETE FROM geom_stat WHERE type = 'geom_ops' AND time = 0
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> DELETE FROM geom_stat WHERE time = 0
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> SELECT FIRST(*) FROM geom_stat
name: geom_stat
time first_delete first_length first_read first_value         first_write
---- ------------ ------------ ---------- -----------         -----------
0    0            0            0          0.06371220172603077 9.199962269114742
> DELETE FROM geom_stat WHERE time < 1
> SELECT FIRST(*) FROM geom_stat WHERE type = 'geom_ops'
name: geom_stat
time first_delete first_length      first_read first_value first_write
---- ------------ ------------      ---------- ----------- -----------
0                 9.399961448878106
> SELECT FIRST(*) FROM geom_stat
name: geom_stat
time first_delete first_length first_read first_value         first_write
---- ------------ ------------ ---------- -----------         -----------
0    0            0            0          0.06371220172603077 9.199962269114742
```

**Comment by jacobmarble** [comment] 2019-09-16 21:40
Duplicate of #14363

**Closed by jacobmarble** 2019-09-16 21:40 UTC
Labels: 1.x

**Comment by jacobmarble** [comment] 2019-09-16 22:05
@yellowpattern I've tried to reproduce, but basic tests all pass. Please share more context (maybe best to share at #14363). Type of index, size of data, show shards output, other retention policies, would be helpful.
