### ISSUE TITLE
Data lost after an update from 2.4 to 2.5

### ISSUE THREAD

**Issue by Koraze** [influxdata/influxdb#23849] opened 2022-11-02 00:26 UTC
Hi,

I lost all my data in my local InfluxDB server (on raspberry) after updating from 2.4 to 2.5, and sadly, I found nothing after an google search.

Do you know how i can recover my data and how to avoid this problem in the future?
Also, do you know where InfluxDB store all his db ?

(I know, I should have made a backup)

__Steps to reproduce:__

1. sudo apt update && sudo apt upgrade
2. sudo reboot now

__Expected behavior:__
I just hopped for a cute update

__Actual behavior:__
InfluxDB seems to forget everything, like a new setup ...

__Environment info:__

* System info: Linux 5.15.0-1017-raspi aarch64
* InfluxDB version: InfluxDB v2.5.0 (git: 6fc66acb0a) build_date: 2022-11-01T16:55:45Z
* Other relevant environment details: The installation was some months ago done with apt (sudo apt install influxdb2)

__Config:__
Ubuntu on Raspberry 4B+

__Logs:__
x
__Performance:__
x

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for ~30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=30s"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz` and `iostat.txt` output files.
```

[profiles.tar.gz](https://github.com/influxdata/influxdb/files/9914801/profiles.tar.gz)
[iostat.txt](https://github.com/influxdata/influxdb/files/9914804/iostat.txt)

**Comment by jules-ch** [comment] 2022-11-02 09:00
I don't know if .deb package is also affected by https://github.com/influxdata/influxdb/issues/23850

**Comment by Delido** [comment] 2022-11-04 13:23
i have the same issue and must restore influx to 2.4, tokens not valid anymore, also cant disable http auth, seems to lost all data. With 2.4 (VM restore) everything is working

**Comment by jeffreyssmith2nd** [comment] 2022-11-07 15:33
@Delido can you try returning to 2.4 and then installing the 2.5.1 release? That should provide a smooth update path.

**Comment by Delido** [comment] 2022-11-07 16:06
@jeffreyssmith2nd Thank you, but not working for me:

![image](https://user-images.githubusercontent.com/20648185/200357552-29d0501f-8e62-41c5-8e8c-cd47f6bb519e.png)

**Comment by jeffreyssmith2nd** [comment] 2022-11-07 19:26
Do you still have data in `/var/lib/influxdb`? And do you have a CLI config in `~/.influxdbv2/configs`? If so, that would at least indicate this is not data loss and instead an error elsewhere.

**Comment by Delido** [comment] 2022-11-07 22:21
okay correct, after upgrade /var/lib/influxdb have the same size also ~/.influxdbv2/configs is present with the same data. so the issue is no data loss. but multiple (every) Auth / Tokens are invalid after Upgrade

**Comment by jeffreyssmith2nd** [comment] 2022-11-08 15:06
How are you actually running influxd? The provided systemd unit or something else?

That `/var/lib/influxd` that you had in 2.4 is wrong. There should be a `influxd.bolt` and `influxd.sqlite` and the `data` `wal` and `replication` folders should have been nested under `engine`, so I'm assuming the default config has been changed somehow.

**Comment by Koraze** [comment] 2022-11-09 11:42
@jeffreyssmith2nd sorry for only replying now.

This trick didn't work for me ... maybe it's because I created a new account and new tokens on the 2.5 ... 

Anyways, even if I'm not very happy about this situation, I only lost 3 months of data.
I fact, I suspected the problem was with the new update so I didn't wait and I posted my probleme here to alert you

**Comment by Delido** [comment] 2022-11-09 19:12
im using default Ubuntu with Influx Repo:
`deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/ubuntu jammy stable`

i found on 2.4 the sqlite and bold file, in a subdirectory:
![image](https://user-images.githubusercontent.com/20648185/200918145-4595ea1c-655a-4177-8414-7d1a22221997.png)
is this not correct? InfluxDB is allmost default config nothing changed, only http / auth 

so i found out, a reboot is working without problems, the Problem is using init.d Script für restarting influx after restart influxdb 2.4 i have the same problem

**Comment by jeffreyssmith2nd** [comment] 2022-11-16 16:16
The folder getting moved to `/var/lib/influxdb/.influxdbv2` would definitely cause the appearance of data loss. Not entirely sure why that happened, I'm going to close this issue out as we've determined data loss is not the problem and add some time to investigate the init.d scripts to make sure the dir is being moved.

**Closed by jeffreyssmith2nd** 2022-11-16 16:16 UTC

**Comment by Nzaca** [comment] 2023-11-21 09:24
Hi , 
I had similar problem  after update . So I newly created file influxd.bold and influx.sqlite in /var/lib/influxdb replace with filese from /var/lib/influxdb/.influxdbv2 , after reboot I can log in to GUI and Grafana can connect to InfluxDB. 
But now the problem is that my old data is missing but it's seems that there are not deleted.
![image](https://github.com/influxdata/influxdb/assets/24225306/e3070279-9b85-4cfd-894c-b9ebe2420189)
![image](https://github.com/influxdata/influxdb/assets/24225306/5960d13a-9b59-426f-8eed-72a5bd6e3a86)
