### ISSUE TITLE
Dashboards issue queries before variables are loaded

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17811] opened 2020-04-21 03:30 UTC
On a dashboard that uses variables, the queries on the dashboards fire before the value for the variable has been loaded. All the queries error and then are re-run with the value of the variable when it returns. 

(ignore the two right most cells) Notice the error blip in the four cells to the left before being rerun.
![Kapture 2020-04-20 at 20 27 13](https://user-images.githubusercontent.com/4805997/79822260-94c2d500-8345-11ea-83f7-ec286f5d442d.gif)

**Comment by drdelambre** [comment] 2020-04-21 21:01
dupe of influxdata/idpe#6675. i can't figure out how to remove the blip and still keep a "please select a variable" in front of the user without it triggering seizures, but working it out.

**Closed by drdelambre** 2020-04-21 21:01 UTC
Labels: kind/bug, severity/sev-4, team/monitoring
