### ISSUE TITLE
Add the ability to rename retention policy

### ISSUE THREAD

**Issue by edbernier** [influxdata/influxdb#9802] opened 2018-05-02 20:11 UTC
### Feature Request

Opening a feature request kicks off a discussion.
Requests may be closed if we're not actively planning to work on them.

__Proposal:__ [Description of the feature]
Extend the current ALTER RETENTION POLICY command to include the ability to rename a retention policy.  See suggested syntax below:
**ALTER RETENTION POLICY <current name> RENAME TO <new name>**

__Current behavior:__ [What currently happens]
Currently there is no way to rename a retention policy.  What you have to do to get around this is to create a new retention policy with the name you want.  Restart data ingest to flow to the new retention policy.  Then SELECT all the records from the existing retention policy INTO the newly created retention policy.  Once all the data has been copied over then DROP the old retention policy.

NOTE: This requires that you have enough room to store the current data twice.

__Desired behavior:__ [What you would like to happen]

1. Pause input traffic
2. ALTER RETENTION POLICY xyz RENAME TO abc
3. Change clients that are writing to or reading from the old retention policy to point to the new retention policy
4. Resume input traffic

__Use case:__ [Why is this important (helps with prioritizing requests)]
It allows an easier ability to change to new naming conventions without requiring lots of extra disk space and the time and resources required to copy the data

**Comment by CAFxX** [comment] 2018-05-03 23:53
Dupe of #8351

**Closed** 2019-07-31 13:29 UTC
Labels: 1.x, kind/feature request, pm/review, wontfix

**Comment by amarbs** [comment] 2022-09-15 05:32
This is an important production requirement.

**Comment by pieter2501** [comment] 2023-03-30 14:46
Basic requirement. Bump!

**Comment by emanuelmanea** [comment] 2023-12-14 09:53
Bump!
