### ISSUE TITLE
storage: some results stop at even thousands

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb#17052] opened 2020-03-01 01:06 UTC
I believe @nathanielc ran into this recently.

Create some data:
```
$ while true; do influx write -o my-org -b my-bucket -t my-token "m f=$RANDOM"; done
```

Count points written so far:
```
$ influx query -t my-token -o my-org 'from(bucket: "my-bucket") |> range(start: -10h) |> count()'
Result: _result
Table: keys: [_start, _stop, _field, _measurement]
                   _start:time                      _stop:time           _field:string     _measurement:string                  _value:int  
------------------------------  ------------------------------  ----------------------  ----------------------  --------------------------  
2020-02-29T15:03:14.224833000Z  2020-03-01T01:03:14.224833000Z                       f                       m                       35391
```

Add a no-op filter to that query:
```
$ influx query -t my-token -o my-org 'from(bucket: "my-bucket") |> range(start: -10h) |> filter(fn: (r) => r._value >= 0) |> count()'
Result: _result
Table: keys: [_start, _stop, _field, _measurement]
                   _start:time                      _stop:time           _field:string     _measurement:string                  _value:int  
------------------------------  ------------------------------  ----------------------  ----------------------  --------------------------  
2020-02-29T15:03:46.459533000Z  2020-03-01T01:03:46.459533000Z                       f                       m                       36287
```

Try a not-quite-no-op filter:
```
$ influx query -t my-token -o my-org 'from(bucket: "my-bucket") |> range(start: -10h) |> filter(fn: (r) => r._value >= 1) |> count()'
Result: _result
Table: keys: [_start, _stop, _field, _measurement]
                   _start:time                      _stop:time           _field:string     _measurement:string                  _value:int  
------------------------------  ------------------------------  ----------------------  ----------------------  --------------------------  
2020-02-29T15:03:26.943410000Z  2020-03-01T01:03:26.943410000Z                       f                       m                       15000
```

Notice result is 15000 (even thousands?).

**Comment by jacobmarble** [comment] 2020-03-01 05:14
Note to self: try to find the offending commit with `git bisect`

**Comment by jacobmarble** [comment] 2020-03-02 18:23
I tried to find the last time the broken query was not broken. When I got back to July 2019, the query fails on a panic inside `query/stdlib` unless the `filter()` function is removed, which defeats the purpose of the bug.

**Comment by jacobmarble** [comment] 2020-03-02 21:59
These screenshots illustrate the ReadFilterRequest argument fields passed to ReadFilter with Flux filter predicate `filter(fn: (r) => r._value >= 1)` vs `>= 0`. The only difference at the ReadFilter call is that filter value. Still need to inspect what the cursor returns, which is a little harder.

![Screen Shot 2020-03-02 at 10 43 19 AM](https://user-images.githubusercontent.com/622263/75709382-6561e700-5c77-11ea-9a08-77ff31c83c18.png)

![Screen Shot 2020-03-02 at 10 43 51 AM](https://user-images.githubusercontent.com/622263/75709378-63982380-5c77-11ea-9693-6155d024d7ee.png)

**Comment by benbjohnson** [comment] 2020-03-20 16:25
Update: Successfully reproduced the issue. I'm digging into the cursor code. My hypothesis right now is that it is either 1) Flux is not continuing to fetch data from the cursor for some reason, or 2) the TSM cursor stops prematurely. The TSM code is pretty well used so I would doubt it is that.

The even thousands seems to be from the fact that the cursors return data in chunks of `tsm1.MaxPointsPerBlock` (which is `1000`).

**Comment by benbjohnson** [comment] 2020-04-03 20:01
Fixed by https://github.com/influxdata/influxdb/pull/17610

**Closed** 2020-11-27 17:40 UTC
Labels: v2-prod-bug
