### ISSUE TITLE
Cursor in script editor mode (flux) cannot go to end of the line

### ISSUE THREAD

**Issue by blvermeu** [influxdata/influxdb#18272] opened 2020-05-28 09:21 UTC
Hi all,

**System:**
-Linux mint virtual machine (6 xeon cores, 12gb memory)
-telegraf, mqtt broker, influxdb 2.0 and grafana all latest versions recently (+/- 3 weeks) installed on the VM

**BACKGROUND:** For the past couple of weeks I have been learning up on the entire flux quering in my influxdb 2.0 database (I have some MQTT feeds from my solar production and my energy meter). That has been working beautifully and managed to get several sorts of math calculations / joins etc.

**ISSUE:** Now my problem, yesterday, when adding a new cell to my panel (in influxdb 2.0), suddenly the cursor in the script editor mode inside the querying field lagged 1, 2 or 3 characters behind, meaning that i cannot select until the end of each row and when I insert a character, it does not get inserted at the place of the cursor but 1 to 3 places behind my cursor. You can also see visually that, the further you go down each line, the cursor is not aligned with the text anymore (cfr pictures below).

I then checked my other cells that were working fine up to that moment, and the issues also presented it on the other cells. The issue did not go away when deleting the cell I was working in. It was also present when editing on a different machine and after restarting the virtual machine, or after restarting influxdb.

The issues is not constant for each line and even not within one line of text (the first characters of each line typically do not seem to have the issue).

Below I have inserted a picture of a piece query, before and after a dash, at the place of the cursor.

![before space](https://user-images.githubusercontent.com/14003666/83122994-b6e20c80-a0d4-11ea-8bd2-339a1edebda4.png)

![after space](https://user-images.githubusercontent.com/14003666/83123014-bfd2de00-a0d4-11ea-8fb5-4feda2b7b779.png)

I really hope someone can assist with this issue, because it is really hard working in this way.

Thank you for reading!

KR,

Ben

**Comment by nathanielc** [comment] 2020-05-28 20:24
@desa or @bthesorceror either of you have ideas on this one?

**Comment by desa** [comment] 2020-05-28 20:59
@blvermeu which browser is this in? We have https://github.com/influxdata/influxdb/issues/18159 and https://github.com/influxdata/influxdb/issues/18026

**Comment by desa** [comment] 2020-05-28 21:07
I'll bump this is priority because it seems like people are hitting it fairly frequently

**Comment by blvermeu** [comment] 2020-05-29 06:53
Hi all,

> @blvermeu which browser and OS are you using? We have #18159 and #18026
The issue is present on windows 10, on 3 different computers, using chrome (Version 80.0.3987.132 (Official Build) (64-bit))
The issue is **not** present on linux mint, using either chrome or firefox.
Internet explorer does not seem to work on any computer.

Hopefully this can be sorted out, because very difficult to edit in this mode! :-)

Thank you all,

kind regards,

Ben

**Comment by desa** [comment] 2020-05-29 22:01
duplicate of https://github.com/influxdata/influxdb/issues/18026

**Closed by desa** 2020-05-29 22:01 UTC
Labels: kind/bug, severity/sev-3, team/monitoring
