### ISSUE TITLE
Script Editor state referring to invalid state when using option type

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/influxdb#16916] opened 2020-02-19 00:47 UTC
![image](https://user-images.githubusercontent.com/17263167/74790984-14f98b00-526e-11ea-896f-ce28d7724ac1.png)

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. open up script editor
2. type in `option vv = { r: "threeve" }` (or something to this effect)
3. delete line created in step 2
3. submit query

__Expected behavior:__
expected query to work as expected. 

__Actual behavior:__
Recieve an error: `type error 13:1-13:6: undefined identifier "optio"`.  

<details><summary>request body</summary>

notice the end of the query has `optio` tacked on:

```json
{
	"query": "from(bucket: \"candles\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"BTC\")\n  |> filter(fn: (r) => r._field == \"close\")\n  |> filter(fn: (r) => r.cur == \"USD\")\n\noptio",
	"extern": {
		"type": "File",
		"package": null,
		"imports": null,
		"body": [
			{
				"type": "OptionStatement",
				"assignment": {
					"type": "VariableAssignment",
					"id": {
						"type": "Identifier",
						"name": "v"
					},
					"init": {
						"type": "ObjectExpression",
						"properties": [
							{
								"type": "Property",
								"key": {
									"type": "Identifier",
									"name": "timeRangeStart"
								},
								"value": {
									"type": "UnaryExpression",
									"operator": "-",
									"argument": {
										"type": "DurationLiteral",
										"values": [
											{
												"magnitude": 6,
												"unit": "h"
											}
										]
									}
								}
							},
							{
								"type": "Property",
								"key": {
									"type": "Identifier",
									"name": "timeRangeStop"
								},
								"value": {
									"type": "CallExpression",
									"callee": {
										"type": "Identifier",
										"name": "now"
									}
								}
							}
						]
					}
				}
			}
		]
	},
	"dialect": {
		"annotations": [
			"group",
			"datatype",
			"default"
		]
	}
}
```

</details>

When submitting this query before throwing in the `option`, it worked as expected, after I added the `option` I started getting this error repeatedly.

__Environment info:__
* macos
* firefox 72.0.2

**Comment by drdelambre** [comment] 2020-03-02 18:32
dupe of #17041 , but just finding it now

**Closed by drdelambre** 2020-03-02 18:32 UTC
Labels: kind/bug, team/monitoring
