### ISSUE TITLE
Display legend is mixing colors on each row

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb#17281] opened 2020-03-15 22:08 UTC
The orange row is not all in the same row. The value is row 3 but the geo_desc is row 1.

![image](https://user-images.githubusercontent.com/4805997/76711583-affb4e80-66ce-11ea-9117-0e30e595e712.png)

**Comment by desa** [comment] 2020-05-29 22:05
duplicate of https://github.com/influxdata/influxdb/issues/17253

**Closed by desa** 2020-05-29 22:05 UTC
Labels: kind/bug, regression, severity/sev-3, team/monitoring
