### ISSUE TITLE
Program is nested too deep 

### ISSUE THREAD

**Issue by denney** [influxdata/influxdb#25390] opened 2024-09-25 07:56 UTC
![image](https://github.com/user-attachments/assets/c3524547-a14f-42c1-8125-6eb7dc4cfcd3)

**Comment by mgattozzi** [comment] 2024-09-26 14:33
Closed as a duplicate of https://github.com/influxdata/influxdb/issues/24029 which you also seemed to have found. If you have any context to add beyond just the error message please add it there.

**Closed by mgattozzi** 2024-09-26 14:33 UTC
