### ISSUE TITLE
There are some issues using both GROUP BY and ORDER BY DESC at the same time.

### ISSUE THREAD

**Issue by ygtzf** [influxdata/influxdb#7308] opened 2016-09-14 10:03 UTC
Hi,

First of all, please forgive my poor English.

I find some issues when using both GROUP BY and ORDER BY DESC at the same time.

It's **OK** when using **GROUP BY time intervals**  and **ORDER BY DESC** at the same time.

**But** it's may be have some issues if using **GROUP BY tag values AND a time interval** and **ORDER BY DESC** at the same time.

**Influxdb version:** 0.13.0
**system info:** Ubuntu 14.04.3 LTS

The commands I used:

1、 The next is **OK**:
```
> select mean(value) from system_cpu where host='dev1' and type_instance='cpu.idle' and time > 1473708540s and time < 1473733700s group by instance,time(7h);
name: system_cpu
tags: instance=0
time                    mean
----                    ----
2016-09-12T16:00:00Z    74.78770643626872
2016-09-12T23:00:00Z    76.18501076709741
  
name: system_cpu
tags: instance=1
time                    mean
----                    ----
2016-09-12T16:00:00Z    75.66244139851084
2016-09-12T23:00:00Z    76.53989406177087
```
2、The next may be **NOT CORRECT** (the result is seem to **double**):
```
> select mean(value) from system_cpu where host='dev1' and type_instance='cpu.idle' and time > 1473708540s and time < 1473733700s group by instance,time(7h) order by desc;
name: system_cpu
tags: instance=1
time                    mean
----                    ----
2016-09-12T23:00:00Z    77.45797279090078
2016-09-12T16:00:00Z    75.66244139851085
  
name: system_cpu
tags: instance=0
time                    mean
----                    ----
2016-09-12T23:00:00Z    76.18501076709751
2016-09-12T16:00:00Z
  
name: system_cpu
tags: instance=1
time                    mean
----                    ----
2016-09-12T23:00:00Z    76.16853637358352
2016-09-12T16:00:00Z

name: system_cpu
tags: instance=0
time                    mean
----                    ----
2016-09-12T23:00:00Z
2016-09-12T16:00:00Z    74.78770643626864
```

I don't know why is it such a result.

Thanks!

**Comment by jsternberg** [comment] 2016-09-14 13:38
Do you have a reproducer you can give us? Also, what is the output of `SHOW SHARDS` for the database you were querying? Finally, can you try this same thing on InfluxDB 1.0 and tell me if it still happens? Thanks.

**Comment by jsternberg** [comment] 2016-09-22 18:47
I'm going to close this since we don't have enough information to reproduce the issue. Please try the latest version and see if the issue still happens. If you are still having an issue, please give us the above information and I'll reopen this issue. Thanks.

**Closed by jsternberg** 2016-09-22 18:47 UTC
Labels: area/queries, kind/bug, need more info
