### ISSUE TITLE
Investigate higher disk i/o utilization on 1.4.2.

### ISSUE THREAD

**Issue by rbetts** [influxdata/influxdb#9201] opened 2017-12-05 18:06 UTC
- Not yet able to reproduce higher io util. WIP.

**Comment by szibis** [comment] 2017-12-05 20:18
I have this issue I have the same high number of reads and writes. Previously an only high number of writes. This is very bad and I get 30% of IO wait right now.

I can add more IOPS but before 1.4.2, on 1.3.6 it was enough.

**Comment by jwilder** [comment] 2017-12-05 20:38
@szibis How many CPU cores do you have available and also how many IOPS can your disks support?

**Comment by szibis** [comment] 2017-12-05 21:39
Using m4 instances on AWS - 16 cores. Additional GP2 EBS with 3TB size. Traffic about 60k+ req writes per second.

Currently using twice much memory then on 1.3.6 - about 50-58GB.

**Comment by jwilder** [comment] 2017-12-06 15:06
@szibis Since you have 16 cores or more, can you try setting:
```
[data]
cache-snapshot-memory-size = 1073741824
max-concurrent-compactions = 4
```

You may need to increase `cache-max-memory-size = 2147483648` or higher if it's still the default.   This won't resolve the issue fully, but should reduce disk util a bit.  You can also experiment with setting `max-concurrent-compactions` as low as `2`, but you'll need to monitor the compaction backlog to make sure it is still keeping up over time.

**Comment by jwilder** [comment] 2017-12-07 17:07
@szibis I have merged a fix to master and 1.4 branch.  If you are able to test it out, that would be great.

**Comment by szibis** [comment] 2017-12-07 18:26
This is available as nightly build or I need to build the package on my own?

**Comment by jwilder** [comment] 2017-12-07 18:31
@szibis If you want to test the nightly, it should be in there tonight. That is based off of master/1.5 though.  The current nightly is using fd11e200c8b2e4d23c31945e330b2768b83d46f5.  Testing off of 1.4, you would need to build off of the 1.4 branch.

**Comment by szibis** [comment] 2017-12-07 21:58
Using this version:
```
influxd version
InfluxDB v1.4.2 (git: 1.4 50063f9ecdab80f3b1afc5ad36dff0e2c5e9cdee)
```
I just set as you suggested
```
cache-snapshot-memory-size = 1073741824
max-concurrent-compactions = 4
```
On influxdb 1.3.6 before config changes
![image](https://user-images.githubusercontent.com/329831/33739631-0de51c24-db9e-11e7-9c46-a8615339634a.png)

On influxdb 1.4.2 after fixes in code and config changes
![image](https://user-images.githubusercontent.com/329831/33740599-869a1428-dba1-11e7-971f-f2a1c72536a2.png)

Looks better on iowait. It is low now.
![image](https://user-images.githubusercontent.com/329831/33740645-a44b3524-dba1-11e7-9bf4-856df73943c9.png)
Previously before problems
![image](https://user-images.githubusercontent.com/329831/33740731-f2913f58-dba1-11e7-8f0b-49195122b507.png)

Waiting for some long interval stats.

**Comment by jwilder** [comment] 2017-12-07 22:03
@szibis I just realized that, if you set `cache-snapshot-memory-size = 1073741824`, you will also need to bump up `cache-max-memory-size` to something higher than `1073741824` (the default).  Setting it to 2 or 3gb might be appropriate for you.  That will prevent getting `cache-max-memory-size` limit errors on writes when the cache fills up.

If you are running the change in 1.4, you shouldn't need the config changes though.  I suggested those as a workaround for 1.4.2 in lieu of the fixes.

**Comment by szibis** [comment] 2017-12-07 23:07
Yes, I use this bumped from the beginning.
```
cache-max-memory-size = 3048576000
```
I will keep them changed.

Thx, for fix and help.

**Comment by lpic10** [comment] 2017-12-08 10:55
@jwilder I also can see a big improvement over previous nightly builds. I had noticed this bump in disk i/o when going from version 1.3 to version 1.4+

![cpu](https://user-images.githubusercontent.com/11616752/33762572-4d413ba4-dc0d-11e7-9b67-feabbea66fd8.png)
![diskio](https://user-images.githubusercontent.com/11616752/33762573-4d725356-dc0d-11e7-8e25-90eaa1a117dc.png)
![diskio2](https://user-images.githubusercontent.com/11616752/33762574-4d8b0608-dc0d-11e7-8c8e-35dca3a15bb7.png)
![diskio3](https://user-images.githubusercontent.com/11616752/33762575-4da76c62-dc0d-11e7-8e50-5d332b517f89.png)

**Comment by jwilder** [comment] 2017-12-08 15:34
@lpic10 Thanks for the update.  What do you have set for `cache-snapshot-memory-size`?

**Comment by lpic10** [comment] 2017-12-08 15:38
> @lpic10 Thanks for the update. What do you have set for cache-snapshot-memory-size?

I don't have it set, I supposed it is the default value

**Comment by lpic10** [comment] 2017-12-13 15:27
@jwilder not sure related, but I've noticed a big increase in memory consumption since the update (blue mark)

![influxdb-internals](https://user-images.githubusercontent.com/11616752/33946507-4831946a-e022-11e7-8ed2-044907d9a30b.png)

Let me know if you want me to run a profile (or if I should comment or open a different issue).

**Comment by jwilder** [comment] 2017-12-13 15:32
@lpic10 Can you try setting `cache-snapshot-memory-size = "25m"`?  I increased the default it in the fix, but I believe that is the cause of the increased memory usage and will likely need to revert it.

**Comment by szibis** [comment] 2017-12-13 15:36
@jwilder All return to bad state. I/Owaits are now high, number of reads are same as number ow writes with cache-snapshot-memory-size set to ```25m``` OOM's are very frequent and memory usage is high much higher then on 1.3.x

Memory and OOM's:
![image](https://user-images.githubusercontent.com/329831/33946925-5b158ac2-e023-11e7-8657-a841ced81228.png)

IO/wait

![image](https://user-images.githubusercontent.com/329831/33946398-fa3c63de-e021-11e7-8a96-96b18e2e4f19.png)

![image](https://user-images.githubusercontent.com/329831/33946925-5b158ac2-e023-11e7-8657-a841ced81228.png)

IOPS

![image](https://user-images.githubusercontent.com/329831/33947012-9e20b148-e023-11e7-8158-f42ad1d882f9.png)

**Comment by lpic10** [comment] 2017-12-13 15:42
@jwilder I just changed here, tomorrow I give an update

**Comment by jwilder** [comment] 2017-12-13 15:45
@szibis Can you grab some profiles via the `/debug/pprof/all` endpoint?

**Comment by szibis** [comment] 2017-12-13 16:28
We have some bigger amount of measurements right now (1100+) because of some bad reporting issue, but it was on 1.3.x and it was working much better than now on 1.4.x. Removing them is now impossible, even one, by one. Standard number of measurements is under 200.

Every config change and restart takes with such big DB even 30+ minutes.
It is very hard to get this profiles on this box/boxes when InfluxDB is operating or try to operate.

[pprof.contentions.delay.001.pb.gz](https://github.com/influxdata/influxdb/files/1556229/pprof.contentions.delay.001.pb.gz)
[pprof.influxd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/influxdata/influxdb/files/1556230/pprof.influxd.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
[pprof.influxd.samples.cpu.001.pb.gz](https://github.com/influxdata/influxdb/files/1556231/pprof.influxd.samples.cpu.001.pb.gz)

**Comment by jwilder** [comment] 2017-12-13 16:41
@szibis I've attached a build of the current 1.4 branch plus some changes I'm testing to resolve these issues.  Would you be able to try this out and see if it improves your situation?
[influxd.gz](https://github.com/influxdata/influxdb/files/1556277/influxd.gz)

I can push up a branch if you prefer to build the binary yourself.

**Comment by szibis** [comment] 2017-12-13 17:00
Testing on one node.

**Comment by szibis** [comment] 2017-12-14 09:53
Looks better

![image](https://user-images.githubusercontent.com/329831/33986050-b1bca8da-e0bc-11e7-9283-65126923b9cd.png)

![image](https://user-images.githubusercontent.com/329831/33986097-d9d09aca-e0bc-11e7-8839-14b46be591e0.png)

**Comment by lpic10** [comment] 2017-12-15 08:36
After changing to `cache-snapshot-memory-size = "25m"` made the memory usage look a bit more stable, but still much higher than before. 

I'll give a try on next nightly with the latest fixes. 

![influxdb-internals2](https://user-images.githubusercontent.com/11616752/34033644-49b16784-e17b-11e7-937e-1eff3ab513b5.png)

**Comment by jwilder** [comment] 2017-12-15 18:29
@lpic10 @szibis @oiooj I've merge some fixes to 1.4 branch and master.  If any of you are able to test those builds out, that would be really helpful.  You should have `cache-snapshot-memory-size` left commented out in your config w/ these changes so that the default is used.

**Comment by lpic10** [comment] 2017-12-20 09:37
![influxdb-internals3](https://user-images.githubusercontent.com/11616752/34199917-8c041198-e56f-11e7-8d34-8286933d39e6.png)

Trying latest nightly with `cache-snapshot-memory-size` commented, some conclusions for now:
- it is rather stable (just few days, but no crashes, no oom);
- memory consumption is still higher than when this issue was filled, but lower than the initial fix;
- disk utilization is about half of what was when this issue was filled, but higher than the initial fix: it is about ~50 IOPS now, was >150 IOPS initially and ~30 IOPS after the initial fix

Unsurprisingly, changes that has reduced disk IO has increased need for memory, and vice-versa.

**Comment by oiooj** [comment] 2017-12-21 13:54
![image](https://user-images.githubusercontent.com/2253095/34258369-9b3f6c46-e698-11e7-8096-c9fde669729c.png)

![image](https://user-images.githubusercontent.com/2253095/34258397-c25f1fec-e698-11e7-9e2e-1896721e2e8d.png)

![image](https://user-images.githubusercontent.com/2253095/34258427-db410ade-e698-11e7-989a-f5ced58d4bea.png)

Looks good. Compared with v1.2.4 only in `disk.io.util` increased by 2%.
I will upgrade when it release.

**Comment by rbetts** [comment] 2018-01-02 18:04
@jwilder should this be closed?

**Closed** 2018-01-02 18:13 UTC
