### ISSUE TITLE
Tokens tab looks gray and blank if user has no tokens

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb#17181] opened 2020-03-10 19:16 UTC
![Kapture 2020-03-10 at 12 15 14](https://user-images.githubusercontent.com/10937678/76350356-d5e8b380-62c8-11ea-9a4f-a67af0d311f6.gif)

**Comment by Asalem1** [comment] 2020-03-10 19:19
Might be a good place to integrate into the Add Graphics epic (#17152) @alexpaxton

**Comment by desa** [comment] 2020-04-10 19:41
dupe of https://github.com/influxdata/influxdb/issues/17635

**Closed by desa** 2020-04-10 19:41 UTC
Labels: kind/bug, regression, severity/sev-4, team/monitoring
