### ISSUE TITLE
CLI with `format JSON` doesn't output the JSON returned from the API.

### ISSUE THREAD

**Issue by desa** [influxdata/influxdb#7517] opened 2016-10-25 18:31 UTC
### Bug report

**System info:** OSX 1.0+

**Steps to reproduce:**
1. Download the NOAA data `curl https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt -o NOAA_data.txt`
2. Import that NOAA data. `influx -import -path=NOAA_data.txt -precision=s`
3. Using the CLI, run the commands `FORMAT json`, `PRETTY`, and `USE NOAA_water_database`.
4. Issue a `SHOW TAG KEYS` command.
5. Compare the resulting JSON to the results of

```
curl "localhost:8086/query?db=NOAA_water_database&q=show+tag+keys" | jq
```

**Expected behavior:** 
The query should return the same JSON.

**Actual behavior:** 
The CLI outputs

``` json
{
  "results":[
    {
      "series":[
        {
          "name":"average_temperature",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        }]
    },
    {
      "series":[
        {
          "name":"h2o_feet",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        }]
    },
    {
      "series":[
        {
          "name":"h2o_pH",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        }]
    },
    {
      "series":[
        {
          "name":"h2o_quality",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"],
            [
              "randtag"]]
        }]
    },
    {
      "series":[
        {
          "name":"h2o_temperature",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        }]
    }]
}
```

The API outputs

``` json
{
  "results":[
    {
      "series":[
        {
          "name":"average_temperature",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        },
        {
          "name":"h2o_feet",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        },
        {
          "name":"h2o_pH",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        },
        {
          "name":"h2o_quality",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"],
            [
              "randtag"]]
        },
        {
          "name":"h2o_temperature",
          "columns":[
            "tagKey"],
          "values":[
            [
              "location"]]
        }]
    }]
}
```

**Comment by desa** [comment] 2016-10-25 20:30
Also happens with `SHOW FIELD KEYS`.

**Comment by jwilder** [comment] 2016-10-25 21:46
@desa I'm not seeing what is different.  Is is the pretty formatted out that is different?

**Comment by desa** [comment] 2016-10-25 22:14
The CLI outputs 

```
{
  "results":[
    {
      "series":[
      ...
    },
    {
      "series":
      ...
    },
    {
      "series":
      ...
    },
   ...
]
}
```

The API outputs

```
{
  "results":[
    {
      "series":[
       ...
      ]
   }
 ]
}
```

**Comment by desa** [comment] 2016-10-25 22:20
@jwilder it's present in the non-pretty printed version as well.

**Comment by corylanou** [comment] 2016-12-07 17:00
@desa this is actually because the CLI uses chunked responses by default, which is correct as we don't know when they will issue a very large query at the CLI, so we play it safe.  The results are not `incorrect`, just `chunked` into their own individual series due to how we do chunking on the server.

Here is the response if you set chunked to true:

```
$ curl "localhost:8086/query?db=NOAA_water_database&pretty=true&chunked=true&q=show+tag+keys"
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "average_temperature",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "location"
                        ]
                    ]
                }
            ],
            "partial": true
        }
    ]
}
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "h2o_feet",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "location"
                        ]
                    ]
                }
            ],
            "partial": true
        }
    ]
}
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "h2o_pH",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "location"
                        ]
                    ]
                }
            ],
            "partial": true
        }
    ]
}
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "h2o_quality",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "location"
                        ],
                        [
                            "randtag"
                        ]
                    ]
                }
            ],
            "partial": true
        }
    ]
}
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "h2o_temperature",
                    "columns": [
                        "tagKey"
                    ],
                    "values": [
                        [
                            "location"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

Is this causing a problem, or was it unexpected behavior?  If it's causing a problem, let me know, otherwise I'll close this out as it's working as designed.

**Comment by desa** [comment] 2016-12-07 17:13
It was just unexpected behavior. Feel free to close it out.

**Closed** 2016-12-07 17:15 UTC
Labels: area/cli, area/queries, kind/bug
