### ISSUE TITLE
InfluxDB V2 Dashboard formatting error

### ISSUE THREAD

**Issue by jdyoung76** [influxdata/influxdb#18031] opened 2020-05-11 14:37 UTC
Whenever I first open a dashboard, all the data with text seems to be "Too Large" for the containers they are in. 
![Screen Shot 2020-05-11 at 10 31 01 AM](https://user-images.githubusercontent.com/56947193/81573787-f8538780-9372-11ea-9046-9147525ac18f.png)

If I change the size of the browser in someway, then the formatting is mostly fixed excluding any text with characters that fall below the baseline, which seem to get clipped.
![Screen Shot 2020-05-11 at 10 24 44 AM](https://user-images.githubusercontent.com/56947193/81573912-1faa5480-9373-11ea-9e6d-ef98bf719d70.png)

Not an overly big deal, but a small hassle an something that needs to be tidied up.

**Comment by 121watts** [comment] 2020-06-23 22:34
Thanks for writing in!  Looks like this issue may be resolved?

![Kapture 2020-06-23 at 15 33 32](https://user-images.githubusercontent.com/7582765/85472625-f3374a00-b566-11ea-8dd4-5d1bbe33262a.gif)

What about for you?

**Comment by Asalem1** [comment] 2020-12-01 20:21
@jdyoung76 I can't seem to reproduce this. Is it still affecting you or can this be marked as closed?

**Closed** 2021-06-11 21:37 UTC
Labels: kind/bug, severity/sev-4, team/ui
