### ISSUE TITLE
Error when viewing check history

### ISSUE THREAD

**Issue by nathanshiaulam** [influxdata/influxdb#17863] opened 2020-04-24 20:24 UTC
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create enough checks to back up the queues. For me, this was about 60 checks with 1 minute intervals
2. Create a new check, notice that its last run status is Failed.
3. Click on its history to get re-directed to an error page

__Expected behavior:__
Describe what you expected to happen.

A description of the error state so I can resolve it. Also expected it to be able to handle 60+ checks without backing up the queues, so I could use some insight as to what the actual limitations are.

__Actual behavior:__
Describe What actually happened.

Occasionally miss checks because queues get backed up. Certain checks never complete successfully and the history always leads to an error page with "An InfluxDB error has occurred. Please report the issue here"
__Environment info:__

* System info: Run `uname -srm` and copy the output here
* InfluxDB version: Run `influxd version` and copy the output here
* Other relevant environment details: Container runtime, disk info, etc
Linux 4.14.171-136.231.amzn2.x86_64 x86_64
InfluxDB 2.0.0-beta.6 (git: acd09bf0b) build_date: 2020-04-24T20:13:22Z
free -h
              total        used        free      shared  buff/cache   available
Mem:           3.9G        3.1G        116M        412K        696M        1.6G

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in log.

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively happening.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by desa** [comment] 2020-05-29 19:55
@nathanshiaulam would it be possible to get the checks and data that you have so that we can attempt to reproduce this issue.

**Comment by russorat** [comment] 2021-05-20 22:17
i'm going to close this for now since it was opened against a pre-release version of influxdb. if you are still facing this problem, please open a new issue with the details.

**Closed by russorat** 2021-05-20 22:17 UTC
Labels: kind/bug, monitoring-and-alerting, severity/sev-3, team/compute, team/ui
