### ISSUE TITLE
Automatically generating data after deleting all points

### ISSUE THREAD

**Issue by Wapiti08** [influxdata/influxdb#21565] opened 2021-05-26 08:58 UTC
I am using influxdb 2.0.4.

I deleted points in a measurement before. It looks like that all the fields were deleted but the tags were kept. And it is still automatically generating tags. I used to set a scraper but I deleted it. There is no background scripts running as well. I am not sure where the problem is.

**Comment by danxmoran** [comment] 2021-05-26 13:06
Possible duplicate of #20704

**Closed** 2021-06-09 13:11 UTC
Labels: area/2.x, area/storage
