### ISSUE TITLE
Got a 204 response when writing data using HTTP/1.0, but no data is written

### ISSUE THREAD

**Issue by jwlighting** [influxdata/influxdb#8049] opened 2017-02-22 19:57 UTC
### Bug report

__System info:__ InfluxDB version: 1.1; OS: Raspbian Lite on RPi 3

__Steps to reproduce:__

1. Send HTTP/1.0 POST-request with line protocol in request body to the /write endpoint

__Expected behavior:__ Get HTTP Status 204 response and have the new data written, or get a 4xx response when no data is written for whatever reason

__Actual behavior:__ I got the HTTP status 204 response, but no data is written. If the measurement does not exists before the request, it is not created as expected

__Additional info:__ The client is self-written C++ program, using the Poco libraries. Sending the same line protocol with curl succeeded and sending the same request with my own program, but using HTTP/1.1 instead of HTTP/1.0, succeeded either.

**Comment by makareth** [comment] 2017-03-09 08:28
Also seen on Ubuntu 16.04, InfluxDb 0.13.
Can be easily reproduced by creating a DB, adding some measurements, then removing all of them.
Then, although the insert queries through the HTTP API return 204, no data is persisted (SELECT * returns an empty set).

**Comment by lobando** [comment] 2017-04-11 21:22
I see this same behaviour using CURL

**Comment by karanrajpal14** [comment] 2017-06-16 06:22
I'm facing the same issue. Any known fix? I'm able to see the call in the logs but no data in the database.

**Comment by randomeleven** [comment] 2017-07-13 20:56
Had a similar issue until I realized I am sending UNIX timestamps in seconds while explicitly specifying precision as milliseconds in the url.
I am using a python client to send data and I had : 
```
line = "measurement1,tag1=wtevevr field1=10 1499978956"
r=requests.post(url="https://server:8086/write?db=eProbeDB&u=myuser&p=mypass&rp=one_week&precision=ms", data=line, verify = False)

```
Multiplied 1499978956 by 1000 to convert to millis and data started showing in influxdb.
Client is on a Debian 8 machine though, so it's possible that the issue is caused by something else in your case.

**Comment by rigalGit** [comment] 2018-01-17 08:16
@makareth I am also facing same issue with influx db 0.14 .Have you find any solution /fix for this ?

**Comment by yagnasrinath** [comment] 2018-03-09 19:19
I am also facing the same issue, only when I pass retention policy (rp) parameter. Otherwise I see that data is persisted. @makareth Did you find any resolution?

**Comment by yagnasrinath** [comment] 2018-03-09 22:08
I got my issue fixed following @randomeleven suggestion. Added a precision query param to the request.

**Comment by rohithmn3** [comment] 2018-03-20 03:28
Hi @yagnasrinath and @randomeleven ,
I am also facing the same issue, but i am using CURL to push the data to influxdb. Below is my command: 
```
measurement="download_speed,component=java_jdk,landscape=aws duration=10,status=100"
echo "$measurement" >/tmp/curl.input
curl -k -m 30 -i -XPOST $url/write?db=<database_name> -u ${username}:${password} --data-binary @/tmp/curl.input
```
```
Getting the below output:
HTTP/1.1 204 No Content
Server: nginx/1.13.8
Date: Mon, 19 Mar 2018 08:39:28 GMT
Content-Type: application/json
Connection: keep-alive
Request-Id: 057a880f-2b51-22e8-9r45-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.4.2
X-Request-Id: 057a880f-2b51-22e8-9r45-000000000000
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Expires: Sat, 26 Jul 1997 05:00:00 GMT
```
But no data at inluxdb.
Could you guys pls help here..!

Regards,
Rohith

**Comment by yagnasrinath** [comment] 2018-03-20 03:46
@rohithmn3 change the command to 
```
curl -k -m 30 -i -XPOST $url/write?precision=ms&db=<database_name> -u ${username}:${password} --data-binary @/tmp/curl.input
```

**Comment by rohithmn3** [comment] 2018-03-20 07:29
Yup...! 👍

**Closed** 2019-07-31 03:29 UTC
Labels: 1.x, area/HTTP, area/client, wontfix

**Comment by lehecka** [comment] 2020-03-17 21:52
I have experienced the same behavior. I am using InfluxDB on RPi3 and logging temperatures to it from my Arduino. I spent a lot of hours debugging my http connection reliability and experimenting with InfluxDb API. I learned that when the http POST request (/write) arrives to the InfluxDb, the response 204 is generated immediately as soon as the headers arrive, its not waiting for the body with the measurements. When the Content-Length header is missing in the POST request the InfluxDB is not flushing the data to the database. I am guessing its still buffering the data somewhere and waiting for some signal which I didn't figure out.
When I added Content-Length header to my requests everything seems to be working fine.

**Comment by makareth** [comment] 2020-05-17 17:32
@lehecka Hmm, not using InfluxxDb anymore because waiting 3 years for an answer is not possible for production deployments. Bu thank you for your insight !

**Comment by gaquino** [comment] 2021-02-01 19:06
Interesting I am getting the same error (204 0-byte body). In my case, my process started working fine but after a period of 5-10 minutes, all my requests started to return this 204 status + the message 0-byte body and nothing being written to InfluxDB.

The worst for me is that I am using InfluxDB official Cloud.... They cannot blame me to have been setup it wrong. SAD

**Comment by MattMills** [comment] 2021-07-31 03:06
If anyone else finds this thread in Google trying to find the answer and you're doing a weird custom HTTP client, the answer for me was a missing Content-Length header. With no Content Length it was responding 204 but doing nothing.

**Comment by fthiery** [comment] 2022-07-29 22:54
For the record, the **204 code seems to be the normal/expected code** when writing data to influx v1 (https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdb.InfluxDBClient.write).

Following this thread i suspected that data was not being written, but in fact it was; my sensor id got reset and i was not getting any data out of my requests (i'm using rtl_433 as client which is sending Content-Length headers).

**Comment by roscrazy** [comment] 2024-01-14 03:14
I hope this helps others - Somehow my code sent points by batch fixed the issue to me 
Use BatchPoints.builder() instead.

**Comment by ppapla** [comment] 2024-01-16 08:17
```
curl --location 'https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/write?precision=ms&bucket=...' \
--header 'Authorization: Token ...' \
--header 'Content-Type: text/plain' \
--data 'postman test="test" 1705343975825'
```

I'm using postman/curl, and I'm getting 204 without any data inserted to influx
